* 搭建Electron开发环境

** Ubuntu安装Node.js 14

*** 采用NodeSource源
    由于系统默认仓库包含的Node.js版本比较旧，因此需要使用NodeSource的Node.js Binary Distributions源。
    #+begin_src bash
    curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    sudo apt-get install -y nodejs # install Node.js 14.x and npm
    sudo apt-get install gcc g++ make # You may also need development tools to build native addons
    ## To install the Yarn package manager, run:
    curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update && sudo apt-get install yarn
    #+end_src

*** 采用清华NodeSource镜像源(https://mirrors.tuna.tsinghua.edu.cn/)
    若直接采用NodeSource源很慢，那么可以切换到清华的NodeSource镜像。但不现在已经移除了NodeSource的镜像了。

** 通过cnpm安装Electron
   #+begin_src bash
   npm install -g cnpm --registry=https://registry.npm.taobao.org
   cnpm i electron@9.3.2 --save-dev # 最新版在编译SQLite3时有问题。
   #+end_src

** TODO Webpack4 + TypeScript + React + Electron 开发环境
   https://www.jianshu.com/p/3aafab67ff70
   https://archive.jlongster.com/Backend-Apps-with-Webpack--Part-I

*** 不打包node_modules的依赖
    https://github.com/liady/webpack-node-externals
    对于后端服务若不想打包node_modules中的依赖，通过如下形式处理
    1. 安装webpack-node-externals
       #+begin_src bash
       cnpm i webpack-node-externals -D
       #+end_src
    2. webpack.config.js
       #+begin_src js
       import nodeExternals from 'webpack-node-externals'

       module.exports = {
           target: 'electron-main', // or 'node'
           // ......
           externals: [nodeExternals()],
       }
       #+end_src

*** SQLite3的注意事项
    REF: http://ask.sov5.cn/q/TQIF0d9kve

    webpack.config.js
    #+begin_src js
    externals: {
        sqlite3: 'commonjs sqlite3' // 或 sqlite3: 'require("sqlite3")'
    }
    #+end_src
    或使用webpack-node-externals排除整个node_modules也可以。

    通过electron-builder构建应用时，要将sqlite3模块复制到dist目录下。（待验证）

*** Sequelize的注意事项
    由于sequelize采用动态引用其它模块(如sqlite、pg等)，而webpack无法探测到这些引用关系，导致编译打包时正常，但运行时就包找不到所以来的模块。
    - 问题代码：
      #+begin_src js
      import Sequelize from 'sequelize'


      export default new Sequelize({
          dialect: 'sqlite',
          storage: 'test.db',
          logging: false,
      })
      #+end_src
    - 解决方案：通过入参dialetcModule指明数据库驱动，实现运行时引用正常。(REF: https://github.com/sequelize/sequelize/issues/9489)
      1. sequelize相关代码
         #+begin_src js
         import Sequelize from 'sequelize'
         import sqlite3 from 'sqlite3'


         export default new Sequelize({
             dialect: 'sqlite',
             dialectModule: sqlite3,
             storage: 'test.db',
             logging: false,
         })
         #+end_src
      2. webpack.config.js中设置数据库驱动配置
         #+begin_src js
         externals: {
           'sqlite3': 'commonjs sqlite3'
         }
         #+end_src

* 单例模式
  注意：两种方式都必须在 ~app.on('ready', createWindow)~ 之前执行。

** Electron 2.x 的方法
   #+begin_src javascript
   import {app, BrowserWindow} from 'electron'
   let mainWindow = null

   function doMakeSingleInstance(commandLine, workingDirectory) {
     if (mainWindow !== null) {
       if (mainWindow.isMinimized()) {
         mainWindow.restore()
       }
       mainWindow.focus()
     }
   }
   if (app.makeSingleInstance(doMakeSingleInstance)) {
     app.quit()
   }

   function createWindow() {
     //......
   }

   app.on('ready', createWindow)
   #+end_src

** Electron 3.x+ 的方法
   Electron 3.x以后新增如下方式，但Electron 2.x的方法依然可用。
   #+begin_src javascript
   import {app, BrowserWindow} from 'electron'
   let mainWindow = null

   function handleSecondInstance(event, commandLine, workingDirectory) {
     if (mainWindow !== null) {
       if (mainWindow.isMinimized()) {
         mainWindow.restore()
       }
       mainWindow.focus()
   }

   function createWindow() {
     //......
   }

   if (app.requestSingleInstanceLock()) {
     app.on('second-instance', handleSecondInstance)
     app.on('ready', createWindow)
   }
   else {
     app.quit()
   }
   #+end_src

   另外相关的新增API还有：
   1. ~app.hasSingleInstanceLock()~ 检查单实例锁状态
   2. ~app.releaseSingleInstanceLock()~ 释放单实例锁

* TODO 使用ffi-napi调用c/c++的动态链接库(dll)
  限制：
  1. 只能调用动态链接库中按照C标准编译的函数；
  2. 不能用于多线程的环境；
  3. dll与调用函数共用同一个线程，因此dll报错会导致整个线程退出。

** 历史版本——node-ffi 和 ref
   限制：仅支持Nodejs8，但Nodejs8已经处于废弃的状态。
   node-ffi让开发者可以仅使用JavaScript来加载和调用c/c++动态链接库的Node.js插件。
   1. 通过内存共享实现C函数和JavaScript代码间的调用；
   2. 数据类型转换则通过 ~ref~, ~ref-array~ 和 ~ref-struct~.

** ffi-napi(https://github.com/node-ffi-napi/node-ffi-napi) 和 ref-napi(https://github.com/node-ffi-napi/ref-napi)
   ffi-napi则是基于node-ffi修改为兼容Nodejs12。
   ref-napi则是基于ref修改为兼容Nodejs12。

*** 安装
    注意：使用npm安装不要使用cnpm。

    1. 为node-gyp安装python2.7和VC++ build tools，以管理员身份运行
       #+begin_src bash
       npm i -g --production windows-build-tools
       #+end_src
    2. 配置python2.7和VC++ build tools
       #+begin_src bash
       npm config set python python2.7
       npm config set msvs_version 2015
       # 将python家目录添加到系统环境变量PATH中
       #+end_src
    3. 安装node-gyp
       #+begin_src bash
       npm i -g node-gyp
       node-gyp list # 查看是否缺少node.lib库，并按提示安装 node-gyp install
       #+end_src
    4. 安装ffi-napi ~npm i ffi-napi --save~
    5. 安装ref-napi ~npm i ref-napi --save~

*** 使用
    注意：
    1. 64位的Nodejs只能调用64位的DLL，32位的Nodejs只能调用32位的DLL。
    2. Library方法的第一个实参不用带文件扩展名，Nodejs会根据操作系统自动补充。

    官方使用示例：https://github.com/node-ffi/node-ffi/wiki/Node-FFI-Tutorial
    #+begin_src javascript
    const ffi = require('ffi-napi')

    // JavaScript字符串转换为为C/C++的wchar_t*类型(a 32-bit pointer to a constant string of 16-biy Unicode Character)
    function convertString2LPCWSTR(str) {
      return new Buffer(str, 'ucs2').toString('binary')
    }

    // 通过ffi加载user32.dll
    const user32_dll = new ffi.Library('user32', {
      'MessageBox': // 声明dll中的按照C标准编译的某个函数
      ['int32', ['int32', 'string', 'string', 'int32']] // 声明函数的返回值，参数列表
    })

    let resultCode = user32_dll.MessageBox(0, convertString2LPCWSTR('标题'), convertString2LPCWSTR('内容'), 1)

    const my_dll = new ffi.Libary('../myAdd', {
      'funAdd':
      ['int32', ['int32', 'int32']]
    })

    let sum = my_dll.funAdd(1, 2) // 同步调用
    my_dll.funAdd.async(1, 2, (error, res) => {
       // ......
    }) // 异步调用
    #+end_src

*** QA
    1. 报 ~LINK 126~
       1. 函数以C++方式编译，因此ffi无法从ddl找到该函数。
       2. ~ffi.Library~ 的第一个参数若为名称，那么该dll必须已注册，否则需要指定dll的具体路径。
       3. dll依赖其他dll，但ffi无法加载这些dll。
    2. 报 ~LINK 127~
       - 找到dll但无法找到声明的函数，可能是返回值类型、参数个数或参数类型不一致导致。
    3. 32位的操作系统无法调用64位的dll。

** Electron + ffi-napi
   - 安装自动编译原生node模块
     #+begin_src bash
     npm i electron-rebuild -D
     npx electron-rebuild # 运行自动编译
     #+end_src
   - 手动编译 进入node_module/ffi-napi文件夹执行 ~node-gyp rebuild --target='当前electron的版本' --arch=x64 --dist-url=https://atom.io/download/atom-shell~ 编译node原生模块
     1. arch ： 计算机的架构（x64或者ia32），如果node环境是32位，那么这里就是ia32，如果是node环境是64位，那么这里就是x64。
     2. 如果路径错误，换成国内镜像路径 --dist-url=https://npm.taobao.org/mirrors/atom-shell

* Integrated with SQLite3
  1. node-sqlite3是Node.js的SQLite3 binding，即包含数据库Driver。
     - 官网：https://github.com/mapbox/node-sqlite3
     - 官网虽然说node-sqlite3只适用以下版本，但实际上通过源码编译的方式可以支持Electron v11.3.0。
       - Node.js v11.x, v12.x, v13.x and v14.x.
       - Electron v6.0.x, v6.1.x, v7.0.x, v7.1.x, v8.0.x, v8.1.x and v8.2.x.
     - 通过npm安装时默认会先采用node-pre-gyp根据当前环境Node/Electron下载二进制版本，若不存在再采用node-gyp执行源码编译构建。
     - 但由于国内下载很慢，所以一般采用Solution One的方式直接下载源码并编译构建即可。
  2. node-sqlite只是Node.js的SQLite客户端而不是Driver，依赖底层Driver如node-sqlite3。
     - 官网：https://github.com/kriasoft/node-sqlite
     - 安装
       #+begin_src bash
       npm install sqlite3 -S # 安装node-sqlite3作为数据库Driver
       npm install sqlite@latest -S # 安装node-sqlite
       #+end_src
     - 使用
       #+begin_src js
       import sqlite3 from 'sqlite3'
       import { open } from 'sqlite'

       (asycn () => {
           const db = await open({
               filename: 'database.db',
               driver: sqlite3.Database,
           })
       })()
       #+end_src

** Prerequisites
    Install Python2.7 and VC++ build tools as ffi-napi does on Windows. Execute the following as Administrator.
    #+begin_src bash
    npm i -g --production windows-build-tools
    npm i -g node-gyp # `cnpm` is fine while installing node-gyp
    npm config set disturl https://npm.taobao.org/mirrors/node # set china repository URL of node source code.
    npm config set ELECTRON_MIRROR https://npm.toabao.org/mirrors/electron/ # set china repository URL of Electron.
    # or set those repository URL in .npmrc file
    # registry=https://registry.npm.taobao.org/
    # disturl=https://npm.taobao.org/mirrors/node/
    # ELECTRON_MIRROR=https://npm.toabao.org/mirrors/electron/

    npm config set python python2.7
    npm config set msvs_version 2015 # For Windows
    #+end_src

** Solution One
   #+begin_src bash
   # It is the same for Mac OS and Windows.
   cnpm install sqlite3@latest --build-from-source --runtime=electron --target=1.7.9 --dist-url=http://atom.io/download/electron --save
   # above command will compile node-sqlite3 by `node-gyp rebuild --target=1.7.9 --arch=x64 --target-arch=x64 --msvs_version=2015 --dist-url=http://atom.io/download/electron` after node-sqlite3 source has been downloaded.
   #+end_src
   If cnpm fails to download the prebuild of SQLite3 cooresponding to the electron version specified by ~--target~ option, it will build a proper one for you immediately.
   After all, it's hard to prebuild all kinds of combinations of ~sqlite version~, ~electron version~ and ~mac|win|linux~.
   The prebulid node-sqlite3 can be download from https://npm.taobao.org/mirrors/sqlite3/

   *Error and Solution*:
   1. If the above command is success, but ~Cannot find module '..../node_sqlite3.node'~ error occurs while the app is running.
      - Ensure the followings are same:
	1. ~electron --version~
	2. ~./node_modules/.bin/electron --version~
	3. electron version in package.json
	4. ~--target~ option value
   2. There is a 404 error occured while installing ~node-pre-gyp~.
      - Ignore this error with ease. It doesn't matter at all.
      - ~node-pre-gyp~ is a set of prebuild binary tools(e.g. some versions of node-sqlite3), but now we want to compile node-sqlite3 from source, so the ~node-pre-gyp~ is not necessary.

** Solution Two
   #+begin_src bash
   npm install sqlite3 -S
   npm install electron-rebuild -D
   # Mac OS / Linux
   ./node_modules/.bin/electron-rebuild
   # Windows
   .\node_modules\.bin\electron-rebuild.cmd
   #+end_src

   QA:
   1. throws ~undefined variable napi_build_version in binding.gyp while trying to load binding.gyp~
      solution: update nodejs to the latest one.

** Validate
   After install node-sqlite3, first of all is to test it is avaiable or not.
   #+begin_src js
   // test.js
   import sqlite3 from 'sqlite3'


   new sqlite3.Database('test.db') // The installation is successful, if there is a test.db created under project directory after execute `node test.js` or `electron test.js`.
   #+end_src

** TODO Using with Sequalize
* TODO Using Native Node Modules
  It is necessary to rebuild electron while integrating with ~ffi-napi~ or ~node-sqlite3~.
  In fact ~ffi-napi~, ~node-sqlite3~ and other binary library are as Node.js native addon compiled with Node.js/Electron headers.

  官方指引: https://www.electronjs.org/docs/tutorial/using-native-node-modules

** Prerequisites
   The Node.js native addon build tool ~node-gyp~ requires Python2.7 and CPP compiler.
   1. Mac OS
      Pyton2.7 is built-in on Mac OS, and CPP compiler would be installed with ~xcode~. The only one extra installation on Mac OS is the ~xcode-select~ (~xcode-select --install~)
   2. Linux
      Python2.7, gcc, g++, make
   3. Windows
      1. Solution One *windows-build-tools* (Recommanded)
	 The npm package ~windows-build-tools~ willl install Python2.7 and visualstudiotools for you just by typing ~npm install windows-build-tools -g --production~ on CMD or Powershell as *Administrator*, and boost the download progress by ~npm config set registry https://registry.npm.taobao.org/~.
      2. Solution Two
	 1. Install Python2.7 and configure it into  environment variable ~%PATH%~ manually.
	 2. Install the giant /visual studio/ with CPP compiler and related library.

** The options of ~node-gyp~
   1. ~--dist-url~, use to specify the fixed URL of Node.js *cpp header tarball*.
      #+begin_src bash
      # For Global
      --dist-url=https://atom.io/download/electron
      # For China
      --dist-url=https://npm.taobao.org/mirrors/atom-shell
      #+end_src
   2. ~--arch~, specify the operating system architecture of native addon which must match the arch of Node.js. (one of ~x86~ and ~x64~)
      There are two ways to get the arch of Node.js, ~ai32~ means the arch is x86, otherwise ~x64~ means it is x64.
      1. Run ~node -p "process.arch"~ on shell
      2. Run ~require('os').arch()~ on Node REPL
   3. ~--target~, specify the electron version of current project. (check by ~./node_modules/.bin/electron --version~)
   4. ~--python~, specify the path to Python2.7 interpretor, if it has been set in ~%PATH%~ environment variable or set by ~npm config set python /path/to/python.exe~ , ignore this option.
   5. ~--msvs_version=2015~, a fixed option, if you have set it by ~npm config set msvs_version 2015 --global~ , ignore this option.
      - If this option is not 2015, there will be ~MSBUILD: error MSB4132: ...... available tool version is 4.0 or 14.0~

** TODO node-pre-gyp
   官网: https://www.npmjs.com/package/node-pre-gyp

** TODO Electron-Rebuild

* 打包
主流的打包工具有 ~electron-builder~ 和 ~electron-packager~ 。

** electron-builder
   Electron-builder provides two package solutions.
   1. ~electron-builder --dir~, package all into directory as a version without installing.
      - Dependencies: ~winCodeSign~
   2. ~electron-builder~, package into a single executable file.
      - Dependencies: ~winCodeSign~, ~nsis~

   How to solve the dependencies:
   1. Download the compressed files(.7z) from https://github.com/electron-userland/electron-builder-binaries/releases;
   2. Uncompress them to the ~%LOCALAPPDATA%\electron-builder\cache\winCodeSign~ and ~%LOCALAPPDATA%\electron-builder\cache\nsis~ respectively, as follows:
      #+begin_src yml
      %LOCALAPPDATA%/electron-builder/cache
      /winCodeSign
      --/winCodeSign-2.6.0
      /nsis
      --/nsis-3.0.4.1
      --/nsis-resources-3.4.1
      #+end_src

*** 文件大小
    Electron项目内嵌整个V8引擎和Chromium内核，因此通过 ~electron-builder --dir~ 打包但尚未压缩的空项目大小已经达到121.MB，而压缩后则为36MB。

*** 打包后的项目结构

**** Windows
     #+begin_src yaml
     /dist/win-unpacked
     -- /locals
         -- am.pak
         -- 一堆pak文件
     -- /resources
         -- app.asar # (空项目为2KB，一个实际项目为130MB+)
         -- electron.asar # (250KB左右)
     -- electron.exe # (67.5MB)
     -- ......
     #+end_src

**** Linux
     - ~asar: true~
       #+begin_src yaml
       /dist/win-unpacked
       -- /locals
           -- am.pak
           -- 一堆pak文件
       -- /resources
           -- app.asar # (空项目为2KB，一个实际项目为130MB+)
       -- ......
       #+end_src
     - ~asar: false~
       #+begin_src yaml
       /dist/win-unpacked
       -- /locals
           -- am.pak
           -- 一堆pak文件
       -- /resources
           -- /app
              -- build/electron.js
              -- package.json # 将执行electron-builder --dir对应的package.json所在目录的内容复制过来。
              -- ......
       -- ......
       #+end_src

**** app.asar文件分析
     1. 解压asar文件
	#+begin_src bash
	npm install -g asar
	asar extract app.asar ./app
	#+end_src
     2. 其内容为包含node_modules目录的项目内容
	注意：node_modules中仅包含production dependencies的依赖项目。

**** electron.asar文件分析
     内部包含Electron相关的源代码，包含remote, ipcMain, ipcRenderer等模块。

**** electron.exe文件分析
     其功能为加载 ~resources/app.asar~ 文件中的内容，包括入口文件的位置(app.asar/package.json的main字段值)。
     打包工具可修改electron.exe的图标、作者和版本号等信息。

*** 配置
    1. 安装 ~npm i electron-builder --save-dev~ 或 ~yarn add electron-builder --dev~
    2. 配置(package.json)
       #+begin_src javascript
       {
         "version": "1.0.0",
         "scripts": {
           // npm run pack, 生成在发布目录下生成linux-unpacked目录。
           // 会根据当前编译构建打包环境生成不同工件，如Windows则使用属性win相关的配置。
           // 也可以运行 electron-builder --publish never --linux 指定工件的目标环境，但一般没有必要。
           "pack": "electron-builder --dir",
           // npm run dist, 生成一个msi,exe,dmg等文件，里面包含就是linux-unpacked的内容。
           // 会根据当前编译构建打包环境生成不同工件，如Windows则使用属性win相关的配置。
           // 也可以运行 electron-builder --publish never --linux 指定工件的目标环境，但一般没有必要。
           "dist": "electron-builder --publish never"
         },
         // electron-builder配置
         "build": {
           "appId": "com.example.app", // 应用程序id
           "productName": "测试", // 应用名称
           "asar": true, // 设置为 true 可以把自己的代码合并并加密
           "directories": {
              // The path to build resources
              // Note: build resources is not packed into the app. if you need to use some files, e.g. as tray icon, please include required files explicity: `"files": ["**/*", "build/icon.*"]`
              "buildResources": "build",
              "output": "dist", // 输出目录
              "app": "app" // The application directory in bundle, containing the application package.json.
           },
           // 指定打包(复制)哪些文件到app.asar文件中，默认是打包package.json所在目录下所有文件
           files: [
             "!node_modules", // 排除
             "./build/**", // 包含子孙目录和文件
             "./package.json" // 包含文件
           ],
           // The compression level: "store" | "normal" | "maximum"
           // store for test environemt, maximum for product environment.
           "compression": "normal",
           // https://www.electron.build/configuration/contents#extraresources
           // copy the file or directory with matching names directly into the app's resources directory(`Contents/Resources` for MacOS, `resources` for Linux and Windows).
           "extraResources": [
             { "from": "./local.db", "to": "./" }
           ],
           // https://www.electron.build/configuration/contents#extrafiles
           // copy the file or directory with matching names directly into the app's directory(`Contents` for MacOS, `app` for Linux and Windows).
           "extraFiles": [],
           // Linux
           "linux": {
             "target": "tar.gz"
           },
           // Mac OS
           "mac": {
             "category": "public.app-category.developer-tools", // 应用程序类别
             "target": ["dmg", "zip"],  // 目标包类型
             "icon": "build/icon.icns" // 图标的路径
            },
          "dmg": {
            "background": "build/background.tiff or build/background.png", // 背景图像的路径
            "title": "标题",
            "icon": "build/icon.icns" // 图标路径
           },
           "win": {
             "target": "nsis" // 目标包类型
             // Optional, 这个意思是打出来32 bit + 64 bit的包，但是要注意：这样打包出来的安装包体积比较大，所以建议直接打32的安装包。
             'arch': ['x64', 'ia32']
             // Optional
             "icon": "path/to/icon.ico",
             // Optional, Ask for executing this application as Administrator every time. The value "highestAvailable" is the same as "requireAdminstrator". And the "asInvoker" is the default value.
             "requestedExecutionLevel": "highestAvailable"
           },
           // Optional
           "nsis": {
             // 是否一键安装，建议为 false，可以让用户点击下一步、下一步、下一步的形式安装程序，如果为true，当用户双击构建好的程序，自动安装程序并打开，即：一键安装（one-click installer）
             // 为true会导致perMachine强制为true。
             "oneClick": true,
             // 安装包名称
             "artifactName": "${productName}-setup-${version}.${ext}",
             // 卸载工具名称
             "uninstallDisplayName": "${productName} ${version}",
             // 当oneClick为true时有效
             "deleteAppDataOnUninstall": false,
             // whether to show install mode installer page(choice per-machine or per-user) for assisted installer. Or whether installation always per all users(per-machine).
             "perMachine": false,
             // 允许请求提升。 如果为false，则用户必须使用提升的权限重新启动安装程序。
             "allowElevation": true,
             // 允许修改安装目录，建议为 true，是否允许用户改变安装目录，默认是不允许
             "allowToChangeInstallationDirectory": false,
             // 安装图标
             "installerIcon": "build/installerIcon_120.ico",
             // 卸载图标
             "uninstallerIcon": "build/uninstallerIcon_120.ico",
             // 安装时头部图标
             "installerHeaderIcon": "build/installerHeaderIcon_120.ico",
             // The name that will be used for all shortcuts.
             "shortcutName": "${productName}",
             // 创建桌面图标, "always" - recreate also on reinstall(even if removed by user).
             "createDesktopShortcut": true,
             // 创建开始菜单图标
             "createStartMenuShortcut": true,
             // Whether to run the installed application after finish. For assisted installer corresponding checkbox will be removed.
             "runAfterFinish": true,
             // electron中LICENSE.txt所需要的格式，并非是GBK，或者UTF-8，LICENSE.txt写好之后，需要进行转化，转化为ANSI
             "license": "LICENSE.txt"
           }
       }
       #+end_src
    3. 运行打包
       #+begin_src bash
       # 打包但不会生成安装程序或屏蔽源码
       npm run pack
       # 打包出可发布包
       npm run dist
       #+end_src

*** 打包过程
    1. electron-builder会从源码编译构建node native module；
       - 因此当package.json存在electron-rebuild，则会提示electron-rebuild为多余依赖，但保留也不会影响打包。
    2. 检查electron是否已经下载，若没有则从github下载。

*** 打包时下载electron失败的解决方案
    原因：
    1. 由于electron-builder在打包时会检查npm的cache中是否包含electron包，若没有则从github上下载，而国内网络环境从github上拉取大部分情况下会失败。
    2. 已从淘宝镜像安装electron，且在如下npm的cache路径下存在安装包
       - Linux: ~$XDG_CACHE_HOME~ or ~~/.cache/electron/~
       - MacOS: ~~/Library/Caches/electron/~
       - Windows: ~%LOCALAPPDATA%/electron/Cache~ or ~~/AppData/Local/electron/Cache/~
    解决方法：从淘宝的 ~~/AppData/Local/electron/Cache/httpscdn.npm.taobao.orgdistelectronv9.2.1electron-v9.2.1-win32-x64.zip~ 目录复制其中的 ~electron-v9.2.1-win32-x64.zip~ 到 ~~/AppData/Local/electron/Cache/~ 即可。
    Download all kinds of electron from https://npm.taobao.org/mirrors/electron/9.3.2/

    *注意：*
    通过 ~cnpm i electron -D~ 下载的electron包不是直接保存在 ~.cache/electron~ 目录下，而是保存在如下路径 ~~/.cache/electron/087ae42001f7295df383c1c4422a348b3f1f67aa3bd8d51310d8aa4c5ff3781f/electron-v11.3.0-linux-x64.zip~ ，这样electron-builder也会认为缺失electron包。
    解决方法：将 ~electron-v11.3.0-linux-x64.zip~ 复制到 ~.cache/electron~ 目录下即可。

*** 打包时包 ~react-script/node_modules/.......~ 无法解析的解决方案
    - 原因：
      若通过npm安装依赖，那么各模块的依赖的模块会在node_modules下不断嵌套，导致模块的文件路径非常长。而Windows下很多程序无法处理长度超过260个字符的文件路径长度，因此会报路径无法解析的异常。
    - 解决方法：
      1. 删除项目的node_modules目录
      2. 使用yarn重新安装所有依赖， ~yarn~

*** 打包优化
    优化方向：缩小项目所打包进app.asar的node_modules文件体积。
    由于有些npm包为了性能或其它原因，使用C/C++实现。而electron-builder在打包时会根据打包目标平台重新下载并编译C/C++代码，并打包到app.asar的node_modules中。

**** 视图层
     使用webpack等工具打包压缩代码，并将不必要的视图层依赖(如 ~eslint~)从package.json的dependencies字段中移除，避免被打包到app.asar文件中。

**** 主进程(Electron层)代码打包
     可以使用webpack对主进程的代码进行打包压缩，但注意 ~target~ 需要设置为 ~electron-main~

**** 双package.json文件进行依赖管理(https://www.electron.build/tutorials/two-package-structure)
     由于electron-builder会将package.json中dependencies中的依赖都打包，若renderer(如React)和electron的依赖均通过同一个package.json管理，
     而renderer中的以来已经通过Webpack等打包，那么最终的asar包中就会包含多余的renderer的依赖。
     因此通过two package structure的方式
     #+begin_src yaml
     - dist # 打包文件所在目录
     - package.json # development package.json
     - app/
       -- package.json  # application package.json
       -- build # 编译文件所在目录
     #+end_src
     作用：开发环境和前端框架使用的dependencies和开发阶段使用devDependencies都写在development package.json，而生产环境electron使用的dependencies则记录在application package.json。
     用法：
     1. development package.json作为主配置文件
        - electron-builder相关的build配置均在这里配置；
        - ~build.directories.buildResources, build.files, build.extraFiles, build.extraResources~ 以application package.json所在目录为工作目录
        - ~build.directories.output~ 以development package.json所在目录为工作目录
        - ~main~ 由于编译文件所在目录必须位于application package.json所在目录下，因此应设置为如 ~./app/build/electron.js~
     2. application package.json
        - 必须包含 ~name,version,main~ 属性，并且保持和development package.json一致
        - ~main~ 由于编译文件所在目录必须位于application package.json所在目录下，因此应设置为如 ~./build/electron.js~
        - ~dependencies~ 包含需要打包的node_modules模块
     3. 位于application package.json所在目录下，执行 ~cnpm i~ 安装dependencies
     4. 位于development package.json所在目录下，执行 ~./node_modules/.bin/electron-builder --publish never~ 打包


     注意：
     1. 每次修改development package.json信息后，均要检查application package.json是否需要同步；
     2. 由于build目录位于application package.json所在目录下，因此Webpack打包时的output路径也要做调整。

*** QA
    1. Application entry file "build\electron.js" in the "E:\repos\l1k\l1k-client-fed\dist\win-unpacked\resources\app.asar" does not exist.
       A: 将Electron的主进程文件main.js，复制到build目录下，并且重命名为electron.js.
    2. 通过 ~electron-builder --dir~ 打包后在main.js获取的__dirname为 E:\repos\l1k\l1k-client-fed\dist\win-unpacked\resources\app.asar\build
    3.  Package "electron" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.

* misc
** ~<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />~ 的作用？
   用于防止XSS攻击，设置仅允许加载的脚本源。

** ~window.open~ 使用native和chrome的区别？
   window.open默认会创建一个BrowserWindow实例，那么就无法使用window.opener获取父窗口实例。
   若设置 ~nativeWindowOpen: true~ 且 ~nodeIntegration: false~ 那么就会使用chrome内置的window.open。

** electron-rebuild的作用？
   若electron内置的node版本和本机的版本不一致，则在使用node原生模块时可能会报错 ~Error: The module 'path/to/native/module.node'~ .
   因此需要借助electron-rebuild自动编译node原生模块。
* 调试模式
** 主进程调试
   Electron主进程是一个Nodejs进程，而Nodejs8+引入 ~--inspect~ 参数用于调试，默认监听 ~9229~ 端口。然后通过Chrome浏览器访问 ~chrome://inspect~ 即可看到对应的调试会话，点击会话即可打开DevTools进行调试。
   1. 调试模式启动electron
      #+begin_src bash
      # 指定监听端口为1234
      ./node_modules/.bin/electron . --inspect=1234

      # 在JavaScript脚本的第一行暂停运行
      ./node_modules/.bin/electron . --inspect-brk=[port]
      #+end_src
   2. 打开Chrome浏览器，访问 ~chrome://inspect~
      1. 等待几秒钟后，在Remote Target下会出现可附加的Nodejs进程
      2. 点击inspect即会打开DevTools工具

** 渲染进程调试
   1. 启动Electron时自动打开调试渲染进程的DevTools工具
      #+begin_src javascript
      const mainWindow = new BrowserWindow()
      mainWindow.loadURL('file://path/to/index.html')
      mainWindow.webContents.openDevTools()
      #+end_src
   2. 启动Electron后手工打开调试渲染进程的DevTools工具

** 生产环境调试
   Debugtron是一个调试生产环境的Electron应用的工具，无需再客户端继承任何代码，而其本身也是基于Electron构建，支持多平台。
   下载地址：https://github.com/bytedance/debugtron/releases
   1. 打开Debugtron应用
   2. 自动检测并展示所有已安装的Electron应用
   3. 点击主进程或渲染进程会话，即可进行调试

** VSCode集成调试
   1. 安装插件：Debugger for Chrome
   2. 在项目根目录下添加配置文件 ~.vscode/launch.json~
      #+begin_src javascript
      {
      "version": "0.2.0",
      "configurations": [
         {
         "type": "node",
         "request": "launch",
         "name": "Main",
         "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
         "runtimeArgs": ["--remote-debugging-port=9222", "."],
         "windows": {
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
           }
        },
        {
         "name": "Renderer",
         "type": "chrome",
         "request": "attach",
         "port": 9222,
         "webRoot": "${workspaceFolder}" // HTML引用的静态资源位于根目录下
         }
      ],
      "compounds": [ // 指定一个组合会话
      {
        "name": "All",
        "configurations": ["Main", "Renderer"] // 分别对应主进程和渲染进程
      }
     ]
     }
      #+end_src
   3. 在VSCode左侧选择debug面板，启动 ~All~ 项目开始调试。此时即可在主进程和渲染进程对应的文件中添加断点。
* 开发环境hot reload
** TODO Electron Connect方案(https://github.com/Quramy/electron-connect)
   通过electron-connect可实现代码文件发生修改后自动重启Electron主进程的功能。

*** TODO 问题
    1. 启动调试模式并通过Chrome://inspect启动DevTools附加到相应Node进程，重启主进程后该附加会失效，必须重新附加才能继续调试。

* 主进程和渲染进程间通信

** ipcMain和ipcRenderer方式
   注意：
   1. 主进程和渲染进程间的通信，均是由渲染进程发起。
   2. 消息在传输前会被序列化，因此对象的原型链将被擦除，并且不能将Function,Promise,Symbol,WeakMap和WeakSet作为消息传递。

*** 异步通信
    1. 普通方式
       #+begin_src javascript
       // renderer
       const {ipcRenderer} = require('electron')

       ipcRenderer.send(channel: string, ...args: any)
       ipcRenderer.on('asyncReply', (event, args)=>{
         // listen to asyncReply from main process.
       })

       // main
       const {ipcMain} = require('electron')

       ipcMain.on(channel, (event, args: any[])=>{
         // do something
         event.sender.send('asyncReply', 'hi') // 向渲染进程的main frame返回消息
         // 或者用 event.reply('asyncReply', 'hi'), 向渲染进程的iframe中发送消息到主进程的frame返回消息
       })
       ipcMain.once(channel, (event, args: any[])=>{
         // remove this listener after invoking automatically
       })
       #+end_src
    2. Promise方式
       #+begin_src javascript
       // renderer
       const {ipcRenderer} = require('electron')

       async function(){
         const result = await ipcRenderer.invoke(channel, arg1, arg2)
       }()

       // main
       const {ipcMain} = require('electron')

       ipcMain.handle(channel, async function(event, ...args){
         const result = await somePromise(...args)
         return result
       })
       ipcMain.handleOnce(channel, async function(event, ...args){
         const result = await somePromise(...args)
         return result
       })
       #+end_src

*** 同步通信
     #+begin_src javascript
     // renderer
     const {ipcRenderer} = require('electron')

     let reply = ipcRenderer.sendSync(channel: string, args: any[])

     // main
     const {ipcMain} = require('electron')

     ipcMain.on(channel, (event, args: any[]) => {
       event.returnValue = 'Return value synchronously.'
     })
     #+end_src

*** 优化手段
    Electron原生IPC的可优化点：
    1. 存在同步通信接口，稍不留神使用就会导致性能下降；
    2. 不支持异步消息合并；
    3. 序列化支持Buffer等特殊类型，大部分系统只需传输JSON，增加序列化和反序列化耗时；
    4. API不一致。

** 主进程向渲染进程发起通信
   主进程中通过BrowserWindow实例的webContents可向渲染进程发起通信。
   #+begin_src js
   const {app, BrowserWindow} from 'electron'
   let win = null

   app.on('ready', () => {
       win = new BrowserWindow({width: 800, height: 600})
       win.loadURL(`file://${__dirname}/index.html`)
       win.webContents.on('did-finish-load', () => {
           win.webContents.send('ping', 'hi')
       })
   })
   #+end_src
   #+begin_src html
   <script>
       require('electron').ipcRenderer.on('ping', (event, message) => {
           console.log(message)
       })
   </script>
   #+end_src
   注意： ~webContents.on~ 只能监听Electron内置的事件。

** remote模块
   作用：让渲染进程以简便的无入侵的形式访问主进程的模块和数据。
   #+begin_src html
   <script>
   var remote = require('electron').remote
   // 在渲染进程中创建另一个渲染进程
   var BrowserWindow = remote.BrowserWindow
   var other = new BrowserWindow({width: 800, height: 800})
   other.loadURL('xxxxx')
   </script>
   #+end_src

*** 注意
    1. remote底层采用同步IPC。
    2. 数据传输时采用如下策略
       1. 简单数据类型，无需序列化直接传输
       2. Object子类，均采用远程对象方式传输。而不是简单的序列化和反序列化。

* 计算密集型任务的解决方案
  由于渲染进程在渲染界面时，会通过IPC与主进程进行同步通信，因此若主进程一直繁忙则会导致UI卡顿。

** 通过BrowserWindow创建预加载tray窗口的Web Worker执行计算密集型运算
   注意：
   1. Web Worker位于渲染进程中；
   2. Web Worker中可使用Node模块；
   3. 绝大部分Node模块为线程不安全，因此不能在多个线程中使用相同的Node模块。

* 本地文件和目录选择
  通过 ~dialog~ 模块使用本地对话框来实现消息提示、选择目录、打开文件和保存文件等操作。
  注意：该模块必须在主进程中使用，因此渲染进程中需要通过IPC(Inter-Process Comminucation)或 ~remote~ 模块间接调用。

** 选择本地文件
   #+begin_src javascript
   // in main process
   const {dialog} = require('electron')

   // 单选
   // 同步方式
   let filepath = dialog.showOpenDialog()
   // 异步方式
   dialog.showOpenDialog(filepath=>{
     console.log(filepath)
   })

   // 多选
   // 同步方式
   let filepaths = dialog.showOpenDialog({properties:['multiSelections']})
   // 异步方式
   dialog.showOpenDialog({properties: ['multiSelections']}, filepath=>{
     console.log(filepath)
   })
   #+end_src

** 选择本地目录
   #+begin_src javascript
   // in main process
   const {dialog} = require('electron')

   // 单选
   // 同步方式
   let filepath = dialog.showOpenDialog({properties: ['openDirectory']})
   // 异步方式
   dialog.showOpenDialog({properties: ['openDirectory']}, filepath=>{
     console.log(filepath)
   })

   // 多选
   // 同步方式
   let filepaths = dialog.showOpenDialog({properties:['openDirectory', 'multiSelections']})
   // 异步方式
   dialog.showOpenDialog({properties: ['openDirectory', 'multiSelections']}, filepath=>{
     console.log(filepath)
   })
   #+end_src
** ~dialog.showOpenDialog~ 详解
   #+begin_src javascript
   dialog.showOpenDialog([browserWindow: BrowserWindow][, options: object][, callback: Function]): string|string[]
   #+end_src
   1. browserWindow 可选入参，提供则作为对话框的父窗口，并以模态方式显示对话框
      #+begin_src javascript
      // 创建BrowserWindow
      const win  = new BrowserWindow({width: 800, height: 800})
      #+end_src
   2. callback 可选入参，提供则为异步调用，否则为同步调用。回调函数的首个实参为选中的文件/目录的绝对路径。
   3. options 可选入参，默认为选择单个文件
      - ~title: string~ Title of the dialog box
      - ~defaultPath: string~ Absolute path to use by default
      - ~buttonLabel: string~ Custom label for the ~open~ button, meanwhile the label of ~cancel~ button can not be customized.
      - ~filters: object[]~ Specifies an array of file types that can be displayed or selected when you want to limit the user to a specific type. For example:
	#+begin_src javascript
	[
	  {name: 'Images', extensions: ['jpg', 'png']},
	  {name: 'Movies', extensions: ['avi', 'mp4']},
	  {name: 'All Files', extensions: ['*']}
            ]
	#+end_src
      - ~properties: string[]~ features the dialog should use. The following values are supported
	- openFile
	- openDirectory
	- multiSelections
	- showHiddenFiles
	- ~createDirectory~ Only available on macOS. Allow creating new directories from dialog.
	- ~promptToCreate~ Only available on Windows. Prompt for creation if the file path entered in the dialog does not exist. This does not actually create the file at the path but allows non-existent paths to be returned that should be created by the application.
	- ~noResolveAliases~ Only available on macOS. Disable the automatic alias(symlink) path resolution. Selected aliases will now return the aliase path instead of their target path.
	- ~treatPackageAsDirectory~ Only available on macOS. Treat packages, such as .app folders, as a directory instead of a file.
      - ~message: string~ Only available on macOS. Message to display above input boxes.
      - ~securityScopedBookmarks~ Only available on macOS. Create security scoped bookmarks when packaged for the Mac App Store.

** ~dialog.showSaveDialog~ 详解
   用法和 ~dialog.showOpenDialog~ 一致，只是options入参中增加如下配置
   - ~nameFieldLabel: string~ Only available on macOS. Custom label for the text displayed in front of the filename text field.
   - ~showsTagField~ Only available on macOS. Show the tags input box.
** ~dialog.showErrorBox(title: string, content: string)~ 详解
   在主进程进入 ~ready~ 状态前都可以使用的方法，用于提示错误信息。

** ~dialog.showMessageBox(title: string, content: string)~ 详解
   和 ~dialog.showOpenDialog~ 用法一致，但回调函数包含两个实参，分别是
   1. response, the index of the button that was clicked.
   2. checkboxChecked, the checked state of the checkbox if ~checkboxLabel~ was set in ~options~ object.

   options入参的属性
   - ~buttons: string[]~ Array of texts for buttons i.e. ["Yes", "No"]
   - ~message: string~ Content of the message box
   - ~detail: string~ Extra infomation of the message
   - ~defaultId: number~ Index of the button in the ~buttons~ array which will be selected by default when the message box opens.
   - ~title: string~ Title of the message box
   - ~type: string~ The type of the message box, can be ~none, info, error, question, warning~ to show respective icon.
   - ~checkboxLabel: string~ if provided, the message box will include a checkbox with the given label. The checkbox state can be inspected only when using callback function.
   - ~checkboxChecked: boolean~ Initial checked state of the checkbox. False by default.
   - ~icon: string~ The image path to show custom icon on message box.
   - ~cancelId: number~ The index of in the ~buttons~ array to be used cancel the dialog , via the Esc key. By default this is assigned to the first button.
   - ~onLink: boolean~ Set it true if you don't want the dialog to appear in the style of modern Windows apps.
   - ~normalizeAccessKeys: boolean~ Set it true to enable ~Alt~ key shortcuts for buttons.
     #+begin_src javascript
     normalizeAccessKeys: true,
     buttons: ["&Yes", "&No"]
     // 键盘按Alt-Y，会选中Yes按钮。
     #+end_src

* Node进程清理工作
  #+begin_src javascript
  function exitHandler(err) {
     if(err) console.error(err)
    // do something before exit
    process.exit()
  }

  process.on('exit', exitHandler)
  process.on('SIGINT', exitHandler) // catches ctrl+c event
  process.on('SIGUSR1', exitHandler) // catches kill pid
  process.on('SIGUSR2', exitHandler) // catches kill pid
  process.on('SIGTERM', exitHandler) // catches kill pid
  process.on('uncaughtException', exitHandler) // catches uncaught exceptions
  #+end_src
* React组件内部引入Electron
  1. 主进程创建渲染进程时需要让渲染进程可使用NodeAPI
     #+begin_src javascript
     const win = new BrowserWindow({
       webPreferences: {
         nodeIntegration: true
       }
     })
     #+end_src
  2. React代码运行在渲染进程上，通过 ~window.require~ 引入而不是 ~require~ 引入，避免与Browserify产生冲突。
     #+begin_src javascript
     import { React } from 'react'
     const { ipcRenderer } = window.require('electron') // 必须放在所有import语句之下，否则ES6编译会报错
     #+end_src
* 调用外部程序
  使用Node的 ~child_process~ 模块创建子进程并调用外部程序。

** 命令行参数长度的限制及解决方案
   参考：https://stackoverflow.com/questions/57166113/how-to-fix-error-spawn-enametoolong-probably-cause-by-jq-in-javascript
   - 问题描述：
     1. 报 ~ENAMETOOLARGE problems~
     2. 报 ~E2BIG error~
   - 命令行参数长度限制：
     1. Windows程序单个参数和所有参数长度上限为 8192 bytes
     2. UNIX/Linux程序单个参数和所有参数长度上限为 128~256 kilobytes

*** 基于stdin的单行数据传递参数的解决方案
    - 优点：
      1. 代码简单：服务提供方仅需从stdin读取单行数据即可获取参数。
    - 遗留问题：
      1. Windows程序stdin单行输入的字符串长度有限制，若数据量太大则无法采用该方案。

    #+begin_src javascript
    const { execFile } = require('child_process')

    /*
     * @param {string} executablePath - 外部程序的绝对路径或基于于调用者的相对路径，如 /path/to/file.exe, ./path/to/file.exe
     * @param {Array<string>} paramsInline - 通过CLI参数形式传递给外部程序的参数
     * @param {string} paramsStdin - 通过外部程序的Stdin形式传递给外部程序的参数，具体参数间的格式必须由服务提供方和服务调用方约定
     * @param {object} [opts={ windowHide: true }] - 外部程序窗口属性
     * @return {Promise}
     */
    function execFileAsync(executablePath: string, paramsInline: string[], paramsStdin: string, opts: object = { windowHide: true }): Promise {
        return new Promise((resolve, reject) => {
            const child = execFile(exectablePath, paramsInline, opts, (error, stdout, stderr) => {
                if (error) {
                    reject({error, stdout, stderr})
                }
               else {
                    resolve({stdout, stderr, child})
               }
             })

            if (paramsStdin) {
                child.stdin.end(paramsStdin)
            }
        })
    }
    #+end_src

*** 基于stdin的多行数据传递参数的解决方案
    - 优点：
      1. 参数长度无上限：通过stdin多行传输参数，不受单行字符串长度的限制。
    - 缺点：
      1. 服务提供方和服务调用方除约定参数格式外，还有约定 ~接收结束符~ 否则无法完成参数的传输，进入下一阶段。

    #+begin_src javascript
    const { execFile } = require('child_process')

    /*
     * @param {string} executablePath - 外部程序的绝对路径或基于于调用者的相对路径，如 /path/to/file.exe, ./path/to/file.exe
     * @param {Array<string>} paramsInline - 通过CLI参数形式传递给外部程序的参数
     * @param {string} paramsStdin - 通过外部程序的Stdin形式传递给外部程序的参数，具体参数间的格式必须由服务提供方和服务调用方约定
     * @param {string} [eof='==EOF=='] - 接收结束符
     * @param {number} [lineSize=6000] - 每行字符数，Windows的上限大约为6500
     * @param {object} [opts={ windowHide: true }] - 外部程序窗口属性
     * @return {Promise}
     */
    function execFileAsync(executablePath: string, paramsInline: string[], paramsStdin: string, eof: string = '==EOF==', lineSize: number = 6000, opts: object = { windowHide: true }): Promise {
        if (paramsStdin) {
          assert.ok(eof != null && eof.trim() != 'Parameter `eof` must be a non empty string.')
        }

        return new Promise((resolve, reject) => {
            const child = execFile(exectablePath, paramsInline, opts, (error, stdout, stderr) => {
                if (error) {
                    reject({error, stdout, stderr})
                }
               else {
                    resolve({stdout, stderr, child})
               }
             })

            if (paramsStdin) {
	    writeAsync(paramsStdin, lineSize, eof, child)
            }
        })
    }

    function writeAsync(paramsStdin: string, lineSize: number, eof: string, child: ChildProcess): Promise {
        if (paramsStdin.length) {
            const line = paramsStdin.slice(0, lineSize)
            const restParamsStdin = paramsStdin.slice(lineSize)
            return new Promise((resolve, reject) => child.stdin.write(`${line}\r\n`, error => error ? reject(error) : resolve()))
	    .then(() => writeAsync(restParamsStdin, lineSize, eof, child), () => new Promise(resolve => child.stdin.end(eof, resolve)))
        }
        else {
            return new Promise(resolve => child.stdin.end(eof, resolve))
        }
    }
    #+end_src
** Windows系统路径空格问题
   若要通过命令行参数传递文件/目录路径，那么必须要注意空格的处理。
   因为Windows命令行参数默认以空格作为参数分隔符，即 ~a b/test.txt~ 默认会被分割为参数 ~a~ 和 ~b/test.txt~ 。
   所以要通过双引号括住参数，防止被意外拆开，即 ~"a b/test.txt"~ 。

** 权限问题
   1. 使用Administrator启动Electron，那么必须以Administrator启动Photoshop，否则通过ActiveX操作Photoshop时会报权限不足。
* yarn和npm
  yarn比npm3.x有如下优势：
  1. 安装速度快，并行下载
  2. 依赖项的版本锁定
     - npm采用语义化版本控制机制
       - 语义化版本的语法及含义
	 1. ~5.0.3~ 精准指定版本号
	 2. ~~5.0.3~ 下载安装 ~5.0.x~ 中的最新版即可
	 3. ~^5.0.3~ 下载安装 ~5.x.x~ 中的最新版即可
       - 语义化版本的问题
	 由于不能确保依赖的模块能实现100%的向上兼容，且语义化版本严格管理升级，那么就容易出现相同packages.json下载安装不同版本依赖模块，导致有的开发者有问题而其他人却没有问题。
     - yarn通过生成yarn.lock文件，锁定项目各依赖模块的具体版本号，所有开发者均按照yarn.lock文件下载并安装依赖。
       - npm3.x则需要通过 ~npm shrinkwrap~ 来生成 shrinkwrap.json 实现 yarn.lock的功能
       - npm5.x后新增package-lock.json实现yarn.lock的功能
  3. 缓存机制
     - yarn会将模块缓存到本地，当新项目需要安装依赖时可离线从本地缓存中下载安装；而npm3.x则必须在线下载安装。
     - npm5.x后在用户家目录下创建 ~.npminstall_tarball~ 目录缓存所有模块，而项目中的node_modules下则用软连接引用项目所依赖的模块。

** yarn
*** Install on Ubuntu 19+
1. Import Yarn repos GPG key and APT to local system.
#+begin_src bash
curl -sS https://dl.yarnpkg.com/debian/pubkey-gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
#+end_src
2. Install Yarn
#+begin_src bash
# Install Node.js at the same time.
sudo apt install yarn
# Do not install Node.js.
sudo apt install --no-install-recommends yarn
#+end_src

*** 卸载方式
    #+begin_src bash
    # Mac OSX
    npm uninstall -g yarn
    rm -rf /usr/local/lib/node_modules/yarn
    rm -rf /usr/local/bin/yarn yarnpkg

    # brew
    brew uninstall yarn
    # tarball
    rm -rf "$HOME/.yarn"
    # npm
    npm uninstall -g yarn
    # ubuntu
    sudo apt-get remove yarn && sudo apt-get purge yarn
    # debian
    yum uninstall yarn
    # windows
    choco uninstall yarn
    #+end_src
*** 基本操作
    #+begin_src bash
    yarn # 根据yarn.lock或packages.json的配置安装依赖模块
    yarn add <module_name> # 下载安装依赖
    yarn add <module_name> --dev # 下载安装依赖，并作为开发时用的依赖
    yarn remove <module_name> # 移除模块
    yarn upgrade # 更新所有运行时的依赖模块
    yarn global add <module_name> # 安装全局模块
    yarn global remove <module_name> # 卸载全局模块

    yarn start # Starts the development servetr
    yarn build # Bundles the app into static files for production
    yarn test # Starts the test runner

    # run this command in the package folder you'd like to link.
    # for example, project A depends to package B, run `yarn link` in package B folder first, and then change directory to project A folder and run `yarn link b`.
    # Links are registered in ~/.config/yarn/link, specify it by `yarn link --link-folder path/to/dir`.
    yarn link
    # link another package that you'd like to test into your current project.
    # this will create a symlink links to your local package folder.
    yarn link [package...]

    yarn unlink
    yarn unlink [package...]

    # 初始化.yarnclean文件，功能和.gitignore一样
    yarn autoclean -I
    # 删除README代码无关等文件
    yarn autoclean -F
    #+end_src

*** 从git下载包
    #+begin_src bash
    yarn add <git remote url>
    yarn add <git remote url>@<branch/commit/tag>
    yarn add https://my-project.org/package.tgz # installs a package from a remote gzipped tarball.
    #+end_src

*** 从本地下载包
    #+begin_src bash
    yar add file:/path/to/your-project # Absolute path. This works both of Yarn and NPM as well.
    yar add file:../to/your-project # Relative path. This works both of Yarn and NPM as well.
    #+end_src

* Nodejs函数的Promisify
** 通过 ~util~  模块的 promisify方法转换
   - 前提： ~util.promisify(original: Function)~ 中的original参数的函数签名必须为 ~(...args, (error, value))~ 即遵守nodeCallback签名。
   - 使用示例：
     #+begin_src javascript
     const { promisify } = require('util')
     const { stat } = require('fs')
     // 回调函数使用方式
     stat('.', (error, stats) => {
         if (error) {
            // 处理异常
         }
         else {
           // 使用 `stats`
         }
     })
     // Promisify后的使用方式
     const statAsync = promisify(stat)
     statAsync('.').then(stats => {
         // 使用 `stats`
     }).catch(error => {
        // 处理异常
     })
     #+end_src
   - 当original参数不满足函数签名必须为 ~(...args, (error, value))~ 的要求，则可以通过 ~util.promisify.custom~ Symbol自定义 ~util.promisify~ 的返回值

** 通过bluebird的 ~promisify~ 和 ~promisifiyall~ 方法转换
   #+begin_src javascript
   const Promise = require('bluebird')
   const { readFile } = require('fs')

   // promisify单个函数
   const readFileAsync = Promise.promisify(readFile)
   // promisify整个模块
   const fs = Promise.promisifyall(require('fs'))
   fs.readFileAsync // 会自动在原函数名后添加Async。
   #+end_src

* CORS
  ~new BrowserWindow({webPreferences: {webSecurity: false}})~ disable CORS limited.
* 无边框窗口
  1. 调整窗口属性
     #+begin_src js
     const { BrowserWindow } = require('electron')
     const win = new BrowserWindow({
       width: 800,
       height: 600,
       resizable: false, // 不允许修改窗口尺寸
       frame: false, // Windows和Linux下去除窗口边框
     })
     win.show()
     #+end_src
  2. 设置可拖放区域
     #+begin_src css
     .dragable-area {
       -webkit-app-region: drag;
       -webkit-user-select: none; /* 文字默认会被选中，导致拖放效果失效，因此需要设置为文字不可选中。 */
     }
     /* 可拖放元素中的元素默认无法响应点击和悬停等鼠标操作，因此需要设置为不可拖放。 */
     .dgrable-area .no-dragable {
       -webkit-app-region: no-drag;
     }
     #+end_src
* 性能优化
** 启动优化
*** 白屏问题
    由于界面渲染需要一定时间，因此可以等待页面加载完成后再显示窗口。
    #+begin_src js
    import { BrowserWindow } from 'electron'
    const mainWindow = new BrowserWindow({
        show: false
    })

    mainWindow.on('ready-to-show', () => {
        mainWindow.show()
        mainWindow.focus()
    })
    #+end_src
* QA
  1. 运行 ~./node_modules/.bin/electron .~ 报 ~Error: FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw~
     - 解决方法：重启操作系统即可。
