* 学习路线
  - React
    1) basic knowledge
    2) css in js
    3) react-router
    4) redux
    5) axios
    6) i18n
    7) tool chain: webpack,babel,npm,npx,nvm,devtools
    8) animation
    9) ssr
    10) immutable
    11) vdom+diff+patch
    12) app with antd
    13) customize component
        1) table(dynamic columns, fixed header, freeze columns, on-fly edit)
        2) tree(drag and drop)
        3) numeric input
        4) form https://jaredpalmer.com/formik/
           1) yup
        5) datetime picker
        6) layout
        7) dialog
  - security
  - http, https
  - memory leak debug

* 手脚架
  github: https://github.com/facebook/create-react-app
  #+begin_src bash
  # create a new project
  npx create-react-app my-app

  # update build tooling
  npm install react-script@lastest
  #+end_src

* JSX
  1. JSX本身为表达式
  2. JSX将在编译期编译为 ~React.createElement~ 等方法
     #+begin_example js
     import React from "react"

     const element = (
       <h1 className="greeting">
         Hello!
       </h1>
     )

     /* 编译后得到
      * const element = React.createElement(
      *                 "h1",
      *                 {className: "greeting"},
      *                 "Hello!")
      */

     /* React.createElement 返回形如以下格式的 React Element
      * { type: "h1",
      *   props: {
      *     className: "greeting",
      *     children: "Hello!"
      *   }
      * }
      */
     #+end_example

  #+begin_src js
  name = "john"

  // 单行JSX不用括号包裹
  el1 = <h1>Hello, {name + " huang"}</h1>

  // 多行JSX需要括号包裹
  el2 = (
    <h1>
      Hello, {name + " huang"}
    </h1>
  )

  // 两种设置属性的方式
  // 静态属性：双引号包裹值
  // 动态属性：花括号包裹JavaScript表达式
  // 注意：JSX中的属性命名采用camelCase，如class变为className，tabindex变为tabIndex
  el3 = <div tabIndex="0" name={name + " huang"}></div>

  // 若没有子元素，可以直接以/>结尾
  el4 = <img src={user.avatarUrl} />

  // 可以包含子元素
  el5 = (
    <div>
       <h1>Hello!</h1>
    </div>
  )
  #+end_src

* Component

** Function Component
   #+begin_example js
   /* @param props
    * @return React Element
    */
   function Welcome(props){
     return <h1>Hello, {props.name}</h1>
   }

   const el = <Welcome name="john" />
   ReactDOM.render(
     el,
     document.getElementById("root")
   )
   #+end_example

** Class Component
   #+begin_example js
   class Welcome extends React.Component {
     constructor(props){
       super(props)
       this.state = {date: new Date()}
     }

     // 生命周期函数，挂载到页面时触发
     componentDidMount(){
       this.timerID = setInterval(
         () => this.setState({date: new Date()})
         1000
       )
     }

     // 生命周期函数，即将从页面卸载时触发
     componentWillUnmount(){
       clearInterval(this.timerID)
     }

     render(){
       return (
         <div>
           <h1>Hello, {this.props.name}</h1>
           <div>datetime: {this.state.date.toLocalTimeString()}</div>
         </div>
       )
     }
   }

   const el = <Welcome name="john" />
   ReactDOM.render(
     el,
     document.getElementById("root")
   )
   #+end_example

* Props and States
  1) Props 必须为只读状态，不能被修改。
  2) States 存储组件内部状态，只能通过 ~setState~ 异步更新
     1) 不依赖现在的值来更新state
        #+begin_example js
        this.setState({name: "abc"})
        #+end_example
     2) 依赖现在的值来更新state
        #+begin_example js
        this.setState((state, props) => {
          return {name: state.name + props.name}
        })
        #+end_example
     3) 分别更新部分state，React会合并更新操作
        #+begin_example js
        constructor(props){
          super(props)
          this.state = {
            posts: [],
            comments: []
          }
        }

        componentDidMount(){
          this.setState({posts: [1]})
          this.setState({comments: [2]})
        }
        #+end_example
* Event Handler

** Function Component的方式
   #+begin_example js
   function ActionLink(props){
     /* @param e {SyntheticEvent} - React根据W3C spec规定编写Event类，已兼容所有浏览器。
      * @return null - 返回false不会导致浏览器默认事件处理函数不执行，需要显式调用preventDefault才行。
      */
     const handleClick = e => {
       e.preventDefault()
       console.log("Click")
     }

     return <a href="#" onClick={handleClick}>Click Me</a>
   }
   #+end_example

** Class Component的方式
   #+begin_example js
   // 方式1
   class ActionLink1 extends React.Component{
     constructor(props){
       super(props)
       this.handleClick = this.handleClick.bind(this, "preset argument")
       this.state = {name: "john"}
     }

     handleClick(preset, e){
       e.preventDefault()
       console.log("Click by " + this.state.name)
     }

     render(){
       return <a href="#" onClick={this.handleClick}>Click Me</a>
     }
   }

   // 方式2
   class ActionLink2 extends React.Component{
     constructor(props){
       super(props)
       this.state = {name: "john"}
     }

     // 新语法：public class fields，会自动绑定this为当前实例
     handleClick = (e) => {
       e.preventDefault()
       console.log("Click by " + this.state.name)
     }

     render(){
       return <a href="#" onClick={this.handleClick}>Click Me</a>
     }
   }

   // 方式3
   class ActionLink1 extends React.Component{
     constructor(props){
       super(props)
       this.state = {name: "john"}
     }

     handleClick(e, other_arg){
       e.preventDefault()
       console.log("Click by " + this.state.name)
     }

     render(){
       return <a href="#" onClick={(e) => this.handleClick(e, "other argument")}>Click Me</a>
     }
   }
   #+end_example
** 注意
   1) 原生的onchange事件是控件失焦后，发现控件内容有变化才触发；React中的onChange事件，则控件内容发生变化即触发。

* 根据条件不渲染组件
  只需返回null即可。

** Function Component
   #+begin_example js
   function Welcome(props){
     if (props.warn){
       return null
     }

     return <h1>Hello</h1>
   }
   #+end_example

** Class Component
   #+begin_example js
   class Welcome extends React.Component{
     render(){
       if (this.props.warn){
         return null
       }

       return <h1>Hello</h1>
     }
   }
   #+end_example
* TODO 列表中的key属性
  对于根据数组生成的元素列表，需要通过设置该数组唯一的key来让React识别元素的修改、新增和删除。
  注意：
  1) key是设置在通过循环数组生成的元素列表的元素上；
  2) key的值为数组内唯一，而不是全局唯一。

** 为什么需要key
   https://reactjs.org/docs/reconciliation.html#recursing-on-children

* Form

** Controlled Components
   元素的值由React管理，用户修改输入内容时必须修改React Element的状态然后由React控制组件的变化。
   注意：若设置为null后，元素的内容就根据用户输入变化，而不受React管控。
   #+begin_example js
   class LoginForm extends React.Component {
     constructor(props){
       super(props)
       this.state = {account: "",
                     password: ""}
       this.handleAccountChange = this.handleAccountChange.bind(this)
       this.handlePasswordChange = this.handlePasswordChange.bind(this)
     }

     handleAccountChange(e){
       this.setState({account: e.target.value})
     }

     handlePasswordChange(e){
       this.setState({password: e.target.value})
     }

     handleSubmit(e){
       e.preventDefault()
       console.log(this.state.account)
       console.log(this.state.password)
     }

     render(){
       return (
         <form onSubmit={this.handleSubmit}>
           <label>
             Account: <input type="text" value={this.state.account} onChange={this.handleAccountChange} />
           </label>
           <label>
             Password: <input type="password" value={this.state.password} onChange={this.handleSubmit} />
           </label>
           <input type="submit" value="submit" />
         </form>
       )
     }
   }
   #+end_example

*** Textarea
    通过属性value设置元素内容，不能通过innerText的方式。
    #+begin_example js
    <textarea value={this.state.value} onChange={this.handleChange}/>
    #+end_example

*** Select
    通过属性select元素的value代替option中通过selected标记选中项。
    当启用multiple时，可向value传递数组选中多个项目。
    #+begin_example js
    <select value={this.state.value} onChange={this.handleChange} multiple={true}>
      <option value="1">No1</option>
      <option value="2">No2</option>
    </select>
    #+end_example

** Uncontrolled Components
   元素的值由原生HTML控件管理，React不参与。

*** 通过ref引用控件来获取值
    #+begin_example js
    class NameForm extends React.Component{
      constructor(props){
        super(props)
        this.handleSubmit = this.handleSubmit.bind(this)
        this.input = React.createRef()
      }

      handleSubmit(e){
        e.preventDefault()
        console.log(this.input.current.value)
      }

      render(){
        return (
          <form onSubmit={this.handleSubmit}>
            <input type="text" ref={this.input} />
            <input type="submit" value="submit" />
          </form>
        )
      }
    }
    #+end_example

*** 由React设置默认值，但不控制后续控件内容的变化
    1) ~input[type="checkbox"], input[type="radio"]~ 通过 ~defaultChecked~ 设置
    2) ~input[type="text"], textarea, select~ 通过 ~defaultValue~ 设置

    #+begin_example js
    class NameForm extends React.Component{
      constructor(props){
        super(props)
        this.handleSubmit = this.handleSubmit.bind(this)
        this.input = React.createRef()
      }

      handleSubmit(e){
        e.preventDefault()
        console.log(this.input.current.value)
      }

      render(){
        return (
          <form onSubmit={this.handleSubmit}>
            <input type="text" ref={this.input} defaultValue={this.props.defaultValue} />
            <input type="submit" value="submit" />
          </form>
        )
      }
    }
    #+end_example

*** File
    由于 ~input[type="file"]~ 为只读控件，必须通过File API来操作，因此File控件必须为Uncontrolled Component。
    #+begin_example js
    class MyForm extends React.Component{
      constructor(props){
        super(props)
        this.handleSubmit = this.handleSubmit.bind(this)
        this.file = React.createRef()
      }

      handleSubmit(e){
        e.preventDefault()
        console.log(this.file.current.files[0].name)
      }

      render(){
        return (
          <form onSubmit={this.handleSubmit}>
            <input type="file" ref={this.file} />
            <input type="submit" value="submit" />
          </form>
        )
      }
    }
    #+end_example
* Fragment
  React规定JSX表达式最多只能返回一个等层React Element，就是说不能返回一组React Element列表。因此通常会外层添加一个容器。
  #+begin_example js
  const el = (
    <div>
      <h1>Hello!</h1>
      <h2>Guys</h2>
    </div>
  )
  #+end_example
  但是有些情况下多出来的容器会导致UI变形，因此可通过 ~<React.Fragment>~ 作为容器，在渲染时会被移除。
  #+begin_example js
  const el = (
    <React.Fragment>
      <h1>Hello!</h1>
      <h2>Guys</h2>
    </React.Fragment>
  )
  #+end_example
  缩写
  #+begin_example js
  const el = (
    <>
      <h1>Hello!</h1>
      <h2>Guys</h2>
    </>
  )
  #+end_example

** 根据数组内容生成Fragment列表也需要设置key属性
  #+begin_example js
  const els = [1,2,3].map(item => (
      <React.Fragment key={item}>
        <h1>Hello!{item}</h1>
        <h2>Guys</h2>
      </React.Fragment>
    )
  )
  #+end_example
* Forwarding Ref
  用于向外暴露组件的内部元素(DOM Element或React Element)，只能用在Function Component上
  #+begin_example js
  const FancyButton = React.forwardRef((props, ref) => (
    <button ref={ref}>
      {props.children}
    </button>
  ))

  const ref = React.createRef()
  const el = (
    <FancyButton ref={ref}>
      <h1>Hello!</h1>
    </FancyButton>
  )

  // ref.current 指向<button></button>元素
  #+end_example
  注意：属性 ~ref~ 不能通过 ~props~ 传递，必须通过 ~React.forwardRef~ 创建函数并作为第二个参数．

** HOC中使用Forwarding Ref
   #+begin_example js
   function logProps(Component){
     class LogProps extends React.Component{
       componentDidUpdate(prevProps){
         console.log(prevProps)
         console.log(this.props)
       }

       render(){
         const {forwardedRef, ...rest} = this.props

         return <Component forwardedRef={forwardedRef} ...rest />
       }
     }

     return React.createRef((props, ref) => (
       <LogProps {...props} forwardedRef={ref} />
     ))
   }

   const FancyButton = props => (
     <button ref={props.forwardedRef}>
       {props.text}
     </button>
   )

   const LogFancyButton = logProps(FancyButton)
   const ref = React.createRef()
   const el = <LogFancyButton ref={ref} text="Hello!"/>
   #+end_example
** 在DevTools中显示forwardRef入参函数的函数名称
   1) 只显示ForwardRef字样
      #+begin_example js
      const FancyButton = React.createRef((props, ref) => (
        <button ref={ref}>
          {props.text}
        </button>
      ))
      #+end_example
   2) 显示ForwardRef(函数名称)字样
      #+begin_example js
      const FancyButton = React.createRef(function FancyButton(props, ref) {
        return (
          <button ref={ref}>
            {props.text}
          </button>
        )
      }
      #+end_example
   3) HOC下显示ForwardRef(自定义内容)字样
      #+begin_example js
      function logProps(Component){
        //.....
        function forwardRef(props, ref){
           return <LogProps forwardedRef={ref} ...props />
        }
        const name = Component.displayName || Component.name
        forwardRef.displayName = `logProps(${name})`

        return React.forwardRef(forwardRef)
      }

      // 显示ForwardRef(logProps(FancyButton))
      const LogFancyButton = logProps(FancyButton)
      #+end_example
* Context API
  提供一种方式在组件树中传递数据，而不用自上而下逐层传递．适用于不同层级的组件共享变量值，如current authenticated user,locale,UI Theme,data cache等多组件需要的全局属性则适用于通过该方式传递。

** API说明
   #+begin_example js
   /* 创建上下文对象，订阅上下文对象的组件会读取最近一个Provider提供的值
    * @param defaultValue {Any} - 上下文中的默认值
    */
   const MyContext = React.createContext(defaultValue)

   /* 允许其子元素将订阅上下文实例内容的变化。
    * 注意：1. Provider可嵌套，元素获取最近的一个Provider提供的值
    *       2. 当Provider的value属性值发生变化时，订阅上下文变化的组件将无条件重新渲染，即使其父组件在shouldComponentUpdate中返回false。
    * @param value {Any} - 作为上下文的值
    */
   <MyContext.Provider value={/* some value */} />

   /* Class.contextType
    * 用于在Class Component中的所有生命周期函数中使用上下文值
    */
   class FancyButton extends React.Component{
     componentDidMount(){
       let value = this.context
     }
     componentDidUpdate(){
       let value = this.context
     }
     componentWillUnmount(){
       let value = this.context
     }
     render(){
       let value = this.context
     }
     // static contextType = MyContext 启用public class fields syntax时可用这个语法设置
   }
   FancyButton.contextType = MyContext // 传统设置方式

   /* 用于在Function Component中使用上下文值
    */
   <MyContext.Consumer>
     {value => /* render something based on the context value */}
   </MyContext.Consumer>
   #+end_example

** 示例——UI Theme
   #+begin_example js
   // theme-context.js
   import React from "react"

   export const theme = {
     light: {
       foreground: "#000",
       background: "#eee"
     },
     dark: {
       foreground: "#fff",
       background: "#222"
     }
   }

   export const ThemeContext = React.createContext()
   #+end_example
   #+begin_example js
   // theme-button.js
   import {ThemeContext} from "theme-context"

   export default ThemeButton = props => (
     <ThemeContext.Consumer>
       {theme => (<button {...props} style={{backgroundColor: theme.background}} />)}
     </ThemeContext.Consumer>
   )
   #+end_example
   #+begin_example js
   // app.js
   import React from "react"
   import {theme, ThemeContext} from "theme-context"
   import ThemeButton from "theme-button"

   class App extends React.Component {
     constructor(props){
       super(props)
       this.state = {theme: theme.dark}

       this.toggleTheme = this.toggleTheme.bind(this)
     }

     toggleTheme(){
       this.setState(state => {theme: state.theme == theme.dark ? theme.light : theme.dark})
     }

     render(){
       return (
         <div>
           <ThemeContext.Provider value={this.state.theme}>
             <ThemeButton onClick={this.toggleTheme}/>
             <ThemeContext.Consumer>
               {theme => <div style={{color: theme.foreground}}>Hello!</div>}
             </ThemeContext.Consumer>
           </ThemeContext.Provider>
         </div>
       )
     }
   }
   #+end_example

** 示例——UI Theme + 将修改上下文部分内容的行为作为上下文的一部分
   #+begin_example js
   // theme-context.js
   import React from "react"

   export const theme = {
     light: {
       foreground: "#000",
       background: "#eee"
     },
     dark: {
       foreground: "#fff",
       background: "#222"
     }
   }

   export const ThemeContext = React.createContext({theme: theme.light
                                                    , toggleTheme: () => {theme: theme.light})
   #+end_example
   #+begin_example js
   // theme-button.js
   import {ThemeContext} from "theme-context"

   export default ThemeButton = props => (
     <ThemeContext.Consumer>
       {ctx => (<button {...props} style={{backgroundColor: ctx.theme.background}} onClick={ctx.toggleTheme} />)}
     </ThemeContext.Consumer>
   )
   #+end_example
   #+begin_example js
   // app.js
   import React from "react"
   import {theme, ThemeContext} from "theme-context"
   import ThemeButton from "theme-button"

   class App extends React.Component {
     constructor(props){
       super(props)
       this.state = {theme: theme.dark
                     , toggleTheme: this.toggleTheme.bind(this)}
     }

     toggleTheme(){
       this.setState(state => {theme: state.theme == theme.dark ? theme.light : theme.dark})
     }

     render(){
       return (
         <div>
           <ThemeContext.Provider value={this.state}>
             <ThemeButton />
             <ThemeContext.Consumer>
               {ctx => <div style={{color: ctx.theme.foreground}}>Hello!</div>}
             </ThemeContext.Consumer>
           </ThemeContext.Provider>
         </div>
       )
     }
   }
   #+end_example

** 示例——订阅多个上下文对象
   #+begin_example js
   import React from "react"
   import ReactDOM from "react-dom"

   user = "john"
   theme = {bg: "#eee"}
   const UserContext = React.createContext(user)
   const ThemeContext = React.createContext(theme)

   const Content = props => (
     <ThemeContext.Consumer>
       {theme => (
         <UserContext.Consumer>
           {user => <div style={backgroundColor: theme.bg}>{user}</div>}
         </UserContext.Consumer>
       )}
     </ThemeContext.Consumer>
   )

   const App = props => (
     <ThemeContext.Provider>
       <UserContext.Provider>
         <Content />
       </UserContext.Provider>
     </ThemeContext.Provider>
   )

   ReactDOM.render(<App />, document.getElementById("root"))
   #+end_example

* Higher-Order Component
  一般用于对已有组件进行增强，不影响UI显示。

  若只想从顶层向最底层元素传递变量，那么HOC则优于Context API。
  1) 问题代码
     #+begin_example js
     // Page和Link组件之间的PageLyout,NavigationBar都需要接收user和avatarSize属性，十分冗余。
     const Page = props => <PageLayout ...props />
     const PageLayout = props => (
       <div>
         <NavigationBar ...props />
         <Feed user={props.user} />
       </div>
     )
     const NavigationBar = props => (
       <Link href={props.user.permlink}>
         <Avatar user={props.user} size={props.avatarSize} />
       </Link>
     )

     const el = <Page user={user} avatarSize={20} />
     #+end_example
  2) HOC方式——传递底层组件和属性一同向下传递
     #+begin_example js
     // 中间组件PageLayout不用接收user和avatarSize属性
     const PageLayout = props => (
       <div>
         <NavigationBar userLink={props.userLink} />
         {props.content}
       </div>
     )
     const Page = props => {
       const userLink = (
         <Link href={props.user.permlink}>
           <Avatar user={props.user} size={props.avatarSize} />
         </Link>
       )
       const content = <Feed user={props.user} />

       return <PageLayout userLink={userLink} content={contetn} />
     }

     const el = <Page user={user} avatarSize={20} />
     #+end_example
* Error Boundaries
  React 16引入该特性，用于解决问题组件不会导致整个系统不可用的问题。
  Error Boundaries的处理流程：
  1) 捕获当前元素及其子元素的渲染函数、生命周期函数和构造函数中的异常
  2) 记录错误日志信息
  3) 渲染一个降级UI

  注意：Error Boundaries不获取以下异常
  1) Event Handlers
  2) Asynchronous code
  3) Server side rendering
  4) Errors thrown in the error boundary itself(rather than its children)

** 自定义Error Boundary Component
   #+begin_example js
   import React from "react"

   class ErrorBoundary extends React.Component {
     constructor(props){
       super(props)
       this.state = {hasError: false}
     }

     static getDerivedStateFromError(error){
       // 只要实现这个函数或componentDidCatch函数，那么该组件即为Error Boundary Component。
       // 该函数用于在捕获到异常时返回降级UI用的state，然后在render函数中根据state值显示渲染降级UI。
       return {hasError: true}
     }

     componentDidCatch(error, info){
       // 只要实现这个函数或static getDerivedStateFromError函数，那么该组件即为Error Boundary Component。
       // 该函数用于捕获异常时记录异常日志信息
       logger.error(error, info)
     }

     render(){
       return this.state.hasError ? (<h1>Something went wrong.</h1>) : this.props.children
     }
   }

   <ErrorBoundary>
     <FancyButton/>
   </ErrorBoundary>
   #+end_example

** 未捕获异常的默认行为
   As of React 16, errors that were not caught by any error boundary will result in unmounting of the whole React component tree.

** 异常消息堆栈
   异常消息堆栈包含如下信息：
   1) 调用链中的组件名称
      这里通过 ~Function.name~ 或 ~Function.displayName~ 获取组件名称，因此对于IE11以前的浏览器则需要使用 function.name-polyfill(https://github.com/JamesMGreene/Function.name) 处理。
   2) 组件所在文件名

** 事件和异步代码引发的异常
   由于Error Boundaries用于捕获导致组件渲染异常的问题，而事件和异步代码的异常在组件渲染阶段并不响应组件进行渲染，因此需要采用JS的 ~try/catch~ 处理。

* Lifecycle

** 创建时
   | 阶段                                | 生命周期函数             |
   |-------------------------------------+--------------------------|
   | "Render阶段"                        | constructor              |
   | 纯净且没有副作用，可能会被React     | getDerivedStateFromProps |
   | 暂停、中止或重新启动                | render                   |
   |-------------------------------------+--------------------------|
   | "Commit阶段"                        | React更新DOM和refs       |
   | 可以使用DOM，运行副作用，安排更新。 | componentDidMount        |

** 更新时
   | 阶段                                                 | 生命周期函数1            | 生命周期函数2            |
   |------------------------------------------------------+--------------------------+--------------------------|
   |                                                      | (New Props)   setState() | forceUpdate()            |
   |------------------------------------------------------+--------------------------+--------------------------|
   | "Render阶段"                                         | getDerivedStateFromProps | getDerivedStateFromProps |
   | 纯净且没有副作用，可能会被React                      | shouldComponentUpdate    |                          |
   | 暂停、中止或重新启动                                 | render                   | render                   |
   |------------------------------------------------------+--------------------------+--------------------------|
   | "Pre-commit阶段"还没实际地更新DOM状态，但可以读取DOM | getSnapshotBeforeUpdate  | getSnapshotBeforeUpdate  |
   |------------------------------------------------------+--------------------------+--------------------------|
   | "Commit阶段"                                         | React更新DOM和refs       | React更新DOM和refs       |
   | 已经更新了DOM，可以使用DOM，运行副作用，安排更新。   | componentDidUpdate       | componentDidUpdate       |

** 卸载时
   | 阶段                                                            | 生命周期函数         |
   |-----------------------------------------------------------------+----------------------|
   | "Commit阶段" 已经更新了DOM，可以使用DOM，运行副作用，安排更新。 | componentWillUnmount |


** 生命周期函数详解
   1) constructor
      1) 用于初始化内部状态，很少用
      2) 唯一可以直接修改state的地方
   2) getDerivedStateFromProps
      React 16.3 引入的新的生命周期函数，用于根据外部属性生成内部状态并作为函数返回值返回，然后会将返回值自动合并到组件的状态上。
      1) 用于替代之前的componentWillReceiveProps
      2) 使用条件
         1) 无条件地更新状态
         2) 当props和state不匹配时更新state
      3) 尽量不使用：维护两者状态一致性会增加复杂度
         1) 直接在render中使用通过计算props的值更容易保持一致性，而不是另外设置到state上。
      4) 每次render都会调用到
      5) 典型场景：表单控件获取默认值
   3) render
      组件唯一必须定义的生命周期函数，用于定义DOM结构的地方。
   4) componentDidMount
      在这里发起异步请求等IO操作
   5) shouldComponentUpdate
      用于自定义某些操作是否需要更新UI，以便作性能优化。返回true为更新UI，false为不更新UI且中止当前流程。
      1) 在页面render之前调用，state已更新，DOM未更新但可访问
      2) 典型场景：获取render之前的DOM状态
   6) getSnapshotBeforeUpdate
      React 16.3 引入的新的生命周期函数
   7) componentDidUpdate
      #+begin_example js
      /* @param {object} prevProps - 之前的props
       * @param {object} prevState - 之前的state
       * @param {any} dataFromGetSnapshortBeforeUpdate - getSnapshotBeforeUpdate函数的返回值
       */
      componentDidUpdate(prevProps, prevState, dataFromGetSnapshortBeforeUpdate)
      #+end_example
      1) 典型场景：页面需要更新props变化重新获取数据
   8) componentWillUnmount
      用于释放资源

* TODO Integrating with other libraries
** Integrating with DOM Manipulation Plugins
   由于React并不知道DOM变化，而是自身维护一份Virtual DOM并映射到DOM中。若外界直接修改DOM，那么React再次通过Virtual DOM映射DOM时将蒙圈。
   因此当在React中使用其他DOM操作库时
   1) DOM操作的元素和React管理的元素要分离
   2) React初始化元素原始状态后，将控制权交给DOM操作，并在生命周期函数 ~componentWillUnmount~ 中执行DOM操作库的事件清理和其他善后工作
      #+begin_example js
      class MyComponent extends React.Component{
        componentDidMount(){
          this.$el = $(this.el)
          this.$el.component()
          this.$el.on("click", function(evt){})
        }

        componentWillUnmount(){
          this.$el.component("destroy")
          this.$el.off("click")
        }

        render(){
          return <div ref={el => this.el = el}></div>
        }
      }
      #+end_example

*** TODO 自定义Select

* Portals
  提供一种方式在当前元素之外渲染子元素。适合Dialog, Tooltips等组件开发。
  #+begin_example js
  /*
   * @param {ReactElement|DOMString|ReactFragment} child - 待渲染的子元素
   * @param {DOMElement} container - 渲染用的容器
   */
  ReactDOM.createPortal(child, container)
  #+end_example

** Event Bubbling Through Portals
   虽然DOM结构上通过Portal渲染的子元素不在当前元素其下，但在React内部维护的Virtual DOM Tree中，该元素依然为当前元素的子元素，因此如Context和Event冒泡等依然和常规的一致。
   #+begin_example js
   import React from "react"
   import ReactDOM from "react-dom"

   const modalRoot = document.getElementById("modal-rootp")
   class Modal extends React.Component {
     constructor(props){
       super(props)
       this.el = document.createElement("div")
     }

     componentDidMount(){
       // 这里是先将子元素渲染到detached DOM element上，然后在加入到render tree中，为的是方便后续移除
       // 若需要用到autoFocus属性，或在这里获取渲染后的尺寸，那么必须在render函数中将子元素直接渲染到位于render tree中的DOM element。
       modalRoot.appendChild(this.el)
     }

     componentWillUnmount(){
       modalRoot.removeChild(this.el)
     }

     render(){
       return ReactDOM.createPortal(this.props.children
                                    , this.el)
     }
   }

   const Parent = props => {
     const handleClick = evt => console.log(evt)

     return (
       <div onClick={handleClick}>
         <Modal>{this.props.children}</Modal>
       </div>
     )
   }

   const App = props => (
     <Parent>
       <button type="button" value="click"/>
     </Parent>
   )


   ReactDOM.render(<App/>, document.getElementById("root"))
   #+end_example;
* Refs and the DOM
  ref用于在render函数中引用DOM Element和React Element。
  常用使用场景：
  1) Managing focus, text selection, or media playback;
  2) Triggering imperative animations;
  3) Integerating with third-party DOM libraries.

  一般场景下使用声明式比指令式更好，如使用isOpen属性控制组件行为，而不是使用open和close函数。

** 使用方式1 ~React.createRef~
   React 16.3 引入的新特性。
   1) 创建(Function Component无法创建Ref)
      #+begin_example js
      class MyComponent extends React.Component {
        constructor(props){
          super(props)
          this.myRef = React.createRef()
        }

        render(){
          return <div ref={this.myRef}></div>
        }
      }
      #+end_example
   2) 访问
      #+begin_example js
      /* 1. 若ref指向HTML Element，则current指向的为DOM Element
       * 2. 若ref指向Class Component，则current指向Class Component实例
       */
      const node = this.myRef.current
      #+end_example
   3) ref指向HTML Element
      1) 在 ~componentDidMount~ 和 ~componentDidUpdate~ 前设置ref的值为HTML Element
      2) 在 ~componentWillUnmount~ 前设置ref的值为null
      3) 实例
         #+begin_example js
         class TextInput extends React.Component {
           constructor(props){
             super(props)
             this.textInput = React.createRef()
             this.focusTextInput = this.focusTextInput.bind(this)
           }

           focusTextInput(evt){
             this.textInput.current.focus()
           }

           render(){
             return (
               <div>
                 <input type="text" ref={this.textInput} />
                 <input type="button" value="focus" onClick={this.focusTextInput} />
               </div>
             )
           }
         }
         #+end_example
   4) ref指向Class Component
      #+begin_example js
      class Parent extends React.Component {
        constructor(props){
          super(props)
          this.textInput = React.createRef()
        }

        componentDidMount(){
          this.textInput.current.focusTextInput()
        }

        render(){
          return <TextInput ref={this.textInput} />
        }
      }
      #+end_example
   5) ref指向Function Component是无效的，因为Function Component是不会生成实例的
      #+begin_example js
      const TextInput = props => <input type="text" />
      class Parent extends React.Component {
        constructor(props){
          super(props)
          this.textInput = React.createRef()
        }

        render(){
          // 无效的
          return <TextInput ref={this.textInput} />
        }
      }
      #+end_example

** 使用方式2 Callback Refs
   1) 创建
      1) 在 ~componentDidMount~ 和 ~componentDidUpdate~ 前设置ref的值为HTML Element
      2) 在 ~componentWillUnmount~ 前设置ref的值为null
      3) 实例
         #+begin_example js
         class TextInput extends React.Component {
           constructor(props){
             super(props)
             this.textInput = null
             this.focusTextInput = this.focusTextInput.bind(this)
             this.getTextInputRef = ref => {this.textInput = ref}
           }

           focusTextInput(evt){
             if (this.textInput){
               this.textInput.current.focus()
             }
           }

           render(){
             return (
               <div>
                 // 注意若使用inline function的形式 <input type="text" ref={ref => {this.textInput = ref}} />
                 // 那么这个inline function会被调用两次，导致this.textInput会先初始化为null，在设置为元素。
                 // 原因是每次调用render函数时都会生成新的inline function实例，而React会传递null来清空原有ref再设置新值。
                 <input type="text" ref={this.getTextInputRef} />
                 <input type="button" value="focus" onClick={this.focusTextInput} />
               </div>
             )
           }
         }
         #+end_example
   2) 实现forwarding ref效果
      #+begin_example js
      const Child = props => <input type="text" ref={props.inputRef} />
      const Parent = props => {
        let refs = {}
        const getInputRef = ref => {
          refs.inputRef = ref
        }

        return <Child inputRef={getInputRef} />
      }
      #+end_example
* TODO Render Props
  通过prop传递function来在多个组件间共享代码。
  React-Router 和 Downshift 都使用该技术实习。

* 设计模式——函数作为子组件
  用于由组件使用者控制如何动态显示组件的内容；若以元素作为子组件则无法灵活控制动态显示，因为调用时已经决定只能显示传入的子元素。
  #+begin_example js
  class MyComponent extends React.Component {
    render(){
      return (
        <div>
          {this.props.children("Hello!")}
        </div>
      )
    }
  }

  const el = (
    <MyComponent>
      {name => <div>{name}</div>}
    </MyComponent>
  )
  #+end_example
