* 基本类型
  #+begin_src javascript
  // boolean
  let isDone: boolean = false
  // number
  let dec: number = 6
  let hex: number = 0xf00d
  let bin: number = 0b1010
  let oct: number = 0o744
  // string
  let name: string = 'john'
  // array
  let items: string[] = []
  let names: Array<string> = []
  // tuple
  let pair: [number, string] = [18, 'john']
  pair[2] = 19 // 越界元素的类型为 number | string 的联合类型
  pair[2] = 'mary' // 越界元素的类型为 number | string 的联合类型
  // enum
  enum Color {Red, Green=2} // 默认从0开始，因此Red的编号为0
  // any, 相当于没有任何类型声明的限制
  let notSure: any = 4
  notSure = 'other type'
  // void，表示没有任何类型
  // 函数没有返回值(undefined)，那么返回值类型声明为void
  // 类型为void的变量，只能赋值为null和undefined
  function show(message: string): void
  let unusable: void = undefined
  // null和undefined是所有类型的子类
  // 在未开启 --strictNullChecks 时，可以将null/undefined赋值给number等类型变量
  // 在开启 --strictNullChecks 后，null/undefined仅能赋值给相应的类型或void类型变量
  let u: undefined = undefined
  let n: null = null
  // never，用于表示永远不存在的值的类型
  // never类型是任何类型的子类
  // never类型的变量仅能赋值为never
  function error(message: string): never {
      throw new Error(message)
  }
  function infiniteLoop(): never {
      while(true) {
         // dead loop
      }
  }
  // object，表示非原始类型
  let o: object = null
  o = {id: 1}
  o = 1 // Error
  #+end_src

* 函数签名

** 完整函数类型  
   #+begin_src js
   function add(x: number, y: number): number {
       return x + y
   }

   let ptrAdd: (x: number, y: number) => number
   ptrAdd = add
   ptrAdd = (a, b) => a+b // TypeScript提供 “按上下文归类”的类型推断机制。
   #+end_src

** 可选参数和参数默认值
   #+begin_src js
   // TypeScript默认所有函数参数均为必选项
   function add1(x: number, y: number): number

   // 通过参数名称后紧跟?，标识该参数为可选项，并且可选参数必须在所有必填参数后面
   function add2(x: number, y?: number): number   

   // 通过参数名称后的=号为参数赋予默认值，并且参数类型由默认值推导得出，并且带默认参数可以放在其它参数前面
   function add3(x: number, y=1): number    // add3(3)
   function add4(x = 1, y: number): number  // add4(undefined, 4)
   #+end_src

** 可变参数
   #+begin_src js
   function add(x: number, ...ys: number[]): number
   #+end_src

** ~this~ 参数
   启动 ~--noImplicitThis~ 后，在函数中使用 ~this~ 则必须以函数第一个参数的形式传入，即不能以自由变量的方式使用 ~this~ (自由变量的this类型为any)
   #+begin_src js
   interface Card {
       text: string,
       read: (this: Card) => void,
       say: (this: void) => void
   }
   const card: Card = {
       text: 'hi there',
       // 不能使用箭头函数
       // 显示声明read成员函数仅能在Card实例上调用
       read: function(this: Card) { console.log(this.text) }
       // this: void表示成员函数内不会使用this
       say: function(this: void) { console.log('hi') }
   }
   card.read()
   #+end_src

*** 通过箭头函数使用自由变量 ~this~ 
    #+begin_src js
    class Handler {
        info: string;
        onClick = (e: Event) => { this.info = e.target.value }
    }
    #+end_src
    注意：
    1. ~this~ 永远指向Handler的实例
    2. 函数是定义在Handler的原型链上

** 函数重载
   函数参数列表不同即可实现函数重载，但注意：
   1. 若两函数参数列表除可选参数和带参数默认值不同外，参数个数和参数类型均相同时，该两个函数被认为是相同的函数。

* ~enum~ 和 ~const enum~ 的区别
  结论：若不需要通过value反向查询枚举类型，那么用 ~const enum~ 类型更安全。
  1. enum
     #+begin_src js
     enum Color { Red, Green=2}
     // 会生成JavaScript Object对象，因此支持通过value方向查询枚举类型
     Color[0] // 返回 'Red'
     Color[1] // 返回 undefined
     Color[2] // 返回 'Green'
     #+end_src
  2. const enum
     #+begin_src js
     const enum Color { Red, Green=2}
     // 不会产生JavaScript Object对象，而是直接在编译期将value替换到引用对应的枚举类型的位置
     #+end_src

* ~{}~, ~object~ 和 ~Object~ 的区别
  结论：若要声明变量为非原始类型，则使用 ~object~

  1. ~{}~ , 表示非null和非undefined的任意类型
  2. ~object~ ，表示非原始类型
  3. ~Object~ 效果和 ~{}~ 基本一样，但对Object原型内置的方法进行校验

* ~any~ 和 ~unknown~ 的区别
  结论：在表示“不知道什么类型”的场景时，使用 ~unknown~
  1. ~any~
     绕过TypeScript类型检查机制，可执行任何操作。
  2. ~unknown~ 
     1. 限制：该类型的变量仅能执行有限操作(~==,===,||,&&,?,!,typeof,instanceof~ 等等)；
     2. 突破限制：通过类型断言转换为其它类型后，才能执行其它类型相应的操作。

* 类型声明
  1. 类型声明的代码在编译后会被删除，不会影响正式代码；
  2. 对于用JavsScript开发的库，需要添加对应的类型声明后才能在TS中使用。

** 命名空间声明 ~namespace~

*** 用于全局对象成员的自定义声明，如jQuery库的声明
    #+begin_src js
    // 定义$作为函数时的类型声明
    declare function $(selector: string): HTMLElement
   
    // 定义$其下成员的类型声明
    declare namespace $ {
	function ajax(url: string, settings: any): void

	// 定义$.fn其下成员的类型声明
	namespace fn {
            function extend(object: any):void
	}
    }

    // 使用
    $('#root')
    $.ajax('./url', {})
    $.fn.extend({})
    #+end_src

*** 内部类， 如antd的 ~Form.Item~
    #+begin_src js
    class Form {
        username: Form.Item = ''
    }

    declare namespace Form {
        class Item {}
    }

    let form: Form = {
        username: ''
    }
    #+end_src

** 类型声明文件
   文件后缀 ~.d.ts~ ，默认会扫描tsconfig.json同级目录下的所有 ~.d.ts~ 文件。但可修改 tsconfig.json 指定扫描目录
   #+begin_src
   include: [
       "./src/**/*",
       "./types/**/*",
   ]
   #+end_src
   
*** 示例 ~jQuery.d.ts~
    #+begin_src js
    declare function jQuery(selector: string): HTMLElement
    declare namespace jQuery {
        function ajax(url: string, settings: any): void
    }

    export default jQuery
    #+end_src

*** 类型声明文件的查找优先级
    1. 根据tsconfig.json配置文件的paths查找类型声明文件；
       #+begin_src 
       {
           "compilerOptions": {
               "baseUrl": "./", // 当设置paths字段时，必须设置该属性。用于解析相对路径。
               "paths": {
	       "*": ["types/*"] // 当执行import语句时，从path.join(baseUrl, 'types')目录查找类型声明文件
	   }
           }
       }
       #+end_src
    2. 查找node_modules/XXX/packages.json中types字段查找类型声明文件；
    3. 查找node_modules/XXX/index.d.ts；
    4. 查找node_modules/@types/XXX/index.d.ts。

** 类型声明扩展

*** 扩展全局变量 ~declare global~
    #+begin_src js
    // myglobal.d.ts
    declare global {
        interface String {
	double(): string
        }

        interface Window {
	myname: string
        }

        declare let globalVariable: string
    }

    // index.ts
    String.prototype.double = function (){
        return Number(this)
    }
    window.myname = 'hi'
    globalVariable = 'john'
    #+end_src

*** 扩展全局变量 ~./src/globals.d.ts~
    在 ~./src/globals.d.ts~ 定义全局对象的类型声明即可
    #+begin_src 
    declare let globalVariable: string
    declare interface Window {
        myname: string
    }
    #+end_src

* 类型保护
  用于对联合类型变量进行类型分支判断。

** 原始类型保护 —— ~typeof~
   #+begin_src js
   function len(x: number | string | boolean): number {
       switch (typeof x) {
           case 'number': return x
           case 'string': return x.length
           default: return Number(boolean)	 
       }
   }
   #+end_src

** 引用类型保护 —— ~instanceof~
   #+begin_src js
   class Fruit {}
   class Apple extends Fruit {}
   class Orange extends Fruit {}
   
   function eat(fruit: Fruit): void {
       if (fruit instanceof Apple) {
           console.log('eat apple')
       }
       else {
           console.log('eat orange')
       }
   }
   #+end_src

** null/undefined保护
   启动strcitNullChecks后，则不能直接访问可能为null/undefined的变量的属性或方法。必须以如下方法操作
   #+begin_src js
   function test(str1: string | null, str2: string | undefined): void {
      // !. 操作符
      const lenOfStr1: number | undefined  = str1!.length
      const lenOfStr2: number | undefined  = str2!.length

      // || 设置默认值
      const anthorLenOfStr1: number = (str1 || '').length
      const anthorLenOfStr2: number = (str2 || '').length

      // ?. 操作符，该操作符处于stage1阶段，需要安装插件才能使用
      const theLastLenOfStr1: number | undefined  = str1?.length      
      const theLastLenOfStr2: number | undefined  = str2?.length
   }
   #+end_src

** ~type~ 的类型保护
   由于通过 ~type~ 描述的类型声明，相当于C/C++中的 ~deftype~ 仅声明已有类型的别名，因此无法通过 ~instanceof~ 进行类型保护。
   仅能通过类型的属性进行类型保护：
   #+begin_src js
   const enum TypeName {
       A = 1,
       B = 2,
   }
   type A = {
       type: TypeName.A,
   }
   type B = {
       type: TypeName.B,
   }
   const x: A |  B = {type: TypeName.B}
   if (x.type === Type.Name.A) {
       console.log('A')
   }
   else {
       console.log('B')
   }
   #+end_src
   
* 泛型
  
** 泛型函数
   #+begin_src js
   function identity<T>(arg: T): T {
       return arg
   }

   const myId1: <T>(arg: T) => T = identity
   const myId2: {<T>(arg: T): T} = identity // 使用“带调用签名的对象字面量”声明泛型函数类型
   #+end_src

** 通过泛型接口定义泛型函数
   #+begin_src js
   interface Identity<T> {
       (arg: T): T;
   }
   
   const myId1: Identity<number> = identity   
   #+end_src

** 泛型类
   仅实例成员可以使用泛型类型，静态成员无法使用泛型类型
   #+begin_src js
   class GenericNumber<T> {
     value: T
   }
   #+end_src

** 泛型约束
   #+begin_src js
   <T extends Number> // 泛型类型T必须为Number类型的子类
   <A extends Object>(arg: new () => A): A // arg的实参为Object的子类型，而不是Object的子类型的实例
   #+end_src

* 类型兼容
** 接口/类的类型兼容
   TypeScript的类型兼容性是基于结构子类型的，和名义(nominal)类型形成对比。
   1. 结构子类型，即只要对象的成员是目标类型成员的超集即类型兼容。
      对于类而言，静态部分不在比较之内，只要成员属性和成员方法（私有成员和受保护成员都要）兼容即类型兼容。
      #+begin_src js
      interface Named {
          name: string
      }
      class Person {
          name: string
          age: number
      }
      class Dog {
          name: string
      }

      const p: Named = new Person()
      const d: Named = new Dog()
      #+end_src
   2. 名义类型，即必须通过明确的声明或类型名称来决定是否兼容
      #+begin_src js
      interface Named {
          name: string
      }
      class Person extends Named {
      }

      const p: Named = new Person()
      #+end_src
  
** 函数的类型兼容
   兼容的条件：
   1. 形参列表个数小于等于目标函数类型的形参列表个数；
   2. 形参列表中形参类型的顺序与目标函数类型的形参列表的一致，或形参类型为目标函数对应位置的参数类型的子类型；
   3. 函数返回值必须为目标函数返回值的子类型。
    
   #+begin_src js
   const add: (x: number, y: number) => number = (x, y) => x + y
   const increment(x: number) => number = x => x+1

   add = increment // 类型兼容
   increment = add // 类型不兼容

   const handleEvent: (e: Event) => void;
   const handleMouseEvent: (e: MouseEvent) => void;
   
   handleEvent = handleMouseEvent // 类型兼容
   handleMouseEvent = handleEvent // 类型不兼容
   #+end_src

** 泛型类型兼容
   1. 当指定泛型参数的类型时，将导致内部具体字段或方法签名不同，因此造成类型不兼容
      #+begin_src js
      interface NoEmpty<T>{
        data: T;
      }
      let x: NotEmpty<number>
      let y: NotEmpty<string>
      x = y // 类型不兼容
      #+end_src
   2. 当没有指定泛型参数的类型时，默认为any，因此类型兼容
      #+begin_src js
      interface NoEmpty<T>{
        data: T;
      }
      let x: NotEmpty
      let y: NotEmpty
      x = y // 类型兼容
      #+end_src

* 类型转换——类型断言
   仅在编译阶段起作用，不对值进行特殊的数据检查和结构，对运行时没有影响。
   #+begin_src js
   type User = {
       id: string,
       name: string,
   }
   const origUser: User | undefined = {id: '', name: ''}
   // 尖括号语法
   const user1: User = <User>origUser
   // as语法
   const user2: User = origUser as User // 若在TypeScript中使用JSX，那么仅支持as语法。
   #+end_src

** 函数签名的类型转换
   #+begin_src js
   interface Event {}
   interface MouseEvent extends Event {}
   const listenEvent: (handler: (e: Event) => void) => void = handler => {
      // ...
   }
   listenEvent(<(e: Event) => void>((e: MouseEvent) => console.log(e)))
   #+end_src
* 交叉类型(Intersection Types)
  即将多个类型合并为一个类型，一般在mixins或其它不适合典型面向对象模型的地方会使用交叉类型。

**  示例——创建简单mixins
   #+begin_src js
   function extend<T, U> (x: T, y: U): T & U {
       const result = <T & U>{}
       for (let id in x) {
           (result as any)[id] = (x as any)[id]
       }
       for (let id in y) {
           if (!result.hasOwnProperty(id)) {
               (result as any)[id] = (y as any)[id]
           }
       }
       return result
   }

   class Person{
     name: string
   }
   class Loggable{
     log(): void
   }
   const v: Person & Loggable = extend(new Person(), new Loggable())
   v.name
   v.log()
   #+end_src

* 联合类型(Union Types)
  类型是类型列表中的其中一种，如 ~number | string | void~
* 类型别名 ~type~
** 结合泛型定义复杂递归类型
    #+begin_src js
    type Tree<T> = {
        value: T,
        left: Tree<T>,
        right: Tree<T>,
    }
    #+end_src

** 定义字面量类型限制可选择
    #+begin_src js
    type Easing = 'ease-in' | 'ease-out' | 'ease-in-out'
    fx(easing: Easing){}
    fx('hi') // 编译失败
    #+end_src

** 映射类型
   基于已有的类型创建新类型，或修改成员为只读或修改为可选等等。

*** ~lib.d.ts~ 内置的标准类型
    #+begin_src js
    type Readonly<T> = {
        readonly [P in keyof T]: T[P]
    }

    type Partial<T> = {
        [P in keyof T]?: T[P]
    }

    type Nullable<T> = {
        [P in keyof T]: T[P] | null
    }

    type Pick<T, K extends keyof T> = {
        [P in K]: T[P]
    }

    type Record<K extends string, T> = {
        [P in K]: T
    }
    Record<'prop1'|'prop2', number> === {props1: number, props2: number}

    Exclude<T,U>  // 从T中剔除可以赋值给U的类型
    Extract<T,U>  // 从T中提取可以赋值给U的类型
    NonNullable<T> // 从T中剔除null和undefined
    ReturnType<T> // 获取函数返回值的类型, RetrunType<()=>number> 及number
    InstanceType<T> // 获取实例的类型
    #+end_src
* 索引类型(Index types)
  #+begin_src js
  class Person {
      name: string,
      age: number
  }

  // keyof 是索引类型查询操作符，keyof T 就是将T上已知的公共属性名生成字面量类型
  // keyof Person === 'name' | 'age'
  // T[K] 表示形如 person['name'] 的类型
  function pluck<T, K extends keyof T>(o: T, names: K[]): T[K][] {
      return names.map(name => o[name])
  }

  pluck(new Person(), ['age'])
  #+end_src

* Symbol
  ES2015开始Symbol作为原生类型，用于表示不可变且唯一的值。

** 使用
    #+begin_src js 
    let sym1 = Symbol()
    let sym2 = Symbol('Optional Name')
    let sym3 = Symbol()
    

    sym1 === sym3 // 永远返回false
    let obj1 = {
        [sym1]: 123
    }
    class C{
        [sym2](){
            return 321
        }
    }
    C()[sym2]()
    #+end_src

** 内置的Symbol
    内置的Symbol用于表示语言内部的行为
    #+begin_src js
    Symbol.hasInstance方法，会被instanceof运算符调用。
    Symbol.isConcatSpreadable布尔值，表示当一个对象上调用Array.prototype.concat时，这个对象的数组元素是否可展开。
    Symbol.iterator方法，被for-of语句调用，返回对象的默认迭代器。
    Symbol.match方法，被String.prototype.match调用。正则表达式用于匹配字符串。
    Symbol.replace方法，被String.prototype.replace调用。正则表达式用于替换字符串中匹配的子串。
    Symbol.search方法，被String.prototype.search调用。正则表达式返回被匹配部分在字符串中的索引。
    Symbol.species函数值，为一个构造函数。用来创建派生对象。
    Symbol.split方法，被String.prototype.split调用。正则表达式分割字符串。
    Symbol.toPrimitive方法，被ToPrimitive抽象操作调用，把对象转换为相应的原始值。
    Symbol.toStringTag方法，被内置方法Object.prototype.toString调用，返回字符串描述。
    Symbol.unscopables对象，其中的属性会被with作用域排除在外。
    #+end_src

* 迭代器 ~for-of~ 和 ~for-in~ 的区别

** ~for-in~
    用于遍历对象公开可遍历的属性名称。
    #+begin_src js
    const names = ['john', 'kite', 'mary']
    const john = {
        name: 'john',
        age: 18,
    }
    const pets = new Set(['Cat', 'Dog'])
    pets['species'] = 'mammals'

    for (let index in names) {
        console.log(index) // 0, 1, 2
    }
    for (let propName in john) {
        console.log(propName) // 'name', 'age'
    }
    for (let pet in pets) {
        console.log(pet) // 'species'
    }
    #+end_src

** 迭代器 ~for-of~
    调用对象的Symbol.iterator方法得到迭代器，然后穷尽迭代器。
    #+begin_src js
    const names = ['john', 'kite', 'mary']
    const john = {
        name: 'john',
        age: 18,
    }
    const pets = new Set(['Cat', 'Dog'])
    pets['species'] = 'mammals'

    for (let index of names) {
        console.log(index) // 'john', 'kite', 'mary'
    }
    // 由于Object没有默认的Symbol.iterator因此会报错
    for (let propName of john) {
        console.log(propName)
    }
    for (let pet of pets) {
        console.log(pet) // 'Cat', 'Dog'
    }
    #+end_src    

* 模块
  任何包含顶级 ~import~ 或 ~export~ 的文件都被当成一个模块，否则它的内容将是全局有效的。

** 重新导出
   #+begin_src js
   // 重新导出其他模块的某些成员，并且重命名
   export {ZipCodeValidator as RegExpValidator} from './ZipCodeValidator'

   // 重新导出其他模块的所有成员
   export * from './ZipCodeValidator'
   #+end_src

** 外部模块声明和使用
   若第三方JS库以模块为组织架构，那么可以以如下方式定义声明和使用

*** 定义声明
    #+begin_src js
    // node.d.ts
    declare module 'url' {
        export interface Url {
            protocol?: string,
            hostname?: string,
        }

        export function parse(urlStr: string, parseQuerystring?, slashesDenoteHost?): Url;
    }

    declare module 'path' {
        export function normalize(p: string): string;
    }
    #+end_src

*** 使用
    #+begin_src js
    /// <reference path="node.d.ts"/>
    import * as URL from 'url'

    let myUrl = URL.parse('test')
    #+end_src

* 命名空间(namespace)
  作用：
  1. 默认情况下，模块下所有成员均属于该模块的全局命名空间中。而命名空间则可以对模块下的成员进行分组，并避免模块下不同组的成员间的命名冲突；
    #+begin_src js
    namespace Validator {
        const letterRegExp = /^[A-Za-z]+$/;

        // 导出命名空间下的成员
        export interface StringValidator {}
    }

    // 使用命名空间的成员
    import { Validator } from './Validator'
    Validator.StringValidator
    #+end_src
  2. 命名空间可跨多文件。当模块成员过多时，可以通过命名空间将成员拆分到多个文件中定义。
    #+begin_src js
    // Validator.ts
    namespace Validator {
        const letterRegExp = /^[A-Za-z]+$/;

        // 导出命名空间下的成员
        export interface StringValidator {}
    }

    // LetterValidator.ts
    /// <reference path='./Validator.ts'/>
    // 由于存在依赖关系，因此必须通过三斜杠指令标识关系
    name Validator {
        export class LetterValidator extends StringValidator {}
    }
    #+end_src

** 别名 ~import alias = x.y.z~
    可对类型、带命名空间含义的符号起别名。
    #+begin_src js
    namespace Validator {
        export interface StringValidator {}
    }

    import sv = Validator.StringValidator
    #+end_src

*** ~import alias = x.y.z~ 和 ~var alias = x.y.z~ 的区别
    #+begin_src js
    var alias = x.y.z
    alias['test'] = 'hi' // 操作成功

    import alias = x.y.z
    alias['test'] = 'hi' // 编译失败
    #+end_src

* Mixins
  用于实现多重继承的功能，注意：仅多重继承成员方法，不会继承字段。
  #+begin_src js
  class Disposable {
      isDisposed: boolean;
      dispose(): void {
          this.isDisposed = true;
      }
  }
  class Serializable {
      isSerialized = boolean;
      serialize(): void {
          this.isSerialized = true;
      }
  }

  // User类型继承Disposable和Serializable类型，并且必须用implements标识仅继承各成员的类型，而不继承实现。
  class User implements Disposable, Serializable {
      // 字段不会被继承，因此必须手写
      isDisposed: boolean = false;
      isSerialized: boolean = false;

      // 成员方法签名必须手写，用于告知TypeScript编译器
      dispose(): void;
      serialize(): void;
  }

  // 通过Mixins Helper函数实现Mixins操作
  function applyMixins(derivedCtor: any, baseCtors: any[]): void {
      baseCtors.forEach(baseCtor => {
          Object.getOwnPropertyNames(baseCtor.prototype)
            .forEach(name => {
                derivedCtor.prototype[name] = baseCtor.prototype[name]
            })
      })
  }

  applyMixins(User, [Disposable, Serializable])
  #+end_src

  * 三斜杠指令
    TypeScript编译器在预处理阶段会对文件的三斜杠指令进行处理。
    注意：
    1. TypeScript编译器是以 *根文件集合* 开始加载并执行三斜杠指令的预处理。
        *根文件集合* 是命令行中指定的待编译源码文件，或在tsconfig.json中files属性指定的文件。
    2. 三斜杠指令中的相对路径是以其所在的文件路径为基准。
    3. 三斜杠指令中引用不存在的路径会报错。
    4. 命令行中添加 ~--noResolve~ 编译选项将禁用预处理阶段。

** ~<reference/>~ 指令
   用于在声明文件中引入其所依赖的声明文件。
   #+begin_src js
   /// <reference path='./path/to/xxx.d.ts'/>

   /// <reference type='moudleName'/> // moduleName会被展开为@types/moduleName的路径，即@types/moduleName/index.d.ts

   /// <reference no-default-lib="true"/> // 表示该声明文件不依赖标准声明文件 lib.d.ts，因此编译时不需要加载 lib.d.ts。若命令行设置--skipDefaultLibCheck，那么该指令将会被忽略。
   #+end_src
   注意:
   1. TypeScript编译阶段生成的声明文件，编译器会自动生成该指令描述依赖关系；
   2. 若要在ts文件中声明一个对 ~@types~ 包的依赖，则需要通过命令行的 ~--types~ 或 tsconfig.json中指定；

** ~<amd-module/>~ 指令
   以AMD作为目标模块系统时，其模块默认均为匿名。但采用如r.js作为模块系统处理程序时，匿名模块将产生问题。
   因此通过该指令为AMD模块命名。
   #+begin_src js
   /// <amd-module name='Validator'/>
   #+end_src
