#+title: UBUNTU19
#+startup: content

* Y7000 2019
** wifi adapter not found
1) 输入 ~sudo rfkill list all~ 查看所有无线设备驱动的信息
   #+begin_quote
   # ideapad为联想自带的无线网卡驱动
   0: ideapad_wlan: Wireless LAN
   Soft blocked: no
   Hard blocked: yes

   # Ubuntu默认的无线网卡驱动
   1: phy0: Wireless LAN
   Soft blocked: no
   Hard blocked: no
   #+end_quote
2) 联想自带的驱动和Ubuntu默认的驱动冲突导致无法找到wifi驱动
   1) 临时修复(重启系统后失效)
      #+begin_example bash
      sudo modprobe -r ideapad_laptop
      #+end_example
   2) 永久修复，在 ~vi /etc/rc.local~ 的 ~exit 0~ 前添加
      #+begin_example bash
      #!/bin/bash

      sudo modprobe -r ideapad_laptop
      exit 0
      #+end_example
      - 设置为可执行权限 ~sudo chmod +x /etc/rc.local~

** nvidia安装
1) 添加驱动源
   #+begin_example bash
   sudo add-apt-repository ppa:graphics-drivers/ppa
   #+end_example
2) 安装驱动，并重启
   #+begin_example bash
   sudo apt-get install nvidia-384 && reboot
   #+end_example
3) 检查安装是否成功
   #+begin_example bash
   sudo nvidia-smi
   sudo nvidia-settings
   #+end_example

** 禁用Nouveau
Nouveau为Nvidia显卡的非官方支持的开源驱动

** 设置中文输入法
   1) 安装输入法管理器
      #+begin_example bash
      sudo apt install fcitx-bin fcitx-table -y
      #+end_example
   2) 安装Google拼音输入法(搜狗输入法未能很好地支持Ubuntu19，因此不使用)
      #+begin_example bash
      sudo apt install fcitx-googlepinyin -y
      #+end_example
   3) 重启系统
   4) 安装(简体/繁体)中文语言包作为输入源(input source)
      1) 搜索并进入 Region & Language
      2) 在Input Sources面板点击 ~+~ 后选择 ~Chinese~ ，然后在新的弹出窗选择 ~Chinese(Intelligent Pinyin)~
   5) 设置系统的输入法管理器
      1) 搜索并进入 Input Method
      2) 选择fcitx
   6) 添加GoolgePinyin到输入发列表中
      1) 搜索并进入 Fcitx Configuration
      2) 点击底部的 ~+~ 添加 GooglePinyin 即可

* WPS中文字体显示问题

** 字体缺失
   1) 下载字体(./wps_symbol_fonts)
      #+begin_example bash
      sudo cp ./wps_symbol_fonts /usr/share/fonts
      #+end_example
   2) 生成字体索引信息
      #+begin_example bash
      sudo mkfontscale
      sudo mkfontdir
      sudo fc-cache
      #+end_example

** 中文字体大小不一致
   安装字体即可
   #+begin_example bash
   sudo apt install ttf-wqy-microhei # 文泉驿-微米黑
   sudo apt install ttf-wqy-zenhei   # 文泉驿-正黑
   sudo apt install xfonts-wqy       # 文泉驿-点阵宋体
   #+end_example

* apt-get
以下命令均在root用户下执行
#+begin_example bash
apt-get update # 更新源
apt-get install <package> # 安装包
apt-get install <package> --reinstall # 重新安装包
apt-get install <package> -f # 修复安装
apt-get remove <package> # 移除包，但保留配置和数据文件
apt-get remove <package> --purge # 移除包，不保留配置和数据文件
apt-get upgrade # 更新已安装的包
apt-get dist-upgrade # 更新系统

apt-cache search <package> # 搜索包
apt-cache show <package> # 获取包信息，包括说明、大小和版本号等
apt-cache depends <package> # 获取该包的依赖项
apt-cache rdepends <package> # 获取依赖该包的其它包

apt-get source <package> # 下载源码
apt-get check # 检查是否有损坏的依赖
apt-get clean && apt-get autoclean # 清理无用的包

apt-get add-apt-repository ppa:<repos> # 添加PPA仓库
apt-get add-apt-repository --remove ppa:<repos> # 移除PPA仓库
#+end_example

** 源
默认位置：/etc/apt/sources.list

* dpkg
#+begin_example bash
dpkg -i <package> # Install.
dpkg -l # List all intalled packages.
dpkg -r <package> # Uninstall.
dpkg -P <package> # Uninstall and remove all related data files.
#+end_example
* Swap Ctrl-R with CapsLock
** 通过xmodmap
   1) ~vi ~/.xmodmap~
      #+begin_example text
      !
      ! swap Caps_Lock <---> Control_R
      !
      remove Lock = Caps_Lock
      remove Control = Control_R
      keysym Control_R = Caps_Lock
      keysym Caps_Lock = Control_R
      add Lock = Caps_Lock
      add Control = Control_R

      !
      ! swap Esc <---> `(on the left of '1' key)
      !
      keysym Escape = grave asciitilde grave asciitilde
      keysym grave = Escape
      #+end_example
   2) 每次重新进入系统(重启、锁屏后重新进入)和键盘重新接入(多模式键盘)，都要执行 ~xmodemap ~/.xmodemap~ ；
   3) 注意重复在执行会撤销设置；
   4) 可以通过 ~xev~ 获取keycode。

** 通过setxkbmap
   1) 每次重新进入系统(重启、锁屏后重新进入)和键盘重新接入(多模式键盘)，都要执行 ~/usr/bin/setxkbmap -layout us -option "ctrl:nocaps"~ ；
   2) 由于可重复执行，因此可以放在 =~/.zshrc= 中。

* TODO ~/etc/rc.local~ and ~/etc/init.d/~
* TODO ~/etc/profile~ and ~/etc/profile.d/~
* TODO Zsh
2** 查看系统当前支持的shell
   #+begin_example bash
   cat /etc/shells
   #+end_example

** Zsh介绍
   官网：http://www.zsh.org
   兼容 Bash 99% 的操作。

   1) 安装
      #+begin_example bash
      sudo apt install zsh -y
      #+end_example
      - Zsh 的配置文件位于 =~/.zshrc=
   2) 安装扩展集合 —— oh-my-zsh
      #+begin_example bash
      wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh
      #+end_example
      - oh-my-zsh 的安装目录位于 =~/.oh-my-zsh=
   3) 设置 Zsh 作为默认的 Login Shell
      #+begin_example bash
      chsh -s /bin/zsh <user>
      #+end_example
      - 恢复 Bash 作为默认 Login Shell
        #+begin_example bash
        chsh -s /bin/bash <user>
        #+end_example
   4) 注销重新进入即可
      - 终端模拟器为用户 Login Shell 的一个子进程，因此必须注销当前 Login Shell 后才能生效；
      - 而调用 ssh 时是创建一个新的 Login Shell ，因此马上会有效果。

*** 增强配置
    1) 启用 ~/etc/profile~ 的配置
       1) 在 =~/.zshrc= 中添加 ~source /etc/profile~ 并保存
       2) 执行 =source ~/.zshrc=

* 邮件客户端
Claws Mail.

* 其它工具
** TODO ranger
Console file manager with VI key bindings.
http://git.midea.com/supplychainsystem/qms/ehs-project

*** 配置
#+begin_example bash
# 生成配置文件所在目录 ~/.config/ranger
ranger --copy-config=all
#+end_example

1) 删除不想预览的文件类型
   在 =~/.config/ranger/scope.sh= 的externsions部分，注释掉不想预览的文件类型即可。

*** 使用
参考 http://www.mikewootc.com/wiki/linux/usage/ranger_file_manager.html
#+begin_example bash
zh # 显示隐藏文件
S # 在当前目录打开新的终端
yy # 复制
dd # 剪切
pp # 粘贴
:delete # 删除
:cw # 重命名
A # 在当前命名的基础上重命名
#+end_example

** pick
允许用户从管道前一个命令输出的列表中，选择其中一项作为输出。并且支持模糊查询操作。
1) 安装
   #+begin_example bash
   sudo apt -y install pick
   #+end_example
2) 使用
   #+begin_example bash
   # 当前目录搜索出的目录路径将作为pick的选项，用户可上下选中后回车，或直接输入字符进行筛选后再选择，选择结果将作为cd的参数
   cd $(find . -type d | pick)

   find -type f | pick | xargs less

   mv "$(find . -maxdepth 1 | pick)" /path/to/target
   #+end_example

** locate
通过Linux系统每天指定时间自动索引备份到系统数据库中的文件，实现文件的模糊查询。
数据库:var/lib/mlocate/mlocate.db
1) 更新数据库
   #+begin_example bash
   # 配置文件/etc/updatedb.conf
   /usr/bin/updatedb
   #+end_example
   1) /etc/updatedb.conf
      #+begin_example
      PRUNE_BIND_MOUNTS = "yes"
      PRUNEFS = "9p afs anon_inodefs auto autofs bdev binfmt_misc cgroup cifs coda configfs cpuset debugfs devpts ecryptfs exofs fuse fusectl gfs gfs2 hugetlbfs inotifyfs iso9660 jffs2 lustre mqueue ncpfs nfs nfs4 nfsd pipefs proc ramfs rootfs rpc_pipefs securityfs selinuxfs sfs sockfs sysfs tmpfs ubifs udf usbfs"
      PRUNENAMES = ".git .hg .svn"
      PRUNEPATHS = "/afs /media /net /sfs /tmp /udev /var/cache/ccache /var/spool/cups /var/spool/squid /var/tmp"
      #+end_example
      - 第一行PRUNE_BIND_MOUNTS="yes"的意思是：是否进行限制搜索。
      - 第二行是排除检索的文件系统类型，即列出的文件系统类型不进行检索。
      - 第三行表示对哪些后缀的文件排除检索，也就是列在这里面的后缀的文件跳过不进行检索。不同后缀之间用空格隔开。
      - 第四行是排除检索的路径，即列出的路径下的文件和子文件夹均跳过不进行检索。updatedb之后使用locate仍然找不到想要文件，可以检查挂载的目录是否被忽略了。
2) 使用
   #+begin_example bash
   # 搜索路径包含abc的记录
   locate abc
   # 搜索路径包含abc大小写不敏感的记录
   locate -i abc
   # 搜索basename包含abc的记录
   locate -b abc
   # 搜索路径全匹配abc的记录
   locate '\abc'
   # 搜索basename路径全匹配abc的记录
   locate -b '\abc'
   # 统计匹配记录数目
   locate -c abc
   # 利用正则表达式匹配，正则表达式语法为http://www.tldp.org/LDP/abs/html/x17129.html
   locate -r "/search[a-z]*.html"
   #+end_example

** TODO find
** Chrome

*** 快捷键
    | Action                         | Shortcut              |
    |--------------------------------+-----------------------|
    | Close current tab              | Ctrl + w              |
    | Close current window           | Ctrl + Shift + w      |
    | Close chrome                   | Ctrl + Shift + q      |
    | Open new tab                   | Ctrl + n              |
    | Open new tab in incognito mode | Ctrl + Shift + n      |
    | Toggle Devtools                | Ctrl + Shift + j      |
    | Clear browsing data            | Ctrl + Shift + Delete |
    | View source code               | Ctrl + u              |
    | Reload                         | Ctrl + r              |
    | Stop loading                   | Esc                   |

*** 插件Vimium
     1) 查看快捷键
        1) 在成功加载的页面中按 ~Esc~ 进入命令模式
        2) 然后按 ~Shift+/~ 显示快捷键清单
     2) 设置快捷键 ~o~ 和 ~O~ 的默认搜索引擎
        1) 在Vimium的Options/Custom search engins设置
           #+begin_example
           s: https://cn.bing.com/search?q=%s
           b: https://www.baidu.com/s?wd=%s
           #+end_example
        2) 然后通过快捷键 ~o~ 或 ~O~ 打开输入框后输入， ~s~ 或 ~b~ 空格加关键字即可。
     3) 显示页面所有链接
        1) 在当前标签中打开链接
           1) 在命令模式下按 ~f~
           2) 输入编号即可
        2) 在新增标签中打开链接
           1) 在命令模式下按 ~F~
           2) 输入编号即可
** 字典StarDict
   http://stardict-4.sourceforge.net/

   1) 安装
      #+begin_example bash
      sudo apt install stardict stardict-tools -y
      #+end_example
   2) 下载并安装词典库
      - 地址 http://download.huzheng.org/
      - 安装
        #+begin_example bash
        mkdir -p ~/.stardict/dic

        cp <词典库压缩文件> ~/.stardict/dic
        tar -xjvf <词典库压缩文件>
        #+end_example
   3) 下载并安装语音
      - 地址 http://sourceforge.net/projects/stardict-4/files/WyabdcRealPeopleTTS/WyabdcRealPeopleTTS.tar.bz2/download
      - 安装
        #+begin_example bash
        tar -xjvf WyabdcRealPeopleTTS.tar.bz2 -C /usr/share/
        #+end_example
** 百度网盘
有提供rpm和dpk版本，直接下载安装使用即可。
** vsdx
https://www.edrawsoft.com/
* 获取当前版本的代号(codename)
Ubuntu 发布版本的官方名称是 Ubuntu X.YY ，其中 X 表示年份（减去2000），YY 表示发布的月份。
Ubuntu 没有像其它软件一样有 1.0 版本，是因为其第一个版本是发布于 2004 年。所以Ubuntu的生日是10月20日。
#+begin_example bash
lsb_release -a
#+end_example
