#+startup: content

* Y7000 2019
** wifi adapter not found
1) 输入 ~sudo rfkill list all~ 查看所有无线设备驱动的信息
   #+begin_quote
   # ideapad为联想自带的无线网卡驱动
   0: ideapad_wlan: Wireless LAN
   Soft blocked: no
   Hard blocked: yes

   # Ubuntu默认的无线网卡驱动
   1: phy0: Wireless LAN
   Soft blocked: no
   Hard blocked: no
   #+end_quote
2) 联想自带的驱动和Ubuntu默认的驱动冲突导致无法找到wifi驱动
   1) 临时修复(重启系统后失效)
      #+begin_example bash
      sudo modprobe -r ideapad_laptop
      #+end_example
   2) 永久修复，在 ~vi /etc/rc.local~ 的 ~exit 0~ 前添加
      #+begin_example bash
      #!/bin/bash

      sudo modprobe -r ideapad_laptop
      exit 0
      #+end_example
      - 设置为可执行权限 ~sudo chmod +x /etc/rc.local~

** nvidia安装
1) 添加驱动源
   #+begin_example bash
   sudo add-apt-repository ppa:graphics-drivers/ppa
   #+end_example
2) 安装驱动，并重启
   #+begin_example bash
   sudo apt-get install nvidia-384 && reboot
   #+end_example
3) 检查安装是否成功
   #+begin_example bash
   sudo nvidia-smi
   sudo nvidia-settings
   #+end_example

** 禁用Nouveau
Nouveau为Nvidia显卡的非官方支持的开源驱动

** 设置中文输入法
   1) 安装输入法管理器
      #+begin_example bash
      sudo apt install fcitx-bin fcitx-table -y
      #+end_example
   2) 安装Google拼音输入法(搜狗输入法未能很好地支持Ubuntu19，因此不使用)
      #+begin_example bash
      sudo apt install fcitx-googlepinyin -y
      #+end_example
   3) 重启系统
   4) 安装(简体/繁体)中文语言包作为输入源(input source)
      1) 搜索并进入 Region & Language
      2) 在Input Sources面板点击 ~+~ 后选择 ~Chinese~ ，然后在新的弹出窗选择 ~Chinese(Intelligent Pinyin)~
   5) 设置系统的输入法管理器
      1) 搜索并进入 Input Method
      2) 选择fcitx
   6) 添加GoolgePinyin到输入发列表中
      1) 搜索并进入 Fcitx Configuration
      2) 点击底部的 ~+~ 添加 GooglePinyin 即可

* WPS中文字体显示问题

** 字体缺失
   1) 下载字体(./wps_symbol_fonts)
      #+begin_example bash
      sudo cp ./wps_symbol_fonts /usr/share/fonts
      #+end_example
   2) 生成字体索引信息
      #+begin_example bash
      sudo mkfontscale
      sudo mkfontdir
      sudo fc-cache
      #+end_example

** 中文字体大小不一致
   安装字体即可
   #+begin_example bash
   sudo apt install ttf-wqy-microhei # 文泉驿-微米黑
   sudo apt install ttf-wqy-zenhei   # 文泉驿-正黑
   sudo apt install xfonts-wqy       # 文泉驿-点阵宋体
   #+end_example

* apt-get
以下命令均在root用户下执行
#+begin_example bash
apt-get update # 更新源
apt-get install <package> # 安装包
apt-get install <package> --reinstall # 重新安装包
apt-get install <package> -f # 修复安装
apt-get remove <package> # 移除包，但保留配置和数据文件
apt-get remove <package> --purge # 移除包，不保留配置和数据文件
apt-get upgrade # 更新已安装的包
apt-get dist-upgrade # 更新系统

apt-cache search <package> # 搜索包
apt-cache show <package> # 获取包信息，包括说明、大小和版本号等
apt-cache depends <package> # 获取该包的依赖项
apt-cache rdepends <package> # 获取依赖该包的其它包

apt-get source <package> # 下载源码
apt-get check # 检查是否有损坏的依赖
apt-get clean && apt-get autoclean # 清理无用的包

apt-get add-apt-repository ppa:<repos> # 添加PPA仓库
apt-get add-apt-repository --remove ppa:<repos> # 移除PPA仓库
#+end_example

** 源
默认位置：/etc/apt/sources.list

* Swap Ctrl-R with CapsLock
** 通过xmodmap
   1) ~vi ~/.xmodmap~
      #+begin_example text
      !
      ! swap Caps_Lock <---> Control_R
      !
      remove Lock = Caps_Lock
      remove Control = Control_R
      keysym Control_R = Caps_Lock
      keysym Caps_Lock = Control_R
      add Lock = Caps_Lock
      add Control = Control_R

      !
      ! swap Esc <---> `(on the left of '1' key)
      !
      keysym Escape = grave asciitilde grave asciitilde
      keysym grave = Escape
      #+end_example
   2) 每次重新进入系统(重启、锁屏后重新进入)和键盘重新接入(多模式键盘)，都要执行 ~xmodemap ~/.xmodemap~ ；
   3) 注意重复在执行会撤销设置；
   4) 可以通过 ~xev~ 获取keycode。

** 通过setxkbmap
   1) 每次重新进入系统(重启、锁屏后重新进入)和键盘重新接入(多模式键盘)，都要执行 ~/usr/bin/setxkbmap -layout us -option "ctrl:nocaps"~ ；
   2) 由于可重复执行，因此可以放在 =~/.zshrc= 中。

* TODO ~/etc/rc.local~ and ~/etc/init.d/~
* TODO ~/etc/profile~ and ~/etc/profile.d/~
* TODO Zsh
** 查看系统当前支持的shell
   #+begin_example bash
   cat /etc/shells
   #+end_example

** Zsh介绍
   官网：http://www.zsh.org
   兼容 Bash 99% 的操作。

   1) 安装
      #+begin_example bash
      sudo apt install zsh -y
      #+end_example
      - Zsh 的配置文件位于 =~/.zshrc=
   2) 安装扩展集合 —— oh-my-zsh
      #+begin_example bash
      wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh
      #+end_example
      - oh-my-zsh 的安装目录位于 =~/.oh-my-zsh=
   3) 设置 Zsh 作为默认的 Login Shell
      #+begin_example bash
      chsh -s /bin/zsh <user>
      #+end_example
      - 恢复 Bash 作为默认 Login Shell
        #+begin_example bash
        chsh -s /bin/bash <user>
        #+end_example
   4) 注销重新进入即可
      - 终端模拟器为用户 Login Shell 的一个子进程，因此必须注销当前 Login Shell 后才能生效；
      - 而调用 ssh 时是创建一个新的 Login Shell ，因此马上会有效果。

*** 增强配置
    1) 启用 ~/etc/profile~ 的配置
       1) 在 =~/.zshrc= 中添加 ~source /etc/profile~ 并保存
       2) 执行 =source ~/.zshrc=

* 邮件客户端
Claws Mail.
