* 基金

** 费用
   基金托管人，托管费：0.25%~0.35%
   基金管理人，申购费：1.5%
   基金管理人，管理费：1.5%~2%
   基金管理人，赎回费：0.5%~1.5%

** 货币基金
   2003年中国第一支货币基金成立。

   标的：国债、央行票据、银行大单定期存款、政府短期债券、信用高的大型企业的短期债券。
   申购费：0
   管理费：0
   托管费：0
   赎回费：0
   收益率：年化3%~5%

** 债券基金
   标的：国债、政府债券
   申购费：A类基金为申购时收费，一般收费较低
   赎回费：B类基金为赎回时收费，一般收费比A类基金要高，但持有3年或以上则免赎回费
   管理费：C类基金没有申购费和赎回费，但有0.3%的管理费，3年的管理费低于A类基金


   分类：
   1. 纯债基
   2. 混合债基
      1. 一级债基
         主要投资债券，还可参与打新股。
         - 基金说明中包含：“基金不直接从二级市场买入股票、权证等权益类资产，但可参与一级市场新股申购或增发”。
      2. 二级债基
         主要投资债券，还会投资一小部分股票
   3. 可转债基
      - 可转化债券，在特定时间按照特定条件转换为普通股票的特殊企业债券。
      - 60%以上投资可转债的称为可转债基。

** 股票基金
   被动型：以上证50、深证100、沪深300、中证500、中证800、中证1000等成分股作为投资标的
   主动型：基金经理自行选股作为投资标的

** 单位净值
   单位净值，表示一份基金的价格。
   除货币基金外，基金发行时的单位净值均为1RMB。

** 累计净值
   累计净值 = 单位净值+历史分红总和

** 基金分红
   从所持有的基金中划分一部分出来，以现金形式返还给客户。
   例如：
   分红前
   | 单位净值 | 份额 | 基金总价值 | 现金 | 总资产 |
   |----------+------+------------+------+--------|
   |      1.6 | 1000 |        160 |    0 | 160    |
   分红后
   | 单位净值 | 份额 | 基金总价值 | 现金 | 总资产 |
   |----------+------+------------+------+--------|
   |      1.3 | 1000 |        130 |   30 |    160 |

** 净值估算(IOPV)
   单位净值是每个交易日20:30更新的，因此交易平台在基金公司更新单位净值前估算出来的。
   主动型基金的估算是不准的，因为其成分股是可能是不公开的;
   被动型基金的估算是相对准确的，因为其成分股是公开的。

** 场内和场外基金
   1. 场内，只能在股票市场上申购和赎回的基金，那么在微信等无法购买，必须在股票软件通过股票账户购买；
      - 代码为159或510开头
      - 赎回到帐时间，T+1
      - 交易费用，和股票交易一样（5元起）
      - 交易方式，手动购买，100股起
      - 分红方式，现金分红
      - 交易价格，下单那刻的单位净值
   2. 场外，能在微信等购买。
      - 代码为基金成立时间排序的序号
      - 赎回到帐时间，T+2或T+3，有些QDII基金为T+7
      - 交易费用，相对高，但各平台有折头
      - 交易方式，手动购买或自动定投
      - 分红方式，现金分红或红利再投资
      - 交易价格，下单那天收盘净值

** 业绩比较基准
   如 业绩比较基准 为 沪深300指数*90%+同业存款利率*10%
   在一年时间内，该基金的涨幅大于等于业绩比较基准，则表示该基金表现合格。
   低意味着低风险，高表示高收益和高风险。

** 基金招募说明说
   基金规模、申购、托管、管理、赎回费率等信息。

** 规模指数：上证50、深证100、沪深300、中证500、中证800、中证1000
   1. 更新频率：每半年或每一年
   2. 筛选规则：按规模和流动性（交易量）
   3. 上证50和深证100：代表大盘股
   4. 中证800：代表大盘股、中盘股和比小盘股大的股票
   5. 中证1000：代表偏小盘的股票


   | 上证50  | 深证100 |         |         |          |
   | 沪深300 | 沪深300 | 沪深300 | 中证500 |          |
   | 中证800 | 中证800 | 中证800 | 中证800 | 中证1000 |

** TODO 回撤率
** 市盈率(PE，本益比)
   每股收益 = 每年净利润 / 公司总股本，反映公司的价值。
   市盈率 = 公司股价 / 每股收益，即每股价格比上价值，市盈率低的股票价值没有被高估。简化为 市盈率 = 当前总市值 / 一年总净利润。

   静态市盈率(PE(LYR)) = 当前总市值 / 去年一年总利润，由于时间严重滞后，因此该指标无用。
   滚动市盈率(PE(TTM)) = 当前总市值 / 近4个季度总净利润，推荐用这个。
   动态市盈率(PE(动)) = 最新股价 / 最新报表折算收益，存在局限性，仅作参考。若报表折算收益取收益高的季度做统计，那么市盈率就会低。


   市盈率就公司股价与其制造财富的能力联系起来，例如 每股价格25RMB / 每股收益5RMB = 市盈率5， 即表示在假设每年每股收益不变的前提下，需要5年的时间才能回本。
   投资回报年限 = (当前股价 - 股东收益) / 每股收益


   不同行业的股票的市盈率无法比较，仅同行业的才有比较的价值。
   银行、地产、钢铁的市盈率比较低，但成长空间也相对较小。
   互联网的市盈率较高，即购买人数多推高每股价格，但其成长空间相对较高。

** 市净率(P/B)
   市净率 = 每股股价 / 每股净资产，越低表示风险越低，投资价值越高。

   一般用于评估重资产公司，但即使市净率低，但产能过剩或企业成长空间低也会失去投资价值，如钢材。

** 每股净资产
   相对股价波动小。

   每股净资产 = (公司总资产 - 公司总负债) / 股票总数
   公司总资产 = 公司注册资金 + 未分配利润 + 各种公积金
   公司总负债 = 贷款 + 待付工资 + 税费

   送股分红会导致每股净资产减少。

** TODO 石油基金
   基金公司换外汇(美金)到国际市场购买石油资源凭证。
   但每家基金公司都有换汇上限。

   *工行的人民币石油存在转仓风险*

   如黄金和白银等，如果是要购买国际资产的都会存在换汇的操作。

** TODO 净资产收益率(ROE, Rate of Return on Common Stockholders' Equity)

** TODO ETF(Exchange Traded Fund)
   交易型开放式指数基金。
   国内外大部分的ETF是指数基金，即上证50ETF则对应上证50的所有成分股。

*** ETF和开放式基金的区别
    1. ETF一天可以随时交易；开放式基金一天只能交易(申购赎回)一次。
    2. ETF赎回的是一篮子股票；开放式基金赎回的是现金。

** TODO 定投
   目的：做多样化的资产配置，以股权投资为核心价值，用于分散资产配置的风险。资产配置包含基金、股票、房产、进修、子女进修等。
   投资周期：3~5年。
   核心资产平均价格：1~3年的价格平均价（(最低价+最高价)/2），低于平均价买，高于则卖，然后投到货币基金作为备用金。
   收益评估：以3~5年作为收益评估。
   标的候选组合（相互存在此长彼消的关系）：ETF50或300（股市）、黄金（全球通用投资品）、房产ETF等。
   每个周期的定投时，从标的候选组合中选择低于各自平均价格最多一个进行申购。

   核心资产，
   外围资产
   - 由于不熟悉而且无法持续通过多次交易拉低持有成本，因此大概率以高成本持有，即使买入价格低于平均价格。
   - 通过更严格的平均价降低高位申购的风险。


   变现(3~5年)
   - 第一道，平均年化超过10%，那么将33%*平均年化收益率的份额变现。
   - 第二道，平均年化超过20%，那么保留20%的份额。


   每年年初要统计持有份额和总值，预计一年新投入的资金。
   年底统计年化收益。


* 投资策略
  1. 第一阶段
     保证能自主控制买入、卖出时间
     - 保障条件
       1. 资金充裕
          足够分批多次（至少6+次）建仓。1. 降低整体标的物的持有成本；2. 降低低位误判导致击穿低成本持有的风险。（资金越充裕防止击穿的成功率越高）
       2. 标的份额充裕
          足够分批策略性多次卖出。否则可能会导致无法在标的物更高位时平仓。
       3. 时间充裕
          标的物的持有时间不受其他因素影响。1. 可以自由选择利好时机卖出；2. 作为因资金不足导致持有成本较高的补充方式；3. 经历完整周期，收益最大化。
  2. 第二阶段
     信息差造成的劣势被抹平
     - 原因
       1. 局外人只能通过公开信息（如基本面，财报等）了解公司情况，和通过同行业对比、国家政策支持等了解，而这些消息仅为片面且会存在偏差；
       2. 局内人知道更多信息，甚至可以控制信息。
     - 做法：选择信息相关性弱的标的物
       1. 指数基金，信息对整体行业影响较小。
  3. 第三阶段
     倒金字塔建仓
     - 方法：
       1. 设定低位、平均价和高位；
       2. 走低时分批建仓，每次建仓比上次多一些；
       3. 走高时分批出仓，每次比上次多一些；
     - 问题：
       1. 价格一般会在平均价之间来回，导致建仓次数减少，那么出货时机会都会减少；
       2. 持有标的物的量小，那么闲置资金多，拉低整体资产收益。

* TODO 什么是票据？
* TODO 什么是普通股票？除了普通股票还有什么股票？
* TODO 政策、监管
