读音：engine x

开源版： http://nginx.net
商业版nginx plus： http://nginx.com
第三方模块： http://wiki.nginx.org/3rdPartyModules

* 特点
1) 单个服务器支持5W并发量
2) CPU、内存等资源消耗低
3) 支持HTTP/IMAP/POP3/SMTP
4) 采用异步非阻塞方式处理请求
5) 多个连接可以对应一个进程
6) 工作进程数和CPU核数相同
7) 支持热部署、热加载和在线升级
8) 模块化开发(非DSO，加入新模块要重新编译整个Nginx)
   1) http和location这些核心模块则定义在 http://nginx.org/en/docs/http/ngx_http_core_module.html 上
9) 支持FastCGI(LNMP)和uWSGI(Python)等协议

AIO是IBM发明的
NIO是ORACLE发明的

* 功能
1) 虚拟主机
2) 支持keep-alive和管道(pipeline)连接
   10000个非活跃的HTTP keep-alive连接仅占用2.5MB内存
3) 访问日志（支持基于日志缓冲写操作提高其性能）
4) url rewrite
   - 请求的是　http://www.test.com/bbs ,让用户重定向到 http://www.test.com/forum
5) 路径别名
   - 定义/test/dir1的别名为dir1，那么请求/dir1/index.html时实际解析到/test/dir1/index.html上
6) 基于IP及用户的访问控制，限制连接数和或请求数
7) 支持速率限制及并发数限制
9) Memcached的GET接口

* 反向代理(reverse proxy)
~proxy_pass protocal://ip|domain:port[uri]~
- 作用：根据URI将请求转发到不同功能的服务器(集群)
- 上下文：location, if in location, limit_except
- 示例
  1) unix domain socket ~proxy_pass unix://tmp/backend.socket:/uri/;~
  2) http 和 https ~proxy_pass ip:port[uri];~
     #+BEGIN_EXAMPLE bash
     server_name test.com;

     # 当客户端访问 http://test.com/forum/index.html
     # 会被转发到 http://196.168.56.191:8080/bbs/index.html
     location /forum/ {
       proxy_pass http://196.168.56.191:8080/bbs/;
     }

     # 当使用 ~,~*,^~,= 等进行模式匹配时，proxy_pass后的url只能设置为 <protocol>://<ip>:<port> 的形式
     # location后的URI部分将被直接传递至上游服务器，而不能为其指定转换为另一个URI。
     # 当客户端访问 http://test.com/forum/index.html
     # 会被转发到 http://196.168.56.191:8080/forum/index.html
     location ~* ^/forum/ {
       proxy_pass http://196.168.56.191:8080;
     }

     # 当使用URL重定向，那么Nginx将使用重定向后的URI处理请求，而不再考虑上游服务器上定义的URI
     # 请求被转发到http://196.168.56.191:8080/index.php?page=$1
     location / {
       rewrite /(.*)$ /index.php?page=$1 break;
       proxy_pass http://196.168.56.191:8080/index;
     }
     #+END_EXAMPLE

** 缓冲(buffer)
   1) 缓冲(buffer)和缓存(cache)的区别
      - 缓冲(buffer)
        - 作用：将数量多规模小的IO操作整理成数量少规模大的IO操作。
        - 特点：
          1) 一般为写IO因此也称为write-buffer，但读IO也可使用buffer
          2) 一般为顺序读写
      - 缓存/快取(cache)
        - 作用：当系统两端处理速度不匹配时的一种折中的方案，如CPU和Memory间分为多级cache实现CPU快速读取指令和数据
        - 特点：
          1) 一般为读操作因此也称为read-cache，但写操作也可使用cache
          2) 必须支持随机读写操作
   2) Nginx中针对代理(proxy)的缓冲设置
      - 注意：
        1) 缓冲(buffer)针对的是从应用服务返回的响应消息，是接收后尽快返回给客户端，还是先暂存在缓冲区然后当buffer被写满或应用服务返回的响应消息被读取完毕(EOF)后才开始向客户端传输。
        2) 下列指定的数值均为针对每个http response的上限，而不是对于整个buffer区指定的上限。
      - ~proxy_buffering on | off~
        - 作用：缓存从应用服务返回的内容，然后再统一返回给客户端。返回的内容会暂存到由 ~proxy_buffers~ 和 ~proxy_buffer_size~ 指定的内存缓冲区中，若内存缓冲区已满则写入磁盘上。
        - 默认值： ~proxy_buffering on;~
        - 上下文：http,server,location
        - 注意：对于采用长轮训的应用而言，必须关闭缓冲区。
        ~proxy_buffers number size~
        - 作用：设置缓冲区数量和每个缓冲区的大小
        - 上下文：http,server,location
        - 示例：
          #+begin_example bash
          proxy_buffers 4 8k;
          #+end_example
        ~proxy_buffer_size~
        - 作用：设置仅用于缓冲应用服务响应头的缓冲区容量，因此其值一般比 ~proxy_buffers~ 小。
        - 上下文：http,server,location
        - 注意：
          1) 即使 ~proxy_buffering off~ 这个缓冲区也会被开启
          2) 当 ~proxy_buffering off~ 那么Nginx会尽快转发应用服务的响应消息给客户端，期间的缓冲区最大值为 ~proxy_buffer_size~ 的值
        ~proxy_busy_buffers_size~
        - 作用：缓冲区被写入后，直到缓冲区中的数据被完整地传输完，这个缓冲区一直处于busy状态，即不能对该缓冲区作任何操作。因此 ~proxy_busy_buffers_size~ 用于控制同时传输数据给客户端的缓冲区最大容量
        - 上下文：http,server,location
        ~proxy_temp_file_write_size size~
        ~proxy_max_temp_file_size size~
        - 作用：设置缓冲区耗尽时，写入磁盘的文件大小上限。
        - 上下文：http,server,location

** 代理超时
   - ~proxy_connect_timeout second~
     - 作用：代理服务与应用服务建立TCP连接的超时时间
     - 默认值： ~proxy_connect_timeout 60s;~
     - 上下文：http,server,location
   - ~proxy_send_timeout second~
     - 作用：代理服务向应用服务发送请求的超时时间
     - 默认值： ~proxy_send_timeout 60s;~
     - 上下文：http,server,location
   - ~proxy_read_timeout second~
     - 作用：代理服务与应用服务读超时时间。
     - 默认值： ~proxy_read_timeout 60s;~
     - 上下文：http,server,location

** 代理重定向
   ~proxy_redirect default|off|regex replacement;~ 和
   - 作用：当上游服务器返回的响应是重定向或刷新请求（如HTTP响应码是301或者302）时，proxy_redirect可以重设HTTP头部的location或refresh字段。
   - off 即不修改Location和Refresh的值
   - default 则根据server_name和location来设置
     #+begin_example bash
     listen 80;
     server_name myproxy.com;
     
     # 下面两种设置是等价的
     location /one/ {
         proxy_pass http://upstream:port/john/;
         proxy_redirect default;
     }
      location /one/ {
         proxy_pass http://upstream:port/john/;
         proxy_redirect http://upstream:port/john/ http://myproxy.com:80/one/;
     }

     # 那么当服务端返回的Location为http://upstream:port/john/hi.html时，反向代理返回给客户端的Location就是http://myproxy.com:80/one/hi.html了。
     #+end_example
   - redirect replacement
     #+begin_example bash
     # 使用反向代理服务的server_name和port
     proxy_redirect http://uptstream:port/john/ /;
     # http转换为https
     proxy_redirect ~^http://([^:]+)(:\d+)?(.*)$ https://$1$2$3;
     #+end_example
   - 默认值： ~proxy_redirect default;~
   - 上下文：http,server,location

** 设置发送给后端服务的请求头
   - ~proxy_set_header header value;~
     - 作用：设置发送给应用服务的请求头
     - 上下文：http,server,location
     - 示例
       #+begin_example bash
       location / {
           proxy_pass https://fsjohnhuang.io;
           proxy_redirect default;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       }
       #+end_example
   - ~proxy_hide_header header~
     - 作用：默认情况下代理接收的请求头将被复制到发送给应用服务的请求头上，通过该指令可以移除指定的请求头
     - 上下文：http,server,location
   - ~proxy_set_body~
     - 上下文：http,server,location

** 容灾和重复处理
   ngx_http_proxy_module中的
   - ~proxy_next_upstream~ 指令
     - 语法： ~proxy_next_upstream error | timeout | invalid_header | http_500 | http_502 | http_503 | http_504 | http_403 | http_404 | http_429 | non_idempotent | off ...;~
       - error 和应用服务建立连接、发送请求或接收响应时出现错误
       - timeout 和应用服务建立连接、发送请求或接收响应时出现超时
       - invalid_header 应用服务返回空响应或非法响应
       - http_500 应用服务返回的状态码为500
       - http_502 应用服务返回的状态码为502
       - http_503 应用服务返回的状态码为503
       - http_504 应用服务返回的状态码为504
       - http_403 应用服务返回的状态码为403
       - http_404 应用服务返回的状态码为404
       - http_429 应用服务返回的状态码为429
       - non_idempotent 默认情况下请求方式为POST,LOCK,PATCH的不会发送到下一台应用服务，启用此项目则允许重复此类请求
       - off 禁止将请求传递给下一个应用服务
     - 作用：当代理和应用服务通信过程中出现指定情况时，访问会继续被分配到下一台应用服务上处理，从而实现容灾处理。
     - 默认值： ~proxy_next_upstream error timeout~
     - 上下文：http,server,location
     - 示例
       #+begin_example bash
       proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504 http_404;
       #+end_example
   - ~proxy_next_upstream_tries times;~
     - 作用：设置重试次数，0表示不限制。
     - 默认值： ~proxy_next_upstream_tries 0;~

** 分片请求
   通过位于http_slice_module的分片请求，将一个客户端的一个大文件的请求分片为向后端服务的小的请求。从而实现并行下载，和独立缓存、独立重试。
   ~slice size~
   - 默认值： ~slice 0~
   - 上下文：http,server,lcation

* if in location
*注意：if 中仅return和rewrite指令是100%执行安全的，其他指令不保证运行结果安全。*

#+begin_example bash
location / {
    if ( $http_x_forwarded_for !~ "^176\.42\.12\.228" ) {
        return 403;
    }

    if ( $slow ) {
      limit_rate 10k; # 限制速度为10Kb
    }
}
#+end_example

** 表达式
注意：所有符号两边必须为空格，否则报语法错误。

| 符号 | 作用             | 示例                          |
|------+------------------+-------------------------------|
| -f   | 文件存在         | if ( -f /path/to/file )       |
| !-f  | 文件不存在       | if ( !-f /path/to/file )      |
| -d   | 目录存在         | if ( -d /path/to/directory    |
| !-d  | 目录不存在       | if ( !-d /path/to/directory ) |
| -e   | 文件或目录存在   | if ( -e /path/to )            |
| !-e  | 文件或目录不存在 | if ( !-e /path/to )           |
| -x   | 可执行文件       | if ( -x /path/to/file )       |
| !-x  | 非可执行文件     | if ( !-x /path/to/file )      |
| ~    | 正则匹配为真           |                               |
| ~*   | 不区分大小写正则匹配为真     |                               |
| =    | 等于为真             |                               |
| !~   |                  |                               |
| !~*  |                  |                               |
| !=   |                  |                               |

* 负载均衡
ISO第7层的负载均衡方案

** GSLB和SLB
   GSLB为全局负载均衡，以省甚至国家为范围实现负载均衡。
   SLB则调度节点和逻辑节点位于同一组部署单位上。Nginx实现的就是属于SLB。

** upstream定义负载均衡的后端服务组
   - 语法
     #+begin_example bash
     upstream <name> {
       server <ip|domain name|unix style uri> [option...];
       ...
     }
     #+end_example
   - option
     - down 表示当前server暂时不参与负载均衡
     - backup 表示当前server为备用服务器，当其它所有非备用服务器均down或忙时才将请求转发到这台服务器
       可实现主备模式。
     - max_fails 设置允许请求失败的次数
     - fail_timeout 设置经过max_fails失败后，服务暂停的时间。如10s, 5m, 6d等
     - max_conns 设置最大的连接数
   - 上下文：http

** 内置均衡策略
#+BEGIN_EXAMPLE bash
http {
  # 做负载均衡时要把这个设置为0
  keepalive_timeout 0;

  # 轮询(RR,Round-Robin)
  # 后端宕机会自动剔除
  upstream balance1{
    server 123.0.0.1 max_fails=1 fail_timeout=10s;
    server 123.0.0.2;
  }

  # 加权轮询
  upstream balance2{
    server 123.0.0.1 max_fails=1 fail_timeout=10s weight=2; # 权重2/3
    server 123.0.0.2 weight=1; # 权重1/3
    server 123.0.0.3; # 没有赋予权重则表示该服务器不参与负载均衡
  }

  # 源地址散列
  upstream balance3{
    ip_hash;
    # max_fails 连续请求失败n次后，后续请求不转发到该后端
    # fail_timeout max_fails条件符合后，多少秒不转发请求到后端
    server 123.0.0.1 max_fails=1 fail_timeout=10s;
    server 123.0.0.2;
    server 123.0.0.3 backup; # 当其他非backup后端down或忙时则将请求转发到backup后端服务
  }

  # 第三方负载策略
  # fair，按后端服务器的响应时间来分配请求，响应时间短的优先分配。但由于实际网络环境复杂，因此要慎用。
  # least_conn，分发到最少连接数的后端服务
  # hash关键值，hash自定义的key
  # 语法：hash key [consistent];
  # 上下文：upstream
  # 版本要求：version 1.7.2
  upstream balance4 {
     hash $request_uri;
     server a;
     server b;
     server c;
   }

  server {
    listen 80;
    server_name www.john.com;

    location /abc.go {
      proxy_pass http://balance1;

      proxy_redirect off;
      proxy_set_header Host $host:$server_port; # 设置转发到后端服务的请求头主机名为客户端请求头的主机名，而不是转发的主机名
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 向后端服务传输实际客户端IP
      proxy_connect_timeout 60s; # Nginx连接到后端服务的连接超时时间
      proxy_read_timeout 10m; # Nginx接收后端服务响应超时时间

      # 返回后端ip和响应状态码
      add_header backendIP $upstream_addr;
      add_header backendCode $upstream_status;
    }
  }
}
#+END_EXAMPLE

** 第三方增强均衡策略

*** nginx-sticky
基于Cookie来实现会话保持均衡策略，相对ip_hash优点如下
1) 可设置会话保持时间
2) 若前端有其他代理服务，则仍然可以实现负载均衡

缺点：
1) 不支持Cookie生命周期续期(Tenginx的session_sticky则支持空闲超时和强制超时等更灵活的策略)

注意：
1) 不能和ip_hash一起使用
2) 客户端第一次并发多个请求时，以最后一个响应的cookie作为转发凭证

**** 安装
#+BEGIN_SRC
wget https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng/get/master.tar.gz

# nginx添加模块需要重新编译
cd nginx-1.14
./configure --prefix=/usr/nginx　--add-module=../nginx-sticky-module --with-http_stub_status_module --with-http_ssl_module --with-http_realip_module
./make
./make install
#+END_SRC

**** 配置
#+BEGIN_EXAMPLE
upstream backend_with_sticky {
    # name Cookie键名，默认为route
　　# expires 设置cookie的生存期，默认不设置，浏览器关闭即失效，需要是大于1秒的值
    # domain $host
    # path /
　　# secure 设置启用安全的cookie，需要HTTPS支持
    # httponly 允许cookie不通过JS泄漏，没用过
    # hash index|md5|sha1，值加密算法
    # no_fallbackup　如果设置了这个，cookie对应的服务器宕机了，那么将会返回502（bad gateway 或者 proxy error），建议不启用
    sticky name=route expires=1h domain=.test.com path=/ no_fallbackup hash=index;

    server backend1.example.com;
    server backend2.example.com;
}

# Tenginx的session_sticky策略
upstream backend_with_session-sticky {
   # mode设置cookie的模式:
　 # insert: 在回复中本模块通过Set-Cookie头直接插入相应名称的cookie。
　 # prefix: 不会生成新的cookie，但会在响应的cookie值前面加上特定的前缀，当浏览器带着这个有特定标识的cookie再次请求时，模块在传给后端服务前先删除加入的前缀，后端服务拿到的还是原来的cookie值，这些动作对后端透明。如：”Cookie: NAME=SRV~VALUE”。
　 # rewrite: 使用服务端标识覆盖后端设置的用于session sticky的cookie。如果后端服务在响应头中没有设置该cookie，则认为该请求不需要进行session sticky，使用这种模式，后端服务可以控制哪些请求需要sesstion sticky，哪些请求不需要。
   # option设置用于session sticky的cookie的选项，可设置成indirect或direct。indirect不会将session sticky的cookie传送给后端服务，该cookie对后端应用完全透明。direct则与indirect相反。
   # maxidle设置session cookie的最长空闲的超时时间
   # maxlife设置session cookie的最长生存期
   # maxage是cookie的生存期。不设置时，浏览器或App关闭后就失效。下次启动时，又会随机分配后端服务器。所以如果希望该客户端的请求长期落在同一台后端服务器上，可以设置maxage。
   # hash不论是明文还是hash值，都有固定的数目。因为hash是server的标识，所以有多少个server，就有等同数量的hash值。
    session_sticky [cookie=name] [domain=your_domain] [path=your_path] [maxage=time] [mode=insert|rewrite|prefix] [option=indirect] [maxidle=time] [maxlife=time] [fallback=on|off] [hash=plain|md5]

    server backend1.example.com;
    server backend2.example.com;
}
#+END_EXAMPLE

** 网络通信流程
#+BEGIN_EXAMPLE
client <-TCP/IP-> nginx <-TCP/IP-> web app
#+END_EXAMPLE

** Upstream服务宕机

检测机制：
1) Nginx将请求转发到后端服务时，才发起后端服务检测；
2) 由于 ~proxy_next_upstream~ 的默认值为 ~error timeout~ ，因此若当前请求发现后端服务异常后，会向集群中的下一个服务器发起请求，从而实现容灾；
3) 若后端服务有问题，则再次将请求转发到另一个健康的后端服务；

*** IP Hash
默认不会自动剔除，需要设置配置如下
#+BEGIN_EXAMPLE
upstream backend {
    ip_hash;
    server 192.1.2.1 down; # 设置这台后端状态为down，即不再转发这台后端
    server 192.1.2.2;
}
#+END_EXAMPLE
通过插件如health check监控和修改配置

** QA
1) 熔断机制

* 代理缓存(proxy cache)
  Nginx的proxy cache由proxy loader和proxy manager组成，缓存在磁盘上，而varnish则缓存在内存中(squid则出现比varnish更早)。
  HTTPD可缓存到磁盘或内存中。
  现在Nginx已经提供模块连接到Memcached。
  根据职责单一原理，反向代理应该专门处理请求转发，而静态内容(图片、文本等)应该放在专门的缓存服务器。然后配置反向代理根据请求URL转发请求到缓存服务器或应用服务器。
  但对于并发量不大的网点，可以将缓存服务集成到反向代理中，从而降低运维复杂度。

  注意：Nginx缓存中的键和缓存对象元数据存储为内存中，而值存储在磁盘上。

** 配置
   - ~proxy_cache_path~
     - 作用：设置缓存所在路径等信息
     - 语法
       #+begin_example bash
       proxy_cache_path path [levels=levels] [use_temp_path=on|off] keys_zone=name:size [inactive=time] [max_size=size]
       [manager_files=number] [manager_sleep=time] [manager_threshold=time]
       [loader_files=number] [loader_sleep=time] [loader_threshold=time]
       [purger=on|off] [purger_files=number] [purger_sleep=time] [purger_threshold=time];
       #+end_example
     - path 缓存数据存放的目录路径
     - levels 定义缓存目录的子目录级别数量和各级别目录的文件名由几个字符组成，最多3级子目录，每级子目录文件名多长2个字符。如1:2表示2级子目录，1级子目录的文件名称由1个字符，2级子目录的文件名称由2个字符组成。
     - keys_zone.name 键空间(位于共享内存中)的名称，一个键空间内包含多个键
     - keys_zone.size 键空间的大小，1MB能存放8000个键
     - max_size 缓存数据存放的目录的大小上限，若超过该上限Nginx会根据LRU规则清理缓存数据。
     - inactive 当缓存在指定时间内没有再被访问过，则被清理掉
     - use_temp_path 设置另一个目录用于存放临时文件，一般设置为关闭，防止不必要的数据拷贝。
     - 上下文：http
     - 示例
       #+begin_example bash
       http {
         proxy_cache_path /opt/app/cache levels=1:2 keys_zone=nginx_cache:10m max_size=1g inactive=60m use_temp_path=off;
       }
       #+end_example
   - ~proxy_cache <zone.name> | off~;
     - 作用：启用代理缓存
     - 默认值： ~proxy_cache off;~
     - 上下文：http,server,location
     - 示例：
       #+begin_src
       location / {
         proxy_cache nginx_cache;
       }

       # 若存在多个磁盘，可以将缓存分布到多个磁盘，从而提高读写速度
       proxy_cache_path /path/to/hdd1 levels=1:2 keys_zone=my_cache_hdd1:10m max_size=10g inactive=60m use_temp_path=off;
       proxy_cache_path /path/to/hdd2 levels=1:2 keys_zone=my_cache_hdd2:10m max_size=10g inactive=60m use_temp_path=off;
       split_clients $request_uri $my_cache {
         50% "my_cache_hdd1";
         50% "my_cache_hdd2";
       }

       server {
          ...
          location / {
            proxy_cache $my_cache;
            proxy_pass http://my_upstream;
          }
       }
       #+end_src
   - ~proxy_cache_valid [code...] time;~
     - code 为返回状态码
     - 作用：配置缓存过期时间
     - 上下文：http,server,location
     - 示例
       #+begin_example bash
       location / {
         proxy_cache nginx_cache; # 要先启用缓存，下面的设置才生效
         proxy_cache_valid 200 304 12h; #  对于response status code 为 200或304的则缓存12小时
         proxy_cache_valid any 10m; # 其它情况则缓存10分钟
       }
       #+end_example
   - ~proxy_cache_key string~
     - 作用：设置缓存的维度
     - 默认值： ~proxy_cache_key $scheme$proxy_host$request_uri~
     - 上下文：http,server,location
   - ~proxy_no_cache string...~
     - 作用：指定哪些条件下不缓存，当string为空时即为缓存，若其中某个string非空或为0则不缓存。
     - 上下文：http,server,location
     - 示例
       #+begin_example bash
       if ($request_uri ~ ^/(login|register|logon)) {
         set $cookie_nocache 1;
       }

       location / {
         proxy_no_cache $cookie_nocache;
       }
       #+end_example
   - ~proxy_cache_use_stale~
     - 作用：当应用服务器因宕机或繁忙等原因无法响应请求时，Nginx返回已过期的缓存内容给客户端。
     - 上下文：http,server,location
     - 示例
       #+begin_src
       # pdating表示缓存已过期但正在被别的Nginx Worker进程更新，但先返回了过期内容
       proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
       #+end_src
   - ~proxy_cache_revalidate off|on~
     - 作用：若缓存过期，那么当请求该资源时Nginx会向后端服务发起带If-Modified-Since或If-none-match的请求，若后端返回304，那么缓存自动续期并返回把缓存返回给客户端。
       默认为off，即即使Expires或Cache-Control过期，但Nginx缓存没有过期，则直接返回缓存内容，而不会先检查后端服务资源是否已更新过。
     - 当服务单返回304，那么$upstream_cache_status为REVALIDATED
     - 上下文：http,server,location
   - ~proxy_cache_min_uses n~
     - 作用：设置当同一链接被请求达到多少次后才缓存起来，默认为1次。
     - 上下文：http,server,location
   - ~proxy_cache_lock off|on~
     - 作用：防止缓存击穿，即缓存MISS后仅第一个请求会被转发到后端服务，其它请求均被阻塞直到缓存生效，返回缓存内容。
     - 上下文：http,server,location
   - ~proxy_cache_lock_age 5s~
     - 作用：Nginx 1.7.8 新增，在指定时间内缓存还没更新，那么后续请求则会发送到服务端。
     - 上下文：http,server,location
   - ~proxy_cache_purge <zone> <key>~
     - 作用: 清理缓存
     - 上下文：location
     - 示例: ~proxy_cache_purge tmpcache $uri$is_args$args;~
   - ~proxy_cache_bypass~
     - 作用：绕过缓存，直接转发请求到后端服务。
     - 上下文：location
     - $upstream_cache_status为BYPASS

** 调试
   在调试阶段于响应头中添加代理缓存命中信息，可有效查看配置是否成功。变量值如下
   1. MISS
   2. EXPIRED - expired, requesst was passed to backend
   3. UPDATING - expired, stale response was used dued to proxy/fastcgi_cache_use_stale updating
   4. STALE - expired, stale response was used dued to proxy/fastcgi_cache_use_stale updating
   5. HIT
   #+begin_example bash
   add_header Nginx-Cache "$upstream_cache_status from $server_addr";
   #+end_example

* 其它缓存
  1. 日志缓存 ~open_log_cache~
  2. 静态文件缓存 ~open_file_cache~
     - 缓存内容
       1. 文件描述符和相关元数据(大小、修改时间等)
       2. 文件和目录存在与否，和与查找相关的任何错误信息(权限被拒绝、文件未找到等)
  3. fastcgi缓存 ~fastcgi_cache~

* 读写分离
  PUT和DELETE方法由WebDAV提供：
  WebDAV(Web-based Distributed Authoring and Versioning) 是一种基于 HTTP1.1 协议的通信协议，扩展了HTTP1.1。在GET、POST和HEAD等几个HTTP标准方法以外添加一些新的方法。
  使应用程序可以对Web Server直接读写，并支持写文件锁定(Locking)和解锁(Unlocking)，还可以支持文件的版本控制。

  #+begin_src
  # 主节点位于 192.168.56.191
  # 备份节点位于 192.168.56.192
  # 若为PUT操作则请求转发到主节点
  location / {
    proxy_pass http://192.168.56.192;
    if ( $request_method = "PUT" ) {
      proxy_pass http://192.168.56.191;      
    }
  }
  #+end_src
* 安装
#+BEGIN_SRC
# 安装依赖
yum install gcc openssl-devel pcre-devel zlib-devel

# 创建用户组和不带家目录的用户
groupadd -r nginx
useradd -r -g nginx -M nginx

# 源码安装

# 配置
# --prefix 用于指定nginx编译后的安装目录
# --add-module 为添加的第三方模块，此次添加了fdfs的nginx模块
# --with..._module 表示启用的nginx模块，如此处启用了http_ssl_module模块
# 查看官方配置 ./configure --help | more
# 其中 --with..._module 表示默认没有启用，需要编译时添加
# 而 --without..._module 表示默认启用，需要编译时禁用
./configure \
  --prefix=/usr \ # 默认安装路径
  --sbin-path=/usr/sbin/nginx \ # Nginx可执行程序路径，路径不存在自动创建目录
  --conf-path=/etc/nginx/nginx.conf \ # 主配置路径
  --error-path=/var/log/nginx/error.log \ # 错误日志
  --http-log-path=/var/log/nginx/access.log \ # 访问日志
  --pid-path=/var/run/nginx/nginx.pid \ 
  --lock-path=/var/lock/nginx.lock \
  --user=nginx \
  --group=nginx \
  --add-module=../nginx-sticky-module \ 
  --with-http_ssl_module \
  --with-http_flv_module \
  --with-http_stub_status_module \ # 提供显示Nginx进程状态的http页面
  --with-http_gzip_status_module \ # 支持gzip压缩
  --with-http_realip_module \
  --with-file_aio \
  --http-client-body-temp-path=/var/tmp/nginx/client/ \ # 用户请求主体的缓存路径，必须保证路径存在
  --http-proxy-temp-path=/var/tmp/nginx/proxy/ \ # 代理缓存路径，必须保证路径存在
  --http-fastcgi-temp-path=/var/tmp/nginx/fcgi/ \
  --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi/ \
  --http-scgi-temp-path=/var/tmp/nginx/scgi/ \
  --with-pcre

# 编译
./make

# 安装
./make install
#+END_SRC

/etc/nginx/nginx.conf同级目录下带 ~.default~ 的文件为nginx默认的配置文件，而不带的是根据配置编译而生成的配置文件。
/etc/nginx/mime.types存储非文本文件类型MIME。

** 安装过程问题
1) 报 ~./configure:  error: the HTTP rewrite module requires the PCRE library.~
   - 安装 pcre-devel
2) 报 ~SSL modules require the OpenSSL library~
   - 安装　openssl-devel

* 命令
  #+begin_example bash
  # -t，执行nginx配置文件语法检查
  # -c，指定nginx配置文件路径
  nginx -t -c /path/to/nginx.conf

  # -s reload，重载nginx配置，会优雅的重启Nginx。
  # -s stop，立即停止服务
  # -s quit，优雅地停止服务
  # -s reopen，重新开始记录日志文件
  nginx -s reload -c /path/to/nginx.conf

  # 查看安装路径和已安装的模块等信息
  nginx -V 2>&1

  # 命令行设置指令并覆盖config文件的指令
  nginx -g "limit_rate 1024;"

  # 指定运行目录
  nginx -p /path/to/work_directory

  # 查看帮助
  nginx -h

  # 立刻停止服务
  kill -TERM $(cat /path/to/nginx.pid)
  kill -INT $(cat /path/to/nginx.pid)
  nginx -s stop

  # 优雅地停止服务
  kill -QUIT $(cat /path/to/nginx.pid)
  nginx -s quit

  # 重新打开日志
  kill -USR1 $(cat /path/to/nginx.pid)
  nginx -s reopen

  # 升级Nginx二进制可执行文件
  kill -USR2 $(cat /path/to/nginx.pid)

  # 优雅地关闭Nginx master进程
  kill -WINCH $(cat /path/to/nginx.pid)
  #+end_example

* Nginx的热部署/在线升级
  Nginx版本升级，或新增模块时使用。

  1. 编译目标版本的Nginx源文件，得到二进制可执行文件
  2. 备份原版本的Nginx二进制可执行文件 ~cp /path/to/nginx{,.old}~
  3. 用目标版本的Nginx二进制可执行文件覆盖原版本的
  4. 通知正在运行的Nginx主进程将要进行热部署
     - 原理：旧Nginx进程和新的Nginx进程都在运行，但新的请求都由新的Nginx来处理，旧Nginx进程仅处理已接收到的请求。
     - 步骤
       1. 运行新Nginx进程，并保留旧Nginx进程和移交请求处理权 ~kill -USR2 <old nginx master process pid>~
          - 问题：若原Nginx启动时是通过环境变量(~PATH~)的话(即不是通过绝对路径启动)，那么会报如下错误
            #+begin_quote
             execve() failed while executing new binary process “nginx” (2: No such file or directory)
            #+end_quote
          - 解决方法：必须采用绝对路径启动Nginx。
          - pid文件的变化：旧Nginnx的nginx.pid会移动到nginx.pid.oldbin，而nginx.pid则为新Nginx的master进程使用。
       2. 通知旧Nginx进程优雅地关闭worker进程，执行后旧Nginx的master进程依然在 ~kill -WINCH <old nginx master process pid>~
          注意：保留旧Nginx的master进程，那么当新Nginx有问题时可以回滚。
          - 回滚注意事项：若配置文件发生变化，则需要先回滚配置文件。
          - 回滚方式
            1. 方式一
               1. 旧主进程重新配置文件并拉起worker进程
                  #+begin_src bash
                  kill -HUP $(cat /path/to/nginx.pid.oldbin)
                  #+end_src
               2. 优雅地停止新Nginx的所有进程
                  #+begin_src bash
                  kill -QUIT $(cat /path/to/nginx.pid)
                  #+end_src
               3. 恢复旧Nginx二进制可执行文件
                  #+begin_src bash
                  cp -f /path/to/nginx.old /path/to/nginx
                  #+end_src
            2. 方式二
               1. 立刻停止新Nginx所有进程，旧Nginx主进程会自动拉起worker进程和恢复pid文件
                  #+begin_src bash
                  kill -TERM $(cat /path/to/nginx.pid)               
                  #+end_src
               2. 恢复旧Nginx二进制可执行文件
                  #+begin_src bash
                  cp -f /path/to/nginx.old /path/to/nginx
                  #+end_src
       3. 新Nginx运行正常后杀死原Nginx的master进程即可, ~kill -QUIT <old nginx master process pid>~

* 配置讲解
** 组成
主配置文件：/etc/nginx/conf/nginx.conf
然后在主配置文件中通过 ~include conf.d/*.conf~ ，引入子配置文件。
1. 由 *指令* 和 *指令块* 组成；
2. 每条指令以 ~;~ 结尾，指令与参数间以空格符号分割；
3. 指令块以 ~{}~ 将多条指令组织在一起；
4. ~include~ 指令允许引入多个配置文件以提升维护性；
5. ~#~ 为单行注释；
6. ~$~ 开头用于引用变量；
7. 部分指令的参数支持正则表达式；
8. 时间参数的单位
   - ms, milliseconds
   - s, seconds
   - m, minutes
   - h, hours
   - d, days
   - w, weeks
   - M, 30 days
   - y, 365 days
9. 空间参数的单位
   - 留空, bytes
   - k或K, kilobytes
   - m或M, megabytes
   - g或G, gigabytes

** 配置项
1) ~server server_name...~
   - 作用：设置虚拟主机的主机名
   - 上下文：http
   - 示例： ~server localhost;~, ~server localhost fsjohnhuang.io~
2) ~resolver ip~
   - 作用：设置DNS服务IP，nginx内部访问域名时均通过这个DNS解析
   - 上下文：http,server,location
3) ~resolver_timeout time~
   - 作用：设置DNS服务解析超时时间
   - 上下文：http,server,location
4) ~keepalive_timeout timeout [header_timeout]~
   - timeout 指定客户端的keep-alive连接超时时间，服务器将这个时间到期时关闭连接。
   - header_timeout 指定响应头 ~Keep-Alive: timeout=time~ 中的time值。从而让浏览器主动关闭连接。没有这个参数，Nginx不会返回Keep-Alive响应头。
   - 默认值： ~keepalive_timeout 75s~
   - 上下文：http,server,location
5) ~sendfile on | off;~
   - 作用：启用Linux的零拷贝
   - 默认值： ~sendfile off~
   - 上下文：http,server,location
6) ~tcp_nopush on | off;~
   - 作用：启用网络缓存，当发送的消息大小达到一定量时才统一发送出去。对于传输大文件而言有优势。
   - Nagle算法
     - 场景：当发送payload为1个字节而包头却为40个字节(IP头20字节+TCP头20字节)，将容易导致网络由于太多数据包，对于重负荷的网络而言会引发拥塞瘫痪。
     - 改进点：若发送端打算多次发送少量数据的数据包(即长度小于MSS的数据包)，那么发送端会先发送第一个小包，后面的数据包会缓存起来，直到下列其中一个条件满足才发送
       1. 发送端接收到接收端返回的ACK确认
       2. 当前数据属于紧急数据
       3. 缓存区满
     - TCP的Nagle算法默认是启用的
     - 适用场景：发送大批量数据，且接收端会及时作出回应
       1. telnet、rlogin等远程登录的长时间在线的应用
       2. 大文件传输
     - 不适用场景：及时发送小批量数据，或接收端不一定会及时回应
       1. 游戏服务器要及时跟踪用户的鼠标坐标。
       2. 没有使用keepalive的HTTP连接。在TCP四次挥手中向服务端向客户端发送FIN报文要等缓存区满才能发送，导致客户端处于FIN__WAIT2时间延长，即阻塞关闭socket的时间延长。
   - 默认值： ~tcp_nopush off~
   - 上下文：http,server,location
   - 注意：仅在 ~sendfile on~ 时生效
7) ~tcp_nodelay on | off;~
   - 作用：和 ~tcp_nopush~ 作用相反，启用时立即向网络发送消息。
   - 默认值： ~tcp_nodelay on~
   - 上下文：http,server,location
   - 注意：当连接为keepalive时才生效。
8) ~gzip on | off;~
   - 作用：启用gzip压缩
   - 默认值： ~gzip off~
   - 上下文：http,server,location
9) ~gzip_comp_level level~
   - 作用：设置压缩率级别，越大表示压缩率越大。值从1到10。
   - 默认值： ~gzip_comp_level 1~
   - 上下文：http,server,location
10) ~gzip_http_version 1.0|1.1~
    - 作用：设置压缩对应的HTTP协议版本，若HTTP版本与之不匹配则不启用GZip压缩。
    - 默认值： ~gzip_http_version 1.1~
    - 上下文：http,server,location
    - 注意：值为1.1则1.0不压缩，值为1.0则1.0和1.1均启用压缩。
11) ~gzip_types <mine> <mine>*;~
    - 作用：设置被压缩的文件的MIME类型，如 ~text/plain~, ~application/x-javascript~
    - 上下文：http,server,location
    - 示例
      #+begin_example
      gzip_types text/plain application/x-javascript;
      #+end_example
12) ~gzip_disable "regex"~
    - 作用：匹配正则表达式的请求，返回非压缩版本
    - 示例
      #+begin_example
      # IE6及以下的返回非压缩版本
      gzip_disable "MSIE [1-6]\.";
      #+end_example
13) ~gzip_vary on | off;~
    - 作用：给CDN和反向代理服务器使用，针对相同的URL，根据请求头字段Accept-Encoding来决定返回压缩还是非压缩版本的资源。
    - 默认值： ~gzip_vary off~
    - HTTP响应头Vary
      - 通过指明哪些请求头字段值可以作为缓存有效与否的依据，从而告知缓存代理服务器，其缓存的资源是fresh还是stale。
      - 详解：
        1) 用户代理请求A资源，缓存服务器转发请求到应用服务器，然后设置响应头Vary值为Accept-Encoding和User-Agent；(~Vary: Accept-Encoding,User-Agent~)
        2) 缓存服务器将A资源的URL+请求头Accept-Encoding值+请求头User-Agent值作为唯一键，缓存A资源；
        3) 用户代理再次请求A资源时，缓存服务器则通过A资源的URL+请求头Accept-Encoding值+请求头User-Agent值作为唯一键，试图读取A资源的缓存副本。
      - 特点：
        1) 内容来自请求头，如Accept-Encoding,User-Agent等
        2) 用户代理会将Vary的值也作为缓存是否有效的依据之一，若缓存中Vary值与服务器返回Vary值不同，则表示缓存失效
        3) Vary值为*时，表示任何请求都是唯一并且非缓存的
14) ~gzip_min_length size~
    - 作用：设置启用压缩的资源最小字节数，建议设置为 ~gzip_min_length 2k~
    - 默认值： ~gzip_min_length 0~
15) ~gzip_proxied off | expired | no-cache | no-store | private | no_last_modified | no_etag | auth | any~
    - 作用：作为反向代理时,当后端服务响应头包含Via时，启用或关闭后端服务返回的结果。
    - 默认值： ~gzip_proxied off;~ 关闭所有代理结果数据的压缩
    - 值解释
      - expired 若Header中包含Expires信息，则启用压缩
      - no-cache 若Header中包含Cache-Control: no-cache信息，则启用压缩
      - no-store 若Header中包含Cache-Control: no-store信息，则启用压缩
      - private 若Header中包含Cache-Control: private信息，则启用压缩
      - no_last_modified 若Header中不包含Last-Modified信息，则启用压缩
      - no_etag 若Header中不包含ETag信息，则启用压缩
      - auth 若Header中包含Authorization信息，则启用压缩
      - any 无条件启用压缩
    - 请求/响应头Via
      - 作用：用于记录请求从客户端发送到应用服务的过程中，经过的代理服务的信息
      - 详解：
        1) 请求经过代理服务A，那么代理服务A转发请求时会在请求头Via上追加服务A的信息；
        2) 请求经过代理服务B，那么代理服务A转发请求时会在请求头Via上追加服务B的信息，这是Via中包含A和B的信息；
        3) 请求p到达应用服务，那么应用服务即可通过请求头的Via得知经过的代理服务信息，然后在将信息原封不动地写入响应头Via返回；
        4) 响应返回到用户代理，那么用户代理也知道经过的代理服务信息。
16) ~gzip_buffers number size~
    - 作用：设置系统获取多少个多少字节的存储单元用于存储gzip压缩结果
    - 默认值：申请和未压缩资源的大小申请
    - 示例
      #+begin_example
      # 申请以8KB为存储单元大小，申请16个存储单元
      gzip_buffers 16 8k;
      #+end_example
17) ~http_gzip_static_module~ 内置模块
    - 作用：读取任何文件时均会先读取相同目录下的 ~.gz~ 文件，若没有才动态压缩或读取原文件。
    - 语法： ~gzip_static on | off;~
    - 默认值： ~gzip_static off;~
    - 注意：
      1) 该功能不受 ~gzip_types~ 设置的限制
      2) ~.gz~ 文件需要自行预先制作并放置好才行
         #+begin_example bash
         gzip -c 9 /path/to/uncompressed /path/to/compressed
         #+end_example
18) ~http_gunzip_module~
    - 作用：对于不支持gzip的用户代理，提供另一种压缩方式。一般不用。
19) ~expires~
    - 作用：添加响应头Cache-Control和Expires
    - 语法：
      1) ~expires time;~
         - time
           - 正数
             1) 当前系统时间+time作为Expires的值
             2) 将time转换为秒数，作为 ~Cache-Control: max-age=<time>~ 的值
           - 负数
             1) 当前系统时间+time作为Expires的值
             2) 设置 ~Cache-Control: no-cache~
         - 示例
           1) ~expires 30s;~ 缓存30秒
           2) ~expires 30m;~ 缓存30分钟
           3) ~expires 2h;~ 缓存2小时
           4) ~expires 30d;~  缓存30天
      2) ~expires epoch | max | off;~
         - epoch 则为将Expires设置为 ~1 January 1970 00:00:01 GMT~
         - max 则为将Expires设置为 ~31 December 2037 23:59:59 GMT~ ，而Cache-Control设置为10年
    - 默认值： ~expires off;~
    - 上下文：http,server和location
    - 示例
      #+begin_example bash
      # 缓存有效期为24小时
      expires 24h;
      #+end_example
20) ~add_header name value [always];~
    - 作用：添加响应头，如 ~Access-Control-Allow-Origin~ 做跨站资源请求
    - 坑：
      1. 发生 ~rewrite last~ 时，第一个匹配的location中的add_header指令将失效
         #+begin_src
         # 请求 /a 返回的响应头仅有 b: 2, 而没有a: 1。
         location =/a {
           add_header a 1;
            rewrite / /b;
         }
         location =/b {
           add_header b 2;
            return 204;
         }
         #+end_src
      2. 仅执行添加操作，而不是重写操作。如果已经存在某响应头，那么会出现重复响应头。其中最突出的就是 ~Content-Type~
         #+begin_src
         http {
           default_type application/octet-stream;
   
           server {
             # 响应头包含两个Content-Type
             # 1. Content-Type: application/octet-stream
             # 2. Content-Type: text/html; charset=utf-8
             location /duplicated_content_type {
               add_header Content-Type "text/html; charset=utf-8";
             }

             location /normal {
               default_type ""; # 清理默认Content-Type
               add_header Content-Type "text/html; charset=utf-8"; 
             }
           }
         }
         #+end_src
    - always: 无论response http code是什么都会添加该响应头
    - 上下文：server,location, if in location
    - 示例
      #+begin_example bash
      location ~ .*\.html?$ {
          add_header Access-Control-Allow-Origin http://www.jesonc.com;
          add_header Access-Control-Allow-Methods GET,POST,PUT,DELETE,OPTIONS;
          root /opt/app/code;
      }

      location ~ .*\.html?$ {
          # *表示允许所有域名跨站访问
          add_header Access-Control-Allow-Origin *;
          add_header Access-Control-Allow-Methods GET,POST,PUT,DELETE,OPTIONS;
          root /opt/app/code;
      }

      location / {
        if ($request_method = 'OPTIONS') {
           add_header 'Access-Control-Allow-Origin' '$http_origin';
           add_header 'Access-Control-Allow-Credentials' 'true';
           add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,DELETE,OPTIONS';
           add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,appcode,Authorization,InvOrgId';
           add_header 'Access-Control-Max-Age' 1728000;
           return 204;
        }
        add_header 'Access-Control-Allow-Origin' '$http_origin' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,DELETE,OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,appcode,Authorization,InvOrgId' always;

        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://zuul;
        break;
      }
      #+end_example
21) ~valid_referers none | blocked | server_names | string | regex...;~
    - 值类型：
      - none 表示直接从浏览器输入地址访问，那么$http_referer为空
      - blocked 表示$http_referer原来不为空，但被防火墙或代理删除了
      - server_names 设置$http_referer需要匹配某机器名
      - string 设置$http_referer需要匹配某IP或某域名
      - regex 正则表达式匹配
    - 作用：根据$http_referer变量实现简单的防盗链功能
    - 上下文：server,location
    - 示例
      #+begin_example bash
      valid_referers none blocked 116.62.12.41 ~/google\./;
      # valid_referers若匹配失败则会将$invalid_referer设置为1
      if ($invalid_referer) {
          return 403;
      }
      #+end_example
22) ~return code [text | url]~ 或 ~return url~
    - text 可以为普通字符串、json或使用变量，它将作为响应体
    - url 必须以http或https开头
    - 作用：向客户端直接返回响应状态码
    - 上下文：server,location,if
    - 示例
      #+begin_example bash
      return 200 "ok";
      return 200 '{"name":"john","id": 123}';
      return 200 "$host $request_uri";
      # 请求重定向
      return 301 http://fsjohnhuang.io;
      # 默认302重定向，302不会影响SEO
      return http://fsjohnhuang.io;
      #+end_example
    - 注意：return指令后的其他指令将不会被执行
23) ~server_tokens on | off~
    - on 作为默认值，在响应头Server中显示版本号，形如 ~Server: nginx/版本号~
    - off 隐藏版本号，形如 ~Server: nginx~
    - 作用：安全优化-隐藏版本号
    - 上下文：http,server,location
24) ~ssi off |  on~
    - 作用：启用Server Side Include。建议禁用。
    - SSI
      - 定义：是一种基于服务端的网页制作技术。就是在将页面内容发送给客户端前，使用SSI指令将文本、图片和其它网页内容添加到当前响应中。
      - 语法：
        - 引入资源 ~<!--#include file="layouts/menu.shtml"-->~
    - 上下文: location
    - 问题：若找不到相应的资源，那么整个响应会报404异常。而通过http_addition_module的add_before_body引入资源，找不到资源时仅引入内容为空，但不影响原来的响应结果。
25) ~ssi_slient_errors off | on~
    - 作用：开启后在处理SSI文件出错时不输出错误提示:”[an error occurred while processing the directive] ”
    - 上下文: location
26) ~ssi_types text/shtml~
    - 作用：默认是ssi_types text/html，所以如果需要htm和html支持，则不需要设置这句，如果需要shtml支持，则需要设置：ssi_types text/shtml
    - 上下文: location
27) ~limit_rate <size>~
    - 作用: 对客户端一个连接设置每秒传输的最大字节数，限速。由于网络带宽有限，因此应该限制某些数据大但相对没有那么重要的资源设置限速，让出带宽给那些重要的数据量小的资源，从而提供重要资源的响应速度。
    - 默认值: no
    - 上下文: http, server, location
    - 示例: ~limit_rate 512k~
    - 或者通过设置变量的方式设置 ~set $limit_size 512k~
    - 注意：由于limit_rate仅限制一个连接的每秒传输上限，所以要配置limit_conn限制并发连接数，才能限制总体的每秒传输数据量。
28) ~limit_rate_after <size>~
    - 作用: 设置客户端一个连接接收多少字节后将启用限速，如果不超过该值则不限速。
    - 默认值: no
    - 上下文: http, server, location
    - 示例: ~limit_rate_after 1m~

** TODO 变量
1) 内置变量：由Nginx模块引入，可直接使用
   - ~$uri~ 不含query string的以/开头的请求路径
   - ~$document_uri~ 与 ~$uri~ 一样
   - ~$args~ query-string
   - ~$query_string~ 与 ~$args~ 一样
   - ~$is_args~ 若请求中带有query_string则返回 ~?~, 否则返回空字符串
   - ~$request_uri~ 含query-string的完整的客户端请求路径
   - ~$request_method~ 请求方式
   - ~$request~ 请求头部信息, 如 ~HEAD /main/index?a=1 HTTP/1.1~
   - ~$scheme~ 协议,返回HEAD/POST/GET/PUT/DELETE等
   - ~$request_filename~ 表示用户请求通过root或alias转换后的文件路径,默认为index.html
   - ~$host~ 不含端口的域名/主机名/IP
   - ~$remote_addr~ 客户端IP
   - ~$binary_remote_addr~ 客户端IP，比 ~$remote_addr~ 省出1个字节
   - ~$remote_port~ 客户端端口号
   - ~$remote_user~ 使用Auth Basic Module时定义的用户名
   - ~$http_user_agent~ 客户端代理信息
   - ~$http_referer~ 获取REFERER请求头
   - ~$http_x_forwarded_for~ 记录客户端、代理服务器的IP地址列表，每个IP间以逗号分隔
   - ~$hostname~ nginx所在机器的主机名
   - ~$server_addr~ 服务器IP
   - ~$server_name~ 服务域名
   - ~$server_port~ 服务端口号
   - ~$server_protocol~ 服务器向客户端响应的协议,返回HTTP/1.1 或 HTTP/1.0
   - ~$time_local~ 服务器本机时间
   - ~$status~ 响应返回码
   - ~$body_bytes_sent~ 响应消息的字节数，不包含响应头的字节数
   - ~$bytes_sent~ 响应消息的总字节数
   - ~$request_time~ TTFB
   - ~$response_time~ nginx与upstream建立连接到关闭连接的时间
   - ~$msec~ 日志写入时间，单位为秒，精度到毫秒
2) HTTP请求变量
   1) arg_PARMETER
   2) http_HEADER, 客户端发送的请求的HEADER
      - ~$http_user_agent~ 获取请求头的USER-AGENT
   3) sent_http_HEADER，服务端返回的响应的HEADER

3) 自定义变量：用户通过 ~set variable_name value;~ 定义
4) 使用变量： ~$variable_name~

** 全局配置
对下面的http/mail/stream等都起作用，主要分为
1) 正常运行必备的配置
2) 优化性能的配置
   - ~limit_rate 50k~ 限速50k,设置为0则表示没有限速
3) 用于调试及定位问题的配置
4) 事件驱动的配置

** 最佳示例
#+BEGIN_EXAMPLE
# 工作进程的启用用户，当工作进程被黑掉时也只能操作nobody用户能操作的文件而已
# 若设置user则master process必须用root，即要以root身份启动nginx
user nobody;
# 工作进程数，默认为auto，和CPU物理核数相同
# 当为CPU密集型应用，如SSL或压缩应用则worker进程数与CPU核数相同
# 当为IO密集型应用，如图片下载服务，则worker进程数为CPU核数的1.5或2倍
worker_processes 8;

# 为每个进程绑定到指定的CPU物理核上(一个核可以绑定多个进程)，那么在并发和进程切换时效率更高
worker_cpu_affinity 00000001 00000010 00000100 00001000 00010000 00100000 01000000 10000000;

# 配置Nginx worker进程最大打开文件数
# 修改操作系统每个进程最大打开的文件描述符数量，ulimit -n 65535
# 永久调整，在/etc/rc.d/rc.local中添加ulimit -n 65535
worker_rlimit_nofile 65535;

# 全局错误日志
error_log /var/log/nginx/error.log;
# PID文件
pid /var/run/nginx.pid;

# 引入其他配置文件的内容
include /etc/nginx/modules-enabled/*.conf

# 工作模式和连接数上限
events {
  # use [kqueue|rtsig|epoll|/dev/poll|select|poll]
  # epoll是Linux 2.6+的高性能网络I/O模型
  # kqueue是FreeBSD的高性能I/O模型
  # select是轮询
  # 默认会自动选择最优的模型
  use epoll;

  # 单进程最大连接数
  # 理论的总体最大连接数=连接数*进程数
  # 实际的总体最大连接数=连接数*进程数/4，除以4是经验值来的
  # 连接为一种文件描述符，因此受到系统文件描述相关设置的限制
  worker_connections 1024;

  # 并行接收链接
  mulit_accept on;
}

http {
  # 引入外部的配置项目，若设置相对路径时，则是相对于当前配置文件
  include /etc/nginx/mime.type;
  # 默认mime类型
  default_type application/octet-stream;
  # 默认响应报文的字符编码
  charset utf-8, gbk;
  # 访问日志, 设置写入高速IO或设置为关闭 access_log off;
  access_log /var/log/nginx/access_log main buffer=16k;
  # 隐藏响应头中的有关操作系统和web server（Nginx）版本号的信息，这样对于安全性是有好处的。
  server_tokens off;

  # 静态资源文件描述符缓存
  open_file_cache max=2000 inactive=20s;
  open_file_cache_valid 30s;
  open_file_cache_min_uses 2;
  open_file_cache_error on;

  # 若禁用sendfile，那么响应静态的过程是
  # 1. 内核从磁盘读取数据到内核的receive buffer
  # 2. 从内核的receive buffer读取并复制数据到用户态的内存空间
  # 3. 从用户态的内存空间读取并复制数据到内核态的TCP/IP栈封装
  # 4. 发送给客户端
  # 若启用sendfile(零拷贝)，那么响应静态的过程是
  # 1. 内核从磁盘读取数据到内核的receive buffer
  # 2. TCP/IP栈封装receive buffer数据
  # 3. 发送给客户端
  sendfile on;

  # 启用buffer: 数据先保存到buffer中，若buffer满或调用flush时才向网络写入
  # 默认关闭，当传输大文件时可能会有问题
  # tcp_nopush causes nginx to attempt to send its HTTP response head in  one pack instead of using partial frames.
  # This is useful for prepending headers before calling sendfile, or for  throughput optimization.
  tcp_nopush on;

  # 对于小数据报文则及时发送，而不采用Nagle算法缓存数据。  
  # don't buffer data-sends(disable Nagle algorithm). Good for sending frequent small bursts of data in real time.
  tcp_nodelay on;

  # TCP连接保持时间，单位秒
  keepalive_timeout 30;
  # 单个客户端在单个keep-alive链接上可以发送的请求数上线。
  keepalive_requests 100000;

  # 以下设置为限制缓冲区大小，防止缓冲区溢出攻击(若溢出则会使用swap区，大大降低Nginx处理请求的效率)。
  # 客户端请求头部(request_line和request_header)的缓冲区，一般设置内存分页大小或整数倍。
  # getconf PAGESIZE
  client_header_buffer_size 4k;
  # 当client_header_buffer_size的大小无法容纳request_line和request_header，
  # 那么就会根据large_client_header_buffers的容量容纳request_line和request_header，
  # 若缓存还是空间不足则会返回414(无法缓冲request_line)或400(无法缓冲request_header)
  # 参数：缓存个数 每个缓存区的容量
  large_client_header_buffers 4 4k;
  # 客户端请求体的缓冲区，一般设置内存分页大小或整数倍。
  client_body_buffer_size 4k;
  # 设置请求报文主体大小的上限，可以理解为客户端上传文件大小的上限。若超过则返回413。
  # 原理，就是通过请求头的Content-Length获取主体大小。
  # 设置为0表示不限制。
  # 默认为1m
  # 上下文：http, server, location
  client_max_body_size 8m;

  # 客户端与Nginx建立连接时，Nginx会先读取HTTP请求头，若在指定时间内读取失败则返回408(Request timed out)
  # 默认值：60秒
  # 上下文: http, server, locaiton
  client_header_timeout 10;
  # Nginx读取HTTP请求体，若在指定时间内读取失败则返回408(Request timed out)
  # 默认值：60秒
  # 上下文: http, server, locaiton
  client_body_timeout 10;
  # Nginx向客户端发送数据，若客户端在指定时间内没有开始接收数据则Nginx关闭该连接。
  # 默认值：60秒
  # 上下文: http, server, locaiton
  send_timeout 60;
  # 
  # 默认值：off
  # 上下文: http, server, locaiton
  reset_timeout_connection on;

  # 限制并发量
  limit_conn_zone $remote_addr zone=lc:5m;

  # 内容压缩
  gzip on;
  gzip_min_length 10240;
  gzip_disable "MSIE [1-6].";
  gzip_types text/plain text/css text/html text/javascript application/x-javascript application/xml application/json;
  gzip_comp_level 2;
  gzip_proxied expired no-cache no-store private auth;
  gzip_vary on;
  gzip_http_version 1.1;
  gzip_buffers 4 16k;

  # 为快速通过文件扩展名找到MIME type，Nginx使用散列表存储MIME type和文件扩展名。
  # 设置每个散列捅占用的内存大小
  # 默认值: 32
  # 取值范围：32,64,128
  # 上下文: http, server, locaiton
  types_hash_bucket_size 32;

  # 值越大所需内存越大，散列key的冲突越小
  # 默认值: 1024
  # 上下文: http, server, locaiton
  types_hash_max_size 2048;

  # 虚拟服务器配置节点
  server {
    listen 80; # 多个虚拟服务器可以指向同一个端口，然后通过server_name来区分由哪个虚拟服务器响应
    server_name www.domain1.com;

    # 限制同一个客户端的并发量
    limit_conn lc 50;
    limit_conn_log_level notice;
    limit_conn_status 503;

    location / {
      # 将请求URI的根目录映射到指定的文件系统目录，若这里采用的是相对路径，则为相对于nginx的安装目录而言
      # 例如 location /abc/123 { root www/htdoc } 那么请求URI为/abc/123/index.html时则会访问 www/htdoc/abc/123/index.html
      # 若返回404等则可以查看/var/log/nginx/error.log
      root html;
      autoindex on; # 显示目录结构
      autoindex_exact_size on; # 显示文件大小
      autoindex_localtime off; # 以当前操作系统的时区显示文件的修改时间 
    }

    error_page 404 /404.html # 相对于nginx的安装目录

     # 虚拟目录
     # 访问/virtual_directory/index.html，会返回/home/wwwroot/lnmmp/test/index.html的内容
     location /virtual_directory/ {
       alias /home/wwwroot/lnmmp/test/;
     }
  }

  server {
    listen 80;
    server_name www.domain2.com;

    location / {
      root /mnt; # 绝对路径
      index index.html index.htm; # 默认首页
    }

    location /abc {
      try_files /;
    }

    error_page 500 505 /50x.html;
    # 通过location定义 /50x.html 的实际路径，而不是直接相对于nginx的安装目录。
    location = /50x.html {
      root /mnt/50x;
      index index.html;
    }

    # 响应静态文件p
    location ~ ^/(images|javascript|js|css|flash|media|static)/ {
      root /var/www/virtual/htdocs; 
      expires 30d; # 缓存30天

      # 静态资源禁止记录访问日志
      access_log off;

      # 限制请求方法
      if ( $request_method !~ ^GET$ ) {
        return 501;
      }

      # 防盗链
      valid_referers none blocked *.myweb.com myweb.com;
      if ( $invalid_referer ) {
        return 403;
      }
    }

    # 查看Nginx状态
    location /NginxStatus {
      stub_status on;
      access_log off;
      allow 127.0.0.1;
      deny all;
      auth_basic "NginxStatus";
      auth_basic_user_file conf/htpasswd;

      # 显示的内容
      # active connection 当前处于打开状态的连接数
      # server accepts handled requests 下3个数字分别表示
      # 1 已经接收过的连接数 2 已经处理过的连接数 3 已经处理过的请求数。一个连接可以存在多个请求。
      # reading 正在读取请求头的连接数
      # writing 正在读取请求主体、处理请求或响应给客户端的连接数
      # waiting keep-alive链接，就是处于活动状态的连接数-reading-writing
    }

    # 禁止访问.hxxx文件
    location ~ /\.ht {
      deny all;
    }

    # 允许部分IP访问
    location /private/ {
      deny 127.0.0.1;
      allow 180.0.0.1;

      root /var/www/virtual/htdocs/private;
      index index.html;
    }
  }

  server {
    listen 443;
    server_name ssl_server;
    
    ssl on; # 启用ssl
    ssl_certificate cert.pem; # 证书
    ssl_certificate_key cert.key; # 密钥
    ssl_session_timeout 5m; # 会话超时为5分钟
    ssl_protocols SSLv2 SSLv3 TLSv1; # 可选用的协议类型
    ssl_ciphers HIGH:!aNULL:!MD5; # 加密算法
    ssl_prefer_server_ciphers on; # Nginx自主选择当前服务器最优加密算法

    location / {
      root /www;
      index index.html;
    }
  }
}
#+END_EXAMPLE
URI: /abc/test.html
URL: http://www.baidu.com/abc/test.html

** Location请求处理匹配
1) 通过请求的ip、端口(listen)和域名(server_name)匹配虚拟服务器
2) 通过URI匹配location
   1) 普通匹配
      1) 匹配顺序与定义顺序无关
      2) 最大前缀匹配
      3) 从上之下匹配，匹配所有普通匹配后选择最符合最大前缀匹配的
   2) 正则匹配
      1) 从上至下匹配，匹配成功马上应用，不再往下匹配
   3) 整体匹配流程
      1) 普通匹配
         1) 命令 ~=~ 匹配时就结束整个匹配流程
         2) 命中 ~^~~ 匹配时就结束整个匹配流程
         3) 其他情况为最大前缀匹配，则转入正则匹配的子流程。若正则匹配失败则采用当前最大前缀匹配项。
      2) 正则匹配
#+BEGIN_SRC
# 注意：模式匹配符与URI之间不要存在空格，尤其是=。
# 若之间存在空格，那么该location将无效
location [=|~|~*|^~]URI {}
#+END_SRC
#+BEGIN_EXAMPLE bash
# 匹配当前路径及子路径下的所有对象
location URI {}
# 通用匹配，任何请求都会匹配到
location / {}
# 精确匹配指定路径
location =URI {}
# 匹配以URI开头的的URL路径，命中则停止匹配流程
location ^~URI {}
# 大小写敏感正则匹配
location ~URI {}
# 大小写不敏感正则匹配
location ~*URI {}
# 区分大小写的正则非匹配
location !~URI {}
# 不区分大小写的正则非匹配
location !~*URI {}
#+END_EXAMPLE

示例：
#+begin_src
location =/ { A }
location / { B }
location /documents/ { C }
location ^~/images/ { D }
location ~*\.(gif|jpg)$ { E }

/ -> A
/index.html -> B
/docments/index.html -> C
/images/logo.gif -> D
/documents/logo.gif -> E
#+end_src

注意： 请求路径为 ~/static/%20/a~ 将匹配 ~location =/static/ /a~

** Rewrite
通过使用nginx内置变量和自定义变量,结合正则表达式和标志位实现在同一域名下的URI重写和重定向.
语法： ~rewrite regex replacement [flag]~ ,根据正则表达式匹配原URL中的PATH、QueryString和Hash信息，然后跳转到replacement指定的地址。
使用范围: 在server/location/if块中使用.
执行顺序:
1) 执行server块的rewrite命令
2) 执行location匹配
3) 执行匹配的location中的rewrite命令

应用场景：
1) 调整用户浏览器URL
2) 让搜索引擎收录网站内容
3) 网站更换域名
4) 根据特殊变量、目录和客户端信息进行跳转

#+begin_src
server_name test.com;

# 请求 test.com/bbs/index.html 时，那么浏览器URL地址栏不变，但实际返回的是 test.com/forum/index.html 的内容
location / {
  root html;
  index index.html;
  rewrite ^/bbs/(.*)$ /forum/$1;
}
#+end_src

*** flag
1) last, 表示完成本次rewrite，重启一下轮检查。一般写在server和if中
   #+begin_src
   server_name test.com;
   # 请求 test.com/bbs/index.html 时，那么浏览器URL地址栏不变，但Nginx内部会重新以 test.com/forum/index.html 来匹配location，并重新进入 location / 块。
   # 由于 /forum/index.html 不匹配 ^/bbs/(.*)$，因此跳过rewrite指令并返回 $NGINX_HOME/html/forum/index.html 的内容。
   location / {
     root html;
     rewrite ^/bbs/(.*)$ /forum/$1 last;
   }

   # 请求 test.com/abc/a 时，那么浏览器URL地址栏不变，但Nginx内部会重新以 test.com/abc/a/index.html 来匹配location，并重新进入 location /abc/ 块。
   # 而 /abc/a/index.html 匹配 ^/abc/(.*)$，因此再次执行rewrite指令，导致陷入rewrite死循环中。
   location /abc/ {
     root html;
     rewrite ^/abc/(.*)$ /abc/$1/index.html last;
   }
   #+end_src
2) break, 表示完成本次rewrite后，不再在Nginx内部重新匹配location，而是直接执行后续操作(如读取文件返回响应)。一般写在location中
   #+begin_example bash
   # 请求/abc/a时，返回 $NGINX_HOME/html/abc/a/index.html 的内容
   location /abc/ {
     root html;
     rewrite ^/abc/(.*)$ /abc/$1/index.html break;
   }
   #+end_example
3) redirect, 返回302临时重定向
   #+begin_example bash
   if ($http_host !~ "^fsjohnhuang\.io") {
       rewrite ^/(.*) http://fsjohnhuang.io/$1 redirect;
       # 或直接写成 rewrite ^/(.*) http://fsjohnhuang.io/$1; 即可
   }
   #+end_example
4) permanent, 返回301永久重定向
   #+begin_example bash
   if ($http_host !~ "^fsjohnhuang\.io") {
       rewrite ^/(.*) http://fsjohnhuang.io/$1 permanent;
   }
   #+end_example

** index指令
1) index指令后跟多个文件路径
2) 多个文件路径间用空格分隔
3) 相对路径在前绝对路径在后
4) Nginx从左至右检查文件是否存在,若存在则发起内部重定向

上下文：server,location

#+BEGIN_EXAMPLE
index index.html index.0.html /index.htm;
#+END_EXAMPLE

** 文件描述符
1) 文件描述符的数量跟内存有关（1G内存大概支持10W个文件描述符）
   1) 查看系统支持的最大文件描述符数量 ~cat /proc/sys/fs/file-max~
2) 每个进程也有可以打开的文件描述符数限制
   1) 查看 ~ulimit -a~ 回显中 open files 或 file descriptors行的数字
   2) 修改 ~ulimit -SHn 123~
3) 异步IO会产生两个文件描述符

** 日志
   1) 类型
      1) 错误日志
         - 上下文：在配置文件最外层设置 或 http块中设置
         - 语法： ~error_log <path> [level]~
           - <日志文件路径> [日志级别]
           - debug、info、notice、warn、error、crit、alert、emerg，从左至右，日志详细程度逐级递减，即 debug 最详细，emerg 最少，默认为 error。
           - 注意：error_log off 并不能关闭错误日志记录，此时日志信息会被写入到文件名为 off 的文件当中。
             #+begin_src
             # 关闭错误日志记录
             error_log /dev/null;
             # error_log nul; # Windows系统的设置
             #+end_src
         - 设置方式
           #+begin_example bash
           # crit为默认值，即最简洁的日志消息
           # 关闭错误日志：error_log /dev/null;
           error_log /var/log/nginx/error.log [level=debug|info|notice|warn|error|crit];
           #+end_example
         - 注意：日志格式不支持自定义
      2) 访问日志
         - 日志格式 —— ~log_format~
           - 上下文：在http块中设置
           - 语法： ~log_format name [escape=default|json] string ...;~
             - <日志格式名称> <日志格式字符串> ...
           - 默认值: ~log_format combined ...;~
           - 示例
             #+begin_example bash
             # 虽然下面日志格式设置分为多行，但实际打印的日志记录仅占一行
             log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                             '$status $body_bytes_sent "$http_referer" '
                             '"$http_user_agent" "$http_x_forwarded_for"';
             #+end_example
         - 日志定义 —— ~access_log~
           - 语法： ~access_log <path> <log_format_name>;~
             - <日志文件路径> <日志格式名称>
           - 示例
             #+begin_example bash
             # 设置将访问日志写入缓存，每5秒写入磁盘。
             # 关闭访问日志 access_log off;
             access_log /path/to/access_log main buffer=32k flush=5s;
             #+end_example
         - 分割日志
           - 步骤：
             1. 复制日志文件 ~cp access_log{,.bk}~
             2. 执行 ~nginx -s reopen~
           - 批处理文件
             #+begin_src bash
             #!/bin/bash
             log_path=/apps/var/log/nginx
             hist_log_path=/apps/var/log/nginx/history
             yesterday=$(date -d "yesterdy" +%Y-%m-%d)
             mv ${log_path}/access_log ${hist_log_path}/access_log_${yesterday}
             mv ${log_path}/error_log ${hist_log_path}/error_log_${yesterday}
             # 效果和nginx -s reopen一样
             kill -USR1 $(cat /usr/local/nginx/nginx.pid)
             #+end_src

** 通过GoAccess可视化access_log
   1. 安装GoAccess到Nginx所在服务器
   2. 启动GoAccess
      #+begin_src bash
      # 当日志格式采用默认值时，--log-format设置为COMBINED即可
      goaccess /path/to/nginx/access_log -o $NGINX_HOME/html/access_log.html --real-time-html --time-format='%H:%M:%S' --date-format='%d/%b/%Y' --log-format=COMBINDED
      #+end_src
   3. nginx.conf配置
      #+begin_src
      location =/access_log {
        alias html/access_log.html;
      }
      #+end_src

* 模块
1.9.11版本后支持DSO（动态装载和卸载模块）

分类：
1) 核心模块：core module
2) 标准模块：
   1) HTTP：ngx_http_*
      1) HTTP Core modules 默认功能
      2) HTTP Optional modules 编译时指定
   2) Mail：ngx_mail_*
   3) Stream：ngx_stream_*　TCP/IP转发
3) 第三方模块：
   1) https://www.nginx.com/resources/wiki/modules/index.html


分为handler,filter,upstream

FastCGI转发请求到PHP，导致并发瓶颈在FastCGI+PHP上，因此通过ngx_lua处理动态内容提高并发数．

map模块

shared memory

** 官方模块
   1) http_stub_status_module
      - 作用：显示当前处理的连接信息
      - 语法： ~stub_status;~
      - 默认值：禁用
      - 上下文：server 和 location 块下设置
      - 使用示例
        1) 配置
           #+begin_example bash
           location /info {
             stub_status;
           }
           #+end_example
        2) 访问 /info 页面
           #+begin_example html
           Active connections: 2
           server accepts handled requests
           396 396 1293
           Reading: 0 Writing: 1 Waiting: 1
           #+end_example
           - Active connections 表示当前活跃的连接数。(Reading+Writing+Waiting = Active connections)
           - 第一个396 表示总握手数；第二个396 表示总连接数；第三个1293 表示总请求数。(当第一和第二个数相等时，即连接没有丢失)
           - Reading 表示正在读的连接数
           - Writing 表示正在写的连接数
           - Waiting 表示当开启keepalive_timeout时，既没有写也没有读，只是在等待的连接数
   2) http_random_index_module
      - 作用：在root指定的目录下，随机选择一个页面作为主页
      - 语法： ~randome_index on | off;~
      - 默认值：off
      - 上下文：location 块下设置
   3) http_sub_module
      - 作用：HTTP内容替换
      - ~sub_filter string replacement;~
        - 作用：将匹配的字符串替换为目标字符串
        - 上下文：http,server和location块中
      - ~sub_filter_last_modified on | off;~
        - 作用：判断文件的修改日期是否更新，有则发送无则不发送
        - 默认值：off
        - 上下文：http,server和location块中
      - ~sub_filter_once on | off;~
        - 作用：配合 ~sub_filter~ ，表示仅替换第一个匹配的字符串，还是所有匹配的字符串
        - 默认值：on
        - 上下文：http,server和location块中
   4) limit_conn_module
      - 作用：用于限制同一个IP地址的TCP连接并发连接数
      - 使用
        1) 配置连接信息存储空间
           - 语法： ~limit_conn_zone key zone=name:size;~
             - key 指定某值作为空间的键，如 ~$remote_addr~
             - name 指定空间的名称
             - size 指定空间的大小
           - 上下文：http 块
        2) 配置并发限制
           - 语法： ~limit_conn zone number;~
             - zone 为 ~limit_conn_zone~ 中的name
             - number 为并发连接数的限制
           - 上下文：http, server 和 location 块
        3) 配置请求被拒绝的响应状态码
           - 语法: ~limit_conn_status 503~
           - 上下文：http, server 和 location 块
        4) 配置当达到连接限制时，错误日志的日志级别
           - 语法: ~limit_conn_log_level info | notice | warn | error~
           - 上下文：http, server 和 location 块
      - 示例：
        #+begin_src
        http {
          limit_conn_zone $remote_addr zone=lc:10m;

          server {
            limit_conn lc 50;
            limit_conn_status 503;
            limit_conn_log_level notice;
          }
        }
        #+end_src
   5) http_limit_req_module
      - 作用：限制HTTP请求的处理速率，即限流
      - 使用
        1) 配置连接信息存储空间
           - 语法： ~limit_req_zone key zone=name:size rate=rate;~
             - key 指定某值作为空间的键，如 ~$binary_remote_addr~
             - name 指定空间的名称
             - size 指定空间的大小
             - rate 指定处理请求队列中请求的频率，如 ~1r/s~ 表示每秒处理1个， ~5r/s~ 表示每秒处理5个
               表示允许相同标识的客户端的访问频次，这里限制的是每秒1次，即每秒只处理一个请求，还可以有比如 30r/m ， 即限制每 2秒 访问一次，即每 2秒 才处理一个请求。
           - 上下文：http 块
        2) 配置并发限制
           - 语法： ~limit_req zone=name [burst=number] [nodelay];~
             - zone=name 为 ~limit_req_zone~ 中的name
             - burst=number 请求队列的长度(默认为0)，清空最大时间为 ~burst/rate~. 超过这个缓冲区的请求直接报503并返回.
             - nodelay 
               - 默认延期时，采用rate的速率处理请求，超出部分缓存到burst的队列中，然后按rate的速率处理burst队列中的请求。若burst满了则后续请求均返回503
                 - 例如：rate=5r/s, burst=5, 那么并发11个请求，前5个请求处于处理中，后5个请求入队列，最后的1个请求返回503。最终2秒处理10个请求。
               - 禁用延期时，则采用rate+burst的速率处理请求，超出部分返回503。
                 - 例如：rate=5r/s, burst=5, 那么并发11个请求，马上处理rate+burst个请求，后续请求返回503。最终一秒内处理10个请求。
           - 上下文：http, server 和 location 块
      - 注意：
        1) 服务一次仅能处理一个请求，其余并发请求均会放进请求队列中，然后按照rate的频率来处理。
           #+begin_example bash
           limit_req_zone $binary_remote_addr zone=req_zone:1m rate=10r/s;
           # 由于请求队列的长度默认为0, 因此rate设置为10r/s的效果与设置为1r/s的是一样的；
           # 仅有一个请求能被正常处理并响应，其它均返回503。
           limit_req zone=req_zone;

           limit_req_status 503;
           # 默认值为error
           limit_req_log_level info | notice| warn | error;
           #+end_example
        2) 当请求频率超出限制后，后续的请求将被拒绝服务(503)。并且被拒绝的请求记录将被保存到error_log指定的文件中。
      - 示例
        #+begin_example
        limit_req_zone $binary_remote_addr zone=req_zone:1m rate=1r/s;
        limit_req zone=req_zone burst=3 nodelay;
        #+end_example
   6) http_access_module
      - 作用：基于IP的访问控制
      - 语法
        - allow： ~allow address | CIDR | unix: | all;~
          - address 为IP
          - CDIR 为网段，如 ~168.10.23.0/24~
          - unix: 为unix的文件socket
          - all 为匹配所有
        - deny： ~deny address | CIDR | unix: | all;~
          - address 为IP
          - CDIR 为网段，如 ~168.10.23.0/24~
          - unix: 为unix的文件socket
          - all 为匹配所有
      - 上下文：http,server,location和limit_except
      - 注意：
        1) allow和deny要成对出现，才能精确实现允许和拒绝的访问控制；若要拒绝所有则只写 ~deny all~ 即可。
        2) 匹配为子上而下，若先匹配allow成功则表示可以访问，若先匹配deny成功则表示不可以访问。若没有匹配成功则表示可以访问。
        3) 基于变量 ~remote_addr~ 来匹配规则的。
           - 问题：无法精确实现访问控制
           - 解决办法：
             1) 采用HTTP_X_FORWARD_FOR，但不是所有客户端或代理服务器都使用该字段，并且可以被任意修改
             2) 结合geo模块
             3) 通过HTTP自定义变量传递
      - 示例
        1) 限制某个网段和某个IP的访问，其他均可以访问
           #+begin_example
           deny 186.10.2.0/24;
           deny 186.10.3.2;
           allow all;
           #+end_example
        2) 仅允许某个IP的访问
           #+begin_example
           allow 186.10.2.4;
           deny all;
           #+end_example
        3) 禁止所有人访问
           #+begin_example
           deny all;

           # 由于第一个指令已经说明拒绝所有IP访问，因此下面的语句均无效
           allow 186.10.2.4;
           allow 186.10.2.3;
           #+end_example
   7) http_auth_basic_module
      - 作用：基于用户的登录进行访问控制
      - 语法：
        1) ~auth_basic string | off;~
           - string 作为显示到登录界面的信息
           - 作用：启用登录访问控制
           - 默认值： ~auth_basic off~
           - 上下文：http,server,location和limit_except
        2) ~auth_basic_user_file file;~
           - file 为用于存储用户密码的文件路径
             #+begin_example
             # 密码为已加密的版本
             # 需要使用httpd的htpasswd工具，因此先要安装httpd
             # htpasswd -c /path/to/file <user>，然后通过prompt方式输入密码后，就会在/path/to/file文件中加入<user>:password的记录了
             name1:password1
             name2:password2:comment
             #+end_example
           - 作用：设置登录用户密码数据文件
           - 上下文：http,server,location和limit_except
      - 该模块实际使用时管理效率低，一般采用如下解决方案
        1) 结合LUA实现高效验证
        2) 通过nginx-auth-ldap模块和已有的LDAP系统打通
   8) secure_link_module
      - 作用
        1) 制定并允许检查请求的连接的真实性以及保护资源免遭未经授权的访问
        2) 限制连接生效周期
      - 语法
        - ~secure_link expression~
          - 作用：设置校验信息来源
          - 上下文：http,server,location
        - ~secure_link_md5 expression~
          - 作用：指定md5加密字符串
          - 上下文：http,server,location
      - 生成连接和验证过程
        1) 客户端发起下载请求
        2) Nginx生成下载连接，形如 ~/download?md5=_1es234&expires=41255~
        3) 客户端通过下载连接下载资源
        4) Nginx校验url中的md5和expires信息，有效则提供下载
      - 示例
        #+begin_example bash
        location / {
          secure_link $arg_md5,$arg_expires;
          # 下面的md5字符串 和 $(echo -n "${time_num}${download_file} ${secret_num}"|openssl md5 --binary | openssl base64 | tr +/ -_ | tr -d =) 一致
          secure_link_md5 "$secure_link_expires$uri john";

          # url不含校验信息
          if ($secure_link = "") {
            return 403;
          }
          # 匹配失败
          if ($secure_link = "0") {
            return 410;
          }
        }
        #+end_example
   9) ngx_http_addition_module
      - 作用：在指定Content-Type(默认为 ~text/html~)的响应报文body标签前后插入其它资源内容(JavaScript或CSS)。
      - 上下文：http,server,location
      - 使用方法
          #+begin_src
          location =/header.html {
            # 头部资源位于 $NGINX_HOME/html/header.html
            root html;
          }
          location =/footer.html {
            # 头部资源位于 $NGINX_HOME/html/footer.html
            root html;
          }

          location /path/to/index {
            default_type "";
            add_header Content-Type "text/html; charset=utf-8";
            root /path/to/root/of/index;
            
            add_before_body /header.html;
            add_after_body /footer.html;
 
            # Nginx 0.7.9开始支持
            # 指定需要被插入header和footer内容的响应报文的MIME类型，可以设置多个，空格分隔。
            # 默认为text/html
            # *表示所有
            # addition_types text/html;
          }
          #+end_src
   10) ngx_http_autoindex_module
       - 作用：启用目录浏览功能。
       - 上下文：server,location
       - 使用
         #+begin_src
         autoindex on;

         # 默认为on，显示出文件确切的大小，单位为bytes
         # off，显示出文件大概的大小，单位为kb、MB或GB
         autoindex_exact_size off;

         # 默认为off，显示文件时间为GMT时间
         # on，显示文件时间为服务器的时间
         autoindex_localtime on;

         # Nginx 1.7.9 开始支持，以哪种风格展示目录
         # 默认为html，其它值为xml, json 和 jsonp
         autoindex_format html;
         #+end_src
       - 美化：可以通过http_addition_module附加CSS和JavaScript美化页面。

* 测试工具
** ab
   ApacheBench could be used to do load testing.
   1) 安装
      #+begin_example bash
      sudo apt -y install apache2-utils
      # sudo yum -y install httpd-tools
      #+end_example
   2) 使用
      #+begin_example bash
      ab -n 50 -c 20 <url>
      #+end_example
* TODO 分层缓存机制
** 浏览器层
1) 用户代理本地的校验是否过期
   Expires(HTTP1.0版本中的定义), Cache-Control(max-age)(HTTP1.1版本中的定义)
2) 协议中Etag头信息校验
   Etag，基于文件内容和修改时间等信息生成的文件指纹。
3) Last-Modified头信息校验
   Last-Modified，最小粒度为秒，因此一秒内发生的变化是无法区分的。

** DNS层
   1. DNS系统本地缓存， 客户端操作系统DNS缓存
   2. LocalDNS缓存，本地DNS提供商的缓存
   3. DNS缓存服务器，专用的DNS缓存服务器
   4. 浏览器DNS缓存，FireFox默认60秒
  
** CDN
   1. 反向代理缓存，基于Squid、Varnish、Nginx、ATS等一级或多级

** Web服务器
   1. Web服务器缓存，Apache(mod_cache)、Nginx(FastCGI缓存、Proxy cache)
   2. Local Cache，应用本地缓存，PHP(Yac, Xcache)、Java(ehcache)

** 分布式缓存
   Memcache, Redis

** 数据库
   1. MySQL，innodb缓存、MYISAM缓存

** 操作系统
   1. CPU Cache，L1、L2、L3的数据缓存和指令缓存
   2. Memory Cache，内存高速缓存
   3. Page Cache，页缓存

** 磁盘
   1. Disk Cache，磁盘缓存(Cache memory)

** 硬件
   1. Raid Cache，磁盘阵列缓存
   
* 最佳实践
  1) root定义在server下，而不是在location中
     #+begin_example bash
     server {
       server_name a;
       root /var/www/html/;
     }
     #+end_example
  2) index定义在server下，而不是在location中
     #+begin_example bash
     server {
       server_name a;
       index index.html index.htm;
     }
     #+end_example
  3) 使用try_files代替if进行文件是否存在的探测
     由于if总会被执行从而降低Nginx的处理速度，所以能不用if就不要用if。
     #+begin_example bash
     location / {
       try_files $uri $uri/ /index.html;
       # if ( !-f $request_filename ){
       #   if ( -d $url/ ) {
       #     rewrite ^.* $uri/ last;
       #   }
       #   if ( !-d $url/ ) {
       #     rewrite ^.* /index.html break;
       #   }
       # }
     }
     #+end_example
  4) 使用嵌套location关闭特定文件的访问权限
     #+begin_example bash
     location ^~ /upload {
       location ~* \.[php|jsp|asp|aspx|cshtml|jinja2|jinja] { return 403; }
     }
     #+end_example
  5) 使用try_files过滤掉不存在的文件
     #+begin_example bash
     location ~* \.php {
       try_files $uri =404;
       fastgci_pass backend;
     }
     #+end_example
  6) 使用try_files优先返回静态内容，其次返回动态内容
     #+begin_example bash
     location / {
       try_files $uri $uri/ @proxy;
     }
     location @proxy {
       proxy_pass http://balance;
     }
     #+end_example
  7) 提取公用配置，并使用include引入
     - 作用：Includes another file, or files matching the specified mask, into configuration. Included files should consist of syntactically correct directives and blocks.
     - 语法： ~include file | mask;~
     - 上下文：any
     - 示例
       #+begin_example bash
       # file为相对于当前配置文件的路径，或绝对路径
       include mine.types;
       # mask为glob表达式
       include vhosts/*.conf;
       #+end_example
  8) 请求重定向优先使用return而不是rewrite
     #+begin_example bash
     rewrite ^/(.*)$ http://example.com/$1 permanent;
     rewrite ^ http://example.com/$request_uri permanent;
     return 301 http://example.com/$request_uri;
     #+end_example
  9) 永远不要使用 ~chmod 777~
     应该通过 ~namei -om /path/to/check~ 获取一个路径的所有权限，然后在调整。
  10) 禁用 SSLv3
      由于SSLv3存在POODLED漏洞，因此禁用SSLv3即可。设置 ~ssl_protocols TLSv1 TLSv1.1 TLSv1.2~

* 静态文件服务器
  #+begin_src
  http {
    # 启用静态资源缓存
    # max为缓存数量，建议和文件打开数保持一致
    # inactive为静态资源多久没有被请求则删除缓存，默认为60s
    open_file_cache max=204800 inactive=20s;

    # 在open_file_cache的inactive时间内至少访问多少次，才被认为该资源活跃不删除缓存。
    # 默认为1
    open_file_cache_min_uses 1;

    # 设置定期验证缓存内容是否发生变化的周期，若发生变化则删除该缓存。
    # 默认为60s
    open_file_cache_valid 30s;

    # 是否缓存权限被拒绝、文件未找到等信息
    # 默认off
    open_file_cache_errors on;

    # 内容压缩
    # 默认禁用gzip。
    # gzip能节省带宽，但会增加服务器CPU开销。且默认仅对text/html进行压缩。
    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_http_version 1.0;
    gzip_comp_level 2;
    gzip_types  text/plain application/x-javascript text/css application/xml;

    server {
      listen 80;
      server_name www.test.com;
      charset utf-8;
      root /html;
      index index.html index.htm;
    }
  }
  #+end_src

** TODO 文件描述符

* TODO 性能调优

** Nginx端优化项目
1. gzip压缩优化
2. expires缓存有还
3. 网络IO事件模型优化
4. 隐藏软件名称和版本号
5. 防盗链优化
6. 禁止恶意域名解析
7. 禁止通过IP地址访问网站
8. HTTP请求方法优化
9. 防DOS攻击单IP并发连接的控制，与连接速率控制
10. 严格设置web站点目录的权限
11. 将nginx进程以及站点运行于监牢模式
12. 通过robot协议以及HTTP_USER_AGENT防爬虫优化
13. 配置错误页面根据错误码指定网页反馈给用户
14. nginx日志相关优化访问日志切割轮询，不记录指定元素日志、最小化日志目录权限
15. 限制上传到资源目录的程序被访问，防止木马入侵系统破坏文件
16. 有关web服务的Linux内核方面深度优化（网络连接、IO、内存等）
17. nginx加密传输优化（SSL）
18. web服务器磁盘挂载及网络文件系统的优化
19. 使用nginx cache

** TODO 内存分配器
*** 使用google-perftools优化Nginx的高并发性能
*** jemalloc

** TODO 降权启用Nginx
   
** TODO TCP/IP栈优化配置

* TODO OpenResty
  https://moonbingbing.gitbooks.io/openresty-best-practices/content/openresty/helloworld.html

* QA
  1) 访问目录时返回403
     - 原因：
       1) Nginx运行帐号没有权限访问目录
       2) Nginx没有启用目录访问的功能
          #+begin_example bash
          location /path/to/direcotry {
            autoindex on;
          }
          #+end_example
  2) 上传文件时返回413(Request Entity Too Large)
     - 原因：上传文件的大小超过Nginx或后端服务的上限
     - 解决：
       #+begin_example bash
       # 默认为1m
       # 设置为0则表示禁止检查客户端请求体的大小
       # 上下文：http,server,location
       client_max_body_size 1m;
       #+end_example
  3) 499(client has closed connection)
     - 解决： ~proxy_ignore_client_abort on~
  4) 502(Bad Gateway)
     - 原因：请求已被后端服务执行，但执行未完成却被强行中止
  5) 504(Gateway Time-out)
     - 原因：请求无法被后端服务执行，一般为Nginx配置有误引起
  6) URI的路径中包含中文或unicode编码字符，那么访问该静态资源时会报500且error.log中记录如下异常
      #+begin_quote
      1113: No mapping for the Unicode character exists in the target multi-byte code page
      #+end_quote
     - 原因：由于URI并不支持中文等非ASCII码字符，因此URI中的中文字符会被编码并转换为escape格式的字符串后再封装到HTTP请求头发送给服务端。而Nginx在接收到请求后会根据服务端系统的字符编码对URI进行解码。
       那么当操作系统编码为UTF-8，而静态资源路径中各部分名称中包含非UTF-8编码的字符时，将会报该问题。
     - 具体事例：
       1. 部署在Windows平台，通过目录页面(~autoindex on~)中的含中文的超链接进入则报异常，直接将中文附加到地址栏则正常。
          - 问题分析：由于目录页面(~autoindex on~)中a标签href特性值会被以Unicode解码再采用UTF-8编码，当通过a标签访问资源时，Nginx接收到URI并UTF-8解码并转换为GBK编码，而Unicode字符表和GBK字符表并不相同，因此就会出现转换异常。
          - 解决方案：
            通过ngx_http_addition_module的 ~add_after_body~ 在页面附加JavaScript脚本替换a标签href特性的值。
            1. nginx.conf
               #+begin_src
               location /path/to/index {
                 autoindex on;
                 root /path/to/root;
                 add_after_body /index_fix_href.html;                                 
               }

               location =/index_fix_href.html {
                 root html;
               }
               #+end_src
            2. index_fix_href.html
               #+begin_src html
               <script>
               document.querySelectorAll("pre a").forEach(function(el, i) {el.href = el.textContent})
               </script>
               #+end_src
       2. 若部署在Linux平台，默认采用UTF-8字符编码。那么有可能该要访问的静态资源是从Windows平台复制过来，因此文件名是采用GBK编码。那么按如步骤处理即可：
          1. 确认并修改系统编码为UTF-8
             1. CentOS修改/etc/sysconfig/i18n内容，并重启系统
                 #+begin_src
                 LANG="en_US.UTF-8"
                 SYSFONT="latarcyrheb-sun16"
                 #+end_src
             2. Debian
                #+begin_src
                apt-get install -y locales
                dpkg-reconfigure locales
                # 然后在对话框选择 en_US.UTF-8，并重启系统
                #+end_src
             3. Ubuntu修改/etc/default/locale内容，然后执行 ~locale-gen en_US en_US.UTF-8~ 最后重启系统
                #+begin_src
                LANG="en_US.UTF-8"
                LANGUAGE="en_US:en"
                #+end_src
          2. 通过convmv将非UTF-8编码的文件名转换为UTF-8编码
             #+begin_src bash
             # --notest 表示对原文件进行修改
             convmv -f GBK -t UTF8 -r --notest /path/to/file
             #+end_src
            
       
