自动化配置工具（提供配置管理、流程控制、资源部署等功能）

蓝绿部署(blue/green deployments)
滚动式部署(rolling deployments)
金丝雀部署(canary deployments)
灰度发布()

等幂性(idempotent)，某动作执行结果为某事物已达到某目标状态，在执行该动作前先检查事物是否已达到某状态，若已达到某状态则不执行，若未达到则执行。
收敛性，某动作可多次执行，每次执行都让状态更趋向于目标状态，并最终达到目标状态。由Mark Burgess在CFEngine中提出的。

backport方式：将一个软件的补丁应用到比此补丁所对应的版本更老的版本的行为。

* 服务器自动化搭建
  | 交付产物： | 虚拟机     | 服务器                | OS镜像                | 已配置的服务器        | 已加固的服务器                                         | 应用就绪的服务器      | 服务器资源池          |
  | 操作：     | 创建VM     | Provision             | 安装补丁              | 部署配置基线          | 部署安全基线，并执行安全验证后向信息安全员交付安全报告 | 交付给应用交付团队    | 运维                  |
  | 角色：     | 系统管理员 | Ansible自动化运维平台 | Ansible自动化运维平台 | Ansible自动化运维平台 | Ansible自动化运维平台                                  | Ansible自动化运维平台 | Ansible自动化运维平台 |

* TODO 服务端命令
#+BEGIN_EXAMPLE bash
# ansible，执行ad-hoc命令

ansible-doc -l # 列出所有已安装的模块
ansible-doc -s win_iis_webapppool # 列出某模块的使用说明

ansible-galaxy install <role_name> # 从http://galaxy.ansible.com/list#/roles上下载role到/etc/ansible/roles/目录下

ansible-config          ansible-test                                                              
ansible-connection    ansible-inventory   ansible-pull        ansible-vault  
#+END_EXAMPLE

ansible-vault
ansible-pull

* 架构
Ansible编排引擎组成：
1) Ansible Core，Ansible自身核心模块；
2) Host Inventory，主机库，用于定义可管控的主机列表；
3) Plugins
   完成模块功能的补充。
   1) Filter Plugins
   2) Callback Plugins
      - 邮件
      - 日志
4) Connection Plugins，连接插件，有local、SSH(默认，底层通过paramiko实现)和ZeroMQ(message bus，大规模时使用这个会提高执行速度)
5) Modules，任务模块，分为自带的Core Modules和自定义的Custom Modules；
6) Playbook，剧本。

* 工作流程
1) 读取配置信息
2) 抓取全量机器、分组列表和关联变量（可从多个静态文件、目录读取，或通过脚本读取从其他来源读取）
3) 使用host-pattern过滤机器列表
4) 根据参数确定执行模块和配置（从modules目录动态读取模块信息，自定义模块则放在modules目录下）
5) Runner执行返回
   1) Connection阶段，通过Connection Plugin连接控制节点
   2) Action阶段，通过Lookup plugin获取Action所需的变量和文件等资源
      1) 若要向管理节点传送文件，内部将使用SCP、SFTP或Rsync(基于SSH)实现
      2) 使用jinja2解释模板时，会调用filters目录下的Filter plugins（自定义Filter则放filters目录下）
      3) 在执行各阶段会调用callbacks目录下的Callback plugins执行钩子函数调用
6) 输出、结束

* TODO 凭证隔离(Crendential Segregation)
可实现研发工程师管理开发服务器，QA工程师管理QA服务器，而系统管理员管理生产环境服务器，不允许跨权限操作服务器。

* TODO 自定义模块
  可以使任何语言开发自定义模块。

* 安装
  [[https://github.com/ansible/ansible][Ansible GitHub]]

  - *管控节点*
    - 依赖项
      - Python2.6+
      - paramiko模块
      - PyYAML
      - Jinja2
      - httplib2
    - 源码安装devel开发版本
      #+BEGIN_EXAMPLE bash
      # 安装依赖项
      sudo easy_install pip
      sudo pip install paramiko PyYAML Jinja2 httplib2 six

      # 下载安装
      git clone git://github.com/ansible/ansible.git --recursive
      cd ./ansible
      source ./hacking/env-setup

      # 更新Ansible
      git pull --rebase
      git submodule update --init --recursive
      #+END_EXAMPLE
    - 系统软件包管理工具进行安装
      - 制作rpm包
        #+BEGIN_EXAMPLE bash
        git clone git://github.com/ansible/ansible.git
        cd ./ansible
        # 要先安装rpm-bulid、make和python2-devel组件
        make rpm

        # 安装
        sudo rpm -Uvh ~/rpmbuild/ansible-*.noarch.rpm
        #+END_EXAMPLE
    - 通过pip安装
      注意：pip会将ansible-playbook等命令安装到~/.local/bin下，那么要通过 ~ln -s $HOME/.local/bin/ansible-playbook /usr/bin/ansible-playbook~ 才能在Jenkins中使用，否则在Jenkins下会报找不到该命令。
  - *被管节点*
    - 依赖项：
      - Python2.4+，若低于2.5则需要安装python-simplejson（可通过raw或script模块安装python和python-simplejson）
      - Windows环境
        - PowerShell3.0+
      - Linux
        - 若启动了SElinux则需要安装libselinux-python，这样Ansible才能执行 ~copy/file/template~ (可通过yum模块安装libselinux-python)

* Inventory组件
Inventory就是管理节点集合
Inventory清单路径：
1) 在/etc/ansible/hosts
2) 执行命令时可通过 ~-i~ 临时指定
3) 修改ansible.cfg的invertory(旧版为hostfile)全局指定
#+BEGIN_EXAMPLE
# 分组
[windows]
127.0.0.1 ansible_ssh_user="lmx" ansible_ssh_pass="password" ansible_ssh_port="5985" ansible_connection="winrm" ansible_winrm_server_cert_validation=ignore ansible_python_interpreter=/usr/bin/python2.7

# 分组内节点使用GLOB
[linux]
127.0.0.[2:4]

[hosts]
fsjohnhuan[g:j].com

# 通过:children可实现分组内包含其他分组 
[common:children]
windows
linux
#+END_EXAMPLE
** 命令
#+BEGIN_EXAMPLE bash
# 列出匹配的节点信息
ansible linux --list-hosts

## <host-pattern>支持通配符和正则表达式匹配管理节点
# 通过:分隔多个管理节点IP/域名/组名，如192.168.0.1:web.example.com:window
# all或'*'匹配所有管理节点
# a:!b表示匹配在分组a而不在分组b的管理节点
# a:&b表示匹配即在分组a又在分组b的管理节点
# *.example.com使用通配符匹配
# a[0]:b[1:]:c[-1]表示通过切片匹配分组下部分管理节点
# ~(web|db).*.example.com以~开头即表示使用正则表达式匹配管理节点
ansible <pattern_goes_here> -m <module_name> -a <arguments>
#+END_EXAMPLE
** 变量
*** 预定义变量/行为参数
    ansible_host，SSH目的主机名或IP
    ansible_ssh_user，SSH链接的用户名，默认值当前用户名
    ansible_ssh_pass，SSH链接的密码
    ansible_ssh_port，SSH链接的端口号，默认值为22
    ansible_connection，链接模式，取值为smart/ssh/paramiko/winrm
    ansible_become，类似于Linux的sudo，默认值none
    ansible_become_user，切换到哪个用户执行命令，默认值为none
    ansible_shell_type，执行命令所使用的shell，默认为sh
    ansible_python_interpreter，使用哪个Python解释器，默认为/usr/bin/python
    ansible_*_interpreter，指定其他语言的解释器，默认为none

*** 自定义变量
    在inventory文件和其他vars文件中定义即可，命名规则为字母、数字和下划线组成，并且首字符必须为字母。
    #+BEGIN_EXAMPLE
    # 直接在管理节点配置中定义
    127.0.0.1 mysql_port=3306

    [test]
    127.0.0.[2:10]

    # 分组定义
    [test:vars]
    mysql_port=3307
    #+END_EXAMPLE

    #+BEGIN_SRC bash
      # 通过{{variable_name}}引用匹配的变量
      ansible all -a 'echo {{mysql_port}}'
    #+END_SRC

    实际项目中会将预定义变量和自定义变量定义在group_vars和host_vars目录下
    #+BEGIN_QUOTE
    /etc/ansible/
    - hosts
    - group_vars/
      - test.yml
    - host_vars/
      - 127.0.0.1.yml
    #+END_QUOTE
    #+BEGIN_EXAMPLE
    ---
    # group_vars/test.yml
    mysql_port: 3307
    #+END_EXAMPLE
    #+BEGIN_EXAMPLE
    ---
    # host_vars/127.0.0.1.yml
    mysql_port: 3306
    #+END_EXAMPLE

    配置文件在/etc/ansible/ansible.cfg中
    #+BEGIN_EXAMPLE
    [defaults]
    remote_port = 22  # 默认ssh端口
    remote_user = lmx # 默认ssh登录帐号
    #+END_EXAMPLE

** 动态Inventory
    从CMDB系统或Zabbix监控系统拉取所有主机信息，然后使用Ansible进行管理。
    只需将配置项inventory指向一个可执行脚本即可，而脚本仅需支持两个选项
    - ~--list~ 或 ~-l~ ，显示所有主机以及主机组的信息（JSON格式）
    - ~--host <host>~ 或 ~-H <host>~ ，返回这个台主机的所有信息(包括认证信息、主机变量等)也是JSON格式
    
    示例
    #+BEGIN_EXAMPLE python
    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    import sys
    import argparse
    import json
    
    def list():
        r = {}
        h = ['172.17.16.10' + str(i) for i in xrange(0,2)]
        hosts = {'hosts': h}
        r['docker'] = hosts

        return json.dump(r, indent=4)

    def host(name):
        r = {'ansible_ssh_pass': '123'}
        cpis = dict(r.items)

        return json.dump(cpis)

    if __name__ == '__main__':
        parser = argparse.ArgumentParser()
        parser.add_argument('-l', '--list', help='hosts list', action='store_true')
        parser.add_argument('-H', '--host', help='hosts vars')
        args = vars(parser.parse_args())

        if args['list']:
            print list()
        elif args['host']:
            print hosts(args['host'])
        else:
            parser.print_help()
    #+END_EXAMPLE

* 配置
  配置读取顺序为：
  1) 环境变量ANSIBLE_CONFIG
  2) 当前工作目录下的ansible.cfg
  3) ~/.ansible.cfg
  4) /etc/ansible/ansible.cfg

  内容采用ini格式

** 常用配置
   #+BEGIN_EXAMPLE ansible.cfg
   [defualts]
   ; inventory=/etc/ansible/hosts，默认的inventory文件路径(1.9版本前叫做hostfile)。若值为目录路径，那么该目录下的文件将合并为一个inventory文件。
   ; library=/usr/share/my_modules/，指定模块地址。多个地址间使用:分隔。默认还会搜索playbook同目录下的library/目录
   ; action_plugins=/usr/share/ansible/plugins/action，action模块存放的路径
   ; callback_plugins=/usr/share/ansible/plugins/callback，callback模块存放的路径
   ; connection_plugins=/usr/share/ansible/plugins/connection，connection模块存放的路径
   ; lookup_plugins=/usr/share/ansible/plugins/lookup，lookup模块存放的路径
   ; vars_plugins=/usr/share/ansible/plugins/vars，vars模块存放的路径
   ; test_plugins=/usr/share/ansible/plugins/test，test模块存放的路径
   ; strategy_plugins=/usr/share/ansible/plugins/strategy，strategy模块存放路径
   ; host_key_checking=True，是否检查SSH主机的密钥(即公钥认证)
   ; sudo_user=root，默认执行命令的用户
   ; timeout=60，SSH连接的超时间隔，单位为秒
   ; remote_user，SSH的用户名
   ; log_path=/var/log/ansible.log，Ansible默认不记录日志，设置日志文件路径则启用日志记录功能。若文件不存在则会自动创建，若存在则将内容追加到文件末尾。输出到文件的同时也会输出到模拟终端中。
   ; forks=5，并行进程的数量
   ; gathering=implicit，控制收集Facts变量的策略
   ; become，是否进行提权
   ; become_method=sudo，提权方式
   ; become_user=root，提权为哪个用户
   ; become_ask_pass=no，提权是否需要密码
   ; ssh_args，控制SSH连接参数
   ; pipelining，多个task间共享SSH连接，可提升Ansible的执行效率
   ; control_path，保存ControlPath socket的路径
   ; retry_files_enabled=False，当playbook失败得情况下，一个重试文件将会创建，默认为开启此功能
   ; retry_files_save_path = ~/.ansible-retry，重试文件的路径，默认为当前目录下.ansible-retry
   #+END_EXAMPLE

** 配置Linux主机SSH免密访问
   #+BEGIN_EXAMPLE bash
   # 在主控节点生成密钥和公钥
   ssh-keygen

   # 将主控节点的公钥传输到被控节点的~/.ssh/authorized_keys下，权限为400
   ssh-copy-id -i /root/.ssh/id_rsa.pub root@<被控节点IP>
   #+END_EXAMPLE
   然后就可以执行
   #+BEGIN_EXAMPLE bash
   # 以ansible用户通过免密方式连接被控节点，然后通过sudo提权执行命令
   ansible webserver -m ping -u ansible -sudo
   # 以交互方式输入密码连接被控节点
   ansible webserver -m ping -u ansible -sudo -k
   #+END_EXAMPLE

* 模块

** 常用模块
1) 用户管理 ~user~
   参数password值必须为加密后的值，因此需要通过openssl生成密码
   #+BEGIN_EXAMPLE bash
   # 为密码ansible生成加密后值，回显$1$GPMku7y
   echo ansible | openssl passwd -1 -stdin
   # 创建新用户
   ansible '*' -m user -a 'name=dev password="$1$GPMku7y"' -f 5 -o
   #+END_EXAMPLE
2) 静态被管节点facts信息采集 ~setup~
   #+BEGIN_EXAMPLE bash
   # 收集并只查看指定信息
   ansible '*' -m setup -a 'filter=ansible_all_ipv4_addresses'
   #+END_EXAMPLE

** Windows模块
官方Windows可用模块： https://docs.ansible.com/ansible/latest/modules/list_of_windows_modules.html
#+BEGIN_EXAMPLE
# ping所有管理端
ansible all -m win_ping

# 复制文件
ansible all -m win_copy -a 'src=/etc/passwd dest=f:\file\passwd'

# 复制目录
ansible all -m win_copy -a 'src=/etc dest=f:\file\'

# 删除管理端的文件
ansible all -m win_file -a 'path=f:\file\passwd state=absent'

# 获取管理端的Windows Facts
ansible all -m setup

# 在管理端执行cmd命令
ansible all -m raw -a 'ipconfig'

# 在管理端执行ansible扩展命令
ansible all -m win_command -a 'whoami'

# 调用PowerShell执行命令
ansible all -m script -a 'foo.ps1'

# ??????
ansible all -m slurp 

# 查看模块的帮助文档
ansible-doc <module_name>

# 查看模块名或描述包含关键字的模块列表
ansible-doc -l <keyword>
#+END_EXAMPLE

** 模块返回值
| 返回值键    | 含义                                                |
|-------------+-----------------------------------------------------|
| changed     | 表示模块是否对管理节点执行了修改操作，有changed或ok |
| failed      | 若模块未能执行，则返回true                          |
| msg         | 模块执行失败的原因                                  |
| rc          | return code                                         |
| stdout      | 标准输出                                            |
| stderr      | 错误输出                                            |
| backup_file | 用于来返回备份文件的路径                            |
| results     | 应用在Playbook中存在循环的情况，返回多个结果        |

* Playbook 
  Playbook采用[[https://yaml.org/spec/1.2/spec.html#Syntax][YAML]]进行编写。
  组织规则：
  1) 一个Playbook可以包含1~N个Play，每个Play是一个完整的部署任务。每个Play定义对某组管理节点执行操作；
  2) 一个Play可以包含1~N个Task，每个Task完成一件事；
  3) 一个Play可以包含1~N个Role，每个Role是对某组Task所需的内容（handlers/templates/等）进行组织。
     
** Playbook语法示例
   #+BEGIN_EXAMPLE yaml
   --- # 首行表示该文件为YAML文件
   # 文档字符串，作者、版本、联系方式、遵循的证书规则、功能描述

   - hosts: linux:centos # 管理节点，遵循Ad-Hoc中所有模式
     gather_facts: yes # 默认第一个任务必定是收集Facts变量，但若后续任务根本不使用Facts变量，那么可以手动禁止
     become: yes  # 是否提升权限，这个可以设置在Play中，也可以设置为Task中
     become_method: sudo # 通过sudo提升权限，这个可以设置在Play中，也可以设置为Task中
     max_fail_percentage: 30 # 设置失败百分之多少时最后结果才被认为是失败
     serial: 15 # 并发对多少台被控节点作操作，可以使用如20%的百分比
     # 设置变量
     vars:
         nginx_port: 80
     vars_files:
         - "one.yml"
         - "two.yml"
     vars_prompt:
         - name: "password vaes"
           prompt: "Enter password"
           default: "secret"
           private: yes
           encrypt: "md5_crypt"
           confirm: yes
           salt: 1234
           salt_size: 8
     # 运行Playbook前将运行的任务
     pre_tasks:
         - name: pre_tasks
           shell: hostname
     # 引入角色
     roles:
         - role: docker
           version: 1.5.0
           when: ansible_system == 'Linux' 
     # 运行Playbook任务
     tasks:
         - name: Install Nginx Package
           tags: [nginx, install] # 设置标签，可通过ansible-playbook -t <tag> 单独运行指定标签的任务，或通过ansible-playbook --skip-tags=<tag> 不执行指定标签的任务
           yum: name=nginx state=present
         - name: Copy Nginx.conf
           tags: [nginx, config]
           template: 
               src: ./nginx.conf.j2
               dest: /etc/nginx/nginx.conf
               owner: root
               group: root
               mode: 0644
               validate: 'nginx -t -c %s'
           # 触发handler
           notify:
               - Restart Nginx Service
        
         # 对于shell和command模块而而言，它们根据所执行命令的return code决定任务是否执行成功
         # 对于不关心return code的命令而言，可采用如下两种方式保证任务执行成功
         - name: run this command and ignore the result
           shell: /usr/bin/somecommand || /bin/true

         - name: run this command and ignore the result
           shell: /usr/bin/somecommand
           ignore_errors: yes

         # 引入其他Playbook
         - include: other_task.yml
           version: 1.1
           dest: /tmp/dest/
           when: ansible_all_ipv4_addresses == '128.1.3.12'
     # 运行Playbook后将运行的任务
     post_tasks:
         - name: post_tasks
           shell: hostname
     # 当某任务执行结果为changed时触发，并且延迟到所有任务执行结束后才执行的动作
     handlers:
         - name: Restart Nginx Service
           service: name=nginx state=restarted
         - include: other_handlers.yml
   #+END_EXAMPLE
   1) 检查playbook语法 ~ansible-playbook nginx.yaml --syntax-check~
   2) 检查操作的被控节点 ~ansible-playbook nginx.yaml --list-hosts~
   3) 查看将要执行的任务 ~ansible-playbook nginx.yaml --list-tasks~
   4) 预演操作结果 ~ansible-playbook nginx.yaml --check~
   5) 以交互式逐个任务执行 ~ansible-playbook nginx.yaml --step~
   6) 仅对部分被控节点执行 ~ansible-playbook nginx.yaml --limit 10.22.12.33~
   7) 一次性执行 ~ansible-playbook nginx.yaml -f 5~
   8) 执行时回显详细日志 ~ansible-playbook nginx.yaml -vvv~

** 执行顺序
   1) 变量加载
   2) Facts收集
   3) pre_tasks执行
   4) pre_tasks通知的handlers执行
   5) roles执行
   6) tasks执行
   7) handlers执行
   8) post_tasks执行
   9) post_tasks通知的handlers执行

** Handlers
   作为Ansible Playbook的Event机制。

*** 执行特点
    1) 当任务执行结果属性changed为changed时，才会触发notify中定义的handlers
    2) handler在整个Play执行完后才执行，并且同一个Play中多次触发同一个handler时，仅执行一次
       #+BEGIN_EXAMPLE yaml
       # task1,2,3执行后才会执行handlers
       - hosts: test
         name: configurate httpd
         tasks:
            - name: 1. ensure apache is a the latest version
              yum: name=httpd state=latest

            - name: 2. write the apache config file
              template: 
                  src: /srv/httpd.conf.j2
                  dest: /etc/httpd.conf
              notify:
                  - restart apache

            - name: 3. ensure apache is running
              service: name=httpd state=started

         handlers:
             - name: restart apache
               service: name=httpd state=restarted
       #+END_EXAMPLE
    3) handler按定义顺序执行，而不是按在任务中调用顺序执行
    4) handler内可以再触发其他handlers
       #+BEGIN_EXAMPLE yaml
       handlers:
           - name: restart apache
             service: name=httpd state=restarted
             notify: restart memcached

           - name: restart memcached
             service: name=memcached state=restarted
       #+END_EXAMPLE
    5) 若要在Playbook中间运行handlers，则要用meta模块 ~meta: flush_handlers~
    6) 若Playbook中途失败，那么不会执行已触发的handlers

*** 应用场景
    1) 重启服务
       #+BEGIN_EXAMPLE yaml
       ---
       # Nginx setup on Windows
       - hosts: nginx
         gather_facts: no
         tasks:
             - name: install nginx
               win_chocolatey:
                   name: nginx
                   state: present
             - name: install nssm
               win_chocolatey:
                   name: nssm
                   state: present
             - name: copy nginx.conf
               win_template:
                    src: nginx.conf.j2
                    dest: d:\path\to\nginx\conf\nginx.conf
             - name: install nginx as windows service
               win_nssm:
                    name: nginx
                    application: d:\path\to\nginx\nginx.exe
                    app_parameters_free_from: -c d:\path\to\nginx\conf\nginx.conf
                    stdout_file: d:\var\log\nginx.stdout
                    stderr_file: d:\var\log\nginx.stderr
                    start_mode: auto
                    state: started # 通过win_nssm安装服务时虽然已经设置state为started，但服务仍然未运行的，要通过handlers启动
                    notify:
                        - start nginx
         handlers:
             - name: start nginx
               win_service:
                   name: nginx
                   start_mode: auto
                   state: started
       #+END_EXAMPLE
    2) 重启系统

** 变量
   Playbook运行前会读取所有相关变量，若不存在则会报错．

*** 优先级
    | 优先级 | 变量类型                                                    |
    |--------+-------------------------------------------------------------|
    | 高     | 外部变量, --extra-vars                                      |
    |        | inventory主机清单中内置变量(ansible_ssh_user等)             |
    |        | play的vars和vars_files                                      |
    |        | invertory主机清单中自定义变量,group_vars和host_vars下的变量 |
    |        | 系统facts变量                                               |
    | 低     | 角色定义的默认变量(roles/rolename/defaults/main.yml)        |

*** 内置变量
    ~inventory_hostname~ Ansible当前执行任务的定义在inventory清单中的主机名，若定义为server1.test.com，则返回server1.test.com
    ~inventory_hostname_shortname~ 若inventory_hostname返回server1.test.com，那么inventory_hostname_shortname则返回server1
    ~hostvars~ 获取某台主机的facts信息，通过 ~hostvars[inventory_hostname]~ 获取当前执行任务的facts信息
    ~group_names~ 获取当前执行任务的主机所属的主机组的主机名列表
    ~groups~ 所有主机组的字典，如 ~groups.web~ 获取 ~[web]~ 这组主机组的所有主机facts信息
    #+BEGIN_EXAMPLE ini
    [web]
    server1
    server2
    #+END_EXAMPLE
    #+BEGIN_EXAMPLE jinja2
    upstream backend {
        {% for host in groups.web %}
        server {{host.inventory_hostname}} {{host.ansible_default_ipv4.address}}:80;
        {% endfor %}
    }
    #+END_EXAMPLE
    ~inventory_dir~ inventory清单所在目录
    ~inventory_file~ inventory清单
    ~play_hosts~ 返回当前playbook运行主机信息

*** Facts变量
    为远程目标主机的IP/OS/以太网设备/MAC地址等系统/硬件信息.
    默认情况下每次执行play时会先执行收集Facts变量,如同先执行 ~ansible all -m setup~ ,并将返回结果保存到内存中,直到playbook结束.

    两种方式优化:
    1) 在playbook的每个play中添加 ~gather_facts: no~, 禁止收集Facts变量
    2) Ansible1.8+可缓存Facts变量
    #+BEGIN_EXAMPLE ansible.cfg
    # 启用缓存
    # smart, 默认收集Facts,但有缓存时则不收集
    # implicit, 不收集Facts
    # explicit, 强制收集Facts
    gathering = smart

    # 缓存到Redis
    fact_caching_timeout = 86400
    fact_caching = redis
    fact_caching_connection = 127.0.0.1:6379

    # 缓存到本地文件
    # fact_caching = jsonfile
    # fact_caching_connection = /tmp/mycachedir
    #+END_EXAMPLE

    *QA*: 若缓存到Redis后报
    #+BEGIN_QUOTE
    TypeError: the JSON object must be str, not 'bytes'
    #+END_QUOTE
    则将ansible/plugins/cache/redis.py中90行
    #+BEGIN_SRC python
    self._cache[key] = json.loads(value)
    # 修改为
    self._cache[key] = json.loads(value.decode('utf-8'))
    #+END_SRC

** 循环结构

*** 标准Loops
    被循环的值为Python List类型
    #+BEGIN_EXAMPLE yaml
    ---
    - name: print
      shell: "echo {{item}}"
      with_itemes:
          - item1
          - item2

    - name: print property
      shell: "echo {{item.name}} {{item.age}}"
      with_itemes:
          - {name: "a", age: 1}
          - {name: "b", age: 2}
    #+END_EXAMPLE

*** 嵌套Loops
    实现一对多或多对多的合并。
    #+BEGIN_EXAMPLE yaml
    ---
    - shell: "echo {{item[0]}}--{{item[1]}}"
      with_nested:
        - ["A"]
        - ["a", "b"]
    # 回显 A--a、A--b
    #+END_EXAMPLE

*** 散列Loops
    被循环的值为Python Dict类型
    #+BEGIN_EXAMPLE yaml
    ---
    vars:
        users:
            john:
                name: john
                age: 18
            mary:
                name: mary
                age: 20
    tasks:   
        - shell: "echo {{item.key}}--{{item.value.age}}"
          with_dict: user
    # 回显 john--18、mary--20
    #+END_EXAMPLE
    
*** 文件匹配Loops
    #+BEGIN_EXAMPLE yaml
    ---
    - shell: "echo {{item}}"
      with_fileglob:
          - /root/*.yaml
    #+END_EXAMPLE

*** 随机Loops
    从列表中随机选中一个值执行
    #+BEGIN_EXAMPLE yaml
    ---
    - shell: "echo {{item.key}}--{{item.value.age}}"
      with_random_choice: 
          - {name: "a", age: 1}
          - {name: "b", age: 2}      
    #+END_EXAMPLE

*** 条件判断Loops
    多次间隔执行某项操作，若执行成功则该任务成功，若超过循环次数依然失败则该任务被认为执行失败
    #+BEGIN_EXAMPLE yaml
    ---
    # 每5秒执行一次 cat /root/Ansible，然后检查回显是否以Master开头
    # 若尝试5次后都失败则该任务失败，否则为成功
    - shell: cat /root/Ansible
      register: result
      until: result.stdout.startswith("Master")
      retries: 5
      delay: 5
    #+END_EXAMPLE

*** 文件优先匹配Loops
    和文件匹配Loops相似，但当第一个匹配后就跳出循环
    #+BEGIN_EXAMPLE yaml
    ---
    - shell: "echo {{item}}"
      with_first_found:
          - /root/a.yaml
          - /root/b.yaml
    #+END_EXAMPLE

*** register Loops
    当在循环中使用register保存执行结果时，那么register中则保存则任务执行结果集合，需要通过Jinja2的循环来读取
    #+BEGIN_EXAMPLE yaml
    - name: print
      shell: "echo {{item}}"
      with_itemes:
          - item1
          - item2
      register: ret

   - debug: msg="{% for i in ret.results%} {{i.stdout}} {% endfor %}"
    #+END_EXAMPLE

** 块结构
   Block块将多个action组装成块，可根据不同条件执行一组action。
   #+BEGIN_EXAMPLE yaml
   --- 
   - hosts: test
     tasks:
         - block:
             - yum: name={{ item }} state=installed
               with_items:
                   - nginx
                   - memcached
             - template: src=templates/src.j2 dest=/etc/foo.conf
             - service: name=bar state=started enabled=True
             
           when: ansible_distribution == 'CentOS'
           rescue:
               - debug: msg="I caught an error"
               - command: /bin/false
               - debug: msg="I also never execute :-("
           always:
               - debug: msg="this always executes"
   #+END_EXAMPLE

** 读取动态变量
   通过lookups插件实现，并且读取操作均在被控节点上执行。
   
*** lookups file
    通过Python的codecs.open打开文件，并将文件内容作为结果返回给变量。
    #+BEGIN_EXAMPLE yaml
    ---
    vars:
        content: "{{ lookup('file', '/etc/sysconfig/network') }}"
    tasks:
        - debug: msg="{% for i in content.split("\n") %} {{ i }} {% endfor %}"
    #+END_EXAMPLE

*** lookups password
    对入参进行加密处理。
    #+BEGIN_EXAMPLE yaml
    ---
    vars:
        content: "{{ lookup('password', 'network') }}"
    tasks:
        - debug: msg="{{content}}"
    #+END_EXAMPLE

*** lookups pipe
    通过Python的subprocess.Popen执行命令将stdout作为结果返回给变量
    #+BEGIN_EXAMPLE yaml
    ---
    vars:
        content: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
    tasks:
        - debug: msg="{{content}}"
    #+END_EXAMPLE

*** lookups redis_kv
    从Redis中读取变量，因此被控节点需要安装Redis Python库。
    #+BEGIN_EXAMPLE yaml
    ---
    vars:
        content: "{{ lookup('redis_kv', 'redis://localhost:6379,ansible') }}"
    tasks:
        - debug: msg="{{content}}"
    #+END_EXAMPLE

*** lookups template
    和lookups file相似，不过在读取内容时会先用被控节点的facts渲染Jinj2模板后在作为结果返回给变量
    #+BEGIN_EXAMPLE jinja2
    # /etc/ansible/lookups.j2
    worker_processes {{ ansible_processer_cores }}
    IPaddress {{ ansible_eth0.ipv4.address }}
    #+END_EXAMPLE
    #+BEGIN_EXAMPLE yaml
    ---
    vars:
        content: "{{ lookup('template', '/etc/ansible/lookups.j2') }}"
    tasks:
        - debug: msg="{{content}}"
    #+END_EXAMPLE

** 错误处理和状态转换
   #+BEGIN_EXAMPLE yaml
   # 忽略错误
   - name: this will not be counted as a failure
     command: /bin/false
     ignore_errors: yes

   # 自定义错误判定条件
   - name: this command prints FAILED when is fails
     command: /usr/bin/xxx -x -y -z
     register: command_result
     failed_when: "'FAILED' in command_result.stderr"

   # 自定义changed判断条件
   - name: validate nginx conf
     shell: "/usr/local/nginx/sbin/nginx -t"
     register: command_result
     changed_when: "command_result.stdout.find('successful')"
   #+END_EXAMPLE

** 进阶操作

*** delegate_to
    任务委派：定义任务将交给非当前play的hosts指定的目标主机执行．
    #+BEGIN_EXAMPLE
    ---
    - hosts: 10.1.1.1 10.1.1.2
      tasks:
        - name: Ping
          ping:

        - name: Ping 10.1.2.3
          ping:
          delegate_to: 10.1.2.3 # 由于hosts有2台目标主机，那么执行2次 ping 10.1.2.3

         - name: Create file local
           shell: 'touch /temp/test.txt'
           delegate_to: localhost
           run_once: yes
    #+END_EXAMPLE

** 目录结构
   #+BEGIN_EXAMPLE
   /var/ansible/
     - production  # inventory file for production environment
     - staging     # inventory file for staging environment
     - group_vars/ # group variables
       - dbservers.yml
     - host_vars/  # variables for specific host
       - 10.12.22.3.yml
     - library/    # 3th party modules
     - filter_plugins # 3th filter plugins
     - site.yml      # master playbook
     - webserver.yml # playbook for webserver tier
     - dbserver.yml  # playbook for dbserver tier

     - roles/
       - common/     # common actions
         - tasks/
           - main.yml # main.yml is the entry file of each role，include模块默认使用这个目录下的文件
         - handlers/
           - ntp.conf.j2
         - templates/ # template模块默认使用这个目录下的文件
         - files/     # 保存需要上传到管理节点的文件，copy模块默认使用这个目录下的文件
         - vars/      # 不可以被覆盖的变量
           - main.yml
         - default/   # 可以被覆盖的变量（优先级别最低）
           - main.yml
         - meta/
           - main.yml # 包含当前role中所有依赖的roles
         - library/ # 3th party modules
         - lookup_plugins/
       - web/
         - tasks/
           - main.yml # main.yml is the entry file of each role
           - copy_code.yml
           - install_httpd.yml
       - db/
   #+END_EXAMPLE

   #+BEGIN_EXAMPLE dbservers.yml
   ---
   # The variables file used by the playbooks in the dbservers group.
   # These don't have to be explicitly imported by vars_files: the are autopopulated.

   mysqlservice: mysqld
   mysql_port: 3306
   #+END_EXAMPLE

   #+BEGIN_EXAMPLE site.yml
   ---
   # This playbook deploys LAMP application.

   - import_playbook: webserver.yml
   - import_playbook: dbserver.yml
   #+END_EXAMPLE
   #+BEGIN_EXAMPLE webserver.yml
   ---

   - hosts: webservers
     roles:
       - common
       - web
   #+END_EXAMPLE
   #+BEGIN_EXAMPLE web/tasks/main.yml
   ---
   # This playbook deploys webserver tier.

   - import_playbook: install_httpd.yml
   - import_playbook: copy_code.yml
   #+END_EXAMPLE

** 开发环境
   - ansible-console工具
     交互式的ansible Ad-Hoc，作为REPL提高开发效率。
     - 默认读取ansible.cfg内容，可以通过 ~ansible-console -i <inventory>~ 等命令设置环境参数
     - ~!hostname~ 查看当前操作的被控节点IP
     - ~cd~ 切换Inventory对象，支持正则
     - ~list~ 显示当前目录下的主机和主机组列表
     - ~forks~ 临时设置并发数
     - ~become~ 设置become模式，例如su或sudo
     - ~!~ 强制调用shell模块
   - 语法验证， ~ansible-playbook script.yaml --syntax-check~
   - 灰度发布，通过 ~delegate_to~ 将一个或多个任务委派到某台测试机器上执行验证
   - 配置文件验证，通过 ~--check~ 和 ~--diff~ 来对比生成后的文件是否符合要求
   - 显示详细执行信息(verbosity)
     执行ansible-playbook时会使用默认级别的verbosity
     1) none，默认级别，仅显示Play头、Task名称和Task执行状态(ok/fatal/changed)
     2) 1(-v)，1级，显示返回值
     3) 2(-vv)，2级，显示输入数据和返回值
     4) 3(-vvv)，3级，显示详细的连接尝试
     5) 4(-vvvv)，4级，会传输-v选项给SSH等具体的连接插件
   - 通过debug模块查看任务返回值
     若下一个任务依赖上一个任务的返回值时，就有可能因返回值内容缺失导致下一个任务执行失败。因此我们有需要预先查看返回值情况的需求了。
     #+BEGIN_EXAMPLE yaml
     ---
     - name: variable introspection demo
       hosts: localhost
       gather_facts: false

       tasks:
         - name: do something
           uri:
              url: http://fsjohnhuang.cnblogs.com
           register: derpops
         - name: show derpops
           debug:
              msg: "derpops value is {{ derpops }}"  # 显示整个返回值
              var: derpops.server                    # 显示返回值的某个属性
     #+END_EXAMPLE
   
* 管理Windows服务器
  PowerShell: 以.NET Framework为平台，接收和返回.NET对象
  Server Core: Windows Server 2008开始提供Server Core模式，只包含安全、TCP/IP、文件系统、RPC等服务器核心子系统。可以安装DNS、DHCP、文件服务、活动目录、ADLDS（轻型目录服务）、打印、媒体、Web服务角色。降低磁盘空间占用、较少的补丁安装。
  而Ansible就是基于PowerShell3.0+管理Windows服务器。

  Windows主机工作环境分为工作组(work group)和域(domain)两种：
  1) 工作组，将不同的电脑按功能分别列入不同的组中
  2) 域，用于一组计算机共享共用的安全数据库，是一组服务器和工作站的集合

** 依赖项
   1) 管理节点必须为Linux系统，并且安装Python2.7+、pywinrm和requests
   2) 被管节点必须为Windows Server 2008 R2+、PowerShell3.0+、.NET Framework3.0+，并且开启WinRM服务
      WinRM为WS-Management协议的Microsoft实现，该协议基于SOAP，由硬件和软件制造商群体开发的公共标准，用于实现该协议的任何计算机设备远程交换管理数据。
      - WinRM监听端口5985和5986，默认关闭

** 被控节点配置
   参考:
   1) https://www.cnblogs.com/kingleft/p/6391652.html
   2) http://www.ansible.com.cn/docs/intro_windows.html (内含Windows Server 2008 R2管理节点配置方式)

   - 安装Framework3.0
     - 下载地址 http://download.microsoft.com/download/B/A/4/BA4A7E71-2906-4B2D-A0E1-80CF16844F5F/dotNetFx45_Full_x86_x64.exe
   - Windows 7 和 Windows Server 2008 R2由于使用Windows Management Framework3.0因此存在OOM漏洞，需要安装补丁
     - 下载地址 http://support.microsoft.com/kb/2842230
   - 设置PowerShell为remotesigned
     - 在PowerShell中执行 ~set-executionpolicy remotesigned~
   - 升级PowerShell至3.0+(Windows7和Windows Server 2008 R2的PowerShell一般为2.0)
     - 查看PowerShell版本，在PowerShell中执行 ~get-host~
     - 到官网下载3.0安装包到管理节点安装
   - 启用WinRM(WS-Management)，在cmd下执行
     - 基本配置 ~winrm quickconfig~
     - 配置验证方式为基本验证 ~winrm set winrm/config/service/auth @{Basic="true"}~
     - 配置加密方式为允许非加密 ~winrm set winrm/config/service @{AllowUnencrypted="true"}~
     - 查看winrm service listener ~winrm e winrm/config/listener~ ，有返回即服务已启用

** QA
   1) 控制端执行 ~ansible all -m win_ping~ 报如下异常：
   #+BEGIN_QUOTE
   FAILED! => {
   "msg": "winrm or requests is not installed: No module named winrm"
   }
   #+END_QUOTE
   那么需要在控制端执行 ~pip install pywinrm~
   2) 管理端已经配置完成，但在控制端执行 ~ansible all -m win_ping~ 返回如下内容
   #+BEGIN_QUOTE
   UNREACHABLE! => {
   "changed": false, 
   "msg": "plaintext: HTTPConnectionPool(host='10.16.40.165', port=5985): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd995aaa910>, 'Connection to 10.16.40.165 timed out. (connect timeout=30)'))", 
   "unreachable": true
   }
   #+END_QUOTE
   那么有可能是防火墙入站规则的问题，在防火墙入站规则将 *Windows 远程管理(HTTP-In)-公用/将作用域/远程IP* 修改为 *任务IP地址* 即可。
   3) 在PowerShell中执行.ps1脚本文件时抛
   #+BEGIN_QUOTE
   无法加载文件 ******.ps1，因为在此系统中禁止执行脚本
   #+END_QUOTE
   那么需要先执行 ~set-executionpolicy remotesigned~
   因为默认值为 restricted为禁止执行任何脚本，而remotesigned为可在本机上执行未签名脚本。
   4) Windows Server 2008 R2已经升级到PowerShell3.0但执行win_ping时还是报
   #+BEGIN_QUOTE
   InvalidOperation: (:) [], ThreadStartException    + FullyQualifiedErrorId : InvalidOperation Thread failed to start
   #+END_QUOTE
   将PowerShell升级到4.0即可（Windows6.1-KB2819745-x64-MultiPkg.msu）。
   1) Windows Server 2008 R2下设置winrm报winrm 拒绝访问 0x80070005 -2147024891疑难杂症
      1) 确定服务中，windows remote management（ws man） 服务已经启动。
      2) 确定网络访问，使用的经典模式，即：[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa]
         “forceguest”=dword:00000000
         如果是1，请改成0，重启机子。感谢老史提供解题方案。
      3) 确定（当前）administrators组中的账户，都设置了密码，而不是空密码。让空密码的远程管理员，登录机子，这肯定不合理。
         这一点，是我们和群友一起试验出来的，空密码就会报拒绝访问的错。感谢提问者qq=504800471，帮忙验证。
         和这个键值或许也应该有关，即：
         [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa]
         “LimitBlankPasswordUse”=dword:00000001
         即空密码账户，只能本地登录。
      4) 确定右键点powershell图标，选择了管理员，权限运行powershell。
      5) 最后运行winrm quickconfig 命令。
   5) windows2008下使用win_iis_website时powershell4.0报”Get-Website : Could not load file or assembly 'Microsoft.IIS.PowerShell.Framework' or one of its dependencies. 系统找不到指定的文件。“

   资料：
   http://dllsearch.net/dlls/m/microsoft.iis.powershell.framework-dll-file
   https://www.cnblogs.com/jiangjun0817/p/4214660.html

   升级powershell5.0
   安装Microsoft .NET Framework 4.5
   https://www.microsoft.com/zh-cn/download/confirmation.aspx?id=30653
   安装Windows Management Framework 5.0，去这里下载，Windows 2008 R2选择安装【Win7AndW2K8R2-KB3134760-x64.msu】
   https://www.microsoft.com/en-us/download/confirmation.aspx?id=54616

* Ansible-Galaxy
  #+BEGIN_EXAMPLE
  # 初始化一个role的目录结构
  ansible-galaxy init /etc/ansible/roles/websrvs

  # 从galaxy.ansible.com上下载名为bennojoy.mysql的role到本地
  ansible-galaxy install -p /etc/ansible/roles bennojoy.mysql

  # 列出已安装的roles
  ansible-galaxy list

  # 查看已安装的role信息
  ansible-galaxy info bennojoy.mysql

  # 卸载
  ansible-galaxy remove bennojoy.mysql
  #+END_EXAMPLE
  在Playbook中使用roles
  #+BEGIN_QUOTE
  - hosts: all
    roles:
    - role: bennojoy.mysql
  #+END_QUOTE

* 插件
用于增强Ansible核心功能。

** 性能监控
1) [[https://github.com/jlafon/ansible-profile][ansible-profile]]
   - 用于统计每个任务的耗时
   - 已经集成到Ansible2.x，只要在ansible.cfg中加入 ~callback_whitelist = profile_tasks~ 即可

** Callback插件
对任务执行响应事件进行处理的插件。

* TODO 安全
  
** ansible-vault
* QA
1) 部署代码时中文乱码
   解决方法：在Ansible配置文件的defaults section下修改为
   #+BEGIN_EXAMPLE
   # module_lang = C
   # module_set_locale = True
   module_lang = en_US.UTF-8
   module_set_locale = True
   #+END_EXAMPLE
   

* TODO 实例-Zabbix

* TODO 实例-Hadoop

* TODO 实例-HAProxy
