工作目录（working directory）
暂存区（stage/index）
版本仓库(Repostiory)

| --->     | 工作目录         | 暂存区  | 版本仓库   |
|----------+------------------+---------+------------|
| 工作目录 |                  | git add |            |
| 暂存区   | git reset --hard |         | git commit |
| 版本历史 |                  |         |            |

* 文件4种状态
1) Untracked 未跟踪
   文件未加入到git库，不参与版本控制。通过 ~git add~ 转变为 Staged 状态
2) Unmodified 工作目录中的文件和版本仓库的一致
   文件参与版本控制。
   1) 通过修改其内容转变为 Modified 状态
   2) 通过 ~git rm~ 转变为 Untracked 状态
3) Modified 工作目录中的文件和版本库的不一致
   文件参与版本控制。
   1) 通过 ~git add~ 转变为 Staged 状态
   2) 通过 ~git checkout~ 从暂存区获取文件覆盖工作目录的文件，同时转换为 Staged 状态 或 Unmodified 状态
4) Staged 暂存状态
   1) 通过 ~git commit~ 提交到版本仓库，同时转换为 Unmodified 状态
   2) 通过 ~git reset HEAD <filename>~ 从版本仓库获取文件覆盖暂存区的文件，同时转换为 Modified 状态

* 配置
  #+BEGIN_EXAMPLE shell
  # 配置当前用户下所有仓库通用的帐号和邮箱地址
  # --local  表示当前仓库下使用，信息保存在.git/config中
  # --global 表示当前用户下所有仓库通用，信息保存在~/.gitconfig中
  # --system 表示所有用户下所有仓库通用
  git config --global user.name "fsjohnhuang" # 用户名
  git config --global user.email "fsjohnhuang@hotmail.com" # 邮箱
  git config --global core.editor vi # message文本编辑器

  # 查看当前仓库、当前用户、系统级和三者的配置
  git config --list --local
  git config --list --global
  git config --list --system
  git config --list

  # 彩色显示
  git config --global color.ui auto
  git config --global color.diff true # diff时的彩色显示
  # 正常显示中文文件路径
  git config --global core.quotepath off

  # 子命令别名
  git config --global alias.co checkout
  git config --global alias.pl pull
  git config --global alias.ps push
  git config --global alias.br branch
  git config --global alias.st status
  git config --global alias.ci commit
  git config --global alias.ca commit -a
  git config --global alias.cp cherry-pick
  git config --global alias.type cat-file -t
  git config --global alias.dump cat-file -p
  git config --global alias.hist "log --pretty=format:'%C(yellow)%h %C(bold blue)%ad%Cred%d%Creset | %s' --graph --date=format:'%y/%m/%d %H:%M:%S'"


  # 删除配置项
  git config [--local|--global|--system] --unset section.key
  #+END_EXAMPLE

* ~git log --pretty=format~
%H: commit hash
%h: 缩短的commit hash
%T: tree hash
%t: 缩短的 tree hash
%P: parent hashes
%p: 缩短的 parent hashes
%an: 作者名字
%aN: mailmap的作者名字 (.mailmap对应，详情参照git-shortlog(1)或者git-blame(1))
%ae: 作者邮箱
%aE: 作者邮箱 (.mailmap对应，详情参照git-shortlog(1)或者git-blame(1))
%ad: 日期 (--date= 制定的格式)
%aD: 日期, RFC2822格式
%ar: 日期, 相对格式(1 day ago)
%at: 日期, UNIX timestamp
%ai: 日期, ISO 8601 格式
%cn: 提交者名字
%cN: 提交者名字 (.mailmap对应，详情参照git-shortlog(1)或者git-blame(1))
%ce: 提交者 email
%cE: 提交者 email (.mailmap对应，详情参照git-shortlog(1)或者git-blame(1))
%cd: 提交日期 (--date= 制定的格式)
%cD: 提交日期, RFC2822格式
%cr: 提交日期, 相对格式(1 day ago)
%ct: 提交日期, UNIX timestamp
%ci: 提交日期, ISO 8601 格式
%d: ref名称
%e: encoding
%s: commit信息标题
%f: sanitized subject line, suitable for a filename
%b: commit信息内容
%N: commit notes
%gD: reflog selector, e.g., refs/stash@{1}
%gd: shortened reflog selector, e.g., stash@{1}
%gs: reflog subject
%Cred: 切换到红色
%Cgreen: 切换到绿色
%Cblue: 切换到蓝色
%Creset: 重设颜色
%C(...): 制定颜色, as described in color.branch.* config option
%m: left, right or boundary mark
%n: 换行
%%: a raw %
%x00: print a byte from a hex code
%w([[,[,]]]): switch line wrapping, like the -w option of git-shortlog(1)

* 本地操作
  #+BEGIN_EXAMPLE shell
  # 初始化仓库
  # git仓库中存在目录.git，用于存放元数据
  git init

  # 创建仓库，并创建同名目录
  git init <repos>

  # 查看
  git status

  # 将工作目录中的某文件加入到暂存区
  git add <file-path>
  # 将工作目录中的所有文件加入到暂存区
  git add .
  # 将工作目录中的已被git跟踪管理的文件加入到暂存区
  git add -u

  # 提交commit
  git commit

  # 重命名
  git mv <original-file> <new-file>

  # 删除文件
  git rm <file>
  # 取消版本跟踪，但不删除文件
  git rm --cache <file>

  # 显示最近4个提交，且提交日志仅用一行显示commit id和日志信息
  git log --oneline -n 4
  # 以树状图显示提交日志，且提交日志仅用一行显示commit id和日志信息
  git log --oneline --graph
  # 查看某文件的提交日志（含对比信息）
  git log -p <file>
  # 查看所有分支的日志
  git log --all
  # 根据关键词，搜索提交历史
  git log -S <keyword>
  # 显示某文件的版本历史
  git log --follow <file>
  # 显示所有提交过的用户，按提交次数排序
  git shortlog -sn
  # 查看某文件的提交日志（仅含sha码）
  git blame <file>

  # 显示某次提交发生变化的文件名和内容
  git show <commit>
  # 显示某次提交发生变化的文件名
  git show --name-only <commit>

  # 带注释的标签，git会创建一个tag对象保存注释和其指向的commit
  git tag -a <tag_name> -m <message>
  # 删除标签
  git tag -d <tag_name>
  # 不带注释的标签，tag直接指向commit id，不会创建tag对象
  git tag

  # 分离头指针(detached head)，即HEAD指向一系列的提交并且没有与某分支关联，git会将其当成垃圾清理掉
  # 为分离头指针建立关联分支
  git branch <new-branch> <commit-id>
  # 或者执行如下命令
  git checkout -b <new-branch>

  # 查看所有分支(远端分支和本地分支)，和分支最新提交id和日志
  git branch -av
  # 查看所有分支(远端分支和本地分支)，分支最新提交id和日志，以及本地分支和远端分支的追踪关系
  git branch -avv
  # 基于当前分支/指定分支/提交，创建并切换到新分支
  git checkout -b <new-branch> [<original-branch>|<commit-id>]
  # 删除分支
  git branch -d <branch>
  # 默认情况下当分支没有被merge，其上的修改在分支删除后会被丢弃，那么git会阻止你删除分支
  # 通过选项 -D 强制删除分支
  git branch -D <branch>
  # 切换分支
  git checkout <branch>
  # 切换到上一个分支
  git checkout -
  # 以指定的标签作为基础创建并切换到detached branch
  git checkout <tag>
  # 注意：分支名称和标签名称必须有所区分，若有重复那么引用时就要使用全路径refs/heads/<branch>和refs/tags/<tag>

  # 分支合并时若两个分支不存在同一个父提交，那么即使没有明显的冲突也会被认为存在冲突
  # 合并后产生的commit存在两个父commit
  # 以非fast-forward方式将指定分支内容合并到当前分支
  git merge --no-ff <branch>
  # 取消合并操作，分支内容回滚到合并前状态
  git merge --abort

  # GitHub的合并策略
  # 1. merge commits，将target branch合并到base branch中并创建一个commit。merge commit有两个父commit，因此删除target branch后依然可以找到target branch的提交记录
  #    特点：保留所有提交记录，但会污染base branch的历史记录
  # 2. squash merging，将target branch上的commit合并为一个commit，并将该commit存放到base branch中
  #    特点：保持base branch干净，但author为该分支的maintainer，而不是target branch的owner
  git merge --squash <target branch> # 然后base branch中的缓冲区会出现一个提交，这里就是target branch合并的内容，提交的author为当前提交人
  # 3. rebase merging，修改target branch的提交历史，然后在合并到base branch上
  #    特点：保持base branch干净，且保留提交的owner
  #    注意：
  #        由于在本地对target branch执行变基操作，因此有可能会导致本地target branch不仅仅只比远端分支多几个提交而已，从而导致执行 git push 时失败。
  #        由于git push实际是采用Fast-forward方式合并本地分支到远端分支，而Fast-forward方式仅使用于target_branch和base_branch的区别仅为target_branch比base_branch多几个提交。
  #        当target branch仅一人开发时可使用git push --force <remote_repos> <target_branch>，将本地分支的提交记录强行覆盖远端分支；
  #        当target branch多人开发时使用git push --force-with-lease <remote_repos> <target_branch>，当远端分支上存在其他人提交的commit时则覆盖失败。
  git rebase -i <base_branch>
  git push --force-with-lease <remote_repos> <target_branch>
  git checkout <base_branch>
  git merge <target_branch>

  # 修改最新commit的日志消息
  git commit --amend # 然后输入日志消息后保存，即会修改最新commit的日志消息
  # 提交修改但不新增提交记录
  # 注意：
  #     1. 执行以下语句和rebase一样会导致无法执行git push合并当前分支到远端分支，需要采用和rebase一样的方式处理；
  #     2. 分支A和分支B完全相同，在分支A执行如下命令后，在分支B中执行合并时，由于分支A和分支B并非多几个提交的关系，从而无法执行Fast-forward操作，需采用Non-fast-forward操作。
  git commit --amend --no-edit

  # 修改前第n个commit的日志消息，注意<n+1-commit-id>为前n+1个提交的id
  # 打开交互界面，显示的提交记录以顺序方式排列（第一行为前第n个提交）
  # 修改第一行第一个单词pick修改为reword，然后保存退出就可以修改日志消息了
  git rebase -i <n+1-commit-id>

  # 将一系列变更合并为一个，让变更历史更加清晰，称为挤压(squashing)
  # 打开交互界面，显示的提交记录以顺序方式排列（第一行为前第n个提交）
  # 以第一行为基础合并提交，因此第一行为pick
  # 其他要合并的提交则修改为squash，然后保存退出即进入编辑界面输入合并日志
  # 操作结束后会创建一个新的commit作为一系列提交合并的提交，并且被合并的系列提交的后续提交都会重建，因为它们的父提交都被修改了
  git rebase -i <n+1-commit-id>

  # 合并几个不连续的提交
  # 在交互界面中，将不连续的提交重新排版让它们相邻，然后和执行将一系列变更合并为一个操作一样即可
  git rebase -i <n+1-commit-id>

  # 当target branch的最新提交不在当前分支时，对当前分支的每个提交以指定分支的最后一个提交作基础进行变基
  # 若出现冲突那么解决冲突后执行 git rebase --continue
  git rebase <target branch>

  # 比较工作目录和暂存区所有文件的差异
  git diff
  # 比较工作目录和暂存区某些文件的差异
  git diff -- <file-path>...
  # 比较暂存区和版本历史中当前提交的差异
  git diff --cache
  # 比较版本历史中当前提交和前一个提交的差异
  git diff HEAD HEAD^
  # 比较两个分支版本历史中当前提交的差异
  git diff <branch-a>..<branch-b>
  git diff <branch-a>..<branch-b> -- <file-path>...
  # 比较分支a和分支b共同的父提交与分支b当前提交的差异
  git diff <branch-a>...<branch-b>
  # 工作目录与某次提交的指定文件进行比较
  git diff <commmit-id> <file>...
  # 仅列出工作目录与暂存区差异的统计
  git diff --stat

  # 丢弃暂存区的变更，恢复和版本历史中当前提交一致
  git reset HEAD
  # 丢弃暂存区部分文件的变更，恢复和版本历史中当前提交一致
  git reset HEAD <file>...

  # 丢弃工作目录部分文件的变更，恢复和暂存区一致
  git checkout -- <file>...

  # 回滚提交（会造成提交丢失）
  # 将HEAD指向某个commit，并且恢复工作目录，暂存区至与该commit内容一致
  git reset --hard <commit-id>
  # 恢复工作目录，暂存区和版本历史当前提交内容一致
  git reset --hard HEAD
  # 恢复工作目录，暂存区和版本历史前一个提交内容一致
  git reset --hard HEAD^
  # 恢复工作目录，暂存区和版本历史前３个提交内容一致，从0开始
  git reset --hard HEAD~3

  # 将工作目录的变更缓存起来
  git stash
  # 从缓存中恢复工作目录
  git stash apply
  # 从缓存中恢复工作目录，并清除缓存区中的该项目内容
  git stash pop

  # 获取子命令的帮助文档
  git help <subcommand>
  git help <subcommand> --web

  # 通过对象id查看对象类型
  git cat-file -t <id>
  # 通过对象id查看对象内容
  git cat-file -p <id>

  # 将refs/heads、refs/tags/和refs/remotes/下的文件和及内容压缩保存到packed-refs
  git gc

  # 将某分支的commit应用到另一个分支上
  git cherry-pick <commit-id>
  #+END_EXAMPLE

  author和commiter可以为不同的人，通过cherry pick实现
  https://opensource.com/article/19/4/server-administration-git?utm_campaign=intrel

* ~git diff~ 输出解释
示例
#+begin_quote
diff --git a/README.md b/README.md
index 5e6a0dc..29f2cd4 100644
--- a/README.md
+++ b/README.md
@@ -1 +1 @@
-b
+a
#+end_quote
1) a/README.md 为变动前，b/README.md变动后
2) 5e6a0dc为暂存区的文件对象id，29f2cd4为为工作目录的文件对象id；100代表普通文件，644代表权限
3) --- a/README.md 中的---表示变动前的版本
4) +++ b/README.md 中的+++表示变动后的版本
5) @@ -1 +1 @@ 表示相对变动前的版本删除1行和新增1行内容
6) -b 表示删除了内容为b这行
7) +a 表示新增了内容为a这行

* 远端操作
  #+BEGIN_EXAMPLE bash
  # 显示关联的远端仓库信息
  git remote -v

  # 添加关联的远端仓库信息
  git remote add <remote-repo-name> <repo-uri>

  # 将本地新建的分支推送到远端仓库
  git push --set-upstream <remote-repo-name> <local-branch-name>
  # 将本地标签推送到远端仓库
  git push --set-upstream <remote-repo-name> --tags
  # 将本地分支和标签都推送到远端仓库
  git push --set-upstream <remote-repo-name> --all
  # 强制推送，即使存在冲突．应该禁止此操作
  git push -f <remote-repo-name> <local-branch-name>
  # 删除远端仓库分支
  git push <remote-repo-name> --delete <branch>
  # 若分支名称和标签名称相同时，需要这样删除
  git push <remote-repo-name> --delete refs/heads/<branch>

  # 推送本地标签到远端仓库
  git push --tags
  # 删除远端分支
  git push origin --delete tag <tag_name>

  # 在已经执行fetch后，以远端仓库为基础创建本地分支
  # remote-branch形如origin/feat-1
  git checkout -b <new-branch> <remote-branch>
  git checkout --track <remote-branch>
  # 创建分支，并指定的远程分支建立追踪关系
  git branch --track <branch> <remote-branch>
  # 设置本地分支追踪远端分支
  git branch -set-upstream <local-branch> <remote-branch>
  # 设置当前本地分支追踪远端分支
  git branch -u <remote-branch>

  # 删除远端仓库已删除，但本地依然存在的分支
  git remote prune <remote-repo>

  # 从远端仓库拉取，remote-repo-name默认为origin
  git fetch [remote-repo-name]
  # 合并代码
  git merge
  # 从远端仓库拉取并合并代码，remote-repo-name默认为origin
  git pull [remote-repo-name]

  # 将其他项目拉取到指定目录下，并且当前目录下会生成.gitmodule文件
  git submodule add <repo> <dir>
  # 更新某submodule内容
  cd <dir> && git pull
  # 更新所有submodule内容
  git submodule foreach git pull

  # 全量克隆仓库(克隆所有分支)，会自动创建追踪origin/master的本地master分支
  # 将帐号密码附加到URL中，git clone http://<user>:<pass>@<repo>
  git clone <repo> [dir]
  # 单一克隆下载仓库(仅仅克隆指定的分支)，会自动创建追踪origin/branch的本地branch分支
  git clone -b <branch> --single-branch <repo> [dir]
  # 局部克隆(克隆最近N次提交的历史)
  git clone --depth=10 <repo> [dir]
  git clone --depth=10 -b <branch> --single-branch <repo> [dir]

  # 克隆带submodule的仓库方式1
  cd <dir> && git submodule init && git submodule update --recursive
  # 克隆带submodule的仓库方式2
  git clone <repo> <dir> --recursive

  # 在父项目中修改子项目代码时用subtree效果更好，subtree命令比submodule命令出来要晚
  # 从<repo>拉取<branch>代码到<dir>下，若加上--squash那么子项目的commit会被合并一个commit从而不污染父项目的版本历史。
  # 要么所有用--squash，要么全都不使用--squash，否则会有问题
  git subtree add --prefix <dir> <repo> <branch>
  # 同步子项目代码
  git subtree pull --prefix <dir> <repo> <branch>
  # 向子项目推送代码
  git subtree push --prefix <dir> <repo> <branch>
  #+END_EXAMPLE

* 回滚远程仓库分支
  1. 私有远程分支
     #+begin_src bash
     git reset --hard HEAD^ # 回滚到上一个版本
     git push -f # 强行推送到远程分支并覆盖
     #+end_src
  2. 公用远程分支
     1. 采用 ~git reset~ 回滚
        1. 用户A执行 ~git reset --hard HEAD^^ && git push -f~ 将远端分支回滚到上上个版本
        2. 用户B、C执行 ~git status~ 会看到 ~Your branch is ahead of 'origin/master' by 2 commits.~ ，也就是B、C的本地分支并没有回滚到上上版本。
           此时若执行 ~git push~ 那么远端分支将恢复原来的状态，回滚失效。因此B、C要分别执行如下操作，才能保持回滚结果：
           #+begin_src bash
           # 以用户B为例
           git reflog # 找回用户B被回滚丢的提交commit id
           git checkout -b user_b_backup <commitid> #  备份提交记录
           git checkout master # 回到主分支
           git reset --hard origin/master # 保持本地主分支和远端主分支一致
           git merge user_b_backup # 合并提交到主分支
           git push # 推送到远端分支
           #+end_src
     2. 采用 ~git revert~ 撤销某次提交，并产生一个新的提交记录。因此并不会丢失别人的提交记录。
        注意点：
        1. revert是撤销一次提交，因此后面的commit id是你需要回滚到的版本的前一次提交
           #+begin_src bash
           git revert HEAD # 撤销最近一次提交
           git revert HEAD~1 # 撤销上上次提交，回到HEAD~2的版本
           #+end_src
        2. 连续执行 ~git revert HEAD~ 相当于没有执行过 ~git revert HEAD~ ，代码没有被撤销但提交记录向前进了。
        3. 若撤销的不是最近一次提交，那么一定会有代码冲突。

* .git目录
  #+BEGIN_EXAMPLE
  .git/
    - HEAD     # 内容为 ref: refs/heads/master，记录当前所在分支
    - config   # 内容为 git config --list --local的输出信息
    - refs/
      - heads/ # 分支目录
        - master # master分支，存放分支指向的commit id，执行git cat-file -t `cat .git/refs/heads/master`回显为commit，表示指向的一个commit对象
        - temp   # temp分支，存放分支指向的commit id
      - tags/  # 标签目录，标签对应项目管理中的里程碑
        - js01   # js01分支，存放分支id，执行git cat-file -t `cat .git/refs/tags/js01`回显为tag，表示指向的一个tag对象
                 # 执行git cat-file -p `cat .git/refs/tags/js01`回显tag对应的commit id和日志信息
    - objects/ # 保存tree、blob、tag、commit对象
        - 18/
          - 4a24f15674f2d93901f9f1b38b7f1c22031581 # 父目录名和该文件名组成tree对象的id或blob对象的id，tree对象包含1~N个block对象
        - pack/ # 执行git gc后对objects下松散的文件进行整理压缩打包，并存放到pack目录下
  #+END_EXAMPLE
  一个commit对应一棵tree，一颗tree包含0~n个blob和0~n棵tree。tree对应文件系统的目录，而blob对应文件系统的文件，注意的是文件内容相同的文件被保存为同一个blob。整体保存该commit对应的文件系统快照。
  例如：一个commit仅包含./doc/readme，那么一个tree表示./，一个tree表示doc，一个blob表示readme。

* TODO 服务端
#+BEGIN_EXAMPLE bash
# 创建用户
sudo adduser git
# 将客户端的ssh-key的公钥收集到服务端放到用户git的家目录下

# 创建不带工作目录的裸仓库
git init --bare
# 克隆不带工作目录的裸仓库
# 哑协议，/path/to/repo.git，性能较差，而且没有进度条
# 智能协议，file:///path/to/repo.git，http://hostname/path/to/repo.git，https://hostname/path/to/repo.git，user@hostname:path/to/repo.git，性能更好，有进度条
git clone --bare <repo-uri> <repo>
#+END_EXAMPLE

* 场景
  1) 当A修改文件名而B修改文件内容，并且A先推送变更到远端仓库，然后B后推送变更到远端仓库
     Git会要求B先从远端仓库执行pull，并且Git会自动更新文件名和将文件内容的变更合并在一起
  2) 当A修改文件名而B也修改文件名，并且A先推送变更到远端仓库，然后B后推送变更到远端仓库
     Git会要求B先从远端仓库执行pull，并且报存在冲突，需要手动删除原文件选择保留哪个新文件，然后提交即可
  3) 分支 *禁止* 执行rebase后在合并到集成分支中

* TODO QA
  1) fast-forward
  2) rebase
  3) ~解决报错：error: The requested URL returned error: 401 Unauthorized while accessing~
     若git版本为1.7.1则升级git到2.x.x即可。
     1) 卸载CentOS6.5自带的git1.7.1
        #+BEGIN_EXAMPLE bash
        yum remove git
        #+END_EXAMPLE
     2) 安装依赖
        #+BEGIN_EXAMPLE bash
        yum install curl-devel expat-devel gettext-devel openssl-devel zlib-devel asciidoc
        yum install  gcc perl-ExtUtils-MakeMaker
        wget http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.14.tar.gz
        tar zxvf libiconv-1.14.tar.gz
        cd libiconv-1.14
        ./configure --prefix=/usr/local/libiconv
        make && make install
        #+END_EXAMPLE
     3) 安装git
        #+BEGIN_EXAMPLE bash
        wget https://github.com/git/git/archive/v2.2.1.tar.gz
        tar zxvf v2.2.1.tar.gz
        cd git-2.2.1
        make configure
        ./configure --prefix=/usr/local/git --with-iconv=/usr/local/libiconv
        make all doc
        make install install-doc install-html
        echo "export PATH=$PATH:/usr/local/git/bin" >> /etc/bashrc
        source /etc/bashrc
        #+END_EXAMPLE
  4) 对于大型代码仓库，采用shallow下载机制减少数据传输和不必要的历史记录。
  5) reference机制，可实现私有的代码镜像仓库定期更新。
  6) archive命令，归档指定代码仓库，保护代码历史记录等重要信息不轻易泄露。
  7) reflog可追踪引用(分支等)变更记录。
  8) blame可逐行定位文件内容修改记录、提交人、时间和注释。
  9) cherry-pick命令对二进制比较分支间差异最有效。
  10) worktree可同时checkout多条分支，实现并行开发。
      - Git版本要求：2.6.0+
      - 使用场景：多分支并行开发
        - 以往的做法
          1) 通过 ~git clone~ 实现一个分支对应一个工作目录。
          2) 一个分支提交合并到主分支后，不会合并到其他分支上。
      - worktree特点
        1) 一个分支对应一个worktree，worktree提交会将变更集合并到其他worktree上。
        2) 删除分支的同时会自动清除对应的worktree。
      - 使用
        - ~git worktree list [--porcelain]~ 显示当前仓库的所有worktree情况，包含每个worktree的关联目录。若没有关联分支则显示 ~detached HEAD~
        - ~git worktree prune~ 彻底删除worktree信息
        - ~git worktree add <path> [<branch>] [--force]~ 新增worktree和关联的目录，默认关联当前分支。
        - ~git worktree lock~ Git会定期自动清除丢没有关联目录的worktree，若关联目录是存放在非永久挂载的磁盘上，则用该命令排除清理行为
        - ~git worktree unlock~ 恢复定期自动清除没有关联目录的worktree的行为。

  11) patch和bundle可实现离线的增量同步和快速更新。
  12) 对于无法delta compress的二进制文件，让LFS(Large file system)处理。
  13) 通过定期gc和prune整理对象库文件存储结构，配置合理缓存保存阀值，提升存储访问效率，减少资源浪费。

* 工作流

** 因素
   1) 团队人员组成
   2) 研发设计能力
   3) 输出产品的特征
   4) 项目难易程度

** 主干开发
   适用因素：
   1) 团队人员能力强、人员少、沟通畅通
   2) 迭代速度快
   3) 有一套有效的特性切换实施机制
   4) 采用组件化开发方式，即各组件间关联性小

   | branch: master: | commit 1 | commit 2 | commit 3 | commit 4 |

** Git Flow
   适用因素：
   1) 基于特性分支开发
   2) 开发周期较长

** GitHub Flow
   适用因素：
   1) 基于特性分支开发
   2) 集成到主分支时则可发布

   | branch: master | commit 1 | commit 2 | commit 3  |           |           | commit 4 |
   | branch: feat-a |          |          |           | commit-a1 | commit-a2 |          |
   | branch: feat-b |          |          | commit-b1 | commit-b2 | commit-b3 |          |

** GitLabFlow
   适用因素：
   1) 基于特性分支开发
   2) 特性分支集成到产品分支，待可发布时则合并到主分支

** 多版本分支
   适用因素：
   1) 多个发布版本分支长期存在，当通用特性变更后通过cherry pick同步文件到对应的发布版本分支上

* TODO Code Review
Git Review + Gerrit
流程：
1) 本地Git提交代码review到Gerrit
2) 在Gerrit作Code Review
3) 通过则merge到分支
4) 不通过
   1) 修改后再update patch set
   2) abandon掉

* 日志格式

** Karma格式
#+BEGIN_EXAMPLE bash
# 第一行不能超过70个字符
<type>[(<scope>)]: <subject>

# 每行不能超过80个字符
<body>

[footer]
#+END_EXAMPLE

- ~<type>~ 指定变更类型
  - ~feat~ new feature for the user, not a new feature for build script.
  - ~fix~ bug fix for the user, not a fix for build script.
  - ~docs~ changes to the documentation.
  - ~style~ formatting, semi colon, etc. no production code change.
  - ~refactor~ refactoring production code, eg. renaming variable.
  - ~test~ adding missing tests, refactoring tests; no production code change.
  - ~chore~ update grunt tasks etc; no production code change.
- ~<scope>~ 指定变更范围，为空表示全局
  - ~init~
  - ~runner~
  - ~watcher~
  - ~config~
  - ~web-server~
  - ~proxy~
  - etc.
- ~<body>~ 详细日志信息
  - uses the imperative, present tense: "change" not "changed" nor "changeds".
  - includes the motivation for the change and contracts with previous behavior.
- ~[footer]~
  - referencing issues, eg. ~Closes #12 #223~
  - breaking changes
    #+BEGIN_EXAMPLE text
    BREAKING CHANGE:

    `port-runner` command line option has changed to `runner-port`, so that it is
    consistent with the configuration file syntax.

    To migrate your project, change all the commands, where you use `--port-runner`
    to `--runner-port`.
    #+END_EXAMPLE

* merge和rebase区别
  1) 原分支图
     |    |      |       | origin |
     | C1 | - C2 | - C3  | - C4   |
     |    |      | \- C5 | - C6   |
     |    |      |       | mywork |
  2) 将origin合并到mywork
     |    |      |      | origin |        |
     | C1 | - C2 | - C3 | - C4   | \      |
     |    |      | \ C5 | - C6   | -C7    |
     |    |      |      |        | mywork |
  3) 以origin为基础对mywork进行变基
     #+BEGIN_EXAMPLE bash
     # 执行变基
     git checkout mywork
     git rebase origin

     # 解决冲突后，继续执行变基
     git rebase --continue

     # 终止变基，回滚
     git rebase --abort
     #+END_EXAMPLE
     |    |      |      | origin |      |        |
     | C1 | - C2 | - C3 | - C4   |      |        |
     |    |      | \ C5 | - C6   | \C5' | -C6'   |
     |    |      |      |        |      | mywork |

** 最佳实践
   由于rebase会修改提交记录
   1) 不对master分支执行rebase，否则会引起很多问题
   2) 仅对本地/特性/个人开发的分支进行rebase

* TODO http://www.git-legit.org/
Git Workflow for Humans

* TODO Fast forward
* TODO 内部

#+begin_example bash
<branchName> # 可能会有歧义
refs/heads/<branchName>

<remoteRepos>/<branchName> # 可能会有歧义
refs/remotes/<remoteRepos>/<branchName>

<tagName> # 可能会有歧义
refs/tags/<tagName>
#+end_example

* Git Hooks
Git Hooks就是在Git执行特定事件前后触发运行的脚本。
分类：
1) 本地Hooks
   1) commit hooks
      - pre-commit
        - 用途：用于检查commit message是否有拼写错误、符合规范，若脚本的return exit code不为0则会终止提交。
        - 触发时机：执行提交前
        - 参数：无
        - 绕过方式： ~git commit -m 'message' --no-verify~
      - prepare-commit-msg
        - 用途：用于设置默认commit message
        - 触发时机：执行提交后尚未进入 commit message 编辑器时
        - 参数：
          1) 被提交的文件路径
          2) commit类型(message, template, merge, squash)
          3) 用于commit的SHA1值
      - commit-msg
        - 用途：用于检查被提交的文件路径是否合规
        - 参数：被提交的文件路径
        - 绕过方式： ~git commit -m 'message' --no-verify~
      - post-commit
        - 用途：在提交执行完成后发送通知等信息
        - 触发时机：提交完成后
        - 参数：无
   2) e-mail hooks(执行 ~git am~ 会触发如下Git Hooks)
      - applypatch-msg
      - pre-applypatch
      - post-applypatch
   3) other hooks
      - pre-rebase
        - 触发时机：执行rebase前
      - post-checkout
        - 用途：用于为自己的项目设置合适的工作区，比如自动生成文档、移动一些大型二进制文件等，也可以用于检查版本库的有效性。
        - 触发时机：执行 ~git checkout~ 或 ~git clone~ 后
        - 参数：
          1) 之前HEAD指向的引用
          2) 当前HEAD指向的引用
          3) 是否检出分支的标识(0为文件检出，1为分支检出)
        - 绕过方式： ~git clone <repos url> --no-checkout~
      - post-merge
        - 用途：用于对一些Git无法记录的数据的恢复，比如文件权限、属主、ACL等。
        - 触发时机：合并成功后
        - 参数：是否压缩合并的标识
2) 服务端Hooks，如receive等
   - pre-receive
     - 用途：分支保护
     - 触发时机：服务端合并客户端推送前
   - post-receive
     - 用途：触发自动化集成、发布
     - 触发时机：服务端合并客户端推送后

Git Hooks 所在位置：
1) 普通仓库的位于 ~/.git/hooks/~ 下(普通仓 ~git init /path/to/repos.git~)
2) 裸仓库的位于 ~./hooks/~ 下(普通仓 ~git init --bare /path/to/repos.git~)


** 配置GitLab的Git Hooks
https://docs.gitlab.com/ee/administration/custom_hooks.html
1) 登录GitLab所在服务器
2) 将钩子脚本部署到 ~/var/opt/gitlab/git-data/repositories/root/xxx.git/hooks/post-receive~
3) 对钩子脚本授予git用户的可执行权力

** 配置GitLab的Web Hooks
GitLab Web Hooks 的说明文档 http://gitlab.com/help/user/project/integrations/webhooks
