原名为Hudson，同类产品有：CruiseControl,BuildBot,TeamCity和BuildForge等。
支持Master/Slave分布式构建。

启动: ~sudo nohup java -jar jenkins.war --httpPort=1300 &~
~--httpsPort=1300~ ，启用HTTPS协议
~--httpListenAddress=0.0.0.0~ ，设置监听的IP范围，默认是监听所有

初始启动时登录页面需要输入类似似如下的密码启动Jenkins
#+BEGIN_QUOTE
Jenkins initial setup is required. An admin user has been created and a password generated.
Please use the following password to proceed to installation:

a84b7e78a5144d4ab43ef516a1fe1de0

This may also be found at: /home/john/.jenkins/secrets/initialAdminPassword
#+END_QUOTE
* 配置
Jenkins工作目录通过环境变量JENKINS_HOME设置。
备份时只需备份$JENKINS_HOME下所有文件即可。

Jenkins从SCM下载代码到本地的$JENKINS_HOME/jobs/<jobname>/workspace/
构建日志保存在$JENKINS_HOME/jobs/<jobname>/builds/

网络代理：

* 插件

*** Git Plugin

*** GitLab Plugin
1. 在GitLab/User Settings/Account获取Private token
2. 在Jenkins/Manage Jenkins/Configure System/ 
   1. 配置gitlab URL(external_url)
   2. 新增Kind为GitLab API token的Credential

* 部署SSH密钥

*** 生成公钥和密钥
在Jenkins服务器上执行
#+BEGIN_EXAMPLE bash git-bash
ssh-keygen -t rsa -C '<填写便于管理的注释>' -b 4096
#+END_EXAMPLE
一直按Enter下去，若在Enter passphrase中输入密码，那么每次向GitLab提交时都要输入密码。

*** 配置公钥
将公钥(/root/ssh/id_rsa.pub)文本复制到GitLab/User Settings/SSH Keys下

* 构建触发器

** Poll SCM
定期检查代码有没有更新，有更新则构建

*** Hudson Poll SCM 时间格式
MINUTE HOUR DOM MONTH DOW
+ MINUTE： 一小时内多少分钟（0-59）
+ HOUR： 一天内多少小时（0-23小时）
+ DOM：一个月内多少天（1-31）
+ MONTH：每月（1-12）
+ DOW：星期几（0-7），其中0和7都表示周日

***** 特殊值
'*'：可用来指定所有有效的值
'M-N'：可以用来指定一个范围,比如“1-5”
'M-N/X'或'*/X'：可用于在指定范围内跳跃一个X的值，比如在MINUTE字段中"*/15"表示"0,15,30,45"，"1-6/2"表示"1,3,5"
'A,B,...,Z'：可以用来指定多个值，比如“0,30”或“1,3,5”

任何空白行和以#开头的都为注释

***** 示例
#+BEGIN_EXAMPLE
15分钟构建一次：H/15 * * * *
每天8点构建一次：0 8 * * *
每天8点~17点，两小时构建一次：0 8-17/2 * * *
周一到周五，8点~17点，两小时构建一次：0 8-17/2 * * 1-5
每月1号、15号各构建一次，除12月：* * 1,15 1-11 *
#+END_EXAMPLE

* 构建后动作（Post-build Actions）
1) 配置邮件
2) 配置返回构建状态给GitLab


* 时区
启动Jenkins时添加如下配置调整时区
#+BEGIN_EXAMPLE
Dorg.apache.commons.jelly.tags.fmt.timeZone=TZ
#+END_EXAMPLE

* URL Shell
通过URL Shell可以操作jenkins服务
#+BEGIN_EXAMPLE
http://<jenkins-server>/<command>
command: exit | restart | reload
#+END_EXAMPLE

* 内置的环境变量
BUILD_NUMBER，构建的唯一数字标识
BUILD_ID，构建的唯一字符串标识
BUILD_TAG，构建的唯一标识
JOB_NAME，任务名称
NODE_NAME，slave节点名称
NODE_LABELS，用于标识slave节点的用处
WORKSPACE，当前job的工作目录
HUDSON_URL=JENKINS_URL，jenkins的url
BUILD_URL，构建url，如http://localhost:8000/job/JavaHelloWorld/23/
JOB_URL，job的url，如http://localhost:8000/job/JavaHelloWorld/

* Master/Slave
https://wiki.jenkins.io/display/JENKINS/Step+by+step+guide+to+set+up+master+and+slave+machines
Jenkins安装在Master服务器上，然后通过SSH、WMI+DCOM、JNLP等与Slave服务器通信。

*注意：*  当Slave中的环境变量发生变化，需重启Slave服务才能生效。

** 通过label指定job分配给哪个slave执行

** Windows Slave配置
*** 采用Java Web Start方式通信
1) 启用JNLP
在Manage Jenkins/Configure Global Security/Agents，设置TCP port for JNLP agents为Random。
2) 新增Node
在Manage Jenkins/Manage Nodes/New Node下将Launch Method设置为Launch agent via Java Web Start即可

在Slave服务端启动Jenkins Slave Service
1) 直接运行服务
将slave.jar复制到Slave服务端上
#+BEGIN_EXAMPLE
java -jar slave.jar -jnlpUrl http://<jenkins_server_host>:<port>/computer/<slave_name>/slave-agent.jnlp
#+END_EXAMPLE

2) jnlp
#+BEGIN_EXAMPLE
javaws slave-agent.jnlp
#+END_EXAMPLE

** QA
1) 若在64bit Windows Slave上执行构建，报 ~java.lang.NoClassDefFoundError: Could not initialize class hudson.slaves.SlaveComputer~ ，请按如下操作检查:
   1) You should have 32 bit JRE Installed
   2) It should be default JRE - you go to configure Java and change the settings if you have 64 bit and 32 bit both change the default to 32 bit path.
   3) Restart the Slave and that's it, Vola
2) 在Windows Slave中通过 ~javaws~ 或 ~java -jar agent.jar......~ 连接时报
#+BEGIN_EXAMPLE
hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
    at hudson.remoting.Engine.onConnectionRejected(Engine.java:335)
    at hudson.remoting.Engine.run(Engine.java:307)
#+END_EXAMPLE
并发现右JNPL4字样，表示Master和Slave间通过JNPL4协议通信失败，那么就作如下操作：
1) 打开Manage Jenkins/Configure Global Security/Agents/Agent Protocols...
2) 将JNLP1/2/3都启用即可
