* 查看系统信息

** 查看系统版本
#+BEGIN_EXAMPLE
# 查看内核版本
uname -a

# 查看发行版版本
cat /etc/issue
cat /etc/redhat-release
#+END_EXAMPLE

* 中断
定义：当需要时，CPU暂停执行当前程序转而执行其他程序的机制。

** 硬中断

帧振器通电后以某频率振动，CPU通过计数器计算振动次数，当达到一个数量后即触发一个硬中断，CPU暂停执行当前程序，调用调度程序去执行其他程序。
执行其他程序前，需要调用系统调度去保存内存、各级缓存数据以便后续恢复现场。


** 软中断

* 服务

** System V
#+BEGIN_SRC
serivce <service_name> <operation>
#+END_SRC
1) ~<service_name>~ 为位于/etc/init.d下的脚本文件名
2) ~<operation>~ 为 ~<service_name>~ 接受的参数

#+BEGIN_SRC
chkconfig <service_name> on
#+END_SRC
1) 服务启动、关闭顺序和描述位于 ~/etc/init.d/<service_name>~ 中
#+BEGIN_EXAMPLE
# chkconfig: - 85 15
# description: Nginx is an HTTP(s) server, HTTP(s) reverse \
#              proxy and IMAP/POP3 proxy server
#+END_EXAMPLE

* 常用命令

** uname
获取内核信息
#+begin_example bash
uname -r
uname -a
#+end_example

** ps
#+BEGIN_EXAMPLE
# 查看进程正在在序号为多少的CPU物理核上运行
ps axo pid,cmd,psr
#+END_EXAMPLE

** pstree

** tail
#+BEGIN_EXAMPLE
# 监控文件内容变化，并实时输出
tail -f <filepath>
#+END_EXAMPLE

** watch

** ab

** md5sum
根据一个或多个文件内容生成MD5编码．

** eval
   - 格式
     #+BEGIN_EXAMPLE bash
     eval <cmd>[;<cmd>]*
     #+END_EXAMPLE
   - 执行逻辑：
     1) 扫描入参命令行集，若遇到变量替换符 ~${}~ 则展开；
     2) 执行替换后的命令行集。
   - 注意
     1) 不能通过eval获取函数处理结果
     2) eval嵌套和不嵌套运行结果一样
   - 示例
     1) 执行包含变量值为命令的命令
        #+BEGIN_EXAMPLE bash
        TEST="Hello World"
        WORD='echo $TEST'
        echo ${WORD}      # 回显 TEST
        eval echo ${WORD} # 回显 Hello World
        #+END_EXAMPLE
     2) 获取shell传来的最后一个参数值
        #+BEGIN_EXAMPLE bash
        #!/bin/bash
        # file: test.sh

        echo "\$$#"      # test.sh first last 回显 $2

        eval echo "\$$#" # test.sh first last 回显 last
        #+END_EXAMPLE

** find

1) 命令格式
   #+begin_example bash
   find [path] [options] [file]
   #+end_example
2) 示例
   #+begin_example bash
   # 将当前目录下的所有文件移动到/test目录下
   find -type f -exec mv {} /test \;
   #+end_example

** TODO xargs
** TODO ifconfig
用于设置或显示网络接口的程序，最小化安装时默认不安装。其和netstat、whois等命令都包含在net-tools下，因此需要手动安装net-tools。

** TODO ss
查看端口

** tcpdump
tcpdump使用libpcap库来抓取网络报，而这个库几乎所有Linux/Unix都内置。

1) 安装
   #+begin_example bash
   sudo yum -y install tcpdump*
   dnf -y install tcpdump
   apt-get -y install tcpdump
   #+end_example
2) 选项
   #+begin_example bash
   # -s <number> 设置内容截取的字节数，0为截取所有；默认截取前96字节内容
   # -a 表示强制将IP显示为网络名称，默认开启
   # -n 表示不解析域名，直接显示IP
   # -nn 表示不解析域名和端口号
   # -S 表示显示绝对的序列号(sequence number)，默认显示相对编号
   # -i <interface name> 监听指定的网卡，默认为any即监听所有网卡
   # -c <number> 截取number个报文就结束
   # -X 同时使用hex和ascii显示报文的内容
   # -XX 同时使用hex和ascii显示报文的内容，并显示以太网头部
   # -A 只使用ascii打印报文的全部数据，不能和-X一起使用
   # -v,-vv,-vvv 显示更多详细信息
   # -t 输出可读的时间戳
   # -tttt 输出最大程度可读的时间戳
   # -D 显示可用的网络接口
   # -F <file> 读取文件内容作为过滤器表达式
   # -w <file> 拦截内容输出到文件中
   # -r <file> 读取文件中的数据报文，显示到屏幕上。如 tcpdump -nXr capture_file.pcap 'host web30'
   # pcap格式的文件通过vim或cat等命令出现乱码，必须使用特定软件来执行
   #+end_example
3) 过滤器
   - 设置protocol：ether, fddi, ip, arp, rarp, decnet, lat, sca, moprc, mopdl, tcp, icmp
     - 默认为所有协议
   - 设置direction：src, dst, src and dst, src or dst
     - 默认为 ~src or dst~, 例如设置过滤器 ~host 10.2.2.2~ 和 ~src or dst host 10.2.2.2~ 是等价的
   - 设置host：net, port, host, portrange
     - net 为网段(采用CIDR模式)，例如 ~net 10.200.0.0/16~
     - port 为端口号，例如 ~port 8080~
     - host 为ip，例如 ~host 10.1.1.1~ 等价于 ~src host 10.1.1.1~
     - portrange 为端口范围，例如 ~portrange 2000-2500~
     - 默认为 ~host~, 例如设置过滤器 ~src 10.2.2.2~ 和 ~src host 10.2.2.2~ 是等价的
   - 数据包字节大小
     - less 或 ~<~, 例如 ~less 32~ 或 ~< 32~
     - greater 或 ~>~, 例如 ~greater 32~ 或 ~> 32~
     - 或 ~<=~
     - 或 ~>=~
   - 逻辑运算符：not, and, or
     - 例如 ~(not tcp port 3128) and tcp port 23~
   - TCP标识
     - 通过 ~tcp[header offset]~ 决定从TCP header中偏移开始运算，通过运算结果筛选
       #+begin_example bash
       tcpdump 'tcp[13] & 32 != 0' # 拦截URGENT(URG)包
       tcpdump 'tcp[13] & 16 != 0' # 拦截ACKNOWLEDGE(ACK)包
       tcpdump 'tcp[13] & 8 != 0' # 拦截PUSH(PSH)包
       tcpdump 'tcp[13] & 4 != 0' # 拦截RESET(RST)包
       tcpdump 'tcp[13] & 2 != 0' # 拦截SYNCHRONIZE(SYN)包
       tcpdump 'tcp[13] & 1 != 0' # 拦截FINISH(FIN)包
       tcpdump 'tcp[13] = 18' # 拦截SYNCHRONIZE/ACKNOWLEDGE(SYNACK)包
       tcpdump 'tcp[32:4] = 0x47455420' # 拦截HTTP GET数据
       tcpdump 'ip[8] < 10' # 拦截TTL小于10的包（通常情况下是存在问题或者在使用traceroute）
       tcpdump 'tcp[(tcp[12]>>2):4] = 0x5353482D' # 拦截SSH连接
       #+end_example
     - 通过更可读的方式设置
        #+begin_example bash
        tcpdump 'tcp[tcpflags] == tcp-syn' # 拦截SYN报文
        tcpdump 'tcp[tcpflags] == tcp-rst' # 拦截RST报文
        tcpdump 'tcp[tcpflags] == tcp-fin' # 拦截FIN报文
        #+end_example
4) 输出内容（然后可通过wireshark、Snort进行分析）
   - TCP报文中Flags的含义
     - ~[S]~ SYN(开始连接)
     - ~[.]~ 没有Flag
     - ~[P]~ PSH(推送数据)
     - ~[F]~ FIN(结束连接)
     - ~[R]~ RST(重置连接)
     - ~[S.]~ SYN-ACK(SYN报文的应答报文)
5) 示例
   #+begin_example bash
   tcpdump -nvv -C 20 'src port 80 and src net 10.25.1.0/25'
   #+end_example

* 定时任务

** at

** crond
crond进程用于周期性(最小单位：分钟)执行某任务的守护进程。Linux的任务调度分为 *系统任务调度* 和 *用户任务调度*
1) 系统任务调度
   系统周期性所要执行的工作，如写缓存数据到硬盘、日志清理等。保存在 ~/etc/crontab~ 中。
   #+begin_example bash
   # /etc/crontab
   # set environment variables before execute run-parts
   SHELL=/bin/bash
   PATH=/sbin:/bin:/usr/sbin:/usr/bin
   MAILO="root"
   HOME=/
   # run-parts
   51 * * * * root run-parts /etc/cron.hourly
   24 7 * * * root run-parts /etc/cron.daily
   24 4 * * 0 root run-parts /etc/cron.weekly
   42 4 1 * * root run-parts /etc/cron.monthlly
   #+end_example
   - 注意：
     1) 系统任务必须为用户root的任务，但root的任务可以定义为用户任务
     2) 重启系统必须定义为系统任务，定义在用户任务中也不会被执行
     3) 在crontab中 ~%~ 是有特殊含义的，表示换行的意思。如果要用的话必须进行转义 ~\%~ ，如经常用的 ~date'+%Y%m%d'~ 在crontab里是不会执行的，应该换成 ~date '+\%Y\%m\%d'~
   - 特殊文件和目录
     1) ~/etc/cron.deny~ 文件中列出用户不允许使用的crontab命令
     2) ~/etc/cron.allow~ 文件中列出用户允许使用的crontab命令
     3) ~/etc/cron.d~
     4) ~/etc/cron.daily~
     5) ~/etc/cron.hourly~
     6) ~/etc/cron.monthly~
     7) ~/etc/cron.weekly~
     8) ~/var/log/cron~ 日志
2) 用户任务调度
   用户周期性所要执行的工作，如用户数据备份、定时邮件提醒等。用户可以通过crontab工具定制自己的计划任务。所有用户任务调度都会保存在 ~/var/spool/cron~ 目录中，并且文件名与用户名一致。
3) ~/etc/crontab~ 和 ~/var/spool/cron/*~ 文件中每一行代表一项任务。
   1) crontab 格式:  ~minute(0-59) hour(0-23) day(1-31) month(1-12) week(0-7) command~
   2) 特殊字符
      - ~*~ 代表所有可能的值，其它字段满足即可。
      - ~,~ 代表一组离散值，只要满足其中一个即可。
      - ~-~ 代表一组连续值，只要满足其中一个即可。
      - ~/~ 代表时间频率，如minute中 ~*/2~ 表示每2分钟执行。
   3) 示例
      #+begin_example bash
      # 每分钟执行一次command
      * * * * * command
      # 每小时第3和15分钟执行一次command
      3,15 * * * * command
      # 每小时执行一次command
      * */1 * * * command
      # 每小时第1分钟以root用户身份执行/etc/cron.hourly目录下的脚本
      1 * * * * root run-parts /etc/cron.hourly
      #+end_example
4) 安装
   #+begin_example bash
   yum install -y crontabs

   /sbin/service crond start
   /sbin/service crond stop
   /sbin/service crond restart
   /sbin/service crond reload
   /sbin/service crond status

   ntsysv # config service start or not when OS is up in GUI.
   chkconfig --level 35 crond on # enable crond start when OS is up.

   crontab [-u <user>] <file> # 将文件<file>作为/var/spool/cron/<user>，默认为当前用户
   crontab [-u <user>] -e # 编辑/var/spool/cron/<user>，默认为当前用户
   crontab [-u <user>] -l # 查看/var/spool/cron/<user>，默认为当前用户
   crontab [-u <user>] -r # 删除/var/spool/cron/<user>，默认为当前用户
   crontab [-u <user>] -i # 删除/var/spool/cron/<user>前提示，默认为当前用户
   #+end_example
5) 注意事项
   1) 手动执行成功，但通过crontab执行不成功。
      - 原因：手动执行是在当前shell环境下执行，可利用当前shell环境的所有环境变量。但crontab执行则不会加载任何环境变量，因此需要在执行前先设置环境变量。
      - 方法：通过 ~source~ 导入环境变量，或直接在cron文件中 ~export~
   2) 脚本中涉及文件路径时必须写绝对路径。
6) run-parts
   遍历目标目录，并执行第一层目录下的可执行文件。
   #+begin_example bash
   # 每小时第1分钟以root用户身份执行/etc/cron.hourly目录下的脚本
   1 * * * * root run-parts /etc/cron.hourly
   #+end_example
7) 最佳实践
   - 目录结构
     #+begin_example yaml
     - sync.d/
       - sync_api.sh
       - sync_web.sh
     - sync.cron
     #+end_example
   - sync.cron
     #+begin_example bash
     SHELL=/bin/bash
     # run-parts
     1 * * * * root run-parts sync.d
     #+end_example
   - 备份和创建
     #+begin_example bash
     crontab -l > cron.bk
     crontab sync.cron
     #+end_example

* TODO 用户和用户组管理

** 用户
1) useradd
   作为底层命令用于创建用户名。
   #+begin_example bash
   useradd <user> # 仅创建用户名和同名用户组，但没有创建对应的家目录，也没有设置密码。因此无法通过该帐号登录系统
   useradd -m <user> # 创建用户名和在/home下创建同名家目录
   passwd <user> # 设置密码

   userdel -r <user> # 删除用户名和相关的用户组、邮件收件目录等信息
   #+end_example
2) adduser
   perl开发的基于useradd的工具
   #+begin_example bash
   adduser <user> # 创建用户名、同名用户组，并以/etc/skel/作为模板创建家目录
   #+end_example

** 用户组
用户组信息位于: ~/etc/group~

#+BEGIN_EXAMPLE bash
# 查看用户所属的用户组列表
groups <user>

# 将用户从原有用户组剔除，添加到新的用户组
usermod -G <groupA> <user>

# 将用户添加到新的用户组
usermode -a -G <groupA> <user>
#+END_EXAMPLE

** 用户密码管理
   1) 2种无交互方式初始化密码的方式
      1) ~echo initial-password | passwd <user> --stdin~
      2) ~chpasswd <user>:<passwd>~
   2) 随机密码生成方式
      #+BEGIN_EXAMPLE bash
      # 生成8个字符的随机密码
      openssl rand -base64 8
      #+END_EXAMPLE

** sudo详解
   作用为将当前用户切换到root或指定用户下，然后以他们的身份去执行命令，最后直接回退到当前用户的身份。

*** 好处
    1) 限制用户只能在某些主机上运行某些命令
    2) 提供详细记录用户行为历史的日志，并能将日志发送到中心主机或日志服务器
    3) 成功执行sudo命令后用户将获取一张存活期为5分钟(编译内核时可修改)的凭证，在凭证存活期内再次执行sudo不再要求输入密码确认

*** sudo命令的执行流程
    1) 系统查找/etc/sudoers文件，判断该用户是否拥有执行sudo的权限
    2) 若具有权限则要求用户输入自己的密码
       - 无需输入密码的情况
         1) root执行sudo时无需输入密码(/etc/sudoers中配置 ~root ALL=(ALL) ALL~ )
         2) 配置允许该用户不用输入密码(/etc/sudoers中配置 ~%wheel ALL=(ALL) NOPASSWOD: ALL~)
    3) 密码验证正确则切换身份并执行sudo后的命令

*** /etc/sudoers文件解析
    #+BEGIN_EXAMPLE
    ## Next comes the main part: which users can run what software on
    ## which machines(the sudoers file can shared between multiple systems).
    ## Syntax:
    ##   Need password:
    ##     USER_FLAG HOST_FLAG=(RUNAS_FLAG) COMMAND_FLAG
    ##
    ##   Don't need password
    ##     USER_FLAG HOST_FLAG=(RUNAS_FLAG) NOPASSWORD: COMMAND_FLAG
    ##
    ## The COMMANDS section may have other options added to it.
    #+END_EXAMPLE
    *配置优先级：后面的配置会覆盖前面的配置*

    sudoers中可定义4种别名:
    1) Host_Alias 用于定义主机列表
       #+BEGIN_EXAMPLE
       Host_Alias FILESERVERS = fs1, hostname2
       #+END_EXAMPLE
    2) Cmnd_Alias 用于定义允许和禁止执行的命令列表(以 ~!~ 开头表示禁止执行该命令)
       #+BEGIN_EXAMPLE
       Cmnd_Alias SERVICES = /sbin/service, /usr/bin/systemctl disable
       #+END_EXAMPLE
    3) User_Alias 用于定义有sudo权限的用户列表
       #+BEGIN_EXAMPLE
       User_Alias ADMINS = jsmith, mikem
       #+END_EXAMPLE
    4) Runas_Alias 用于定义用户以什么身份执行的列表
       #+BEGIN_EXAMPLE
       Runas_Alias RUNAS_FLAG = root, oracle
       #+END_EXAMPLE

*** sudo命令
    #+BEGIN_EXAMPLE bash
    # 显示当前的sudo配置
    sudo -ll

    # 查看某个用户的sudo配置
    sudo -lU <user>

    # 切换为root用户
    sudo su -
    #+END_EXAMPLE

*** 通过visudo编辑sudo配置
    命令visudo会锁住/etc/sudoers文件，然后将修改保存到临时文件中，待格式检查无误后才会覆盖/etc/sudoers文件。
    *注意：若/etc/sudoers文件格式错误则会导致sudo不可用*

    visudo的默认编辑器为vi，可通过环境变量VISUAL和EDITOR设置，其中VISUAL优先级更高。
    #+BEGIN_EXAMPLE bash
    # 修改编辑器为nano
    EDITOR=nano visudo
    #+END_EXAMPLE

*** 利用/etc/sudoers.d/配置sudo
    命令sudo会解析读取/etc/sudoers.d/下的文件，而这些文件的格式和/etc/sudoers一样。
    读取解析顺序：
    1) 按字母顺序加载
    2) 以 ~.~ 或 =~= 开头的文件会被跳过(文件名建议以双字母开头)

*** 实例
    1) 允许普通用户apps具体/etc/init.d/nagios脚本重启的权限
       #+BEGIN_EXAMPLE
       apps ALL= NOPASSWD: /etc/init.d/nagios restart
       #+END_EXAMPLE
    2) 允许普通用户apps具体root的所有权限
       #+BEGIN_EXAMPLE
       apps ALL=(ALL) NOPASSWD: ALL
       #+END_EXAMPLE
    3) 允许用户组apps中所有用户具体root的所有权限
       #+BEGIN_EXAMPLE
       %apps ALL=(ALL) NOPASSWD: ALL
       #+END_EXAMPLE
    4) 允许用户apps执行部分命令
       #+BEGIN_EXAMPLE
       apps ALL=/sbin/halt,/sbin/poweroff
       #+END_EXAMPLE
    5) 设置用户apps的sudo凭证存活时间为20分钟，若设置为0则每次执行sudo都会询问密码
       #+BEGIN_EXAMPLE
       Defaults:apps timestamp_timeout=20
       #+END_EXAMPLE
    6) 禁用root
       *注意：禁用root之前要配置好普通用户的sudo权限*
       #+BEGIN_EXAMPLE bash
       # 锁住root
       passwd -l root

       # 解锁root
       sudo passwd -u root
       #+END_EXAMPLE

* 设置代理

** 服务端tinyproxy设置
#+BEGIN_EXAMPLE bash
sudo apt install asciidoc # 安装依赖

# 安装tinyproxy
sudo wget https://github.com/tinyproxy/tinyproxy/releases/download/1.8.4/tinyproxy-1.8.4.tar.gz -O tinyproxy-1.8.4.tar.gz

tar xf tinyproxy-1.8.4.tar.gz

./configure --enable-transparent --prifix=/usr/local/tinyproxy

./make && ./make install

# 启动
/usr/local/tinyproxy/sbin/tinyproxy -c /usr/local/tinyproxy/etc/tinyproxy.conf

# 测试http
curl url --proxy 10.10.10.10:8888

# 测试https
curl url --proxy 10.10.10.10:8888 -k
#+END_EXAMPLE

*** 配置
#+BEGIN_EXAMPLE tinyproxy.conf
# 添加白名单
Allow 10.27.80.0/24
Allow 11.65.48.0/24
Allow 18.90.12.145
#+END_EXAMPLE

** 客户端设置
| 环境变量    | 描述                                                         | 示例                                       |
|-------------+--------------------------------------------------------------+--------------------------------------------|
| http_proxy  | 设置http协议代理                                             | 10.0.0.51:8080、user:passwd@10.0.0.10.8080 |
| https_proxy | 设置https协议代理                                            |                                            |
| ftp_proxy   | 设置ftp协议代理                                              |                                            |
| all_proxy   | 一次性设置所有协议的代理，设置这个后上述变量都不用设置了     |                                            |
| no_proxy    | 设置无需代理的主机名或域名，可使用通配符，多个时使用逗号分隔 | *.aiezu.com, 10.*,*,*                      |

* 网络

** OSI(开放系统互联)七层框架
|  7 | 应用层     | 应用层协议     | 应用层     | APDU     |
|  6 | 表示层     | 表示层协议     | 表示层     | PPDU     |
|  5 | 会话层     | 会话层协议     | 会话层     | SPDU     |
|  4 | 传输层     | 传输层协议     | 传输层     | TPDU     |
|  3 | 网络层     | 网络层协议     | 网络层     | 报文     |
|  2 | 数据链路层 | 数据链路层协议 | 数据链路层 | 帧       |
|  1 | 物理层     | 物理层协议     | 物理层     | 比特     |
| 层 | 主机A      |                | 主机B      | 数据单位 |

** FTP

*** Client
    #+BEGIN_EXAMPLE bash
    # 进入 FTP Client
    ftp
    # 连接FTP Server，后续需要输入用户名和密码
    open <ip>

    # 在FTP Server上执行命令
    dir
    mkdir <dir>
    # rm -rf
    mrdir <dir>
    cd <dir>
    # 下载文件到本地
    get <file>
    # 批量下载文件到本地
    # <pattern> 值如 *.*
    mget <pattern>
    # 删除文件
    delete <pattern>

    # 在本地上执行命令
    # ls
    !dir
    # cd
    lcd
    # 上传文件到FTP Server
    put <file>
    # 批量上传文件到FTP Server
    mput <pattern>

    # 退出FTP Client
    bye
    #+END_EXAMPLE
** SSH
   SSH作为通用协议其全名为Secure Shell协议，是由国际互联网工程任务组(The Internet Engineering Task Force, IETF)指定的一个标准，目的是为创建一个工作在应用层和传输层的基础上的安全协议，避免数据以明文传输。
   OpenSSH作为SSH的一个具体实现(包含客户端openssh和服务端openssh-server)，是一个由OpenBSD管理的项目。OpenSSH基于SSH这种通用协议上，提供很多其他应用层协议及工具。
   1) ssh，用于登录远程服务器以及在其上执行命令。
   2) scp，在两台服务器间传输文件。
   3) sftp，基于OpenSSH实现类似FTP程序。

   另外，OpenSSH还提供如下命令行工具方便进行ssh操作
   1) ssh-add
   2) ssh-keysign
   3) ssh-keyscan
   4) ssh-keygen
   5) ssh-copy-id

*** 命令
#+BEGIN_EXAMPLE bash
# 删除known_hosts中主机的信息
ssh-keygen -f "~/.ssh/known_hosts" -R 192.168.0.169
#+END_EXAMPLE

*** 远程执行命令
#+begin_example bash
# 顺序执行多条非交互命令
ssh root@168.1.2.3 "pwd; cat hello.txt"

# 执行交互命令
# 当ssh不带命令时，ssh会创建一个tty。当带命令时，默认不会创建tty，而是执行完命令后即结束会话。
# 通过选项-t显式让ssh创建一个tty。
# 官方解释："Force pseudo-terminal allocation.  This can be used to execute arbitrary screen-based programs on a remote machine, which can be very useful, e.g. when implementing menu services.  Multiple -t options force tty allocation, even if ssh has no local tty."
ssh -t root@168.1.2.3 "sudo ls /etc"

# 当执行的为持续运行或本应以守护进程执行的命令时，
# ssh <user>@<ip> <command> 由于标准输出和标准错误文件描述符并不会关闭，因此将无法退出，必须通过 ssh <user>@<ip> nohup <command> 1>/dev/null 2>&1 &
# 注意：执行 ssh <user>@<ip> cd /path/to/working_directory; nohup <command> 1>/dev/null 2>&1 & 也无法退出

# 执行本地脚本文件
ssh root@168.1.2.3 < test.sh
# 执行可传参数的本地脚本文件
ssh root@168.1.2.3 'bash -s' < test.sh helloworld
# 执行远程脚本文件，必须为绝对路径
ssh root@168.1.2.3 '/path/to/script.sh'
# 执行可传参数的远程脚本文件，必须为绝对路径
ssh root@168.1.2.3 '/path/to/script.sh' helloworld
#+end_example

*** 基于密码和密钥的认证方式
    1) 基于密钥的认证方式
       1) 客户端在 =~/.ssh= 下生成一对公钥密钥，并将公钥发送到将要登录的服务器上
          #+BEGIN_EXAMPLE bash
          # 生成SSH公钥(~/.ssh/id_rsa.pub)和密钥(~/.ssh/id_rsa)
          ssh-keygen -t rsa -C "xxx@xxx.com"
          # 传输并作为最后一行追加公钥到服务端的~/.ssh/authorized_keys文件中
          ssh-copy-id -i ~/.ssh/id_rsa.pub <user>@<remote_server_ip>
          #+END_EXAMPLE
       2) 客户端发起连接请求，并将客户端公钥一并发到服务端
          客户端第一次登录服务端时，服务端会发送 *公钥指纹* 让用户确认将要连接的服务器是否有效(防止伪装)，若输入yes确认继续访问则会将给服务端的公钥作为最后一行追加到客户端的 =~/.ssh/known_hosts= 文件中，后续登录相同服务器时会作为依据和服务端的公钥进行验证，若验证失败则有可能是服务端被伪装了。但可通过修改客户端的 ~/etc/ssh/ssh_config~ 禁用这验证过程：
          #+BEGIN_EXAMPLE
          StrictHostKeyChecking no
          #+END_EXAMPLE
       3) 服务端从请求登录的用户的 =~/.ssh/authorized_keys= 目录下获取步骤1中的客户端公钥，与请求中的公钥作对比，不一致则登录失败
       4) 服务端生成一段challenge(质询)并用客户端公钥加密后发送给客户端
       5) 客户端使用客户端密钥解密得到服务端发送过来的chanllenge，然后用服务端公钥加密再发送给服务端，若和之前生成的一致则登录成功
       6) 客户端和服务端的后续通信则通过双方的公钥加密数据，然后各自通过密钥解密数据。
    2) 基于密码的认证方式
       1) 客户端发起连接请求
       2) 服务端接收请求后向客户端发送服务端公钥
          客户端第一次登录服务端时，服务端会发送 *公钥指纹* 让用户确认将要连接的服务器是否有效(防止伪装)，若输入yes确认继续访问则会将给服务端的公钥保存到客户端的 =~/.ssh/known_hosts= 文件中，后续登录相同服务器时会作为依据和服务端的公钥进行验证，若验证失败则有可能是服务端被伪装了。但可通过修改客户端的 ~/etc/ssh/ssh_config~ 禁用这验证过程：
          #+BEGIN_EXAMPLE
          StrictHostKeyChecking no
          #+END_EXAMPLE
       3) 客户端用服务端公钥加密登录密码，并连通客户端公钥发送给服务端
       4) 服务端通过服务端密钥解密获取登录密码后，验证通过则允许登录。
       5) 客户端和服务端的后续通信则通过双方的公钥加密数据，然后各自通过密钥解密数据。

*** 服务端配置
    1) 配置文件路径: ~/etc/ssh/sshd_config~
       #+BEGIN_EXAMPLE
       # Port 22 sshd服务端口号
       # ListenAddress 0.0.0.0 服务器一般有多张网卡，这里用于指定sshd服务绑定到哪张网卡(监听哪张网卡的请求)，默认0.0.0.0为绑定到所有网卡上。可以通过多条配置绑定多个网卡。

       PermitRootLogin yes # 允许root用户远程登录

       PasswordAuthentication yes # 允许使用基于密码/口令校验的登录方式
       PermitEmptyPasswords no # 允许空密码

       RSAAuthentication yes
       PubkeyAuthentication yes # 允许基于密钥校验的登录方式

       # AllowUsers myuser jerry 仅允许myuser和jerry远程登录该服务器
       # DenyUsers root foo 不允许root和foo远程登录该服务器
       #+END_EXAMPLE

    2) 从TCP层面控制 ~/etc/host.allow~
       #+BEGIN_EXAMPLE
       sshd: 192.168.2.12 192.168.2.13 # 仅允许这两个IP访问sshd服务
       #+END_EXAMPLE

*** 启用sshd
    #+BEGIN_EXAMPLE bash
    service sshd restart
    # 或 systemctl restart sshd
    #+END_EXAMPLE

*** 登录远程服务器
    #+BEGIN_EXAMPLE bash
    ssh root@192.168.10.12
    # sshd默认端口号为22
    # 或 ssh root@192.168.10.12:22
    # 或 ssh -p 22 root@192.168.10.12

    # 指定使用哪个密钥访问服务端
    ssh -i <private_key_path> <user>@<ip>

    # 临时设置客户端配置
    ssh -o StrictHostKeyChecking=no <user>@<ip>
    #+END_EXAMPLE

*** 本地配置多个SSH key供不同的服务端使用
    #+BEGIN_EXAMPLE bash
    # 本地配置多个SSH key供不同的服务端使用
    ssh-keygen -t rsa -C 'xxx@xxx.com' -f ~/.ssh/gitlab-rsa
    ssh-keygen -t rsa -C 'xxx@xxx.com' -f ~/.ssh/github-rsa
    #+END_EXAMPLE

    #+BEGIN_EXAMPLE bash
    # ~/.ssh/config
    # gitlab
    Host gitlab.com
    HostName gitlab.com
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/gitlab-rsa

    # github
    Host github.com
    HostName github.com
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/github-rsa
    #+END_EXAMPLE

*** SSH Agent
    使用场景：
    1) 无需重复输入密码：用ssh-add添加密钥时，如果私钥有密钥，那么仅需输入一次密码，后续使用时不用再输入密码。
    2) 客户端A已经和服务端B、服务端C建立基于密钥登录机制，通过客户端A远程访问服务端B，在服务端B再远程访问服务端C时，依然要通过口令来验证登录。通过ssh-agent则可以使用免密访问登录。

    使用：
    1) 启动ssh-agent
       #+BEGIN_EXAMPLE bash
       ssh-agent
       #+END_EXAMPLE
    2) 添加密钥
       #+BEGIN_EXAMPLE bash
       ssh-add ~/.ssh/id_rsa
       #+END_EXAMPLE
    3) 启用允许使用ssh-agent进行转发
       全局配置在 ~/etc/ssh/ssh_config~ 上设置，而局部配置则在 =~/.ssh/config= 上设置。
       #+BEGIN_EXAMPLE
       Host *
         ForwardAgent yes
       #+END_EXAMPLE

*** sshpass
    通过非交互方式实现基于口令的SSH协议的远程登录验证（即在命令行中输入口令），支持SSH协议下的所有命令，如ssh、scp和sftp。

    实例：
    #+BEGIN_EXAMPLE bash
    # 从环境变量SSPPASS中获取登录密码
    sshpass -e ssh <user>@<ip>

    # 在命令行输入登录密码
    sshpass -p <password> ssh <user>@<ip>

    # 从文件中去读取登录密码
    sshpass -f <path/to/password> ssh <user>@<ip>
    #+END_EXAMPLE

*** QA
    1) SSH发起连接访问时报 ~Permission denied (publickey,gssapi-keyex,gssapi-with-mic).~
       1) 前提条件：若没有将向服务端发送过public key，而是采用密码方式验证。
          - 解决方法：可能是没有启用PasswordAuthentication
            1) 修改/etc/ssh/sshd_config
               #+BEGIN_EXAMPLE
               PasswordAuthentication yes
               #+END_EXAMPLE
            2) 重启sshd
               #+BEGIN_EXAMPLE bash
               systemctl restart sshd
               #+END_EX

** TODO Samba
Samba为在Linux/Unix系统中实现微软的SMB/CIFS协议，从而实现Linux/Unix与Windows共享的文件服务。

SMB(Server Message Block，服务消息块)和CIFS(Common Internet File System，通用互联网文件系统)是微软为实现主机间文件通信、打印机共享而设计的私有网络通信协议。

*** 服务端
- 安装
  1) 安装软件
     #+begin_example
     sudo apt-get install samba samba-common
     #+end_example
  2) 创建共享目录
     #+begin_example bash
     mkdir -p ~/share
     chmod 777 ~/share
     #+end_example
  3) 添加samba用户
     #+begin_example bash
     # 在交互中设置samba用的密码
     sudo smbpasswd -a <user>
     #+end_example
  4) 在/etc/samba/smb.conf中添加
     #+begin_example
     [share]
     comment = share folder
     browseable = yes
     path = /home/john/share
     create mask = 0700
     directory mask = 0700
     valid users = john
     force user = john
     force group = john
     public = yes
     available = yes
     writable = yes
     #+end_example
  5) 重启samba服务
     #+begin_example bash
     # 或者 sudo /etc/init.d/smb restart
     sudo service smb restart
     #+end_example
- smbd服务
  - 功能：负责为客户机提供服务器中共享资源(目录和文件)的访问。
  - 监听端口：
    - 139，SMB协议
    - 445，CIFS协议
- nmdb服务
  - 功能：负责提供基于NetBIOS协议的主机名称解析，以便Windows网络中的主机进行查询服务。
  - 监听端口：
    - 137/138，NetBIOS协议
- 配置文件/etc/samba/smb.conf
  - 配置检查工具 ~testparm~

*** Windows客户端
1) Win+R 中输入 ~\\<samba server ip>~
   - 若不能访问共享目录，那是因为组织的安全策略阻止未经身份验证的来宾访问。
     - 解决方式：
       1) Win+R 输入gpedit进入 *本地组策略编辑器*
       2) 依次进入 ~计算机配置~, ~管理模板~, ~Lanman工作站~, ~启用不安全的来宾登录~
       3) 设置为 ~已启用~ 即可
   - 若提示当前服务端smb服务为1.0，要求提供2.0版本服务从而导致访问失败
     - 解决方式1：
       1) 依次进入 ~控制面板~, ~程序~, ~程序和功能~, ~启用或关闭Windows功能~
       2) 安装 ~SMB 1.0/CIFS 文件共享支持~ 的 ~SMB 1.0/CIFS 客户端~ 即可

*** Linux客户端
1) 通过mount挂载
   #+begin_example bash
   sudo mount -t cifs -o username=<username>,password=<password>,vers=1.0 //<ip>/<username> <mount point>

   # 例如
   # sudo mount -t cifs -o username=root,password=123,vers=1.0 //10.16.25.167/root /mnt/smb
   #+end_example
2) 通过cifs-utils挂载(http://www.jinbuguo.com/man/mount.cifs.html)
   #+begin_example bash
   # 安装
   sudo apt-get -y install cifs-utils
   # 挂载
   sudo mount.cifs //<ip>/<username> <mount point> -o username=<username>,password=<password>

   # 例如
   # sudo mount.cifs -o username=root,password=123 //10.16.25.167/root /mnt/smb
   #+end_example
   - 开机自动挂载，在 ~/etc/fstab~ 添加一行
     #+begin_example bash
     //<ip>/<username> <mount point> cifs username=<username>,password=<password> 0 0
     #+end_example

* TODO 压缩/解压
** 压缩格式
1) Gzip
   - 优点
     1) 压缩/解压速度快，压缩率高
     2) 处理压缩文件方便和处理文本一样
   - 缺点
     1) 不支持切片
   - 场景
     1) 文件压缩后的体积在130MB以内可使用
   - 解压
     #+begin_example bash
     # 将压缩包解压到指定目录下
     tar -zxvf xxx.tar.gz -C target_dir/

     # 提取压缩包的部分文件到指定目录下, 压缩包中的目录结构保持
     tar -C target_dir/ -zxvf xxx.tar.gz --wildcards dir_in_tar/xxx*yyy
     tar -C target_dir/ -zxvf xxx.tar.gz dir_in_tar/xxx1 dir_in_tar/yyy1
     #+end_example
   - 压缩
     #+begin_example bash
     # 压缩指定目录下的某个目录的内容
     # 打包压缩./dist下的内容，并保存到当前目录下的dist.tar.gz
     tar -C ./dist -zcvf dist.tar.gz .
     #+end_example
2) Bzip2
   - 优点
     1) 压缩率高于Gzip
     2) 支持切片
   - 缺点
     1) 压缩/解压速度超级慢
   - 场景
     1) 备份历史记录、文件
     2) 对压缩速率要求不高，对压缩率要求高的场景
3) xz
   - 优点
     1) 压缩率比7z高
   - 缺点
     1) 压缩/解压速度慢
   - 解压
     #+begin_example bash
     # 分步解压
     xz -d xxx.tar.xz
     tar -xvf xxx.tar

     # 直接解压
     tar -xvJf xxx.tar.xz
     #+end_example
   - 压缩
     #+begin_example bash
     tar -cvf xxx.tar xxx
     xz -z xxx.tar
     #+end_example
* 符号链接和硬链接
链接都是为文件起别名。

** inode(索引节点)
   文件存储分为
   1) inode，存放文件元数据
      - 元数据
        - 文件大小(单位：数据块)
          - 数据块：硬盘的最小存储单位为扇区(Sector)，每个扇区存储空间为512B。当操作系统读取硬盘时并不是以扇区作为读写单位，而是以多个连续扇区组成的数据块作为读写单位，常见的数据块大小为4KB。
        - 文件的数据块在磁盘中的起始位置
        - 文件拥有者的User ID
        - 文件所属组的Group ID
        - 文件的读、写、执行权限
          - 读，读取文件在数据区中对应的数据块内容
          - 写，写入文件在数据区中对应的数据块内容
          - 执行，读取文件inode信息
        - 链接数，即多少文件名指向该inode
        - ctime 最近一次变动时间
        - mtime 最近一次内容变动时间
        - atime 最近一次被打开访问的时间
      - 存储位置：inode table
      - 大小：128B或256B，每个文件系统中的inode数量在格式化时已经确定，一般是每1KB或2KB设置一个inode。
        - 示例：对于容量为1GB的硬盘，若inode大小为128B，每1KB设置一个inode，那么inode table的大小则为128MB，占硬盘的12.8%。
        - 因此有可能inode table已满而无法创建新文件，但数据区还有空间的问题。
      - inode编号，操作系统内部使用inode编号操作inode，而不是通过文件名操作inode。
      - 命令
        #+begin_example bash
        # 查看指定文件的inode信息
        stat /path/to/file

        # 查看每个文件系统的inode总数、已用数量
        df -i

        # 查看每个inode节点的大小
        sudo dumpe2fs -h /dev/hda1 | grep inode

        # 显示文件的inode编号
        ls -i /path/to/file
        #+end_example
      - 通过文件名打开文件的底层实现
        1) 目录在数据区对应的数据块中存储的是一个个由文件名称和inode编号组成的记录，因此系统会通过文件名称找到对应的inode编号
        2) 然后通过inode编号到inode table中找到inode信息
        3) 最后从inode中获取文件数据块所在的位置
      - inode的特殊作用
        1) 当文件名称包含特殊字符，导致无法正常删除。那么可以通过删除inode来执行文件删除操作；
        2) 移动或重命名文件，只是改变其所在目录的内容，并不会影响inode编号；
        3) 系统无法通过inode编号获取文件名称。
   2) block，文件内容数据块
      - 存储位置：数据区

** 符号/软链接(Symbolic link)
符号链接相当于一个指向文件名字的指针，当通过符号链接访问文件时，实质是转向通过其指向的文件名字访问数据块。
| inode table |    | data block             |
|-------------+----+------------------------|
| inode1      | -> | /path/to/file1, inode2 |
|             |    | /path/to/file2, inode1 |
|-------------+----+------------------------|
| inode2      | -> | file content           |
|-------------+----+------------------------|

因此通过 ~java -jar application.jar~ 启动服务，若application.jar为application-v0.0.0.1.jar的符号链接，那么jar包内部获取的文件名字为application-v0.0.0.1.jar。

创建一个指向目标文件/目录的快捷方式，特点如下：
1) 目标文件/目录被删除，软链接失效；
2) 能够跨文件系统(分区)建立软链接；
3) 支持相对路径。

命令
1) 建立
   #+begin_example bash
   ln -s /path/to/target /path/to/link
   #+end_example
2) 查看
   #+begin_example bash
   # 可以看到 /path/to/link -> /path/to/target 的信息
   ls -l /path/to/link
   #+end_example

** 硬链接(Hard link)
硬链接就是同一个inode对应多个文件名称。
| inode table |    | data block             |
|-------------+----+------------------------|
| inode1      | -> | /path/to/file1, inode2 |
|             |    | /path/to/file2, inode2 |
|-------------+----+------------------------|
| inode2      | -> | file content           |
|-------------+----+------------------------|

- *特点*
  1) 目标文件被删除，硬链接依然有效；
  2) 由于实现上采用inode不能够跨文件系统(分区)建立硬链接；
  3) 目录下默认会创建两个硬链接目录 ~.~ 和 ~..~ ；
  4) 不支持用户创建硬链接目录。

- *命令*
  1) 建立
   #+begin_example bash
   ln /path/to/target /path/to/link
   #+end_example
  2) 查看
   #+begin_example bash
   # 获取inode编号，通过inode编号在家目录下查找硬链接关联的文件
   ls -i /path/to/link | awk "{print $1}" | xargs find ~/ -inum
   #+end_example

* ~#!/usr/bin/env bash~ 和 ~#!/usr/bin/bash~ 的区别
1) ~#!/usr/bin/env bash~
   1) 优点：由于不同系统的bash程序位置并不尽相同，因此通过 ~/usr/bin/env~ 只需环境变量 ~$PATH~ 中包含程序路径即可执行
   2) 缺点：在多用户系统中，若别人在 ~$PATH~ 中放置其他bash的路径则会有问题
2) ~#!/usr/bin/bash~
   1) 优点：指定bash的绝对路径，确保执行版本
   2) 缺点：不够灵活
