官网：https://www.seleniumhq.org/

* Selenium工具集
1) Selenium IDE
   提供浏览器操作的录制和回放功能，和创建自动化测试脚本并导出指定编程语言的版本。
2) Selenium RC
   作为核心工具，支持多种语言编写的自动化测试脚本，通过Selenium RC服务器作为代理服务器区访问引用从而执行测试
   - 组成：
     1) Client Libraries
        用于编写测试脚本，控制Selenium Server的库。
     2) Selenium Server
        负责控制浏览器行为，分为3部分：Launcher,HttpProxy,Core。
3) Selenium Grid
   分布式自动化UI测试框架。
4) Selenium WebDriver
   作为Selenium RC的替代者。

* 等待操作

** TODO 隐式等待(implicitly_wait) 详解

** EC(expected_conditions) 模块详解
#+BEGIN_EXAMPLE python
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Chrome()
driver.get('url')

# WebDriverWait(driver: WebDriver, timeout: int, freq: float) -> WebDriverWait
# Args:
#     driver(WebDriver): 浏览器驱动
#     timeout(int): 超时时间
#     freq(float): 检测频率
# Retuns:
#     WebDriverWait
#
# WebDriverWait.until(ec: EC)
# Args:
#     ec(EC): 监测条件
# Returns:
#     bool: 在指定时间内满足条件则返回True，否则返回False

# 判断title是否是一致
EC.title_is('')
# 判断title是否包含预期值
EC.title_contains('')
# 判断某个元素是否被加到了dom树里，并不代表该元素一定可见，如果定位到就返回元素
EC.presence_of_element_located((locator))
# 判断是否至少有1个元素存在于dom树中，如果定位到就返回列表
EC.presence_of_all_elements_located((locator))
# 判断某个元素是否被添加到了dom里并且可见，可见代表元素可显示且宽和高都大于0
EC.visibility_of_element_located((locator))
# 判断某个元素是否被添加到了dom里并且可见，可见代表元素可显示且宽和高都大于0
EC.visibility_of(driver.find_element(locator))
# 判断是否至少有一个元素在页面中可见，如果定位到就返回列表
EC.visibility_of_any_elements_located((locator))
# 判断某个元素在是否存在于dom或不可见,如果可见返回False,不可见返回这个元素
EC.invisibility_of_element_located((locator))
# 判断指定的元素中是否包含了预期的字符串，返回布尔值
EC.text_to_be_present_in_element((locator),'预期的text')
# 判断指定元素的value属性值中是否包含了预期的字符串，返回布尔值(注意：只是value属性)
EC.text_to_be_present_in_element_value((locator),'预期的text')
# 判断该frame是否可以switch进去，如果可以的话，返回True并且switch进去，否则返回False
EC.frame_to_be_available_and_switch_to_it(locator)
# 判断某个元素是否可见并且是可点击的，如果是的就返回这个元素，否则返回False
EC.element_to_be_clickable((locator))
# 等待某个元素从dom树中移除
EC.staleness_of(driver.find_element(locator))
# 判断某个元素是否被选中了,一般用在下拉列表
EC.element_to_be_selected(driver.find_element(locator))
# 判断某个元素的选中状态是否符合预期
EC.element_selection_state_to_be(driver.find_element(locator),True)
# 判断某个元素的选中状态是否符合预期
EC.element_located_selection_state_to_be((locator),True)
# 判断页面上是否存在alert,如果有就切换到alert并返回alert的内容
EC.alert_is_present()
#+END_EXAMPLE

* 执行JavaScript
#+BEGIN_EXAMPLE python
el = driver.find_element((By.ID, 'test'))
driver.execute_script('arguments[0].setAttribute("style", arguments[1]);', el, 'backgroud: green;border: 2px solid red;')
#+END_EXAMPLE

* 自动化测试模型
  库(Library)，由代码集合成的一个产品，供程序员调用。采用面向对象组织形式的库称为类库，而采用面向过程组织形式的库称为函数库。

  框架(Framework)，为解决一个或一类问题而开发的产品，用于只需使用框架提供的类或函数即可实现所有功能。如unittest可用于实现测试用例的组织和执行，完成单元测试的所有工作。

  工具(Tools)，提供单独的操作界面供用户操作实现特定任务。如Selenium IDE。

  而测试模型即为测试工具和框架的设计思想。

** 线性测试
   早期的测试模块，通过录制或编写模拟用户完整的操作场景，并且各测试脚本互不依赖。

   - 优点：
     1) 每个脚本可以独立运行
   - 缺点：
     1) 开发成本高，大量重复代码
     2) 维护成本高，大量重复代码

** 模块化驱动测试
   对线性测试模型进行改进，利用程序语言特性将公共部分抽取出来实现重用。

** 数据驱动测试
   实质上即为测试数据的参数化，从外部文件(excel,csv,txt.html等)导入测试用数据。

** 关键字驱动测试
   将数据更换为关键字，通过图形界面向让用户在其提供的表格上填写工具提供的关键字来以过程式的方式编写测试用例，而Robot Framework是其中的佼佼者。
   相当于一套GUI的DSL，因此还不如直接写脚本。

* Page Object 设计模式
  作为Selenium的最佳实践之一，由如下优点：
  1) 减少代码的重复
  2) 提高测试用例的可读性
  3) 提高测试用例的可维护性，特别是针对UI频繁变化的项目

  规则：
  1) 一个HTML页面对应一个Page Object。
  2) 凡是人能做的事，Page Object通过webdriver都能做到。
     - 即Page的方法以功能来定义，将具体的元素操作隐藏在底层
       - 示例
         1) 选择左侧功能菜单的某个项目 ~select_menu(name)~
         2) 在用户名称输入框输入信息 ~set_username(text)~
  3) 然后在测试用例中调用Page Object的方法编排测试逻辑

* WebDriver配置

** Firefox 
#+BEGIN_EXAMPLE python
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.firefox.options import Options


firefox_options = Options()
firefox_options.add_argument('--headless')
firefox_options.add_argument('--disable-gpu)
driver_path = r'C:\Program Files (x86)\Mozilla Firefox\geckodriver.exe'
binary = FirefoxBinary(r'C:\Program Files (x86)\Mozilla Firefox\firefox.exe')
driver = webdriver.Firefox(firefox_binary=binary,
                           firefox_options=firefox_options
                           executable_path=driver_path)
#+END_EXAMPLE

** Chrome
#+BEGIN_EXAMPLE python
from selenium  import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-gpu)
driver_path = r'C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe'
driver = webdriver.Chrome(chrome_options=chrome_options
                          executable_path=driver_path)
#+END_EXAMPLE

* TODO BDD框架——Lettuce入门

* QA
  1) 启动Firefox时运行报 ~selenium.common.exceptions.WebDriverException: Message: newSession~
     - 原因：geckodriver版本太旧。
     - 解决方法：到 https://github.com/mozilla/geckodriver/releases 下载最新版的geckodriver到环境变量 ~PATH~ 下，若采用virtualenv创建虚拟环境则放在虚拟环境python/bin即可。
  2) 运行时偶发性抛出 ~selenium.common.exceptions.ElementNotInteractableException~
     - 原因：由于页面渲染和行为具有时间不精准性，因此有可能在元素被遮挡或不可见时就调用 ~click()~ 的方法。
     - 解决方法：通过EC检测元素状态，若可交互才执行 ~click()~ 等方法。
