官网：https://www.seleniumhq.org/

API DOC: https://selenium-python.readthedocs.io/api.html

* 自动化测试基础

** 测试分类1——根据项目流程阶段
1) 单元测试
   针对程序中的单个子程序或具有独立功能的代码段进行测试。
2) 集成测试
   基于单元测试，对通过单元模块组装成的系统或子系统进行测试，重点是检查模块间的接口是否正确。
3) 系统测试
   针对整个系统进行测试，验证系统是否满足需求规格中的功能、性能的要求。
4) 验收测试
   是部署软件前最后一个测试阶段，用于向客户展示系统能够满足客户要求。

** 测试分类2——白盒、黑盒和灰盒测试
1) 黑盒测试
   不关心程序内部逻辑结构，针对程序界面和功能进行测试，验证程序是否按照规格说明书的规定正常使用、能否正常接收输入数据并产生正确的输出信息。
2) 白盒测试
   按照程序内部逻辑结构测试程序，检验程序每条逻辑路径是否都能按预期要求正确工作。
3) 灰盒测试
   介于黑盒测试与白盒测试之间。
   既关注输出对于输入的正确性，同时也关注内部表现。但不像白盒测试那样详细、完整，只是通过一些表征性的现象、事件、标志来判断内部的运行状态。

** 测试分类3——功能、性能测试
1) 功能测试
   1) 逻辑功能测试
   2) 界面测试
   3) 易用性测试
   4) 安装测试
   5) 兼容性测试
2) 性能测试
   1) 时间性能
      指软件的一个具体的响应时间。
   2) 空间性能
      主要指软件运行时所消耗的系统资源，如硬件资源、CPU、内存、网络带宽消耗等。

** 测试分类4——冒烟测试、回归测试、随机测试、探索性测试和安全测试
1) 冒烟测试
   指测试小组在正式测试一个新版本之前，先投入较少的人力和时间验证一个软件的主要功能，如果主要功能都没有运行通过，则打回开发组重新开发。从而节省时间和人力投入到不可测的项目中。
2) 回归测试
   指修改了旧代码后，重新进行测试以确人修改后没有引入新的错误或导致其他代码产生错误。
3) 随机测试
   指测试中的所有输入数据都是随机生成的，其目的是模拟用户的真实操作，并发现一些边缘性的错误。一般放在测试的最后执行。
4) 探索性测试
   作为随机测试的升级版，是一种测试思维技术，强调在碰到问题时及时改变测试策略。
5) 安全测试

** 怎样的项目适合自动化测试
1) 任务测试明确，不会频繁变动
2) 每次构建后的测试验证
3) 比较频繁的回归测试
4) 软件系统界面稳定，变动少
5) 需要在多平台上运行的相同测试案例、组合遍历型的测试，大量的重复任务
6) 软件维护周期长
7) 项目进度压力不太大
8) 被测试的软件系统开发较为规范，能够保证系统的可测试性
9) 具备大量的自动化测试平台
10) 测试人员具有较强的编程能力

* Selenium工具集
1) Selenium IDE
   提供浏览器操作的录制和回放功能，和创建自动化测试脚本并导出指定编程语言的版本。
2) Selenium RC
   作为核心工具，支持多种语言编写的自动化测试脚本，通过Selenium RC服务器作为代理服务器区访问引用从而执行测试
   - 组成：
     1) Client Libraries
        用于编写测试脚本，控制Selenium Server的库。
     2) Selenium Server
        负责控制浏览器行为，分为3部分：Launcher,HttpProxy,Core。
3) Selenium Grid
   分布式自动化UI测试框架。
4) Selenium WebDriver
   作为Selenium RC的替代者。

* WebDriver方法和属性
#+begin_example python
driver.get(url: str) # 访问指定url, 注意：若当前URL就是入参的URL，那么将不会有任何操作

driver.page_source: str # 返回页面源码
driver.quit() # 关闭浏览器
driver.current_url # 当前url
driver.maximize_window() # 最大化窗口
driver.current_window_handle # 获取当前窗口句柄
driver.get_window_size() # 获取窗口大小
driver.set_window_size(width: int, height: int) # 设置窗口大小
driver.get_window_position() # 获取窗口坐标
driver.window_handles # 获取当前所有打开的窗口句柄
driver.switch_to.window(driver.current_window_handle) # 进入指定的窗口
driver.close() # 关闭当前窗口
#+end_example

* WebDriver事件监控
通过 ~selenium.webdriver.support.events.EventFiringWebDriver~ 监听WebDriver触发的所有事件，然后触发事件回调函数；
注意：只能监听由WebDriver触发的事件，也就是如请求重定向导致浏览URL发生变化的事件是无法通过这些方法监听的。

通过 ~selenium.webdriver.support.events.AbstractEventListener~ 定义事件回调函数
#+begin_example python
from selenium import webdriver
from selenium.webdriver.support.events import EventFiringWebDriver, AbstractEventListener


class MyListener(AbstractEventListener):
    def before_navigate_to(self, url, driver): pass
    def after_navigate_to(self, url, driver): pass
    def before_navigate_forward(self, url, driver): pass
    def after_navigate_forward(self, url, driver): pass
    def before_navigate_back(self, url, driver): pass
    def after_navigate_back(self, url, driver): pass
    def after_navigate_refresh(self, url, driver): pass
    def before_navigate_rehresh(self, url, driver): pass

    def before_change_value_of(self,):pass
    def after_change_value_of(self,):pass
    def before_click(self,):pass
    def after_click(self,):pass
    def before_find(self,):pass
    def after_find(self,):pass
    def before_execute_script(self,):pass
    def after_execute_script(self,):pass
    def before_close(self,):pass
    def after_close(self,):pass
    def before_quit(self,):pass
    def after_quit(self,):pass
    def on_exception(self,):pass

driver = EventFiringWebDriver(webdriver.Chrome(), MyListener())
driver.get("http://fsjohnhang.io")
#+end_example

* 导航
#+begin_example python
driver.get(url: str)
driver.forward()
driver.back()
driver.refresh()
#+end_example
* 元素定位
8种定位方式：
| 类型              | 方法                                   |
|-------------------+----------------------------------------|
| id                | find_element(s)_by_id()                |
| class name        | find_element(s)_by_class_name()        |
| link text         | find_element(s)_by_link_text()         |
| xpath             | find_element(s)_by_xpath()             |
| name              | find_element(s)_by_name()              |
| tag name          | find_element(s)_by_tag_name()          |
| partial link text | find_element(s)_by_partial_link_text() |
| css selector      | find_element(s)_by_css_selector()      |

特别说明
1) link text，根据 ~<a>text</a>~ 中text的内容通过完全匹配来定位元素
2) partial link text，根据 ~<a>text</a>~ 中text的内容通过部分匹配来定位元素
3) xpath，作为一种在XML文档中定义元素的DSL，也可用于HTML。
   1) 绝对路径定位 ~/html/body/div[2]~
      - 下标从1开始
      - 绝对路径以单个斜杠开始 ~/~
   2) 元素属性定位
      - 相对路径以两个斜杠开始 ~//~ ，表示当前页面某个目录下
      - 属性必须位于方括号内，并以 ~@~ 开始。如 ~[@id=''],[@name=''],[@class=''],[@type='']~
      - 示例
        #+BEGIN_EXAMPLE
        //input[@name='cc']
        #+END_EXAMPLE
   3) 层级和属性结合
      #+BEGIN_EXAMPLE
      //input[@name='cc']/div[2]/button[@class='primary' and @id='kw']
      #+END_EXAMPLE

** XPath和CSS Selector对比
| 定位方式      | XPath                | CSS Selector    |
|---------------+----------------------+-----------------|
| 标签          | //div                | div             |
| By id         | //div[@id='elid']    | div#elid        |
| By class      | //div[@class='elid'] | div.elid        |
| By attributes | //div[@title='test'] | div[title=test] |
| 定位子元素    | //div/h1,//div/*     | div>h1,div>*    |

* 等待操作

** 隐式等待(implicitly_wait) 详解
通过一定的时长等待页面上某元素加载完成，若超出设置时长元素仍然没被加载，则抛出NoSuchElementException。

#+BEGIN_EXAMPLE python
driver = webdriver.Firefox()
driver.implicitly_wait(10) # 0 second as default.

# 当获取#dd时该元素还没被加载，则会在10秒内通过轮询方式获取该元素。若能获取则继续执行，否则抛出NoSuchElementException。
driver.find_element(By.ID, 'dd')
# 当获取.cd时该元素还没被加载，则会在10秒内通过轮询方式获取该元素。若能获取则继续执行，否则抛出NoSuchElementException。
driver.find_element(By.CLASS, 'cd')
#+END_EXAMPLE

** 显示等待详解
让WebDriver在指定时间范围内等待某条件成立时继续执行，否则抛出TimeoutException。

#+BEGIN_EXAMPLE python
"""
Args:
  driver(WebDriver): Browser driver.
  timeout(int): Seconds of timeout.
  poll_frequency(float): Frequency of checking, default value is 0.5 second.
  ignored_exceptions(Exception): Indicate which exception would be raised when operation is timeout, raise NoSuchElementException by default.

Returns:
  WebDriverWait:
"""
WebDriverWait(driver, timeout, poll_frequency=0.5, ignored_exceptions=None)

"""
Args:
  method(()->bool): Wait until `method` returns True.
"""
until(method, message='')
"""
Args:
  method(()->bool): Wait until `method` returns False.
"""
until_not(method, message='')
#+END_EXAMPLE

*** EC(expected_conditions) 模块详解
#+BEGIN_EXAMPLE python
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Chrome()
driver.get('url')

WebDriverWait(driver, 10, 0.1).until(EC.title_is("tet"))

# 判断title是否是一致
EC.title_is('')
# 判断title是否包含预期值
EC.title_contains('')
# 判断某个元素是否被加到了dom树里，并不代表该元素一定可见，如果定位到就返回元素
EC.presence_of_element_located((locator))
# 判断是否至少有1个元素存在于dom树中，如果定位到就返回列表
EC.presence_of_all_elements_located((locator))
# 判断某个元素是否被添加到了dom里并且可见，可见代表元素可显示且宽和高都大于0
EC.visibility_of_element_located((locator))
# 判断某个元素是否被添加到了dom里并且可见，可见代表元素可显示且宽和高都大于0
EC.visibility_of(driver.find_element(locator))
# 判断是否至少有一个元素在页面中可见，如果定位到就返回列表
EC.visibility_of_any_elements_located((locator))
# 判断某个元素在是否存在于dom或不可见,如果可见返回False,不可见返回这个元素
EC.invisibility_of_element_located((locator))
# 判断指定的元素中是否包含了预期的字符串，返回布尔值
EC.text_to_be_present_in_element((locator),'预期的text')
# 判断指定元素的value属性值中是否包含了预期的字符串，返回布尔值(注意：只是value属性)
EC.text_to_be_present_in_element_value((locator),'预期的text')
# 判断该frame是否可以switch进去，如果可以的话，返回True并且switch进去，否则返回False
EC.frame_to_be_available_and_switch_to_it(locator)
# 判断某个元素是否可见并且是可点击的，如果是的就返回这个元素，否则返回False
EC.element_to_be_clickable((locator))
# 等待某个元素从dom树中移除
EC.staleness_of(driver.find_element(locator))
# 判断某个元素是否被选中了,一般用在下拉列表
EC.element_to_be_selected(driver.find_element(locator))
# 判断某个元素的选中状态是否符合预期
EC.element_selection_state_to_be(driver.find_element(locator),True)
# 判断某个元素的选中状态是否符合预期
EC.element_located_selection_state_to_be((locator),True)
# 判断页面上是否存在alert,如果有就切换到alert并返回alert的内容
EC.alert_is_present()
#+END_EXAMPLE

* WebElement
通过定位获取的元素类型WebElement或WebElement集合。

** 常用方法和属性
#+BEGIN_EXAMPLE python
we = driver.find_element_by_id('test')


we.clear() # 清除文本
we.send_keys('abc') # 模拟键盘输入字符
we.click() # 模拟单击操作
we.submit() # 模拟回车操作
we.get_attribute('name') # 获取元素特性
we.get_attribute('class') # 获取元素特性
we.is_displayed() # 返回该元素是否用户可见
we.is_selected() # 返回该元素是否被选中

we.tag_name # 获取元素的Tag Name
we.location # 论元素是否在可视区域，滚动条始终不动，返回相对整个html或者对应frame的坐标 {u'y': 225, u'x': 13}
we.size # 返回元素的尺寸, {'height': 160, 'width': 300}
we.text # 返回元素的文本(textContent, innerText)
#+END_EXAMPLE

* 鼠标事件
封装在类ActionChains中。

1) 右键菜单
   #+BEGIN_EXAMPLE python
   from selenium import webdriver
   from selenium.webdriver.common.action_chains import ActionChains

   driver = webdriver.Firefox()
   we = driver.find_element_by_id('test')
   ActionChains(driver)
       .context_click(we) # 定义执行右键菜单动作
       .perform() # 执行操作
   #+END_EXAMPLE
2) 双击
   #+BEGIN_EXAMPLE python
   from selenium import webdriver
   from selenium.webdriver.common.action_chains import ActionChains

   driver = webdriver.Firefox()
   we = driver.find_element_by_id('test')
   ActionChains(driver)
       .double_click(we)
       .perform() # 执行操作
   #+END_EXAMPLE
3) 拖动
   #+BEGIN_EXAMPLE python
   from selenium import webdriver
   from selenium.webdriver.common.action_chains import ActionChains

   driver = webdriver.Firefox()
   source = driver.find_element_by_id('source')
   target = driver.find_element_by_id('target')
   ActionChains(driver)
       .drag_and_drop(source, target)
       .perform() # 执行操作
   #+END_EXAMPLE
4) 悬停
   #+BEGIN_EXAMPLE python
   from selenium import webdriver
   from selenium.webdriver.common.action_chains import ActionChains

   driver = webdriver.Firefox()
   we = driver.find_element_by_id('test')
   ActionChains(driver)
       .move_to_element(we)
       .perform() # 执行操作
   #+END_EXAMPLE

* 键盘事件
通过类Keys来输入键盘上所有按键，甚至是组合键(如 ~Ctrl+A~ 等)

#+BEGIN_EXAMPLE python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox()
we = driver.find_element_by_id('test')

we.send_keys(Keys.BACK_SPACE) # 删除键
we.send_keys(Keys.SPACE)
we.send_keys(Keys.TAB)
we.send_keys(Keys.ESCAPE)
we.send_keys(Keys.ENTER)
we.send_keys(Keys.CONTROL, 'a') # Ctrl+A
we.send_keys(Keys.F1)
we.send_keys(Keys.F12)
#+END_EXAMPLE

* 操作iframe/frame
#+BEGIN_EXAMPLE python
"""
切换到指定的iframe或frame中

Args:
    loc(str|WebElement): 字符串时会作为id或name来定位iframe/frame，或直接传递iframe/frame的WebElement对象。
"""
driver.switch_to.frame(loc)

"""
返回上一级iframe/frame中
"""
driver.switch_to.parent_content()

"""
返回最外层的iframe/frame中
"""
driver.switch_to.default_content()
#+END_EXAMPLE

* 操作警告弹出窗
#+BEGIN_EXAMPLE python
driver.switch_to_alert() # 获取当前alert/confirm/prompt弹出窗

driver.switch_to_alert().text # 获取当前alert/confirm/prompt弹出窗的提示信息
driver.switch_to_alert().accept() # 接受现有警告框
driver.switch_to_alert().dismiss() # 解散现有警告框
driver.switch_to_alert().send_keys(message) # 向文本框输入信息
#+END_EXAMPLE

* 上传文件
** 普通上传——文件作为值放在input标签中，然后通过form提交实现上传
#+BEGIN_EXAMPLE python
# 通过send_keys设置文件路径
driver.find_element_by_name('file').send_keys('d:\\upload_file.txt')
#+END_EXAMPLE

** 插件上传——通过Flash、JavaScript或Ajax等技术实现上传
通过外部工具AutoIt进行Windows GUI操作脚本化录制，然后通过 ~os.system~ 调用。

* 操作Cookie
#+BEGIN_EXAMPLE python
"""
获取所有cookie信息

Returns:
    list<dict>: 所有cookie信息

Examples:
    每个dict的内容为httpOnly:bool, name:str, secure:bool, expiry:int, value:str, path:str, domain:str.
"""
driver.get_cookies()

"""
根据名称获取cookie信息

Args:
    name(str):

Returns:
    dict:
"""
driver.get_cookie(name)

"""
添加cookie

Args:
    cookie_dict(dict): 必须包含name和value的键值

Examples:
    driver.add_cookie({'name': 'test', 'value': '123'})
"""
driver.add_cookie(cookie_dict)

"""
删除cookie信息

Args:
    name(str): cookie的name值
    optionsString(str): 仅支持path和domain，如path="/"; domain=”www.foo.com“
"""
driver.delete_cookie(name, optionsString)

"""
删除所有cookie信息
"""
driver.delete_all_cookies()
#+END_EXAMPLE

* 执行JavaScript
#+BEGIN_EXAMPLE python
el = driver.find_element((By.ID, 'test'))
driver.execute_script('arguments[0].setAttribute("style", arguments[1]);', el, 'backgroud: green;border: 2px solid red;')
#+END_EXAMPLE

* 滚动到某元素
#+begin_example python
el_box = driver.find_element_by_css_selector('.box')
js = 'arguments[0].scrollIntoView();'
driver.execute_script(js, el_box)
#+end_example

* 控制HTML5视频播放
要借助JavaScript控制
#+BEGIN_EXAMPLE python
url = driver.execute_script('return arguments[0].currentSrc', video)
driver.execute_script('arguments[0].play()', video)
driver.execute_script('arguments[0].pause()', video)
driver.execute_script('arguments[0].load()', video)
#+END_EXAMPLE

* 截屏
#+BEGIN_EXAMPLE python
# 截图当前窗口，并保存。
driver.get_screenshot_as_file("/path/to/screenshot.jpg")

#+END_EXAMPLE

* WebDriver原理
采用Server-Client架构，我们编写的则为Client端，向Server端发送指令操作浏览器。
WebDriver的工作流程：
1) WebDriver启动目标浏览器，并绑定到指定端口。而被启动的浏览器实例则作为WebDriver的Remote Server。
2) Client端通过CommandExecutor发送HTTPRequest给Remote Server的侦听端口(通信协议：the webdriver wire protocol)
3) Remote Server需要依赖原生的浏览器组件(如IEDriverServer.exe、chromedriver.exe、geckodriver.exe)来转化浏览器的native调用。

其中若开启logging模块的debug模式，那么就能捕获到Client向Server发送的POST请求，但无法获取Server端的应答。

* 自动化测试模型
  库(Library)，由代码集合成的一个产品，供程序员调用。采用面向对象组织形式的库称为类库，而采用面向过程组织形式的库称为函数库。

  框架(Framework)，为解决一个或一类问题而开发的产品，用于只需使用框架提供的类或函数即可实现所有功能。如unittest可用于实现测试用例的组织和执行，完成单元测试的所有工作。

  工具(Tools)，提供单独的操作界面供用户操作实现特定任务。如Selenium IDE。

  而测试模型即为测试工具和框架的设计思想。

** 线性测试
   早期的测试模块，通过录制或编写模拟用户完整的操作场景，并且各测试脚本互不依赖。

   - 优点：
     1) 每个脚本可以独立运行
   - 缺点：
     1) 开发成本高，大量重复代码
     2) 维护成本高，大量重复代码

** 模块化驱动测试
   对线性测试模型进行改进，利用程序语言特性将公共部分抽取出来实现重用。

** 数据驱动测试
   实质上即为测试数据的参数化，从外部文件(excel,csv,txt.html等)导入测试用数据。

** 关键字驱动测试
   将数据更换为关键字，通过图形界面向让用户在其提供的表格上填写工具提供的关键字来以过程式的方式编写测试用例，而Robot Framework是其中的佼佼者。
   相当于一套GUI的DSL，因此还不如直接写脚本。

* Selenium Grid2
让位于主节点(HUB)的测试用例可以在不同的分支节点(NODE)上运行，从而实现并行在不同的浏览器版本和操作系统组合上测试。
已经集成到Selenium Server当中，因此需下载Selenium Server(http://www.seleniumhq.org/download/)。
必须启动一个HUB和至少一个NODE。

1) 测试脚本(脚本位于IP为192.168.127.3上)
   #+BEGIN_EXAMPLE python
   from selenium.webdriver import Remote

   # 定义测试主机和浏览器类型
   lists = {'http://192.168.127.3:4444/wd/hub': 'chrome',
            'http://192.167.127.4:5555/wd/hub': 'firefox',
            'http://192.167.127.4:5555/wd/hub': 'internet explorer',}

   # 可配合多进程多线程实现并行测试
   for host, browser in lists:
       driver = Remote(command_executor=host, # 指定测试主机，默认为http://127.0.0.1:4444/wd/hub
                       desired_capabilities={'platform': 'ANY',
                                             'browserName': browser,
                                             'version': '',
                                             'javascriptEnabled': True})
       driver.get('http://www.baidu.com')
       driver.find_element_by_id('kw').send_keys(browser)
       driver.close()
   #+END_EXAMPLE
2) 启动HUB(假设IP为192.168.127.3)
   #+BEGIN_EXAMPLE bash
   # HUB的默认端口号为4444
   java -jar selenium-server-standalone-2.27.0.jar -role hub -port 4444
   #+END_EXAMPLE
3) 启动NODE(假设IP为192.168.127.4)
   #+BEGIN_EXAMPLE bash
   # NODE的默认端口号为5555
   java -jar selenium-server-standalone-2.27.0.jar -role node -port 5555 -hub http://192.168.127.3:4444/grid/register
   #+END_EXAMPLE

* Page Object 设计模式
  作为Selenium的最佳实践之一，由如下优点：
  1) 减少代码的重复
  2) 提高测试用例的可读性
  3) 提高测试用例的可维护性，特别是针对UI频繁变化的项目

  规则：
  1) 一个HTML页面对应一个Page Object。
  2) 凡是人能做的事，Page Object通过webdriver都能做到。
     - 即Page的方法以功能来定义，将具体的元素操作隐藏在底层
       - 示例
         1) 选择左侧功能菜单的某个项目 ~select_menu(name)~
         2) 在用户名称输入框输入信息 ~set_username(text)~
  3) 然后在测试用例中调用Page Object的方法编排测试逻辑

* Component Driven 设计模式
  基于 Page Object 设计模式作扩展，针对大型项目。

** 目录结构
   #+BEGIN_EXAMPLE yaml
   project/
     - reports/
     - tests/
         - components/     # 公共组件
             - __init__.py
             - menu.py
             - list.py
         - pages/          # 页面
             - __init__.py
             - main/
                 - __init__.py # 页面
                 - list.py     # 私有组件
         - scenarios/      # 操作场景
             - __init__.py
             - login.py
             - submit_form.py

         - test_hr.py # 针对场景作测试
   #+END_EXAMPLE

* TODO WebDriver配置

** Firefox
https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
FireFox启动速度慢。

#+BEGIN_EXAMPLE python
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.firefox.options import Options


firefox_options = Options()
firefox_options.add_argument('--headless')
firefox_options.add_argument('--disable-gpu')
firefox_options.add_argument('--mute-audio') # without audio
firefox_options.add_argument('user-agent=Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36')
driver_path = r'C:\Program Files (x86)\Mozilla Firefox\geckodriver.exe'
binary = FirefoxBinary(r'C:\Program Files (x86)\Mozilla Firefox\firefox.exe')
driver = webdriver.Firefox(firefox_binary=binary,
                           firefox_options=firefox_options
                           executable_path=driver_path)
#+END_EXAMPLE

1) 设置默认文件下载路径
   #+BEGIN_EXAMPLE python
   from selenium import webdriver
   import os

   fp = webdriver.FirefoxProfile()
   # 0表示下载到浏览器默认下载路径，2为下载到指定目录
   fp.set_preference('browser.download.folderList', 2)
   # 是否显示开始，True为显示、False为不显示
   fp.set_preference('browser.download.manager.showWhenStarting', False)
   # 指定下载目录
   fp.set_preference('browser.download.dir', os.getcwd())
   # 指定下载内容的Content-type值
   fp.set_preference('browser.helperApps.neverAsk.saveToDisk', 'application/octet-stream')

   driver = webdriver.Firefox(firefox_profile=fp)
   #+END_EXAMPLE
2) 设置无界面操作
   #+BEGIN_EXAMPLE python
   from selenium import webdriver
   from selenium.webdriver.firefox.options import Options


   firefox_options = Options()
   firefox_options.add_argument('--headless')
   firefox_options.add_argument('--disable-gpu')
   firefox_options.add_argument('--mute-audio') # without audio
   driver = webdriver.Firefox(firefox_options=firefox_options)
   #+END_EXAMPLE
3) 设置WebDriver路径
   #+BEGIN_EXAMPLE python
   from selenium import webdriver

   driver_path = r'C:\Program Files (x86)\Mozilla Firefox\geckodriver.exe'
   driver = webdriver.Firefox(executable_path=driver_path)
   #+END_EXAMPLE
4) 设置浏览器可执行文件路径
   #+BEGIN_EXAMPLE python
   from selenium import webdriver
   from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

   binary = FirefoxBinary(r'C:\Program Files (x86)\Mozilla Firefox\firefox.exe')
   driver = webdriver.Firefox(firefox_binary=binary)
   #+END_EXAMPLE
5) 其它
   #+BEGIN_EXAMPLE python
   from selenium import webdriver
   from selenium.webdriver.firefox.options import Options


   firefox_options = Options()
   firefox_options.add_argument('user-agent=Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36')
   driver = webdriver.Firefox(firefox_options=firefox_options)
   #+END_EXAMPLE
6) 设置代理
   #+begin_example python
   from selenium import webdriver
   from selenium.webdriver.firefox.firefox_profile import FirefoxProfile

   # Firefox所有profile设置：http://kb.mozillazine.org/Firefox_:_FAQs_:_About:config_Entries
   # 在Firefox的地址栏输入about:config查看配置即可
   profile = FirefoxProfile()
   profile.set_preference("network.proxy.type", 1) # 启动手动设置代理，默认为0——直接连接
   profile.set_preference("network.proxy.http", proxy_url)
   profile.set_preference("network.proxy.http_port", proxy_port)
   profile.set_preference("network.proxy.ssl", ssl_url)
   profile.set_preference("network.proxy.ssl_port", ssl_port)
   profile.update_prefrences()
   driver = webdriver.Firefox(profile)


   proxy = "212.66.117.168:41258"


# 其他方式
# As after 46 version of firefox you need to use geckodriver and for that you can set up proxy this way.
firefox_capabilities = webdriver.DesiredCapabilities.FIREFOX
firefox_capabilities['marionette'] = True

firefox_capabilities['proxy'] = {
    "proxyType": "MANUAL",
    "httpProxy": proxy,
    "ftpProxy": proxy,
    "sslProxy": proxy
}

driver = webdriver.Firefox(capabilities=firefox_capabilities)


proxy = "212.66.117.168:41258"
prox = Proxy()
prox.proxy_type = ProxyType.MANUAL
prox.http_proxy = proxy
prox.socks_proxy = proxy
prox.ssl_proxy = proxy

capabilities = webdriver.DesiredCapabilities.CHROME
prox.add_to_capabilities(capabilities)
driver = webdriver.Chrome(desired_capabilities=capabilities)
   #+end_example

** Chrome
chromium: https://centos.pkgs.org/7/epel-x86_64/chromium-79.0.3945.88-1.el7.x86_64.rpm.html
chromedriver: http://chromedriver.storage.googleapis.com/index.html

| chromedriver版本 | 支持的Chrome版本 |
|------------------+------------------|
| v2.40            | v66-68           |
| v2.39            | v66-68           |
| v2.38            | v65-67           |
| v2.37            | v64-66           |
| v2.36            | v63-65           |
| v2.35            | v62-64           |
| v2.34            | v61-63           |
| v2.33            | v60-62           |
| v2.32            | v59-61           |
| v2.31            | v58-60           |
| v2.30            | v58-60           |
| v2.29            | v56-58           |
| v2.28            | v55-57           |
| v2.27            | v54-56           |
| v2.26            | v53-55           |
| v2.25            | v53-55           |
| v2.24            | v52-54           |
| v2.23            | v51-53           |
| v2.22            | v49-52           |
| v2.21            | v46-50           |
| v2.20            | v43-48           |
| v2.19            | v43-47           |
| v2.18            | v43-46           |
| v2.17            | v42-43           |
| v2.13            | v42-45           |
| v2.15            | v40-43           |
| v2.14            | v39-42           |
| v2.13            | v38-41           |
| v2.12            | v36-40           |
| v2.11            | v36-40           |
| v2.10            | v33-36           |
| v2.9             | v31-34           |
| v2.8             | v30-33           |
| v2.7             | v30-33           |
| v2.6             | v29-32           |
| v2.5             | v29-32           |
| v2.4             | v29-32           |

#+BEGIN_EXAMPLE python
from selenium  import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--ignore-certificate-errors')
chrome_options.add_argument('--test-type')
chrome_options.binary_location = '/path/to/chromium'
##INFO = 0
##WARNING = 1
##LOG_ERROR = 2
##LOG_FATAL = 3
##default is 0
chrome_options.add_argument('--log-level=3')
driver_path = r'C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe'
driver = webdriver.Chrome(chrome_options=chrome_options
                          executable_path=driver_path)
#+END_EXAMPLE

** IE
#+BEGIN_EXAMPLE python
driver = webdriver.Ie()
#+END_EXAMPLE

* BDD框架——Lettuce入门
Behavior Driven Development 作为敏捷软件开发技术，主要从用户的需求出发，强调系统行为。在2003年初由Dan North命名。
BDD框架:
1) Cucumber(Ruby)
2) Jdave(Java)
3) Behat(PHP)
4) Behave(Python)
5) Lettuce(Python)

Lettuce允许使用自然语言(英语)描述一个系统的行为，操作步骤如下：
1) decribe behaviour
2) define step in python
3) run and watch it fail
4) write code to make it pass
5) run and watch it pass

** 示例
目录结构：
#+BEGIN_QUOTE
tests/
    - features/
             - zero.feature
             - steps.py
#+END_QUOTE

#+BEGIN_EXAMPLE
# zero.feature
Feature: Compute factorial
   In order to play with Lettuce
   As beginners
   We'll implement factorial

Scenario: Factorical of 0
Given I have the number 0
When I compute its factorial
Then I see the number 1
#+END_EXAMPLE

#+BEGIN_EXAMPLE python
from lettuce import *

@step('I have the number (\d+)')
def have_the_number(step, number):
    world.number = int(number)

@step('I compute its factorial')
def compute_its_factorial(step):
    world.number = factorial(world.number)

@step('I see the number (\d+)')
def check_number(step, expected):
    expected = int(expected)
    assert world.number == expected, 'Got %d' % world.number

def factorial(number):
    number = int(number)
    if (number == 0) or (nummber == 1):
        return 1
    else:
        return number
#+END_EXAMPLE

* QA
  1) 启动Firefox时运行报 ~selenium.common.exceptions.WebDriverException: Message: newSession~
     - 原因：geckodriver版本太旧。
     - 解决方法：到 https://github.com/mozilla/geckodriver/releases 下载最新版的geckodriver到环境变量 ~PATH~ 下，若采用virtualenv创建虚拟环境则放在虚拟环境python/bin即可。
  2) 运行时偶发性抛出 ~selenium.common.exceptions.ElementNotInteractableException~
     - 原因：由于页面渲染和行为具有时间不精准性，因此有可能在元素被遮挡或不可见时就调用 ~click()~ 的方法。
     - 解决方法：通过EC检测元素状态，若可交互才执行 ~click()~ 等方法。
  3) 启动时报 ~selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities~
     - 原因：Firefox没有安装或版本与浏览器驱动不匹配
  4) 启动时报 ~selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process~
     - 原因：
       #+begin_quote
       implies that the GeckoDriver was unable to initiate/spawn a new WebBrowsing Session i.e. Firefox Browser session.
       Your main issue is the incompatibility between the version of the binaries you are using as follows:
       Your GeckoDriver version is 0.22.0.
       Release Notes of GeckoDriver v0.21.0 (2018-06-15) clearly mentions the following:
       Firefox 57 (and greater)
       Selenium 3.11 (and greater)
       Your Firefox version is 52.9.0.
       So there is a clear mismatch between GeckoDriver v0.22.0 and the Firefox Browser v57
       #+end_quote
     - 解决方法：
       #+begin_quote
       Upgrade GeckoDriver to GeckoDriver v0.22.0 level.
       GeckoDriver is present in the specified location.
       GeckoDriver is having executable permission for non-root users.
       Upgrade Firefox version to Firefox v62.0.2 levels.
       Clean your Project Workspace through your IDE and Rebuild your project with required dependencies only.
       If your base Web Client version is too old, then uninstall it through Revo Uninstaller and install a recent GA and released version of Web Client.
       Execute your Selenium Test as a non-root user.
       #+end_quote
     - 参考：https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
       #+begin_quote
       Running as root, I didn't think can be a problem. It was, thanks. When I was setting custom capabilities the error was different although with same root cause. Pasting here for anybody searching: Unable to find a matching set of capabilities (Selenium::WebDriver::Error::SessionNotCreatedError)
       #+end_quote
* TODO Browsermob-Proxy
基于LittleProxy的使用Java开发的开源代理程序。
官网：https://github.com/lightbody/browsermob-proxy

HAR file(HTTP档案规范， http://www.softwareishard.com/blog/har-12-spec/):
用于存储HTTP请求响应信息的通用文件格式，基于JSON。Firebug、httpwatch和Fiddler等都支持该格式。

1) 安装Browsermob-Proxy服务端
   https://github.com/lightbody/browsermob-proxy/releases
2) 安装Python API包
   #+begin_example bash
   pip instlal browsermob-proxy
   #+end_example
3) 使用
   #+begin_example python
   from browsermobproxy import Server
   from selenium import webdriver
   from selenium.webdriver.chrome.options import Options


   # 创建代理服务
   proxy_server = Server("/path/to/browsermob-proxy")
   proxy_server.start()
   proxy = proxy_server.create_proxy()

   # 创建Selenium客户端
   chrome_options = Options()
   chrome_options.add_argument("--proxy-server=%s" % proxy.proxy)
   driver = webdriver.Chrome(chrome_options=chrome_options)

   # 创建Firefox客户端
   # https://browsermob-proxy-py.readthedocs.io/en/stable/
   from selenium import webdriver
   profile  = webdriver.FirefoxProfile()
   profile.set_proxy(proxy.selenium_proxy())
   driver = webdriver.Firefox(firefox_profile=profile)

   # 设置拦截内容
   proxy.new_har("john", options={"captureHeaders": True, "captureContent": True})
   driver.get("http://fsjohnhuang.io")
   result = proxy.har # 返回HAR JSON
   for entry in result["log"]["entries"]:
       url = entry["request"]["url"]
       resp = entry["response"]
       content = resp["content"]["text"]

   # 善后
   server.stop()
   # 由于server.stop()并不能彻底清除相关进程，可以添加如下内容彻底结束进程
   find_port = 'netstat -aon|findstr %s' % self.port
   result = os.popen(find_port)
   text = result.read()
   pid_line = text.split('\n', 1)[0]
   pid = pid_line.replace(" ","").split("LISTENING")[1]
   find_kill= 'taskkill -f -pid %s' % pid
   result = os.popen(find_kill)
   os.close()

   driver.quit()
   #+end_example
* TODO PyPubSub
http://pypubsub.sourceforge.net/

#+begin_example python
from pubsub import pub

def topic1_handler(message, extra=None): pass
def topic1_handler(message1, message2, extra=None): pass

pub.subscribe(listener, pub.ALL_TOPICS) # 订阅所有消息
pub.subscribe(listener, "rootTopic") # 订阅顶级主题
pub.subscribe(listener, "rootTopic.subTopic") # 订阅子级主题

pub.AUTO_TOPIC #
pub.AUTO_TOPIC.getName()

pub.sendMessage("rootTopic", message=1, extra=2)
#+end_example
