* How to Install Emacs 27.x
1. Add PPA Repository ~sudo add-apt-repositry ppa:kelleyk/emacs~
2. Install by APT
   #+begin_src bash
   sudo apt update
   sudo apt install emacs27
   #+end_src
3. Uninstall
   #+begin_src bash
   sudo add-apt-repository --rmove ppa:kelleyk/emacs
   sudo apt remove --autoremove emacs27
   #+end_src

** Issue: Unmet Dependencies
   The *unmet dependencies* will be thrown whenever you run ~apt-get upgrade~ or ~apt-get install~, if there were broken before.
   The solutions are:
   1. Install the dependencies with ~--fix-broken~ option
      #+begin_src bash
      sudo apt --fix-broken install
      sudo apt-get update
      # If the above solution does not work, try the second one.
      #+end_src
   2. Remove the application which cause this problem.

* What is PPA source?
  PPA means Personal Package Archives as all are hosted on launchpad.net for Ubuntu users.
  There are *daily*, *dev*, *stable* and *beta* version of each application that you can choose as you like.

  #+begin_src bash
  sudo add-apt-repository ppa:chromium-daily/stable # Add https://launchpad.net/~choromium-daily/+archive/daily to local apt source.
  sudo apt-get update
  sudo apt-get install chromium-daily
  #+end_src


* TODO 包仓库
  中国大陆镜像：http://elpa.emacs-china.org/

** QA
   1) 若使用gnu仓库时报如下问题
      - 问题描述
        #+begin_quote
        Failed to verify signature archive-contents.sig: (\"No public key for 474F05837FBDEF9B created at 2014-09-29T07:20:03-0700 using DSA
        #+end_quote
      - 解决办法
        为Emacs版本问题，需要在init.el中添加 ~(setq package-check-signature nil)~ 即可。


* 目录/文件操作
通过 ~C-x d~ 进入 Dired Mode，屏幕显示当前目录的文件和子目录。
- 光标移动到对应的文件/目录上
  1) ~d~ ，标记为将要删除
  2) ~D~ ，立即删除
  3) ~R~ ，立即重命名
  4) ~C~ ，立即复制
  5) ~u~ ，取消光标所在文件/目录的标记
  6) ~U~ ，取消所有标记
  7) ~x~ ，执行标记的动作
- ~^~ ，跳转到上一层目录

* 分屏
~C-x 0~ ，关闭当前窗口
~C-x 1~ ，最大化当前窗口
~C-x 2~ ，上下分屏
~C-x 3~ ，左右分屏

* 包
gnuplot，画图
graphviz，dot语言解释器，用于画流程图
  C-c c 编译生成图片， C-c p 可以预览图片
ido， ~C-x~ 键的增强
smex， ~M-x~ 键的增强
helm-bibtex，管理和插入参考文档
company，代码和英语单词补全
flycheck，实时语法检查
langtool和flyspell，语法和拼写检查
helm-show-kill-ring，复制粘帖工具
minted，高亮tex代码
[[https://github.com/emacs-helm/helm][helm]]
imenu，显示当前buffer的函数列表，可实现跳转。
helm-dash 看编程文档
cnfonts 配置中英文等宽字体
ac-html 网页必需的package，提供自動補全html的能力。
magit Git

** Company: Complete Anything
一个可配置的前端和后端套件，前端负责和Emacs交互，后端负责链接具体的语言解析/编译器。
内置的后端：elisp, Clang, CMake, files, keyword, capf等
第三方的后端：JavaScript/TypeScript使用微软的tsserver或lsp等，c/c++使用irony或rtags，Python使用Jedi。

1) 配置
   #+begin_example elisp
   ;; 全局启用company mode，或 (add-hook 'after-init-hook 'global-company-mode)
   (global-company-mode t)
   ;; 响应时间，若态吃CPU则设置为0.3
   (setq company-idle-delay 0)
   ;; 至少打完3个字符才启动
   (setq company-minimun-prefix-length 3)
   ;; 设置全局的后端，company会逐个询问后端若有响应则中断询问并返回结果
   ;; 可以如下面一样对后端进行分组，company会按组询问并将组内所有后端的响应结果都返回
   (setq company-backends
         '((company-files
            company-keywords
            company-capf
            company-yasnippet)
           (company-abbrev company-dabbrev)))

   ;; 根据major mode加入后端
   (add-hook 'emacs-lisp-mode-hook
     (lambda ()
       (add-to-alist (make-local-variable 'company-backends)
         '(company-lisp))))

   ;; 根据major mode移除其他后端，设置指定后端
   (add-hook 'emacs-lisp-mode-hook
     (lambda ()
       (set (make-local-variable 'company-backends)
         '(company-lisp))))
   #+end_example
2) 操作
   1) ~C-h v company-backends~ 查看现在和原来的company-backends绑定值
   2) ~M-x company-diag~ 显示company-backeds绑定值，生效的后端，启用前缀等信息
3) 上下移动选择参考项
   默认采用 ~M-n~ 和 ~M-p~ 移动游标，但可以重新绑定为 ~C-n~ 和 ~C-p~
   #+begin_example elisp
   (with-eval-after-load 'company
     (define-key company-active-map (kbd "\C-n") #'company-select-next)
     (define-key company-active-map (kbd "\C-p") #'company-select-previous)
     (define-key company-active-map (kbd "M-n") nil)
     (define-key company-active-map (kbd "M-p") nil))
   #+end_example
4) 对于company-mode和yasnippet的tab键冲突的情况，优先使用yasnippet
   #+begin_example elisp
   (advice-add 'company-complete-common :before (lambda ()
     (setq my-company-point (point))))
   (advice-add 'company-complete-common :after (lambda ()
     (when (equal my-company-point (point)) (yas-expand))))
   #+end_example
** Web-mode
1) 功能
   1) 自动缩进
   2) 语法高亮
   3) 程序折叠
   4) 支持多种语言(vue,jsx,php,jinja2,jsp,asp,mustache,html等)
2) 配置
   #+begin_example elisp
   (setq web-mode-markup-indent-offset 2)
   (setq web-mode-css-indent-offset 2)
   (setq web-mode-code-indent-offset 2)
   (setq web-mode-enable-current-element-highlight t)
   (setq web-mode-enable-css-colorization t)
   #+end_example
3) 根据web-content-type来分别设置配置项
   #+begin_example elisp
   (defun my/web-html-setup ()
     "Setup for web-mode html files."
     (message "web-mode use html related setup")
     (flycheck-add-mode 'html-tidy 'web-mode)
     (flycheck-select-checker 'html-tidy)
     (add-to-alist (make-local-variable 'company-backends)
       '(company-web-html))
     (add-hook 'before-save-hook 'sgml-pretty-print))

   (add-hook 'web-mode-hook
             (lambda ()
               (cond ((equal web-mode-content-type "html")
                      (my/web-html-setup)))))
   #+end_example

** Emmet-mode
官网：https://github.com/smihica/emmet-mode
#+begin_example elisp
(add-hook 'web-mode-hook 'emmet-mode)
(add-hook 'css-mode-hook 'emmet-mode)
(add-hook 'scss-mode-hook 'emmet-mode)
(add-hook 'sgml-mode-hook 'emmet-mode)
(add-hook 'react-mode-hook 'emmet-mode)
#+end_example

* 处理特殊符号 ~^M~ 和 换行符
输入 ~^M~: ~c-q c-m~
输入换行符: ~c-q c-j~

替换 ~^M~ (Mac的换行符号)
1) 替换： ~m-x replace-string RET c-q c-m RET RET~
2) 修改为Unix编码： ~c-x RET utf-8-unix RET c-x c-w RET y~
* 代码格式化
** 内置方式
#+begin_example elisp
M-x mark-whole-buffer ;; 或 C-x h，选中整个缓冲区
M-x indent-buffer     ;; 格式化

M-x mark-defun        ;; 或 C-M-h，选中当前函数
#+end_example
* emacs后台服务模式运行
在.zshrc中欧给你加入
#+begin_example bash
# alias emacs
alias emacsd='emacs --daemon'
alias e='emacsclient -t'
alias ec='emacsclient -c'

# run emacs daemon
[[ -z $(ps -C 'emacs --daemon' -o pid=) ]] && emacsd

# add kill emacs function
function kill-emacs(){
    emacsclient -e "(kill-emacs)"
    emacs_pid=$( ps -C 'emacs --daemon' -o pid= )
    if [[ -n "${emacspid}" ]];then
        kill -9 "${emacs_pid}"
    fi
}
#+end_example
~emacsd~ 运行后台服务
~ec~ 新建一个图形化窗口(frame)编辑，若连接不到X Server则打开一个新虚拟终端编辑
~e~ 在当前终端编辑
~kill-emacs~ 关闭后台服务
* Shell and Ternimal Emulation
** The Inferior Shell

All external, interactive shells(e.g. ~M-x shell~ and ~M-x python-shell~) in Emacs are derived from *comint-mode*.
~M-x shell~ runs a the *inferior shell* as is the wrapper around your default shell. It is governed by ~explicit-shell-file-name~, ~ESHELL~ environment variable or ~shell-file-name~, in that order.


All *shell* does is redirect the input and output to Emacs, and that means interactive console(like top, ssh, etc.) won't work properly.

** Terminal Emulator
https://www.gnu.org/software/emacs/manual/html_node/emacs/Terminal-emulator.html#Terminal-emulator

The Emacs terminal emulator is exactly that: it emulates the VT100-style ANSI escape codes, just like *xterm* or *rxvt*.
It isn't complete or perfect, but most things like ~top~ and ~ssh~ will work properly. To run the terminal emulator, type ~M-x term~ or ~M-x ansi-term~ (for full ANSI support).

*line mode* enabled by ~C-c C-j~, the terminal buffer will behave much like *shell mode* and normal Emacs buffers.
*char mode* enabled by ~C-C C-k~, each character is sent directly to the underlying inferior shell without preprocessing by Emacsd.

** The Emacs Shell (eshell)
EShell is written entirely in EmacsLisp. To invoke it, run ~M-x eshell~.
1. EShell is a feature-rich replacement for your standard-fare shells linke *bash* with the added bonus of working on any platform Emacs runs on.
2. EShell has gone to some lengths to keep the syntax familiar with *bash*.
3. EShell is clever enough to redirect certain commands that Emacs itself offers, such as ~man~, ~grep~ and so on.
4. woefully underdocumented.
* projectile
  插件：counsel-projectile

** 配置
   #+begin_src elisp
   (projectile-global-mode)
   (setq projectile-enable-caching t)
   (global-set-key (kbd "<f5>") 'projectile-find-file) ;; 通过文件名全项目范围内搜索文件
   #+end_src
