* 目录/文件操作
通过 ~C-x d~ 进入 Dired Mode，屏幕显示当前目录的文件和子目录。
- 光标移动到对应的文件/目录上
  1) ~d~ ，标记为将要删除
  2) ~D~ ，立即删除
  3) ~R~ ，立即重命名
  4) ~C~ ，立即复制
  5) ~u~ ，取消光标所在文件/目录的标记
  6) ~U~ ，取消所有标记
  7) ~x~ ，执行标记的动作
- ~^~ ，跳转到上一层目录

* 分屏
~C-x 0~ ，关闭当前窗口
~C-x 1~ ，最大化当前窗口
~C-x 2~ ，上下分屏
~C-x 3~ ，左右分屏

* 包
gnuplot，画图
graphviz，dot语言解释器，用于画流程图
  C-c c 编译生成图片， C-c p 可以预览图片
ido， ~C-x~ 键的增强
smex， ~M-x~ 键的增强
helm-bibtex，管理和插入参考文档
company，代码和英语单词补全
flycheck，实时语法检查
langtool和flyspell，语法和拼写检查
helm-show-kill-ring，复制粘帖工具
minted，高亮tex代码
[[https://github.com/emacs-helm/helm][helm]]
imenu，显示当前buffer的函数列表，可实现跳转。
helm-dash 看编程文档
cnfonts 配置中英文等宽字体
ac-html 网页必需的package，提供自動補全html的能力。
magit Git

** Company: Complete Anything
一个可配置的前端和后端套件，前端负责和Emacs交互，后端负责链接具体的语言解析/编译器。
内置的后端：elisp, Clang, CMake, files, keyword, capf等
第三方的后端：JavaScript/TypeScript使用微软的tsserver或lsp等，c/c++使用irony或rtags，Python使用Jedi。

1) 配置
   #+begin_example elisp
   ;; 全局启用company mode，或 (add-hook 'after-init-hook 'global-company-mode)
   (global-company-mode t)
   ;; 响应时间，若态吃CPU则设置为0.3
   (setq company-idle-delay 0)
   ;; 至少打完3个字符才启动
   (setq company-minimun-prefix-length 3)
   ;; 设置全局的后端，company会逐个询问后端若有响应则中断询问并返回结果
   ;; 可以如下面一样对后端进行分组，company会按组询问并将组内所有后端的响应结果都返回
   (setq company-backends
         '((company-files
            company-keywords
            company-capf
            company-yasnippet)
           (company-abbrev company-dabbrev)))

   ;; 根据major mode加入后端
   (add-hook 'emacs-lisp-mode-hook
     (lambda ()
       (add-to-alist (make-local-variable 'company-backends)
         '(company-lisp))))

   ;; 根据major mode移除其他后端，设置指定后端
   (add-hook 'emacs-lisp-mode-hook
     (lambda ()
       (set (make-local-variable 'company-backends)
         '(company-lisp))))
   #+end_example
2) 操作
   1) ~C-h v company-backends~ 查看现在和原来的company-backends绑定值
   2) ~M-x company-diag~ 显示company-backeds绑定值，生效的后端，启用前缀等信息
3) 上下移动选择参考项
   默认采用 ~M-n~ 和 ~M-p~ 移动游标，但可以重新绑定为 ~C-n~ 和 ~C-p~
   #+begin_example elisp
   (with-eval-after-load 'company
     (define-key company-active-map (kbd "\C-n") #'company-select-next)
     (define-key company-active-map (kbd "\C-p") #'company-select-previous)
     (define-key company-active-map (kbd "M-n") nil)
     (define-key company-active-map (kbd "M-p") nil))
   #+end_example
4) 对于company-mode和yasnippet的tab键冲突的情况，优先使用yasnippet
   #+begin_example elisp
   (advice-add 'company-complete-common :before (lambda ()
     (setq my-company-point (point))))
   (advice-add 'company-complete-common :after (lambda ()
     (when (equal my-company-point (point)) (yas-expand))))
   #+end_example
** Web-mode
1) 功能
   1) 自动缩进
   2) 语法高亮
   3) 程序折叠
   4) 支持多种语言(vue,jsx,php,jinja2,jsp,asp,mustache,html等)
2) 配置
   #+begin_example elisp
   (setq web-mode-markup-indent-offset 2)
   (setq web-mode-css-indent-offset 2)
   (setq web-mode-code-indent-offset 2)
   (setq web-mode-enable-current-element-highlight t)
   (setq web-mode-enable-css-colorization t)
   #+end_example
3) 根据web-content-type来分别设置配置项
   #+begin_example elisp
   (defun my/web-html-setup ()
     "Setup for web-mode html files."
     (message "web-mode use html related setup")
     (flycheck-add-mode 'html-tidy 'web-mode)
     (flycheck-select-checker 'html-tidy)
     (add-to-alist (make-local-variable 'company-backends)
       '(company-web-html))
     (add-hook 'before-save-hook 'sgml-pretty-print))

   (add-hook 'web-mode-hook
             (lambda ()
               (cond ((equal web-mode-content-type "html")
                      (my/web-html-setup)))))
   #+end_example

** Emmet-mode
官网：https://github.com/smihica/emmet-mode
#+begin_example elisp
(add-hook 'web-mode-hook 'emmet-mode)
(add-hook 'css-mode-hook 'emmet-mode)
(add-hook 'scss-mode-hook 'emmet-mode)
(add-hook 'sgml-mode-hook 'emmet-mode)
(add-hook 'react-mode-hook 'emmet-mode)
#+end_example
