* Kitchen
refrigerator /rɪˈfrɪdʒəreɪtər/ 冰箱
fridge /frɪdʒ/ 冰箱
freezer 冰箱
dish rack 碗架
counter 柜台
sink 水槽
wok 中式炒菜锅
pan 平底锅
frying pan 长柄平底煎锅
turner/spatula /ˈspætʃələ/ 锅铲
ladle 长柄勺
gas stove 燃气灶
ventilator /ˈventɪleɪtər/ 抽油烟机，换气扇
apron 围裙
cpuboard 碗柜
cabinet 储物柜
oven 烤箱
oven glove 烘烤用手套
measuring cup/spoon 量杯
tongs /tɑːŋz/ 夹面包/牛肉等用的夹子
microwave 微波炉
thermos 保温瓶
electric kettle 电热水壶
medicine pot 药煲
soup pot 汤煲
blender 搅拌机，榨汁机
grinder 磨豆机
toaster 烤面包机
cutting board 砧板
water purifier 净水器
knife 刀
grater /ˈɡreɪtər/ 胡萝卜/青瓜的磨丝/碎器
cheese shredder 奶酪磨碎器
spoon 调羹
porcelain spoon /ˈpɔːrsəlɪn/ 瓷调羹
slotted spoon 漏勺
chopsticks 筷子
fork 叉
roller pin 擀面杖
bottle opener 开瓶器
nutcracker 坚果钳
scales 天平，称
roaster/tray 烤盘
steam rack 蒸架
steamer 蒸锅
clay pot 砂锅
mutton in hot pot 羊肉火锅
rice cooker 饭煲
pressure cooker 高压锅
non-stick pan 不粘锅
funnel /ˈfʌnl/ 漏斗
salt shaker 小盐瓶
whisk /wɪsk/ 打蛋器
bowl 碗
soup bowl 汤碗
rice bowl 饭碗
doubler 大碗
dishwasher 洗碗机
freezer bag 保鲜袋
trash/garbage bag 垃圾袋
dustbin/trash can/refuse bin/gabage can 垃圾筒
power strip 电源插排
mop 拖把
dustpan 簸箕
broom 扫把
plug/socket 插座
wall plug 墙上的插座
(deep) frying 炸
pan frying 煎
steaming 蒸
smoked 熏
decoct /diˈkɑːkt/ 熬,煎服
roast/bake 烤
grill /ɡrɪl/ 烤串
dice 切丁
chop 切块
slice 切片
cut into strips 切条
stewing /'stjuɪŋ/ 炖

* Face
head
hair 头发
temple 太阳穴
forehead 额头
eyebrow /ˈaɪbraʊ/ 眉毛
eyelash 眼睫毛
eye 眼睛
iris /ˈaɪrɪs/ 虹膜
ear 耳朵
cheek 面颊
nose 鼻子
nostril /ˈnɑːstrəl/ 鼻孔
jaw /dʒɔː/ 颚
mouth 口
lip 唇
chin 下巴
neck 脖子
shoulder 肩膀
arm 手臂
elbow /ˈelboʊ/ 肘
forearm 前臂
wrist /rɪst/ 手腕
hand 手
armpit /ˈɑːrmpɪt/ 腋窝
back 背部
chest 胸部
waist 腰部
abdomen /ˈæbdəmən/ 腹部
hip 臀部
buttocks 臀部
leg 腿
thigh 大腿
knee 膝盖
calf /kæf/ 小腿
foot 脚丫
heel 脚跟
* TODO TOEIC
mister, a form of address for a man. (a form of address 称呼)
conference, an event where people exchange ideas.
vacation, a holiday or a break from work.
client, somesone who pays for a service.
e-book, an electronic book.
airport, the place where you go to get on a plane.
memo, a written reminder to do something.
reservation, to put something to hold on for use later, e.g. car, hotel room.
logical, to do with reason.
fax, to send using a fax machine.
o'clock, the hour of the day.
sincerely, with honestly.

sometime, at some unknown point in time.
website, a set of internet pages that give information about a particular person or organization.
supervisor, the person who is in charge.
candidate, the person being considered for a job or position in office.
refund, give back money that has already been paid.
goods, resources or things bought or sold.
workshop, a building or room where things are made or repaired.
downtown, the business or central part of a city or town.
deadline, when something must be finished.
invoice, a written request for payment for the goods and services listed.(发票)
brochure, a small paper book that gives information about a product or service.(资料手册)
noon, the middle of the day.
accountant, a person responsible for the money in a business.
clerk, someone who works at a counter(柜台).(职员、服务台接待员)
lobby, the main area of a hotel just inside the entrance.
publish, to print and distribute.
resume, a short statement of the important details of something.
enclose, to surround fully.
applicant, a person who submits papers in order to do something, e.g. job applicant.(申请人)
seminar, a discussion session or class led by a teacher, or expert.
technician, someone who is trained with special skills to do practical work.
cloth, a piece of thin material.
fare, the cost for a ride, e.g. bus, or taxi.
receipt, proof of payment.
traveler, a tourist or adventurer who visits many countries.
caller, the person that is phoning you.
subway, a tunnel under the road for people to walk through.
luggage, bags and cases that you carry your clothes in when you go on a journey.
shipment, delivery of goods, e.g. carried by a large vehicle.
infer, to guess something with given information.
waiter, a man whose job it is to bring meals to your table in a restaurant or cafe.
rental, the act of paying for the use of something(as an apartment or house or car).
warranty, the promise to repair or replace a product if it ceases(停止) to work properly.(保修期，保用单)
cafeteria, a restuarant where you serve youself and pay a cashier(出纳员，付钱给收银员).
chef, a person who cooks for a living.
elevator, a machine that takes people to different floors in a building.
reception, the act of greeting people.
correctly, to do something the right way.
lease, to rent.
bicycle, a vehicle with two wheels and pedals.
notify, officially tell someone some information.
preview, a chance to see something before it becomes generally available.
attendant, someone who waits on or tends to the needs(满足需求) of another.(护工，随从)
subscription, the amount of money that you pay to receive a service or product regularly.
convenient, to be easy to do.
manual, a book that explains how to do something.
clue, a hint, a tip.
garage, a place where you keep your car.
obtain, to get.
oval, a shape that looks like an egg.
inventory, detailed list of everything included.(库存、财产清单)
outdoor, outside in the open air.
suitcase, a large bag like container for carrying clothes when traveling.
destination, the place you want to be at the end of a journey.
occupation, profession or job.
postpone, put off until a later time.
contradict, to say the opposite of(v. 反驳)
umbrella, something, like an organization, that covers a similar range of things.(伞、保护伞)
inference, the act of guessing something with given information.
cellphone, phone that connects to the system by raido so that you can use it anywhere.

compact, tightly packed in a small size.
merchandise, goods for sale.(商品)
receptionist, someone who works at the front desk, e.g. secretary.
dentist, a person who looks after your teeth for a living.
identification, a document that shows who a person is, e.g. passport, driver's licence.
coupon, a piece of paper that you can use to buy goods or to get them at a reduced price.
depart, to leave.
reschedule, to set a new time for something.
tactic, like a plan or scheme.(策略)
renovation, the process of being restored to a previous or better condition.(翻修，革新)
upgrade, to improve what was old or outdated.
precede, to happen before something else.
replacement, to put something/someone in place of something/someone else.
dine, have supper, eat dinner.
passport, official document containing information about you that allows you to enter other countries.
coworker, a person that works with you in the same workplace.
upcoming, happening soon.
cabinet, a piece of furniture with shelves to store things.
appliance, a machine or device that does a particular task.(电器,装置)
explanatory, to explain or make clear.
instructor, someone who teaches for a living.(教练、大学讲师)
keyboard, the part of computer that you type on.
media, related to different forms of communication, e.g. TV, radio, newspapers etc.
supermarket, a large self-service store selling food and household items.
valid, just, fair, right.
admission, entrance into something.(hospital admission住院)
laptop, a computer small enough to carry and to use in your lap.
underline, to call attention to.
electrical, to do with electricity.
airplane, a powered vehicle that flys through the air to its destination.
assignment, a project or task.
exit, to leave.
attendee, someone present(at a meeting or event)
cruise, a long, relaxing holiday on a ship.(乘船游览)
birthday, the day in the year on which a person was born.
cafe, a restaurant where simple and usually quite cheap meals are served.
comprehension, the act of understanding.
mall, very large building containing lost of stores and restaurants.
medication, a substance(物品) used to make an illness or condition get better.(药物)
recycle, to find another use for something that is going to be put in the trash.
renew, to make something new again.
tenant, someone who pays rent for the use of property like land or rooms.(租客)
sandwich, two pieces of bread with a filling inside, e.g. meat or jam.
departure, the act of leaving.
mini, smaller than is usual for a particular type of thing.
fitness, the state of being healthy.
inconvenience, something that causes trouble or discomfort.
banquet, a formal meal given for a lot of people.(宴会)
closet, a small cupboard.
unreal, not true to life.
distractor, an incorrect option offered in a multiple choice question.(干扰项)
expire, come to an end.
folder, a file or covering to keep papers in.
photocopy, an exact copy of a document made with a photographic machine.(复印件)
renovate, restore to a previous or better condition.
sunny, a day with no clouds or rain just sunshine.
calendar, something you hang on the wall that has the months of the year on it.
donation, the money that is given to a cause(事业) or charity(慈善机构).(捐赠)
feedback, information given to the provider about how good or bad the goods or services were.
shortly, very soon.
snack, small amount of food eaten between meals.
warehouse, a building where a large number of things are stored while they are waiting to be sold.
copier, a machine that makes paper copies.
provider, someone who takes care of others with money, food, home.
beverage, any liquid suitable for drinking.(饮料)
hungry, in need of food, needing to eat.
inspection, a formal or official examination of something.(检查、视察)
recipient, the person who receives something.
aisle, long narrow area for walking between rows of something.
inspect, look over carefully.
mechanic, a person who fixes machinery for living.
merger, when one company buys another company to create one big company.

soccer, ball game played by two teams who try to score goals without handling the ball.
sweater, a warm item of clothing worn over the arms and upper body, made of wool.
ingredient, something listed in a recipe(食谱), e.g. flour(小麦面粉), sugar.(成分，原料)
rewrite, to write again differently.
itinerary, a detail plan of what will happen in a journey.(旅行日程)
workplace, the location where you do your job.
architect, someone who designs buildings.
convenience, the state of being easy.
eligible, able to be chosen.(符合条件的，有资格当选的)
indoor, inside a house or building.
baggage, travel bags.
click, to press a button.
dial, to make a phone call by pressing the buttons.
container, something that holds things.
drawer, a sliding compartment(隔层) you keep things in.
lab, where you do experiments.
submission, the act of formally delivering a document, for a decision to be made about it.(提交)
bulletin, a short news report.
certificate, a piece of paper stating you did something.
gym, building with equipment you can use to exercise your body.
highway, a major road connecting cities.
respondent, someone who relies to something.(回答问题的人，被告)
jewelry, gold, silver, stones etc. you wear for decoration, e.g. necklace.
overtime, work done in addition to regular working hours.
battery, something that produces electric energy.
donate, to give money to a cause or charity.
outstanding, not yet completed.(优秀的，未完成的)
skim, to move quickly above the surface without touching it.
briefcase, a small bag with a handle usually used for carrying business papers.
dessert, sweet food you eat after your main meal.
impact, the effect one thing makes on another.(强大作用，冲击力，撞击)
innovative, to be creative and come up with new ideas.(创新的)
inquire, to ask about(调查)
overnight, from one day to the next.(一夜之间)
venue, the place that an event is happening.(聚集地点)
commuter, someone who travels a long way to work and back.(远距离上下班往返的人)
logo, a small design used by a company as its symbol.
newsletter, report or open letter giving information of interest to a special group.(内部刊物)
advisor, someone who gives an opinion on what to do.
cartridge, a piece of the equipment that is a sealed unit(密封装置), and that can be taken out and replaced.(墨盒、笔芯、弹药筒)
cloudy, weather where the sky is filled with clouds.
photographer, someone who takes pictures for living.
shopper, someone who buys things in a store.
tag, a label.
announcer, someone who gives a message publicly.
aspect, a part of a feature.
audit, to check something is correct, usually related to accounts in business.
constructor, a builder.
download, transfer a file or program onto your computer.
password, a secret word or phrase needed to prove who you are.
prohibit, not allowed.
stadium, sports ground surrounded by rows of seats where people go to watch events.
terminal, the place where the transport line ends, like the final train station on the line.
weekday, all the working days in a week, usually Monday to Friday.
bonus, extra, usually in the form of money.
cart, a wagon(货车车厢，马/牛车) or truck used to for transport.
delicious, to taste good.
ink, liquid found(foundation) in pens.
supervise, to watch over and manage.
waitress, a woman whose job it is to bring meals to your table in a restaurant or cafe.
cleaner, someone who cleans for living.
developer, someone who designs and builds properties.
headquarter, the main office of an organization.
shuttle, travel back and forth between two points.
stationery, any materials needed for writing and printing.(文具)
subscribe, to pay money to receive a service or product regularly.
alike, similar, almost the same.
flavor, the taste of something, e.g. sweet, sour.

picnic, a packed meal to take with you and eaten in the open air.
recipe, directions for baking or cooking something.
refreshment, a small amount of food and drink served as a light meal.
administrative, to do with the management of an office.(管理的，行政的)
authorize, to give permission for something.
commonly, frequently, usually.
distribution, the act of circulating(传递，散布) things in a wide area.
sofa, a long soft seat with a back, big enough for at least two people to sit on.
accommodate, to give something that is needed.
affordable, not expensive, one is able to pay easily.
annoy, to bother or irritate(使烦恼).

* Email

** The differences in connotations of each letter ending
   Ordered in increasing formality.
   1. *Love* Very personal. Used between lovers, family and close friends.
   2. *Cheers* Very casual. Used between friends. Can be used between coworkers if you want to appear very casual, at the risk of sounding unprofessional.
   3. *Take care* Casual and used between friends.
   4. *Thanks* or *Thank you* 'Thanks' is very casual and 'Thank you' is formal. Usually used in business setting. 'Thank you' is a great way to end an email to a stranger, especially if you are making a request or asking a question.
   5. *Yours* or *Yours Truly* or *Truly* Casual or business casual. A more personal, but still polite way to end the letter. You've probably met the recipient in real life.
   6. *Best* or *Best Wishes* Casual or business casual. A polite way to end the letter. Can be used between friends or strangers.
   7. *Sincerely* or *Sincerely Yours* or *Yours Sincerely* Casual, business casual or formal. The standard letter ending. 'Sincerely' is the most versatile ending because it can be used to end either casual or formal correspondence. If you're unsure about how to sign your letter, use 'Sincerely'.
   8. *Regards* or *Best Regards* Business casual or formal. You would use this if the recipient is someone you haven't met in real life.
   9. *Cordially* Formal. Used in business correspondence when the topic of the letter is serious. Sometimes used if there is a conflict between sender and the recipient.


   Using an ending that is too casual for the situation may not always be inappropriate.
   Conversely, using a casual ending can show you self-confidence. But to do this requires you to gauge whether the recipient would like a more casual conversation.
* Cloth
  These socks have worn out. Throw them away.
  No I won't. They are wearable after being darned.
