
Python社区中还没出现如Maven/Gradle那样不仅管理依赖，还能初始化项目目录、测试、生成文档等。

* 虚拟环境

** 限制pip必须在一个激活的虚拟环境中执行安装
#+BEGIN_EXAMPLE shell
# 在~/.bashrc中加入
export PIP_REQUIRE_VIRTUALENV=true

# 要在虚拟环境外执行安装则需要使用gpip install
gpip() {
    PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
#+END_EXAMPLE

** pipenv
   pipenv由Kenneth Reitz开发是基于pip和virtualenv的更高级的集成虚拟环境的依赖管理器，在安装第三方依赖时自动生成Pipfile用于记录Python版本、开发依赖(dev-packages)、运行依赖(packages)和项目的基本信息，并且通过 ~pipenv run python <project.py>~ 启用一个虚拟环境运行项目。

   缺点：无法通过pip安装的第三方依赖，就比较难安装到虚拟环境了。
   Pipfile.lock的内容为通过hash算法将包名称和版本，以及依赖关系生成哈希值，保证包的完整性．

*** 安装
#+BEGIN_EXAMPLE shell
# 将pipenv安装到~/.local下
pip install pipenv --user --upgrade
# 将~/.local/bin加入到环境变量PATH中，后续在shell中可使用pipenv命令
export PATH=$HOME/.local/bin:$PATH
#+END_EXAMPLE

*** 使用
#+BEGIN_EXAMPLE shell
# 创建并进入项目
mkdir foo_project && cd foo_project

# 创建虚拟环境
pipenv --python 2.7

# 创建Python2的虚拟环境
pipenv --two

# 创建Python3的虚拟环境
pipenv --three

# 安装运行时依赖
pipenv install jenkins-job-builder
# 安装开发阶段的依赖
pipenv install jenkins-job-builder --dev

# 卸载第三方依赖
pipenv uninstall jenkins-job-builder

# 卸载所有依赖
pipenv uninstall --all

# 安装当前目录下Pipfile内的生产依赖，并更新Pipfile.lock
# 若没有上述文件则根据当前目录下的requirements.txt生成Pipfile和Pipfile.lock在安装
pipenv install

# 安装Pipefile.lock中所有的包
pipenv sync

# 安装requirements.txt内的依赖
pipenv install -r requirements.txt

# 根据Pipfile.lock的内容安装依赖
pipenv install --ignore-pipfile

# 根据当前虚拟机环境中已安装的依赖名称和版本作为内容生成Pipfile.lock
pipenv lock

# 安装开发依赖
pipenv install --dev jenkins-job-builder

# 安装当前目录下Pipfile、Pipfile.lock内的开发依赖
pipenv install --dev

# 更新依赖版本，Pipfile不发生变化，但Pipfile.lock会发生变化
pipenv update jenkins-job-builder

# 在不激活虚拟环境下，临时在虚拟环境运行应用
pipenv run python foo.py

# 激活虚拟环境
pipenv shell

# 激活虚拟环境后在虚拟环境运行应用
python foo.py
# 退出虚拟环境
exit

# 查看依赖图
pipenv graph

# 生成包含dev-packages和pacakges的requirements.txt
pipenv lock -r --dev > requirements.txt
# 生成包含pacakges的requirements.txt
pipenv lock -r > requirements.txt

# 删除虚拟环境
pipenv --rm

# 列出本地工程路径
pipenv --where

# 列出虚拟环境路径
pipenv --venv

# 列出虚拟环境的Python可执行文件
pipenv --py
#+END_EXAMPLE

*** 注意
    1) 由于pipenv不会读取pip.conf，因此修改源时需要修改Pipfile的source即可．国内源
       - 阿里云：http://mirrors.aliyun.com/pypi/simple/
       - 豆瓣：http://pypi.douban.com/simple/
       - 清华大学：https://pypi.tuna.tsinghua.edu.cn/simple/
       - 中国科学技术大学：https://pypi.mirrors.ustc.edu.cn/simple/
    2) 当安装包时发现lock步骤缓慢，可以通过 ~pipenv install <package> --skip-lock~ 跳过lock步骤。若还是慢则需要采用上述方式更换源了。
    3) 若要生成运行时依赖的requirements.txt，那么必须生成 ~.lock~ 文件。生成requirements.txt的命令为 ~pipenv lock -r > requirments.txt~
    4) 若移动了项目的目录路径，那么原来的virtualenvs和项目路径的映射将会失效。通过在 =~/.bashrc= 中设置如下配置，将映射关系保存到项目目录下
       #+BEGIN_EXAMPLE bash
       #!/bin/bash
       export PIPENV_VENV_IN_PROJECT=1
       #+END_EXAMPLE
    5) 若项目中依赖自定义环境变量，可配置到项目根目录下的 ~.env~ 文件，pipenv运行时会自动加载

*** Pipfile和Pipfile.lock的区别
    Pipfile和Pipfile.lock对标Ruby中的Gemfile和Gemfile.lock。
    Pipfile包含
    1) 依赖源
    2) 生产和开发依赖包名称
    3) 虚拟环境Python版本信息

    Pipfile.lock除了包含Pipfile中包含的信息外，还包含
    1) 当前使用的生产和开发依赖包的具体版本号
    2) 依赖包自身依赖的所有依赖包以及它们的版本号

    只需要将Pipfile纳入版本控制即可。

** poetry
pipenv的替代品

** conda
   Windows下使用

* 其他
tox或nox会自动运行测试和linter，并构建文档。它们支持”依赖矩阵“。

* 版本管理
采用SemVer或CalVer。
可通过工具帮忙管理：incremental,bumpversion和setuptools_scm等。

* style和linting
1) 代码规范检查工具 —— pycodestyle
   #+begin_example bash
   # 安装
   pip install pycodestyle

   # 对一个或多个文件打印检查报告
   pycodestyle --first <file.py>
   pep8 --first <file.py>

   # 显示不符合规范的源码
   pycodestyle --show-source --show-pep8 <file.py>
   #+end_example
2) 代码风格格式化 —— autopep8
   #+begin_example bash
   # 安装
   pip install autopep8

   # 使用
   autopep8 --in-place <file.py>
   autopep8 --in-place <file.py> --aggressive <file.py>
   #+end_example

* code coverage
coverage.py

* 安全漏洞检测
bandit

* 第三方依赖漏洞检测
safety

* 自动化测试
Robot Framework
Java Cucumber 在Python中有对应的Lettuce
Locust负载测试工具
Selenium Web自动化测试

docker-py提供docker支持

* Emacs

** 配置文件
   默认加载 =~/.emacs.d/init.el= ，但可通过 ~emacs -q --load /path/to/init.el~ 来指定加载配置文件。

** 在指定目录下搜索匹配文件的内容
   ~M-x rgrep~

** Elpy
   1) Automatic Indentation
      - isort，格式化 ~import~ 和 ~from...import~ 等导入语句
        - 安装和使用
          #+begin_src bash
          pip install --user isort
          isort -ls old.py
          #+end_src
        - Emacs配置
          #+begin_src elisp
          (defvar myPackages
	        '(elpy
	          py-isort))
	      (require 'py-isort)
	      (add-hook 'before-save-hook 'py-isort-before-save)
          #+end_src
      - yapf，google代码格式化
        - 安装和使用
          #+begin_src bash
          pip install --user yapf
          yapf old.py > new.py
          yapf -i old.py # 直接修改源文件
          #+end_src
   2) Syntax Highlighting
   3) Auto-Completing
      - Jedi，负责让Emacs和后端Python服务通信，获取提示框的内容
      	#+begin_src bash
	pip install --user jedi
	#+end_src
      - Rope，负责tab键代码补全
      	#+begin_src bash
	# Python2.x
	pip install --user rope
	# Python3
	pip install --user rope_py3k
	#+end_src
   4) Syntax Checking
      - flymake，Elpy默认的语法检查工具
      - flycheck，提供实时语法检查但对于有问题的语句不会通过下划线提示
      	#+begin_src elisp
     	(defvar myPackages
	      '(elpy
     	    flycheck))
     	(when (require 'flycheck nil t)
	      (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
     	  (add-hook 'elpy-mode-hook flycheck-mode))
    	#+end_src
      	#+begin_src bash
        pip install pylint # pycompile flake8 mypy
    	#+end_src
        - 功能
          1) ~C-c ! v~ 或 ~M-x flycheck-verify-setup~ 显示flycheck与后端语法检查工具的绑定情况
          2) ~C-c ! l~ 显示详细的语法问题缓冲区
          3) ~C-c ! n~ 光标跳转到下一个语法异常位置
          4) ~C-c ! p~ 光标跳转到上一个语法异常位置
   5) Python REPL Integration
      - ipython集成
      	#+begin_src elisp
	(setq python-shell-interpreter "ipython"
	      python-shell-interpreter-args "-i --simple-prompt")
	#+end_src
   6) Style
      - pep8，Python标准代码风格
      	#+begin_src bash
	pip install --user autopep8
	#+end_src
      	#+begin_src elisp
	(defvar myPackages
	  '(elpy
	    py-autopep8))
	; enable autopep8 formatting on save
	;; ignoring:
	;; - E501 - Try to make lines fit within --max-line-length characters.
	;; - W293 - Remove trailing whitespace on blank line.
	;; - W391 - Remove trailing blank lines.
	;; - W690 - Fix various deprecated code (via lib2to3).
	(require 'py-autopep8)
	(setq py-autopep8-options '("--ignore=E501,W293,W391,W690"))
	(add-hook 'python-mode-hook 'py-autopep8-enable-on-save)
	#+end_src
   7) Virtual Environment Support, and
   8) Much more!
