官方教程：https://docs.sqlalchemy.org/en/13/core/tutorial.html
中文教程：https://www.osgeo.cn/sqlalchemy/

* 安装
#+BEGIN_EXAMPLE bash
pip install sqlalchemy
#+END_EXAMPLE

* 数据库链接字符串
格式: ~数据库类型+数据库驱动名称://用户名:口令@机器地址:端口号/数据库名~

1) SQLite, ~sqlite:///<filepath>~
   1) 绝对路径, ~sqlite:////test.db~
   2) 相对路径, ~sqlite:///test.db~
2) MySQL, ~mysql+mysqlconnector://root:123@localhost:3306/test~

* 组成
从上自下分为两大模块（最底层为DBAPI）
1) SQLAlchemy ORM
   - Object Relational Mapper(ORM)
2) SQLAlchemy ORM
   1) Schema/Types
   2) SQL Expression Language
      1) SQL Expression， 通过SQLAlchemy的DSL书写SQL表达式（为ORM的基础）
      2) Raw SQL，直接书写SQL
      3) ORM，避免书写SQL
   3) Engine
      1) Connection Pooling
      2) Dialect
3) DBAPI


内置DataSource 和 日志功能

* 操作

** 版本检查
#+begin_example python
import sqlalchemy

sqlalchemy.__version__
#+end_example

** 连接数据库
#+BEGIN_EXAMPLE python
from sqlalchemy import create_engine
# Args:
#   encoding(str): 编码方式。
#   echo(bool): 设置是否在控制台输出SQL等日志信息，默认值为False。
#
# Returns:
#   sqlalchemy.engine.base.Engine: 数据引擎实例，只有调用数据库操作时才会去连接数据库
engine = create_engine('mysql://root:@localhost:3306/webpy?charset=utf8', encoding='utf-8', echo=True)
# connectionless execution
# 适合不需要事务的操作
# Args:
#   sql(str): SQL语句
engine.execute('select 1 from dual').scalar()
# connection execution
# 适合需要事务控制的操作
conn = engine.connect()
conn.execute('select * from dual')
#+END_EXAMPLE

** 定义映射(表必须定义主键)
1) 分步定义Table类、实体类 和 类表映射关系
   #+BEGIN_EXAMPLE python
   from sqlalchemy import (
        create_engine,
        MetaData,
        Table,
        Column,
        Integer,
        String,
        Float,
        Text,
        Sequence,
        Date,
        DateTime,
        Boolean,
        Binary,
        ForeignKey,
    )
    from sqlalchemy.orm import mapper

    # 数据库引擎
    engine = create_engine('sqlite:///test.db')
    # 表和实体映射关系元数据
    metadata = MetaData()

    # 定义表
    userTable = Table('user', metadata,
                 Column('id', Integer, primary_key=True),
                 Column('name', String(20), unique=True, nuallale=False),
           )
    addrTable = Table('addr', metadata,
                 Column('id', Integer, primary_key=True),
                 Column('user_id', None, ForeignKey('user.id')),
                 Column('email', String(60), nullable=False),
           )

    # 若表不存在则创建
    metadata.create_all(engine)

    # 定义实体类
    class User(object):
        pass
    class Addr(object):
        pass

    # 创建表和实体类间的映射
    userMapper = mapper(User, userTable)
    addrMapper = mapper(Addr, addrTable)
    #+END_EXAMPLE
2) 通过 ~declarative_base~ 统一定义
   ~declarative_base~ 类用于维护类和表的映射关系， 应用中一个数据库使用唯一一个Base作为该数据库下所有映射的父类。
   #+BEGIN_EXAMPLE python
   from sqlalchemy import (
       create_engine,
       MetaData,
       Table,
       Column,
       Integer,
       String,
       ForeignKey,
       DateTime,
   )
   from sqlalchemy.ext.declarative import declarative_base


   Base = declarative_base()
   # 统一定义, 并且不能定义构造函数
   class User(Base):
       __tablename__ = 'user'
       id = Column('id', Integer, primary_key=True)
       name = Column('name', String(20), unique=True, nuallale=False)
       created_date = Column(DateTime, default=datetime.datetime.utcnow)

       def __repr__(self):
           return '<{}({},{})>'.format(self.__class__.__name__, self.id, self.name)

   class Addr(Base):
       __tablename__ = 'addr'
       id = Column('id', Integer, primary_key=True)
       user_id = Column('user_id', None, ForeignKey('user.id'))
       email = Column('email', String(60), nullable=False)

       def __repr__(self):
           return '<{}({},{},{})>'.format(self.__class__.__name__, self.id, self.user_id, self.email)

   # 数据库引擎
   engine = create_engine('sqlite:///test.db')

   # 以Base子类为依据自动生成Table并调用mapper()，后续可通过User.table获取表定义，通过User.__mapper__获取映射关系对象。
   # 必须加载所有domain后执行才会自动在数据库建立表格
   Base.metadata.create_all(engine)
   #+END_EXAMPLE

*** 清理表结构
#+BEGIN_EXAMPLE
Base.metadata.drop_all()
#+END_EXAMPLE

*** 字段类型
    1) 通用类型位于 ~sqlalchemy~ 下
    2) 特定数据库(如MySQL)的类型位于 ~sqlalchemy.dialects~ 下

** 自增主键
1) 数据库不提供自增字段的(如Oracle)
   #+BEGIN_EXAMPLE python
   from sqlalchemy import Sequence
   Column('id', Integer, Sequence('user_idseq'), primary_key=True )
   #+END_EXAMPLE

** 通过Session跟踪管理Domain
   Session内部维护着一个Identity Map，其键值为Domain实例的Primary Key，而值则为该Domain实例。
   而Domain实例处于4种状态：
   1) Transient(瞬时的)，实例还不在Session管理中，也没有在数据库中对应的记录。如刚通过User()创建的实例，仅仅只有mapper()与之关联。
   2) Pending(挂起的)，调用session.add()后添加到Session的跟踪管理下，但仍然没有在数据库中存在与之对应的记录，需要等待flush动态才能存储到数据库中。
   3) Persistent(持久的)，实例处于Session跟踪管理下，并且在数据库中有与之对应的记录。
   4) Detached(游离的)，实例不在Session管理中，但在数据库中有对应的记录，对实例的任何操作都不会触发任何SQL语句。

*** 创建Session
    #+BEGIN_EXAMPLE python
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker

    engine = create_engine('sqlite:///test.db')

    DBSession = sessionmaker(bind=engine)
    # 后期也可以设置数据库引擎，DBSession.configure(bind=engine)
    session = DBSession()


    session.rollback()
    session.commit()
    #+END_EXAMPLE

*** 查询
    1) Query实例
       #+BEGIN_EXAMPLE python
       # 定义返回的结果组件类型为User
       q1: Query = session.query(User)
       # 定义返回的结果组件类型为tuple(User.name, User.age)
       q2: Query = session.query(User.name, User.age)
       # 定义返回的结果组件类型为tuple(user: User, User.name)
       q3: Query = session.query(User, User.name)

       for name, age in q2.all():
           print('name: {}, age: {}'.format(name, age))
       #+END_EXAMPLE
    2) Query实例方法
       1) ~filter_by~ 参数为关键字参数
          #+BEGIN_EXAMPLE python
          records = q2.filter_by(name='john').all()
          #+END_EXAMPLE
       2) ~filter~ 参数为SQL表达式结构
          #+BEGIN_EXAMPLE python
          records = q2.filter(User.name == 'john').all()
          records = q2.filter(User.name != 'john').all()
          records = q2.filter(User.name.like('j%')).all()
          # IN
          records = q2.filter(User.name.in_(['a', 'b'])).all()
          # NOT IN
          records = q2.filter(~User.name.in_(['a', 'b'])).all()
          records = q2.filter(User.name == None).all()
          records = q2.filter(User.name != None).all()
          # 3种AND的方式
          records = q2.filter(User.name != None, User.age == 12).all()
          records = q2.filter(User.name != None).filter_by(age == 12).all()
          from sqlalchemy import and_
          records = q2.filter(and_(User.name != None, age == 12)).all()
          # OR
          from sqlalchemy import or_
          records = q2.filter(or_(User.name != None, User.age == 12)).all()
          # 入参raw sql
          from sqlalchemy import text
          records = q2.filter(text('id<24')).order_by(text('id')).all()
          #+END_EXAMPLE
       3) 触发返回结果
          1) ~all()~ 返回所有
             对结果可以执行切片操作。
          2) ~first()~ 返回第一个元素
          3) ~one()~ 有且仅有一个元素时才返回，但没有记录或多于一个记录时会抛出异常
          4) ~one_or_none()~ 有且仅有一个元素时才返回，没有记录则返回None。多于一个记录时会抛出异常
          5) ~count()~ 返回记录数目
       4) 分组
          #+BEGIN_EXAMPLE python
          from sqlalchemy import func

          q4 = session.query(func.count(), User.name).group_by(User.name)
          #+END_EXAMPLE
       5) 排序
          #+BEGIN_EXAMPLE python
          q4 = q2.order_by(text('id'))
          #+END_EXAMPLE

*** 插入
    #+BEGIN_EXAMPLE python
    user = User(name='john')
    session.add(user)
    # session.add_all(users: Iterable)
    session.commit()
    #+END_EXAMPLE

*** 删除
1) 先获取Domain再操作
   #+BEGIN_EXAMPLE python
   user = session.query(User).get(0)
   session.delete(user)
   session.commit()
   #+END_EXAMPLE
2) 直接操作
   #+begin_example python
   (session
    .query(User)
    .limit(1)
    .delete())
   #+end_example

*** 更新
1) 先获取Domain后更新
   #+BEGIN_EXAMPLE python
   user = session.query(User).get(0)
   user.name = 'johnjohn'
   session.commit()
   #+END_EXAMPLE
2) 直接更新
   #+begin_example python
   (session
    .query(User)
    .limit(1)
    .update({"name": "johnjohn"}))
   #+end_example

*** 触发flush的时机
    1) ~session.commit()~
    2) ~session.flush()~
    3) ~session.query()~ 等查询语句
*** 分页查询

* 关联关系
** ~sqlalchemy.orm.relationship~ 参数说明
   1) ~backref~ 参数则为关系提供反向引用的声明，即在关系的另一端的类中定义一个指向当前类对象的属性。
      1) 仅仅使用 ~relationship~
         #+BEGIN_EXAMPLE python
         class User(Base):
             __tablename__ = 'user'
             id = Column('id', Integer, primary_key=True)
             addr = relationship('Addr')

         class Addr(Base):
             __tablename__ = 'addr'
             id = Column('id', Integer, primary_key=True)
             user_id = Column(Integer, ForeignKey('user.id'))

         user = session.query(User).get(0)
         user.addr # 可访问

         addr = session.query(Addr).get(0)
         addr.user # 访问失败
         #+END_EXAMPLE
      2) 使用 ~relationship~ 和 ~backref~
         #+BEGIN_EXAMPLE python
         class User(Base):
             __tablename__ = 'user'
             id = Column('id', Integer, primary_key=True)
             addr = relationship('Addr', backref='user')

         class Addr(Base):
             __tablename__ = 'addr'
             id = Column('id', Integer, primary_key=True)
             user_id = Column(Integer, ForeignKey('user.id'))

         user = session.query(User).get(0)
         user.addr # 可访问

         addr = session.query(Addr).get(0)
         addr.user # 可访问
         #+END_EXAMPLE
   2) ~lazy~ 参数表示仅访问关联对象时才连接数据库查询，默认值为True
   3) ~remote_side~ 表示外键指向自身
      1) 普通定义
         #+BEGIN_EXAMPLE python
         class Node(Base):
             __tablename__ = 'nodes'
             id = Column(Integer, primary_key=True)
             parent_id = Column(Integer, ForeignKey('nodes.id'))
             parent = relationship('Node', remote_side=[id])
         #+END_EXAMPLE
      2) 建立双向关联
         #+BEGIN_EXAMPLE python
         class Node(Base):
             __tablename__ = 'nodes'
             id = Column(Integer, primary_key=True)
             parent_id = Column(Integer, ForeignKey('nodes.id'))
             children = relationship('Node', backref=backref('parent', remote_side=[id]))
         #+END_EXAMPLE

   4) ~primaryjoin~
      默认情况下连接条件为主键和外键，但可通过 ~primaryjoin~ 来指定连接条件
      #+BEGIN_EXAMPLE python
      parent = relationship('Parent', primaryjoin=lambda: and_(User.id==Addr.user_id, User.name.like('john%')))
      #+END_EXAMPLE
   5) ~secondaryjoin~
   6) ~order_by~
      #+BEGIN_EXAMPLE python
      relationship('Addr', order_by=lambda : desc(Addr.email))
      relationship('Addr', order_by='desc(Addr.email)')
      #+END_EXAMPLE

** 一对多(one to many)
   就是relationship定义在一的一方。
   #+BEGIN_EXAMPLE python
   class Parent(Base):
     __tablename__ = 'parent'
     id = Column(Integer,primary_key = True)
     children = relationship("Child",backref='parent') # 在Child中添加属性parent用于指向其关联Parent实例

   class Child(Base):
     __tablename__ = 'child'
     id = Column(Integer,primary_key = True)
     parent_id = Column(Integer,ForeignKey('parent.id'))
   #+END_EXAMPLE

** 多对一(many to one)
   就是ForeignKey和relationship都定义在多的一方。
   #+BEGIN_EXAMPLE python
   class Parent(Base):
     __tablename__ = 'parent'
     id = Column(Integer, primary_key=True)

   class Child(Base):
     __tablename__ = 'child'
     id = Column(Integer, primary_key=True)
     parent_id = Column(Integer, ForeignKey('parent.id'))
     parent = relationship("Parent", backref="children", cascade='all') # 在Parent中添加属性children用于指向其关联Child实例集合
     # cascade='all' 用于设置级联删除，否则删除Parent时仅将其Child的parent.id置空
   #+END_EXAMPLE

** 一对一(one to one)
   1) 从一对多语法改为一对一
      #+BEGIN_EXAMPLE python
      class Parent(Base):
        __tablename__ = 'parent'
        id = Column(Integer,primary_key = True)
        child = relationship("Child",backref='parent', uselist=False) # 在Child中添加属性parent用于指向其关联Parent实例

      class Child(Base):
        __tablename__ = 'child'
        id = Column(Integer,primary_key = True)
        parent_id = Column(Integer,ForeignKey('parent.id'))
      #+END_EXAMPLE

   2) 从多对一语法改写为一对一
      #+BEGIN_EXAMPLE python
      class Parent(Base):
        __tablename__ = 'parent'
        id = Column(Integer, primary_key=True)

      class Child(Base):
        __tablename__ = 'child'
        id = Column(Integer, primary_key=True)
        parent_id = Column(Integer, ForeignKey('parent.id'))
        parent = relationship("Parent", backref=backref("child", uselist=False), cascade='all') # 在Parent中添加属性child用于指向其关联Child实例
        # cascade='all' 用于设置级联删除，否则删除Parent时仅将其Child的parent.id置空
      #+END_EXAMPLE

** 多对多(many to many)
   需要一张中间表，然后通过 ~secondary~ 来指定。
   #+BEGIN_EXAMPLE python
   post_keywords = Table('post_keywords', Base.metadata,
                         Column('post_id', Integer, ForeignKey('posts.id')),
                         Column('keyword_id', Integer, ForeignKey('keywords.id')),
                   )

   class Post(Base):
       __tablename__ = 'posts'
       id = Column(Integer, primary_key=True)
       keywords = relationship('Keyword', secondary=post_keywords, backref='posts')

   class Keyword(Base):
       __tablename__ = 'keywords'
       id = Column(Integer, primary_key=True)
   #+END_EXAMPLE

** 关联查询
   1) 手工指定关联
      #+BEGIN_EXAMPLE python
      user, addr = session.query(User, Addr).filter(User.id==Addr.user_id).first()
      #+END_EXAMPLE

   2) 通过定义外键自动关联
      #+BEGIN_EXAMPLE python
      user = session.query(User).join(Addr).filter(Addr.email.like('%test')).first()
      #+END_EXAMPLE

* Oracle
cx_Oracle为Python的Oracle连接驱动模块，需要另行下载安装。而cx_Oracle又依赖instant client。
官网: https://oracle.github.io/python-cx_Oracle/
Doc: https://cx-oracle.readthedocs.io/en/latest/

环境参数: Python3, amd64

** Linux下安装cx_Oracle

*** 安装instantclient-basic和instantclient-sdk
在 http://www.oracle.com/technetwork/database/database-technologies/instant-client/downloads/index.html 下载和目标oracle对应的版本(~select * from v$version;~)
1) 解压
#+begin_src shell
unzip xxx.zip -d /opt/
#+end_src

2) 设置环境变量
#+begin_src .bashrc
export ORACLE_HOME=/opt/instantclient_major_minor/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME
export C_INCLUDE_PATH=$ORACLE_HOME/sdk/include/
#+end_src

3) 建立软链接
#+begin_src shell
cd $ORACLE_HOME
ln -s libclnth.so.major.minor libclnth.so
#+end_src

4) 安装python3-dev
#+begin_src shell
sudo apt install python3-dev
#+end_src
否则会报python.h缺失的异常。

5) 安装cx_Oracle
cx_Oracle必须和操作系统和instantclient版本一致，如32位、Python3.x。
#+begin_src shell
sudo pip install cx_Oracle
#+end_src

疑问：https://oracle.github.io/odpi/doc/installation.html#linux

** Windows下安装cx_Oracle
1) 安装instant client，并设置环境变量
#+begin_src
setx TNS_ADMIN "d:\instanceclient_12_2"
setx NLS_LANG "SIMPLIFIED CHINESE_CHINA.ZHS16GBK"
#+end_src

2) 将instant client下的oraocci12.dll、oraociei12.dll、oci.dll复制到%PYTHON_HOME%\Lib\site-packages下

3) 验证 ~python -c "import cx_Oracle"~
若报异常：64-bit Oracle Client library cannot be loaded: "The specified module could not be found"
则需要安装正确的VC++库（Oracle版本对应的VC++库，不是越新越好，向下不兼容的）
| Oracle版本     | VC++库版本               |
|----------------+--------------------------|
| Oracle18和12.2 | VS 2013                  |
| Oracle12.1     | VS 2010                  |
| Oracle11.2     | VS 2005 (32bit 或 64bit) |
VC++库: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#bookmark-vs2013


在TNS_ADMIN下添加tnsnames.ora即可设置TNS。


1.6. 验证
进入python3 REPL，输入import cx_Oracle看是否引入成功

#+begin_src python
import cx_Oracle

conn_str = "帐号/密码@数据库服务器ip:端口/服务"
conn = cx_Oracle.connect(conn_str, encoding='UTF-8',
                         nencoding='UTF-8')  # 这样就可以解决中文乱码的问题
cursor = conn.cursor()
cursor.execute("select * from dual")
row = cursor.fetchone()
print(row)

cursor.close()
conn.close()
#+end_src

分页
#+begin_src python
type page_start_from_1 = int
type pagesize = int
type is_raise_error_when_nodata = bool
paginate: : page_start_from_1 -> pagesize -> is_raise_error_when_nodata -> Pagination

Pagination  # has_next :: bool
Pagination  # has_prev :: bool
Pagination  # next_num :: int
Pagination  # prev_num :: int
#+end_src
* Python DB API 2.0

** API介绍
#+begin_example python
conn = connect() # 返回连接对象

cursor = conn.cursor() # 返回数据库游标
cursor.callproc(proc_name: str [, params]) # 调用存储过程，支持：Oracle
cursor.execute(sql: str [, params]) # 执行SQL语句
cursor.executemany(sql: str, params: Iterable) # 以序列中的参数执行多次SQL语句
cursor.executescript() #执行DDL，支持：SQLite3
cursor.fetchone() # 获取查询结果中的一行记录
cursor.fetchmany(size: int=cursor.arraysize) # 获取查询结果中指定数量的记录
cursor.fetchall() # 获取所有查询结果，会占用大量内存
cursor.nextset() # 迭代获取下一个记录
cursor.arraysize # 用于获取记录总数
cursor.setinputsize # 用于设置调用存储过程时，设置入参的数量
cursor.setoutputsize # 用于设置调用存储过程时，设置出参的数量

conn.commit() # 事务提交
conn.rollback() # 事务回滚
conn.close() # 关闭连接

# 数据库异常
StandardError
  Warning
  Error
    InterfaceError
    DataBaseError

# 参数形式，通过模块级变量paramstyle的值指定
# qmark:(?)
# numeric:(:1)
# named:(:name)
# format:(%s)
# pyformat:(%(name)s), 若为整形数时则使用 %(name)d
#+end_example

** SQLite3实例

*** 特点
1) 开源的嵌入式关系型数据库
2) 不用安装、配置、启动
3) 依赖文件系统
4) 支持事务
5) 客户端和服务端在同一个进程空间运行

*** Python操作
Python标准库中包含SQLite3模块。

**** QA
1) 报 ~ModuleNotFoundError: No module named '_sqlite3'~
   - 原因：编译安装Python时缺少SQLite模块
   - 解决方案：
     1) 安装SQLite3依赖 ~sudo yum -y install sqlite-devel~
     2) 重新编译Python
        #+begin_example bash
        ./configure --prefix=/usr/local/Python3.6/ --enable-optimizations --enable-loadable-sqlite-extensions
        make -j `grep processor /proc/cpuinfo  | wc -l`
        #+end_example
     3) 删除原有的Python
        #+begin_example bash
        rm -rf /usr/local/Python3.6/
        #+end_example
     4) 安装Python
        #+begin_example bash
        make install
        #+end_example

**** 基本操作
#+begin_example python
from sqlite3 import connect, Row

db_name = ":memory:" # 内存数据库。若为文件路径则保存到文件系统上。
conn = connect(db_name)

# 行对象(Row)
# 支持以列名或索引号访问，迭代访问和len()操作
conn.row_factory = Row
with conn.cursor() as cur:
    cur.execute("select * from sys_user")
    row = cur.fetchone()

    print(row["col1"]) # 以列名访问
    print(row[1]) # 以索引号访问，从1开始
    for col in row: # 以迭代方式访问
        print(col)
    print("%d" % len(row)) # len()

    # 批量操作
    # 通过executemany
    data = [(1,2,3,), (2,3,4,)]
    cur.executemany("insert into test(id, age, grade) values(?,?,?)", data)
    # 通过executescript
    cur.executescript("""
    insert into test(id, age, grade) values(1,2,3);
    insert into test(id, age, grade) values(2,3,4);
    """)

    cur.commt()
#+end_example

**** 二进制文件操作
#+begin_example python
from sqlite3 import connect

conn = connect(":memory:")
with cur in conn.cursor():
  # 写入
  with open("test.jpg") as f:
      cur.execute("insert into test(id, data) values(1, ?)", (f.read()))

  cur.commit()

  # 读取
  cur.execute("select data from test where id = 1")
  row = cur.fetchone()
  with open("test2.jpg", "wb+") as f:
      f.write(cur[1])
#+end_example

**** 自定义函数
作用：可在SQL语句中调用Python方法

#+begin_example python
from sqlite3 import connect
import binascii


# 定义Python函数
def encrypt(data: str) -> str:
    crc = str(binascii.crc32(data.encode()))
    while len(crc) < 10:
        crc = "0" + crc

    return data + crc


def check(data: str) -> Optional[str]:
    if len(data) < 11:
        return None

    crc_res = str(binascii.crc32(data[:-10].encode()))
    while len(crc) < 10:
        crc_res = "0" + crc_res

    if crc_res == data[-10:]:
        return crc_res[:-10]

class AbsSum(object):
    def __init__(self,):
        self.s = 0

    def step(self, v):
        self.s += v

    def finalize(self,):
        return self.s


db_name = ":memory:"
conn = connect(db_name)

# 注册基础函数
# Args:
#     :str: 注册到SQL中的函数名
#     :int: 函数参数数量
#     :Function: Python函数
conn.create_function("checkk", 1, check)

# 注册聚合函数
# Args:
#     :str: 注册到SQL中的函数名
#     :int: 函数参数数量
#     :Class: Python类名
conn.create_aggreate("abssum", 1, AbsSum)

with conn.cursor() as cur:
    cur.execute("select abssum(id), checkk(name) from test")
    count = len(cur.fetchall())

    cur.commit()
#+end_example
**** 数据类型转换
None - NULL
int - integer
str - text
bytes - blob
** MariaDB实例
MySQL的开源分支，采用CS模式。

*** 搭建数据库
#+begin_example bash
mysqld --console # 启动数据库
mysqladmin -u root -p password # 添加帐号密码
#+end_example

*** Python操作
连接库：
1) 第三方库(支持Python3.x)
   1) pymysql
   2) MYSQL-Python
2) MySQL官方连接库(MySQL connector Python)
   #+begin_example bash
   pip install mysql-connector-python
   #+end_example

#+begin_example python
# 建立连接对象：mysql.connector.connect
# 数据库异常：mysql.connector.Error
# 切换数据库：conn.database = new_database_name
# 以format或pyformat作为paramstyle，即%s或%(name)s、%(name)d

from mysql.connector import connect

db_name = {
    "host": "localhost",
    "database": "test",
    "user": "john",
    "password": "pass",
}

conn = connect(**db_name)
with conn.cursor() as cur:
    cur.execute("select * from sys_user where id = %s", 1)
    cur.execute("select * from sys_user where id = %(id)s", {"id":1})
#+end_example
** MongoDB实例
GrideFS：在数据库中保存文件。

*** Python操作
驱动库：pymongo

#+begin_example python
from pymongo import MongoClient


# 建立连接对象
db = MongoClient(host: str, port: int)

db_test = db.test # 获取数据库对象
stud = db_test.student # 获取数据库对象下的集合
stud.insert_one({"id":1, "name": "john"}) # 向集合插入文档
stud.find_one() # 返回一条文档，接收一个字典类型的参数，用于作为选择条件

stud.find()
stud.insert_many()
stud.update()
stud.update_many()
stud.replace_one()
stud.delete_one()
stud.find_one_and_delete()
stud.find_one_and_replace()
stud.find_one_and_update()
stud.count()
stud.group()
stud.distinct()
#+end_example

*** mongoengine
Object-Document Mapper，类似于ORM。

#+begin_example python
from mongoengine import *

conn = connect("test")

class User(Document):
    meta = {"allow_inheritance": True} # 允许继承，默认为False

    def clean(self,):
        # 在save前被执行，可以用于设置自动计算的值
        pass

    # 默认建立id字段对应mongodb的_id属性，但可以自定义主键和用id或pk来引用主键
    # u = User.objects[0]
    # u.id == u.uid == u.pk
    uid = SequenceField(primary_key=True)
    name = StringField() # StringField(regex=None, max_length=None, min_length=None)
    age = IntField()     # IntField(min_value=None, max_value=None)
                         # FloatField(min_value=None, max_value=None)
                         # BooleanField()
                         # DateTimeFIeld()
                         # ListField()
                         # DictField()
                         # ReferenceField() 参考类型
                         # SequenceField() 自动产生一个整数序列，自增值
    ff = FileField()     # FileField()

# 上述Field的通用入参
# default: Any 默认值
# required: bool 必填
# primary_key: bool
# null: bool
# choices: List[Any] 值范围
# unique: bool

# CUD
user = User(name="john", age=1)
user.save() # 插入文档
user.update(age=13) # 更新字段，此时数据库的值已经更新，但user对象还没同步过来
user.update(inc_age=1) # （修改器）在原值基础上增加1，此时数据库的值已经更新，但user对象还没同步过来
user.reload() # 从数据库同步数据过来
user.delete() # 删除文档
user.drop_collection() # 删除集合

# R
User.objects # 返回集合中所有文档
User.objects.count()
User.objects.filter()
User.objects.all()
User.objects.first()
User.objects.order_by()
User.objects.limit()
User.objects.skip()

# 保存文件
user.ff.put(open("/path/to/file", "rb", content_type="image/jpeg"))
user.save()

# 读取文件
with open("/path/to/file", "wb+") as f:
    f.write(user.ff.read())

# 删除
user.ff.delete()
#+end_example
