* 8种基本数据类型
  - byte, 1byte signed integer
    - default 0
    - min -128
    - max 127
    - 包装类 Byte
  - short, 2byte signed integer
    - default 0
    - min -32768
    - max 32767
    - 包装类 Short
  - int, 4byte signed integer
    - default 0
    - min -2,147,483,648
    - max 2,147,483,647
    - 包装类 Integer
  - long, 8byte signed integer
    - default 0L
    - min -9,223,372,036,854,775,808
    - max 9,223,372,036,854,775,807
    - 包装类 Long
  - float, 4byte IEEE 754 float
    - default 0.0f
    - 不能用于表示精确的值，如货币
    - 包装类 Float
  - double, 8byte IEEE 754 float
    - default 0.0d
    - 不能用于表示精确的值，如货币
    - 包装类 Double
  - boolean
    - default false
    - 包装类 Boolean
  - char, a 2byte Unicode character
    - default \u0000
    - min \u0000
    - max \uffff
    - 包装类 Character
    - 示例
      #+BEGIN_EXAMPLE java
      char uniChar = '\u039A'; // Unicode 字符表示形式
      char[] charArray = {'a', 'b'};
      #+END_EXAMPLE
  
  8种基本数据类型的包装类的属性
  - SIZE，返回数据类型所占的位数
  - MIN_VALUE，返回最小值
  - MAX_VALUE，返回最大值
  所有基本数据类型的包装类都继承Number
  静态方法
  - valueOf(primitive_value)，将基本数据类型转换为包装类
  实例方法
  - xxxValue()，从包装类实例中提取内部的基本数据类型变量值

  

  隐式类型转换： ~byte,short,char -> int -> long -> float -> double~ 
  显式强制转换需注意内容：
  1) 浮点数转整数会直接舍弃小数，而不是四舍五入
  2) 不能对boolean类型进行类型转换

* 局部变量、实例变量和静态变量
  1) 局部变量
     - 在线程栈上分配存储空间
     - 没有默认值，因此声明后必须经过初始化后才能使用
  2) 实例变量
     - 有默认值
       - 数值型变量为0
       - 布尔型变量为false
       - 引用类型变量为null
     - 变量值的初始化时机
       1) 声明时设置
       2) 构造方法中设置
  3) 静态变量
     - 在静态存储区分配存储空间
     - 有默认值
       - 数值型变量为0
       - 布尔型变量为false
       - 引用类型变量为null
     - 变量值的初始化时机
       1) 声明时设置
       2) 构造方法中设置
       3) 静态语句块中设置

* StringBuffer和StringBuilder
  StringBuffer为线性安全，而StringBuilder在Java5引入且为非线性安全。
  由于StringBuilder为非线程安全，因此性能上优于StringBuffer。

* 数组
  #+BEGIN_EXAMPLE java
  // 2种声明方式
  int[] a; // 首推这种
  int b[];

  // 定义容量为5的int数组
  int[] c = new int[5];
  int[] d = {1,2,3,4,5};
  
  String[] strs = new String[]{"a", "b"};

  // 2×n的二维数组
  int[][] e = new int[2][];
  e[0] = new int[2]; 
  e[1] = new int[3]; 
  e[0][0] = 1;
  e[0][1] = 2;
  e[1][0] = 4;
  e[1][1] = 6;
  e[1][2] = 7;

  int[] nums = new int[]{1,2,3};
  Integer[] iNums = new Integer[]{1,2,3};
  Object[] oINums = (Object[])iNums; // 强制转换成功
  Object[] oNums = (Object[])nums; // 强制转换失败
  #+END_EXAMPLE

** ~java.util.Arrays~ 操作数组的帮助类
   - ~int Arrays.binarySearch(T[] a, T key)~ 对已排序的数组进行二分查找对象，若找到则返回对应的索引，否则返回-1。
   - ~boolean Arrays.equals(T[] a, T[] b)~ 当两个数组中所有相应元素对都是相等，那么认为这两个数组是相等的。
   - ~void Arrays.fill(T[] a, T b)~ 用元素b填满数组a。
   - ~void sort(T[] a)~ 根据自然顺序进行升序排列。

* 日期时间

** ~java.util.Date~
   - 构造方法
     1) ~new Date()~ 使用当前日期时间初始化对象
     2) ~new Date(long millisec)~ 参数作为相对于1970/1/1起的毫秒数来初始化对象
   - 实例方法
     很多方法已经被标识为deprecated，建议使用Calender来操作
     - ~boolean after(Date date)~ 判断Date实例是否在入参之后
     - ~boolean before(Date date)~ 判断Date实例是否在入参之前
     - ~Object clone()~ 复制实例副本
     - ~boolean equals(Date date)~ Date实例和入参相同则返回true
     - ~int hashCode()~ 返回对象的哈希码
     - ~int compareTo(Date date)~ Date实例与入参相同则返回0；Date实例在入参之前则返回负数；Date实例在入参之后则返回正数
     - ~long getTime()~ 返回自1970/1/1 00:00:00 GMT以来的毫秒数
     - ~void setTime(long time)~ 参数作为相对于1970/1/1起的毫秒数来设置日期时间对象值
     - ~String toString()~ 返回格式为 ~dow mon dd hh:mm:ss UTC yyyy~ 格式的日期时间字符串，其中dow为Sun,Mon,Tue,Web,Thu,Fri,Sat

** 日期时间字符串格式化
   1) ~java.text.SimpleDateFormat~
      继承 ~java.text.DateFormat~ ，提供locale-sensitive的日期和格式化字符串之间的相互转换功能。
      - 日期时间转换为格式化字符串
      #+BEGIN_EXAMPLE java
      // 假定当前时区为东8(即GMT+8)
      // 因此所有时间的默认时区均为东8
      Date now = new Date(); // 假设日期时间为 2019-04-21 00:00:00
      SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
      String gmt8 = ft.format(now); // 2019-04-21 00:00:00
      ft.setTimeZone(TimeZone.getInstance("GMT")); // 设置时区为0时区
      String gmt = ft.format(now); // 2019-04-20 16:00:00
      #+END_EXAMPLE
      - 将字符串解析为日期时间
        #+BEGIN_EXAMPLE java
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = ft.parse("2019-02-02 00:02:00");
        #+END_EXAMPLE
   2) ~System.out.printf~
      以 ~%t~ 开头并以下面表格的一个字母结尾即可格式化日期时间
      | 转换符 | 说明                                            | 示例                             |
      |--------+-------------------------------------------------+----------------------------------|
      | c      | 全部日期和时间信息，和new Date().toString()一样 | 星期六 十月 27 14:21:20 CST 2007 |
      | F      | yyyy-MM-dd                                      |                                  |
      | D      | MM/dd/yy                                        |                                  |
      | r      | hh:mm:ss pm(12进制)                             | 02:25:51 下午                    |
      | T      | hh:mm:ss (24进制)                               | 14:25:51                         |
      | R      | hh:mm (24进制)                                  | 14:28                            |
      | B      | 月份全称                                        | January                          |
      | b      | 月份简称                                        | Jan                              |
      | A      | 星期全称                                        |                                  |
      | a      | 星期简称                                        |                                  |
      | C      | 年的前两位                                      |                                  |
      | y      | 年的后两位                                      |                                  |
      | m      | 两位数字的月份                                  |                                  |
      | d      | 两位数字的日期                                  |                                  |
      | e      | 一位数字的月份（前面不补零）                    |                                  |
      - 示例
        #+BEGIN_EXAMPLE java
        Date date = new Date();
        // 普通使用方式
        System.out.printf("%tR%n", date); // 显示14:28换行符
        // 使用索引
        System.out.printf("%1$s %2$tR %2$tT", "hi", date); // 显示hi 14:28 14:28:41没有换行符
        #+END_EXAMPLE
   3) ~String.format~
      采用和 ~System.out.printf~ 一致的格式化编码，但可以设置语言区域
      #+BEGIN_EXAMPLE java
      Date date = new Date();
      String str = String.format(Locale.US, "英语月份简称：%tb", date);
      String str = String.format("本地月份简称：%tb", date);
      #+END_EXAMPLE

** 测量时间间隔(毫秒) —— ~System.currentTimeMillis()~
   #+BEGIN_EXAMPLE
   long start = System.currentTimeMillis();
   // do something
   long end = System.currentTimeMillis();

   System.out.printf("%d", edn - start);
   #+END_EXAMPLE
   
** ~Calendar~ 实例
   可单独提取、增加、减少日期时间年、月、日等组件值。
   #+BEGIN_EXAMPLE java
   Calendar c1 = Calendar.getInstance(); // 返回GregorianCalendar实例，默认为当前时区的时间
   c1.set(2019, 12, 31); // 设置日期为2019/12/31
   c1.set(Calendar.YEAR, 2012);
   c1.set(Calendar.MONTH, 11); // 月份从0开始计算，其它均从1开始计算
   c1.set(Calendar.DATE, 30);
   c1.set(Calendar.DAY_OF_MONTH, 30); // 和 Calendar.DATE 效果一样
   c1.set(Calendar.HOUR, 12); // 12进制
   c1.set(Calendar.HOUR_OF_DAY, 13); // 24进制
   c1.set(Calendar.MINUTE, 45);
   c1.set(Calendar.SECOND, 55);
   c1.set(Calendar.DAY_OF_WEEK, 1); // 星期几，1星期日，2星期一
   // 对应有获取方法
   c1.get(Calendar.YEAR);
   // 在当前基础上增减
   c1.add(Calendar.YEAR, 1);
   c1.add(Calendar.YEAR, -1);
   #+END_EXAMPLE

*** Date和Calendar转换
    #+BEGIN_EXAMPLE java
    // Calendar转Date
    Calendar cale = Calendar.getInstance();
    Date date = cale.getTime();

    // Date转Calendar
    cale.setTime(date);
    #+END_EXAMPLE

* IO

** 字符流
   - Reader
     - BufferedReader
       - 示例：从标准输入读取字符
       #+BEGIN_EXAMPLE java
       BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
       char c = 'q';
       do {
         if (c != 'q'){
           System.out.println(c);
         }
         c = reader.read();
       }(c != 'q');
       #+END_EXAMPLE
     - InputStreamReader
       - FileReader
     - StringReader
     - PipedReader
     - CharArrayReader
     - FilterReader
       - PushbackReader
   - Writer
     - BufferedWriter
     - OutputStreamWriter
       - FileWriter
     - PrinterWriter
     - PipedWriter
     - CharArrayWriter
     - FilterWriter

** 字节流
   - InputStream
     - FileInputStream
     - FilterInputStream
       - BufferedInputStream
       - DataInputStream
       - PushbackInputStream
     - ObjectInputStream
     - PipedInputStream
     - SequenceInputStream
     - StringBufferInputStream
     - ByteArrayInputStream
   - OutputStream
     - FileOutputStream
     - FilterOutputStream
       - BufferedOutputStream
       - DataOutputStream
       - PrintStream
     - ObjectOutputStream
     - PipedOutputStream
     - ByteArrayOutputStream

** BIO(Blocking IO)
   同步阻塞编程方式，JDK1.4引入的特性。

** NIO(Unblocking/New IO)
   同步非阻塞编程方式，基于Reactor。

** AIO(Asynchronous IO)
   异步非阻塞编程方式，JDK1.7引入被称为NIO2.0。位于 ~java.nio.channels~ 下的4个异步通道：
   1) AsynchronousSocketChannel
   2) AsynchronousServerSocketChannel
   3) AsynchronousFileChannel
   4) AsynchronousDatagramChannel

* 修饰符
用于定义类、方法和变量，通常放在语句的最前端

** 访问控制修饰符
1) default 在同一个包内可见。使用对象：类、接口、方法、变量
2) public 公开。使用对象：类、接口、方法、变量
3) protected 对同一包内的类和所有子类可见。使用对象：方法、变量、内部类
4) private 在同一个类内可见。使用对象：方法、变量、内部类

*** 接口的默认访问修饰符
1) 变量默认为 ~public static final~
2) 方法默认为 ~public abstract~

** 非访问控制修饰符
1) final 用来修饰类、方法和变量
   1) 修饰类，类为最终类不能被继承
      1) 其下方法自动添加final修饰符
      2) 其下成员变量不会自动添加final修饰符
   2) 修饰方法，方法不能被子类重写(Override)
   3) 修饰变量，变量值不能被修改
      1) 变量为引用类型，那么变量指向的引用地址不能修改，但引用对应的内部属性可以被修改
         #+BEGIN_EXAMPLE java
         final Map<String, String> map = new HashMap<String, String>();
         map.put("one", "1");
         #+END_EXAMPLE
      2) 搭配static声明类变量作为常量使用
2) abstract 用来修饰抽象类和抽象方法
   1) 抽象类不能同时声明为final
   2) 抽象方法不能同时声明为final或static
   3) 若一个类包含抽象方法，那么该类也必须声明为抽象类
3) static 用来修饰类方法和类变量
4) synchronized 声明方法同一时间只能被一个线程访问
   - 示例 ~public synchronized void showDetails() {}~
5) volatile 修饰成员变量在每次线程访问时均强制从共享内存中重新读取值，并且当发生变化时强制线程将变化值回写到共享内存
6) transient 修饰变量不参与类的序列化

* 枚举
1) 可单独声明或在类和接口中声明
   #+BEGIN_EXAMPLE java
   class FreshJuice {
     enum FreshJuiceSize { SMALL, MEDIUM, LARGE }
     FreshJuiceSize size;
   }
   
   public class FreshJuiceTest {
     public static void main(String []args) {
       FreshJuice juice = new FreshJuice();
       juice.size = FreshJuice.FreshJuiceSize.LARGE;
     }
   }
   #+END_EXAMPLE
2) 枚举中可定义方法、变量和构造函数
   #+BEGIN_EXAMPLE java
   // 枚举类Sex
   public enum Sex {
     MALE(1, "男性"), FEMALE(2, "女性"); // 枚举值MALE和FEMALE

     private int id;
     private String name;
     
     private Sex(int id, String name){
       this.id = id;
       this.name = name;
     }

     public int getId(){
       return this.id;
     }

     public void setId(int id){
       this.id = id;
     }

     public String getName(){
       return this.name;
     }

     public void setName(String name){
       this.name = name;
     }

     public static Sex getSex(int id){
       if (id == 1){
         return MALE;
       }
       else if (id == 2){
         return FEMALE;
       }

       return null;
     }
   }
   #+END_EXAMPLE

* 源文件声明规则
1) 一个源文件中只能有一个public类
2) 一个源文件中可以有多个非public类
3) 源文件名称必须和public类名称保持一致
4) 如果类定义在某个包中，那么源文件首行必须为package语句
5) import语句需放在package语句之后

* Java包
  用于对类和接口进行分类

** import语句
   通过完全限定名（包名+类名）引用指定类，而Java编译器就定位到对应的源文件。
   #+BEGIN_EXAMPLE java
   import java.io.*;
   #+END_EXAMPLE

** import static 静态引用
   从JDK1.5引入的特性，通过静态引入可以在当前类中直接使用被导入类的静态方法和静态成员变量，而不用以被导入类作为前缀来使用。
   #+BEGIN_EXAMPLE java
   import static org.john.Test.StaticMethod; // 引入静态方法StaticMethod
   import staitc org.john.Test.*; // 引入Test类下的所有静态方法和成员变量
   
   public class TestC{
     public void print(){
       StaticMethod(StaticMember);
     }
   }
   #+END_EXAMPLE

* 面对对象编程

** ~super~ 和 ~this~
   ~super~ 用于显式访问父类成员
   ~this~ 用于显式访问当前类的成员

** 构造方法
   子类不会继承父类的构造方法，默认情况下会隐式调用父类的无参构造方法，但可通过 ~super~ 来显式调用父类的其它构造方法。
   #+BEGIN_EXAMPLE java
   class Super1 {
     Super1(){
       System.out.println("Super1 default constructor.");
     }
     Super1(int num){
       System.out.println("Super1 constructor with argument `num`.");
     }
   }
   class Child1 extends Super1{
     Child1(){
       super(10);
       System.out.println("Child1 default constructor.");
     }

     Child1(int num){
       System.out.println("Child1 constructor with argment `num`.");
     }
   }

   Super1 s1 = new Child1();
   Super1 s2 = new Child1(10);
   /* Super1 constructor with argument `num`.
    * Child1 default constructor.
    * Super1 default constructor.
    * Child1 constructor with argment `num`.
    */
   #+END_EXAMPLE

** 接口
   实现接口的抽象类可不实现接口的所有方法，否则则需要实现接口的所有方法。
   1) 接口和抽象类的区别
      1) 接口不能包含静态代码块和静态方法
      2) 一个类可实现多个接口，但只能继承一个抽象类
      3) 接口的方法不能有方法体，而抽象类中的非抽象方法将包含方法体
      4) 接口的成员变量修饰符只能为 ~public static final~ ，抽象类的成员变量修饰符和普通实现类一样
   2) 接口定义
      #+BEGIN_EXAMPLE java
      [public|private] interface <接口名称> [extends <其它接口名称>...]{}
      #+END_EXAMPLE
   3) 接口多继承
      接口支持多继承，即可通过 ~extends~ 继承多个父接口
      #+BEGIN_EXAMPLE java
      interface A{}
      interface B{}
      interface C extends A, B {}
      #+END_EXAMPLE
   4) 标记接口
      不包含任何属性和方法，仅用于表明它的实现类属于一个特定的类型拥有某个或某些权利。

** 重写(Override)和重载(Overload)
   - 重写(Override)
     子类重新实现父类的签名相同的实例方法
     1) 子类方法不能抛出比父类方法范围更大的异常，仅能抛出父类方法声明的异常或其派生类
        #+BEGIN_EXAMPLE java
        class Super1{
          void echo throws IOException () {}
        }
        class Child1 extends Super1{
          // 编译时报错，因为子类方法抛出的异常范围比父类的更大
          void echo throws Exception () {}
        }
        #+END_EXAMPLE
     2) 子类方法的参数列表必须和父类的一致
     3) 子类方法的返回值类型要么和父类的一致，要么为父类方法返回值类型的派生类(Java5前必须和父类的一致)
     4) 子类方法的访问权限不能低于父类的
        1) 父类为public，那么子类必须为public
        2) 父类为default，那么子类可以为default或public
        3) 父类为protected，那么子类可以为protected、default或public
     5) 在子类方法中可通过 ~super~ 调用父类中被重写的方法
     6) 静态方法不存在重写，父类和子类的静态方法各自独立
   - 重载(Overload)
     在同一个类中多个名称相同但方法参数列表不同的实例或静态方法，重载方法的返回值类型可相同也可以不同
     1) 重载方法必须具有不同的参数列表，仅返回值类型不同是无法区分方法的

** 多态
   三个必要条件：
   1) 继承
   2) 重写
   3) 父类引用指向子类对象
      #+BEGIN_EXAMPLE java
      Super1 super1 = new Child1();
      #+END_EXAMPLE

** 注解
   1) ~@Override~ 指示该方法为重写父类的同名方法，那么在编译时会检查被标识的方法签名是否与父类签名一致，若不一致则编译失败。

** 泛型(generics/parameterized type)
   从Java5引入的特性，提供了编译时类型安全检查机制，防止运行时的执行与数据类型不符的非法操作。泛型本质为 *参数化类型* ，即为所操作的数据类型指定一个参数。
   注意点：
   1) 类型参数只能代表 *引用类型* 不能是原始类型

*** 泛型方法
    #+BEGIN_EXAMPLE java
    // 入参类型和返回值类型采用泛型
    public <E> E print(E a){
      System.out.println(a);
      
      return a;
    }

    // 多个泛型
    public <E, T> T forceCast(E a){
      return (T)a;
    }
    
    // 有界泛型，通过extends或implements设置泛型必须为某类或接口的派生类
    public <T extends Comparable<T>> T maximum(T x, T y){
      T max = x;
      if (y.compareTo(max) > 0){
        max = y;
      }

      return max;
    }
    #+END_EXAMPLE

*** 泛型类
    #+BEGIN_EXAMPLE java
    public class Box<T>{
      private T value;
      public T getValue(){
        return this.value;
      }
      public void setValue(T value){
        this.value = value;
      }
    }
    #+END_EXAMPLE

*** 类型限定符
    1) ~extends~ 用于限制为某类或接口的派生类
       对于继承多个类或接口则通过 ~&~ 表示，如 ~<T extends Comparable & Serializable>~
    2) ~super~ 用于限制为某类及父类、基类类型，如Object类型
*** 类型通配符
    1) ~?~ 用于对不关心应类型参数具体值的场景
       #+BEGIN_EXAMPLE java
       void printData(List<?> data){
         System.out.println(data.get(0));
       }
       #+END_EXAMPLE
    2) 带 ~extends~ 的有界泛型通配符，用于对不关心应类型参数具体值但需要限制为某类或接口的派生类
       注意：实现某接口也是用 ~extends~
       #+BEGIN_EXAMPLE java
       void printNumber(List<? extends Number> data){
         System.out.println(data.get(0) + 1);       
       }
       #+END_EXAMPLE
    3) 带 ~super~ 的有界泛型通配符，用于对不关心应类型参数具体值但需要限制为某类及父类、基类类型，如Object类型
       #+BEGIN_EXAMPLE java
       void printNumber(List<? super Number> data){
         System.out.println(data.get(0) + 1);       
       }
       #+END_EXAMPLE
   
*** 底层原理
    类型擦写(type erasure)：编译器在编译时会将所有类型参数信息擦除掉，在运行时不存在任何类型参数相关的信息。如 ~List<String>~ 在运行时只剩下 ~List~ ，这样就能兼容Java5之前版本的二进制类库，因此称Java的泛型为伪泛型。
    由于类型参数信息对JVM来说是不可见的，因此无法避免在运行时出现的类型转换异常的情况，但也不会出现真泛型中的类型膨胀问题。

    问题示例1——运行时Class类实例相相等
    #+BEGIN_EXAMPLE java
    ArrayList<String> list1 = new ArrayList<String>();
    list1.add("abc");
    ArrayList<Integer> list2 = new ArrayList<Integer>();
    list2.add(123);

    // 返回true
    System.out.println(list1.getClass() == list2.getClass());
    #+END_EXAMPLE
    
    问题示例2——运行时反射方法调用
    #+BEGIN_EXAMPLE java
    ArrayList<String> list1 = new ArrayList<String>();
    list1.add("abc");
    // list1.add(123); 编译失败
    Method m = list1.getClass().getMethod("add", Object.class);
    m.invoke(list1, 123); // 运行正常
    #+END_EXAMPLE
    
**** 显式和隐式声明类型变量    
     #+BEGIN_EXAMPLE java
     public class App{
       public static <T> T add(T x, T y){
         return y;
       }

       public static void main(String[] args){
         Integer i = App.add(1, 2); // 隐式声明类型变量为Integer
         Float d = App.add(1, 2.1); // 隐式声明类型变量为Float
         
         Integer i = App.<Integer>add(1, 2); // 显式声明类型变量为Integer
         Float d = App.<Float>add(1, 2.1); // 显式声明类型变量为Float
         
         // Integer i = App.<Integer>add(1, 2.1); // 编译报错
         Number n = App.<Number>add(1, 2.1);
       }
     }
     #+END_EXAMPLE

**** 类型擦写原理
     编译时将所有类型参数(parameterized type)中指定的类型转换为原始类型(raw type)，然后自动在取值位置添加类型转换代码。
     1) 原始类型，即最后在字节码中类型变量真正的数据类型；
     2) 转换原始类型的规则
        1) 没有类型限定符时，统一转换为Object；
        2) 附带 ~extends~ 类型限定符，统一转换为第一个基类或接口；
           #+BEGIN_EXAMPLE java
           public <T extends Comparable & Serializable> T get(){ return null; }
           // 转换为public Comparable get() { return null; }
           #+END_EXAMPLE
           *建议：将标记接口放在限制列表的最后*
        3) 附带 ~super~ 类型限定符，统一转换为Object。
     3) 自动添加类型转换代码
        #+BEGIN_EXAMPLE java
        public <T> T get(T a){ return a; }
        Integer a = <Integer>get(1);
        
        // 编译后的代码逻辑如下
        public Object get(Object a){ return a; }
        Object oA = get(1);
        Integer a = (Integer)oA;
        #+END_EXAMPLE

**** 限制分析
     1) 类型变量不能为8种基础类型和void
        因为类型擦写后的原始类型为Object，基础类型强转Object无效，因此必须使用它们的封装类才行。
     2) 编译期仅根据引用类型变量的类型参数作检查，而不管实际引用的对象的类型参数
        #+BEGIN_EXAMPLE java
        ArrayList list1 = new ArrayList<String>();
        list1.add("abc");
        list1.add(123);

        ArrayList<String> list2 = new ArrayList();
        list2.add("abc");
        list2.add(123); // 编译失败
        #+END_EXAMPLE
     3) 静态方法和属性不能引用类的类型参数
        由于类的类型参数是在类实例化时才能确定，若静态方法和属性引用类的类型参数，则无法确认类型参数的实际类型
        #+BEGIN_EXAMPLE java
        public class Basket<E>{
          public static void add(E e); // 编译失败
        }
        #+END_EXAMPLE
     4) 不支持类型参数的直接实例化，但可以通过反射实现
        #+BEGIN_EXAMPLE java
        public <T extends Comparable> T[] test(T[] a){
          // T m = new T(); 编译失败
          // T[] ms = new T[2]; 编译失败

          T[] ms = (T[])Array.newInstance(a.getClass().getComponentType(), 2);
          return ms;
        }
        #+END_EXAMPLE
     5) 重写含类型参数的方法
        #+BEGIN_EXAMPLE java
        class P<T>{
          private T val;
          public void set(T val){
            this.val = val;
          }
          public T get(){
            return this.val;
          }
        }

        class C extends P<Date>{
          @Override
          public void set(Date val){
            super.set(val);
          }
          @Override
          public Date get(){
            return super.get();
          }
        }

        /**
        * 编译后
        */
        class P{
          private Object val;
          public void set(Object val){
            this.val = val;
          }
          public Object get(){
            return this.val;
          }
        }

        class C extends P{
          public void set(Date val){
            super.set(val);
          }

          public Date get(){
            return super.get();
          }

          // 编译器自动生成桥接方法
          @Override
          public void set(Object val){
            this.set((Date)val);
          }

          // 编译器自动生成桥接方法
          // Object get() 和 Date get()仅返回值不同，而参数列表相同。在编译时被认为是相同的方法，会报重复定义。
          // 但JVM将返回值+参数列表作为方法签名，因此在运行时被认为是不同的方法。
          @Override
          public Object get(){
            return this.get();
          }
        }
        #+END_EXAMPLE
     6) 类型参数不能出现在 ~catch~ 中
        #+BEGIN_EXAMPLE java
        try{}
        catch(T e){}
        #+END_EXAMPLE
     7) 泛型类不能出现在 ~catch~ 中
        #+BEGIN_EXAMPLE java
        try{}
        catch(Problem<T> e){}
        #+END_EXAMPLE
     8) 泛型类不支持 ~instanceof~ ，除非用通配符
        #+BEGIN_EXAMPLE java
        ArrayList<String> sList = new ArrayList<String>();
        // if (sList instanceof ArrayList<String>) 编译失败
        if (sList instanceof ArrayList<?>) {
          // do something
        }
        #+END_EXAMPLE

*** 泛型的型变(type variance)——协变(convariance)和逆变(contravariance)
    型变(type variance)
    #+BEGIN_QUOTE
    Type variance refers to the techniques by which we can allow, or not allow, subtyping in our parameterized types.
    #+END_QUOTE
    假设现在存在 ~List<Orange>~ 和 ~List<Fruit>~ 两个类型，它们可以存在以下任一个关系：
    1) 不型变(invariance): ~List<Orange>~ 和 ~List<Fruit>~ 两者没有任何关系；
    2) 协变(covariance): ~List<Orange>~ 为 ~List<Fruit>~ 的子类型；
    3) 逆变(cotravariance): ~List<Fruit>~ 为 ~List<Orange>~ 的子类型；
    
    *子类(Subclass)* 和 *子类型(Subtype)* 不是一个概念，子类一定是子类型，但子类型不一定是子类。如 ~List<Orange>~ 是 ~List<? extends Fruit>~ 的子类型，但不是子类。

**** Java中的协变
     #+BEGIN_EXAMPLE java
     List<? extends Object> oList;
     List<String> sList = new LinkedList<String>();
     sList.add("hello");
     oList = sList;

     for (int i = 0; i < oList.size(); i++){
       System.out.println(oList.get(i));
     }

     // 编译失败
     // oList.add("123");
     #+END_EXAMPLE
     Java编译器通过限制方法参数列表中包含类型参数的方法调用，保证运行时的类型安全。也就是方法签名如 ~void test(T a)~ ，其中的 ~T~ 会被 ~? extends Object~ 替换掉，即使方法体并没有用到。

     *特点：*
     1) 禁止向泛型类执行写入操作
     2) 允许安全地从泛型类中读取数据
     
**** Java中的逆变
     #+BEGIN_EXAMPLE java
     List<? super Fruit> superFruitList = new LinkedList<Object>();
     superFruitList.add(new Orange());
     superFruitList.add(new Fruit());
     
     Object o = superFruitList.get(0);
     Fruit f = (Fruit)superFruitList.get(1);
     #+END_EXAMPLE

     *特点：*
     1) 允许安全地向泛型类执行写入操作
     2) 无法保证运行时从泛型类中读取数据类型的安全性

**** 为什么需要泛型的型变
     在泛型类型安全的基础上，提高API的灵活性。

*** 类型参数的命名约定
    - ~E~ Element，广泛用于Java Collection中
    - ~K~ Key
    - ~N~ Number
    - ~T~ Type
    - ~V~ Value
    - ~S,U,V~ 第2,3,4个类型参数

*** QA
    1) ~List<String>~ 的变量可以赋值给 ~List<Object>~ 吗？
       不能，Java中这两个类型是完全没有关系的。

** 方法的可变参数
   JDK1.5引入的特性，支持传递同类型的可变参数给方法，并且必须作为最后一个参数。
   #+BEGIN_EXAMPLE java
   public class Test{
     public void printMax(String str, double... numbers){
       // do something
     }

     public void execute(){
       String firstArg = "the first argument";
       double[] vals = {1d,2d,3d};
       this.printMax(firstArg, 1d,2d);
       this.printMax(firstArg, vals);
     }
   }
   #+END_EXAMPLE

*** 方法重载优先匹配固定参数
    若调用的方法能匹配到固定参数重载方法和可变参数重载方法，那么优先匹配固定参数重载方法。
    #+BEGIN_EXAMPLE java
    public class Test{
      public static String concat(String a, String b){
        System.out.println("concat(String a, String b)");
        return a + b;
      }
      public static String concat(String... strs){
        System.out.println("concat(String... strs)");
        StringBuilder sb = new StringBuilder();
        for (String str : strs){
          sb.append(str);
        }
        return sb.toString();
      }

      public static void main(String[] args){
        concat("a", "b"); // concat(String a, String b)
        concat("a", "b", "c"); // concat(String... strs)
      }
    }
    #+END_EXAMPLE

*** 如匹配到多个可变参数重载方法，则会报编译时异常
    #+BEGIN_EXAMPLE java
    public class Test{
      public static void test(String a, Integer... b){
        System.out.println("Integer");
      }
      public static void test(String a, String... b){
        System.out.println("String");
      }

      public static void main(String[] args){
        // test("abc", null); 由于无法判断null的数据类型，因此会抛出编译时异常
        String[] b = null;
        test("abc", b); // String
      }
    }    
    #+END_EXAMPLE

*** 反射
    由于反射是在运行时获取类、方法等的元数据，而可变参数在运行时被编译为数组。因此通过反射调用可变参数方法时，可变参数用数组代替。
    #+BEGIN_EXAMPLE java
    public class Test{
      public static void print(String... strs){
        System.out.println(strs[0]);
      }

      public static void main(String[] args){
        Method method = Test.class.getMethod("print", String[].class);
        method.invoke(null, new String[]{"a", "b"}); // 成功
        method.invoke(null, "a", "b"); // 抛出java.lang.IllegalArgumentException: wrong number of arguments
      }
    }
    #+END_EXAMPLE

** 内部类
   作用：
   1) 当要实现的接口方法与当前类的方法签名冲突时，可通过内部类实现接口方法(内部类可访问外部类所有成员)；
   2) 通过内部类继承其它类型，达到多继承的效果；
    
*** 分类
    1) 成员内部类
       #+BEGIN_EXAMPLE java
       public class Fruit {
         private double price = 100;
        
         private class InnerPrice implements Price{
           public double getPrice(){
             // discount 在Price接口中定义
             return price * discount;
           }
         }

         public class InnerTimeToMarket extends TTM {
           private double price = 200;

           @Override
           public Date getTTM(){
             // 当内部类和外部类存在同名成员变量/方法时，调用外部类成员变量/方法则要采用如下方式
             // 即内部类拥有指向外部类的引用
             System.out.printf("OuterClass price is: %d", Fruit.this.price);
             System.out.printf("InnerClass price is: %d", price);
             return new Date();
           }
         }

         public Price askPrice(){
           return new InnerPrice();
         }
       }
      
       // 调用
       Fruit f = new Fruit();
       // 通过private或protected隐藏内部类，调用则只需调用接口或父类约定的方法即可
       Price p = f.askPrice();
       p.getPrice();

       // 通过public暴露内部类，需要先实例化外部类，再实例化其内部类
       Fruit.InnerTimeToMarket ttm = f.new InnerTimeToMarket();
       #+END_EXAMPLE
       - 注意：
         1) 成员内部类不能拥有静态变量
         2) 成员内部类不能拥有静态方法
         3) 成员内部类不能拥有静态内部类
         4) 成员内部类可定义 ~static final~ 常量
    2) 静态内部类
       #+BEGIN_EXAMPLE java
       public static class Fruit {
         private static double price = 100;
        
         public static class InnerTimeToMarket extends TTM {
           private static double price = 200;

           @Override
           public Date getTTM(){
             // 当内部类和外部类存在同名静态变量/方法时，调用外部类静态变量/方法则要采用如下方式
             System.out.printf("InnerClass price is: %d", Fruit.price);
             System.out.printf("InnerClass price is: %d", price);
             return new Date();
           }
         }
       }

       // 调用
       Fruit.InnerTimeToMarket ttm = new Fruit.InnerTimeToMarket();
       Date time = ttm.getTTM();
       #+END_EXAMPLE
       - 注意：
         1) 静态内部类必须定义在静态类中
         2) 静态内部类中仅能访问外部类的静态变量和静态方法
    3) 局部内部类
       #+BEGIN_EXAMPLE java
       if (true){
         final String name = "john";
         class InnerClass{
           public void print(){
             System.out.println(name);
           }
         }
         InnerClass n = new InnerClass();
       }
       #+END_EXAMPLE
       - 注意
         1) 定义在成员方法的局部内部类，可以访问外部类的所有成员变量和成员方法
         2) 定义在静态方法的局部内部类，可以访问外部类的所有静态变量和静态方法
         3) 局部内部类可以访问方法中的修饰为 ~final~ 的局部变量和方法入参
            - 原理：
              由于局部变量随调用栈帧的释放而被回收，而内部类实例有可能依然可被访问，两者生命周期不一致。而实际上局部变量将作为构造方法入参，参与局部内部类的实例化过程。但存在如下问题，局部变量为基础类型时，Java默认采用传值方式传参。为避免开发人员误会在局部内部类操作的结果会影响到局部变量，因此通过 ~final~ 修饰局部变量，将基本类型的变量标记为常量，引用类型的则直接传递引用本身。
    4) 匿名内部类
       #+BEGIN_EXAMPLE java
       // new interfacename(){} 或 new superclassname(){}
       if (true){
         Fruit f = new Fruit(){
           public double getPrice(){
             return 1d;
           }
         }
       }
       #+END_EXAMPLE

* 异常处理
  1) 异常类型
     - ~java.lang.Throwable~ 所有异常的顶层父类
       - ~java.lang.Error~ 包括虚拟机错误和线程死锁，无法被程序员捕获处理，因此一旦抛出Error异常程序则会挂掉。
       - ~java.lang.Exception~ 可被获取和处理
         - ~java.lang.Runtime~ 运行时异常
         
  2) 异常分类
     1) unchecked exception(非检查性异常)
        Error类型异常、Runtime类型及其派生类异常。这类异常在编译时不被提发现和提示，开发人员应该通过修改代码的方式来杜绝这类异常，而不是依赖异常处理器处理(~try...catch~)处理。
        | 异常                            | 描述                                                                                                                 |
        |---------------------------------+----------------------------------------------------------------------------------------------------------------------|
        | ArithmeticException             | 当出现异常的运算条件时，抛出此异常。例如，一个整数"除以零"时，抛出此类的一个实例。                                   |
        | ArrayIndexOutOfBoundsException  | 用非法索引访问数组时抛出的异常。如果索引为负或大于等于数组大小，则该索引为非法索引。                                 |
        | ArrayStoreException             | 试图将错误类型的对象存储到一个对象数组时抛出的异常。                                                                 |
        | ClassCastException              | 当试图将对象强制转换为不是实例的子类时，抛出该异常。                                                                 |
        | IllegalArgumentException        | 抛出的异常表明向方法传递了一个不合法或不正确的参数。                                                                 |
        | IllegalMonitorStateException    | 抛出的异常表明某一线程已经试图等待对象的监视器，或者试图通知其他正在等待对象的监视器而本身没有指定监视器的线程。     |
        | IllegalStateException           | 在非法或不适当的时间调用方法时产生的信号。换句话说，即 Java 环境或 Java 应用程序没有处于请求操作所要求的适当状态下。 |
        | IllegalThreadStateException     | 线程没有处于请求操作所要求的适当状态时抛出的异常。                                                                   |
        | IndexOutOfBoundsException       | 指示某排序索引（例如对数组、字符串或向量的排序）超出范围时抛出。                                                     |
        | NegativeArraySizeException      | 如果应用程序试图创建大小为负的数组，则抛出该异常。                                                                   |
        | NullPointerException            | 当应用程序试图在需要对象的地方使用 null 时，抛出该异常                                                               |
        | NumberFormatException           | 当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常。                               |
        | SecurityException               | 由安全管理器抛出的异常，指示存在安全侵犯。                                                                           |
        | StringIndexOutOfBoundsException | 此异常由 String 方法抛出，指示索引或者为负，或者超出字符串的大小。                                                   |
        | UnsupportedOperationException   | 当不支持请求的操作时，抛出该异常。                                                                                   |
     2) checked exception(检查性异常)
        编译时会发现、提示并强制开发人员添加异常处理器或throws申明异常，才能通过编译的异常类型。
        | 异常                       | 描述                                                                                                                       |
        |----------------------------+----------------------------------------------------------------------------------------------------------------------------|
        | ClassNotFoundException     | 应用程序试图加载类时，找不到相应的类，抛出该异常。                                                                         |
        | CloneNotSupportedException | 当调用 Object 类中的 clone 方法克隆对象，但该对象的类无法实现 Cloneable 接口时，抛出该异常。                               |
        | IllegalAccessException     | 拒绝访问一个类的时候，抛出该异常。                                                                                         |
        | InstantiationException     | 当试图使用Class类中的newInstance方法创建一个类的实例，而指定的类对象因为是一个接口或是一个抽象类而无法实例化时，抛出该异常 |
        | InterruptedException       | 一个线程被另一个线程中断，抛出该异常。                                                                                     |
        | NoSuchFieldException       | 请求的变量不存在                                                                                                           |
        | NoSuchMethodException      | 请求的方法不存在                                                                                                           |
  3) 异常处理器
     #+BEGIN_EXAMPLE java
     try{
       
     }
     catch(IOException e){
       // catch 语句块所捕获的顺序为自上而下，因此异常类型的顺序为子类到父类
     }
     catch(Exception e){
     }
     finally{
       // 不能在finally 语句块中调用return，否则会覆盖返回值
     }

     return "something";
     #+END_EXAMPLE
  4) 自定义异常
     #+BEGIN_EXAMPLE java 
     public class MyException extends Exception{
       public MyException(String message){
         super(message);
       }
     }
     #+END_EXAMPLE

* TODO 集合类型

** Java2出现的
*** ~java.util.BitSet~ (位集合)
    实现了一组可单独设置和清除的位标识。

*** ~java.util.Vector~   
    动态数组，功能和ArrayList类似，但有如下区别：
    1) Vector是线性安全
    2) Vector包含很多不属于集合框架的方法

*** ~java.util.Stack~
    ~java.util.Stack~ 为 ~java.util.Vector~ 的子类。

*** ~java.util.Properties~
    为 ~java.util.Hashtable~ 的派生类，通过 ~System.getProperties()~ 获取环境变量时的返回值类型就是 ~java.util.Properties~
    | 方法签名                                               | 描述                                     |
    |--------------------------------------------------------+------------------------------------------|
    | Properties()                                           | 无参构造方法                             |
    | Properties(Properties props)                           | 以props作为默认值的构造方法              |
    | String getProperty(String key)                         | 通过键搜索属性值                         |
    | String getProperty(String key, String defaultProperty) | 通过键搜索属性值，若搜索失败则返回默认值 |
    | void list(PrintStream streamOut)                       | 将属性列表输出到输出流中                 |
    | vod list(PrintWriter streamOut)                        | 将属性列表输出到输出流中                 |
    | void load(InputStream streamIn) throws IOException     | 从输入流读取属性列表                     |
    | Enumeration propertyNames()                            | 枚举键值对                               |
    | Object setProperty(String key, String value)           | 内部调用Hashtable的put方法               |
    | void store(OutputStream streamOut, String description) | 将属性列表输出到输出流                   |

*** Dictionary

** Java2后出现的集合框架
   集合框架的设计目标：
   1) 提供高性能的集合操作
   2) 对不同类型的集合采用类似的方式操作
   3) 对某个集合的扩展和适应必须简单
   
   组成：
   1) 接口
      1) Collection
         标识存储一组不唯一、无序的元素。
      2) List
         继承Collection接口，标识存储一组不唯一、有序的元素。
         - 特点
           1) 检索效率高
           2) 插入、删除效率低(会引起其它元素位置改变)
      3) Set
         继承Collection接口，标识存储一组唯一、无序的元素。
         - 特点
           1) 检索效率低
           2) 插入、删除效率高(不会引起其它元素位置改变)
      4) Queue
         继承Collection接口，标识一组遵循FIFO操作的元素。
      5) Map
         标识一系列键值对。
      6) SortedMap
         继承Map接口，标识一系列将key按升序排列的键值对。
      7) Map$Entry
         在Map接口内部定义的，标识一组键值对。
   2) 抽象类/实现类
      1) AbstractCollection
         实现大部分Collection接口的方法。
      2) AbstractList
         继承AbstractCollection和List，并实现大部分List接口的方法。
      3) AbstractSequentialList
         继承AbstractList，提供对集合元素的链式访问而不是随机访问。
      4) LinkedList
         链式数据结构的列表，非线性安全。
         - 特点
           1) 检索效率低
           2) 插入、删除效率高
         - 线性安全改造
           #+BEGIN_EXAMPLE java
           List<String> unsafeList = new LinkedList();
           List<String> safeList = Collections.synchronizedList(unsafeList);
           #+END_EXAMPLE
      5) ArrayList
         大小可变的数组，非线性安全。
         - 特点
           1) 检索效率高
           2) 插入、删除效率低
         - 线性安全改造
           #+BEGIN_EXAMPLE java
           List<String> unsafeList = new LinkedList();
           List<String> safeList = Collections.synchronizedList(unsafeList);
           #+END_EXAMPLE
      6) Vector
         继承AbstractList
      7) Stack
         继承Vector，提供一组遵循FILO操作集合
      8) AbstractSet
         继承AbstractCollection和Set，并实现大部分Set接口的方法。
      9) HashSet
         存储一组唯一、无序的元素。         
      10) LinkedHashSet
          具有可预知迭代顺序的Set接口的hash和linkedlist的实现
      11) TreeSet
          提供排序等功能
      12) AbstractMap
          集成Map接口，实现大部分Map的方法
      13) HashMap
          继承AbstractMap，根据键的HashCode值存储数据，检索效率高，非线性同步
      14) Hashtable
          继承AbstractMap，根据键的HashCode值存储数据，检索效率高，线性同步
      15) SortedMap
          继承Map接口，标识提供排序功能
      16) TreeMap
          继承SortedMap，实现排序等功能
      17) WeakHashMap
          继承AbstractMap，使用弱密钥的哈希表
      18) LinkedHashMap
          继承HashMap，对键按自然顺序来排序
      19) IdentityHashMap
          继承AbstractMap，比较时采用引用相等来比较。
   3) 算法
      作为 ~java.util.Collections~ 和 ~java.util.Arrays~ 静态方法提供。
      1) ~java.util.Arrays~
         - ~Arrays.asList(T... a)~ 将数组转换为大小固定的List实例，若向该List实例添加元素则会抛异常UnsupportedOperationException
      2) ~java.util.Collections~

** ConcurrentHashMap

* TODO 迭代器
  实现Iterator或ListIteractor(继承Iterator，允许双向遍历列表和修改元素)接口

** 使用示例
   #+BEGIN_EXAMPLE java
   Map<String, String> map = new HashMap<String, String>();
   
   // 遍历键
   for (String key : map.keySet()){}
   // 遍历值
   for (String key : map.valueSet()){}

   // 使用Iterator实例
   Iterator<Map.Entry<String, String>> it = map.entrySet().iterator();
   while (it.hasNext()){
     Map.Entry<String, String> entry = it.next();
     System.out.printf("key: %s, value: %s", entry.getKey(), entry.getValue());
   }
   // 或
   for (Map.Entry<String, String> entry : map.entrySet()){
     System.out.printf("key: %s, value: %s", entry.getKey(), entry.getValue());
   }
   #+END_EXAMPLE
  
* TODO 比较器
  Comparator 和 Comparable

* TODO 注解
* TODO 打包发布
  jar、ear和war的差别
* 反射
Class类(类型类)，即所有Java类型的均为Class类的实例。连8种基本数据类型和void类型，都是Class类的实例。
#+BEGIN_EXAMPLE java
public Class{
  private Class(ClassLoader classLoader);
}
#+END_EXAMPLE
获取方式
1) ~类名.class~
2) ~实例.getClass()~
3) ~Class.forName("全限定类名")~ ， 通过Bootstrap ClassLoader加载获取，前提是相关的class文件在classpath下。
4) ~this.getClass().getClassLoader().loadClass("全限定类名")~ ，使用指定的ClassLoader加载获取。

** 示例
- 反射的对象
  #+BEGIN_EXAMPLE java
  package com.john;
  
  public interface Animal{}
  
  public class User{
    public String say(String suffix){
      return "User: " + suffix;
    }
  }
  
  public class Student extends User implements Animal{
    private String name;
    public int age;
  
    public void getName(){
      return this.name;
    }
  
    private void setName(String name){
      this.name = name;
    }
  
    public static final String JOB = "student";
    public static String GET_JOB(){
      return JOB:
    }
  
    public Student(){
    }
  
    public Student(String name, int age){
      this.name = name;
      this.age = age;
    }
  
    @Override
    public String say(String suffix){
      return "Student: " + suffix;
    }
  }
  #+END_EXAMPLE
- 反射操作  
  #+BEGIN_EXAMPLE java
  // 获取全限定类名
  Student student = new Student();
  student.getClass().getName(); // 返回com.john.Student
  
  // 3种获取Class类实例的方法
  Class<?> cObj1 = Student.class;
  Class<?> cObj2 = student.getClass();
  Class<?> cObj3 = Class.forName("com.john.Student");

  // 实例化
  Student student1 = (Student)cObj1.newInstance(); // 调用无参构造方法
  Student student2 = (Student)cObj1.newInstance("john", 25); // 调用含参构造方法
  
  // 获取接口的Class类实例
  Class<?>[] interfaces = cObj1.getInterfaces();

  // 获取父类的Class类实例
  Class<?> superClass = cObj1.getSuperclass();

  // 获取所有构造方法
  Constructor<?>[] cs = cObj1.getConstructors();
  
  // 获取当前类(不含父类和接口)所有方法(包含public、protected、default、private)
  Method[] fs = cObj1.getDeclaredMethods(); 
  // 获取当前类及从父类继承而来的所有公共方法
  Method[] fs1 = cObj1.getMethods();
  for (Method f : fs){
    // 获取方法名称
    String functionName = f.getName();
    // 获取方法修饰符
    Modifier<?>[] ms = f.getModifiers();
    String modifierNames = Modifier.toString(ms); // 方法所有修饰符组成的字符串
    // 获取方法入参列表类型
    Class<?>[] parameterTypes = f.getParameterTypes();
    // 获取方法声明抛出的异常
    Class<?>[] exceptionTypes = f.getExceptionTypes();
  }

  // 获取当前类(不含父类和接口)所有属性(包含public、protected、default、private)
  Field[] fields = cObj1.getDeclaredFields();
  // 获取当前类及从父类继承而来的所有公共属性
  Field[] fields1 = cObj1.getFields();

  // 调用实例方法
  Method mSay = cObj1.getDeclaredMethod("say", String.class);
  String ret = (String) mSay.invoke(student, "Hello"); // 输出 Student: Hello

  // 调用静态方法
  Method mGetJob = cObj1.getMethod("GET_JOB");
  String ret1 = (String) mGetJob.invoke(null);
  
  // 访问privat字段
  Field field = cObj1.getDeclaredField("name");
  field.setAccessible(true); // 私有成员字段必须暴力反射后才能读写
  field.set(student, "set by reflect");
  String name = (String)field.get(student);

  // 操作数组
  Integer[] array = [1,2,3];
  Class<?> clazz = array.getClass();
  if (clazz.isArray()){
    System.out.println("is array");
  }
  // 获取数组元素数据类型
  Class<?> componentClazz = array.getClass().getComponentType();
  // 实例化，数组长度为10
  Object newArray = Array.newInstance(componentClazz, 10);
  Integer len = Array.getLength(newArray);
  System.arraycopy(array, 0, newArray, 0, len);
  #+END_EXAMPLE

** ~public static native java.lang.Class sun.reflect.Reflection.getCallerClass(int depth)~
   用于获取调用该方法的类/父类/祖先类信息
   #+BEGIN_EXAMPLE java
   package com.test;

   public class C {
     public void test(){
       Class<?> clazz0 = java.reflect.Reflection.getCallerClass(0);
       Class<?> clazz1 = java.reflect.Reflection.getCallerClass(1);
       Class<?> clazz2 = java.reflect.Reflection.getCallerClass(2);
       System.out.println(clazz0.getName());
       System.out.println(clazz1.getName());
       System.out.println(clazz2.getName());
     }
   }

   public class P {
     public static void main(String[] args){
       C c = new C();
       c.test();
       // java.reflect.Reflection
       // com.test.C
       // com.test.P
     }
   }
   #+END_EXAMPLE

* 从classpath获取资源
  ClassLoader是从classpath中读取资源的类，一般情况通过ClassLoader加载字节码文件(.class文件)，但它提供两个方法加载其他资源。
  - ~public URL getResource(String name)~
    实际代码中一般是通过 ~YourClass.class.getResource(String name)~ 来调用，通过委托底层依然是调用ClassLoader的该方法。
  - ~public InputStram getResourceAsStream(String name)~
    实际代码中一般是通过 ~YourClass.class.getResourceAsStream(String name)~ 来调用，通过委托底层依然是调用ClassLoader的该方法。
  - ~public static URL getSystemResource(String name)~ 静态方法调用该方法获取classpath下的资源。
  - ~public static InputStream getSystemResourceAsStream(String name)~ 静态方法调用该方法获取classpath下的资源。
 
** 示例
   #+BEGIN_EXAMPLE java
   package com.test;
   
   public class App {
     public static void main(String[] args){
       Class<?> clazz = App.class;
       
       clazz.getResource(""); // 返回当前.class文件所在目录的绝对URI，如file:///d:\workspace\john\bin\com\test
       clazz.getResource("/"); // 返回当前.class文件所在classpath的绝对URI，如file:///d:\workspace\john\bin\
       clazz.getClassLoader().getResource(""); // 返回当前.class文件所在classpath的绝对URI，如file:///d:\workspace\john\bin\
       ClassLoader.getSystemResource(""); // 返回当前.class文件所在classpath的绝对URI，如file:///d:\workspace\john\bin\
       Thread.currentThread().getContextClassLoader().getResource(""); // 返回当前.class文件所在classpath的绝对URI，如file:///d:\workspace\john\bin\
     }
   }
   #+END_EXAMPLE

** ResourceBundle
   基于类路径读取属性文件，因此属性文件必须包含在classpath下，并通过全限定类名读取属性文件，并且提供缓存功能，若要更新则要手动清除。
   #+BEGIN_EXAMPLE java
   ResourceBundle bundle = ResourceBundle.getBundle("com.test.properties.test01");
   System.out.println(bundle.getString("jdbc.driver");
   Enumeration<String> keys = bundle.getKeys();
   while (keys.hasMoreElements()){
     String key = keys.nextElement();
     System.out.printf("%s: %s%n", key, bundle.getString(key));
   }
   #+END_EXAMPLE

*** properties文件
    1) 行注释: 以 ~#~ 开头
    2) 编码: ~ISO-8859-1~, 该编码不支持中文，中文需转换为Unicode编码才行。
       
* ClassLoader(类加载器)
  1) Bootstrap ClassLoader
     C++实现，作为Ext ClassLoader的父类加载器，负责jdk_home/lib目录下的核心API或-Xbootclasspath指定的jar包装入工作。
  2) System ClassLoader
     负责 ~java -classpath/-Djava.class.path~ 所指目录下的类和jar包装入工作。
  3) Ext ClassLoader
     作为App ClassLoader的父类加载器，负责jdk_home/lib/ext目录下的jar包或-Djava.ext.dirs指定目录下的jar包装入工作。
  4) App ClassLoader
     负责加载用户类。
  5) Customer ClassLoader
     一般都继承App ClassLoader，用户自定义。

** 获取ClassLoader的方法
   1) ~this.getClass().getClassLoader()~
   2) ~Thread.currentThread().getContextClassLoader()~ 获取当前线程的ClassLoader
   3) ~ClassLoader.getSystemClassLoader()~ 获取系统入口点使用的ClassLoader

* TODO JNI

* 文档注释
  | 标签          | 说明                                               |
  |---------------+----------------------------------------------------|
  | @author       | 作者                                               |
  | @deprecated   | 指定类或成员已过期                                 |
  | {@docRoot}    | 指定当前文档的根目录                               |
  | @exception    | 指定抛出的异常                                     |
  | {@inheritDoc} | 从直接父类即成的注释                               |
  | {@link}       | 插入一个引用另一个主题的链接                       |
  | {@linkplain}  | 插入一个引用另一个主题的链接，但以纯文本形式显示   |
  | @param        | 方法参数                                           |
  | @return       | 方法返回值                                         |
  | @see          | 指定一个到另一个主题的链接                         |
  | @serial       | 说明一个序列化属性                                 |
  | @serialData   | 说明通过writeObject()和writeExternal()方法写的数据 |
  | @serialField  | 说明一个ObjectStreamField组件                      |
  | @since        | 标记什么时候引入一个特定的变化                     |
  | @throws       | 和@exception一样                                   |
  | {@value}      | 说明常量的值，该常量必须是static属性               |
  | @version      | 版本号                                             |

  然后通过命令 ~javadoc~ 生成文档。
** 示例
   #+BEGIN_EXAMPLE java
   /***
   * @author huangza
   * @version 0.1.0
   */
   public class Box<String>{
     /**
     * @param a string one.
     * @param b string one.
     * @return concatenate string.
     * @exception IOException
     * @see IOException
     */
     public String concat(String a, String b){
       return a + b;
     }
   }
   #+END_EXAMPLE

* JNDI(Java Naming and Directory Interface)
  是一组在Java中访问命名和目录服务的API，作为J2EE的核心技术之一。
  1) 命名服务
     将名称和对象联系起来，让我们可以通过名称访问对象。
  2) 目录服务
     基于命名服务上作增强，使得对象不仅有名称还有属性。
  
  JNDI组成
  1) 应用编程接口(API)
  2) Naming Manager
  3) 服务提供者接口(SPI,Service Provider Interface)
  4) LDAP服务提供者、NIS服务提供者、文件系统服务提供者等

  优点：通过名称引用Java对象或资源，而不必知道对象或资源的物理位置。
   
  JNDI现在可访问的命名和目录服务有
  1) DNS
  2) XNam
  3) Novell目录服务
  4) LDAP
  5) CORBA对象服务
  6) 文件系统
  7) Windows的注册表
  8) RMI
  9) DSML v1&v2
  10) NIS
  
  在J2EE环境下，JNDI的主要用途
  1) 获得Java事务API中的UserTransaction接口的引用
  2) 获得如JDBC、JMS等连接到资源工厂
  3) 在EJB组件中，查找其他EJB组件

  JNDI的概念
  1) Atomic Name(原子名)
     不可分割的名字，如/ETC/FSTAB中的ETC和FSTAB均为Atomic Name
  2) Compound Name(复合名)
     由0或多个Atomic Name组成，如/ETC/FSTAB就是Compound Name
  3) Binding(绑定)
     名字和对象或资源的关联
  4) Context(上下文)
     包含0或多个Binding，如java/MySql中java为Context，而MySql为名字，整体和某个对象或资源关联起来了
  5) Subcontext(子上下文)
     上下文的上下文，如java/ejb/helloBean中ejb为Subcontext
  6) 命名系统
     构成命名空间定义的语法语义
  7) 命名空间
     根据命名系统的语法约定由原子名、复合名、上下文构成的结构，如文件系统的命名空间由目录和文件名组成
  8) 合成名
     由多个命名系统组成的名字，如URL ~http://java.sun.com/product/index.html~
     1) http来自URL scheme-id命名系统
     2) java.sum.com来自DNS命名系统
     3) product、index.html来自文件系统的命名系统

** 工具包
   - ~javax.naming~ 提供访问命名服务的类和接口
     - Context 命名服务操作的入口
   - ~javax.naming.directory~ 对 ~javax.naming~ 扩充，提供访问目录服务的功能
     - DirContext 目录服务操作的入口
   - ~javax.naming.event~ 对访问命名和目录服务提供事件通知的支持
     - NamingEvent 命名或目录服务产生的事件
     - NamingListener 事件监听
   - ~javax.naming.ldap~ 提供对LDAPv3扩展操作和控件的支持
     - LdapContext LDAP目录服务操作的入口
   - ~javax.naming.spi~ 允许动态插入不同实现。为有兴趣创建服务提供者的开发者提供的。

** LDAP(Light Directory Access Protocol)
   相当于简易版本的RDBMS，以树状的层次结构存储数据，适用于读多写少的场景。（优化过读取操作）
   
*** 概念
    1) DN(Distinguished Name)
       标记记录路径的唯一标识。其中Base DN为基准DN，即从哪个DN开始搜索(搜索范围分为One Level和Subtree)。而RDN为叶子节点本身的标识。
    2) DC(Domain Component)
       记录所属区域
    3) OU(Organization Unit)
       组织单元
    4) CN/UID
       记录的名字
   
*** 运维工具
    1) GUI查看工具 —— Free LDAP Browser
   
*** TODO 示例

* 单元测试
  
** JUnit3
   针对JDK1.5之前不支持注解的版本
   #+BEGIN_EXAMPLE java
   public class AppTest extends TestCase{
     public AppTest(){
       // 执行BeforeClass的逻辑
     }
   
     @Override
     protected void setUp() throws Exception{
       // 每个testXxx执行前执行
     }

     @Override
     protected void tearDown() throws Exception{
       // 每个testXxx执行后执行
     }

     // 方法名必须以test开头，标识该方法为testcase
     public void testXxx() throws Exception{
       assertTrue(true);
     }
   }
   #+END_EXAMPLE

** JUnit4
   针对JDK1.5之后支持注解的版本
   #+BEGIN_EXAMPLE java
   public class AppTest{
     // 在所有测试用列和所有@Before标识的方法执行前执行一次
     @BeforeClass
     public static void beforeClass() throws Exception{}

     // 在所有测试用列和所有@After标识的方法执行后执行一次
     @AfterClass
     public static void afterClass() throws Exception{}
     
     @Before
     public void setUp() throws Exception{}

     @After
     public void tearDown() throws Exception{}

     /***
     * 1. 测试用例方法名没有限制，但约定俗成还是以test开头
     * 2. 必须为public void且参数列表必须为空
     */
     @Test
     public void testXxx() throws Exception{
       assertTrue(true);
     }

     // 期望该测试用例在400毫秒内执行完成
     @Test(timeout=400)
     public void testBbb() throws Exception{
     }

     // 期望该测试用例抛出ArithmeticExceptrion异常
     @Test(excepted=ArithmeticExceptrion.class)
     public void testAaa() throws ArithmeticExceptrion{
     }

     @Test
     @Ignore // 忽略该测试用例
     public void testCcc() throws Exception{}
   }
   #+END_EXAMPLE

*** 测试套件(TestSuite)
    将多个类定义的TestCase纳入TestSuite中，那么就可一次性运行多个类中的TestCase。
    #+BEGIN_EXAMPLE java
    @RunWith(Suite.class) // 指定测试运行器为Suite.class
    @Suite.SuiteClasses({AppTest.class, TaskTest.class}) // 包含TestCase类或其他TestSuite类
    public class AppSuite(){}
    #+END_EXAMPLE

*** 参数化测试
    用于对某方法在多种场景下进行测试。
    #+BEGIN_EXAMPLE java
    // 指定测试运行器为Suite.class
    @RunWith(Parameterized.class)
    public class AppTest {
      // 场景参数
      int a;
      int b;
      
      // 通过@Parameters标记返回值为Collection的静态方法来设置场景参数生成方法
      @Parameters
      public static Collection<int[]> init(){
        return Arrays.asList(new int[][]{
          {1,2},
          {3,4},
          {5,6}
        });
      }
      
      // 必须定义带参数的构造方法来构造特定场景的测试用例
      public AppTest(int a, int b){
        this.a = a;
        this.b = b;
      }
      
      @Test
      public void testXxx(){
        assertEquals(this.a, this.b);
      }
    }
    #+END_EXAMPLE

** TODO JUnit5
   包含JUnit Jupiter、JUnit Platform和JUnit Vintage。
   https://www.ibm.com/developerworks/cn/java/j-introducing-junit5-part1-jupiter-api/index.html

** 断言库

* Java8新特性
  
** Lambda表达式

** 方法引用

** 函数式接口

** 默认方法

** 新工具

** Stream API

** Date Time API

** Optional类

** Nashorn JavaScript引擎

** Base64

* QA
1) CopyOnWrite
2) 泛型
3) 线程池
4) CAS
5) AQS
6) JVM
7) 实现java.io.Serializable接口的类需要定义 ~private static final long serialVersionUID~ ?
 

