* 8种基本数据类型
  - byte, 1byte signed integer
    - default 0
    - min -128
    - max 127
    - 包装类 Byte
  - short, 2byte signed integer
    - default 0
    - min -32768
    - max 32767
    - 包装类 Short
  - int, 4byte signed integer
    - default 0
    - min -2,147,483,648
    - max 2,147,483,647
    - 包装类 Integer
  - long, 8byte signed integer
    - default 0L
    - min -9,223,372,036,854,775,808
    - max 9,223,372,036,854,775,807
    - 包装类 Long
  - float, 4byte IEEE 754 float
    - default 0.0f
    - 不能用于表示精确的值，如货币
    - 包装类 Float
  - double, 8byte IEEE 754 float
    - default 0.0d
    - 不能用于表示精确的值，如货币
    - 包装类 Double
  - boolean
    - default false
    - 包装类 Boolean
  - char, a 2byte Unicode character
    - default \u0000
    - min \u0000
    - max \uffff
    - 包装类 Character
    - 示例
      #+BEGIN_EXAMPLE java
      char uniChar = '\u039A'; // Unicode 字符表示形式
      char[] charArray = {'a', 'b'};
      #+END_EXAMPLE
  
  8种基本数据类型的包装类的属性
  - SIZE，返回数据类型所占的位数
  - MIN_VALUE，返回最小值
  - MAX_VALUE，返回最大值
  所有基本数据类型的包装类都继承Number
  静态方法
  - valueOf(primitive_value)，将基本数据类型转换为包装类
  实例方法
  - xxxValue()，从包装类实例中提取内部的基本数据类型变量值

  

  隐式类型转换： ~byte,short,char -> int -> long -> float -> double~ 
  显式强制转换需注意内容：
  1) 浮点数转整数会直接舍弃小数，而不是四舍五入
  2) 不能对boolean类型进行类型转换

* 局部变量、实例变量和静态变量
  1) 局部变量
     - 在线程栈上分配存储空间
     - 没有默认值，因此声明后必须经过初始化后才能使用
  2) 实例变量
     - 有默认值
       - 数值型变量为0
       - 布尔型变量为false
       - 引用类型变量为null
     - 变量值的初始化时机
       1) 声明时设置
       2) 构造方法中设置
  3) 静态变量
     - 在静态存储区分配存储空间
     - 有默认值
       - 数值型变量为0
       - 布尔型变量为false
       - 引用类型变量为null
     - 变量值的初始化时机
       1) 声明时设置
       2) 构造方法中设置
       3) 静态语句块中设置

* StringBuffer和StringBuilder
  StringBuffer为线性安全，而StringBuilder在Java5引入且为非线性安全。
  由于StringBuilder为非线程安全，因此性能上优于StringBuffer。

* 数组
  #+BEGIN_EXAMPLE java
  // 2种声明方式
  int[] a; // 首推这种
  int b[];

  // 定义容量为5的int数组
  int[] c = new int[5];
  int[] d = {1,2,3,4,5};
  
  String[] strs = new String[]{"a", "b"};

  // 2×n的二维数组
  int[][] e = new int[2][];
  e[0] = new int[2]; 
  e[1] = new int[3]; 
  e[0][0] = 1;
  e[0][1] = 2;
  e[1][0] = 4;
  e[1][1] = 6;
  e[1][2] = 7;

  int[] nums = new int[]{1,2,3};
  Integer[] iNums = new Integer[]{1,2,3};
  Object[] oINums = (Object[])iNums; // 强制转换成功
  Object[] oNums = (Object[])nums; // 强制转换失败
  #+END_EXAMPLE

** ~java.util.Arrays~ 操作数组的帮助类
   - ~int Arrays.binarySearch(T[] a, T key)~ 对已排序的数组进行二分查找对象，若找到则返回对应的索引，否则返回-1。
   - ~boolean Arrays.equals(T[] a, T[] b)~ 当两个数组中所有相应元素对都是相等，那么认为这两个数组是相等的。
   - ~void Arrays.fill(T[] a, T b)~ 用元素b填满数组a。
   - ~void sort(T[] a)~ 根据自然顺序进行升序排列。

* 日期时间

** ~java.util.Date~
   - 构造方法
     1) ~new Date()~ 使用当前日期时间初始化对象
     2) ~new Date(long millisec)~ 参数作为相对于1970/1/1起的毫秒数来初始化对象
   - 实例方法
     很多方法已经被标识为deprecated，建议使用Calender来操作
     - ~boolean after(Date date)~ 判断Date实例是否在入参之后
     - ~boolean before(Date date)~ 判断Date实例是否在入参之前
     - ~Object clone()~ 复制实例副本
     - ~boolean equals(Date date)~ Date实例和入参相同则返回true
     - ~int hashCode()~ 返回对象的哈希码
     - ~int compareTo(Date date)~ Date实例与入参相同则返回0；Date实例在入参之前则返回负数；Date实例在入参之后则返回正数
     - ~long getTime()~ 返回自1970/1/1 00:00:00 GMT以来的毫秒数
     - ~void setTime(long time)~ 参数作为相对于1970/1/1起的毫秒数来设置日期时间对象值
     - ~String toString()~ 返回格式为 ~dow mon dd hh:mm:ss UTC yyyy~ 格式的日期时间字符串，其中dow为Sun,Mon,Tue,Web,Thu,Fri,Sat

** 日期时间字符串格式化
   1) ~java.text.SimpleDateFormat~
      继承 ~java.text.DateFormat~ ，提供locale-sensitive的日期和格式化字符串之间的相互转换功能。
      - 日期时间转换为格式化字符串
      #+BEGIN_EXAMPLE java
      // 假定当前时区为东8(即GMT+8)
      // 因此所有时间的默认时区均为东8
      Date now = new Date(); // 假设日期时间为 2019-04-21 00:00:00
      SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
      String gmt8 = ft.format(now); // 2019-04-21 00:00:00
      ft.setTimeZone(TimeZone.getInstance("GMT")); // 设置时区为0时区
      String gmt = ft.format(now); // 2019-04-20 16:00:00
      #+END_EXAMPLE
      - 将字符串解析为日期时间
        #+BEGIN_EXAMPLE java
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = ft.parse("2019-02-02 00:02:00");
        #+END_EXAMPLE
   2) ~System.out.printf~
      以 ~%t~ 开头并以下面表格的一个字母结尾即可格式化日期时间
      | 转换符 | 说明                                            | 示例                             |
      |--------+-------------------------------------------------+----------------------------------|
      | c      | 全部日期和时间信息，和new Date().toString()一样 | 星期六 十月 27 14:21:20 CST 2007 |
      | F      | yyyy-MM-dd                                      |                                  |
      | D      | MM/dd/yy                                        |                                  |
      | r      | hh:mm:ss pm(12进制)                             | 02:25:51 下午                    |
      | T      | hh:mm:ss (24进制)                               | 14:25:51                         |
      | R      | hh:mm (24进制)                                  | 14:28                            |
      | B      | 月份全称                                        | January                          |
      | b      | 月份简称                                        | Jan                              |
      | A      | 星期全称                                        |                                  |
      | a      | 星期简称                                        |                                  |
      | C      | 年的前两位                                      |                                  |
      | y      | 年的后两位                                      |                                  |
      | m      | 两位数字的月份                                  |                                  |
      | d      | 两位数字的日期                                  |                                  |
      | e      | 一位数字的月份（前面不补零）                    |                                  |
      - 示例
        #+BEGIN_EXAMPLE java
        Date date = new Date();
        // 普通使用方式
        System.out.printf("%tR%n", date); // 显示14:28换行符
        // 使用索引
        System.out.printf("%1$s %2$tR %2$tT", "hi", date); // 显示hi 14:28 14:28:41没有换行符
        #+END_EXAMPLE
   3) ~String.format~
      采用和 ~System.out.printf~ 一致的格式化编码，但可以设置语言区域
      #+BEGIN_EXAMPLE java
      Date date = new Date();
      String str = String.format(Locale.US, "英语月份简称：%tb", date);
      String str = String.format("本地月份简称：%tb", date);
      #+END_EXAMPLE

** 测量时间间隔(毫秒) —— ~System.currentTimeMillis()~
   #+BEGIN_EXAMPLE
   long start = System.currentTimeMillis();
   // do something
   long end = System.currentTimeMillis();

   System.out.printf("%d", edn - start);
   #+END_EXAMPLE
   
** ~Calendar~ 实例
   可单独提取、增加、减少日期时间年、月、日等组件值。
   #+BEGIN_EXAMPLE java
   Calendar c1 = Calendar.getInstance(); // 返回GregorianCalendar实例，默认为当前时区的时间
   c1.set(2019, 12, 31); // 设置日期为2019/12/31
   c1.set(Calendar.YEAR, 2012);
   c1.set(Calendar.MONTH, 11); // 月份从0开始计算，其它均从1开始计算
   c1.set(Calendar.DATE, 30);
   c1.set(Calendar.DAY_OF_MONTH, 30); // 和 Calendar.DATE 效果一样
   c1.set(Calendar.HOUR, 12); // 12进制
   c1.set(Calendar.HOUR_OF_DAY, 13); // 24进制
   c1.set(Calendar.MINUTE, 45);
   c1.set(Calendar.SECOND, 55);
   c1.set(Calendar.DAY_OF_WEEK, 1); // 星期几，1星期日，2星期一
   // 对应有获取方法
   c1.get(Calendar.YEAR);
   // 在当前基础上增减
   c1.add(Calendar.YEAR, 1);
   c1.add(Calendar.YEAR, -1);
   #+END_EXAMPLE

*** Date和Calendar转换
    #+BEGIN_EXAMPLE java
    // Calendar转Date
    Calendar cale = Calendar.getInstance();
    Date date = cale.getTime();

    // Date转Calendar
    cale.setTime(date);
    #+END_EXAMPLE

* IO

** 字符流
   - Reader
     - BufferedReader
       - 示例：从标准输入读取字符
       #+BEGIN_EXAMPLE java
       BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
       char c = 'q';
       do {
         if (c != 'q'){
           System.out.println(c);
         }
         c = reader.read();
       }(c != 'q');
       #+END_EXAMPLE
     - InputStreamReader
       - FileReader
     - StringReader
     - PipedReader
     - CharArrayReader
     - FilterReader
       - PushbackReader
   - Writer
     - BufferedWriter
     - OutputStreamWriter
       - FileWriter
     - PrinterWriter
     - PipedWriter
     - CharArrayWriter
     - FilterWriter

** 字节流
   - InputStream
     - FileInputStream
     - FilterInputStream
       - BufferedInputStream
       - DataInputStream
       - PushbackInputStream
     - ObjectInputStream
     - PipedInputStream
     - SequenceInputStream
     - StringBufferInputStream
     - ByteArrayInputStream
   - OutputStream
     - FileOutputStream
     - FilterOutputStream
       - BufferedOutputStream
       - DataOutputStream
       - PrintStream
     - ObjectOutputStream
     - PipedOutputStream
     - ByteArrayOutputStream

** BIO(Blocking IO)
   同步阻塞编程方式，JDK1.4引入的特性。

** NIO(Unblocking/New IO)
   同步非阻塞编程方式，基于Reactor。

** AIO(Asynchronous IO)
   异步非阻塞编程方式，JDK1.7引入被称为NIO2.0。位于 ~java.nio.channels~ 下的4个异步通道：
   1) AsynchronousSocketChannel
   2) AsynchronousServerSocketChannel
   3) AsynchronousFileChannel
   4) AsynchronousDatagramChannel

* 修饰符
用于定义类、方法和变量，通常放在语句的最前端

** 访问控制修饰符
1) default 在同一个包内可见。使用对象：类、接口、方法、变量
2) public 公开。使用对象：类、接口、方法、变量
3) protected 对同一包内的类和所有子类可见。使用对象：方法、变量、内部类
4) private 在同一个类内可见。使用对象：方法、变量、内部类

*** 接口的默认访问修饰符
1) 变量默认为 ~public static final~
2) 方法默认为 ~public abstract~

** 非访问控制修饰符
1) final 用来修饰类、方法和变量
   1) 修饰类，类为最终类不能被继承
      1) 其下方法自动添加final修饰符
      2) 其下成员变量不会自动添加final修饰符
   2) 修饰方法，方法不能被子类重写(Override)
   3) 修饰变量，变量值不能被修改
      1) 变量为引用类型，那么变量指向的引用地址不能修改，但引用对应的内部属性可以被修改
         #+BEGIN_EXAMPLE java
         final Map<String, String> map = new HashMap<String, String>();
         map.put("one", "1");
         #+END_EXAMPLE
      2) 搭配static声明类变量作为常量使用
2) abstract 用来修饰抽象类和抽象方法
   1) 抽象类不能同时声明为final
   2) 抽象方法不能同时声明为final或static
   3) 若一个类包含抽象方法，那么该类也必须声明为抽象类
3) static 用来修饰类方法和类变量
4) synchronized 声明方法同一时间只能被一个线程访问
   - 示例 ~public synchronized void showDetails() {}~
5) volatile 修饰成员变量在每次线程访问时均强制从共享内存中重新读取值，并且当发生变化时强制线程将变化值回写到共享内存
6) transient 修饰变量不参与类的序列化

* 枚举
1) 可单独声明或在类和接口中声明
2) 枚举中可定义方法、变量和构造函数 ???
#+BEGIN_EXAMPLE java
class FreshJuice {
  enum FreshJuiceSize { SMALL, MEDIUM, LARGE }
  FreshJuiceSize size;
}

public class FreshJuiceTest {
  public static void main(String []args) {
    FreshJuice juice = new FreshJuice();
    juice.size = FreshJuice.FreshJuiceSize.LARGE;
  }
}
#+END_EXAMPLE

* 源文件声明规则
1) 一个源文件中只能有一个public类
2) 一个源文件中可以有多个非public类
3) 源文件名称必须和public类名称保持一致
4) 如果类定义在某个包中，那么源文件首行必须为package语句
5) import语句需放在package语句之后

* Java包
  用于对类和接口进行分类

** import语句
   通过完全限定名（包名+类名）引用指定类，而Java编译器就定位到对应的源文件。
   #+BEGIN_EXAMPLE java
   import java.io.*;
   #+END_EXAMPLE

** import static 静态引用
   从JDK1.5引入的特性，通过静态引入可以在当前类中直接使用被导入类的静态方法和静态成员变量，而不用以被导入类作为前缀来使用。
   #+BEGIN_EXAMPLE java
   import static org.john.Test.StaticMethod; // 引入静态方法StaticMethod
   import staitc org.john.Test.*; // 引入Test类下的所有静态方法和成员变量
   
   public class TestC{
     public void print(){
       StaticMethod(StaticMember);
     }
   }
   #+END_EXAMPLE

* 面对对象编程

** ~super~ 和 ~this~
   ~super~ 用于显式访问父类成员
   ~this~ 用于显式访问当前类的成员

** 构造方法
   子类不会继承父类的构造方法，默认情况下会隐式调用父类的无参构造方法，但可通过 ~super~ 来显式调用父类的其它构造方法。
   #+BEGIN_EXAMPLE java
   class Super1 {
     Super1(){
       System.out.println("Super1 default constructor.");
     }
     Super1(int num){
       System.out.println("Super1 constructor with argument `num`.");
     }
   }
   class Child1 extends Super1{
     Child1(){
       super(10);
       System.out.println("Child1 default constructor.");
     }

     Child1(int num){
       System.out.println("Child1 constructor with argment `num`.");
     }
   }

   Super1 s1 = new Child1();
   Super1 s2 = new Child1(10);
   /* Super1 constructor with argument `num`.
    * Child1 default constructor.
    * Super1 default constructor.
    * Child1 constructor with argment `num`.
    */
   #+END_EXAMPLE

** 接口
   实现接口的抽象类可不实现接口的所有方法，否则则需要实现接口的所有方法。
   1) 接口和抽象类的区别
      1) 接口不能包含静态代码块和静态方法
      2) 一个类可实现多个接口，但只能继承一个抽象类
      3) 接口的方法不能有方法体，而抽象类中的非抽象方法将包含方法体
      4) 接口的成员变量修饰符只能为 ~public static final~ ，抽象类的成员变量修饰符和普通实现类一样
   2) 接口定义
      #+BEGIN_EXAMPLE java
      [public|private] interface <接口名称> [extends <其它接口名称>...]{}
      #+END_EXAMPLE
   3) 接口多继承
      接口支持多继承，即可通过 ~extends~ 继承多个父接口
      #+BEGIN_EXAMPLE java
      interface A{}
      interface B{}
      interface C extends A, B {}
      #+END_EXAMPLE
   4) 标记接口
      不包含任何属性和方法，仅用于表明它的实现类属于一个特定的类型拥有某个或某些权利。

** 重写(Override)和重载(Overload)
   - 重写(Override)
     子类重新实现父类的签名相同的实例方法
     1) 子类方法不能抛出比父类方法范围更大的异常，仅能抛出父类方法声明的异常或其派生类
        #+BEGIN_EXAMPLE java
        class Super1{
          void echo throws IOException () {}
        }
        class Child1 extends Super1{
          // 编译时报错，因为子类方法抛出的异常范围比父类的更大
          void echo throws Exception () {}
        }
        #+END_EXAMPLE
     2) 子类方法的参数列表必须和父类的一致
     3) 子类方法的返回值类型要么和父类的一致，要么为父类方法返回值类型的派生类(Java5前必须和父类的一致)
     4) 子类方法的访问权限不能低于父类的
        1) 父类为public，那么子类必须为public
        2) 父类为default，那么子类可以为default或public
        3) 父类为protected，那么子类可以为protected、default或public
     5) 在子类方法中可通过 ~super~ 调用父类中被重写的方法
     6) 静态方法不存在重写，父类和子类的静态方法各自独立
   - 重载(Overload)
     在同一个类中多个名称相同但方法参数列表不同的实例或静态方法，重载方法的返回值类型可相同也可以不同
     1) 重载方法必须具有不同的参数列表，仅返回值类型不同是无法区分方法的

** 多态
   三个必要条件：
   1) 继承
   2) 重写
   3) 父类引用指向子类对象
      #+BEGIN_EXAMPLE java
      Super1 super1 = new Child1();
      #+END_EXAMPLE

** 注解
   1) ~@Override~ 指示该方法为重写父类的同名方法，那么在编译时会检查被标识的方法签名是否与父类签名一致，若不一致则编译失败。

** 泛型
   从Java5引入的特性，提供了编译时类型安全检查机制。泛型本质为 *参数化类型* ，即为所操作的数据类型指定一个参数。
   注意点：
   1) 类型参数只能代表 *引用类型* 不能是原始类型

*** 泛型方法
    #+BEGIN_EXAMPLE java
    // 入参类型和返回值类型采用泛型
    public <E> E print(E a){
      System.out.println(a);
      
      return a;
    }

    // 多个泛型
    public <E, T> T forceCast(E a){
      return (T)a;
    }
    
    // 有界泛型，通过extends或implements设置泛型必须为某类或接口的派生类
    public <T extends Comparable<T>> T maximum(T x, T y){
      T max = x;
      if (y.compareTo(max) > 0){
        max = y;
      }

      return max;
    }
    #+END_EXAMPLE

*** 泛型类
    #+BEGIN_EXAMPLE java
    public class Box<T>{
      private T value;
      public T getValue(){
        return this.value;
      }
      public void setValue(T value){
        this.value = value;
      }
    }
    #+END_EXAMPLE

*** 类型通配符
    1) ~?~ 用于对不关心应类型参数具体值的场景
       #+BEGIN_EXAMPLE java
       void printData(List<?> data){
         System.out.println(data.get(0));
       }
       #+END_EXAMPLE
    2) 带 ~extends~ 或 ~implements~ 的有界泛型通配符，用于对不关心应类型参数具体值但需要限制为某类或接口的派生类
       #+BEGIN_EXAMPLE java
       void printNumber(List<? extends Number> data){
         System.out.println(data.get(0) + 1);       
       }
       #+END_EXAMPLE
    3) 带 ~super~ 的有界泛型通配符，用于对不关心应类型参数具体值但需要限制为某类及其三层父类类型，如Object类型
       #+BEGIN_EXAMPLE java
       void printNumber(List<? super Number> data){
         System.out.println(data.get(0) + 1);       
       }
       #+END_EXAMPLE
   
** 方法的可变参数
   JDK1.5引入的特性，支持传递同类型的可变参数给方法，并且必须作为最后一个参数。
   #+BEGIN_EXAMPLE java
   public class Test{
     public void printMax(String str, double... numbers){
       // do something
     }

     public void execute(){
       String firstArg = "the first argument";
       double[] vals = {1d,2d,3d};
       this.printMax(firstArg, 1d,2d);
       this.printMax(firstArg, vals);
     }
   }
   #+END_EXAMPLE

*** 方法重载优先匹配固定参数
    若调用的方法能匹配到固定参数重载方法和可变参数重载方法，那么优先匹配固定参数重载方法。
    #+BEGIN_EXAMPLE java
    public class Test{
      public static String concat(String a, String b){
        System.out.println("concat(String a, String b)");
        return a + b;
      }
      public static String concat(String... strs){
        System.out.println("concat(String... strs)");
        StringBuilder sb = new StringBuilder();
        for (String str : strs){
          sb.append(str);
        }
        return sb.toString();
      }

      public static void main(String[] args){
        concat("a", "b"); // concat(String a, String b)
        concat("a", "b", "c"); // concat(String... strs)
      }
    }
    #+END_EXAMPLE

*** 如匹配到多个可变参数重载方法，则会报编译时异常
    #+BEGIN_EXAMPLE java
    public class Test{
      public static void test(String a, Integer... b){
        System.out.println("Integer");
      }
      public static void test(String a, String... b){
        System.out.println("String");
      }

      public static void main(String[] args){
        // test("abc", null); 由于无法判断null的数据类型，因此会抛出编译时异常
        String[] b = null;
        test("abc", b); // String
      }
    }    
    #+END_EXAMPLE

*** 反射
    由于反射是在运行时获取类、方法等的元数据，而可变参数在运行时被编译为数组。因此通过反射调用可变参数方法时，可变参数用数组代替。
    #+BEGIN_EXAMPLE java
    public class Test{
      public static void print(String... strs){
        System.out.println(strs[0]);
      }

      public static void main(String[] args){
        Method method = Test.class.getMethod("print", String[].class);
        method.invoke(null, new String[]{"a", "b"}); // 成功
        method.invoke(null, "a", "b"); // 抛出java.lang.IllegalArgumentException: wrong number of arguments
      }
    }
    #+END_EXAMPLE

* TODO 异常处理

** 异常/错误

* 集合类型

** Java2出现的
*** ~java.util.BitSet~ (位集合)
    实现了一组可单独设置和清除的位标识。

*** ~java.util.Vector~   
    动态数组，功能和ArrayList类似，但有如下区别：
    1) Vector是线性安全
    2) Vector包含很多不属于集合框架的方法

*** ~java.util.Stack~
    ~java.util.Stack~ 为 ~java.util.Vector~ 的子类。

*** ~java.util.Properties~
    为 ~java.util.Hashtable~ 的派生类，通过 ~System.getProperties()~ 获取环境变量时的返回值类型就是 ~java.util.Properties~
    | 方法签名                                               | 描述                                     |
    |--------------------------------------------------------+------------------------------------------|
    | Properties()                                           | 无参构造方法                             |
    | Properties(Properties props)                           | 以props作为默认值的构造方法              |
    | String getProperty(String key)                         | 通过键搜索属性值                         |
    | String getProperty(String key, String defaultProperty) | 通过键搜索属性值，若搜索失败则返回默认值 |
    | void list(PrintStream streamOut)                       | 将属性列表输出到输出流中                 |
    | vod list(PrintWriter streamOut)                        | 将属性列表输出到输出流中                 |
    | void load(InputStream streamIn) throws IOException     | 从输入流读取属性列表                     |
    | Enumeration propertyNames()                            | 枚举键值对                               |
    | Object setProperty(String key, String value)           | 内部调用Hashtable的put方法               |
    | void store(OutputStream streamOut, String description) | 将属性列表输出到输出流                   |

*** Dictionary

** Java2后出现的集合框架
   集合框架的设计目标：
   1) 提供高性能的集合操作
   2) 对不同类型的集合采用类似的方式操作
   3) 对某个集合的扩展和适应必须简单
   
   组成：
   1) 接口
      1) Collection
         标识存储一组不唯一、无序的元素。
      2) List
         继承Collection接口，标识存储一组不唯一、有序的元素。
         - 特点
           1) 检索效率高
           2) 插入、删除效率低(会引起其它元素位置改变)
      3) Set
         继承Collection接口，标识存储一组唯一、无序的元素。
         - 特点
           1) 检索效率低
           2) 插入、删除效率高(不会引起其它元素位置改变)
      4) Queue
         继承Collection接口，标识一组遵循FIFO操作的元素。
      5) Map
         标识一系列键值对。
      6) SortedMap
         继承Map接口，标识一系列将key按升序排列的键值对。
      7) Map$Entry
         在Map接口内部定义的，标识一组键值对。
   2) 抽象类/实现类
      1) AbstractCollection
         实现大部分Collection接口的方法。
      2) AbstractList
         继承AbstractCollection和List，并实现大部分List接口的方法。
      3) AbstractSequentialList
         继承AbstractList，提供对集合元素的链式访问而不是随机访问。
      4) LinkedList
         链式数据结构的列表，非线性安全。
         - 特点
           1) 检索效率低
           2) 插入、删除效率高
         - 线性安全改造
           #+BEGIN_EXAMPLE java
           List<String> unsafeList = new LinkedList();
           List<String> safeList = Collections.synchronizedList(unsafeList);
           #+END_EXAMPLE
      5) ArrayList
         大小可变的数组，非线性安全。
         - 特点
           1) 检索效率高
           2) 插入、删除效率低
         - 线性安全改造
           #+BEGIN_EXAMPLE java
           List<String> unsafeList = new LinkedList();
           List<String> safeList = Collections.synchronizedList(unsafeList);
           #+END_EXAMPLE
      6) Vector
         继承AbstractList
      7) Stack
         继承Vector，提供一组遵循FILO操作集合
      8) AbstractSet
         继承AbstractCollection和Set，并实现大部分Set接口的方法。
      9) HashSet
         存储一组唯一、无序的元素。         
      10) LinkedHashSet
          具有可预知迭代顺序的Set接口的hash和linkedlist的实现
      11) TreeSet
          提供排序等功能
      12) AbstractMap
          集成Map接口，实现大部分Map的方法
      13) HashMap
          继承AbstractMap，根据键的HashCode值存储数据，检索效率高，非线性同步
      14) Hashtable
          继承AbstractMap，根据键的HashCode值存储数据，检索效率高，线性同步
      15) SortedMap
          继承Map接口，标识提供排序功能
      16) TreeMap
          继承SortedMap，实现排序等功能
      17) WeakHashMap
          继承AbstractMap，使用弱密钥的哈希表
      18) LinkedHashMap
          继承HashMap，对键按自然顺序来排序
      19) IdentityHashMap
          继承AbstractMap，比较时采用引用相等来比较。
   3) 算法
      作为 ~java.util.Collections~ 和 ~java.util.Arrays~ 静态方法提供。
      1) ~java.util.Arrays~
         - ~Arrays.asList(T... a)~ 将数组转换为大小固定的List实例，若向该List实例添加元素则会抛异常UnsupportedOperationException
      2) ~java.util.Collections~

** ConcurrentHashMap

* TODO 迭代器
  实现Iterator或ListIteractor(继承Iterator，允许双向遍历列表和修改元素)接口

** 使用示例
   #+BEGIN_EXAMPLE java
   Map<String, String> map = new HashMap<String, String>();
   
   // 遍历键
   for (String key : map.keySet()){}
   // 遍历值
   for (String key : map.valueSet()){}

   // 使用Iterator实例
   Iterator<Map.Entry<String, String>> it = map.entrySet().iterator();
   while (it.hasNext()){
     Map.Entry<String, String> entry = it.next();
     System.out.printf("key: %s, value: %s", entry.getKey(), entry.getValue());
   }
   // 或
   for (Map.Entry<String, String> entry : map.entrySet()){
     System.out.printf("key: %s, value: %s", entry.getKey(), entry.getValue());
   }
   #+END_EXAMPLE
  
* TODO 比较器
  Comparator 和 Comparable

* TODO 注解
* TODO 打包发布
  jar、ear和war的差别
* TODO 反射
Class类(类型类)，即所有Java类型的均为Class类的实例。连8种基本数据类型和void类型，都是Class类的实例。
#+BEGIN_EXAMPLE java
public Class{
  private Class(ClassLoader classLoader);
}
#+END_EXAMPLE
获取方式
1) ~类名.class~
2) ~实例.getClass()~
3) ~Class.forName("全限定类名")~ ， 通过类加载器加载获取，前提是相关的class文件在classpath下。

** 示例
- 反射的对象
  #+BEGIN_EXAMPLE java
  package com.john;
  
  public interface Animal{}
  
  public class User{
    public String say(String suffix){
      return "User: " + suffix;
    }
  }
  
  public class Student extends User implements Animal{
    private String name;
    public int age;
  
    public void getName(){
      return this.name;
    }
  
    private void setName(String name){
      this.name = name;
    }
  
    public static final String JOB = "student";
    public static String GET_JOB(){
      return JOB:
    }
  
    public Student(){
    }
  
    public Student(String name, int age){
      this.name = name;
      this.age = age;
    }
  
    @Override
    public String say(String suffix){
      return "Student: " + suffix;
    }
  }
  #+END_EXAMPLE
- 反射操作  
  #+BEGIN_EXAMPLE java
  // 获取全限定类名
  Student student = new Student();
  student.getClass().getName(); // 返回com.john.Student
  
  // 3种获取Class类实例的方法
  Class<?> cObj1 = Student.class;
  Class<?> cObj2 = student.getClass();
  Class<?> cObj3 = Class.forName("com.john.Student");

  // 实例化
  Student student1 = (Student)cObj1.newInstance(); // 调用无参构造方法
  Student student2 = (Student)cObj1.newInstance("john", 25); // 调用含参构造方法
  
  // 获取接口的Class类实例
  Class<?>[] interfaces = cObj1.getInterfaces();

  // 获取父类的Class类实例
  Class<?> superClass = cObj1.getSuperclass();

  // 获取所有构造方法
  Constructor<?>[] cs = cObj1.getConstructors();
  
  // 获取当前类(不含父类和接口)所有方法(包含public、protected、default、private)
  Method[] fs = cObj1.getDeclaredMethods(); 
  // 获取当前类及从父类继承而来的所有公共方法
  Method[] fs1 = cObj1.getMethods();
  for (Method f : fs){
    // 获取方法名称
    String functionName = f.getName();
    // 获取方法修饰符
    Modifier<?>[] ms = f.getModifiers();
    String modifierNames = Modifier.toString(ms); // 方法所有修饰符组成的字符串
    // 获取方法入参列表类型
    Class<?>[] parameterTypes = f.getParameterTypes();
    // 获取方法声明抛出的异常
    Class<?>[] exceptionTypes = f.getExceptionTypes();
  }

  // 获取当前类(不含父类和接口)所有属性(包含public、protected、default、private)
  Field[] fields = cObj1.getDeclaredFields();
  // 获取当前类及从父类继承而来的所有公共属性
  Field[] fields1 = cObj1.getFields();

  // 调用实例方法
  Method mSay = cObj1.getDeclaredMethod("say", String.class);
  String ret = (String) mSay.invoke(student, "Hello"); // 输出 Student: Hello

  // 调用静态方法
  Method mGetJob = cObj1.getMethod("GET_JOB");
  String ret1 = (String) mGetJob.invoke(null);
  
  // 访问privat字段
  Field field = cObj1.getDeclaredField("name");
  field.setAccessible(true); // 私有成员字段必须暴力反射后才能读写
  field.set(student, "set by reflect");
  String name = (String)field.get(student);

  // 操作数组
  Integer[] array = [1,2,3];
  Class<?> clazz = array.getClass();
  if (clazz.isArray()){
    System.out.println("is array");
  }
  // 获取数组元素数据类型
  Class<?> componentClazz = array.getClass().getComponentType();
  // 实例化
  Object newArray = Array.newInstance(componentClazz, 10);
  Integer len = Array.getLength(newArray);
  System.arraycopy(array, 0, newArray, 0, len);
  #+END_EXAMPLE

     
* TODO JNI

* 文档注释
  | 标签          | 说明                                               |
  |---------------+----------------------------------------------------|
  | @author       | 作者                                               |
  | @deprecated   | 指定类或成员已过期                                 |
  | {@docRoot}    | 指定当前文档的根目录                               |
  | @exception    | 指定抛出的异常                                     |
  | {@inheritDoc} | 从直接父类即成的注释                               |
  | {@link}       | 插入一个引用另一个主题的链接                       |
  | {@linkplain}  | 插入一个引用另一个主题的链接，但以纯文本形式显示   |
  | @param        | 方法参数                                           |
  | @return       | 方法返回值                                         |
  | @see          | 指定一个到另一个主题的链接                         |
  | @serial       | 说明一个序列化属性                                 |
  | @serialData   | 说明通过writeObject()和writeExternal()方法写的数据 |
  | @serialField  | 说明一个ObjectStreamField组件                      |
  | @since        | 标记什么时候引入一个特定的变化                     |
  | @throws       | 和@exception一样                                   |
  | {@value}      | 说明常量的值，该常量必须是static属性               |
  | @version      | 版本号                                             |

  然后通过命令 ~javadoc~ 生成文档。
** 示例
   #+BEGIN_EXAMPLE java
   /***
   * @author huangza
   * @version 0.1.0
   */
   public class Box<String>{
     /**
     * @param a string one.
     * @param b string one.
     * @return concatenate string.
     * @exception IOException
     * @see IOException
     */
     public String concat(String a, String b){
       return a + b;
     }
   }
   #+END_EXAMPLE

* JNDI(Java Naming and Directory Interface)
  是一组在Java中访问命名和目录服务的API，作为J2EE的核心技术之一。
  1) 命名服务
     将名称和对象联系起来，让我们可以通过名称访问对象。
  2) 目录服务
     基于命名服务上作增强，使得对象不仅有名称还有属性。
  
  JNDI组成
  1) 应用编程接口(API)
  2) Naming Manager
  3) 服务提供者接口(SPI,Service Provider Interface)
  4) LDAP服务提供者、NIS服务提供者、文件系统服务提供者等

  优点：通过名称引用Java对象或资源，而不必知道对象或资源的物理位置。
   
  JNDI现在可访问的命名和目录服务有
  1) DNS
  2) XNam
  3) Novell目录服务
  4) LDAP
  5) CORBA对象服务
  6) 文件系统
  7) Windows的注册表
  8) RMI
  9) DSML v1&v2
  10) NIS
  
  在J2EE环境下，JNDI的主要用途
  1) 获得Java事务API中的UserTransaction接口的引用
  2) 获得如JDBC、JMS等连接到资源工厂
  3) 在EJB组件中，查找其他EJB组件

  JNDI的概念
  1) Atomic Name(原子名)
     不可分割的名字，如/ETC/FSTAB中的ETC和FSTAB均为Atomic Name
  2) Compound Name(复合名)
     由0或多个Atomic Name组成，如/ETC/FSTAB就是Compound Name
  3) Binding(绑定)
     名字和对象或资源的关联
  4) Context(上下文)
     包含0或多个Binding，如java/MySql中java为Context，而MySql为名字，整体和某个对象或资源关联起来了
  5) Subcontext(子上下文)
     上下文的上下文，如java/ejb/helloBean中ejb为Subcontext
  6) 命名系统
     构成命名空间定义的语法语义
  7) 命名空间
     根据命名系统的语法约定由原子名、复合名、上下文构成的结构，如文件系统的命名空间由目录和文件名组成
  8) 合成名
     由多个命名系统组成的名字，如URL ~http://java.sun.com/product/index.html~
     1) http来自URL scheme-id命名系统
     2) java.sum.com来自DNS命名系统
     3) product、index.html来自文件系统的命名系统

** 工具包
   - ~javax.naming~ 提供访问命名服务的类和接口
     - Context 命名服务操作的入口
   - ~javax.naming.directory~ 对 ~javax.naming~ 扩充，提供访问目录服务的功能
     - DirContext 目录服务操作的入口
   - ~javax.naming.event~ 对访问命名和目录服务提供事件通知的支持
     - NamingEvent 命名或目录服务产生的事件
     - NamingListener 事件监听
   - ~javax.naming.ldap~ 提供对LDAPv3扩展操作和控件的支持
     - LdapContext LDAP目录服务操作的入口
   - ~javax.naming.spi~ 允许动态插入不同实现。为有兴趣创建服务提供者的开发者提供的。

** LDAP(Light Directory Access Protocol)
   相当于简易版本的RDBMS，以树状的层次结构存储数据，适用于读多写少的场景。（优化过读取操作）
   
*** 概念
    1) DN(Distinguished Name)
       标记记录路径的唯一标识。其中Base DN为基准DN，即从哪个DN开始搜索(搜索范围分为One Level和Subtree)。而RDN为叶子节点本身的标识。
    2) DC(Domain Component)
       记录所属区域
    3) OU(Organization Unit)
       组织单元
    4) CN/UID
       记录的名字
   
*** 运维工具
    1) GUI查看工具 —— Free LDAP Browser
   
*** TODO 示例

* 单元测试
  
** JUnit3
   针对JDK1.5之前不支持注解的版本
   #+BEGIN_EXAMPLE java
   public class AppTest extends TestCase{
     public AppTest(){
       // 执行BeforeClass的逻辑
     }
   
     @Override
     protected void setUp() throws Exception{
       // 每个testXxx执行前执行
     }

     @Override
     protected void tearDown() throws Exception{
       // 每个testXxx执行后执行
     }

     // 方法名必须以test开头，标识该方法为testcase
     public void testXxx() throws Exception{
       assertTrue(true);
     }
   }
   #+END_EXAMPLE

** JUnit4
   针对JDK1.5之后支持注解的版本
   #+BEGIN_EXAMPLE java
   public class AppTest{
     // 在所有测试用列和所有@Before标识的方法执行前执行一次
     @BeforeClass
     public static void beforeClass() throws Exception{}

     // 在所有测试用列和所有@After标识的方法执行后执行一次
     @AfterClass
     public static void afterClass() throws Exception{}
     
     @Before
     public void setUp() throws Exception{}

     @After
     public void tearDown() throws Exception{}

     /***
     * 1. 测试用例方法名没有限制，但约定俗成还是以test开头
     * 2. 必须为public void且参数列表必须为空
     */
     @Test
     public void testXxx() throws Exception{
       assertTrue(true);
     }

     // 期望该测试用例在400毫秒内执行完成
     @Test(timeout=400)
     public void testBbb() throws Exception{
     }

     // 期望该测试用例抛出ArithmeticExceptrion异常
     @Test(excepted=ArithmeticExceptrion.class)
     public void testAaa() throws ArithmeticExceptrion{
     }

     @Test
     @Ignore // 忽略该测试用例
     public void testCcc() throws Exception{}
   }
   #+END_EXAMPLE

*** 测试套件(TestSuite)
    将多个类定义的TestCase纳入TestSuite中，那么就可一次性运行多个类中的TestCase。
    #+BEGIN_EXAMPLE java
    @RunWith(Suite.class) // 指定测试运行器为Suite.class
    @Suite.SuiteClasses({AppTest.class, TaskTest.class}) // 包含TestCase类或其他TestSuite类
    public class AppSuite(){}
    #+END_EXAMPLE

*** 参数化测试
    用于对某方法在多种场景下进行测试。
    #+BEGIN_EXAMPLE java
    // 指定测试运行器为Suite.class
    @RunWith(Parameterized.class)
    public class AppTest {
      // 场景参数
      int a;
      int b;
      
      // 通过@Parameters标记返回值为Collection的静态方法来设置场景参数生成方法
      @Parameters
      public static Collection<int[]> init(){
        return Arrays.asList(new int[][]{
          {1,2},
          {3,4},
          {5,6}
        });
      }
      
      // 必须定义带参数的构造方法来构造特定场景的测试用例
      public AppTest(int a, int b){
        this.a = a;
        this.b = b;
      }
      
      @Test
      public void testXxx(){
        assertEquals(this.a, this.b);
      }
    }
    #+END_EXAMPLE

** TODO JUnit5
   包含JUnit Jupiter、JUnit Platform和JUnit Vintage。
   https://www.ibm.com/developerworks/cn/java/j-introducing-junit5-part1-jupiter-api/index.html

** 断言库

* Java8新特性
  
** Lambda表达式

** 方法引用

** 函数式接口

** 默认方法

** 新工具

** Stream API

** Date Time API

** Optional类

** Nashorn JavaScript引擎

** Base64

* QA
1) CopyOnWrite
2) 泛型
3) 线程池
4) CAS
5) AQS
6) JVM
7) 实现java.io.Serializable接口的类需要定义 ~private static final long serialVersionUID~ ?
 

