JDBC(Java Database Connectivity)，是一个独立于特定数据库管理系统的、通用的SQL数据库存取和操作的公共接口，具体实现类由各RDBMS厂商提供。

* 概要
  JDBC接口组成：
  1) JDBC API
     抽象接口，供应用开发人员使用(连接数据库、执行SQL语句、获取结果)
  2) JDBC Driver Manager
  3) JDBC Driver API
     供SQL数据库厂商开发数据库驱动程序用。
     ~java.sql.Driver~ 是所有驱动程序必须实现的接口，当在应用程序不必要直接使用 ~java.sql.Driver~ ，而是使用 ~java.sql.DriverManager~ 去调用具体的Driver实现。
     - JDBC驱动程序分为4种类型
       1) JDBC-ODBC桥
          把JDBC API调用转换为ODBC API调用，然后ODBC API调用数据库厂商的ODBC驱动程序操作数据库。
          - 组成: *JDBC ODBC Bridge Driver* -> *ODBC API* -> *DB Client Lib*
       2) 部分本地API+部分Java的驱动程序
          本地API把JDBC API调用转换直接对数据库的标准调用，需要安装本地数据库驱动。
          - 组成: *Partial Java JDBC Driver* -> *DB Client Lib*
       3) JDBC网络的纯Java驱动程序(具有性能、可移植性、功能上的优势)
          使用一种数据库无关的协议，将操作请求发送到中间服务器，由中间服务器再去操作数据库。
          - 组成: *Pure Java JDBC Driver* -> *DB Middleware Server*
       4) 本地协议的纯Java驱动程序(具有性能、可移植性、功能上的优势)
          完全由Java编写，JDBC驱动程序通过与数据库建立的Socket连接，采用具体厂商网络协议把JDBC调用转换为直接连接的网络调用。
          - 组成: *Pure Java JDBC Driver*
  
  JDBC URL: 用于标识一个被注册的驱动程序，驱动程序管理通过JDBC URL选择正确的驱动程序，从而建立到数据库的连接。
  JDBC URL由3部分组成，各部分用冒号(:)分隔。
  1) 协议: JDBC URL中的协议均为jdbc
  2) 子协议: 子协议用于标识一个数据库驱动程序，如mysql,oracle等
  3) 子名称: 依赖子协议而变化，用于定位数据库服务位置
  
  示例：
  1) Oracle: ~jdbc:oracle:thin:@localhost:1521:sid~
     - Oracle的JDBC URL存在3种形式
       1) thin using an SID
          - 格式: ~jdbc:oracle:thin:@host:port:SID~
          - 示例: ~jdbc:oracle:thin:@127.0.0.1:1521:orcl~
          - 通过如下语句获取SID
            #+BEGIN_EXAMPLE sql
            -- 以sysdba身份登入
            select value from v$parameter where name='instance_name';
            #+END_EXAMPLE
       2) thin using a ServiceName
          对于集群而言各数据库的SID均不相同，但采用相同的ServiceName。
          - 格式: ~jdbc:oracle:thin:@host:port/service_name~
          - 示例: ~jdbc:oracle:thin:@127.0.0.1:1521/orcl.city.com~
          - 通过如下语句获取ServiceName
            #+BEGIN_EXAMPLE sql
            -- 以sysdba身份登入
            select value from v$parameter where name='service_name';
            #+END_EXAMPLE
       3) thin using a TNS Name
          - 格式: ~jdbc:oracle:thin:@TNSName~
          - 示例: ~jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=orcl.city.com)))~
     - 驱动程序
       - JDK1.5 —— ojdbc5.jar
       - JDK1.6/1.7/1.8 —— ojdbc6.jar
       - 若已经安全Oracle服务端或客户端，则从 ~$ORACLE_HOME/jdbc/lib~ 获取驱动程序即可
  2) SQLServer: ~jdbc:microsoft:sqlserver//localhost:1433;DatabaseName=sid~
  3) MySQL: ~jdbc:mysql://localhost:3306/sid~
  
  示例
  1) 直接使用 ~java.sql.Driver~
     #+BEGIN_EXAMPLE java
     public static void main(String[] args) {
       Driver driver = new com.mysql.jdbc.Driver();
  
       String jdbcUrl = "jdbc:mysql://127.0.0.1:3306/test";
       Properties props = new Properties();
       props.put("user", "root");
       props.put("password", "123");
       
       Connection conn = driver.connect(jdbcUrl, props);
     }
     #+END_EXAMPLE
  2) 通过反射使用 ~java.sql.Driver~
     #+BEGIN_EXAMPLE java
     public static void main(String[] args){
       InputStream in = getClass().getClassLoader().getResourceAsStream("db.properties");
       Properties props = new Properties();
       props.load(in);
       Connection conn = getConnection(props.getProperty("jdbc.driverClass")
       , props.getProperty("jdbc.jdbcUrl")
       , props.getProperty("jdbc.user")
       , props.getProperty("jdbc.password"));
     }
  
     public static Connection getConnection(String driverClass, String jdbcUrl, String user, String password) throws Exception{
       Driver driver = (Driver) Class.forName(driverClass).newInstance();
       Properties props = new Properties();
       props.put("user", "root");
       props.put("password", "123");
       
       Connection conn = driver.connect(jdbcUrl, props);
       return conn;
     }
     #+END_EXAMPLE
  3) 通过驱动程序管理器 ~java.sql.DriverManager~
     好处：可以注册多个驱动程序，然后通过不同的JDBC URL来获取对应的数据库的驱动程序。
     #+BEGIN_EXAMPLE java
     public static Connection getConnection(String driverClass, String jdbcUrl, String user, String password) throws Exception{
       // 加载数据库驱动程序
       Class.forName(driverClass);
       /*
       * 驱动程序中一般存在静态代码块在加载驱动时自动执行驱动注册到驱动管理器的操作，因此不用在这里手动执行如下代码
       * DriverManager.registerDriver(Class.forName(driverClass).newInstance())
       */
       
       // 通过DriverManager获取Connection实例
       Connection conn = DriverManager.getConnection(jdbcUrl, user, password);
       return conn;
     }   
     #+END_EXAMPLE
  
* 通过Statement执行SQL脚本
  #+BEGIN_EXAMPLE java
  public void execute(String sql){
    Connection conn = null;
    Statement stat = null;
    try{
      conn = getConnection("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3306/test", "root", "123");
      stat = conn.createStatement();
      // 可执行DML
      stat.executeUpdate(sql);
    }
    finally{
      try{
        if(stat != null) stat.close();
      }
      catch(Exception e){}
      try{
        if(conn != null) conn.close();
      }
      catch(Exception e){}
    }
  }

  public List<User> query(String sql){
    List<User> users = new LinkedList<User>();
    Connection conn = null;
    Statement stat = null;
    ResultSet rs = null;
    try{
      conn = getConnection("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3306/test", "root", "123");
      stat = conn.createStatement();
      // 可执行DQL
      rs = stat.executeQuery(sql);

      /***
      * ResultSet为结果集，通过调用实例方法next()判断游标是否到达最后一行，若不是则游标移动到后面一行记录，并返回true。(相当于将Iterator的hasMore()和next()方法组合在一起)
      * 通过实例方法getXxx(int columnIndex)通过列索引或getXxx(String columnLabel)通过列别名获取列值，columnIndex从1开始
      */
      while (rs.next()){
        User user = new User();
        user.setId(rs.getInt(1)); 
        user.setName(rs.getString(2));
        user.setDateCreated(rs.getDate(3));
        users.add(user);
      }

      return users;
    }
    finally{
      try{
        if(rs != null) rs.close();
      }
      catch(Exception e){}
      try{
        if(stat != null) stat.close();
      }
      catch(Exception e){}
      try{
        if(conn != null) conn.close();
      }
      catch(Exception e){}
    }
  }
  #+END_EXAMPLE

* 通过PreparedStatement执行SQL脚本
  ~java.sql.PreparedStatement~ 为 ~java.sql.Statement~ 的派生类。
  优点：
  1) 采用参数绑定形式的SQL脚本，而不是拼接SQL脚本，提高数据库执行SQL脚本的效率；
  2) 自动处理SQL注入问题。
  
  #+BEGIN_EXAMPLE java
  // sql为 insert into user(name, age, datecreated) values(?, ?, ?)
  public void execute(String sql){
    Connection conn = null;
    PreparedStatement stat = null;
    try{
      conn = getConnection("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3306/test", "root", "123");
      /* 
      * 若如MySQL支持数据库自增列，那么通过第二个参数设置为Statemenet.RETURN_GENERATED_KEYS即可，
      * 默认值为Statement.NO_GENERATED_KEYS。
      */ 
      stat = conn.preparedStatement(sql, Statement.RETURN_GENERATED_KEYS);
      stat.setString(1, "john"); // 索引从1开始
      stat.setInt(2, 18);
      stat.setDate(3, new java.sql.Date(new java.util.Date().getTime()));
      // 可执行DML，返回受影响的行数
      int effectedRecordCount = stat.executeUpdate();
      
      // 获取数据库自增列的数据
      ResultSet rs = stat.getGeneratedKeys();
      ResultSetMetaData rsmd = rs.getMetaData();
      int columnCount = rsmd.getColumnCount();
      while(rs.next()){
        for (int i = 0; i < columnCount; i++){
          String name = rsmd.getColumnName(i+1); // 列名为 GENERATED_KEY
          Object value = rs.getObject(i+1);
          System.out.printf("%s: %s %n");
        }
      }
    }
    finally{
      try{
        if(stat != null) stat.close();
      }
      catch(Exception e){}
      try{
        if(conn != null) conn.close();
      }
      catch(Exception e){}
    }
  }

  // sql为 select * from user where name = ? or age > ?
  public List<User> query(String sql){
    List<User> users = new LinkedList<User>();
    Connection conn = null;
    PreparedStatement stat = null;
    ResultSet rs = null;
    try{
      conn = getConnection("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3306/test", "root", "123");
      stat = conn.preparedstatement(sql);
      stat.setString(1, "john");
      stat.setInt(2, 18);
      // 可执行DQL
      rs = stat.executeQuery();

      /***
      * ResultSet为结果集，通过调用实例方法next()判断游标是否到达最后一行，若不是则游标移动到后面一行记录，并返回true。(相当于将Iterator的hasMore()和next()方法组合在一起)
      * 通过实例方法getXxx(int columnIndex)通过列索引或getXxx(String columnLabel)通过列别名获取列值，columnIndex从1开始
      */
      while (rs.next()){
        User user = new User();
        user.setId(rs.getInt(1)); 
        user.setName(rs.getString(2));
        user.setDateCreated(rs.getDate(3));
        users.add(user);
      }

      return users;
    }
    finally{
      try{
        if(rs != null) rs.close();
      }
      catch(Exception e){}
      try{
        if(stat != null) stat.close();
      }
      catch(Exception e){}
      try{
        if(conn != null) conn.close();
      }
      catch(Exception e){}
    }
  }
  #+END_EXAMPLE

** 利用反射封装结果集
   #+BEGIN_EXAMPLE java
   public <T> T query(Class<T> clazz, String sql, Object[] args){
    T entity = null;
    Connection conn = null;
    PreparedStatement stat = null;
    try{
      conn = getConnection("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3306/test", "root", "123");
      stat = conn.preparedstatement(sql);
      for (int i = 0; i < args.length; i++){
        stat.setObject(i+1, args[i]);
      }

      // 可执行DQL
      ResultSet rs = stat.executeQuery();

      /***
      * ResultSetMetaData实例方法
      * getColumnLabel(int columnIndex):String 返回指定列的别名
      * getColumnCount():Intger 返回结果集每行的列数
      * getColumnTypeName(int columnIndex):String 返回指定列的数据库特定的类型名称
      * getColumnDisplaySize(int columnIndex):Intger 返回指定列的最大标准宽度，单位为字符
      * isNullable(int columnIndex):boolean 表示指定列是否可为空
      * isAutoIncrement(int columnIndex):boolean 指示指定列是否自动编号，这样该列只允许读操作
      */
      ResultSetMetaData rsmd = rs.getMetaData();

      if (rs.next()){
        entity = clazz.newInstance();
        for (int i = 0; i < rsmd.getColumnCount(); i++){
          String label = rsmd.getColumnLabel(i + 1);
          Object val = rs.getObject(i + 1);
          // 利用Apache的BeanUtils操作
          BeanUtils.setProperty(entity, label, val);
        }
      }

      return entity;
    }
    finally{
      try{
        if(stat != null) stat.close();
      }
      catch(Exception e){}
      try{
        if(conn != null) conn.close();
      }
      catch(Exception e){}
    }     
   }
   #+END_EXAMPLE

* DAO(Data Access Object)
  指仅仅包含操作数据库的逻辑(CRUD)，而不包含业务相关逻辑。

* 通过JDBC驱动处理元数据
  #+BEGIN_EXAMPLE java
  /***
   * getURL():String 返回数据库的URL字符串
   * getUserName():String 返回当前数据库用户名
   * isReadOnly():boolean 表示数据库是否只允许读操作
   * getDatabaseProductName():String 返回数据库的产品名称
   * getDatabaseProductVersion():String 返回数据库的版本号
   * getDriverName():String 返回驱动程序名称
   * getDriverVersion():String 返回驱动程序版本号
   * 还能获取数据表、触发器、存储过程等信息
   */
  DatabaseMetaData dmd = conn.getMetaData();
  #+END_EXAMPLE
* 操作LOB
  LOB(Large Object, 大对象)，是一种用来存储大量二进制或文本数据的数据类型(最大容量为4GB)。
  - Oracle分为内部和外部2类LOB
    1) 内部LOB
       以字节流的形式存储在数据库内部，因此可参数事务，和像处理普通数据一样可对其进行备份和恢复擦作。
       3种内部LOB：
       1) BLOB(二进制数据)， 适用于存储如图片、视频、音频等二进制数据
       2) CLOB(单字节字符数据)，适用于存储超长文本数据
       3) NCLOB(多字节字符数据)，适用于存储超长文本数据
    2) 外部LOB
       该类型的数据为只读，不能参与事务，也不能单单通过数据库对其进行备份和恢复。
       1种外部LOB：
       1) BFILE，仅存储数据在操作系统中的位置信息，而数据的实体以外部文件的形式存储在操作系统的文件系统中。
  - MySQL的BLOB分为4种
    1) TinyBlob(最大255B)
    2) Blob(最大65KB)
    3) MediumBlob(最大16MB)
    4) LongBlob(最大4GB)

** 示例
   #+BEGIN_EXAMPLE java
   public void saveBlob(String avatar){
     String sql = "insert into user(uid, avatar) values(?, ?)";
     Connection conn = null;
     PreparedStatement stat = null;
     InputStream in = null
     try{
       conn = getConnection();
       stat = conn.preparedStatement(sql);
       stat.setString(1, "john");
       in = FileInputStream(avatar);
       stat.setBlob(2, in);
       
       stat.executeUpdate();
     }
     finally {
       if (in != null){
         try{
           in.close()
         }
         catch(Exception e){}
       }
       if (stat != null){
         try{
           stat.close()
         }
         catch(Exception e){}
       }
       if (conn != null){
         try{
           conn.close()
         }
         catch(Exception e){}
       }
     }
   }

   public void readBlob(String uid){
     String sql = "select avatar from user where uid = ?";
     Connection conn = null;
     PreparedStatement stat = null;

     try{
       conn = getConnection();
       stat = conn.preparedStatement(sql);
       stat.setString(1, uid);

       ResultSet rs = stat.executeQuery();
       while(rs.next()){
         Blob blob = rs.getBlob(1);
         InputStream in = blob.getBinaryStream();
         
         OutputStream out = new FileOutputStream("avatar/" + uid + ".jpg");
         byte[] buffer = new byte[1024];
         int len = 0;
         while ((len = in.read(buffer)) != -1){
           out.write(buffer, 0, len);
         }
         
         out.close();
         in.close();
       }
     }
     finally {
       if (in != null){
         try{
           in.close()
         }
         catch(Exception e){}
       }
       if (stat != null){
         try{
           stat.close()
         }
         catch(Exception e){}
       }
       if (conn != null){
         try{
           conn.close()
         }
         catch(Exception e){}
       }
     }
   }
   #+END_EXAMPLE

* 事务
  #+BEGIN_EXAMPLE java
  public void doIt(){
    Connection conn = getConnection();
    
    try{
      // 事务开始前，取消默认的自动提交设置
      conn.setAutoCommit(false);
      
      // 从同一个conn中获取Statement或其派生类执行数据库操作
  
      // 执行正常时进行事务提交操作
      conn.commit();
    }
    catch (Exception e){
      try{
        // 执行异常则进行事务回滚操作
        conn.rollback();
      }
      catch(SQLException e){}
    }
  }
  #+END_EXAMPLE

** 事务隔离级别
   | 隔离级别        | 描述                                                                                                                |
   |-----------------+---------------------------------------------------------------------------------------------------------------------|
   | READ UNCOMMITED | 允许事务读取其它事务未提交的变更。存在脏读、不可重复读和幻读的问题                                                  |
   | READ COMMITED   | 只允许事务读取其它事务已经提交的变更。存在不可重复读和幻读的问题                                                    |
   | REPEATABLE READ | 在事务持续期间，通过禁止其它事务对指定字段提交变更(CUD)，从而确保该事务可以从该字段重复读取相同的值。存在幻读的问题 |
   | SERIALIZABLE    | 在事务持续期间，通过禁止其它事务对指定表提交变更(CUD)，从而确保该事务可以从该表重复读取相同的行数。                 |

   Oracle支持 ~READ COMMITED~ (默认) 和 ~SERIALIZABLE~ 2种事务级别
   MySQL支持全部，默认为 ~REPEATABLE READ~
  
   #+BEGIN_EXAMPLE java
   Connection conn = getConnection();
   /*
   * Connection.TRANSACTION_NONE
   * Connection.TRANSACTION_READ_UNCOMMITED
   * Connection.TRANSACTION_READ_COMMITED
   * Connection.TRANSACTION_REPEATABLE_READ
   * Connection.TRANSACTION_SERIALIZABLE
   */
   conn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITED);
   #+END_EXAMPLE

* 批量操作
  ~Statement实例.addBatch(String sql)~ 或 ~PreparedStatement实例.addBatch()~, 添加需要批量处理的SQL语句
  ~Statement实例.executeBatch()~, 执行批量处理语句
  ~Statement实例.clearBatch()~, 清理上一批次通过 ~addBatch~ 添加的批量处理SQL语句，从而添加下一批次的批量处理语句
  
  批量的场景：
  1) 多条SQL语句的批量处理
  2) 一条SQL语句的批量处理

** 示例
   #+BEGIN_EXAMPLE java
   Connection conn = getConnect();
   PreparedStatement stat = conn.preparedStatement(sql);
  
   for (int i = 0; i < 100000; i++){
     stat.setString(1, "test" + 1);
    
     // 逐条执行
     // stat.executeUpdate();

     // 批量执行
     stat.addBatch();
   }

   stat.executeBatch();
   stat.clearBatch();
   #+END_EXAMPLE

* 数据库连接池
  ~javax.sql.DataSource implements CommonDataSource~ 接口定义连接池规范，通常由服务器(Weblogic,WebSphere,Tomcat等)提供实现，也有一些开源组织提供的实现：
  1) DBCP
  2) C3P0
  3) HikariCP
     运用字节码作优化
  4) AlibabaDruid

  DataSource通常被称为数据源，包含连接池和连接池管理器两部分。

** Commons DBCP示例
   1) 代码配置
      #+BEGIN_EXAMPLE java
      BasicDataSource dataSource = new BasicDataSource();
      dataSource.setUsername("root");
      dataSource.setPassword("123");
      dataSource.setUrl("jdbc:mysql://127.0.0.1/hello");
      dataSource.setDriverClassName("com.mysql.jdbc.Driver");   

      // 设置初始化连接数
      dataSource.setInitialSize(10);
      // 设置最大连接数
      dataSource.setMaxActive(50);
      // 设置空闲时至少保持的连接数
      dataSource.setMinIdle(5);
      // 等待连接池分配连接的最大等待毫秒数，超过则抛出异常
      dataSource.setMaxWait(1000 * 5);

      Connection conn = dataSource.getConnection();
      #+END_EXAMPLE
   2) properties配置
      #+BEGIN_EXAMPLE java
      InputStream in = getClass().getClassLoader().getResourceAsStream("db.properties");
      Properties props = new Properties();
      props.load(in);
      BasicDataSource ds = BasicDataSourceFactory.createDataSource(props);
      #+END_EXAMPLE
      #+BEGIN_EXAMPLE ini
      username=
      password=
      driverClassName=
      url=
      
      initialSize=
      maxActive=
      minIdle=
      maxWait=
      #+END_EXAMPLE

** C3P0示例
   1) 代码配置
      #+BEGIN_EXAMPLE java
      ComboPooledDataSource dataSource = new ComboPooledDataSource();
      dataSource.setUser("root");
      dataSource.setPassword("123");
      dataSource.setJdbcUrl("jdbc:mysql://127.0.0.1/hello");
      dataSource.setDriverClassName("com.mysql.jdbc.Driver");   

      Connection conn = dataSource.getConnection();
      #+END_EXAMPLE
   2) properties配置
      #+BEGIN_EXAMPLE java
      ComboPooledDataSource dataSource = new ComboPooledDataSource("helloc3p0"); // 在配置文件中匹配name特性值相同的named-config的配置。
      Connection conn = dataSource.getConnection();
      #+END_EXAMPLE
      #+BEGIN_EXAMPLE xml
      <!-- 文件名为c3p0-config.xml，即会自动被搜索到并加载 -->
      <c3p0-config>
        <named-config name="helloc3p0">
          <property name="user">root</property>
          <property name="password">123</property>
          <property name="driverClass">com.mysql.jdbc.Driver</property>
          <property name="jdbcUrl">jdbc:mysql://localhost:123/test</property>
          
          <!-- 若数据连接池的连接数不足时，一次性向服务器申请的连接数 -->
          <property name="acquireIncrement">50</property>
          <property name="initialPoolSize">100</property>
          <property name="minPoolSize">50</property>
          <property name="maxPoolSize">1000</property>
          <!-- C3P0数据库连接池可以维护的Statement个数 -->
          <property name="maxStatements">0</property>
          <!-- 每个连接同时可以使用的Statement对象的个数 -->
          <property name="maxStatementsPerConection">5</property>
        </named-config>
      </c3p0-config>
      #+END_EXAMPLE
   
* Apache DBUtils
对JDBC的简单封装，极大地简化JDBC编码的工作量。
API:
- ~org.apache.commons.dbutils.QueryRunner~
  #+BEGIN_EXAMPLE java
  Connection conn = getConnection();
  String sql = "delete from user where id in (?, ?)";
  QueryRunner runner = new QueryRunner();
  try{
    runner.update(conn, sql, 11, 22);
  }
  catch (Exception e){
    e.printStackTrace();
  }
  finally {
    if (conn != null){
      try{
        conn.close();
      }
      catch (Exception e){}
    }
  }
  #+END_EXAMPLE
- ~org.apache.commons.dbutils.ResultSetHandler~
  #+BEGIN_EXAMPLE java
  Connection conn = getConnection();
  String sql = "select * from user where id = ?";
  QueryRunner runner = new QueryRunner();
  try{
    User user = runner.query(conn, sql, new org.apache.commons.dbutils.handler.BeanHandler(User.class), 11);
    // List<User> users = runner.query(conn, sql, new org.apache.commons.dbutils.handler.BeanListHandler(User.class), 11);
  }
  catch (Exception e){
    e.printStackTrace();
  }
  finally {
    if (conn != null){
      try{
        conn.close();
      }
      catch (Exception e){}
    }
  }
  #+END_EXAMPLE
- 工具类 ~org.apache.commons.dbutils.DbUtils~
 
* 调用存储过程/函数
  #+BEGIN_EXAMPLE java
  public void callFunction(){
    // 第一个参数为返回值
    // 第二个参数为IN类型的参数
    // 第三个参数为OUT类型或IN OUT类型的参数
    String sql = "{?= call function_name[(?, ?)]}";
    Connection conn = null;
    CallableStatement stat = null;
    
    try{
      conn = getConnection();
      stat = conn.preparedCall(sql);
      // 通过registerOutParameter方法注册 返回值、OUT参数或IN OUT参数
      stat.registerOutParameter(1, java.sql.Types.NUMERIC);
      stat.registerOutParameter(3, java.sql.Types.NUMERIC);      
      // 通过setXxx方法注册 IN参数
      // 通过setNull方法注册null值作为参数值
      stat.setString(2, "john");
      
      // 执行数据库操作
      stat.execute();

      // 通过getXxx方式获取返回值、OUT参数或IN OUT参数的值
      double result1 = stat.getDouble(1);
      double result3 = stat.getDouble(3);
    }
    catch(Exception e){
      e.printStackTrace();
    }
    finally {
      if (stat != null){
        try{
          stat.close();
        }catch(Exception e){}
      }
      if (conn != null){
        try{
          conn.close();
        }catch(Exception e){}
      }
    }
  }
  public void callProcedure(){
    String sql = "{call procedure_name[(?, ?)]}";

    // 第一个参数为IN类型的参数
    // 第二个参数为OUT类型或IN OUT类型的参数
    String sql = "{call procedure_name[(?, ?)]}";
    Connection conn = null;
    CallableStatement stat = null;
    
    try{
      conn = getConnection();
      stat = conn.preparedCall(sql);
      // 通过registerOutParameter方法注册 返回值、OUT参数或IN OUT参数
      stat.registerOutParameter(2, java.sql.Types.NUMERIC);
      // 通过setXxx方法注册 IN参数
      // 通过setNull方法注册null值作为参数值
      stat.setString(1, "john");
      
      // 执行数据库操作
      stat.execute();

      // 通过getXxx方式获取OUT参数或IN OUT参数的值
      double result1 = stat.getDouble(2);
    }
    catch(Exception e){
      e.printStackTrace();
    }
    finally {
      if (stat != null){
        try{
          stat.close();
        }catch(Exception e){}
      }
      if (conn != null){
        try{
          conn.close();
        }catch(Exception e){}
      }
    }
  }
  #+END_EXAMPLE
