JAR，用于Java程序发布的包
WAR，用于网站发布的包
[[http://maven.apache.org/][官网]]

* TODO Ant,Maven和Gradle对比

* 依赖下载流程
1) 本地仓库
2) 默认中央仓库(http://repo1.maven.org/maven2/)
3)
4) 在pom.xml中自定义的远程仓库私有仓库(代理公共中央仓库)

* Maven配置
  配置文件路径: ~$MAVEN_HOME/conf/setting.xml~
  - 配置远程仓库
    1) 在 ~$MAVEN_HOME/conf/setting.xml~ 或 ~$LOCAL_REPOSITORY/setting.xml~ 中设置
       - 规则
         1) 一个respository最多配置一个mirror
       - 示例
       #+BEGIN_EXAMPLE xml
       <!-- 设置远程仓库的镜像信息 -->
       <mirrors>
         <mirror>
           <!-- 唯一标识，Maven将id值按字母表顺序查询依赖 -->
           <id>alimaven</id>
           <!-- 仓库描述 -->
           <name>aliyun maven</name>
           <!-- 仓库地址 -->
           <url>https://maven.aliyun.com/repository/central</url>
           <!-- 设置表达式匹配请求哪些仓库时则使用该mirror配置
                * 匹配所有仓库请求，当搭建私有仓库时通常使用*匹配所有仓库请求
                repo1,repo2 配置repo1或repo2仓库
                *, !repo1 配置除repo1外的其它所有仓库
                external:* 配置所有非本地的仓库
             -->
           <mirrorOf>central</mirrorOf>
         </mirror>
       </mirrors>
       <!-- 设置远程仓库的帐号密码 -->
       <servers>
         <server>
           <id>alimaven</id>
           <username></username>
           <password></password>
         </server>
       </servers>

       <profile>
       </profile>
       #+END_EXAMPLE
    2) 在项目的 ~pom.xml~ 中设置
       #+BEGIN_EXAMPLE xml
       <project>
         <repositories>
           <repository>
             <!-- 唯一标识，Maven将id值按字母表顺序查询依赖 -->
             <id>alimaven</id>
             <!-- 仓库描述 -->
             <name>aliyun maven</name>
             <!-- 仓库地址 -->
             <url>https://maven.aliyun.com/repository/central</url>
           </repository>
         </repositories>
       </project>
       #+END_EXAMPLE
  - 配置下载依赖的源码和javadoc
    #+BEGIN_EXAMPLE xml
    <profiles>
      <profile>
        <id>downloadSources</id>
        <properties>
          <downloadSources>true</downloadSources>
          <downloadJavadocs>true</downloadJavadocs>
        </properties>
      </profile>
    </profiles>
    <activeProfiles>
      <activeProfile>downloadSources</activeProfile>
    </activeProfiles>
    #+END_EXAMPLE

* 项目结构
  #+BEGIN_EXAMPLE yml
  pom.xml
  src/
    - main/
      - java/ Java源码目录
      - resources/ 资源目录
      - filters/ 资源过滤目录
      - assembly/ Assembly descriptors
      - config/ 配置文件目录
      - webapp/ 网页源码目录
    - test
      - java/
      - resources/
      - filters/
  target/ 输出目录
  #+END_EXAMPLE

* Version规范
~<major>.<minor>.<incremental>-<qualifier>~
~<qualifier>~ 中除beta、alpha等值外还有如下值
- SNAPSHOT, 表示不稳定的版本。作为特殊版本号用于告知Maven该工程处于开发阶段，将经常更新和发布，若有其他工程依赖此类型的artifact，那么Maven会在仓库中寻找其最新版本下载使用。
- LATEST, 表示为最新版本。
- RELEASE，表示稳定版。

规范：
1) 同一个项目中所有模块版本保持一致
2) 子模块统一继承父模块的版本
3) 统一在顶层模块POM的 ~<dependencyManagement/>~ 节点中定义所有子模块的依赖版本号，而子模块POM中不添加依赖版本号
4) 开发测试阶段使用SNAPSHOT
5) 生产发布阶段使用RELEASE
6) 新版本迭代只修改顶层的POM版本

Maven遵循“约定优于配置”的策略(convention over configuration)
1) 任务compile，默认从src/main/java下编译所有java文件，并把输出的class文件存放到target/classes中；

** Maven SNAPSHOT(快照)
版本号形如 ~1.0.0-SNAPSHOT~ 的快照版本，用于表示当前项目处于快速开发阶段，Maven仓库中该快照版本对应的构建物将不定时被更新，而依赖该项目的其他项目在每次构建时都必须从Maven仓库中重新下载最新的JAR包。
1) 非SNAPSHOT版本的特点：
   1) 若每次发布新功能都要更新版本号，则需要通知依赖该项目的其他项目更新pom.xml从而下载最新JAR包；
   2) 若每次发布新功能都不更新版本号，则需要通知依赖该项目的其他项目清理已经下载的JAR包，并重新下载
      #+begin_example bash
      # 清理已下载的所有JAR包
      mvn dependency:purge-local-repository
      # 下载依赖并构建、打包项目
      mvn clean package
      #+end_example
2) SNAPSHOT版本的特点：
   每次发布新功能都要不需要更新版本号，也不必通知依赖该项目的其他项目组，他们在每次构建项目时Maven会自动去下载最新版的JAR包。显式要求Maven去下载最新版的SNAPSHOT版本也是可以的 ~mvn clean package -U~ 。

* pom.xml详解
Maven在执行任务或目标时，会在当前目录查找并读取pom.xml，然后根据配置信息执行目标。
pom.xml中包含如下信息
1) 项目依赖
2) 插件
3) 执行目标
4) 项目构建profile
5) 项目版本
6) 项目开发者列表
7) 相关邮件信息

** 模板
#+begin_example xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instane"
         xsi:schemaLoaction="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion> <!-- POM模型版本，当前固定为4.0.0 -->

    <parent>...</parent><!-- 设置父POM -->

    <!-- 1. 公司或组织的唯一标识，并且作为包生成规则。
            如groupId为io.fsjohnhuang.devops，Maven会在src/main/java下执行mkdir -p io/fsjohnhuang/devops

         2. groupId:artifactId:version 统称为POM坐标，例如 io.fsjohnhuang.devops:cmdb:1.0.0-SNAPSHOT
      -->
    <groupId>io.fsjohnhuang.devops</groupId>
    <artifactId>cmdb</artifactId> <!-- 项目的唯一标识 -->
    <version>1.0.0-SNAPSHOT</version> <!-- 项目版本号 -->

    <!-- 打包模式：jar(默认值), war, ear, pom(表示项目仅仅包含了元数据)
         注意：不同的打包模式对应的不同goal和phase绑定关系
      -->
    <packaging>pom</packaging>

    <name></name> <!-- 项目名称，Maven产生文档使用 -->
    <url></url> <!-- 项目主页，Maven产生文档使用 -->
    <description><![CDATA[]]></description> <!-- 项目详细描述，Maven产生文档使用 -->

    <properties>
    </properties>

    <modules></modules> <!-- 模块列表 -->

    <dependencies>
    <!-- 通过POM坐标声明依赖项，并由Maven统一下载更新和管理-->
    </dependencies>

    <dependencyManagers>
    <dependencyManagers>

    <repositories>
    </repositories>
</project>
#+end_example

** Super POM(父 POM)
   所有POM都会继承一个父POM，父POM包含一些可以被继承的设置(目录结构、输出目录、仓库地址、报表目录等)，子POM可覆盖父POM的配置。
   设置父POM的方式
   1) 隐式继承
      若没有显式指定继承父POM，Maven会默认继承effective pom。
      - 查看effective pom的配置信息
        1) 创建工程目录，并创建pom.xml
           #+begin_example xml
           <project xmlns = "http://maven.apache.org/POM/4.0.0"
               xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation = "http://maven.apache.org/POM/4.0.0
               http://maven.apache.org/xsd/maven-4.0.0.xsd">

               <!-- 模型版本 -->
               <modelVersion>4.0.0</modelVersion>
               <!-- 公司或者组织的唯一标志，并且配置时生成的路径也是由此生成， 如com.companyname.project-group，maven会将该项目打成的jar包放本地路径：/com/companyname/project-group -->
               <groupId>com.companyname.project-group</groupId>

               <!-- 项目的唯一ID，一个groupId下面可能多个项目，就是靠artifactId来区分的 -->
               <artifactId>project</artifactId>

               <!-- 版本号 -->
               <version>1.0</version>
           </project>
           #+end_example
        2) 执行 ~mvn help:effective-pom~ 向stdout输出配置信息
   2) 显式继承
      #+begin_example xml
      <parent>
          <groupId></groupId>
          <artifactId></artifactId>
          <version></version>
          <!-- 父POM的相对路径，默认值为../pom.xml。
               父POM的搜索顺序：
               1. 在构建当前项目的目录路径搜索父POM；
                  例如某项目存在子模块
                  - project/
                      - pom.xml
                      - moduleA/
                          - pom.xml
                  那么在目录project下执行mvn，那么project/moduleA/pom.xml的父POM为project/pom.xml。
               2. relativePath指定路径搜索父POM；
               3. 本地仓库中搜索父POM。
          -->
          <relativePath></relativePath>
      </parent>
      #+end_example

** 依赖声明
#+begin_example xml
<dependencies>
  <dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version></version>
    <!--
      compile(默认值)，打包到最终的构建件中
      provided，编译需要，不打包到最终的构建件中。如Spring Boot生成WAR包，而不是包含Tomcat的JAR包，那么Tomcat依赖就需要设置为provided了。又如lombok也是。
      runtime，编译不需要，运行时需要(接口和实现分离)，打包到最终的构建件中。如编译时缺少mysql-connector-java不会失败，但运行时就会失败。。
      test，测试使用，不打包到最终的构建件中。如测试框架。
      system，加载本地jar，不打包到最终的构建件中。
    -->
    <scope></scope>
    <systemPath></systemPath> <!-- 指定scope为system的包路径 -->
    <!--

    -->
    <type></type>
    <optional></optional>

    <exclusions>
      <exclusion>
        <groupId></groupId>
        <artifactId></artifactId>
      </exclusion>
    </exclusions>
  </dependency>
</dependencies>
#+end_example

*** 依赖传递

** 仓库
   3种仓库-本地、中央和远程，搜素下载依赖顺序：
   1) 在本地仓库搜索，若没有则进行第2步；
   2) 若设置远程仓库，则从1个或多个远程仓库搜索，搜索失败或没有设置远程仓库均会进行第3步；
   3) 在中央仓库搜索，若没有则抛出错误。

*** 本地仓库
    - 默认：位于 ~$HOME/.m2/repository~
    - 自定义：通过修改配置文件 ~$MAVEN_HOME/conf/setting.xml~
      #+BEGIN_EXAMPLE xml
      <localRepository>/path/to/local-repository</localRepository>
      #+END_EXAMPLE

*** 中央仓库
https://search.maven.org/

*** 远程仓库
    1) 在 ~$MAVEN_HOME/conf/setting.xml~ 或 ~$LOCAL_REPOSITORY/setting.xml~ 中设置
       - 规则
         1) 一个respository最多配置一个mirror
       - 示例
       #+BEGIN_EXAMPLE xml
       <!-- 设置远程仓库的镜像信息 -->
       <mirrors>
         <mirror>
           <!-- 镜像唯一标识，Maven将id值按字母表顺序查询依赖 -->
           <id>alimaven</id>
           <!-- 镜像描述 -->
           <name>aliyun maven</name>
           <!-- 镜像地址 -->
           <url>https://maven.aliyun.com/repository</url>
           <!-- 仓库镜像中包含多个仓库(如central,google,jcenter等)，通过mirrorOf设置使用该镜像下哪个仓库。
                * 匹配所有仓库请求，当搭建私有仓库时通常使用*匹配所有仓库请求
                repo1,repo2 配置repo1或repo2仓库
                *, !repo1 配置除repo1外的其它所有仓库
                external:* 配置所有非本地的仓库
             -->
           <mirrorOf>central</mirrorOf>
         </mirror>
       </mirrors>
       <!-- 设置远程镜像的帐号密码 -->
       <servers>
         <server>
           <id>alimaven</id>
           <username></username>
           <password></password>
         </server>
       </servers>
       #+END_EXAMPLE
    2) 在项目的 ~pom.xml~ 中设置
       #+BEGIN_EXAMPLE xml
       <repositories>
          <repository>
            <!-- 唯一标识，Maven将id值按字母表顺序查询依赖 -->
            <id>alimaven</id>
            <!-- 仓库描述 -->
            <name>aliyun maven</name>
            <!-- 仓库地址，最后的central匹配mirrorOf的值，表示用 -->
            <url>https://maven.aliyun.com/repository</url>
            <releases>
               <enabled>false</enabled> <!-- 设置当依赖为发布版本时，是否使用该仓库 -->
                <!-- 设置依赖更系策略
                     always
                     daily(默认)
                     interval:x x为分钟数
                     never
                 -->
               <updatePolicy>always</updatePolicy>
               <!-- Maven发布构建件到仓库时会带上checksum文件。当checksum文件缺失或不正确时，通过ignore,fail,warn设置处理方式 -->
               <checksumPolicy>warn</checksumPolicy>
            </releases>
            <snapshots>
               <enabled>true</enabled> <!-- 设置当依赖为SNAPSHOT版本时，是否使用该仓库 -->
               <updatePolicy>never</updatePolicy>
               <checksumPolicy>fail</checksumPolicy>
            </snapshots>
          </repository>
        </repositories>
      #+END_EXAMPLE

* 静态资源打包

** 默认配置
#+begin_example yaml
- src/
  - main/
    - java/
    - resources/
  - test/
    - java/
    - resources/
- target/
  - classes/
  - test-classes/
#+end_example
默认会将main/resources的内容复制到target/classes/resources下，而test/resources的内容复制到target/test-classes/resources下。

** 方式1：通过设置pom.xml的resources属性
#+begin_example xml
<build>
  <resources>
    <resource>
      <!-- 设置静态资源目录  -->
      <directory>src/main/java</directory>
      <!-- 复制目的目录 -->
      <targetPath>${build.outputDirectory}</targetPath>
      <excludes>
        <exclude>**/*.yaml</exclude>
      </excludes>
      <includes>
        <include>**/*.xml</include>
      </includes>
      <!-- 开启资源过滤 -->
      <filter>true</filter>
    </resource>
  </resources>
</build>
#+end_example

** 方式2：通过maven-resources-plugin设置
maven-compile-plugin用于编译Java代码，而maven-resources-plugin用于处理静态资源。

#+begin_example xml
<plugin>
  <groupId>org.apache.maven.plugin</groupId>
  <aritfactId>maven-resources-plugin</artifactId>
  <version>2.5</version>
  <exection>
    <id>copy-xmls</id>
    <phase>process-sources</phase>
    <goals>
      <goal>copy-resources</goal>
    </goals>
    <configuration>
      <outputDirectory>${basedir}/target/classes</outputDirectory>
      <resources>
        <resource>
          <directory>${basedir}/src/main/java</directory>
          <includes>
            <include>**/*.xml</include>
          </includes>
        </resource>
        <resource>
          <directory>${basedir}/src</directory>
          <includes>
            <include>*.xml</include>
          </includes>
        </resource>
      </resources>
    </configuration>
  </exection>
</plugin>
#+end_example

* 打包可执行JAR
若直接打包为普通JAR，要执行JAR则要调用
#+begin_example bash
java -cp xxx.jar io.fsjohnhuang.App
#+end_example
若打包为可执行JAR则只需
#+begin_example bash
java -jar xxx.jar
#+end_example

** 方式1
通过 ~mvn assembly:assembly~ 打包
1) pom.xml
   #+begin_example xml
   <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-assembly-plugin</artifactId>
       <version>2.2.0</version>
       <configuration>
           <archive>
               <manifest>
                   <mainClass>io.fsjohnhuang.App</mainClass>
               </manifest>
           </archive>
           <descriptorRefs>
               jar-with-dependencies
           </descriptorRefs>
       </configuration>
   </plugin>
   #+end_example
2) 执行 ~mvn assembly:assembly~
3) 可执行JAR位于./target/<artifactId>-<version>-jar-with-dependencies.jar


通过 ~mvn package~ 打包
1) pom.xml
   #+begin_example xml
   <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-assembly-plugin</artifactId>
       <version>2.2.0</version>
       <configuration>
           <archive>
               <manifest>
                   <mainClass>io.fsjohnhuang.App</mainClass>
               </manifest>
           </archive>
           <descriptorRefs>
               jar-with-dependencies
           </descriptorRefs>
       </configuration>
       <executions>
           <execution>
               <id>make-assembly</id>
               <phase>package</phase>
               <goals>
                   <goal>single</goal>
               </goals>
           </execution>
       </executions>
   </plugin>
   #+end_example

** 方式2
将项目依赖的JAR复制到一个目录中，并在MANIFEST文件中添加Class-Path和Main-Class。
1) pom.xml
   #+begin_example xml
   <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-jar-plugin</artifactId>
       <configuration>
           <archive>
               <manifest>
                   <mainClass>io.fsjohnhuang.App</mainClass>
                   <addClasspath>true</addClasspath>
                   <classpathPrefix>dependency/</classpathPrefix> <!-- 依赖的JAR复制到这个目录下 -->
               </manifest>
           </archive>
       </configuration>
   </plugin>
   <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-dependency-plugin</artifactId>
       <executions>
           <execution>
               <id>copy-dependencies</id>
               <phase>package</phase>
               <goals>
                   <goal>copy-dependencies</goal>
               </goals>
           </execution>
       </executions>
   </plugin>
   #+end_example
2) 执行 ~mvn package~

* 多模块
根pom.xml
#+BEGIN_EXAMPLE xml
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.john</groupId>
  <artifactId>StudentMIS</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <!-- jar(默认值)
       war
       ear
       pom, 表示项目仅仅包含了元数据(metadata)
       内置配置了，不同的打包模式对应的不同goal和phase绑定关系
    -->
  <packaging>pom</packaging>

  <!-- 描述子模块 -->
  <modules>
    <module>Utils</module>
    <module>Entities</module>
  </modules>

  <!-- 子模块也会继承这些properties值 -->
  <properties>
    <junit.version>4.12</junit.version>
  </properties>
  <!-- 在根pom.xml中通过dependencyManagement节点统一声明依赖的版本号和作用范围，但不会做实质的引入操作。
       而在子模块pom.xml中通过dependencies节点按需引入依赖。
    -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>JUnit</artifactId>
        <version>${junit.version}</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <!-- 在根pom.xml中直接通过dependencies节点引入依赖时，其所有子模块均会自动引入相同的依赖，无法做到按需引入。
    -->
  <dependencies>
    <dependency>
      <groupId>org.other</groupId>
      <artifactId>Something</artifactId>
      <version>1.0.0</version>
      <scope>provider</scope>
    </dependency>
  </dependencies>
</project>
#+END_EXAMPLE

子模块的pom.xml
#+BEGIN_EXAMPLE xml
<project>
  <!-- 父模块的坐标 -->
  <parent>
    <groupId>com.john</groupId>
    <artifactId>StudentMIS</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <!-- 子模块的POM信息 -->
  <modelVersion>4.0.0</modelVersion>
  <!-- 子模块的groupId和version都保持和父模块一致 -->
  <artifactId>Utils</artifactId>

  <denpendencies>
    <!-- 引入其他子模块，编译后会将依赖打包存放到lib目录下 -->
    <denpendency>
      <groupId>com.john</groupId>
      <artifactId>Entity</artifactId>
    </denpendency>
    <!-- 引入第三方依赖，version和scope由根pom.xml统一管理。
         也可设置version和scope，优先级比根pom.xml的高
      -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>JUnit</artifactId>
    </dependency>
  </denpendencies>
</project>
#+END_EXAMPLE

* 在命令行使用Maven指令


~mvn <life cycle phase>|<goal> ...~

#+begin_example bash
# 先删除原有的构建，再执行install这个lifecycle phase
# 默认情况下maven会在线检查依赖的版本等变化，并作更新
# 通过 mvn -o clean install 则禁止maven进行在线检查依赖
mvn clean install

# 多模块构建时，可设置构建失败的处理方式
# --fail-at-end 当所有模块构建完毕后，才反馈整体构建失败
# --fail-fast 当某个模块构建失败，马上中止本次构建
# --fail-never 整体构建永远被认为是成功的

# 脚手架
# 交互式创建
mvn archetype:generate

# 创建项目
mvn archetype:generate -DgroupId=com.john -DartifactId=Test -Dversion=1.0.0-SNAPSHOT -DarchetypeArtifactId=maven-archetype-webapp -DinteractiveMode=false
#+end_example

#+BEGIN_EXAMPLE  shell
# 查看版本号
mvn -v

# 为Maven项目生成Eclipse项目元数据
mvn eclipse:eclipse
# 清理Eclipse项目元数据
mvn eclipse:clean

# 为Maven项目生成IDEA项目元数据
mvn idea:idea
# 清理IDEA项目元数据
mvn idea:clean

# 删除原有的class文件
mvn clean

# 将Java源码编译为class文件
mvn compile

# 运行单元测试并生成测试报告
mvn test

# 根据POM.xml中的packaging标签指定，将项目打包为war或jar包
mvn package

# 编译项目并生成jar包，然后存放到本地仓库中，供其它模块安装和调用
mvn install

# 生成项目相关信息的网站
mvn site

# 发布
mvn deploy

# 下载源码
mvn dependency:sources

# 下载javadoc
mvn dependency:resolve -Dclassifier=javadoc

# 清理并重新解析当前项目相关的本地仓库依赖
# 1. 重新解析当前项目的整棵依赖树；2. 清理本地仓库；3. 根据远端仓库重新解析依赖树
mvn dependency:purge-local-repository
# 仅解析直接依赖，而不是包含间接依赖的整棵依赖树
mvn dependency:purge-local-repository -DactTransitively=false
# 仅清理和重新解析指定依赖
mvn dependency:purge-local-repository -Dinclude=org.slf4j:slf4j-api,org.slf4j:log4j-over-slf4j
mvn dependency:purge-local-repository -Dinclude=org.slf4j -DresolutionFuzziness=groupId -Dverbose=true
# 不清理和重新解析指定依赖
mvn dependency:purge-local-repository -Dexclude=org.slf4j:slf4j-api,org.slf4j:log4j-over-slf4j

# 清理并重解析当前项目相关的本地仓库依赖，清理不再解析非当前项目的本地依赖
mvn dependency:purge-local-repository -DmanualInclude=org.apache:apache

# 从本地安装依赖到本地仓库(如ojdbc.jar是收费的，因此中央仓库中没有该资源，只能通过将依赖安装到本地仓库，然后才能在项目中加载安装)
mvn install:install-file -Dfile=/path/to/jdbc6-11.2.0.3.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0.3 -Dpackaging=jar -DgeneratePom=true
#+END_EXAMPLE

特别说明：
1) 不执行compileTest和test
   - 命令方式： ~mvn package -Dmaven.test.skip=true~
   - pom设置方式：
     #+begin_example xml
     <plugin>
         <groupId>org.apache.maven.plugin</groupId>
         <artifactId>maven-compiler-plugin</artifactId>
         <version>2.1</version>
         <configuration>
             <skip>true</skip>
         </configuration>
     </plugin>
     <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-plugin</artifactId>
         <version>2.5</version>
         <configuration>
             <skip>true</skip>
         </configuration>
     </plugin>
     #+end_example
2) 不执行test
   - 命令方式： ~mvn package -DskipTests~
   - pom设置方式：
     #+begin_example xml
     <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-plugin</artifactId>
         <version>2.5</version>
         <configuration>
             <skipTests>true</skipTests>
         </configuration>
     </plugin>
     #+end_example

* TODO Maven Wrapper
* TODO Maven生命周期(Life Cycle, Phase, Goal)
  Maven包含3个相互独立的生命周期
  1) default lifecycle, handles the project deployment
     1) validate, validate the project is correct and all necessary information is available.
     2) compile, compile the source code of the project.
     3) test, test the compiled source code using a suitable unit testing framework. these tests should not require the code be packaged or deployed.
     4) package, take the compiled code and package it in its distributable format within `target` directory, such as a JAR or WAR.
        - the name of artifact file will be based on `artifactId` and  `version` defined in pom.xml.
          #+begin_example bash
          # executes the JAR file.
          java -jar target/artifactId-version.jar
          #+end_example
     5) integration-test, process and deploy the package if necessary into an environment where integration test can be run.
     6) verify, run any checks to verify the package is valid and meets quality criteria.
     7) install, install or copy the package into the local repository, for use as a denpendency in other projects locally.
     8) deploy, done in integration or release environment, copies the final package to the remote repository for sharing with other developers and projects.
  2) clean lifecycle, cleans up artifacts created by prior builds
  3) site lifecycle, generates site documentation for this project

  对于以 ~pre-,post-,process-~ 开头的生命周期阶段，并没mvn命令与之对应。因为这些阶段均用于作准备或会产生对外界无用的临时状态数据。

  1个Life Cycle是多个Phase，1个Goal对应1个Phase；Goal为Phase的具体实现，根据打包模式使用不同的Goal，例如项目类型为jar，那么package phase对应的goal则为jar:jar，若为项目类型为war，那么package phase对应的goal为war:war。

* 通过Jetty运行Web项目
  Jetty相当与IIS Express
  #+BEGIN_EXAMPLE xml
  <!--pom.xml-->
  <!-- 坐标：下面三个元素唯一标识一个项目
       groupId不仅仅对应公司或组织名，建议具体到项目名
       artifactId代表模块名
    -->
  <groupId>org.john</groupId>
  <artifactId>Test</artifactId>
  <version>1.0-SNAPSHOT</version>

  <packaging>war</packaging> <!--指定通过Maven打包输出war包-->

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <!-- 依赖范围
           compile, 编译、测试、运行都有效，默认值
           test, 测试有效
           provided, 编译、测试有效，如servlet，运行时容器会提供实现
           runtime, 运行、测试有效，如jdbc，编译时只需相应的接口，测试和运行时才需要具体的实现
           system, 编译、测试有效。此范围的依赖必须通过systemPath元素显式的指定依赖文件，因而此类依赖是不通过Maven仓库解析的，一般适合本机测试环境下依赖本地的服务。
        -->
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <!-- 插件 -->
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.mortbay.jetty</groupId>
          <artifactId>maven-jetty-plugin</artifactId>
          <version>6.1.26</version>
          <configuration>
            <webAppSourceDirectory>src/main/webapp</webAppSourceDirectory>
            <scanIntervalSeconds>3</scanIntervalSeconds>
            <contextPath>/jetty</contextPath>
            <connectors>
              <connector implementation="org.mortbay.jetty.nio.SelectChannelConnector">
                <port>4000</port>
              </connector>
            </connectors>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  #+END_EXAMPLE
  #+BEGIN_EXAMPLE bash
  mvn jetty:run
  #+END_EXAMPLE

* 在Tomcat中运行
#+BEGIN_EXAMPLE xml
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>tomcat-maven-plugin</artifactId>
  <version>1.1</version>
  <configuration>
    <path>/wp</path>
    <port>8080</port>
    <uriEncoding>UTF-8</uriEncoding>
    <url>http://localhost:8080/manager/html</url>
    <server>tomcat6</server>
  </configuration>
</plugin>
#+END_EXAMPLE
* QA
1) 执行 ~mvn site~ 报异常 ~java.lang.NoClassDefFoundError: org/apache/maven/doxia/siterenderer/DocumentContent~
   - 解决方法：在pom.xml中添加
     #+begin_example xml
     <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7</version>
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.doxia</groupId>
              <artifactId>doxia-site-renderer</artifactId>
              <version>1.8</version>
            </dependency>
          </dependencies>
        </plugin>
     #+end_example
2) 执行编译时报org/apache/maven/shared/filtering/MavenFilteringException
   - 原因：本地仓库中的resource plugin没有下载，一定是download resource插件时Maven私服上没有这个版本的插件
   - 解决办法：在pom.xml中添加
     #+begin_example xml
     <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-resources-plugin</artifactId>
         <version>2.4.3</version>
         <configuration>
             <encoding>${project.build.sourceEncoding}</encoding>
         </configuration>
     </plugin>
     #+end_example
