JAR，用于Java程序发布的包
WAR，用于网站发布的包
[[http://maven.apache.org/][官网]]

* 仓库资源
  #+begin_src xml
  	<repositories>
		<repository>
			<id>aliyun-central</id>
			<name>aliyun-central</name>
			<url>https://maven.aliyun.com/repository/central</url>
		</repository>
		<repository>
			<id>aliyun-jcenter</id>
			<name>aliyun-jcenter</name>
			<url>https://maven.aliyun.com/repository/public</url>
		</repository>
		<repository>
			<id>aliyun-public</id>
			<name>aliyun-public</name>
			<url>https://maven.aliyun.com/repository/public</url>
		</repository>
		<repository>
			<id>aliyun-spring</id>
			<name>aliyun-spring</name>
			<url>https://maven.aliyun.com/repository/spring</url>
		</repository>
		<repository>
			<id>aliyun-spring-plugin</id>
			<name>aliyun-spring-plugin</name>
			<url>https://maven.aliyun.com/repository/spring-plugin</url>
		</repository>
		<repository>
			<id>163</id>
			<name>163</name>
			<url>http://mirrors.163.com/maven/repository/maven-public</url>
		</repository>
	</repositories>
  #+end_src

* TODO Ant,Maven和Gradle对比

** Ant
   Ant构建项目采用的是指令方式，如源码编译部分通过javac命令以及一系列属性(如源码路径、依赖库路径等)，而打成war包时则通过war命令和附带的一系列属性(如编译好的class目录)。

** Maven
   Maven将项目抽象为POM(Poject Object Model)，并使用POM对项目进行构建、打包、文档化等操作。
   Maven默认规定
   - 源码路径为src/main/java
   - 测试路径为src/test/java
   - 配置文件路径为src/main/resources
   - 编译目标路径为target

* 依赖下载流程
1) 本地仓库
2) 默认中央仓库(http://repo1.maven.org/maven2/)
3) 在pom.xml中自定义的远程仓库私有仓库(代理公共中央仓库)

* Maven配置
  配置文件路径: ~$MAVEN_HOME/conf/setting.xml~
  - 配置远程仓库
    1) 在 ~$MAVEN_HOME/conf/setting.xml~ 或 ~$LOCAL_REPOSITORY/setting.xml~ 中设置
       - 规则
         1) 一个respository最多配置一个mirror
       - 示例
       #+BEGIN_EXAMPLE xml
       <!-- 设置远程仓库的镜像信息 -->
       <mirrors>
         <mirror>
           <!-- 唯一标识，Maven将id值按字母表顺序查询依赖 -->
           <id>alimaven</id>
           <!-- 仓库描述 -->
           <name>aliyun maven</name>
           <!-- 仓库地址 -->
           <url>https://maven.aliyun.com/repository/central</url>
           <!-- 设置表达式匹配请求哪些仓库时则使用该mirror配置
                * 匹配所有仓库请求，当搭建私有仓库时通常使用*匹配所有仓库请求
                repo1,repo2 配置repo1或repo2仓库
                *, !repo1 配置除repo1外的其它所有仓库
                external:* 配置所有非本地的仓库
             -->
           <mirrorOf>central</mirrorOf>
         </mirror>
       </mirrors>
       <!-- 设置远程仓库的帐号密码 -->
       <servers>
         <server>
           <id>alimaven</id>
           <username></username>
           <password></password>
         </server>
       </servers>

       <profile>
       </profile>
       #+END_EXAMPLE
    2) 在项目的 ~pom.xml~ 中设置
       #+BEGIN_EXAMPLE xml
       <project>
         <!-- 依赖仓库地址-->
         <repositories>
           <repository>
             <!-- 唯一标识，Maven将id值按字母表顺序查询依赖 -->
             <id>alimaven</id>
             <!-- 仓库描述 -->
             <name>aliyun maven</name>
             <!-- 仓库地址 -->
             <url>https://maven.aliyun.com/repository/central</url>
             <!-- 是否每次都获取最新版本的依赖 -->
             <snapshots>
               <enabled>true</enabled>
             </snapshots>
           </repository>
         </repositories>
          <!-- Maven 插件仓库地址-->
         <pluginRespositories>
           <pluginRespository>
             <!-- 唯一标识，Maven将id值按字母表顺序查询依赖 -->
             <id>alimaven</id>
             <!-- 仓库描述 -->
             <name>aliyun maven</name>
             <!-- 仓库地址 -->
             <url>https://maven.aliyun.com/repository/central</url>
           </pluginRespository>
         </pluginRespositories>
       </project>
       #+END_EXAMPLE
  - 配置下载依赖的源码和javadoc
    #+BEGIN_EXAMPLE xml
    <profiles>
      <profile>
        <id>downloadSources</id>
        <properties>
          <downloadSources>true</downloadSources>
          <downloadJavadocs>true</downloadJavadocs>
        </properties>
      </profile>
    </profiles>
    <activeProfiles>
      <activeProfile>downloadSources</activeProfile>
    </activeProfiles>
    #+END_EXAMPLE
  - 配置本地仓库地址
    #+begin_src xml
    <localRepository>/path/to/local/repo</localRepository>
    #+end_src

** 国内plugin仓库
   #+begin_src xml
       <pluginRepositories>
        <pluginRepository>
            <id>aliyun-central</id>
            <name>aliyun-central</name>
            <url>https://maven.aliyun.com/repository/central</url>
        </pluginRepository>
        <pluginRepository>
            <id>aliyun-jcenter</id>
            <name>aliyun-jcenter</name>
            <url>https://maven.aliyun.com/pluginRepository/jcenter</url>
        </pluginRepository>
        <pluginRepository>
            <id>aliyun-public</id>
            <name>aliyun-public</name>
            <url>https://maven.aliyun.com/pluginRepository/public</url>
        </pluginRepository>
        <pluginRepository>
            <id>aliyun-spring</id>
            <name>aliyun-spring</name>
            <url>https://maven.aliyun.com/pluginRepository/spring</url>
        </pluginRepository>
        <pluginRepository>
            <id>aliyun-spring-plugin</id>
            <name>aliyun-spring-plugin</name>
            <url>https://maven.aliyun.com/pluginRepository/spring-plugin</url>
        </pluginRepository>
        <pluginRepository>
            <id>163</id>
            <name>163</name>
            <url>http://mirrors.163.com/maven/pluginRepository/maven-public</url>
        </pluginRepository>
    </pluginRepositories>
   #+end_src

** 国内仓库
   #+begin_src xml
   	<repositories>
		<!-- 可指向以github托管maven包
                <repository>
			<id>maven-git-repo</id>
			<url>http://github.com/path/to/repository</url>
			<releases><enabled>true</enabled></releases>
			<snapshots><enabled>true</enabled></snapshots>
		</repository>-->
		<repository>
			<id>aliyun-central</id>
			<name>aliyun-central</name>
			<url>https://maven.aliyun.com/repository/central</url>
		</repository>
		<repository>
			<id>aliyun-jcenter</id>
			<name>aliyun-jcenter</name>
			<url>https://maven.aliyun.com/repository/jcenter</url>
		</repository>
		<repository>
			<id>aliyun-public</id>
			<name>aliyun-public</name>
			<url>https://maven.aliyun.com/repository/public</url>
		</repository>
		<repository>
			<id>aliyun-spring</id>
			<name>aliyun-spring</name>
			<url>https://maven.aliyun.com/repository/spring</url>
		</repository>
		<repository>
			<id>aliyun-spring-plugin</id>
			<name>aliyun-spring-plugin</name>
			<url>https://maven.aliyun.com/repository/spring-plugin</url>
		</repository>
		<repository>
			<id>163</id>
			<name>163</name>
			<url>http://mirrors.163.com/maven/repository/maven-public</url>
		</repository>
	</repositories>
   #+end_src

* Eclipse中使用Maven
  Eclipse的默认Maven不支持修改Maven本地仓库路径，因此一般都使用Eclipse自带的默认Maven。
  配置独立安装的Maven：
  1. 在Window/Preference/Maven/Installations下添加Maven Home目录；
  2. 在Window/Preference/Maven/User Settings下将Global Settings设置为conf/settings.xml。那么其它项目将会自动根据全局配置的内容设置。

* Idea中使用Maven

** 配置
   由于Idea自带的Maven不禁止我们自定义本地仓库(配置文件在Idea安装路径/plugins/maven/lib/maven3/conf/settings.xml)，所以可以直接使用。若要配置独立的Maven，可按如下步骤：
   1. File/Settings/Build, Execution, Deployment/Build Tools/Maven中配置Maven Home目录
   2. File/Settings/Build, Execution, Deployment/Build Tools/Maven中配置User settings file并勾选Override
   3. File/Settings/Build, Execution, Deployment/Build Tools/Maven中配置Local repository并勾选Override
   4. File/Settings/Build, Execution, Deployment/Build Tools/Maven/Importing中勾选Import Maven projects automatically，那么会自动引入Maven依赖的JAR包。

** 配置Tomcat
   1. 在Run/Edit Configuration中，添加Tomcat Server Local；
   2. 在Application server中选中Tomcat安装的目录
   3. 选择Deployment页签，并添加Artifact
   4. 将Application Context修改为自定义字符串，那么在浏览器上输入 ~localhost:8080/{Application Context}/~ 就可以访问站点

** 导入Maven工程
   1. 在Project Structure/Modules，点击Import Module
   2. 选择Maven工程所在的目录
   3. 在Import module from external model中选择Maven

* 项目结构
  #+BEGIN_EXAMPLE yml
  pom.xml
  src/
    - main/
      - java/ Java源码目录
      - resources/ 资源目录
      - filters/ 资源过滤目录
      - assembly/ Assembly descriptors
      - config/ 配置文件目录
      - webapp/ 网页源码目录
    - test
      - java/
      - resources/
      - filters/
  target/ 输出目录
  #+END_EXAMPLE

* Version规范
~<major>.<minor>.<incremental>-<qualifier>~
~<qualifier>~ 中除beta、alpha等值外还有如下值
- SNAPSHOT, 表示不稳定的版本。作为特殊版本号用于告知Maven该工程处于开发阶段，将经常更新和发布，若有其他工程依赖此类型的artifact，那么Maven会在仓库中寻找其最新版本下载使用。
- LATEST, 表示为最新版本。
- RELEASE，表示稳定版。

规范：
1) 同一个项目中所有模块版本保持一致
2) 子模块统一继承父模块的版本
3) 统一在顶层模块POM的 ~<dependencyManagement/>~ 节点中定义所有子模块的依赖版本号，而子模块POM中不添加依赖版本号
4) 开发测试阶段使用SNAPSHOT
5) 生产发布阶段使用RELEASE
6) 新版本迭代只修改顶层的POM版本

Maven遵循“约定优于配置”的策略(convention over configuration)
1) 任务compile，默认从src/main/java下编译所有java文件，并把输出的class文件存放到target/classes中；

** Maven SNAPSHOT(快照)
版本号形如 ~1.0.0-SNAPSHOT~ 的快照版本，用于表示当前项目处于快速开发阶段，Maven仓库中该快照版本对应的构建物将不定时被更新，而依赖该项目的其他项目在每次构建时都必须从Maven仓库中重新下载最新的JAR包。
1) 非SNAPSHOT版本的特点：
   1) 若每次发布新功能都要更新版本号，则需要通知依赖该项目的其他项目更新pom.xml从而下载最新JAR包；
   2) 若每次发布新功能都不更新版本号，则需要通知依赖该项目的其他项目清理已经下载的JAR包，并重新下载
      #+begin_example bash
      # 清理已下载的所有JAR包
      mvn dependency:purge-local-repository
      # 下载依赖并构建、打包项目
      mvn clean package
      #+end_example
2) SNAPSHOT版本的特点：
   每次发布新功能都要不需要更新版本号，也不必通知依赖该项目的其他项目组，他们在每次构建项目时Maven会自动去下载最新版的JAR包。显式要求Maven去下载最新版的SNAPSHOT版本也是可以的 ~mvn clean package -U~ 。

* pom.xml详解
Maven在执行任务或目标时，会在当前目录查找并读取pom.xml，然后根据配置信息执行目标。
pom.xml中包含如下信息
1) 项目依赖
2) 插件
3) 执行目标
4) 项目构建profile
5) 项目版本
6) 项目开发者列表
7) 相关邮件信息

** 模板
#+begin_example xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instane"
         xsi:schemaLoaction="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion> <!-- POM模型版本，当前固定为4.0.0 -->

    <parent>...</parent><!-- 设置父POM -->

    <!-- 1. 公司或组织的唯一标识，并且作为包生成规则。
            如groupId为io.fsjohnhuang.devops，Maven会在src/main/java下执行mkdir -p io/fsjohnhuang/devops

         2. groupId:artifactId:version 统称为POM坐标，例如 io.fsjohnhuang.devops:cmdb:1.0.0-SNAPSHOT
      -->
    <groupId>io.fsjohnhuang.devops</groupId>
    <artifactId>cmdb</artifactId> <!-- 项目的唯一标识 -->
    <version>1.0.0-SNAPSHOT</version> <!-- 项目版本号 -->

    <!-- 打包模式：jar(默认值), war, ear, pom(表示项目仅仅包含了元数据)
         注意：不同的打包模式对应的不同goal和phase绑定关系
      -->
    <packaging>pom</packaging>

    <name></name> <!-- 项目名称，Maven产生文档使用 -->
    <url></url> <!-- 项目主页，Maven产生文档使用 -->
    <description><![CDATA[]]></description> <!-- 项目详细描述，Maven产生文档使用 -->

    <properties>
    </properties>

    <modules></modules> <!-- 模块列表 -->

    <dependencies>
    <!-- 通过POM坐标声明依赖项，并由Maven统一下载更新和管理-->
    </dependencies>

    <dependencyManagers>
    <dependencyManagers>

    <repositories>
    </repositories>
</project>
#+end_example

** Super POM(父 POM)
   所有POM都会继承一个父POM，父POM包含一些可以被继承的设置(目录结构、输出目录、仓库地址、报表目录等)，子POM可覆盖父POM的配置。
   设置父POM的方式
   1) 隐式继承
      若没有显式指定继承父POM，Maven会默认继承effective pom。
      - 查看effective pom的配置信息
        1) 创建工程目录，并创建pom.xml
           #+begin_example xml
           <project xmlns = "http://maven.apache.org/POM/4.0.0"
               xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation = "http://maven.apache.org/POM/4.0.0
               http://maven.apache.org/xsd/maven-4.0.0.xsd">

               <!-- 模型版本 -->
               <modelVersion>4.0.0</modelVersion>
               <!-- 公司或者组织的唯一标志，并且配置时生成的路径也是由此生成， 如com.companyname.project-group，maven会将该项目打成的jar包放本地路径：/com/companyname/project-group -->
               <groupId>com.companyname.project-group</groupId>

               <!-- 项目的唯一ID，一个groupId下面可能多个项目，就是靠artifactId来区分的 -->
               <artifactId>project</artifactId>

               <!-- 版本号 -->
               <version>1.0</version>
           </project>
           #+end_example
        2) 执行 ~mvn help:effective-pom~ 向stdout输出配置信息
   2) 显式继承
      #+begin_example xml
      <parent>
          <groupId></groupId>
          <artifactId></artifactId>
          <version></version>
          <!-- 父POM的相对路径，默认值为../pom.xml。
               父POM的搜索顺序：
               1. 在构建当前项目的目录路径搜索父POM；
                  例如某项目存在子模块
                  - project/
                      - pom.xml
                      - moduleA/
                          - pom.xml
                  那么在目录project下执行mvn，那么project/moduleA/pom.xml的父POM为project/pom.xml。
               2. relativePath指定路径搜索父POM；
               3. 本地仓库中搜索父POM。
          -->
          <relativePath></relativePath>
      </parent>
      #+end_example

** 依赖声明
#+begin_example xml
<dependencies>
  <dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version></version>
    <!--
      compile(默认值)，打包到最终的构建件中
      provided，编译需要，不打包到最终的构建件中。如Spring Boot生成WAR包，而不是包含Tomcat的JAR包，那么Tomcat依赖就需要设置为provided了。又如lombok也是。
      runtime，编译不需要，运行时需要(接口和实现分离)，打包到最终的构建件中。如编译时缺少mysql-connector-java不会失败，但运行时就会失败。。
      test，测试使用，不打包到最终的构建件中。如测试框架。
      system，加载本地jar，不打包到最终的构建件中。
    -->
    <scope></scope>
    <systemPath></systemPath> <!-- 指定scope为system的包路径 -->
    <!--

    -->
    <type></type>
    <optional></optional>

    <exclusions>
      <exclusion>
        <groupId></groupId>
        <artifactId></artifactId>
      </exclusion>
    </exclusions>
  </dependency>
</dependencies>
#+end_example

*** 依赖传递

** 仓库
   3种仓库-本地、中央和远程，搜素下载依赖顺序：
   1) 在本地仓库搜索，若没有则进行第2步；
   2) 若设置远程仓库，则从1个或多个远程仓库搜索，搜索失败或没有设置远程仓库均会进行第3步；
   3) 在中央仓库搜索，若没有则抛出错误。

*** 本地仓库
    - 默认：位于 ~$HOME/.m2/repository~
    - 自定义：通过修改配置文件 ~$MAVEN_HOME/conf/setting.xml~
      #+BEGIN_EXAMPLE xml
      <localRepository>/path/to/local-repository</localRepository>
      #+END_EXAMPLE

*** 中央仓库
https://search.maven.org/

*** 远程仓库
    1) 在 ~$MAVEN_HOME/conf/setting.xml~ 或 ~$LOCAL_REPOSITORY/setting.xml~ 中配置远程仓库镜像。
       - 规则
         1) 一个respository最少配置一个mirror
       - 示例
       #+BEGIN_EXAMPLE xml
       <!-- 设置远程仓库的镜像信息 -->
       <mirrors>
         <mirror>
           <!-- 镜像唯一标识，Maven将id值按字母表顺序查询依赖 -->
           <id>alimaven</id>
           <!-- 镜像描述 -->
           <name>aliyun maven</name>
           <!-- 镜像地址 -->
           <url>https://maven.aliyun.com/repository</url>
           <!-- 仓库镜像中包含多个仓库(如central,google,jcenter等)，通过mirrorOf设置使用该镜像下哪个仓库。
	    并且可以通过mirrorOf的值实现继承或直接查找的单个或多个仓库的目的。

                * 匹配所有仓库请求，当搭建私有仓库时通常使用*匹配所有仓库请求
                repo1,repo2 配置repo1或repo2仓库
                *, !repo1 配置除repo1外的其它所有仓库
                external:* 配置所有非本地的仓库
             -->
           <mirrorOf>central</mirrorOf>
         </mirror>
       </mirrors>
       <!-- 设置远程镜像的帐号密码 -->
       <servers>
         <server>
           <id>alimaven</id>
           <username></username>
           <password></password>
         </server>
       </servers>
       #+END_EXAMPLE
    2) 在项目的 ~pom.xml~ 中设置
       #+BEGIN_EXAMPLE xml
       <repositories>
          <repository>
            <!-- 唯一标识，Maven将id值按字母表顺序查询依赖 -->
            <id>alimaven</id>
            <!-- 仓库描述 -->
            <name>aliyun maven</name>
            <!-- 仓库地址，最后的central匹配mirrorOf的值，表示用 -->
            <url>https://maven.aliyun.com/repository</url>
            <releases>
               <enabled>false</enabled> <!-- 设置当依赖为发布版本时，是否使用该仓库 -->
                <!-- 设置依赖更系策略
                     always
                     daily(默认)
                     interval:x x为分钟数
                     never
                 -->
               <updatePolicy>always</updatePolicy>
               <!-- Maven发布构建件到仓库时会带上checksum文件。当checksum文件缺失或不正确时，通过ignore,fail,warn设置处理方式 -->
               <checksumPolicy>warn</checksumPolicy>
            </releases>
            <snapshots>
               <enabled>true</enabled> <!-- 设置当依赖为SNAPSHOT版本时，是否使用该仓库 -->
               <updatePolicy>never</updatePolicy>
               <checksumPolicy>fail</checksumPolicy>
            </snapshots>
          </repository>
        </repositories>
      #+END_EXAMPLE

* 静态资源打包

** 默认配置
#+begin_example yaml
- src/
  - main/
    - java/
    - resources/
  - test/
    - java/
    - resources/
- target/
  - classes/
  - test-classes/
#+end_example
默认会将main/resources的内容复制到target/classes/resources下，而test/resources的内容复制到target/test-classes/resources下。

** 方式1：通过设置pom.xml的resources属性
#+begin_example xml
<build>
  <resources>
    <resource>
      <!-- 设置静态资源目录  -->
      <directory>src/main/java</directory>
      <!-- 复制目的目录 -->
      <targetPath>${build.outputDirectory}</targetPath>
      <excludes>
        <exclude>**/*.yaml</exclude>
      </excludes>
      <includes>
        <include>**/*.xml</include>
      </includes>
      <!-- 开启资源过滤 -->
      <filter>true</filter>
    </resource>
  </resources>
</build>
#+end_example

** 方式2：通过maven-resources-plugin设置
maven-compile-plugin用于编译Java代码，而maven-resources-plugin用于处理静态资源。

#+begin_example xml
<plugin>
  <groupId>org.apache.maven.plugin</groupId>
  <aritfactId>maven-resources-plugin</artifactId>
  <version>2.5</version>
  <exection>
    <id>copy-xmls</id>
    <phase>process-sources</phase>
    <goals>
      <goal>copy-resources</goal>
    </goals>
    <configuration>
      <outputDirectory>${basedir}/target/classes</outputDirectory>
      <resources>
        <resource>
          <directory>${basedir}/src/main/java</directory>
          <includes>
            <include>**/*.xml</include>
          </includes>
        </resource>
        <resource>
          <directory>${basedir}/src</directory>
          <includes>
            <include>*.xml</include>
          </includes>
        </resource>
      </resources>
    </configuration>
  </exection>
</plugin>
#+end_example

* 打包可执行JAR
若直接打包为普通JAR，要执行JAR则要调用
#+begin_example bash
java -cp xxx.jar io.fsjohnhuang.App
#+end_example
若打包为可执行JAR则只需
#+begin_example bash
java -jar xxx.jar
#+end_example

** 方式1——maven-assembly-plugin
支持自定义的打包结构，可以定制依赖项（Shell脚本、SQL脚本、.properties和.xml文件）等。
1) pom.xml
   #+begin_example xml
   <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-assembly-plugin</artifactId>
       <version>2.2.0</version>
       <!-- 若绑定到package Phase，那么执行mvn package就会自动执行该Goal;
            若没有绑定则需要直接执行Goal，mvn assembly:assembly
       -->
       <executions>
           <execution>
             <id>make-assembly</id>
             <!-- 绑定到package Phase -->
             <phase>package</phase>
             <goals>
                 <!-- 只运行一次 -->
                 <goal>single</goal>
             </goals>
           </execution>
       </executions>
       <configuration>
           <!-- 打包出来的项目名称，最终的文件名为$finalName-$descriptorRefs。
                若不设置该项目，最终的文件名为$artifactId-$version-$descriptorRefs。
           -->
           <finalName>name of project</finalName>
           <archive>
               <manifest>
                   <mainClass>io.fsjohnhuang.App</mainClass>
               </manifest>
           </archive>
           <!-- Maven预设置的描述符，或自行配置描述符文件
                预设置的描述符有：
                bin
                src
                project
                jar-with-dependencies: 将所有外部依赖JAR都加入生成的JAR包中。
           -->
           <descriptorRefs>jar-with-dependencies</descriptorRefs>
           <!-- 配置描述符文件
           <descriptor>src/main/assembly/assembly.xml</descriptor> -->
       </configuration>
   </plugin>
   #+end_example
2) 执行 ~mvn assembly:assembly~ 或 ~mvn package~
3) 可执行JAR位于./target/<artifactId>-<version>-jar-with-dependencies.jar

*** 描述符文件
若要实现自定义打包的效果，则需要配置描述符文件。

#+begin_example xml
<assembly>
    <!-- 对应descriptorRef中的值，作为打包文件名的后缀。 -->
    <id>assembly</id>
    <!-- 设置打包格式，可同时设置多个。支持以下类型：
         zip,tar,tar.gz,tar.bz2,jar,war
    -->
    <formats>
        <format>tar.gz</format>
    </formats>
    <includeBaseDirectory>true</includeBaseDirectory>
    <fileSets>
        <fileSet>
           <directory>src/main/bin</directory>
           <includes>
               <include>*.sh</include>
           </includes>
           <outputDirectory>bin</outputDirectory>
           <fileMode>0755</fileMode> <!-- 默认为0644 -->
        </fileSet>
        <fileSet>
           <directory>src/main/conf</directory>
           <outputDirectory>conf</outputDirectory>
        </fileSet>
        <fileSet>
           <directory>src/main/sql</directory>
           <includes>
               <include>*.sql</include>
           </includes>
           <outputDirectory>sql</outputDirectory>
        </fileSet>
        <fileSet>
           <directory>target/classes/</directory>
           <includes>
               <include>*.properties</include>
               <include>*.xml</include>
               <include>*.txt</include>
           </includes>
           <outputDirectory>conf</outputDirectory>
        </fileSet>
    </fileSets>
    <files>
        <file>
            <source>target/${project.artifactId}-${project-version}.jar</source>
            <!-- 修改文件名
               <destName></destName>
            -->
            <outputDirectory>.</outputDirectory>
        <file>
    </files>
    <dependencySets>
        <dependencySet>
            <!--
            false：将依赖以原来的JAR形式打包
            true：将依赖解压为*.class文件的目录结构再进行打包
            -->
            <unpack>false</unpack>
            <!--
            指定符合哪个作用范围的依赖会被打包。一般compile和provided都不用管，写为runtime即可。
            -->
            <scope>runtime</scope>
            <outputDirectory>lib</outputDirectory>
        </dependencySet>
    </dependencySets>
</assembly>
#+end_example

** 方式2
将项目依赖的JAR复制到一个目录中，并在MANIFEST文件中添加Class-Path和Main-Class。
1) pom.xml
   #+begin_example xml
   <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-jar-plugin</artifactId>
       <configuration>
           <archive>
               <manifest>
                   <mainClass>io.fsjohnhuang.App</mainClass>
                   <addClasspath>true</addClasspath>
                   <classpathPrefix>dependency/</classpathPrefix> <!-- 依赖的JAR复制到这个目录下 -->
               </manifest>
           </archive>
       </configuration>
   </plugin>
   <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-dependency-plugin</artifactId>
       <executions>
           <execution>
               <id>copy-dependencies</id>
               <phase>package</phase>
               <goals>
                   <goal>copy-dependencies</goal>
               </goals>
           </execution>
       </executions>
   </plugin>
   #+end_example
2) 执行 ~mvn package~

* 多模块

  Maven commands runs in the following order under Multi-module project:
  1. Maven first loads the parent POM and locates all of the submodule POMs.
  2. Maven then puts all of these project POMs into Maven Reactor which analyzes the dependencies between modules.
  3. Maven Reactor takes care of ordering components to ensure that interdependent modules are compiled and installed in the proper order.
     - Maven Reactor preserves the order of modules as defined in the POM unless changes need to be made.
  4. Maven executes the specified goals for every module in the multi-module build according the result from Maven Reactor.

** 示例

*** The Simple Parent Project
    A multi-module project is defined by a parent POM referencing one or more submodules.

    #+BEGIN_EXAMPLE xml
    <project>
      <modelVersion>4.0.0</modelVersion>

      <groupId>com.john</groupId>
      <artifactId>StudentMIS</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <!-- jar(默认值)
           war
           ear
           pom, 表示项目仅仅包含了元数据(metadata)，对于multi-module项目的parent pom而言，必须设置为pom。
           内置配置了，不同的打包模式对应的不同goal和phase绑定关系
        -->
      <packaging>pom</packaging>
      <name>The Name of Multi-module Project</name>

      <!-- 描述子模块
           <module>元素的值为子模块所属目录的名称，Maven会从这些目录下寻找pom.xml文件，并列入Maven构建项目中。
        -->
      <modules>
        <module>Utils</module>
        <module>Entities</module>
      </modules>

      <!-- 子模块也会继承这些properties值 -->
      <properties>
        <junit.version>4.12</junit.version>
      </properties>
      <!-- 在根pom.xml中通过dependencyManagement节点统一声明依赖的版本号和作用范围，但不会做实质的引入操作。
           而在子模块pom.xml中通过dependencies节点按需引入依赖。
        -->
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>junit</groupId>
            <artifactId>JUnit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
          </dependency>
        </dependencies>
      </dependencyManagement>
      <!-- 在根pom.xml中直接通过dependencies节点引入依赖时，其所有子模块均会自动引入相同的依赖，无法做到按需引入。
        -->
      <dependencies>
        <dependency>
          <groupId>org.other</groupId>
          <artifactId>Something</artifactId>
          <version>1.0.0</version>
          <scope>provider</scope>
        </dependency>
      </dependencies>

      <build>
        <!-- 在根pom.xml中通过pluginManagement节点统一声明依赖的版本号和作用范围，但不会做实质的引入操作。
           而在子模块pom.xml中通过plugins节点按需引入依赖。
        -->
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <configuration>
                <source>1.5</source>
                <target>1.5</target>
              </configuration>
            </plugin>
          </plugins>
        </pluginManagement>
      </build>
    </project>
    #+END_EXAMPLE

*** Submodule
  #+BEGIN_EXAMPLE xml
  <project>
    <!-- 父模块的坐标 -->
    <parent>
      <groupId>com.john</groupId>
      <artifactId>StudentMIS</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </parent>

    <!-- 子模块的POM信息 -->
    <modelVersion>4.0.0</modelVersion>
    <!-- 子模块的groupId和version都保持和父模块一致 -->
    <artifactId>Utils</artifactId>
    <packaging>jar</packaging>

    <name>The Name of Submodule</name>

    <denpendencies>
      <!-- 引入其他子模块，编译后会将依赖打包存放到lib目录下 -->
      <denpendency>
        <groupId>com.john</groupId>
        <artifactId>Entity</artifactId>
        <version>1.0-SNAPSHOT</version>
        <scope>compile</scope>
      </denpendency>
      <!-- 引入第三方依赖，version和scope由根pom.xml统一管理。
           也可设置version和scope，优先级比根pom.xml的高
        -->
      <dependency>
        <groupId>junit</groupId>
        <artifactId>JUnit</artifactId>
      </dependency>
    </denpendencies>
  </project>
  #+END_EXAMPLE

* 在命令行使用Maven指令
~mvn <life cycle phase>|<goal> ...~

#+begin_example bash
# 先删除原有的构建，再执行install这个lifecycle phase
# 默认情况下maven会在线检查依赖的版本等变化，并作更新
# 通过 mvn -o clean install 则禁止maven进行在线检查依赖
mvn clean install

# 多模块构建时，可设置构建失败的处理方式
# --fail-at-end 当所有模块构建完毕后，才反馈整体构建失败
# --fail-fast 当某个模块构建失败，马上中止本次构建
# --fail-never 整体构建永远被认为是成功的

# 脚手架
# 交互式创建
mvn archetype:generate

# 创建项目
mvn archetype:generate -DgroupId=com.john -DartifactId=Test -Dversion=1.0.0-SNAPSHOT -DarchetypeArtifactId=maven-archetype-webapp -DinteractiveMode=false
#+end_example

#+BEGIN_EXAMPLE  shell
# 查看版本号
mvn -v

# 为Maven项目生成Eclipse项目元数据
mvn eclipse:eclipse
# 清理Eclipse项目元数据
mvn eclipse:clean

# 为Maven项目生成IDEA项目元数据
mvn idea:idea
# 清理IDEA项目元数据
mvn idea:clean

# 删除原有的class文件
mvn clean

# 将Java源码编译为class文件
mvn compile

# 运行单元测试并生成测试报告
mvn test

# 根据POM.xml中的packaging标签指定，将项目打包为war或jar包
mvn package

# 编译项目并生成jar包，然后存放到本地仓库中，供其它模块安装和调用
mvn install

# 生成项目相关信息的网站
mvn site

# 发布
mvn deploy

# 下载源码
mvn dependency:sources

# 下载javadoc
mvn dependency:resolve -Dclassifier=javadoc

# 清理并重新解析当前项目相关的本地仓库依赖
# 1. 重新解析当前项目的整棵依赖树；2. 清理本地仓库；3. 根据远端仓库重新解析依赖树
mvn dependency:purge-local-repository
# 仅解析直接依赖，而不是包含间接依赖的整棵依赖树
mvn dependency:purge-local-repository -DactTransitively=false
# 仅清理和重新解析指定依赖
mvn dependency:purge-local-repository -Dinclude=org.slf4j:slf4j-api,org.slf4j:log4j-over-slf4j
mvn dependency:purge-local-repository -Dinclude=org.slf4j -DresolutionFuzziness=groupId -Dverbose=true
# 不清理和重新解析指定依赖
mvn dependency:purge-local-repository -Dexclude=org.slf4j:slf4j-api,org.slf4j:log4j-over-slf4j

# 清理并重解析当前项目相关的本地仓库依赖，清理不再解析非当前项目的本地依赖
mvn dependency:purge-local-repository -DmanualInclude=org.apache:apache

# 从本地安装依赖到本地仓库(如ojdbc.jar是收费的，因此中央仓库中没有该资源，只能通过将依赖安装到本地仓库，然后才能在项目中加载安装)
mvn install:install-file -Dfile=/path/to/jdbc6-11.2.0.3.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0.3 -Dpackaging=jar -DgeneratePom=true
#+END_EXAMPLE

特别说明：
1) 不执行compileTest和test
   - 命令方式： ~mvn package -Dmaven.test.skip=true~
   - pom设置方式：
     #+begin_example xml
     <plugin>
         <groupId>org.apache.maven.plugin</groupId>
         <artifactId>maven-compiler-plugin</artifactId>
         <version>2.1</version>
         <configuration>
             <skip>true</skip>
         </configuration>
     </plugin>
     <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-plugin</artifactId>
         <version>2.5</version>
         <configuration>
             <skip>true</skip>
         </configuration>
     </plugin>
     #+end_example
2) 不执行test
   - 命令方式： ~mvn package -DskipTests~
   - pom设置方式：
     #+begin_example xml
     <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-plugin</artifactId>
         <version>2.5</version>
         <configuration>
             <skipTests>true</skipTests>
         </configuration>
     </plugin>
     #+end_example

** Debug Mode
   Once the Maven debug level logging is enabled, it will print all the actions that it takes during the build process.
   ~mvn <phase|goal> -X~

* Maven Wrapper
由于Maven插件可能和特定版本的Maven兼容，因此需要通过Maven Wrapper锁定项目所使用的Maven版本。
mvnw实际调用的是.mvn/wrapper/maven-wrapper.jar中的 ~org.apache.maven.wrapper.MavenWrapperMain~ 。

** 安装
1) 在POM添加插件
   #+begin_example
   <plugin>
     <groupId>com.rimerosolutions.maven.plugins</groupId>
     <artifactId>wrapper-maven-plugin</artifactId>
     <version>0.0.4</version>
   </plugin>
   #+end_example
   - 命令 ~mvn wrapper:wrapper~ 就会在当前目录下就会生成mvnw、mvnw.bat和maven/下的maven-wrapper.jar、maven-wrapper.properties和MavenWrapperDownloader.java。
2) 直接在命令行执行GOAL
   #+begin_example bash
   # 安装最新版本的mvnw,然后在当前目录下就会生成mvnw、mvnw.cmd和.mvn/wrapper/下的maven-wrapper.jar、maven-wrapper.properties和MavenWrapperDownloader.java。
   mvn -N io.takari:maven:wrapper

   # 安装或修改mvnw所使用的maven版本号
   # 实际就是修改.mvn/wrapper/maven-wrapper.properties中distributionUrl所指向的Maven URL
   mvn -N io.takari:maven:wrapper -Dmaven=3.1.0
   #+end_example

** 使用
使用./mvnw代替mvn命令执行mvn的命令即可。
#+begin_example bash
./mvnw clean install
#+end_example

* Maven生命周期(Life Cycle, Phase, Goal, Plugin)
** Maven包含3个相互独立的生命周期
1) default lifecycle, handles the project deployment
   1) validate, validate the project is correct and all necessary information is available.
   2) initialize
   3) generate-sources
   4) process-sources
   5) generate-resources
   6) process-resources
   7) compile, compile the source code of the project.
   8) process-classes
   9) generate-test-sources
   10) process-test-sources
   11) generate-test-resources
   12) process-test-resources
   13) test-compile
   14) process-test-classes
   15) test, test the compiled source code using a suitable unit testing framework. these tests should not require the code be packaged or deployed.
   16) prepare-package
   17) package, take the compiled code and package it in its distributable format within `target` directory, such as a JAR or WAR.
       - the name of artifact file will be based on `artifactId` and  `version` defined in pom.xml.
         #+begin_example bash
         # executes the JAR file.
         java -jar target/artifactId-version.jar
         #+end_example
   18) pre-integration-test
   19) integration-test, process and deploy the package if necessary into an environment where integration test can be run.
   20) post-integration-test
   21) verify, run any checks to verify the package is valid and meets quality criteria.
   22) install, install or copy the package into the local repository, for use as a denpendency in other projects locally.
   23) deploy, done in integration or release environment, copies the final package to the remote repository for sharing with other developers and projects.
2) clean lifecycle, cleans up artifacts created by prior builds
   1) pre-clean
   2) clean
   3) post-clean
3) site lifecycle, generates site documentation for this project
   1) pre-site
   2) site
   3) post-site
   4) site-deploy

对于以 ~pre-,post-,process-~ 开头的生命周期阶段，并没mvn命令与之对应。因为这些阶段均用于作准备或会产生对外界无用的临时状态数据。

1个Life Cycle是多个Phase，每个Phase对应1个或多个Goal；
Goal为Phase的具体实现，根据打包模式使用不同的Goal，例如项目类型为jar，那么package phase对应的goal则为jar:jar，若为项目类型为war，那么package phase对应的goal为war:war。

** Phase
#+begin_example bash
# 下列命令均为执行到Life Cycle中的某个Phase，表示执行这个Phase及之前所有Phase绑定的Goal。
# 而每个Phase都会绑定Maven默认的Goal或没有对应Goal或对应自定义的Goal。
mvn clean
mvn validate
mvn compile
mvn test
mvn package
mvn verify
mvn install
mvn site
mvn deploy

# 也可以跳过某些Phase
mvn install -Dmaven.test.skip=true
#+end_example

** Goal
Goal作为Maven中任务的最小单位。
分为两类：
1) 和Phase绑定的，即执行到某个Phase就会触发该Goal；
2) 不和Phase绑定的，作为单独任务执行，相当于Ant的target。
   - 前提：项目已经执行到某个Phase，才能执行非绑定Goal。

** Plugin
插件包含一组Goal，这组Goal可包含Phase绑定和不绑定的，我们也可以重新绑定。
Plugin的命名规则: ~plugin-artifactId:plugin-version:plugin-goal(goal-execution-id)~

直接调用Plugin的Goal，跳过所有Phase
#+begin_example bash
# 格式：plugin-artifactId:plugin-goal
mvn compiler:compile
mvn compiler:testCompile
mvn surefire:test
mvn jar:jar
#+end_example

*** 查看Plugin中包含的Goal
通过help插件(Maven Help Plugin)查看其他插件提供哪些Goal。
#+begin_example xml
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-eclipse-plugin</artifactId>
            <version>2.10</version>
            <configuration>
                <downloadSources>true</downloadSources>
                <downloadJavadocs>true</downloadJavadocs>
                <wtpversion>2.0</wtpversion>
                <wtpContextName>spring3</wtpContextName>
            </configuration>
        </plugin>
    </plugins>
</build>
#+end_example
命令:
#+begin_example bash
# 格式：mvn help:describe -Dplugin=groupId:artifactId:version
mvn help:describe -Dplugin=org.apache.maven.plugins:maven-eclipse-plugin:2.10
#+end_example

* 从非Maven Central Respository下载安装依赖
** 在本地编译打包并安装到Maven Local Repository
   1. 下载依赖项目源码并编译为JAR包
   2. 利用maven-install-plugin插件的install-file目标安装到Maven Local Repository
      #+begin_src bash
      # -Dfile: 包的本机绝对路径
      # -Dpackaging: jar或war，生成包的后续
      # -Dclassifier: 兄弟包的别名，也就是-Dversion值后面的字符，如common-auth-0.0.1-SNAPSHOT-core.jar中的core
      mvn install:install-file -Dfile=<path-to-file> -DgroupId=<group-id> -DartifactId=<artifact-id> -Dversion=<version> -Dpackaging=<packaging>

      # 通过pom.xml读取groupId等信息
      mvn install:install-file -Dfile=<path-to-file> -DpomFile=<path-to-pomfile>

      # Maven 2.5+已简化为如下命令
      mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=<path-to-file>
      #+end_src

** 从GitHub/git/svn安装
   1. 编译发布到本地某目录下
      #+begin_src xml
      <!-- pom.xml -->
      <build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                        <!-- 编译后保留方法形参名称不变 -->
                        <compilerArgs>
	                <arg>-parameters</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>
                <!-- 在打包后的JAR文件中保留javadoc注释，实际会另外生一个xxxx-sources.jar文件 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
	       <version>2.4</verion>
                    <executions>
                        <execution>
                            <goals><goal>jar</goal></goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
      </build>
      <distributionManagement>
        <repository>
            <id>internal</id>
            <url>file://${project.build.directory}/mvn-repo</url>
        </repository>
      </distributionManagement>
      #+end_src
      执行 ~mvn deploy~
   2. 将mvn-repo下的内容上传到GitHub
   3. 从GitHub下载
      #+begin_src xml
      <!-- pom.xml -->
      <repositories>
        <repository>
	  <id>mvn-repo</id>
	  <url>url-to-github-branch</url>
	  <releases><enable>true</enable></releases>
	  <snapshots><enable>true</enable></snapshots>
        </repository>
      </repositories>
      #+end_src
      执行 ~mvn compile~

** 利用JitPack从GitHub下载
   JitPack builds GitHub projects on demand and provides ready-to-user packages.
   pom.xml配置
   #+begin_src xml
   <!-- 引入GitHub的项目 -->
   <dependency>
    <groupId>com.github.User</groupId>
    <artifactId>Repo name</artifactId>
    <version>Release tag</version>
   </dependency>

   <!-- 添加JitPack作为远程库 -->
   <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
   </repository>
   #+end_src

* 通过Jetty运行Web项目
  Jetty相当与IIS Express
  #+BEGIN_EXAMPLE xml
  <!--pom.xml-->
  <!-- 坐标：下面三个元素唯一标识一个项目
       groupId不仅仅对应公司或组织名，建议具体到项目名
       artifactId代表模块名
    -->
  <groupId>org.john</groupId>
  <artifactId>Test</artifactId>
  <version>1.0-SNAPSHOT</version>

  <packaging>war</packaging> <!--指定通过Maven打包输出war包-->

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <!-- 依赖范围
           compile, 编译、测试、运行都有效，默认值
           test, 测试有效
           provided, 编译、测试有效，如servlet，运行时容器会提供实现
           runtime, 运行、测试有效，如jdbc，编译时只需相应的接口，测试和运行时才需要具体的实现
           system, 编译、测试有效。此范围的依赖必须通过systemPath元素显式的指定依赖文件，因而此类依赖是不通过Maven仓库解析的，一般适合本机测试环境下依赖本地的服务。
        -->
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <!-- 插件 -->
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.mortbay.jetty</groupId>
          <artifactId>maven-jetty-plugin</artifactId>
          <version>6.1.26</version>
          <configuration>
            <webAppSourceDirectory>src/main/webapp</webAppSourceDirectory>
            <scanIntervalSeconds>3</scanIntervalSeconds>
            <contextPath>/jetty</contextPath>
            <connectors>
              <connector implementation="org.mortbay.jetty.nio.SelectChannelConnector">
                <port>4000</port>
              </connector>
            </connectors>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  #+END_EXAMPLE
  #+BEGIN_EXAMPLE bash
  mvn jetty:run
  #+END_EXAMPLE

* 在Tomcat中运行
#+BEGIN_EXAMPLE xml
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>tomcat-maven-plugin</artifactId>
  <version>1.1</version>
  <configuration>
    <path>/wp</path>
    <port>8080</port>
    <uriEncoding>UTF-8</uriEncoding>
    <url>http://localhost:8080/manager/html</url>
    <server>tomcat6</server>
  </configuration>
</plugin>
#+END_EXAMPLE
* plugins和pluginManagement的区别
** plugins
   特性：
   1. 用于引入插件和配置插件参数。
   2. 绑定到Mavne生命周期的各个阶段，即执行mvn命令时会加载通过plugins定义的插件。

** pluginManagement
   特性：
   1. 用于配置插件，而不是引入插件。
   2. 不绑定到Maven生命周期的各个阶段，即执行mvn命令时不会加载通过pluginManagement声明的插件。但可配置插件绑定的Maven生命周期phase和goals。
   用处：
   一般在父POM中声明各子POM会使用的插件及版本号，并且在实际使用该插件的子POM中通过plugins通过 ~groupId~ 和 ~artifactId~ 引入插件，而插件版本号则统一由父POM维护，从而保持各子模块的插件版本号一致。

** 示例
   1. 父POM
      #+begin_src xml
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
	      <groupId>org.apache.maven.plugins</groupId>
	      <artifactId>maven-source-plugin</artifactId>
	      <version>2.1</version>
                   <configuration>
                       <attach>true</attach>
                   </configuration>
                   <executions>
                       <execution>
	              <phase>compile<phase>
                           <goals>
                               <goal>jar</goal>
                           </goals>
                       </execution>
                   </executions>
	    </plugin>
          </plugins>
        </pluginManagement>
      </build>
      #+end_src
   2. 子POM
      #+begin_src xml
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
      #+end_src

* TODO cxf-codegen-plugin插件使用
* Oracle JDBC Driver安装
  由于Oracle为public maven repository提供Oracle JDBC Driver，因此我们需要自行到官网下载JAR文件，并通过Maven安装到local repository。
  1. 将ojdbc7-12.1.0.2.jar放置到项目根目录的lib目录下，随项目进行版本管理；
  2. 在POM.xml文件中加入dependency定义
     #+begin_src xml
     <dependency>
         <groupId>com.oracle</groupId>
         <artifactId>ojdbc7</artifactId>
         <version>12.1.0.2</version>
     </dependency>
     #+end_src
  3. 安装Oracle JDBC Driver到local repository
     #+begin_src shell
     # 在项目根目录下执行
     # -Dfile= 指定需要安装的JAR包
     # -DgroupId=
     # -DartifactId=
     # -Dversion=
     # -Dpackaging=jar 对应pom.xml中的packaging节点
     mvn install:install-file -Dfile=./lib/ojdbc7-12.1.0.2.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0.2 -Dpackaging=jar
     #+end_src

** Spring Boot中 ~<scope>system</scope>~ 的陷阱
   若部署环境安装了Oracle客户端或打包为非内置Web容器的SpringBoot包时，那么可以将dependency定义写为
   #+begin_src xml
     <dependency>
         <groupId>com.oracle</groupId>
         <artifactId>ojdbc7</artifactId>
         <version>12.1.0.2</version>
         <scope>system</scope>
         <systemPath>${basedir}/lib/ojdbc7-12.1.0.2.jar</systemPath>
     </dependency>
   #+end_src
   即可不必将Oracle JDBC Driver安装到local repository，即可成功编译和发布应用。
   注意：此方式打包出来的JAR内并没有Oracle JDBC Driver的JAR包，需要部署环境提供。直接运行SpringBoot应用会报如下异常：
   #+begin_quote
   ############
   application failed to start

   Description:
   ..................................
   Reason: Failed to load driver class oracle.jdbc.driver.OracleDriver in either of HikariConfig class loader or Thread context classloader.

   Action:
   Update your application's configuration
   ############
   #+end_quote
   解决方法：
   1. 外置Web容器时，则需要在部署目录的lib下放置ojdbc7-12.1.0.2.jar。
   2. 内置Web容器则无法通过上述方式设置dependency定义，必须通过local repository安装Oracle JDBC Driver。

* QA
1) 执行 ~mvn site~ 报异常 ~java.lang.NoClassDefFoundError: org/apache/maven/doxia/siterenderer/DocumentContent~
   - 解决方法：在pom.xml中添加
     #+begin_example xml
     <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7</version>
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.doxia</groupId>
              <artifactId>doxia-site-renderer</artifactId>
              <version>1.8</version>
            </dependency>
          </dependencies>
        </plugin>
     #+end_example
2) 执行编译时报org/apache/maven/shared/filtering/MavenFilteringException
   - 原因：本地仓库中的resource plugin没有下载，一定是download resource插件时Maven私服上没有这个版本的插件
   - 解决办法：在pom.xml中添加
     #+begin_example xml
     <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-resources-plugin</artifactId>
         <version>2.4.3</version>
         <configuration>
             <encoding>${project.build.sourceEncoding}</encoding>
         </configuration>
     </plugin>
     #+end_example
