JPA(Java Persistent API)，作为Java EE官方标准的一种ORM规范，并不是ORM产品，具体通用性。规范中对数据库结构提供较完整的封装，如Hibernat那样从POJO到数据库表的映射关系，通过规范/框架提供的存储逻辑自动生成对应的SQL并自动调用JDBC接口来执行。

PO(Persistent Object,持久化对象)，通过该对象可对数据库执行增、删、改的操作，以面向对象的方式操作数据库。

JTA(Java Transaction API)

DriverManager，操作一次数据库都重新建立一个数据库链接。
DataSource，提供数据库连接池优化对数据库的操作。实现javax.sql.DataSource接口，因此可以为任意第三方数据源，也可以通过JNDI从容器中获取的数据源。

JavaBeans
为符合特定规范的Java类：
1) 公有类
2) 私有字段
3) 公有getter和setter
4) 无参构造方法

* 简单示例
  - src/mybatis-config.xml
    #+BEGIN_EXAMPLE xml
    <?xml version="1.0" encoding="UTF-8" ?>
    <!DOCTYPE configuration
      PUBLIC "-//mybatis.org/DTD Config 3.0//EN"
      "http://mybatis.org/dtd/mybatis-3-config.dtd">
    <configuration>
        <!-- 指定Myatis所用日志的具体实现 -->
        <settings>
            <setting name="logImpl" value="LOG4J"/>
        </settings>
        <!-- 数据库环境配置 -->
        <environments default="sqlite">
            <environment id="sqlite">
                <transactionManager type="JDBC"/>
                <dataSource type="POOLED">
                    <property name="driver" value="org.sqlite.JDBC"/>
                    <property name="url" value="jdbc:sqlite:/path/to/example.db"/>
                    <property name="username" value=""/>
                    <property name="password" value=""/>                    
                </dataSource>
            </environment>
        </environments>
        <mappers>
            <mapper resource="org/john/mapper/UserMapper.xml"/>
        </mappers>
    </configuration>
    #+END_EXAMPLE
  - PO
    #+BEGIN_EXAMPLE java
    package org.john.domain
    // src/org/john/domain/User.java
  
    public class User {
        private Integer id;
        private String name;
        // setter,getter
    }
    #+END_EXAMPLE
  - mapper.xml
    #+BEGIN_EXAMPLE xml
    <!-- org/john/mapper/UserMapper.xml-->
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0/EN"
     "http://mybatis.org/data/mybatis-3-mapper.dtd">
    <!-- namespace必须全局唯一，一般命名方式为<包名>+<SQL映射文件名> -->
    <mapper namespace="org.john.mapper.UserMapper">
       <!-- useGeneratedKeys表示使用数据库的自动增长策略，需要底层数据库的支持 -->
       <insert id="save" parameterType="org.john.domain.User" useGeneratedKeys="true"> 
           INSERT INTO USER(name) values(#{name})
       </insert>
    </mapper>
    #+END_EXAMPLE
  - log4j.properties
    #+BEGIN_EXAMPLE
    # src/log4j.properties
    log4j.rootLogger=ERROR, stdout
    log4j.logger.org.john.mapper.UserMapper=DEBUG
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern = [%-5p] %d{yyyy-MM-dd HH:mm:ss,SSS} method:%l%n%m%n
    #+END_EXAMPLE
  - 程序入口
    #+BEGIN_EXAMPLE java
    package org.john;
    
    public static class App {
        public static void main(String[] args) {
            InputStream configStream = Resources.getResourceAsStream("mybatis-config.xml");
            SqlSessionFactory sessionFactory = new SqlSessionFactoryBuilder().build(configStream);
            SqlSession session = sessionFactory.openSession();
            
            User user = new User();
            user.setName("john");
            session.insert("org.john.mapper.UserMapper.save", user);
            session.commit();
            session.close();
        }
    }
    #+END_EXAMPLE

* 核心对象

~SqlSessionFactoryBuilder~, 读取MyBatis的XML配置文件或预制定的Configuration对象初始化SqlSessionFactory。
1) 读取MyBatis的XML配置文件初始化SqlSessionFactory实例
   1) 通过 ~Resources.getResourceAsStream("mybatis-config.xml")~ 读取XML配置文件并将其构建为输入流
   2) 将输入流传给 ~new SqlSessionFactoryBuilder().build~, 内部构建XMLConfigBuilder实例并通过其方法parse，解析XML配置文件内容并返回Configuration实例
   3) SqlSessionFactoryBuilder根据Configuration实例创建一个DefaultSessionFactory实例，并返回给调用者使用。

~SqlSessionFactory~, 为单个数据库映射关系经过编译后的内存镜像。
- 通过方法 ~new SqlSessionFactoryBuilder().build~ 从XML配置文件或一个预先定制的Configuration实例构建出来。
- 线性安全。
- 建议使用单例模式，在应用运行期间常存且避免重复创建。
  #+BEGIN_EXAMPLE java
  package org.john;
  import org.apache.ibatis.io.Resources;
  import org.apache.ibatis.session.SqlSession;
  import org.apache.ibatis.session.SqlSessionFactory;
  import org.apache.ibatis.session.SqlSessionFactoryBuilder;

  public class App {
    private static SqlSessionFactory sqlSessionFactory = null;
    static {
      try{
        InputStream inputStream = Resources.getResourceAsStream("mybatis-config.xml");
        sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
      } catch (Exception e) {
        e.printStackTrace();
      }
    }

    public static SqlSession getSqlSession(){
      return sqlSessionFactory.openSession();
    }

    public static void main(String[] args) {
      SqlSession session = getSqlSession();
    }
  }
  #+END_EXAMPLE
- 底层封装了DataSource。
- 常用方法
  - ~SqlSession openSession()~

~SqlSession~, 持久化操作对象。
- 常用方法
  - ~int insert(String statement)~, statement为在mapper.xml中元素 ~<insert>~ 的id值
  - ~int insert(String statement, Obejct parameter)~, statement为在mapper.xml中元素 ~<insert>~ 的id值
  - ~int update(String statement)~, statement为在mapper.xml中元素 ~<update>~ 的id值
  - ~int update(String statement, Object parameter)~, statement为在mapper.xml中元素 ~<update>~ 的id值
  - ~int delete(String statement)~, statement为在mapper.xml中元素 ~<delete>~ 的id值
  - ~int delete(String statement, Object parameter)~, statement为在mapper.xml中元素 ~<delete>~ 的id值
  - ~<T> T selectOne(String statement)~, statement为在mapper.xml中元素 ~<select>~ 的id值
  - ~<T> T selectOne(String statement, Object parameter)~, statement为在mapper.xml中元素 ~<select>~ 的id值
  - ~<E> List<E> selectList(String statement)~, statement为在mapper.xml中元素 ~<select>~ 的id值
  - ~<E> List<E> selectList(String statement, Object parameter)~, statement为在mapper.xml中元素 ~<select>~ 的id值
  - ~<E> List<E> selectList(String statement, Object parameter, RowBounds rowBounds)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - rowBounds用于分页，属性offset为查询的当前页数，属性limit为显示多少条数据。
  - ~<K,V> Map<K,V> selectMap(String statement, String mapKey)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - mapKey用于指定表中的一个列名。
  - ~<K,V> Map<K,V> selectMap(String statement, Object parameter, String mapKey)~, statement为在mapper.xml中元素 ~<select>~ 的id值
  - ~<K,V> Map<K,V> selectMap(String statement, Object parameter, String mapKey, RowBounds rowBounds)~, statement为在mapper.xml中元素 ~<select>~ 的id值
  - ~void select(String statement, ResultHandler handler)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - handler为用于处理查询返回的复杂结果集，通常用于多表查询。
  - ~void select(String statement, Object parameter, ResultHandler handler)~, statement为在mapper.xml中元素 ~<select>~ 的id值
  - ~void select(String statement, Object parameter, RowBounds rowBounds, ResultHandler handler)~, statement为在mapper.xml中元素 ~<select>~ 的id值
  - ~void commit()~
  - ~void rollback()~
  - ~void close()~
  - ~Connection getConnection()~
  - ~<T> T getMapper(Class<T> type)~, 返回mapper接口的代理对象，该对象关联了SqlSession对象，可以通过该对象直接调用方法操作数据库，参数type是Mapper的接口类型。MyBatis建议通过mapper对象访问MyBatis。

* MyBatis配置文件
  #+BEGIN_EXAMPLE xml
  <configuration>
      <!-- 引入外部配置，并在当前文档中动态替换。
           如：db.properties的内容为
                 username=root
                 password=root
               配置文件中其他部分动态替换为
               <property name="username" value="${username}"/>
               <property name="password" value="${password}"/>
        -->
      <properties resource="db.properties"/>
      <!-- 改变MyBatis运行时行为 -->
      <settings>
          <!--开启映射器的缓存-->
          <setting name="cacheEnabled" value="true"/>
          <!--开启关联对象延迟加载，在特定关联关系中可通过设置fetchType属性来覆盖该属性值-->
          <setting name="lazyLoadingEnabled" value="true"/>
          <!--为true时会使带有延迟加载属性的对象立即加载，默认值为true。因此需要设置为false-->
          <setting name="aggressiveLazyLoading" value="false"/>
          <!--允许单一语句返回多结果集-->
          <setting name="multipleResultSetsEnabled" value="true"/>
          <!--使用列标签代替列名，具体表现依赖数据库驱动-->
          <setting name="useColumnLabel" value="true"/>
          <!--允许JDBC支持自动生成主键-->
          <setting name="useGeneratedKeys" value="false"/>
          <!--设置MyBatis如何自动映射列到字段
              NONE, 取消自动映射
              PARTIAL, 只自动映射没有定义嵌套结果映射的结果集（默认值）
              FULL, 自动映射任意复杂的结果集
            -->
          <setting name="autoMappingBehavior" value="PARTIAL"/>
          <!--自动映射时发现未知数据表列的时应如何处理
              NONE, 不处理（默认值）
              WARNING, 输出警告
              FAILING, 映射失败，抛出SqlSessionException
            -->
          <setting name="autoMappingUnknownColumnBehavior" value="WARNING"/>
          <!--配置默认的执行器
              SIMPLE, 普通的执行器（默认值）
              REUSE, 执行器会重用预处理语句(prepared statements)
              BATCH, 执行器将重用语句并执行批量更新
            -->
          <setting name="defaultExecutorType" value="SIMPLE"/>
          <!--超时时间，决定驱动等待数据库响应的秒数-->
          <setting name="defaultStatementTimeout" value="25"/>
          <!--默认返回的结果集的大小-->
          <setting name="defaultFetchSize" value="100"/>
          <!--允许在嵌套语句中使用分页，默认值为false-->
          <setting name="safeRowBoundsEnabled" value="false"/>
          <!--开启自动驼峰命名规则，默认值为false-->
          <setting name="mapUnderscoreToCamelCase" value="false"/>
          <!--MyBatis利用本地缓存机制(local cache)防止循环引用(circular references)和加速重复嵌套查询。
              SESSION, 缓存一个会话中执行的所有查询（默认值）
              STATEMENT, 相同SqlSession的不同调用将不会共享数据
            -->
          <setting name="localCacheScope" value="SESSION"/>
          <!--当没有为参数提供特定的JDBC类型时，为空值指定JDBC类型。
              NULL
              VARCHAR
              OTHER（默认值）
            -->
          <setting name="jdbcTypeForNull" value="OTHER"/>
          <!--指定哪个对象的方法触发一次延迟加载，属性值设置为方法名的list集合-->
          <setting name="lazyLoadTriggerMethods" value="equals,clone,hashCode,toString"/>
          <!--指定MyBatis增加到日志名称的前缀-->
          <setting name="logPrefix" value="MyBatis"/>
          <!--指定MyBatis所用日志的具体实现，未指定时将自动查找
              值范围：SLF4J|LOG4J|LOG4J2|JDK_LOGGING|COMMONS_LOGGING|STDOUT_LOGGING|NO_LOGGING
            -->
          <setting name="logImpl" value="LOG4J"/>
          <!--指定创建具有延迟加载能力的对象所用到的代理工具
              CGLIB
              JAVASSIT(默认值)
            -->
          <setting name="proxyFactory" value="CGLIB"/>
          <!--指定当结果集中值为null时是否调用映射对象的setter方法。对于primitive type(int,boolean等)是不能设置为null的-->
          <setting name="callSettersOnNulls" value="false"/>
      </settings>

      <!--设置当前XML文档内使用的类型别名-->
      <typeAliases>
          <!-- 为类型org.john.domain.User设置别名user -->
          <typeAlias alias="user" type="org.john.domain.User"/>
          <!-- MyBatis扫描指定包下的所有类型
               1) 通过@Alias("alias_name")标识的类型，则以注解值作为别名
               2) 否则，以首字母小写非限定类型名称作为别名
            -->
          <package name="org.john.mapper"/>
      </typeAilases>

      <!--typeHandlers(类型处理器)
          在预处理语句(PreparedStatement)中设置一个参数 和 从结果集中取出一个值时，都会通过类型处理器将取出的值转换为Java类型。
        -->
      <!--objectFactory(对象工厂)
         在创建结果对象实例时，会使用对象工厂实例来完成。
        -->

      <!--数据源列表-->
      <environments default="dev">
          <environment id="dev">
              <!--数据库事务管理配置，结合Spring时Spring会使用自带的管理器来覆盖这部分的设置。
                  JDBC, 直接使用JDBC的提交和回滚设置，依赖从数据源得到的连接来管理事务范围。
                  MANAGED, 让容器来管理事务的整个生命周期，它不提交和回滚一个廉洁。
                -->
              <transactionManager type="MANAGED">
                  <property name="closeConnection" value="false"/>
              </transactionManager>
              <!--
                  UNPOOLED, 每次请求时打开和关闭数据库连接
                  POOLED, 启用数据库连接池
                  - poolMaximumActiveConnections, 在任意时间最大的正使用的连接数，默认值为10
                  - poolMaximumIdleConnections, 在任意时间最大的空闲连接数
                  - poolMaximumCheckoutTime, 在被强制返回前，池中连接被checkout的时间，默认值2000ms
                  - poolTimeToWait, 等待获取可用连接的超时时间，若超时则创建一个新的连接，默认值2000ms
                  - poolPingQuery, 发送到数据库的侦测查询，用于检查连接是否处于正常工作状态。默认值为NO PING QUERY SET
                  - poolPingEnabled, 启用数据库的侦测查询，默认值为false。启用后要设置poolPingQuery为用于侦测用的SQL语句。
                  - poolPingConnectionsNotUsedFor, 配置poolPingQuery的执行频率
                  JNDI, 使用EJB或应用服务器容器中配置的数据源
                  - initial_context, 调用initialContext.lookup(initial_context)寻找JNDI上下文，若忽略那么属性data_source将会直接从InitialContext中寻找。
                  - data_source, 引用数据源实例位置的上下文路径
                  <dataSource type="JNDI">
                      <property name="initial_context" value="java:/comp/env"/>
                      <property name="data_source" value="fkjavads"/>
                  </dataSource>
                -->
              <dataSource type="POOLED">
                  <property name="driver" value="${driver}"/>
                  <property name="url" value="${url}"/>
                  <property name="username" value="${username}"/>
                  <property name="password" value="${password}"/>
              </dataSource>
          </environment>
      </environments>

      <!--配置映射文件-->
      <mappers>
          <!--使用类路径查找-->
          <mapper resource="org/john/mapper/UserMapper.xml"/>
          <!--使用本地文件路径查找-->
          <mapper url="file:///project/org/john/mapper/UserMapper.xml"/>
          <!--使用接口类-->
          <mapper class="org.john.mapper.UserMapper"/>
          <!--使用包名-->
          <package name="org.john.mapper"/>
      </mappers>
  </configuration>
  #+END_EXAMPLE
* XML映射文件配置Mapper
  #+BEGIN_EXAMPLE xml
  <mapper namespace="john.mybatis.mapper.UserMapper">

  <!-- select, 映射查询语句
       属性：
         - id, 在mapper的namespace下唯一的标识符
         - parameterType, 入参的完全限定类名或别名
         - resultType, 返回值类型的完全限定名或别名，和属性resultMap不能同时使用
         - resultMap, 外部resultMap的命名引用，用于复杂的映射
         - flushCache, 为true时只要语句被调用，都会导致本地缓存和二级缓存都被清空，默认值为false
         - useCache, 为true时语句执行结果被二级缓存，为false时禁用二级缓存。select语句中默认值为true
         - timeout, 返回请求结果超时时间
         - fetchSize, 每次返回的结果的最大行数
         - statementType, STATEMENT/PREPARED/CALLABLE对应JDBC的Statement/PreparedStatement/CallableStatement。默认值为PREPARED。
         - resultSetType, 结果集类型，FORWARD_ONLY/SCROLL_SENSITIVE/SCROLL_INSENSITIVE。默认值为unset
         - databaseId, 若设置databaseIdProvider，那么MyBatis会加载所有不带databaseId或匹配当期那databaseId的语句。
                       可设置为oracle、mysql等，元素内部通过 <if test="_databaseId = 'oracle'"></if> 来书写针对特定数据库的SQL语句
         - resultOrdered, 仅针对嵌套结果的select语句适用。节省内存空间。
         - resultSets, 针对多个结果集的情况，给每个结果集列出一个别名，别名间以逗号分隔
    -->
  <select id="selectUser" parameterType="int" resultType="hashmap">
    SELECT * FROM USER WHERE ID = #{id}
  </select>

  <!-- 对于支持主键自增的数据库(如MySQL,SQLServer支持auto-generated key field)
       属性：
         - keyProperty, 默认值为unset,用于设置通过数据库的getGeneratedKeys方法或<selectKey>子元素获取的返回值，将赋值到领域模型的哪个属性中
         - keyColumn, 设置数据库自增的主键名。对特定数据库(如PostgreSQL)，若自增的主键不为第一个字段则必须设置
       返回值：为新增记录的主键值
    -->
  <insert id="insertUser1" useGeneratedKeys="true" keyProperty="id">
    insert into User(name) values(#{name})
  </insert>
   
  <!-- 对于不支持主键自增的数据库(如Oracle不支持auto-generated key field) -->
  <insert id="insertUser2">
    <!-- <selectKey>在<insert>和<update>元素中插入查询语句
         属性：
           - keyProperty, 默认值为unset,用于设置将selectKey操作结果赋值到领域模型的哪个属性中
           - resultType, 返回值类型的完全限定名或别名
           - order, 取值范围BEFORE/AFTER，表示在执行insert/update语句前/后执行selectKey操作
           - statementType, STATEMENT/PREPARED/CALLABLE对应JDBC的Statement/PreparedStatement/CallableStatement。默认值为PREPARED。
      -->
    <selectKey keyProperty="id" resultType="_int" order=“BEFORE" statementType="PREPARED">
      select squence_user.nextval as id from dual
    </selectKey>
    insert into User(id, name) values(#{id}, #{name})
  </insert>

  <!-- <update> 和 <delete> 类似
    -->

  <!--sql, 可被其他语句引用的可重用语句块，可循环引用-->
  <sql id="userColumns">
    ${alias}.id, ${alias}.name
  </sql>
  <select id="findUser">
    select
    <include refid="userColumns">
        <property name="alias" value="t1"/>
    </include>
    from User t1
  </select>

  <!--resultMap, 当结果集列名与返回值类型的字段名称不匹配时，通过resultMap设置映射关系
      属性：
        - id, resultMap标签的标识
        - type, 返回值的完全限定类型或别名
        - autoMapping, 默认值为true，自动映射为自动查找与字段名小写同名的属性名，并调用setter方法。
      子元素：
        - <id>, 设置主键字段映射
        - <result>, 设置普通字段映射
        - <discriminator>, 设置动态映射，其下的设置会与同级映射配置整合后作为整体的映射配置
          - 属性：
             - column, 以哪个表字段值作为入参
             - javaType, 将字段值转换为哪个Java类型
          - 子元素：
             - case, 条件判断
               - 属性：
                 - value, 期待值
                 - resultType
                 - resultMap
               - 子元素：
                 - <id>
                 - <result>
    -->
  <resultMap id="userResultMap" type="org.john.domain.User">
    <id property="id" column="user_id"/>
    <result property="name" column="user_name"/>
    <result column="juniorHighSchool" property="juniorHighSchool"/>
    <discriminator column="during" javaType="_int">
      <case value="4" resultType="org.john.domain.User">
        <result column="juniorHighSchool" property="seniorHighSchool"/>
      </case>
      <case value="5" resultMap="dynamicRM"/>
      <case value="6" resultMap="dynamicRM"/>
    </discriminator>
  </resultMap>
  <resultMap id="dynamicRM" type="org.john.domain.User">
    <result column="juniorHighSchool" property="seniorHighSchool"/>
  </resultMap>
  <!-- 通过子元素<constructor>指定通过构造方法赋值来实例化领域模型
       注意：其子元素顺序必须和构造方法的参数列表顺序一致
       子元素：
         - <idArg>, 标记入参的主键
         - <arg>, 标记入参的普通字段
    -->
  <resultMap id="userResultMap1" type="org.john.domain.User">
    <constructor>
      <idArg column="ID" javaType="_long"/>
      <arg column="Name" javaType="string"/>
    </constructor>
  </resultMap>
  <select id="findUser2" resultMap="userResultMap">
    select * from user
  </select>

  <resultMap id="userResultMap" type="org.john.domain.User">
    <id property="id" column="user_id"/>
    <result property="name" column="user_name"/>
    <!--多对一/一对一-->
    <association property="clazz" 
                 javaType="org.john.domain.Clazz"
                 column="clazz_id"
                 select="selectClazzWithId"/>
  </resultMap>
  <select id="selectClazzWithId" resultType="org.john.domain.Clazz">
     -- #{id}为org.john.domain.Clazz的id字段
     select * from clazz where id = #{id}
  </select>
  <select id="selectUser" resultMap="userResultMap">
     select * from user
  </select>

  <resultMap id="clazzResultMap" type="org.john.domain.Clazz">
    <id property="id" column="clazz_id"/>
    <result property="name" column="clazz_name"/>
    <!--一对多-->
    <collection property="students"
                javaType="ArrayList"
                ofType="org.john.domain.Student"
                column="clazz_id"
                select="selectStudentWithClazzId"
                fetchType="lazy"/>
   <!-- fetchType值为eager表示立即加载、lazy表示延迟加载
        要启用延迟必须在mybatis-config.xml中启用lazyLoadingEnabled和关闭aggressiveLazyLoading-->
  </resultMap>
  <select id="selectClazz" resultMap="clazzResultMap">
     select * from clazz
  </select>
  <select id="selectUserWithId">
     -- #{id}为org.john.domain.Clazz的id字段
     select * from user where clazz_id=#{id}
  </select>
  </mapper>
  #+END_EXAMPLE

  通过mapper接口对象操作数据库
  #+BEGIN_EXAMPLE java
  // 定义mapper接口对象
  public interface ClazzMapper {
      Clazz selectClazz();
  }

  public interface UserMapper {
      User selectUser();
  }

  // 主入口
  ClazzMapper cm = session.getMapper(ClazzMapper.class);
  UserMapper um = session.getMapper(UserMapper.class);
  Clazz clazz = cm.selectClazz();
  User user = um.selectUser();
  #+END_EXAMPLE
* 动态SQL
  MyBatis使用基于OGNL的表达式实现动态SQL。
  - if
    #+BEGIN_EXAMPLE xml
    <select id="selectEmployeeByLoginLike" parameterType="hashmap" resultType="org.john.domain.User">
    select * from user where state = 'ACTIVE'
    <if test="loginname != null and password != null">
      and loginname = #{loginname} 
      and password = #{password}
    </if>
    </select>
    #+END_EXAMPLE
    #+BEGIN_EXAMPLE java
    public interface EmployeeMapper{
        List<User> selectEmployeeByLoginLike(HashMap<String, Object> params);
    }
    
    EmployeeMapper employeeMapper = session.getMapper(EmployeeMapper.class);
    HashMap<String, Object> params = new HashMap<String, Object>();
    params.put("loginname", "john");
    params.put("password", "123");
    List<User> users = employeemapper.selectEmployeeByLoginLike(params);
    users.forEach(user -> System.out.println(user.getName()));
    #+END_EXAMPLE
  - choose(when, otherwise)
    if...elif...else语句
    #+BEGIN_EXAMPLE xml
    <select id="selectUsers" parameterType="hashmap" resultType="org.john.domain.User">
    select * from user where state = 'ACTIVE'
    <choose>
       <when test="id != null">
       and id = #{id}
       </when>
       <when test="loginname != null and password != null">
       and loginname = #{loginname} 
       and password = #{password}
       </when>
       <otherwise>
       and sex = 'male'
       </otherwise>
    </choose>
    </select>
    #+END_EXAMPLE
  - where
    只有一个以上的if条件有值才去插入where子句，并且会自动处理多余的and或or的开头保留字。
    #+BEGIN_EXAMPLE xml
    <select id="selectUsers" parameterType="hashmap" resultType="org.john.domain.User">
    select * from user
    <where>
       <if test="state != null">
       state = #{state}
       </if>
       <if test="id != null">
       and id = #{id}
       </if>
       <if test="loginname != null and password != null">
       and loginname = #{loginname} 
       and password = #{password}
       </if>
       <if>
       and sex = 'male'
       </if>
    </where>
    </select>
    #+END_EXAMPLE
  - set
    自动处理多余的逗号
    #+BEGIN_EXAMPLE xml
    <update id="selectUsers" parameterType="hashmap">
    update user
    <set>
      <if test="loginname != null">loginname=#{loginname},</if>
      <if test="password != null">password=#{password},</if>
    </set>
    </update>
    #+END_EXAMPLE
  - foreach
    #+BEGIN_EXAMPLE xml
    <select id="selectUsers" resultType="org.john.domain.User">
    select * from user
    where id in 
    <!--当入参为List或Array时会自动添加到内部Map实例中，List入参的键名为list，Array入参的键名为array。
        属性item定义元素引用名称
        属性index定义元素索引名称
        属性collection指定入参的键名list|array
      -->
    <foreach item="item" index="index" collection="list" open="(" separator="," close=")">
    #{item}
    </foreach>
    </select>
    #+END_EXAMPLE
  - bind
    从OGNL表达式中创建一个变量，并将其绑定到上下文。
    #+BEGIN_EXAMPLE xml
    <select id="selectUsre" resultType="org.john.domain.User">
    <bind name="pattern" value="'%' + _parameter.getName() + '%'"/>
    select * from user
    where loginname like #{pattern}
    </select>
    #+END_EXAMPLE
  - trim
    当标签体有内容时则为内容添加前缀、后缀，而且可以除去内容前后部分内容
    #+BEGIN_EXAMPLE xml
    <select id="findActiveBlogLike"
         resultType="Blog">
      SELECT * FROM BLOG
      <!--
        prefix属性值为添加到内容的前缀信息
        prefixOverrides属性值为除去内容前的内容，当需要除去多个内容时，使用管道符|分割，注意：空格也将被除去
      -->
      <trim prefix="where" prefixOverrides="AND |OR ">
        <if test="state != null">
             state = #{state}
        </if>
        <if test="title != null">
            AND title like #{title}
        </if>
        <if test="author != null and author.name != null">
            AND author_name like #{author.name}
        </if>
      </trim>
    </select>
    #+END_EXAMPLE
* 事务管理
  事务4个特性：
  1) 原子性(Atomicity), 事务作为应用中不可再分割的最小逻辑执行单位。
  2) 一致性(Consistency), 数据库从一种一致性状态，变到另一种一致性状态。一致性通过原子性来保证。
  3) 隔离性(Isolation), 并发执行的事务之间互不干扰，即事务操作过程中的中间状态无法被其他事务访问。
  4) 持续性(Durability/Persistence), 事务一旦提交，其对数据的任何草走都将记录到永久存簇器中。 

** 相关接口和实现类
接口org.apache.ibatis.transaction.Transaction，而其实现类为org.apache.ibatis.transaction.jdbc.JdbcTransaction和org.apache.ibatis.transaction.managed.ManagedTransaction。
工厂接口org.apache.ibatis.transaction.TransactionFactory，而其实现类为org.apache.ibatis.transaction.jdbc.JdbcTransactionFactory和org.apache.ibatis.transaction.managed.ManagedTransactionFactory来获取事务的实例对象。
   
接口Transaction
#+BEGIN_EXAMPLE java
public interface Transaction {
    Connection getConnection() throws SQLException;
    void commit() throws SQLException;
    void rollback() throws SQLException;
    void close() throws SQLException;
}
#+END_EXAMPLE

** 创建事务实例的过程
   1) 根据mybatis-config.xml中 ~<transactionManager>~ 的属性type值创建JdbcTransactionFactory或ManagedTransactionFactory实例
      #+BEGIN_EXAMPLE java
      // <transactionManager>节点解析方法
      private TransactionFactory transactionManagedElement(XNode context) throws Exception {
        /* 前面已经通过下面语句注册别名JDBC和MANAGED对应的工厂类
           typeAliasRegistry.registerAlias("JDBC", JdbcTransactionFactory.class);
           typeAliasRegistry.registerAlias("MANAGED", ManagedTransactionFactory.class);
         */
        if (context != null){
          String type = context.getStringAttribute("type");
          Properties props = context.getChildrenAsProperties();
          TransactionFactory factory = (TransactionFactory) resolveClass(type).newInstance();
          factory.setProperties(props);
          return factory;
        }
        throw new BuilderException("Enviroment declaration requries a TransactionFactory.");
      }
      #+END_EXAMPLE
   2) 然后通过TransactionFactory实例，以Connection实例或DataSource实例、隔离级别、自动提交作为入参创建Transaction实例。
   3) JdbcTransaction和ManagedTransaction的区别
      1) JdbcTranscation实际使用的是java.sql.Connection提供的事务操作，依赖数据库本身的支持。
      2) ManagedTransaction则将事务管理交由应用容器(Weblogic等)管理，自身不提供commit和rollback操作，而是由容器统一管理。

* 数据缓存机制
  分为一级和二级缓存：
  1) 一级缓存为SqlSession级别的缓存。
  2) 二级缓存为mapper级别的缓存，多个SqlSession共享的。

** 一级缓存(SqlSession级别)
   - 默认开启
   - 缓存数据保存在SqlSession实例内部的HashMap实例中
   - 缓存逻辑
     1) 当在同一个SqlSession实例执行相同的SQL语句时，第一次执行后会将数据以对象id为键保存到内部的HashMap中，后续查询则直接从缓存中读取；
     2) 若SqlSession实例执行DML(insert,update,delete)并提交到数据，那么一级缓存将被自动清空。

** 二级缓存(mapper级别)
   - 默认关闭
     - 在mybatis-config.xml中通过 ~<setting name="cacheEnabled" value="true"/>~ 开启二级缓存
     - 在使用二级缓存的mapper.xml中通过 ~<cache eviction="LRU" flushInterval="60000" size="512" readOnly="true"/>~ 开启
       - flushInterval, 刷新间隔毫秒数。默认值为unset，即不刷新。
       - size, 缓存数目。默认值1024
       - readOnly, 默认值为false。只读的缓存会给调用者返回相同的实例，因为这些对象不能被修改。可读写的缓存会返回缓存对象的拷贝。
       - eviction, 回收策略，默认值为LRU
         - LRU, 最近最少用策略
         - FIFO, 先进先出策略
         - SOFT, 软引用策略，移除基于垃圾回收器状态和软引用规则的对象
         - WEAK, 弱引用策略，更积极地移除基于垃圾回收器状态和弱引用规则的对象
   - 注意：被二级缓存的对象及其父类必须实现java.io.Serializable接口，因为二级缓存数据存储介质不一定在内存，可能在硬盘或远程服务器。
   - 缓存数据保存在Mapper内部的HashMap实例中
   - 缓存逻辑
     不同的SqlSession实例多次执行相同的mapper的namespace下的sql语句，且传递相同的参数，导致最终生成相同的sql语句，那么第一执行后将结果缓存起来，后续查询均从缓存读取。
* 注解配置Mapper
  MyBatis的注解位于org.apache.ibatis.annotations下
  - ~@Select~, Select语句的SQL映射
  - ~@SelectProvider~, Select语句的动态SQL映射。允许通过属性type和method指定一个完全限定类名和方法名在执行时返回运行的查询语句
  - ~@Insert~, Insert语句的SQL映射
  - ~@InsertProvider~, Insert语句的动态SQL映射。允许通过属性type和method指定一个完全限定类名和方法名在执行时返回运行的插入语句
  - ~@Update~, Update语句的SQL映射
  - ~@UpdateProvider~, Update语句的动态SQL映射。允许通过属性type和method指定一个完全限定类名和方法名在执行时返回运行的更新语句
  - ~@Delete~, Delete语句的SQL映射
  - ~@DeleteProvider~, Delete语句的动态SQL映射。允许通过属性type和method指定一个完全限定类名和方法名在执行时返回运行的删除语句
  - ~@Result~, 列和属性间的结果映射。属性包括：
    - id, 布尔值，表示是否被用于主键映射
    - column,
    - property,
    - javaType,
    - jdbcType
    - type Handler
    - one, 和XML中的 ~<association>~ 相似
    - many, 和XML中的 ~<collection>~ 相似
  - ~@Results~, 多个结果映射列表
  - ~@Options~, 提供配置选项的附加值，通常用于在映射语句上作为附加功能配置出现
  - ~@One~, 复杂类型的单独属性值映射。必须指定属性select，表示已映射的SQL语句的完全限定名
  - ~@Many~, 复杂类型的集合属性值映射。必须指定属性select，表示已映射的SQL语句的完全限定名
  - ~@Param~, 为映射器方法参数定义名字。

** 示例-CRUD
   #+BEGIN_EXAMPLE java
   public interface UserMapper{
     @Insert("insert into user(name, sex) values(#{name}, #{sex})")
     @Options(useGeneratedKeys=true, keyProperty="id")
     int saveUser(User user);

     @Delete("delete from user where id = #{id}")
     int removeUser(@Param("id") Integer id);

     @Update("update user set name=#{name}, sex=#{sex} where id=#{id}")
     void modifyUser(User user);

     @Select("select * from user where id=#{id}")
     @Results({
        @Result(id=true, column="id", property="id"),
        @Result(column="name", property="name"),
        @Result(column="sex", property="sex")
     })
     User selectUserById(@Param("id") Integer id);

     @Select("select * from user")
     List<User> selectAllUser();
   }
   #+END_EXAMPLE

** 示例-OneToOne
   #+BEGIN_EXAMPLE java
   public interface UserMapper{
     @Select("select * from user where id = #{id}")
     @Results({
        @Result(id=true, column="id", property="id"),
        @Result(column="name", property="name"),
        @Result(column="clazz_id", property="clazz",
                one=@One(
                    select="org.john.mapper.ClazzMapper.selectClazzById",
                    fetchType=FetchType.EAGER
                    ))
     })
     User selectUserById(@Param("id") Integer id);
   }
   #+END_EXAMPLE

** 示例-OneToMany
   #+BEGIN_EXAMPLE java
   public interface ClazzMapper {
     @Select("select * from clazz where id = #{id}")
     @Results({
        @Result(id=true, column="id", property="id"),
        @Result(column="id", property="students",
                many=@Many(
                     select="org.john.mapper.UserMapper.selectUserByClazzId",
                     fetchType=FetchType.LAZY
                     ))
     })
     Clazz getClazzById(@Param("id") Integer id);
   }
   #+END_EXAMPLE

** 示例-动态SQL注解
   - SQL工具类 ~org.apache.ibatis.jdbc.SQL~ 可避免直接使用字符串拼接
     - ~T SELECT(String columns)~
     - ~T FROM(String table)~
     - ~T JOIN(String join)~
     - ~T INNER_JOIN(String join)~
     - ~T LEFT_OUTER_JOIN(String join)~
     - ~T RIGHT_OUTER_JOIN(String join)~
     - ~T WHERE(String condition)~
     - ~T OR()~
     - ~T AND()~
     - ~T GROUP_BY(String column)~
     - ~T HAVING(String column)~
     - ~T ORDER_BY(String column)~
     - ~T INSERT_INTO(String table)~
     - ~T VALUES(String column, String value)~
     - ~T DELETE_FROM(String table)~
     - ~T UPDATE(String table)~
     - ~T SET(String set)~
   - ~*Provider~ 方法接收以下参数：
     - 无参数
     - Java对象
     - java.util.Map对象
   
   #+BEGIN_EXAMPLE java
   publc class UserDynaSqlProvider {
     public String selectWithParam(Map<String, Object> param){
       return new SQL(){
         {
           SELECT("*");
           FROM("user");
           if (param.get("id") != null) {
             WHERE(" id = #{id} ");
           }
           if (param.get("loginname") != null) {
             WHERE(" loginname = #{loginname} ");
           }
         }
       }.toString();
     }
   }
   #+END_EXAMPLE
* Spring集成 
  MyBatis3问世前Spring3的开发工作已经完成，因此Spring3中没有内置对MyBatis3的支持，需要引入MyBatis提供的mybatis-spring.jar来集成。到Spring4时则延续这一做法。
  1) 在applicationContext.xml配置MyBatis工厂类
  2) 在DAO层使用Spring注入的工具Bean对数据进行操作

  #+BEGIN_EXAMPLE xml
  <!-- applicationContext.xml -->
  xmlns:mybatis="http://mybatis.org/schema/mybatis-spring"
  xmlns:p="http://www.springframework.org/schema/p"
  xmlns:tx="http://www.springframework.org/schema/tx"
  xsi:schemaLocation="http://mybatis.org/schema/mybatis-spring
                      http://mybatis.org/schema/mybatis-spring.xsd
                      http://www.springframework.org/schema/p
                      http://www.springframework.org/schema/p.xsd
                      http://www.springframework.org/schema/tx
                      http://www.springframework.org/schema/tx.xsd"

  <!-- 注册Spring Bean -->
  <context:component-scan base-package="org.john"/>           
  <!-- 引入mapper接口 -->
  <mybatis:scan base-package="org.john.mapper"/>
  <!-- 使用PropertyOverrideConfigurer后处理器加载数据源参数
  <context:property-override location="classpath:db.properties"/> -->
  <!-- 配置c3p0数据源
  <bean id="dataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource"/> -->
  <!-- 配置jdbc数据源 -->
  <bean id="dataSource" class="org.springframework.jdbc.dataSource.DriverManagerDataSource">
    <property name="driverClassName">
      <value>com.mysql.jdbc.Driver</value>
    </property>
    <property name="url">
      <value>jdbc:mysql://localhost:3306/oa?zeroDateTimeBehavior=convertToNull</value>
    </property>
    <property name="username">
    </property>
    <property name="password">
    </property>
  </bean>

  <!-- 指定SqlSessionFactory为社区开发的实现类 -->
  <!--<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean" p:dataSource-ref="dataSource"/>-->
  <bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
    <property name="dataSource" ref="dataSource"/>
    <!-- 在当前classpath中读取MyBatis配置文件sqlMapConfig.xml -->
    <property name="configLocation" ref="classpath:sqlMapConfig.xml"/>
  </bean>

  <!-- JDBC事务管理器 -->
  <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager" p:dataSource-ref="dataSource"/>
  <!-- 启用支持annotation注解方式事务管理 -->
  <tx:annotation-driven transaction-manager="transactionManager"/>
  #+END_EXAMPLE

  #+BEGIN_EXAMPLE
  # db.properties
  dataSource.driverClass=com.mysql.jdbc.Driver
  dataSource.jdbcUrl=jdbc:mysql://127.0.0.1:3306/mybatis
  dataSource.user=root
  dataSource.password=root
  dataSource.maxPoolSize=20
  dataSource.maxIdleTime=1000
  dataSource.minPoolSize=6
  dataSource.initialPoolSize=5
  #+END_EXAMPLE

  #+BEGIN_EXAMPLE xml
  <!-- spring框架提供的字符集过滤器 -->
  <!-- spring Web MVC框架提供了org.springframework.web.filter.CharacterEncodingFilter用于解决POST方式造成的中文乱码问题  -->
  <filter>
     <filter-name>encodingFilter</filter-name>
     <filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
     <init-param>
         <param-name>encoding</param-name>
         <param-value>UTF-8</param-value>
     </init-param>
     <!-- force强制，促使 -->
     <init-param>
         <param-name>forceEncoding</param-name>
         <param-value>true</param-value>
     </init-param>
  </filter>
  <filter-mapping>
     <filter-name>encodingFilter</filter-name>
     <url-pattern>/*</url-pattern>
  </filter-mapping>
  #+END_EXAMPLE

   [[MyBatis Spring Adapter][https://github.com/mybatis/spring]]

** 另一个部分   

   通过IOC实现即插即拔功能。
   通过AOP框架将数据库事务委托给Spring处理。
   - 默认情况下抛出异常后，将引发事务回滚。
   - 事务隔离级别
     Oracle支持读写提交(默认)和序列化，MySQL支持可重复读(默认)
     1) 脏读，一个事务能读取另外一个事务未提交的数据，导致 *脏读*
     2) 读写提交，一个事务还没结束，其之前读取过的数据已经被修改了，导致 *不可重复读*
     3) 可重复读，一个事务还没结束，其读取的记录数被删减或增加了，导致 *幻读*
     4) 序列化
   - 传播行为
     用于指示方法调用的问题，Spring中定义了7中传播行为。
     | 传播行为                  | 含义                                                         |
     |---------------------------+--------------------------------------------------------------|
     | PROPAGATION_REQUIRED      | 若存在一个事务，则加入该事务。否则创建新事务                 |
     | PROPAGATION_SUPPORTS      | 若存在一个事务，则加入该事务。否则以非事务方式执行           |
     | PROPAGATION_MANDATORY     | 若存在一个事务，则加入该事务。否则抛出异常                   |
     | PROPAGATION_REQUIRES_NEW  | 总是创建新事务。若已存在一个事务，则将该已存在的事务挂起     |
     | PROPAGATION_NOT_SUPPORTED | 总以非事务方式执行。若已存在一个事务，则将该已存在的事务挂起 |
     | PROPAGATION_NEVER         | 总以非事务方式执行。若已存在一个事务，则抛出异常             |
     | PROPAGATION_NESTED        | 若存在一个活动事务，则运行在一个嵌套的事务中。否则创建新事务 |
     - 自调用
       由于insertRoleList调用自身的insertRole方法时并不是调用动态代理类实例的方法，因此并没有触发动态代理类的invoke方法，而Spring事务处理逻辑均写在invoke方法中，因此insertRole会在insertRoleList所属的事务上下文中执行。
       #+BEGIN_EXAMPLE java
       @Service
       public class RoleServiceImpl {
         @Autowired
         private RoleDAO roleDAO;

         @Transactional(isolation=Isolation.READ_COMMITTED, propagation=Propagation.REQUIRED)
         public int insertRoleList(List<Role> roleList){
           for (Role role : roleList){
             this.insertRole(role);
           }
         }

         @Transactional(isolation=Isolation.READ_COMMITTED, propagation=Propagation.REQUIRED_NEW)
         public int insertRole(Role role){
           roleDAO.insert(role);
         }
       }
       #+END_EXAMPLE

** 通过注解方式配置
   通过SqlSessionTemplate来使用SqlSession，从而得到Mapper。

* 增强工具

** [[http://www.mybatis.org/generator/][MyBatisGenerator]]
   MyBatis代码生成器，可根据数据库表生成相关代码
   - POJO
   - Mapper接口
   - SQL Mapper XML

** [[https://pagehelper.github.io][MyBatisPageHelper]]
   - 支持多种数据库
   - 支持多种分支方式
