JPA(Java Persistent API)，作为Java EE官方标准的一种ORM规范，并不是ORM产品，具体通用性。规范中对数据库结构提供较完整的封装，如Hibernat那样从POJO到数据库表的映射关系，通过规范/框架提供的存储逻辑自动生成对应的SQL并自动调用JDBC接口来执行。

PO(Persistent Object,持久化对象)，通过该对象可对数据库执行增、删、改的操作，以面向对象的方式操作数据库。

JTA(Java Transaction API)

JDBC(Java Data Base Connectivity)是由SUN公司提出的一系列规范接口，具体实现由数据库厂商实现，是一种典型的桥接模式。

DriverManager，操作一次数据库都重新建立一个数据库链接。
DataSource，提供数据库连接池优化对数据库的操作。实现javax.sql.DataSource接口，因此可以为任意第三方数据源，也可以通过JNDI从容器中获取的数据源。

JavaBeans
为符合特定规范的Java类：
1) 公有类
2) 私有字段
3) 公有getter和setter
4) 无参构造方法

* 资源
  官方GitHub主页：https://github.com/mybatis

* 简单示例
  - src/mybatis-config.xml
    #+BEGIN_EXAMPLE xml
    <?xml version="1.0" encoding="UTF-8" ?>
    <!DOCTYPE configuration
      PUBLIC "-//mybatis.org/DTD Config 3.0//EN"
      "http://mybatis.org/dtd/mybatis-3-config.dtd">
    <configuration>
        <!-- 指定Myatis所用日志的具体实现 -->
        <settings>
            <setting name="logImpl" value="LOG4J2"/>
        </settings>
        <!-- 数据库环境配置 -->
        <environments default="sqlite">
            <environment id="sqlite">
                <transactionManager type="JDBC"/>
                <dataSource type="POOLED">
                    <property name="driver" value="org.sqlite.JDBC"/>
                    <property name="url" value="jdbc:sqlite:/path/to/example.db"/>
                    <property name="username" value=""/>
                    <property name="password" value=""/>                    
                </dataSource>
            </environment>
        </environments>
        <mappers>
            <mapper resource="org/john/mapper/UserMapper.xml"/>
        </mappers>
    </configuration>
    #+END_EXAMPLE
  - PO
    #+BEGIN_EXAMPLE java
    package org.john.domain;
    // src/org/john/domain/User.java
  
    public class User {
        private Integer id;
        private String name;
        // setter,getter
    }
    #+END_EXAMPLE
  - SQL映射文件
    #+BEGIN_EXAMPLE xml
    <!-- org/john/mapper/UserMapper.xml-->
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0/EN"
     "http://mybatis.org/data/mybatis-3-mapper.dtd">
    <!-- namespace必须全局唯一，一般命名方式为<包名>+<SQL映射文件名> -->
    <mapper namespace="org.john.mapper.UserMapper">
       <!-- useGeneratedKeys表示使用数据库的自动增长策略需要底层数据库的支持 -->
       <insert id="save" parameterType="org.john.domain.User" useGeneratedKeys="true"> 
           INSERT INTO USER(name) values(#{name})
       </insert>
    </mapper>
    #+END_EXAMPLE
  - Mapper接口
    #+BEGIN_EXAMPLE java
    package org.john.mapper;
    import org.john.domain.User;
    
    public interface UserMapper {
      public boolean save(User user);
    }
    #+END_EXAMPLE
  - log4j2.xml
    #+BEGIN_EXAMPLE
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
      <Appenders>
        <Console name="stdout" target="SYSTEM_OUT">
          <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>
      </Appenders>
      <Loggers>
        <Root level="TRACE">
          <AppenderRef ref="stdout"/>
        </Root>
      </Loggers>
    </Configuration>
    #+END_EXAMPLE
  - 程序入口
    #+BEGIN_EXAMPLE java
    package org.john;
    
    public static class App {
        public static void main(String[] args) {
            InputStream configStream = Resources.getResourceAsStream("mybatis-config.xml");
            SqlSessionFactory sessionFactory = new SqlSessionFactoryBuilder().build(configStream);
            SqlSession session = sessionFactory.openSession();
            
            User user = new User();
            user.setName("john");

            /* 通过SQL映射文件中的namespace+id的方式操作数据库
               缺点: 
                 1. 编译器无法在编译时检查字符串指定的namespace+id的合法性;
                 2. SqlSession的insert/update/delete等方法入参均为Object，无法在编译时限制入参类型; 
                 3. 非面向对象的编程风格。
             */
            try{
              session.insert("org.john.mapper.UserMapper.save", user);
              session.commit();
            } finally {
              session.close();
            }

            /* 通过Mapper接口的方式操作数据库
               SqlSession.getMapper方法会根据Mapper接口生成和返回代理类org.apache.ibatis.binding.MapperProxy，然后在代理类通过方法签名获取MapperMethod来执行操作
             */
           try{
             UserMapper userMapper = session.getMapper(org.john.mapper.UserMapper.class);
             userMapper.save(user);
             System.out.println(userMapper.class); // 返回的是Proxy
             session.commit();
           } finally {
             session.close();
           }
        }
    }
    #+END_EXAMPLE

* 核心对象

- ~SqlSessionFactoryBuilder~, 读取MyBatis的XML配置文件或预制定的Configuration对象初始化SqlSessionFactory。
  - 读取MyBatis的XML配置文件初始化SqlSessionFactory实例
    1) 通过 ~Resources.getResourceAsStream("mybatis-config.xml")~ 读取XML配置文件并将其构建为输入流
    2) 将输入流传给 ~new SqlSessionFactoryBuilder().build~, 内部构建XMLConfigBuilder实例并通过其方法parse，解析XML配置文件内容并返回 ~org.apache.ibatis.session.Configuration~ 实例
    3) SqlSessionFactoryBuilder根据Configuration实例创建一个DefaultSessionFactory实例，并返回给调用者使用。
- ~SqlSessionFactory~, 为单个数据库映射关系经过编译后的内存镜像。
  - 通过方法 ~new SqlSessionFactoryBuilder().build~ 从XML配置文件或一个预先定制的Configuration实例构建出来。
  - 线性安全。
  - 建议使用单例模式，在应用运行期间常存且避免重复创建。
  #+BEGIN_EXAMPLE java
  package org.john;
  import org.apache.ibatis.io.Resources;
  import org.apache.ibatis.session.SqlSession;
  import org.apache.ibatis.session.SqlSessionFactory;
  import org.apache.ibatis.session.SqlSessionFactoryBuilder;

  public class SqlSessionTemplate {
    private static SqlSessionFactory sqlSessionFactory = null;
    static {
      try{
        InputStream inputStream = Resources.getResourceAsStream("mybatis-config.xml");
        sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
      } catch (Exception e) {
        e.printStackTrace();
      }
    }

    public static SqlSession getSqlSession(){
      return sqlSessionFactory.openSession();
    }
  }

  public class App {
      public static void main(String[] args) {
      SqlSession session = SqlSessionTemplate.getSqlSession();
    }
  }
  #+END_EXAMPLE
  - 底层封装了DataSource。
  - 常用方法
    - ~SqlSession openSession()~
- ~SqlSession~, 持久化操作对象。
  和 ~Connection~ 对象一样为非线程安全对象，因此每次使用时必须重新创建一个。
p  - 常用方法
    - ~int insert(String statement)~, statement为在mapper.xml中元素 ~<insert>~ 的id值
    - ~int insert(String statement, Obejct parameter)~, statement为在mapper.xml中元素 ~<insert>~ 的id值
    - ~int update(String statement)~, statement为在mapper.xml中元素 ~<update>~ 的id值
    - ~int update(String statement, Object parameter)~, statement为在mapper.xml中元素 ~<update>~ 的id值
    - ~int delete(String statement)~, statement为在mapper.xml中元素 ~<delete>~ 的id值
    - ~int delete(String statement, Object parameter)~, statement为在mapper.xml中元素 ~<delete>~ 的id值
    - ~<T> T selectOne(String statement)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - ~<T> T selectOne(String statement, Object parameter)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - ~<E> List<E> selectList(String statement)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - ~<E> List<E> selectList(String statement, Object parameter)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - ~<E> List<E> selectList(String statement, Object parameter, RowBounds rowBounds)~, statement为在mapper.xml中元素 ~<select>~ 的id值
      - rowBounds用于分页，属性offset为查询的当前页数，属性limit为显示多少条数据。
    - ~<K,V> Map<K,V> selectMap(String statement, String mapKey)~, statement为在mapper.xml中元素 ~<select>~ 的id值
      - mapKey用于指定表中的一个列名。
    - ~<K,V> Map<K,V> selectMap(String statement, Object parameter, String mapKey)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - ~<K,V> Map<K,V> selectMap(String statement, Object parameter, String mapKey, RowBounds rowBounds)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - ~void select(String statement, ResultHandler handler)~, statement为在mapper.xml中元素 ~<select>~ 的id值
      - handler为用于处理查询返回的复杂结果集，通常用于多表查询。
    - ~void select(String statement, Object parameter, ResultHandler handler)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - ~void select(String statement, Object parameter, RowBounds rowBounds, ResultHandler handler)~, statement为在mapper.xml中元素 ~<select>~ 的id值
    - ~void commit()~
    - ~void rollback()~
    - ~void close()~
    - ~Connection getConnection()~
    - ~<T> T getMapper(Class<T> type)~, 返回mapper接口的代理对象，该对象关联了SqlSession对象，可以通过该对象直接调用方法操作数据库，参数type是Mapper的接口类型。MyBatis建议通过mapper对象访问MyBatis。

* MyBatis配置文件
  默认配置信息已经在org.apache.ibatis.session.Configuration类中设置。(在Eclipse中通过Navigation/Open Type工具查看)
  #+BEGIN_EXAMPLE xml
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE configuration
    PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
    "http://mybatis.org/dtd/mybatis-3-config.dtd">
  <configuration>
      <!-- 设置内联属性或引入外部配置，并在当前文档中动态替换。
           1. 设置内联属性
           <properties>
             <property name="prop_name" value="prop_value"/>
           </properties>
           2. 引入外部配置的资源定位方式
           resource: 通过类路径引入，如org/john/test.xml。类路径就是编译后以lib或target为父目录的路径
           url: 通过网络或本地路径引入，http://www.test.com/test.xml或file:///c:\test.xml

           加载顺序
           1. 读取property子元素的值
           2. 根据properies元素的resource或url读取属性文件，并覆盖同名属性值
           3. 读取作为方法参数传递的属性值，并覆盖同名属性值

           
           示例：
           1. 通过方法传递属性值
              InputStream cfgStream = Resources.getResourceAsStream("mybatis-config.xml")
              InputStream propsStream = Resources.getResourceAsStream("db.properties");
              Properties props = new Properties();
              props.load(propsStream);
              SqlSessionFactory factory = new SqlSessionFactoryBuilder().build(cfgStream, props);

           2. 外部db.properties的内容为
                 username=root
                 password=root
              配置文件中其他部分动态替换为
              <property name="username" value="${username}"/>
              <property name="password" value="${password}"/>
        -->
      <properties resource="db.properties"/>
      <!-- 改变MyBatis运行时行为 -->
      <settings>
          <!--开启映射器的缓存-->
          <setting name="cacheEnabled" value="true"/>
          <!--开启关联对象延迟加载，在特定关联关系中可通过设置fetchType属性来覆盖该属性值，默认值为false。
              立即加载的好处是多条SQL一次性发送，性能更高。
              延迟加载的实现原理是通过动态代理
            -->
          <setting name="lazyLoadingEnabled" value="true"/>
          <!--为true时会使带有延迟加载属性的对象立即被完整加载，即加载对象及与其直接关联的对象，而不立即加载间接的对象。默认值为true。
              因此要启用延迟加载，那么lazyLoadingEnabled需要设置为true，并且aggressiveLazyLoading为false-->
          <setting name="aggressiveLazyLoading" value="false"/>
          <!--允许单一语句返回多结果集-->
          <setting name="multipleResultSetsEnabled" value="true"/>
          <!--使用列标签代替列名，具体表现依赖数据库驱动-->
          <setting name="useColumnLabel" value="true"/>
          <!--允许JDBC支持自动生成主键-->
          <setting name="useGeneratedKeys" value="false"/>
          <!--设置MyBatis如何自动映射列到字段
              NONE, 取消自动映射
              PARTIAL, 只自动映射没有定义嵌套结果映射的结果集（默认值），要求列名和javaBean属性名一致
              FULL, 自动映射任意复杂的结果集
            -->
          <setting name="autoMappingBehavior" value="PARTIAL"/>
          <!--自动映射时发现未知数据表列的时应如何处理
              NONE, 不处理（默认值）
              WARNING, 输出警告
              FAILING, 映射失败，抛出SqlSessionException
            -->
          <setting name="autoMappingUnknownColumnBehavior" value="WARNING"/>
          <!--配置默认的执行器
              SIMPLE, 普通的执行器（默认值）
              REUSE, 执行器会重用预处理语句(prepared statements)
              BATCH, 执行器将重用语句并执行批量更新
            -->
          <setting name="defaultExecutorType" value="SIMPLE"/>
          <!--超时时间，决定驱动等待数据库响应的秒数-->
          <setting name="defaultStatementTimeout" value="25"/>
          <!--默认返回的结果集的大小-->
          <setting name="defaultFetchSize" value="100"/>
          <!--允许在嵌套语句中使用分页，默认值为false-->
          <setting name="safeRowBoundsEnabled" value="false"/>
          <!--开启自动驼峰命名规则，默认值为false
              即数据库表字段为A_COL，自动对应POJO成员变量aCol
            -->
          <setting name="mapUnderscoreToCamelCase" value="false"/>
          <!--MyBatis3.3+利用本地缓存机制(local cache)防止循环引用(circular references)和加速重复嵌套查询。
              SESSION, 缓存一个会话中执行的所有查询（默认值）,即启用一级缓存
              STATEMENT, 相同SqlSession的不同调用将不会共享数据，即禁用一级缓存
            -->
          <setting name="localCacheScope" value="SESSION"/>
          <!--当没有为参数提供特定的JDBC类型时，为空值(null)指定原生JDBC的类型。
              NULL
              VARCHAR
              OTHER（默认值）,MySQL能识别这个值，但Oracle不能识别因此会导致在Oracle插入空值时会报错，即使在表字段可空
            -->
          <setting name="jdbcTypeForNull" value="OTHER"/>
          <!--指定哪个对象的方法触发一次延迟加载，属性值设置为方法名的list集合-->
          <setting name="lazyLoadTriggerMethods" value="equals,clone,hashCode,toString"/>
          <!--指定MyBatis增加到日志名称的前缀-->
          <setting name="logPrefix" value="MyBatis"/>
          <!--指定MyBatis所用日志的具体实现，未指定时将自动查找
              值范围：SLF4J|LOG4J|LOG4J2|JDK_LOGGING|COMMONS_LOGGING|STDOUT_LOGGING|NO_LOGGING
            -->
          <setting name="logImpl" value="LOG4J2"/>
          <!--指定创建具有延迟加载能力的对象所用到的代理工具
              CGLIB(3.3以前的默认值)
              JAVASSIT(3.3以后的默认值)
            -->
          <setting name="proxyFactory" value="CGLIB"/>
          <!--指定当结果集中值为null时是否调用映射对象的setter方法。对于primitive type(int,boolean等)是不能设置为null的-->
          <setting name="callSettersOnNulls" value="false"/>
          <!-- JDK1.8后才能使用，用于启用SQL映射文件入参名称与Mapper接口方法型参名称一致 -->
          <setting name="useActualParamName" value="true"/>
      </settings>

      <!--设置所有SQL映射文件内使用的类型别名-->
      <typeAliases>
          <!-- 为类型org.john.domain.User设置别名user
               1) 若仅设置type值，则别名为以首字母小写的非限定类型名称
               2) 别名不区分大小写，因此一般用小写
            -->
          <typeAlias alias="user" type="org.john.domain.User"/>
          <!-- MyBatis扫描指定包下的所有类型
               1) 通过@Alias("alias_name")标识的类型，则以注解值作为别名
               2) 否则，以首字母小写的非限定类型名称作为别名
            -->
          <package name="org.john.mapper"/>
      </typeAilases>

      <!--typeHandlers(类型处理器)
          在预处理语句(PreparedStatement)中设置一个参数 和 从结果集中取出一个值时，都会通过typeHandler将取出的值从Java类型转换为数据库类型，或从数据库类型转换为Java类型。
          日期和时间的处理在JDK1.8以前一直是个头痛的问题。通常会使用JSR310规范领导者Stephen Colebourne创建的Joda-Time来操作。JDK1.8已经实现全部JSR310规范。
          MyBatis3.4以前需要使用JSR310规范操作日期时间，那么就要手工引入mybatis-typehandlers-jsr310包的typeHandlers。
          MyBatis3.4后已经内置并自动引入JSR310的typeHandler了。
        -->
      <typeHandlers>
          <!-- 
            1. 通过jdbcType和javaType作为匹配标识，注册自定义/第三方类型转换器。
               若SQL映射文件中result节点的jdbcType、javaType和typeHandler节点的匹配时，则自动采用handler属性执行的类型转换器。
               若SQL映射文件中变量绑定如 #{roleName javaType=string, jdbcType=VARCHAR}，则自动采用handler属性执行的类型转换器。
            2. 若SQL映射文件中result节点指定typeHandler属性则直接将其作为类型转换器。
               若SQL映射文件中变量绑定如 #{roleName ,typeHandler=com.john.typeHandler.MyStringTypeHandler}，则直接将其作为类型转换器。
            -->
          <typeHandler jdbcType="VARCHAR" javaType="string" handler="com.john.typeHandler.MyStringTypeHandler"/>

          <!-- 也可通过包扫描注册，那么jdbcType和javaType就采用注解MappedTypes和MappedJdbcTypes的值 -->
          <package name="com.john.typeHandler"/>
      </typeHandlers>

      <!-- plugins(插件)
           能够在以下4大核心对象的方法前后进行拦截
           Executor(update,query,flushStatements,commit,rollback,getTransaction,close,isClosed)
           ParameterHandler(getParameterObject,setParameters)
           ResultSetHandler(handleResultSets,handleOutputParameters)
           StatementHandler(prepare,parameterize,batch,update,query)
        -->

      <!-- objectFactory(对象工厂)
           在创建结果对象实例时，会使用对象工厂去构建POJO。
           默认的ObjectFactory为org.apache.ibatis.reflection.factory.DefaultObjectFactory
           <objectFactory type="com.john.factory.MyObjectFactory">
             <property name="name" value="MyObjectFactory"/>
           </objectFactory>
        -->

      <!--数据源列表-->
      <environments default="dev">
          <environment id="dev">
              <!-- 每个environment节点下必须包含transactionManager和dataSource节点 -->
              <!--数据库事务管理配置，结合Spring时Spring会使用自带的管理器来覆盖这部分的设置。
                  1. JDBC, 直接使用JDBC的提交和回滚设置，依赖从数据源得到的连接来管理事务范围。(JdbcTransactionFactory)
                    <transactionManager type="JDBC">
                      <property name="autoCommit" value="false"/> <!-- 自动提交事务，默认为true -->
                    </transactionManager>
                  2. MANAGED, 让容器来管理事务的整个生命周期，在JNDI数据源中经常使用，它执行事务提交和回滚，而是交由容器处理。(ManagedTransactionFactory)

                  3. 自定义事务管理器，通过实现TranscationManager接口即可，然后type值指定自定义事务管理器的全限定类名
                -->
              <transactionManager type="MANAGED">
                  <property name="closeConnection" value="false"/>
              </transactionManager>
              <!--
                  UNPOOLED, 每次请求时打开和关闭数据库连接(UnpooledDataSourceFactory)
                  POOLED, 启用数据库连接池(PooledDataSourceFactory)
                    - poolMaximumActiveConnections, 在任意时间最大的正使用的连接数，默认值为10
                    - poolMaximumIdleConnections, 在任意时间最大的空闲连接数
                    - poolMaximumCheckoutTime, 在被强制返回前，池中连接被checkout的时间，默认值2000ms
                    - poolTimeToWait, 等待获取可用连接的超时时间，若超时则创建一个新的连接，默认值2000ms
                    - poolPingQuery, 发送到数据库的侦测查询，用于检查连接是否处于正常工作状态。默认值为NO PING QUERY SET
                    - poolPingEnabled, 启用数据库的侦测查询，默认值为false。启用后要设置poolPingQuery为用于侦测用的SQL语句。
                    - poolPingConnectionsNotUsedFor, 配置poolPingQuery的执行频率
                  JNDI, 使用EJB或应用服务器容器中配置的数据源(JndiDataSourceFactory)
                    - initial_context, 调用initialContext.lookup(initial_context)寻找JNDI上下文，若忽略那么属性data_source将会直接从InitialContext中寻找。
                    - data_source, 引用数据源实例位置的上下文路径
                      <dataSource type="JNDI">
                          <property name="initial_context" value="java:/comp/env"/>
                          <property name="data_source" value="fkjavads"/>
                      </dataSource>
                  自定义数据源，通过实现org.apache.ibatis.datasource.DataSourceFactory接口即可，然后type值指定自定义数据源的全限定类名
                    - 如使用DBCP数据源
                      package com.john.datasource;
                      public class DbcpDataSourceFactory extends BasicDataSource impelements DataSourceFactory {
                        private Properties props = null;
                        @Override
                        public void setProperties(Properties props){
                          this.props = props;
                        }
                        @Override
                        public DataSource getDataSource(){
                          DataSource ds = null;
                          try{
                            ds = BasicDataSourceFactory.createDataSource(props);
                          }
                          catch (Exception e){}
                          return ds;
                        }
                      }
                      <dataSource type="com.john.datasource.DbcpDataSourceFactory">
                      </dataSource>
                    - 如使用c3p0数据源
                    ?????
                -->
              <dataSource type="POOLED">
                  <property name="driver" value="${driver}"/>
                  <property name="url" value="${url}"/>
                  <property name="username" value="${username}"/>
                  <property name="password" value="${password}"/>
              </dataSource>
          </environment>
      </environments>
      
      <!-- 数据库厂商标识
           在SQL映射文件中select/update/delete等节点可使用datasourceId标识该语句是在哪个数据库厂商上才执行，
           然后会调用sqlSessionFactory.getConfiguration().getDatabaeId()获取当前正操作的数据库厂商标识，
           然后从SQL映射文件中加载匹配datasourceId值的语句和没有设置datasourceId属性的语句，
           datasourceId值和sqlSessionFactory.getConfiguration().getDatabaeId()相同的语句执行优先级没有datasourceId属性的语句要高。

           DB_VENDOR为内部注册的策略器，当连接数据库后会通过getDatabaseProductName()获取数据库厂商标识，并用于与
           <property name value/> 中的name属性值匹配，命中则将value属性值作为参数调用sqlSessionFactory.getConfiguration().setDatabaseId(String id)；
           若没有命中，或没有配置则sqlSessionFactory.getConfiguration().getDatabaeId()恒返回null。
        -->
      <databaseIdProvider type="DB_VENDOR">
          <property name="SQL Server" value="sqlserver"/>
          <property name="DB2" value="db2"/>
          <property name="Oracle" value="oracle"/>
          <property name="MySQL" value="mysql"/>
      </databaseIdProvider>

      <!--配置映射文件-->
      <mappers>
          <!--使用类路径查找-->
          <mapper resource="org/john/mapper/UserMapper.xml"/>
          <!--使用本地文件路径查找-->
          <mapper url="file:///project/org/john/mapper/UserMapper.xml"/>
          <!--使用接口全限定名称
              1) 若使用SQL映射文件与Mapper接口关联，则必须遵循一下规则
                 1) SQL映射文件必须和接口位于同一个包下，并且文件名必须相同
                 2) SQL映射文件内的namespace必须为Mapper接口的全限定名称，select/update/delete等节点的id必须和Mapper接口的方法名一一对应
              2) 若使用注解将SQL语句与Mapper接口内方法进行关联，则直接使用即可
            -->
          <mapper class="org.john.mapper.UserMapper"/>
          <!--使用包名，规则和使用接口全限定名称一样-->
          <package name="org.john.mapper"/>
      </mappers>
  </configuration>
  #+END_EXAMPLE

** 自定义类型转换器
#+BEGIN_EXAMPLE java
package com.john.typeHandler;

@MapperTypes({String.class}) // 设置拦截哪些Java类型
@MapperJdbcTypes({JdbcType.VARCHAR}) // 设置拦截哪些Jdbc类型，必须为枚举类org.apache.ibatis.type.JdbcType所列的枚举类型
public class MyStringTypeHandler implements TypeHandler<String> {
  @Override
  public void setParameter(PreparedStatement ps, int index, String value, JdbcType jt) throws SQLException {
    ps.setString(index, value);
  }
  @Override
  public String getResult(ResultSet rs, String colName) throws SQLException {
    return rs.getString(ColName);
  }
  @Override
  public String getResult(ResultSet rs, int index) throws SQLException {
    return rs.getString(index);
  }
  @Override
  public String getResult(CallableStatement cs, int index) throws SQLException {
    return cs.getString(index);
  }
}
#+END_EXAMPLE

** 枚举类型typeHandler
- ~org.apache.ibatis.type.EnumTypeHandler~ ，使用枚举字符串名称作为参数传递
  - 示例:
    数据库USER表的SEX字段0为male，1为female
    #+BEGIN_EXAMPLE java
    package com.john.enums;
    public enum Sex {
      MALE, FEMALE;
    }
    #+END_EXAMPLE
    #+BEGIN_EXAMPLE xml
    <!-- mybatis-config.xml -->
    <typeHandlers>
      <typeHandler handler="org.apache.ibatis.type.EnumOrdinalTypeHandler" javaType="com.john.enums.Sex"/>
    </typeHandlers>

    <!-- mapper.xml -->
    <resultMap id="a" type="com.john.domain.User">
      <result column="sex" property="sex" typeHandler="org.apache.ibatis.type.EnumOrdinalTypeHandler"/>
    </resultMap>
    <select resultMap="a">
      select * from user where sex = #{sex, typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler}
    </select>
    #+END_EXAMPLE
- ~org.apache.ibatis.type.EnumOrdinalTypeHandler~ ，使用整数下标作为参数传递
  - 示例:
    数据库USER表的SEX字段MALE和FEMALE
    #+BEGIN_EXAMPLE xml
    <!-- mybatis-config.xml -->
    <typeHandlers>
      <typeHandler handler="org.apache.ibatis.type.EnumTypeHandler" javaType="com.john.enums.Sex"/>
    </typeHandlers>

    <!-- mapper.xml -->
    <resultMap id="a" type="com.john.domain.User">
      <result column="sex" property="sex" typeHandler="org.apache.ibatis.type.EnumTypeHandler"/>
    </resultMap>
    <select resultMap="a">
      select * from user where sex = #{sex, typeHandler=org.apache.ibatis.type.EnumTypeHandler}
    </select>
    #+END_EXAMPLE

*** 自定义枚举类型转换器
#+BEGIN_EXAMPLE java
package com.john.enums;
public enum Sex {
  MALE(1), FEMALE(2);

  private int id;
  
  public int getId(){
    return this.id;
  }

  private Sex(int id){
    this.id = id;
  }

  public static Sex getSex(int id){
    if (id == 1){
      return MALE;
    }
    else if (id == 2){
      return FEMALE;
    }

    return null;
  }
}
#+END_EXAMPLE
#+BEGIN_EXAMPLE java
package com.john.typeHandler;
@MappedTypes({Sex.class})
@MappedJdbcTypes({Jdbc.NUMERIC})
public class SexEnumTypeHandler implements TypeHandler<Sex>{
  @Override
  public Sex getResult(ResultSet rs, String name) throws SQLException {
    int id = rs.getInt(name);
    return Sex.getSex(id);
  }

  @Override
  public Sex getResult(ResultSet rs, int index) throws SQLException {
    int id = rs.getInt(index);
    return Sex.getSex(id);
  }

  @Override
  public Sex getResult(CallableStatement cs, int index) throws SQLException {
    int id = cs.getInt(index);
    retunr Sex.getSex(id);
  }

  public void setParameter(PreparedStatement ps, int index, Sex sex, JdbcType jdbcType) throws SQLException{
    int id = sex.getId();
    ps.setInt(index, id);
  }
}
#+END_EXAMPLE
#+BEGIN_EXAMPLE xml
<!-- mybatis-config.xml -->
<typeHandlers>
  <typeHandler handler="com.john.typeHandler.SexEnumTypeHandler" javaType="com.john.enums.Sex"/>
</typeHandlers>
#+END_EXAMPLE

** BLOB类型typeHandler
   内置BlobTypeHandler和BlobByteObjectArrayTypeHandler，而后者是为了兼容性一般很少用。
   只需数据库表字段为Blob，而Domain entity的属性类型为byte[]，那么就会自动使用BlobTypeHandler作数据类型处理。

* SQL映射文件配置
  *注意：* 与select/update/delete语句对应的Mapper接口方法，其返回值默认可设置为 ~void,int,long,boolean,Integer,Long,Boolean~ 来获取操作所影响的记录数目。

** 基本映射配置
   #+BEGIN_EXAMPLE xml
   <mapper namespace="john.mybatis.mapper.UserMapper">

   <!-- select, 映射查询语句
        属性：
          - id, 在mapper的namespace下唯一的标识符
          - parameterType, 可选属性，入参的完全限定类名或别名
          - resultType, 返回值类型的完全限定名或别名，和属性resultMap不能同时使用
          - resultMap, 外部resultMap的命名引用，用于复杂的映射。和属性resultType不能同时使用
          - flushCache, 为true时只要语句被调用，都会导致本地缓存和二级缓存都被清空，默认值为false
          - useCache, 为true时语句执行结果被二级缓存，为false时禁用二级缓存。select语句中默认值为true
          - timeout, 返回请求结果超时时间
          - fetchSize, 每次返回的结果的最大行数，默认值由数据库厂商提供的JDBC驱动所设置的
          - statementType, STATEMENT/PREPARED/CALLABLE对应JDBC的Statement/PreparedStatement/CallableStatement。默认值为PREPARED。
          - resultSetType, 结果集类型，默认值由数据库厂商提供的JDBC驱动所设置的。取值范围
              FORWARD_ONLY：允许游标向前访问
              SCROLL_SENSITIVE：允许游标前后访问，若数据在被访问后被修改或删除则会通知游标更新
              SCROLL_INSENSITIVE：允许游标前后访问，若数据在被访问后被修改或删除则不会通知游标更新
          - databaseId, 若在mybatis-config.xml中设置databaseIdProvider，则该属性值可设置为databaseIdProvider中设置的数据库厂商别名，否则要设置为数据库厂商全名如“Oracle”,"SQL Server","MySQL","DB2"。
                        MyBaits会从Connection实例中获取当前操作的数据库信息，然后加载所有不带databaseId或匹配当期那databaseId的语句。
                        元素内部也可通过 <if test="_databaseId = 'oracle'"></if> 来书写针对特定数据库的SQL语句
          - resultOrdered, 仅针对嵌套结果的select语句适用。节省内存空间。默认值为false
          - resultSets, 针对多个结果集的情况，给每个结果集列出一个别名，别名间以逗号分隔
     -->
   <!-- 接口方法为 public Map<String, Object> selectUser(int id) -->    
   <select id="selectUser" parameterType="int" resultType="map" databaseId="mysql">
     SELECT * FROM USER WHERE ID = #{id}
   </select>
   
   <!-- 接口方法为 public List<User> selectUsers() -->
   <!-- 接口方法为 
        @MapKey("id") // 指定用User的id作为Map的键名
        public Map<String, User> selectUsers() -->
   <select id="selectUsers" resultType="org.john.domain.User">
     SELECT * FROM USER
   </select>

   <!-- 调用时直接传入 "%john%" 即可 -->
   <select id="selectUsersLike" resultType="org.john.domain.User">
     select * from user where name like #{namelike}
   </select>

   <!-- 对于支持主键自增的数据库(如MySQL,SQLServer支持auto-generated key field)
        属性：
          - userGeneratedKeys，默认值为false，用于设置是否获取数据库自增主键值，并且需要通过keyProperty指定将该值保存到POJO的哪个变量中
            java.sql.Statement中提供一个java.sql.ResultSet getGeneratedKeys()的方法获取数据库自增主键值，而该属性即告知MyBatis调用该方法获取自增主键值
          - keyProperty, 默认值为unset,用于设置通过数据库的getGeneratedKeys方法或<selectKey>子元素获取的返回值，将赋值到领域模型的哪个属性中
          - keyColumn, 设置数据库自增的主键名。对特定数据库(如PostgreSQL)，若自增的主键不为第一个字段则必须设置
        示例
        // Mapper接口
        public int insert(User user);

        // 使用
        UserMapper userMapper = session.getMapper(UserMapper.class);
        User user = new User();
        user.setName("john");
        int count = userMapper.save(user);
        System.out.println(string.format("影响的记录数: %s", count));
        System.out.println(string.format("自增主键值: %s", user.getId()));
     -->
   <insert id="insertUser1" useGeneratedKeys="true" keyProperty="id">
     insert into User(name) values(#{name})
   </insert>
    
   <!-- 对于不支持主键自增的数据库(如Oracle不支持auto-generated key field) -->
   <insert id="insertUser2">
     <!-- <selectKey>在<insert>和<update>元素中插入查询语句
          属性：
            - keyProperty, 默认值为unset,用于设置将selectKey操作结果赋值到领域模型的哪个属性中
            - resultType, 返回值类型的完全限定名或别名
            - order, 取值范围BEFORE/AFTER，表示在执行insert/update语句前/后执行selectKey操作
            - statementType, STATEMENT/PREPARED/CALLABLE对应JDBC的Statement/PreparedStatement/CallableStatement。默认值为PREPARED。
       -->
     <selectKey keyProperty="id" resultType="_int" order=“BEFORE" statementType="PREPARED">
       select squence_user.nextval as id from dual
     </selectKey>
     insert into User(id, name) values(#{id}, #{name})
   </insert>

   <!-- <update> 和 <delete> 类似 -->

   <!--sql, 可被其他语句引用的可重用语句块，可循环引用-->
   <sql id="userColumns">
     ${alias}.id, ${alias}.name
   </sql>
   <select id="findUser">
     select
     <include refid="userColumns">
         <property name="alias" value="t1"/>
     </include>
     from User t1
   </select>

   <!--resultMap, 当结果集列名与返回值类型的字段名称不匹配时，通过resultMap设置映射关系
       属性：
         - id, resultMap标签的标识
         - type, 返回值的完全限定类型或别名
         - autoMapping, 默认值为true，自动映射为自动查找与字段名小写同名的属性名，并调用setter方法。
       子元素：
         - <id>, 设置主键字段映射
         - <result>, 设置普通字段映射
         - <discriminator>, 设置动态映射，其下的设置会与同级映射配置整合后作为整体的映射配置
           - 属性：
              - column, 以哪个表字段值作为入参
              - javaType, 将字段值转换为哪个Java类型
           - 子元素：
              - case, 条件判断
                - 属性：
                  - value, 期待值
                  - resultType
                  - resultMap
                - 子元素：
                  - <id>
                  - <result>
     -->
   <resultMap id="userResultMap" type="org.john.domain.User">
     <id property="id" column="user_id"/>
     <result property="name" column="user_name"/>
     <result column="juniorHighSchool" property="juniorHighSchool"/>
     <discriminator column="during" javaType="_int">
       <case value="4" resultType="org.john.domain.User">
         <result column="juniorHighSchool" property="seniorHighSchool"/>
       </case>
       <case value="5" resultMap="dynamicRM"/>
       <case value="6" resultMap="dynamicRM"/>
     </discriminator>
   </resultMap>
   <resultMap id="dynamicRM" type="org.john.domain.User">
     <result column="juniorHighSchool" property="seniorHighSchool"/>
   </resultMap>
   <!-- 通过子元素<constructor>指定通过构造方法赋值来实例化领域模型
        注意：其子元素顺序必须和构造方法的参数列表顺序一致
        子元素：
          - <idArg>, 标记入参的主键
          - <arg>, 标记入参的普通字段
     -->
   <resultMap id="userResultMap1" type="org.john.domain.User">
     <constructor>
       <idArg column="ID" javaType="_long"/>
       <arg column="Name" javaType="string"/>
     </constructor>
   </resultMap>
   <select id="findUser2" resultMap="userResultMap">
     select * from user
   </select>
   #+END_EXAMPLE

** 一对一/多对一关系(~association~)
   #+BEGIN_EXAMPLE java
   package org.john.domain;

   @Data
   public class Student{
     private Integer id;
     private String name;
     private Clazz clazz;
   }
   @Data
   public class Clazz{
     private Integer id;
     private String name;
   }
   #+END_EXAMPLE

   #+BEGIN_EXAMPLE xml
   <!-- 1. 联合查询时，通过级联属性的方式进行映射 -->
   <select id="getStudentWithClassInfo" resultMap="getStudentWithClassInfo">
   select a.id, a.name, b.id class_id, b.name class_name
   from tbl_student a join tbl_class b on (a.class_id = b.id)
   </select>

   <resultMap id="getStudentWithClassInfo" type="org.john.domain.Student">
     <id property="id" column="id"/>
     <result property="name" column="name"/>
     <result property="clazz.id" column="class_id"/>
     <result property="clazz.name" column="class_name"/>
   </resultMap>

   <!-- 2. 联合查询时，通过association关联的方式进行映射 -->
   <select id="getStudentWithClassInfo" resultMap="getStudentWithClassInfo">
   select a.id, a.name, b.id class_id, b.name class_name
   from tbl_student a join tbl_class b on (a.class_id = b.id)
   </select>

   <resultMap id="getStudentWithClassInfo" type="org.john.domain.Student">
     <id property="id" column="id"/>
     <result property="name" column="name"/>
     <!-- property: 次查询结果存放的POJO属性名
          javaType: 次查询结果存放的POJO属性的数据类型
       -->
     <association property="clazz" javaType="org.john.domain.Clazz">
       <id property="id" column="class_id"/>
       <result property="name" column="class_name"/>
     </association>
   </resultMap>

   <!-- 3. 分步查询时，通过association关联的方式进行映射 -->
   <select id="getClassInfo" resultType="org.john.Clazz">
   -- 次查询
   select * from tbl_class where id = #{id}
   </select>

   <select id="getStudent" resultMap="getStudent">
   -- 主查询
   select * from tbl_student
   </select>

   <resultMap id="getStudent" type="org.john.domain.Student">
     <id property="id" column="id"/>
     <result property="name" column="name"/>     
     <!-- property: 次查询结果存放的POJO属性名
          select: 次查询的id
          column: 将主查询结果的哪个数据库表字段作为参数传递给次查询
          fetchType: 次查询执行时机
                     lazy(默认值)，懒执行，只有在mybatis-config.xml/settings中启动lazyLoadingEnabled和禁用aggressiveLazyLoading才能生效
                     eager，和主查询一起执行
          
       -->
     <association property="clazz"
                  select="org.john.mapper.ClassInfoMapper.getClassInfo" column="class_id"
                  fetchType="lazy"/>
   </resultMap>
   #+END_EXAMPLE

** 一对多关系(~collection~)
   #+BEGIN_EXAMPLE java
   package org.john.domain;

   @Data
   public class Student{
     private Integer id;
     private String name;
     private Clazz clazz;
   }
   @Data
   public class Clazz{
     private Integer id;
     private String name;
     private List<Student> students;
   }
   #+END_EXAMPLE

   #+BEGIN_EXAMPLE xml
   <!-- 1. 联合查询，通过collection实现嵌套结果集的方式 -->
   <select id="getClassInfoWithStudents" resultMap="getClassInfoWithStudents">
   select a.id, a.name, b.id student_id, b.name student_name
   from tbl_class a left join tbl_student b on (a.id=b.class_id)
   where id = #{id}
   </select>
   
   <resultMap id="getClassInfoWithStudents" type="org.john.domain.Clazz">
     <id property="id" column="id"/>
     <result property="name" column="name"/>
     <collection property="students" javaType="ArrayList" ofType="org.john.domain.Student">
       <id property="id" column="student_id"/>
       <result property="name" column="student_name"/>
     </collection>
   </resultMap>

   <!-- 2. 分步查询时，通过collection方式 -->
   <select id="getStudentByClassId" resultType="org.john.domain.Student">
   select id, name
   from tbl_student
   where class_id = #{class_id}
   </select>

   <select id="getClassInfo" resultMap="getClassInfo">
     <id property="id" column="id"/>
     <result property="name" column="name"/>
     <collection property="students" javaType="ArrayList"
                 select="org.john.mapper.StudentMapper.getStudentByClassId"
                 column="class_id"
                 fetchType="lazy">
     </collection>
   </select>
   #+END_EXAMPLE

** 向association和collection子查询传递多个参数
由于MyBatis会将参数封装到Map实例中，因此传递多个时直接传递Map字面量即可
#+BEGIN_EXAMPLE xml
<!-- column="{key1=column1, key2=column2}" -->
column="{id=class_id, name=class_name}"
#+END_EXAMPLE

* SQL映射文件中的参数
  #+BEGIN_EXAMPLE java
  // 单个入参且入参为primitive value时，入参名称随意即可
  @Select("select * from user where id = #{id123}")
  public User getUser(int id);

  // 多个入参时，MyBatis会将参数添加到Map中，而默认的key为param1~paramN或0~N
  @Select("select * from user where id = #{param1} and name = #{param2}")
  // 或者 @Select("select * from user where id = #{0} and name = #{1}")
  public User getUser(int id, int name);

  // 通过@Param注解标识命名参数，现在MyBatis封装的Map实例中键有id,1,param1,param2
  @Select("select * from user where id = #{id} and name = #{param2}")
  public User getUser(@Param("id") int id, int name);

  // POJO作为入参，MyBatis会将其字段封装到Map中，键名为字段名
  @Select("select * from user where id = #{id} and name = #{name}")
  public User getUsre(User user);

  // 直接传递一个Map实例
  @Select("select * from user where id = #{id} and name = #{name}")
  public User getUser(Map<String, String> user);

  /* 入参为Collection,List和Array时，MyBatis会将它们封装到Map中
     Collection的键名为collection
     List的键名为list
     Array的键名为array
   */
  @Select("select * from user where id = #{list[0]}")
  public List<User> getUsers(List<String> ids);

  @Select("select * from user where id = #{0} and name = #{u.name}")
  public User getUser(int id, @Param("u") User user); 
  #+END_EXAMPLE
  param1~paramN为MyBatis额外添加到Map实例中的键，无论是命令参数还是无名参数一样会生成。
  而0~N为无名参数的键，若该参数设置为命名参数则对应的索引号将被具体设置的名称所替代。

** 参数配置
#+BEGIN_EXAMPLE xml
<!-- 设置Java类型和Jdbc类型来匹配类型转换器 -->
#{age, javaType=double, jdbcType=NUMERIC}

<!-- 指定类型转换器 -->
#{age, typeHandler=MyTypeHandler}

<!-- 设置保存的精度 -->
#{age, javaType=double, jdbcType=NUMERIC, numericScale=2}
#+END_EXAMPLE

** 存储过程/函数的参数配置
#+BEGIN_EXAMPLE xml
<!-- mode: 设置参数类型，IN/OUT/INOUT
  -->
#{role, mode=OUT, jdbcType=CURSOR, javaType=ResultSet, resultMap=roleResultMap}
#+END_EXAMPLE

* 动态SQL
  MyBatis使用基于OGNL的表达式实现动态SQL，就是在条件判断、表达式计算中采用OGNL表达式。
  
** [[http://commons.apache.org/proper/commons-ognl/][OGNL(Object-Graph Navigation Language)]]
   | 功能         | 示例                                      |
   |--------------+-------------------------------------------|
   | 访问对象属性 | person.name                               |
   | 调用方法     | person.getName()                          |
   | 访问静态属性 | @java.lang.Math@PI                        |
   | 调用静态方法 | @java.util.UUID@randomUUID()              |
   | 调用构造方法 | new com.atguigu.bean.Person("admin").name |
   | 运算符       | +,-,*,/                                   |
   | 逻辑运算符   | in,not in, >, >=,<,<=,==,!=               |
   | 关系运算符   | &&,and,or                                 |
   *注意* xml中 ~<,>,",&&,||~ 等必须转义才能使用

** 动态SQL元素详解
   - if
     #+BEGIN_EXAMPLE xml
     <select id="selectEmployeeByLoginLike" parameterType="hashmap" resultType="org.john.domain.User">
     select * from user where state = 'ACTIVE'
     <if test="loginname != null and password != null and loginname != &quot;&quot;">
       and loginname = #{loginname} 
       and password = #{password}
     </if>
     </select>
     #+END_EXAMPLE
     #+BEGIN_EXAMPLE java
     public interface EmployeeMapper{
         List<User> selectEmployeeByLoginLike(HashMap<String, Object> params);
     }
     
     EmployeeMapper employeeMapper = session.getMapper(EmployeeMapper.class);
     HashMap<String, Object> params = new HashMap<String, Object>();
     params.put("loginname", "john");
     params.put("password", "123");
     List<User> users = employeemapper.selectEmployeeByLoginLike(params);
     users.forEach(user -> System.out.println(user.getName()));
     #+END_EXAMPLE
   - choose(when, otherwise)
     if...elif...else语句
     #+BEGIN_EXAMPLE xml
     <select id="selectUsers" parameterType="hashmap" resultType="org.john.domain.User">
     select * from user where state = 'ACTIVE'
     <choose>
        <when test="id != null">
        and id = #{id}
        </when>
        <when test="loginname != null and password != null">
        and loginname = #{loginname} 
        and password = #{password}
        </when>
        <otherwise>
        and sex = 'male'
        </otherwise>
     </choose>
     </select>
     #+END_EXAMPLE
   - where
     只有一个以上的if条件有值才去插入where子句，并且会自动处理多余的and或or的开头保留字。
     #+BEGIN_EXAMPLE xml
     <select id="selectUsers" parameterType="hashmap" resultType="org.john.domain.User">
     select * from user
     <where>
        <if test="state != null">
        state = #{state}
        </if>
        <if test="id != null">
        and id = #{id}
        </if>
        <if test="loginname != null and password != null">
        and loginname = #{loginname} 
        and password = #{password}
        </if>
        <if>
        and sex = 'male'
        </if>
     </where>
     </select>
     #+END_EXAMPLE
   - set
     自动处理多余的逗号
     #+BEGIN_EXAMPLE xml
     <update id="selectUsers" parameterType="hashmap">
     update user
     <set>
       <if test="loginname != null">loginname=#{loginname},</if>
       <if test="password != null">password=#{password},</if>
     </set>
     </update>
     #+END_EXAMPLE
   - foreach
     #+BEGIN_EXAMPLE xml
     <select id="selectUsers" resultType="org.john.domain.User">
     select * from user
     where id in 
     <!--当入参为List或Array时会自动添加到内部Map实例中，List入参的键名为list，Array入参的键名为array。
         属性item定义元素引用名称
         属性index定义元素索引名称, List或Array时为索引号，Map时为键名
         属性collection指定将入参哪个键值对传给foreach子句作为被循环的数据集合
       -->
     <foreach item="item_id" index="index" collection="ids" open="(" separator="," close=")">
     #{item_id}
     </foreach>
     </select>
     #+END_EXAMPLE
     - MySQL批量插入
       #+BEGIN_EXAMPLE xml
       <!-- 1. MySQL支持insert into tbl() values(),(),()的批量插入语句 -->
       <insert id="save" databaseId="mysql">
       insert into tbl_student(id, name)
       values
         <foreach item="student" collection="param1" separator=",">
         (#{student.id}, #{student.name})
         </foreach>
       </insert>

       <!-- 2. MySQL链接参数中添加allowMultiQueries=true启用通过分号分隔来组合多条SQL语句为一条SQL语句
       <insert id="save" databaseId="mysql">
         <foreach item="student" collection="param1" separator=";">
         insert into tbl_student(id, name)
         values (#{student.id}, #{student.name})
         </foreach>
       </insert>
       #+END_EXAMPLE
     - Oracle批量插入
       #+BEGIN_EXAMPLE xml
       <insert id="save" databaseId="oracle">
       insert into tstudent(name,age) 
       <foreach collection="param1" item="student" open="(" close=")" separator="union all">
       select #{student.name} as a, #{student.age} as b from dual
       </foreach>
       </insert>
       #+END_EXAMPLE
   - bind
     从OGNL表达式中创建一个变量，并将其绑定到上下文。
     #+BEGIN_EXAMPLE xml
     <select id="selectUsre" resultType="org.john.domain.User">
     <bind name="pattern" value="'%' + _parameter.getName() + '%'"/>
     select * from user
     where loginname like #{pattern}
     </select>
     #+END_EXAMPLE
   - trim
     当标签体有内容时则为内容添加前缀、后缀，而且可以除去内容前后部分内容
     #+BEGIN_EXAMPLE xml
     <select id="findActiveBlogLike"
          resultType="Blog">
       SELECT * FROM BLOG
       <!--
         prefix属性值为添加到内容的前缀信息
         prefixOverrides属性值为除去内容前的内容，当需要除去多个内容时，使用管道符|分割，注意：空格也将被除去
       -->
       <trim prefix="where" prefixOverrides="AND | OR">
         <if test="state != null">
              state = #{state}
         </if>
         <if test="title != null">
             AND title like #{title}
         </if>
         <if test="author != null and author.name != null">
             AND author_name like #{author.name}
         </if>
       </trim>
     </select>
     #+END_EXAMPLE
 
** 内置变量 ~_parameter~ 和 ~_databaseId~
   在动态SQL中可以引用内置变量 ~_parameter~ 和 ~_databaseId~
   - ~_parameter~ 就是入参Map实例自身
     #+BEGIN_EXAMPLE xml
     <select id="xxx">
     -- 下面的语句和 select * from user where id=#{param1} 是等价的
     select * from user where id=#{_parameter.param1}
     </select>
     #+END_EXAMPLE
   - ~_databaseId~ 若在mybatis-config.xml中设置了databaseIdProvider为数据库厂商命名别名，那么这个变量的时就是那个别名，否则为原名

* 事务管理
  事务4个特性：
  1) 原子性(Atomicity), 事务作为应用中不可再分割的最小逻辑执行单位。
  2) 一致性(Consistency), 数据库从一种一致性状态，变到另一种一致性状态。一致性通过原子性来保证。
  3) 隔离性(Isolation), 并发执行的事务之间互不干扰，即事务操作过程中的中间状态无法被其他事务访问。
  4) 持续性(Durability/Persistence), 事务一旦提交，其对数据的任何草走都将记录到永久存簇器中。 

** 相关接口和实现类
接口org.apache.ibatis.transaction.Transaction，而其实现类为org.apache.ibatis.transaction.jdbc.JdbcTransaction和org.apache.ibatis.transaction.managed.ManagedTransaction。
工厂接口org.apache.ibatis.transaction.TransactionFactory，而其实现类为org.apache.ibatis.transaction.jdbc.JdbcTransactionFactory和org.apache.ibatis.transaction.managed.ManagedTransactionFactory来获取事务的实例对象。
   
接口Transaction
#+BEGIN_EXAMPLE java
public interface Transaction {
    Connection getConnection() throws SQLException;
    void commit() throws SQLException;
    void rollback() throws SQLException;
    void close() throws SQLException;
}
#+END_EXAMPLE

** 创建事务实例的过程
1) 根据mybatis-config.xml中 ~<transactionManager>~ 的属性type值创建JdbcTransactionFactory或ManagedTransactionFactory实例
   #+BEGIN_EXAMPLE java
   // <transactionManager>节点解析方法
   private TransactionFactory transactionManagedElement(XNode context) throws Exception {
     /* 前面已经通过下面语句注册别名JDBC和MANAGED对应的工厂类
        typeAliasRegistry.registerAlias("JDBC", JdbcTransactionFactory.class);
        typeAliasRegistry.registerAlias("MANAGED", ManagedTransactionFactory.class);
      */
     if (context != null){
       String type = context.getStringAttribute("type");
       Properties props = context.getChildrenAsProperties();
       TransactionFactory factory = (TransactionFactory) resolveClass(type).newInstance();
       factory.setProperties(props);
       return factory;
     }
     throw new BuilderException("Enviroment declaration requries a TransactionFactory.");
   }
   #+END_EXAMPLE
2) 然后通过TransactionFactory实例，以Connection实例或DataSource实例、隔离级别、自动提交作为入参创建Transaction实例。
3) JdbcTransaction和ManagedTransaction的区别
   1) JdbcTranscation实际使用的是java.sql.Connection提供的事务操作，依赖数据库本身的支持。
   2) ManagedTransaction则将事务管理交由应用容器(Weblogic等)管理，自身不提供commit和rollback操作，而是由容器统一管理。

* 数据缓存机制
  分为一级和二级缓存：
  1) 一级缓存为SqlSession级别的缓存。
  2) 二级缓存为namespace级别的缓存，多个SqlSession共享的。

** 一级缓存(SqlSession级别)
   - 默认开启
   - 缓存数据保存在SqlSession实例内部的Map实例中
   - 缓存逻辑
     1) 当在同一个SqlSession实例执行相同的SQL语句时，第一次执行后会将数据以对象id为键保存到内部的Map中，后续查询则直接从缓存中读取；
     2) 若SqlSession实例执行DML(insert,update,delete)并提交到数据，那么一级缓存将被自动清空。
   - 缓存失效的4种情况
     1) 查询不在同一个SqlSession中执行
     2) 查询在同一个SqlSession中执行，但查询条件不同
     3) 查询在同一个SqlSession中执行，多次查询操作之间插入DML操作
        insert/update/delete节点提供一个flushCache属性，用于设置该操作是否会清除一级和二级缓存，默认值为true。而select节点也提供flushCache属性，不过默认值为false。
     4) 手动清除一级缓存
        #+BEGIN_EXAMPLE java
        SqlSession sqlSession = SqlSessionFactory.openSession();
        try{
          sqlSession.selectOne("xxx");
          sqlSession.clearCache(); // 手动清理一级缓存
          sqlSession.selectOne("xxx");
        }
        finally {
          sqlSession.close();
        }
        #+END_EXAMPLE

** 二级缓存(mapper级别)
   - 默认关闭
     - 在mybatis-config.xml中通过 ~<setting name="cacheEnabled" value="true"/>~ 开启二级缓存
     - 在使用二级缓存的mapper.xml中通过 ~<cache eviction="LRU" flushInterval="60000" size="512" readOnly="true"/>~ 开启
       - flushInterval, 刷新间隔毫秒数。默认值为unset，即不刷新。
       - size, 缓存数目。默认值1024
       - readOnly, 默认值为false。只读的缓存会给调用者返回相同的实例，因为这些对象不能被修改。可读写的缓存会返回缓存对象的拷贝。
       - eviction, 回收策略，默认值为LRU
         - LRU, 最近最少用策略
         - FIFO, 先进先出策略
         - SOFT, 软引用策略，移除基于垃圾回收器状态和软引用规则的对象
         - WEAK, 弱引用策略，更积极地移除基于垃圾回收器状态和弱引用规则的对象
   - *注意* 被二级缓存的对象及其父类必须实现java.io.Serializable接口，因为二级缓存数据存储介质不一定在内存，可能在硬盘或远程服务器。
   - ~select~ 节点提供useCache属性用于在当前namespace已启用二级缓存的前提下，单独启用或禁用二级缓存，默认为true。
   - 缓存数据保存在Mapper内部的HashMap实例中
   - 缓存逻辑
     不同的SqlSession实例多次执行相同的mapper的namespace下的sql语句，且传递相同的参数，导致最终生成相同的sql语句，那么第一执行后将结果缓存起来，后续查询均从缓存读取。
   - 缓存失效
     各个namespace的二级缓存失效是独立的，互不干扰。
     1) 多次查询操作之间插入DML操作
        insert/update/delete节点提供一个flushCache属性，用于设置该操作是否会清除一级和二级缓存，默认值为true。而select节点也提供flushCache属性，不过默认值为false。
     2) 由于符合eviction条件被清理

** 集成第三方缓存作为二级缓存
通过实现org.apache.ibatis.cache.Cache接口，我们可以将各种成熟的缓存中间件集成到MyBatis中。
而MyBatis已经提供ehcache(hibernate默认的缓存中间件),redis等的集成适配器包。

*** 自定义缓存实现
#+BEGIN_EXAMPLE java
// 实现 org.apache.ibatis.cache.Cache
// 获取缓存编号
String getId();
// 保存key值缓存对象
void putObject(Object key, Object value);
// 获取key值缓存对象
void getObject(Object key);
// 移除key值缓存对象
void removeObject(Object key);
// 清空缓存
void clear();
// 获取缓存大小
int getSize();
// 获取缓存读写锁
ReadWriteLock getReadWriteLock();
#+END_EXAMPLE
#+BEGIN_EXAMPLE xml
<cache type="com.john.cache.MyCache">
  <!-- 在自定义缓存类中新增host属性和setter方法就会自动注入 -->
  <property name="host" value="123"/>
</cache>
#+END_EXAMPLE






** 引用其它namespace的二级缓存策略
   #+BEGIN_EXAMPLE xml
   <mapper namespace="org.john.mapper.StudentMapper">
     <!-- namespace: 设置为被引用的namespace
       -->
     <cache-ref namespace="org.john.mapper.ClassMapper"/>
   </mapper>
   #+END_EXAMPLE

** 查询时缓存逻辑流程
   1) 发起查询操作
   2) 若启用二级缓存
      1) 调用CachingExecutor，在二级缓存匹配查询
      2) 若命中则直接返回记录，并退出查询流程
   3) 调用Executer
   4) 若启用一级缓存
      1) 从Local Cache匹配查询
      2) 若命中则直接返回记录，并退出查询流程
   5) 执行JDBC查询

* 通过注解配置SQL映射
  MyBatis的注解位于org.apache.ibatis.annotations下
  - ~@Select~, Select语句的SQL映射
  - ~@SelectProvider~, Select语句的动态SQL映射。允许通过属性type和method指定一个完全限定类名和方法名在执行时返回运行的查询语句
  - ~@Insert~, Insert语句的SQL映射
  - ~@InsertProvider~, Insert语句的动态SQL映射。允许通过属性type和method指定一个完全限定类名和方法名在执行时返回运行的插入语句
  - ~@Update~, Update语句的SQL映射
  - ~@UpdateProvider~, Update语句的动态SQL映射。允许通过属性type和method指定一个完全限定类名和方法名在执行时返回运行的更新语句
  - ~@Delete~, Delete语句的SQL映射
  - ~@DeleteProvider~, Delete语句的动态SQL映射。允许通过属性type和method指定一个完全限定类名和方法名在执行时返回运行的删除语句
  - ~@Result~, 列和属性间的结果映射。属性包括：
    - id, 布尔值，表示是否被用于主键映射
    - column,
    - property,
    - javaType,
    - jdbcType
    - type Handler
    - one, 和XML中的 ~<association>~ 相似
    - many, 和XML中的 ~<collection>~ 相似
  - ~@Results~, 多个结果映射列表
  - ~@Options~, 提供配置选项的附加值，通常用于在映射语句上作为附加功能配置出现
  - ~@One~, 复杂类型的单独属性值映射。必须指定属性select，表示已映射的SQL语句的完全限定名
  - ~@Many~, 复杂类型的集合属性值映射。必须指定属性select，表示已映射的SQL语句的完全限定名
  - ~@Param~, 为映射器方法参数定义名字。

** 示例-CRUD
   #+BEGIN_EXAMPLE java
   public interface UserMapper{
     @Insert("insert into user(name, sex) values(#{name}, #{sex})")
     @Options(useGeneratedKeys=true, keyProperty="id")
     int saveUser(User user);

     @Delete("delete from user where id = #{id}")
     int removeUser(@Param("id") Integer id);

     @Update("update user set name=#{name}, sex=#{sex} where id=#{id}")
     void modifyUser(User user);

     @Select("select * from user where id=#{id}")
     @Results({
        @Result(id=true, column="id", property="id"),
        @Result(column="name", property="name"),
        @Result(column="sex", property="sex")
     })
     User selectUserById(@Param("id") Integer id);

     @Select("select * from user")
     List<User> selectAllUser();
   }
   #+END_EXAMPLE

** 示例-OneToOne
   #+BEGIN_EXAMPLE java
   public interface UserMapper{
     @Select("select * from user where id = #{id}")
     @Results({
        @Result(id=true, column="id", property="id"),
        @Result(column="name", property="name"),
        @Result(column="clazz_id", property="clazz",
                one=@One(
                    select="org.john.mapper.ClazzMapper.selectClazzById",
                    fetchType=FetchType.EAGER
                    ))
     })
     User selectUserById(@Param("id") Integer id);
   }
   #+END_EXAMPLE

** 示例-OneToMany
   #+BEGIN_EXAMPLE java
   public interface ClazzMapper {
     @Select("select * from clazz where id = #{id}")
     @Results({
        @Result(id=true, column="id", property="id"),
        @Result(column="id", property="students",
                many=@Many(
                     select="org.john.mapper.UserMapper.selectUserByClazzId",
                     fetchType=FetchType.LAZY
                     ))
     })
     Clazz getClazzById(@Param("id") Integer id);
   }
   #+END_EXAMPLE

** 示例-动态SQL注解
   - SQL工具类 ~org.apache.ibatis.jdbc.SQL~ 可避免直接使用字符串拼接
     - ~T SELECT(String columns)~
     - ~T FROM(String table)~
     - ~T JOIN(String join)~
     - ~T INNER_JOIN(String join)~
     - ~T LEFT_OUTER_JOIN(String join)~
     - ~T RIGHT_OUTER_JOIN(String join)~
     - ~T WHERE(String condition)~
     - ~T OR()~
     - ~T AND()~
     - ~T GROUP_BY(String column)~
     - ~T HAVING(String column)~
     - ~T ORDER_BY(String column)~
     - ~T INSERT_INTO(String table)~
     - ~T VALUES(String column, String value)~
     - ~T DELETE_FROM(String table)~
     - ~T UPDATE(String table)~
     - ~T SET(String set)~
   - ~*Provider~ 方法接收以下参数：
     - 无参数
     - Java对象
     - java.util.Map对象
   
   #+BEGIN_EXAMPLE java
   publc class UserDynaSqlProvider {
     public String selectWithParam(Map<String, Object> param){
       return new SQL(){
         {
           SELECT("*");
           FROM("user");
           if (param.get("id") != null) {
             WHERE(" id = #{id} ");
           }
           if (param.get("loginname") != null) {
             WHERE(" loginname = #{loginname} ");
           }
         }
       }.toString();
     }
   }
   #+END_EXAMPLE
* Spring集成 
  MyBatis3问世前Spring3的开发工作已经完成，因此Spring3中没有内置对MyBatis3的支持，需要引入MyBatis提供的mybatis-spring.jar来集成。到Spring4时则延续这一做法。
  1) 在applicationContext.xml配置MyBatis工厂类
  2) 在DAO层使用Spring注入的工具Bean对数据进行操作

  #+BEGIN_EXAMPLE xml
  <!-- applicationContext.xml -->
  xmlns:mybatis="http://mybatis.org/schema/mybatis-spring"
  xmlns:p="http://www.springframework.org/schema/p"
  xmlns:tx="http://www.springframework.org/schema/tx"
  xsi:schemaLocation="http://mybatis.org/schema/mybatis-spring
                      http://mybatis.org/schema/mybatis-spring.xsd
                      http://www.springframework.org/schema/p
                      http://www.springframework.org/schema/p.xsd
                      http://www.springframework.org/schema/tx
                      http://www.springframework.org/schema/tx.xsd"

  <!-- 注册Spring Bean -->
  <context:component-scan base-package="org.john"/>           
  <!-- 引入mapper接口 -->
  <mybatis:scan base-package="org.john.mapper"/>
  <!-- 使用PropertyOverrideConfigurer后处理器加载数据源参数
  <context:property-override location="classpath:db.properties"/> -->
  <!-- 配置c3p0数据源
  <bean id="dataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource"/> -->
  <!-- 配置jdbc数据源 -->
  <bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
    <property name="driverClassName">
      <value>com.mysql.jdbc.Driver</value>
    </property>
    <property name="url">
      <value>jdbc:mysql://localhost:3306/oa?zeroDateTimeBehavior=convertToNull</value>
    </property>
    <property name="username">
    </property>
    <property name="password">
    </property>
  </bean>

  <!-- 
    创建SqlSessionFactory实例
    指定SqlSessionFactory为社区开发的实现类 -->
  <!--<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean" p:dataSource-ref="dataSource"/>-->
  <bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
    <property name="dataSource" ref="dataSource"/>
    <!-- 在当前classpath中读取MyBatis配置文件mybatis-config.xml -->
    <property name="configLocation" value="classpath:mybatis-config.xml"/>
    <!-- 指定SQL映射文件位置  -->
    <property name="mapperLocations" value="classpath:org/john/mapper/*.xml"/>
  </bean>

  <!-- 扫描所有Mapper接口，从而实现自动注入(@Autowired) -->
  <mybatis-spring:scan base-package="org.john.dao"/>
  <!-- 以前的写法
    <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
      <!--递归扫描value值指定包下的文件-->
      <property name="basePackage" value="org.john.dao"/>
      <property name="sqlSessionFactoryBeanName" value="sqlSessionFactroy"/>
      <!-- 若指定了sqlSessionTemplate, 那么sqlSessionFactory将被忽略 -->
      <property name="sqlSessionTemplateBeanName" value="sqlSessionTemplate"/>
      <!-- 表示通过该注解标识的接口将被识别为Mapper接口 -->
      <property name="annotationClass" value="org.springframework.stereotype.Repository"/>
      <!-- 表示继承该接口的接口将被识别为Mapper接口
      <property name="mapperInterface" value="">
      -->
    </bean>
    -->

  <!-- JDBC事务管理器 -->
  <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager" p:dataSource-ref="dataSource"/>
  <!-- 启用支持annotation注解方式事务管理 -->
  <tx:annotation-driven transaction-manager="transactionManager"/>
  #+END_EXAMPLE

  #+BEGIN_EXAMPLE
  # db.properties
  dataSource.driverClass=com.mysql.jdbc.Driver
  dataSource.jdbcUrl=jdbc:mysql://127.0.0.1:3306/mybatis
  dataSource.user=root
  dataSource.password=root
  dataSource.maxPoolSize=20
  dataSource.maxIdleTime=1000
  dataSource.minPoolSize=6
  dataSource.initialPoolSize=5
  #+END_EXAMPLE

  #+BEGIN_EXAMPLE xml
  <!-- spring框架提供的字符集过滤器 -->
  <!-- spring Web MVC框架提供了org.springframework.web.filter.CharacterEncodingFilter用于解决POST方式造成的中文乱码问题  -->
  <filter>
     <filter-name>encodingFilter</filter-name>
     <filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
     <init-param>
         <param-name>encoding</param-name>
         <param-value>UTF-8</param-value>
     </init-param>
     <!-- force强制，促使 -->
     <init-param>
         <param-name>forceEncoding</param-name>
         <param-value>true</param-value>
     </init-param>
  </filter>
  <filter-mapping>
     <filter-name>encodingFilter</filter-name>
     <url-pattern>/*</url-pattern>
  </filter-mapping>
  #+END_EXAMPLE

   [[MyBatis Spring Adapter][https://github.com/mybatis/spring]]

** 另一个部分   

   通过IOC实现即插即拔功能。
   通过AOP框架将数据库事务委托给Spring处理。
   - 默认情况下抛出异常后，将引发事务回滚。
   - 事务隔离级别
     Oracle支持读写提交(默认)和序列化，MySQL支持可重复读(默认)
     1) 脏读，一个事务能读取另外一个事务未提交的数据，导致 *脏读*
     2) 读写提交，一个事务还没结束，其之前读取过的数据已经被修改了，导致 *不可重复读*
     3) 可重复读，一个事务还没结束，其读取的记录数被删减或增加了，导致 *幻读*
     4) 序列化
   - 传播行为
     用于指示方法调用的问题，Spring中定义了7中传播行为。
     | 传播行为                  | 含义                                                         |
     |---------------------------+--------------------------------------------------------------|
     | PROPAGATION_REQUIRED      | 若存在一个事务，则加入该事务。否则创建新事务                 |
     | PROPAGATION_SUPPORTS      | 若存在一个事务，则加入该事务。否则以非事务方式执行           |
     | PROPAGATION_MANDATORY     | 若存在一个事务，则加入该事务。否则抛出异常                   |
     | PROPAGATION_REQUIRES_NEW  | 总是创建新事务。若已存在一个事务，则将该已存在的事务挂起     |
     | PROPAGATION_NOT_SUPPORTED | 总以非事务方式执行。若已存在一个事务，则将该已存在的事务挂起 |
     | PROPAGATION_NEVER         | 总以非事务方式执行。若已存在一个事务，则抛出异常             |
     | PROPAGATION_NESTED        | 若存在一个活动事务，则运行在一个嵌套的事务中。否则创建新事务 |
     - 自调用
       由于insertRoleList调用自身的insertRole方法时并不是调用动态代理类实例的方法，因此并没有触发动态代理类的invoke方法，而Spring事务处理逻辑均写在invoke方法中，因此insertRole会在insertRoleList所属的事务上下文中执行。
       #+BEGIN_EXAMPLE java
       @Service
       public class RoleServiceImpl {
         @Autowired
         private RoleDAO roleDAO;

         @Transactional(isolation=Isolation.READ_COMMITTED, propagation=Propagation.REQUIRED)
         public int insertRoleList(List<Role> roleList){
           for (Role role : roleList){
             this.insertRole(role);
           }
         }

         @Transactional(isolation=Isolation.READ_COMMITTED, propagation=Propagation.REQUIRED_NEW)
         public int insertRole(Role role){
           roleDAO.insert(role);
         }
       }
       #+END_EXAMPLE

** 通过SqlSessionTemplate操作数据库
   MyBatis中通过SqlSessionFactory获取SqlSession实例，而集成Spring后可通过SqlSessionTemplate(org.mybatis.spring.SqlSessionTemplate)来使用SqlSession实例。
   #+BEGIN_EXAMPLE xml
   <!-- applicationContext.xml -->
   <bean id="sqlSessionTemplate" class="org.mybatis.spring.SqlSessionTemplate">
     <!-- 将sqlSessionFactory Bean作为构造方法第一个参数构造SqlSessionTemplate -->
     <constructor-arg index="0" ref="sqlSessionFactory" />
     <!--
       第二可选入参为ExecutorType，取值范围为SIMPLE, REUSE, BATCH
       <constructor-arg index="1" value="BATCH" />
     -->
   </bean>
   <bean id="userDao" class="org.john.dao.UserDao">
     <property name="sqlSessionTemplate" ref="sqlSessionTemplate"/>
   </bean>
   #+END_EXAMPLE
   #+BEGIN_EXAMPLE java
   public class UserDao {
     private SqlSessionTemplate sqlSessionTemplate;
     public void setSqlSessionTemplate(SqlSessionTemplate sqlSessionTemplate) {
       this.sqlSessionTemplate = sqlSessionTemplate;
     }
     public SqlSessionTemplate getSqlSessionTemplate(){
       return this.sqlSessionTemplate;
     }

     public int deleteUser(Long id){
       return this.sqlSessionTemplate.delete("org.john.dao.UserDao.deleteUser", id);
     }
   }
   #+END_EXAMPLE

** 通过Mapper接口操作数据库
   通过MapperFactoryBean作为中介让Spring为我们注入Mapper
   #+BEGIN_EXAMPLE xml
   <bean id="userDao" class="org.mybatis.spring.mapper.MapperFactoryBean">
     <!-- 指定UserDao接口作为Mapper接口 -->
     <property name="mapperInterface" value="org.john.dao.UserDao"/>
     <!-- 若指定了sqlSessionTemplate, 那么sqlSessionFactory将被忽略 -->
     <property name="sqlSessionFactory" ref="sqlSessionFactory"/>
     <property name="sqlSessionTemplate" ref="sqlSessionTemplate"/>
   </bean>
   #+END_EXAMPLE
   #+BEGIN_EXAMPLE java
   public interface UserDao {}
   
   public class UserService {
     @Autowired
     private UserDao userDao;
   }
   #+END_EXAMPLE
   
*** 通过MapperScannerConfigurer自动扫描批量注册Mapper接口
    #+BEGIN_EXAMPLE xml
    <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
      <!--递归扫描value值指定包下的文件-->
      <property name="basePackage" value="org.john.dao"/>
      <property name="sqlSessionFactoryBeanName" value="sqlSessionFactroy"/>
      <!-- 若指定了sqlSessionTemplate, 那么sqlSessionFactory将被忽略 -->
      <property name="sqlSessionTemplateBeanName" value="sqlSessionTemplate"/>
      <!-- 表示通过该注解标识的接口将被识别为Mapper接口 -->
      <property name="annotationClass" value="org.springframework.stereotype.Repository"/>
      <!-- 表示继承该接口的接口将被识别为Mapper接口
      <property name="mapperInterface" value="">
      -->
    </bean>
    #+END_EXAMPLE

* 运行原理
  | 参数映射  -->    | SQL解析 -->     | SQL执行 -->    | 结果处理和映射   |
  |------------------+-----------------+----------------+------------------|
  | 配置             | 配置            | SimpleExecutor | 配置             |
  | 映射解析         | 解析            | BatchExecutor  | 转换             |
  | 类型解析         | SQL语句动态生成 | ReuseExecutor  |                  |
  | ParameterHandler | SqlSource       | Executor       | ResultSetHandler | 

  DefaultSqlSessionFactory implements SqlSessionFactory
  SqlSessionManager implements SqlSessionFactory, SqlSession
  DefaultSqlSession implements SqlSession

  #+BEGIN_EXAMPLE java
  InputStream inputStream = Resources.getResourceAsStream("mybatis-config.xml");
  SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
  /* 内部调用栈
     - XmlConfigBuilder parser = new XmlConfigBuilder(inputStream, null, null);
       parser.parse() :: Configuration
       - parser:XPathParser.evalNode("/configuration") 查找根节点并作为起点供parseConfiguration方法遍历获取其他配置项
       - parseConfiguration(XNode root) 内部通过如settingsElement(Properties props)等方法遍历获取子配置项，并添加到全局配置Configuration对象(包含mybatis-config.xml和所有SQL映射文件的信息)中。
         - mapperElement(XNode parent)
           if ("package".equals(child.getName())){
             // package优先级最高    
           }
           else {
             if (resource != null && url == null && mapperClass == null){
               // resource优先级第二高  
             }
             else if (resource == null && url != null && mapperClass == null){
               // url优先级第三高  
             }
             else if (resource == null && url == null && mapperClass != null){
               // mapperClass优先级最低  
             }
           }
           - XMLMapperBuilder mapperParser = new XMLMapperBuilder(mapperInputStream, configuration) 通过上述4种方式获取SQL映射文件后，构造XMLMapperBuilder实例对其进行解析
           - mapperParser.parse() 内部会通过configuration.isResourceLoaded(mapperInputStream)避免重复解析
             - configurationElement(XNode root) 和parseConfiguration一样以mapper节点为入口对SQL映射文件进行遍历获取子配置信息
               - buildStatementFromContext(context.evalNodes("select|insert|update|delete"))
                 - XMLStatementBuilder statementBuilder = new XMLStatementBuilder(configuration)
                 - statementBuilder.parseStatementNode() 解析select/insert/update/delete节点
                   - 获取所有属性后调用 builderAssistant.addMappedStatement() :: MappedStatement 对应一个CRUD标签的所有信息
                     MappedStatement.sqlSource 就是对应预处理后的SQL脚本
                     - 内部会将这个MappedStatement通过configuration.addMappedStatement()添加到Configuration对象中
                 - 若statementBuilder.parseStatementNode() 解析过程中出现异常，则会调用configuration.addIncompleteStatement(statementBuilder)
             每次执行mapperParser.parse()均会执行
             - parsePendingResultMaps()
             - parsePendingCacheRefs()
             - parsePendingStatements()

       Configuration.mappedStatements 包含所有SQL映射文件中的预处理后CRUD语句
       Configuration.mapperRegistry.knownMappers :: HashMap<K,V> 以Mapper接口为键，org.ibatis.binding.MapperProxyFactory为值
       
       - build(configuration)
         - new DefaultSqlSessionFactory(configuration)
   */

  SqlSession sqlSession = sqlSessionFactory.openSession();
  /* 内部调用栈
     - openSessionFromDataSource(configuration.getDefaultExecutorType(), null, false) :: SqlSession
       configuration.getDefaultExecutorType()::String 获取mybatis-config.xml中settings/setting[name=defaultExecutorType]的值，默认为SIMPLE
       - 读取environments节点的信息
       - Executor executor = configuration.newExecutor(tx, execType) tx为事务对象，execType就是SIMPLE/BATCH/REUSE
         - 根据execType值创建SimpleExecutor/BatchExecutor/ReuseExecutor
         - 若启用二级缓存则创建CachingExecutor，并将上述的具体Executor包装在CachingExecutor内部，实际操作数据库的操作依然为具体的Executor处理，CachingExecutor只是在此基础上添加缓存逻辑
         - executor = (Executor) interceptorChain.pluginAll(executor) 调用拦截器链
           - 遍历所有拦截器并调用 executor = interceptor.plugin(executor) 加工Executor实例
       - new DefaultSqlSession(configuration, executor, autoCommit)
   */
  StudentMapper studentMapper = sqlSession.getMapper(StudentMapper.class);
  /* 内部调用栈
     - configuration.getMapper()
       - mapperRegistry.getMapper()
         - 创建MapperProxyFactory实例并调用实例的newInstance(sqlSession)方法
           - MapperProxy mapperProxy = new MapperProxy(sqlSession, mapperInterface, mapperMethod)
           - Proxy.newProxyInstance(mapperInterface.getClassLoader(), new Class[] {mapperInterface}, mapperProxy)
   */
  studentMapper.getStudent(1); // 启动了二级缓存
  /* 内部调用栈
     - invoke
       - 判断调用的方法是否在Object还是在接口中定义的，若在Object中定义则马上执行后退出
       - MapperMethod mapperMethod = cachedMapperMethod(method) 将调用的方法转换为MyBatis可以识别处理的MapperMethod
         - this.command = new SqlCommand(configuration, mapperInterface, method)
         - this.method = new MethodSignature(configuration, mapperInterface, method)
       - mapperMethod.execute(sqlSession, args)
         - 通过this.command.getType()判断是执行CRUD哪类命令
         - 通过method.convertArgsToSqlCommandParam(args)将入参封装为传给SQL命令的Map对象
         - 然后调用SqlSession.selectOne等方法执行数据库操作，以selectOne为例子
           - 调用selectList取多行记录，然后返回第一行记录
             - MappedStatement ms = configuration.getMappedStatement(statement) 获取经过预处理的SQL语句信息
               - class MappedStatement 保存映射文件节点信息
                 id           : String
                 sqlSource    : SqlSource
                 parameterMap : ParameterMap
                 configuration: Configuration
                 datasourceId : String
                 .....................
                 getBoundSql(): BoundSql
               - class SqlSource 作为接口主要是根据参数和其他的规则组装SQL(包括动态SQL)
                 getBoundSql(): BoundSql
               - class BoundSql 存放SQL和参数以及参数规则，插件一般要获取它来拿到当前运行的SQL和参数及参数规则信息
                 sql                  : String SQL语句
                 parameterMappings    : List<ParameterMapping> ParameterMapping存储参数属性、名称、表达式、javaType和jdbcType、typeHandler等信息
                 parameterObject      : Object 参数本身如简单对象、POJO、Map或@Param注解的参数
                                               int/float等基本类型的入参会包装为Integer/Float等再保存到parameterObject
                                               POJO/Map会直接保存到parameterObject
                                               多个参数/@Param/List/Collection/Array会经处理后封装为Map再保存到parameterObject
                 additionalParameter  : Map<String, Object>
                 metaParameters       : MetaObject
                 getSql()             : String
                 getParameterObject() : Object
             - executor::CachingExecutor.query(ms, wrapCollection(parameter)， rowBounds)
               wrapCollection 将collection,array封装到Map实例中
               - BoundSql boundSql = ms.getBoundSql(parameterObject) 取出预处理后的SQL和入参映射及入参值等信息
               - CacheKey key = createCacheKey(ms, parameterObject, rowBounds, boundSql) 生成一级和二级缓存用的键名
               - 
   */
  #+END_EXAMPLE

** 4大核心对象
Mapper执行过程就是通过4大核心对象来完成数据库操作和结果返回：
1) Executor(update,query,flushStatements,commit,rollback,getTransaction,close,isClosed)
   由它来调度StatementHandler,ParameterHandler和ResultSetHandler等来执行对应的SQL。
2) StatementHandler(prepare,parameterize,batch,update,query)
   用通过它使用数据库的Statement(PreparedStatement)执行操作，是4大核心对象的核心。
3) ParameterHandler(getParameterObject,setParameters)
   用于SQL对参数的处理。
4) ResultSetHandler(handleResultSets,handleOutputParameters)
   用于进行最后数据集(ResultSet)的封装返回处理

*** Executor
内置3种执行器
1) SIMPLE, 简易执行器，默认的执行器
2) REUSE, 重用预处理语句的执行器
3) BATCH, 重用预处理和批量处理的执行器

#+BEGIN_EXAMPLE java
public Executor newExecutor(Transaction transaction, ExecutorType executorType) {
  executorType = executorType == null ? defaultExecutorType : executorType;
  executorType = executorType == null ? ExecutorType.SIMPLE : executortype;
  Executor executor;
  if (ExecutorType.BATCH == executorType){
    executor = new BatchExecutor(this, transaction);
  }
  else if (ExecutorType.REUSE == executorType){
    executor = new ReuseExecutor(this, transaction);
  }
  else {
    executor = new SimpleExecutor(this, transaction);
  }

  // 启动二级缓存时
  if (cacheEnabled){
    executor = new CachingExecutor(executor);
  }
  // 插件链，为执行器生成一层层动态代理对象，来附加上插件逻辑。
  executor = (Executor) interceptorChain.pluginAll(executor);
  return executor;
}
#+END_EXAMPLE

SimpleExecutor的源码
#+BEGIN_EXAMPLE java
public class SimpleExecutor extends BaseExecutor {
  // ........
  @Override
  public <E> List<E> doQuery(MappedStatement ms, Object parameter, RowBounds rowBounds, ResultHandler resultHandler, BoundSql boundSql)
  throws SQLException{
    Statement stmt = null;
    try {
      Configuration configuration = ms.getConfiguration();
      StatementHandler handler = configuration.newStatementHandler(wrapper, ms, parameter, rowBounds, resultHandler, boundSql);
      stmt = preparedStatement(handler, ms.getStatementLog());
      return handler.<E>query(stmt, resultHandler);
    }
    finally {
      closeStatement(stmt);
    }
  }

  private Statement preparedStatement(StatementHandler handler, Log statementLog) throws SQLException{
    Statement stmt;
    Connection connection = getConnection(statementLog);
    stmt = handler.prepare(connection);
    handler.parameterize(stmt);
    return stmt;
  }
}
#+END_EXAMPLE

*** StatementHandler
内置3种数据库会话器
1) SimpleStatementHandler
2) PreparedStatementHandler
3) CallableStatementHandler

创建StatementHandler的源码
#+BEGIN_EXAMPLE java
public StatementHandler newStatementHandler(Executor executor, MappedStatement mappedStatement, Object parameterObject, RowBounds rowBounds, ResultHandler resultHandler, BoundSql boundSql) {
  // RoutingStatementHandler是通过适配模式找到对应的StatementHandler来执行
  StatementHandler statementHandler = new RoutingStatementHandler(executor, mappedStatement, parameterObject, rowBounds, resultHandler, boundSql);
  statementHandler = (StatementHandler) interceptorChain.pluginAll(statementHandler);
  return statementHandler;
}
#+END_EXAMPLE

RoutingStatementHandler的源码
#+BEGIN_EXAMPLE java
public class RoutingStatementHandler implements StatementHandler{
  // 采用适配器模式
  private final StatementHandler delegate;
  
  public RoutingStatementHandler(Executor executor, MappedStatement mappedStatement, Object parameterObject, RowBounds rowBounds, ResultHandler resultHandler, BoundSql boundSql){
    switch (mappedStatement.getStatementType()){
      case STATEMENT:
        delegate = new SimpleStatementHandler(executor, mappedStatement, parameterObject, rowBounds, resultHandler, boundSql);
        break;
      case PREPARED:
        delegate = new PreparedStatementHandler(executor, mappedStatement, parameterObject, rowBounds, resultHandler, boundSql);
        break;
      case CALLABLE:
        delegate = new CallableStatementHandler(executor, mappedStatement, parameterObject, rowBounds, resultHandler, boundSql);
        break;
      default:
        throw new ExecutorException("Unknown statement type: " + mappedStatement.getStatementType());
    }
    // .......
  }
}
#+END_EXAMPLE

PreparedStatementHandler的源码
#+BEGIN_EXAMPLE java
public abstract class BaseStatementHandler implements StatementHandler{
  @Override
  public Statement prepare(Connection connection) throws SQLException {
    ErrorContext.instance().sql(boundSql.getSql());
    Statement stmt = null;
    try{
      // instantiateStatement会通过boundSql.getSql()获取SQL语句然后进行预编译
      stmt = instantiateStatement(connection);
      setStatementTimeout(statement);
      setFetchSize(statement);
      return stmt;
    }
    catch (SQLException e){
      closeStatement(stmt);
      throw e;
    }
    catch (Exception e){
      closeStatement(stmt);
      throw new ExecutorException("Error preparing statement. Cause: " + e, e);
    }
  }

  @Override
  public void parameterize(Statement statement) throws SQLException {
    parameterHandler.setParameters((PreparedStatement) statement);
  }

  @Override
  public <E> List<E> query(Statement statement, ResultHandler resultHandler) throws SQLException {
    PreparedStatement ps = (PreparedStatement) statement;
    ps.execute();
    return resultSetHandler.<E>handlerResultSets(ps);
  }
}
#+END_EXAMPLE

*** ParameterHandler
DefaultParameterHandler的源码
#+BEGIN_EXAMPLE java
public void setParameters(PreparedStatement ps){
  ErrorContext.instance().activity("setting parameters").object(mappedStatement.getParameterMap().getId());
  List<ParameterMapping> parameterMappings = boundSql.getParameterMappings();
  if (parameterMappings != null){
    for (int i = 0; i < parameterMappings.size(); i++){
      ParameterMapping parameterMapping = parameterMappings.get(0);
      if (parameterMapping.getMode() != ParameterMode.OUT) {
        Object value;
        String propertyName = paramenterMapping.getProperty();
        if (boundSql.hasAdditionalParameter(propertyName)){
          value = boundSql.getAdditionalParameter(propertyName);
        }
        else if (parameterObject == null){
          value = null;
        }     
        else if (typeHandlerRegistry.hasTypeHandler(parameterObject.getClass())){
          value = parameterObject;
        }         
        else {
          MetaObject metaObject = configuration.newMetaObject(parameterObject);
          value = metaObject.getValue(propertyName);
        }             
        TypeHandler typeHandler = parameterMapping.getTypeHandler();
        JdbcType jdbcType = parameterMapping.getJdbcType();
        if (value == null && jdbcType == null){
          jdbcType = configuration.getJdbcTypeForNull();
        }
        try{
          // 全部通过typeHandler设置入参
          typeHandler.setParameter(ps, i+1, value, jdbcType);
        }     
        catch (TypeException e){
          throw new TypeException("Could not set parameters for mapping: " + parameterMapping + ". Cause: " + e, e);
        }
        catch (SQLException e){
          throw new TypeException("Could not set parameters for mapping: " + parameterMapping + ". Cause: " + e, e);          
        }             
      }     
    }
  }
}
#+END_EXAMPLE

*** ResultSetHandler
在handleResultSets方法中通过typeHandler和ObjectFactory对结果集进行组装后再返回。

* 插件 
  Configuration对象在创建4大核心对象时，采用责任链模式将插件逻辑附加到4大核心对象中。
  注意：
  1) 能不用插件尽量不要用插件，因为它修改了MyBatis的底层设计
  2) 由于插件采用层层代理对象的责任链模式，通过反射进行操作，因此性能不高。

** 插件接口
自定义插件必须实现以下接口
#+BEGIN_EXAMPLE java
public interface Interceptor {
  // 插件的核心方法，它将直接覆盖所拦截对象的原有方法。通过入参invocation对象来调用原有方法。
  Object intercept(Invocation invocation) throws Throwable;
  // 给被拦截对象生成一个代理对象，并返回它。target为被拦截对象。
  // 一般内部采用org.apache.ibatis.plugin.Plugin中的wrap静态方法生成代理对象
  Object plugin(Object target);
  // 允许在mybatis-config.xml中plugin元素中配置参数，插件初始化时被调用一次。
  void setProperties(Properties properties);
}
#+END_EXAMPLE
这里采用模板模式(Template)，就是提供一个骨架并告知骨架中的方法用途，具体由开发者来完成它。

** 插件初始化
在XMLConfigBuilder中初始化
#+BEGIN_EXAMPLE java
private void pluginElement(XNode parent) throws Exception {
  if (parent != null){
    for (XNode child : parent.getChildren()){
      String interceptor = child.getStringAttribute("interceptor");
      Properties properties = child.getChildrenAsProperties();
      Interceptor interceptorInstance = (Interceptor) resolveClass(interceptor).newInstance();
      interceptorInstance.setProperties(properties);
      configuration.addInterceptor(interceptorInstance);
    }
  }
}
#+END_EXAMPLE
在Configuration中
#+BEGIN_EXAMPLE java
public void addInterceptor(Interceptor interceptor){
  interceptorChain.addInterceptor(interceptor);
}
#+END_EXAMPLE
在InterceptorChain中
#+BEGIN_EXAMPLE java
private final List<Interceptor> interceptors = new ArrayList<Interceptor>();

public void addInterceptor(Interceptor interceptor){
  interceptors.add(interceptor);
}
#+END_EXAMPLE

** 插件责任链
内就拿Configuration的newExecutor为例
#+BEGIN_EXAMPLE java
executor = (Executor) interceptorChain.pluginAll(executor);
#+END_EXAMPLE
#+BEGIN_EXAMPLE java
/// 通过动态代理来构建责任链
public Object pluginAll(Object target){
  for (Interceptor interceptor : interceptors){
    target = interceptor.plugin(target); // 内部调用Plugin.wrap静态方法构建代理实例
  }
  return target;
}
#+END_EXAMPLE
#+BEGIN_EXAMPLE java
public class Plugin implements InvocationHandler {
  public static Object wrap(Object target, Interceptor interceptor){
    Map<Class<?>, Set<Method>> singatureMap = getSignatureMap(interceptor);
    Class<?> type = target.getClass();
    Class<?>[] interfaces = getAllInterfaces(type, singatureMap);
    if (interfaces.length > 0){
      return Proxy.newProxyInstance(
        type.getClassLoader(),
        interfaces,
        new Plugin(target, interceptor, singatureMap)
      );
    }
    
    return target;
  }

  public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
    try{
      Set<Method> methods = singatureMap.get(method.getDeclaringClass());
      if (methods != null && methods.contains(method)){
        return interceptor.intercept(new Invocation(target, method, args));
      }
      return method.invoke(target, args);
    }
    catch (Exception e){
      throw ExcetionUtil.unwrapThrowable(e);
    }
  }
}
#+END_EXAMPLE
Invocation类提供proceed方法调用被拦截对象的原方法
#+BEGIN_EXAMPLE java
public Object proceed() throws InvocationTargetException, IllegalAccessException {
  return method.invoke(target, args);
}
#+END_EXAMPLE

** 工具类——MetaObject
用于读取和修改一些重要对象的属性。主要方法：
- ~MetaObject forObject(Object object, ObjectFactory objectFactory, ObjectWrapperFactory objectWrapperFactory)~
  用于获取包装对象
- ~Object getValue(String name)~
  用于获取对象属性，支持OGNL
- ~void setValue(String name, Object value)~
  用于设置对象属性，支持OGNL

示例-拦截StatementHandler修改SQL
#+BEGIN_EXAMPLE java
StatementHandler statementHandler = (StatementHandler) invocation.getTarget();
MetaObject metaStatementHandler = SystemMetaObject.forObject(statementHandler);

// 通过递归获取真正的StatementHandler而不是代理类实例
while (metaStatementHandler.hasGetter("h")){
  Object object = metaStatementHandler.getValue("h");
  metaStatementHandler = SystemMetaObject.forObject(object);  
}

String sql = (String)metaStatementHandler.getValue("delegate.boundSql.sql");
if (sql != null && sql.toLowerCase().trim().indexOf("select") == 0){
  sql = String.format("select * from (%s) $_$limit_$table_ limit 1000", sql);
  metaStatementHandler.setValue("delegate.boundSql.sql", sql);
}
#+END_EXAMPLE

** 实现自定义插件
   1) 确定拦截的对象和方法
      - Executor是执行SQL的全过程，包括组装参数、结果集返回和执行嗯SQL过程都可以拦截，因为范围广泛因此用得不多
      - StatementHandler是执行SQL的过程，可以重写执行SQL的过程
        可拦截的方法
        - ~Statement prepare(Connection connection) throws SQLException~
        - ~void parameterize(Statement statement) throws SQLException~
        - ~void batch(Statement statement) throws SQLException~
        - ~void update(Statement statement) throws SQLException~
        - ~<E> List<E> query(Statement statement, ResultHandler resultHandler) throws SQLException~
        - ~BoundSql getBoundSql()~
        - ~ParameterHandler getParameterHandler()~
      - ParameterHandler主要用于拦截执行SQL的参数组装，可以重写组装参数规则
      - ResultSetHandler用于拦截结果集的组装，可以重写组装结果规则
   2) 通过注解指定拦截的对象和方法
      #+BEGIN_EXAMPLE java
      package com.john.plugin;

      @Interceptors(
        @Signature(
        type = StatementHandler.class,
        method = "prepare",
        args = {Connection.class}
        )
      )
      public class MyPlugin implements Interceptor{
        Properties props = null;
        @Override
        public Object intercept(Invocation invocation) throws Throwable {
          return invocation.proceed();
        }
         
        @Override
        public Object plugin(Object target){
          return Plugin.wrap(target, this);
        }

        public void setProperties(Properties props){
          this.props = props;
        }
      }
      #+END_EXAMPLE
   3) 在mybatis-config.xml配置
      #+BEGIN_EXAMPLE xml
      <plugins>
        <plugin interceptor="com.john.plugin.MyPlugin">
          <property name="dbType" value="mysql"/>
        </plugin>
      </plugins>
      #+END_EXAMPLE

* 批处理
  1) 配置
     1) 全局配置(mybatis-config.xml)
        #+BEGIN_EXAMPLE xml
        <settings>
          <setting name="defaultExecutorType" value="BATCH"/>
        </settings>
        #+END_EXAMPLE
     2) Session配置
        #+BEGIN_EXAMPLE java
        SqlSession session = sqlSessionFactory.openSession(ExecutorType.BATCH);
        #+END_EXAMPLE
     3) Spring配置
        #+BEGIN_EXAMPLE xml
        <bean id="sqlSessionTemplate" class="org.mybatis.spring.SqlSessionTemplate">
          <constructor-arg index="0" ref="sqlSessionFactory"/>
          <constructor-arg index="1" ref="BATCH"/>
        </bean>
        #+END_EXAMPLE
  2) 注意事项
     1) 对数据库的操作在执行commit时才会发送到数据库
     2) 通过调用 ~session.flushStatement()~ 在事务未提交的前提下，将对数据库的操作发送给数据库执行。
  3) 示例
     #+BEGIN_EXAMPLE java
     // 采用全局配置
     try{
       RoleMapper roleMapper = session.getMapper(RoleMapper.class);
       Role role = new Role();
       role.setName("xxx");
       roleMapper.save(role);
       session.flushStatement(); // 若不执行这句，那么数据库并没有name为xxx的role记录
       Role role = roleMapper.select("xxx");
       System.out.println(role.getName());
       session.commit();
     }
     catch (Exception e){
       session.rollback();
     }
     #+END_EXAMPLE
* 存储过程和函数
** 返回基本类型
   #+BEGIN_EXAMPLE xml
   <select id="count" statementType="CALLABLE">
   {call count_role (
     #{roleName, mode=IN, jdbcType=VARCHAR},
     #{result, mode=INOUT, jdbcType=INTEGER},
     #{execDate, mode=OUT, jdbcType=DATE}
   )}
   </select>
   #+END_EXAMPLE
   #+BEGIN_EXAMPLE java
   ProcedureMapper mapper = session.getMapper(ProcedureMapper.class);
   Pojo o = new Pojo();
   o.setRoleName("test");
   o.setResult("cc");
   o.count(o);
   System.out.println(o.getResult();
   SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
   System.out.println(sdf.format(o.getExecDate()));
   #+END_EXAMPLE

** 返回游标
   #+BEGIN_EXAMPLE xml
   <resultMap id="roleMap" type="ResultPojo">
     <id property="roleName" column="role_name"/>
   </resultMap>
   <select id="getRole" statementType="CALLABLE" resultType="TestPojo">
   {call get_role (
     #{roleName, mode=IN, jdbcType=VARCHAR},
     #{start, mode=IN, jdbcType=INTEGER},
     #{end, mode=IN, jdbcType=INTEGER},     
     #{count, mode=OUT, jdbcType=INTEGER},     
     #{result, mode=OUT, jdbcType=CURSOR, javaType=ResultSet, resultMap=roleMap}
   )}
   </select>
   #+END_EXAMPLE   
   #+BEGIN_EXAMPLE java
   @Data
   pulic class ResultPojo {
     private String roleName;
   }
   @Data
   public class TestPojo {
     private String roleName;
     private int start;
     private int end;
     private int count;
     private List<ResultPojo> result;
   }

   Pmapper mapper = session.getMapper(Pmapper.class);
   TestPojo p = new TestPojo();
   p.setRoleName("xxx");
   p.setStart(0);
   p.setEnd(10);
   p.setCount(0);
   p.setResult(new ArrayList<ResultPojo>());
   mapper.getRole(p);
   System.out.println(p.getCount());
   for (ResultPojo item : p.getResult()){
     System.out.println(item.getRoleName());
   }
   #+END_EXAMPLE

* 分页

** 通过内置的RowBounds分页
   问题：会先将所有记录查询到应用服务器，然后再根据分页信息抽取数据，因此势必有出现内存溢出的问题。
   RowBounds源码
   #+BEGIN_EXAMPLE java
   public class RowBounds {
     public static final int NO_ROW_OFFSET = 0;
     public static final int NO_ROW_LIMIT = Integer.MAX_VALUE;
     public static final RowBounds DEFAULT = new RowBounds();
     
     @Getter
     private int offset; // 从第几行开始读取，从0开始
     @Getter
     private int limit;  // 最多读取多少行
     
     public RowBounds(){
       this.offset = NO_ROW_OFFSET;
       this.limit = NO_ROW_LIMIT;
     }

     public RowBounds(int offset, int limit){
       this.offset = offset;
       this.limit = limit;
     }
   }
   #+END_EXAMPLE
   使用示例
   #+BEGIN_EXAMPLE xml
   <select id="getRole" parameterType="string" resultType="Role">
     <bind name="pattern" value="'%' + _parameter + '%'" >
     select * from role where name like #{pattern}
   </select>
   #+END_EXAMPLE
   #+BEGIN_EXAMPLE java
   public interface RoleMapper{
     List<Role> getRole(String name, RowBounds rowBounds);
   }

   RoleMapper mapper = .....
   List<Role> roles = mapper.getRole("xxx", new RowBounds(0,10));
   #+END_EXAMPLE

** 通过[[https://pagehelper.github.io][MyBatisPageHelper]]分页
   1) mybatis-config.xml配置
      #+BEGIN_EXAMPLE xml
      <plugins>
        <plugin interceptor="com.github.pagehelper.PageHelper">
          <property name="dialect" value="mysql"/>
          <property name="offsetAsPageNum" value="false"/>
          <property name="rowBoundsWithCount" value="false"/>
          <property name="pageSizeZero" value="true"/>
          <property name="reasonable" value="false"/>
          <property name="supportMethodsArguments" value="false"/>
          <property name="returnPageInfo" value="none"/>
        </plugin>
      </plugins>
      #+END_EXAMPLE
   2) SQL映射文件
      #+BEGIN_EXAMPLE xml
      <select id="getRole">
      select * from role
      </select>
      #+END_EXAMPLE
   3) 分页
      #+BEGIN_EXAMPLE java
      int pageNum = 1; // 第几页，从1开始
      int pageSize = 10; // 每页记录数目
      Page page = PageHelper.startPage(pageName, pageSize, true);
      List<Role> roles = mapper.getRole();
      int total = page.getTotal();
      #+END_EXAMPLE

*** API说明
    #+BEGIN_EXAMPLE java
    // 统计总数
    PageHelper.startPage(pageName, pageSize, true);
    // 不统计总数
    PageHelper.startPage(pageName, pageSize, false);
    // 查询所有，获取不掉用PageHelper即不执行分页操作
    PageHelper.startPage(1, 0);
    // 获取order by语句
    String orderBy = PageHelper.getOrderBy();
    Page<?> page = PageHelper.startPage(pageNum, pageSize, orderBy);
    //isReasonable分页合理化,null时用默认配置
    Page<?> page = PageHelper.startPage(pageNum, pageSize, isCount, isReasonable);
    //isPageSizeZero是否支持PageSize为0，true且pageSize=0时返回全部结果，false(默认值)时分页,null时用默认配置
    Page<?> page = PageHelper.startPage(pageNum, pageSize, isCount, isReasonable, isPageSizeZero);
    #+END_EXAMPLE

*** 线程安全问题
    原因：由于分页信息保存在静态的ThreadLocal参数中
    问题：当分页信息在当前线程运行的方法中没有被消费掉，那么有可能在其它方法中被意外使用，导致不该分页的地方出现分页操作。
    1) 不安全的用法
       #+BEGIN_EXAMPLE java
       PageHelper.startPage(1,10);
       Object o = null;
       if (o != null){
         mapper.query();
       }
       #+END_EXAMPLE
    2) 安全的用法
       #+BEGIN_EXAMPLE java
       public void f1(){
         Object o = null;
         if (o != null){
           PageHelper.startPage(1,10);
           mapper.query();
         }
       }

       public void f2(){
         try{
           Object o = null;
           PageHelper.startPage(1,10);
           if (o != null){
  
             mapper.query();
           }
         }
         finally {
           PageHelper.clearPage(); // 显式清理ThreadLocal参数
         }
       }
       #+END_EXAMPLE


    



* 代码生成器——[[http://www.mybatis.org/generator/][MyBatisGenerator]]
  遵循Data First原则，可根据数据库表生成相关代码
   - POJO
   - Mapper接口
   - SQL Mapper XML

   QBC风格的条件查询

** POM配置
   #+BEGIN_EXAMPLE xml
   <dependencies>
     <dependency>
       <groupId>org.mybatis.generator</groupId>
       <artifactId>mybatis-generator-maven-plugin</artifactId>
       <version>1.3.7</version>
       <type>maven-plugin</type>
     </dependency>
   </dependencies>
   <plugin>
    <groupId>org.mybatis.generator</groupId>
    <artifactId>mybatis-generator-maven-plugin</artifactId>
    <version>1.3.7</version>
    <configuration>
        <configurationFile>src/main/resources/mybatis-generator/generatorConfig.xml</configurationFile>
        <verbose>true</verbose>
        <overwrite>true</overwrite>
    </configuration>
    <executions>
        <execution>
            <id>Generate MyBatis Artifacts</id>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.mybatis.generator</groupId>
            <artifactId>mybatis-generator-core</artifactId>
            <version>1.3.7</version>
        </dependency>
    </dependencies>
   </plugin>
   #+END_EXAMPLE

** generatorConfig.xml
   #+BEGIN_EXAMPLE xml
   <?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE generatorConfiguration
        PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
        "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">

   <generatorConfiguration>
    <!-- 指定JDBC驱动位置 -->
    <classPathEntry
            location="C:/Oracle/Middleware/wlserver_10.3/server/lib/ojdbc6.jar"/>
    <context id="my" targetRuntime="MyBatis3">
        <commentGenerator>
            <property name="suppressDate" value="false"/>
            <property name="suppressAllComments" value="true"/>
        </commentGenerator>

        <!-- 数据库链接信息 -->
        <jdbcConnection driverClass="oracle.jdbc.driver.OracleDriver"
                        connectionURL="jdbc:oracle:thin:@172.20.16.***:1521:CARGO" userId="***"
                        password="***"/>

        <!-- domain路径 -->
        <javaModelGenerator targetPackage="ctas.test.entity"
                            targetProject="D:/yangjm/Code/CTAS/JAVAEE/CTAS2CCSP/src/main/java">
            <property name="enableSubPackages" value="true"/>
            <property name="trimStrings" value="true"/>
        </javaModelGenerator>

        <!-- SQL映射文件路径 -->
        <sqlMapGenerator targetPackage="ctas.test.entity.xml"
                         targetProject="D:/yangjm/Code/CTAS/JAVAEE/CTAS2CCSP/src/main/java">
            <property name="enableSubPackages" value="true"/>
        </sqlMapGenerator>
        
        <!-- Mapper接口路径 -->
        <javaClientGenerator targetPackage="ctas.test.mapper"
                             targetProject="D:/yangjm/Code/CTAS/JAVAEE/CTAS2CCSP/src/main/java" type="XMLMAPPER">
            <property name="enableSubPackages" value="true"/>
        </javaClientGenerator>

        <!-- 生成表 -->
        <!--<table tableName="T_FEE_AGTBILL" domainObjectName="FeeAgentBill"
               enableCountByExample="false" enableUpdateByExample="false"
               enableDeleteByExample="false" enableSelectByExample="false"
               selectByExampleQueryId="false"/>-->

        <table tableName="CTAS_FEE_BASE" domainObjectName="FeeBase"
               enableCountByExample="false" enableUpdateByExample="false"
               enableDeleteByExample="false" enableSelectByExample="false"
               selectByExampleQueryId="false">
            <!--<columnRenamingRule searchString="^D_"
                                replaceString=""/>-->
        </table>
    </context>
   </generatorConfiguration>
   #+END_EXAMPLE

* QA
  1) 参数传递方式 ~${}~ 和 ~#{}~ 的差别
     - 差别
       1) ~#{}~ 在预处理阶段会被数据库的占位符(如MySQL的 ~?~)替换，并通过绑定参数的方式处理SQL注入
          - 可附加属性
            1) javaType
            2) jdbcType, 设置当Java类型null对应的jdbc类型，默认为OTHER，这个MySQL能够识别使用，但Oracle无法识别从而抛出异常
               #+BEGIN_EXAMPLE sql
               insert into user(name, email) values(#{name}, #{email, jdbcType=NULL})
               #+END_EXAMPLE
            3) mode(存储过程)
            4) numericScale，设置数字的精度
            5) resultMap
            6) typeHandler
            7) jdbcTypeName
            8) expression(未来准备支持的功能)
       2) ~${}~ 以普通字符串拼接的方式将SQL语句和参数值进行拼接，因此不会处理SQL注入的问题
     - 应用场景？？
       1) ~${}~ 应用于拼接表名等原生jdbc不支持占位符的地方
          #+BEGIN_EXAMPLE sql
          select * from ${year}_salary
          select * from user order by ${name} ${order}
          #+END_EXAMPLE
       2) 模糊查询
          1) 通过 ~#{}~
             #+BEGIN_EXAMPLE sql
             -- 入参值为"%john%"
             select * from user where name #{name_like}
             #+END_EXAMPLE
          2) 通过 ~${}~
             #+BEGIN_EXAMPLE sql
             -- 入参值为"john"，但存在SQL注入的安全问题
             select * from user hwere name '%${name_like}%'
             #+END_EXAMPLE
  2) Mapper接口如何跟xml文件中的sql建立关联
     MyBatis通过动态代理的形式根据接口生成代理对象
  3) 拋出 ~Unsupported major.minor version 52.0~
     其实就是项目运行环境为JDK1.8，但现在提供的运行环境低于JDK1.8。
     | JDK版本 | Standord Parser |
     |---------+-----------------|
     |       8 |              52 |
     |       7 |              51 |
     |       6 |              50 |
     |       5 |              49 |
     |     1.4 |              48 |
     |     1.3 |              47 |
     |     1.2 |              46 |
     |     1.1 | 45              |
     - Eclipse下修复：将Build Path下的JDK修改为JDK8即可。

