* Spring MVC 4

** JavaEE分层模型
   1) 表现层(View)
      底层通过称为DTO(Data Transfer Object, 数据传输对象)的JavaBean向表现层传输状态信息。
      - Servlet和JSP，JSP将被Web服务器编译为Servlet，然后Web服务器运行Servlet对外提供服务。Servlet3.x新增如下特性
        - 异步请求
        - 注解
        - 增强的Servlet API
        - 非阻塞IO
      - FreeMarker
      - Velocity
   2) 控制器层(Controller)
   3) 服务逻辑层(Service)
   4) 数据访问服务层(DAO,Data Access Object)
      在MyBatis中称为Mapper层
      - Hibernate，全自动ORM
      - MyBatis，半自动ORM
   5) 领域对象层(Domain Object)
      由一系列POJO(Plain Old Java Object, 普通的传统的Java对象)组成。

** Spring MVC 4
   通过继承HttpServlet的org.springframework.web.servlet.DispatcherServlet作为前端控制器来拦截用户请求并分派请求到具体执行业务控制的Controller，并处理请求。视图技术包含JSP、Velocity、Tiles、iText和POI等，功能分工上包含控制器、验证器、命令对象、模型对象、处理程序映射视图解析器等。
   Spring核心容器依赖common-logging的JAR包。

*** MVC模型
    1) Model1
       View和Controller层均通过JSP实现，将控制逻辑和表现逻辑混杂在一起，代码重用性、可扩展性和维护性极低，但由于架构简单开发速度快。
    2) Model2
       JSP作为View、Servlet作为Controller、JavaBean作为Model，提高代码重用、可扩展和维护性。

*** 简单应用
    目录结构
    #+BEGIN_EXAMPLE
    - ProjectName/
        - .idea/
        - lib/ # 内含Spring MVC相关依赖的JAR
        - src/
            - org.myproject.controller/
                - HelloController.java
        - web/
            - WEB-INF/
                - web.xml
                - dispatch-servlet.xml
                - content/
                    - welcome.jsp
        - pom.xml
        - ProjectName.iml
    #+END_EXAMPLE

**** 传统方式
     #+BEGIN_EXAMPLE xml
     <!-- WebContent/WEB-INF/web.xml -->
     <?xml version="1.0" encoding="UTF-8"?>
     <web-app  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://java.sun.com/xml/ns/javaee" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" id="WebApp_ID" version="3.0">

       <display-name>My first Spring MVC 4 Web Application</display-name>

       <!-- 加载Servlet WebApplicationContext -->
       <context-param>
         <param-name>contextConfigLocation</param-name>
         <param-value>/WEB-INF/dispatcher-servlet.xml</param-value>
       </context-param>
       <servlet>
         <servlet-name>dispatcher</servlet-name>
         <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
         <load-on-startup>1</load-on-startup>
       </servlet>
       <servlet-mapping>
         <servlet-name>dispatcer</servlet-name>
         <url-pattern>/</url-pattern>
       </servlet-mapping>
       
       <listener>
         <!-- 加载Root WebApplicationContext，然后由它再启动Servlet WebApplicationContext的加载，因此没有个配置时无法启用Spring MVC -->
         <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
       </listener>

     </web-app>
     #+END_EXAMPLE
     Spring MVC解析contextConfigLocation指定的文件并根据文件配置信息创建一个基于ApplicationContext容器的WebApplicationContext容器对象(称为上下文环境)。WebApplicationContext需要ServletContext，因此必须拥有Web容器的提前下才能完成启动Spring Web应用上下文的工作。
     Spring MVC将具体的Controller称为Handle

     在dispatcher-servlet.xml通过Bean组件配置handler和URL路径映射
     #+BEGIN_EXAMPLE xml
     <!-- /WEB-INF/dispatcher-servlet.xml -->
     <!-- 配置Handler和URL路径映射 -->
     <bean name="/hello" class="org.myproject.controller.HelloController"/>
     <!-- 配置处理映射器将bean节点的name作为URL路径进行匹配查找 -->
     <bean class="org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping"/>
     <!-- 启用继承HandlerAdapter的SimpleControllerHandlerAdapter实例来调用Handler的handleRequest方法 -->
     <bean class="org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter"/>
     <!-- 配置View Resolver -->
     <bean class="org.springframework.web.servlet.view.InternalResourceViewResolver“>
       <property name="prefix">
         <value>/WEB-INF/views/</value>
       </property>
       <property name="suffix">
         <value>.jsp</value>
       </property>
     </bean>

     <!-- 
         /WEB-INF/views下的文件默认不能通过URL直接访问，必须通过Controller进行映射。
         但对于Controller没有任何逻辑，为执行映射编写一个Controller显然是徒劳的，因此可通过<mvc:view-controller path=""/>简化映射操作
     -->
     <mvc:view-controller path="/success"/> <!-- 访问/success时会自动映射到/WEB-INF/views/success.jsp -->
     #+END_EXAMPLE

     #+BEGIN_EXAMPLE java
     // src/org/myproject/controller/HelloController.java
     package org.myproject.controller;
     import javax.servlet.http.HttpServletRequest;
     import javax.servlet.http.HttpServletResponse;
     import org.apache.commons.logging.Log;
     import org.apache.commons.logging.LogFactory;
     import org.springframework.web.servlet.ModelAndView;
     import org.springframework.web.servlet.mvc.Controller;

     public class HelloController implements Controller {
         private static final Log logger = LogFactory.getLog(HelloController.class);
        
         // 返回一个包含视图名称或视图名称和模型的ModelAndView对象
         @Override
         public ModelAndView handleRequest(HttpServletRequest request, HttpServletResponse response){
             logger.info("handleRequest invoked");
             ModelAndView mv = new ModelAndView();
             // 添加模型数据，可为任意的POJO对象
             mv.addObject("message", "Hello World!");
             // 设置逻辑视图名，视图解析器会解析到具体的视图页面
             // 将视图页面存放在/WEB-INF/views下，那么就不能通过URL直接访问视图页面
             mv.setViewName("welcome");
            
             return mv;
         }
     }
     #+END_EXAMPLE

     #+BEGIN_EXAMPLE html
     <!-- WebContent/WEB-INF/views/welcome.jsp -->
     <%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
     <!doctype html>
     <html>
       <body>
         ${requestScope.message}
         <!-- 或者 -->
         ${message}
       </body>
     </html>
     #+END_EXAMPLE

**** 注解方式
     Spring MVC 2.5后支持注解方式。
     #+BEGIN_EXAMPLE xml
     <!-- WEB-INF/dispatch-servlet.xml -->
     <!-- Spring自动扫描base-package下的包和子包的Java文件，将存在Spring注解的类， -->
     <context:component-scan base-package="org.myproject.controller"/>
     #+END_EXAMPLE

     #+BEGIN_EXAMPLE java
     // src/org/myproject/controller/HelloController.java
     package org.myproject.controller;
     import org.apache.commons.logging.Log;
     import org.apache.commons.logging.LogFactory;
     import org.springframework.web.servlet.ModelAndView;
     import org.springframework.stereotype.Controller;
     import org.springframework.web.bind.annotation.RequestMapping;
     import org.springframework.web.bind.annotation.RequestParam;

     @Controller
     public class HelloController {
         private static final Log logger = LogFactory.getLog(HelloController.class);
        
         // 返回一个包含视图名称或视图名称和模型的ModelAndView对象
         @RequestMapping("/hello")
         public ModelAndView showMessage(
                 @RequestParam(value="name", required=false, defaultValue="world") String name){
             logger.info("handleRequest invoked");
             ModelAndView mv = new ModelAndView();
             // 添加模型数据，可为任意的POJO对象
             mv.addObject("message", "Hello World!");
             // 设置逻辑视图名，视图解析器会解析到具体的视图页面
             // 将视图页面存放在/WEB-INF/views下，那么就不能通过URL直接访问视图页面
             mv.setViewName("welcome");
            
             return mv;
         }
     }     
     #+END_EXAMPLE
     
*** DispatcherServlet作用
    1) org.springframework.web.servlet.DispatcherServlet内部操作
       #+BEGIN_EXAMPLE java
       protected void initStrategies(ApplicationContext context){
           initMultipartResolver(context); // 初始化上传文件解析器
           initLocaleResolver(context); // 初始化本地化解析器
           initThemeResolver(contect); // 初始化主题解析器
           initHandlerMappings(context); // 初始化N个处理器映射器
           initHandlerAdapters(context); // 初始化N个处理器适配器
           initHandlerExceptionResolvers(context); // 初始化N个处理器异常解析器，执行过程中遇到异常将交给HandlerExceptionResolver来解析
           initRequestToViewNameTranslator(context); // 初始化视图名称转换器
           initViewResolvers(context); // 初始化N个视图解析器
           initFlashMapManager(context); // 初始化flash映射管理器
       }
       #+END_EXAMPLE
    2) org.springframework.web.servlet.DispatcherServlet.properties配置文件包含默认组件
       #+BEGIN_EXAMPLE xml
       // 若查找不到name值为localeResolver，class值没有继承LocaleResolver结尾Bean组件时采用默认值
       org.springframework.web.servlet.LocaleResovler=org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver
       // 若查找不到name值为themeResolver，class值没有继承ThemeResolver结尾Bean组件时采用默认值
       org.springframework.web.servlet.ThemeResolver=org.springframework.web.servlet.theme.FixedThemeResolver
       // 若detectAllHandlerMappings为true(默认值)，则根据类型匹配机制在上下文和Spring容器中查找所有class值继承HandlerMapping的Bean组件
       // 若detectAllHandlerMappings为false，则查找name值为handlerMapping，class值继承HandlerMapping的Bean组件
       // 若上述两个条件都没有匹配到时采用默认值
       org.springframework.web.servlet.HandlerMapping=org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping, org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping
       // 若detectAllHandlerAdapters为true(默认值)，则根据类型匹配机制在上下文和Spring容器中查找所有class值继承HandlerAdapter的Bean组件
       // 若detectAllHandlerAdapters为false，则查找name值为handlerAdapter，class值继承HandlerAdapter的Bean组件
       // 若上述两个条件都没有匹配到时采用默认值
       org.springframework.web.servlet.HandlerAdapter=org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter,org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter,org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter
       // 若detectAllHandlerExceptionResolvers为true(默认值)，则根据类型匹配机制在上下文和Spring容器中查找所有class值继承HandlerExceptionResolver的Bean组件
       // 若detectAllHandlerExceptionResolvers为false，则查找name值为handlerExceptionResolver，class值继承HandlerExceptionResolver的Bean组件
       // 若上述两个条件都没有匹配到时采用默认值
       org.springframework.web.servlet.HandlerExceptionResolver=org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerExceptionResolver,org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver,org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver
       // 若查找不到name值为viewNameTranslator，class值没有继承ViewNameTanslator结尾Bean组件时采用默认值
       org.springframework.web.servlet.RequestToViewNameTranslator=org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator
       // 若detectAllViewResolvers为true(默认值)，则根据类型匹配机制在上下文和Spring容器中查找所有class值继承ViewResolver的Bean组件
       // 若detectAllViewResolvers为false，则查找name值为viewResolver，class值继承ViewResolver的Bean组件
       // 若上述两个条件都没有匹配到时采用默认值
       org.springframework.web.servlet.ViewResolver=org.springframework.web.servlet.view.InternalResourceViewResolver
       // 若查找不到name值为flashMapManager，class值没有继承FlashMapManager结尾Bean组件时采用默认值
       org.springframework.web.servlet.FlashMapManager=org.springframework.web.servlet.support.SessionFlashMapManager
       // 若查找不到name值为multipartResolver，class值没有继承MultipartResolver结尾Bean组件时不加载该类型的组件
       #+END_EXAMPLE
    3) 作用
       1) 对请求URL进行解析得到URI，然后根据URI调用HandlerMapping实例获得Handler对象和对应的拦截器，组成一个HandlerExecutionChain对象返回。然后选择合适的HandlerAdpater实例处理Handler实例。
       2) 解析请求体转换为对象
       3) 根据HTTP协议将响应对象序列化
    4) WebApplicationContext层次
       | *DispatcherServelt*                                                                               |
       |---------------------------------------------------------------------------------------------------|
       | Root WebApplicationContext(containing middle-tier services, datasources, etc.)                    |
       | Services/Repositories/Components                                                                  |
       |---------------------------------------------------------------------------------------------------|
       | ^Delegates if no bean found^                                                                      |
       |---------------------------------------------------------------------------------------------------|
       | Servlet WebApplicationContext(containing controllers, view resolvers and other web-related beans) |
       | Controllers/ViewResolver/HandlerMapping                                                           |
       - AOP中是区分Servlet WebApplicationContext的方法和Root WebApplicationContext的方法的拦截和增强。

*** 注解
    1) ~@Controller~
       全限定类名org.springframework.stereotype.Controller，其标识的类实例将作为作为Controller。其标识为 ~@RequestMapping~ 的公开实例方法将作为具体的handler。
       在dispatcher-servlet.xml中通过配置 ~<context:component-scan base-package=""/>~ 启动包扫描功能，自动注册带 ~@Controller,@Service,@repository,@Component~ 等注解的类成为Spring Bean。
       #+BEGIN_EXAMPLE java
       import org.springframework.stereotype.Controller;
       import org.springframework.web.bind.annotation.RequestMapping;
       import org.springframework.ui.Model;
       
       @Controller
       public class HelloController {
           @RequestMapping("/hello")
           public String index(Model m){
               m.addAttribute("message", "test") // jsp视图中通过${message}、${request.message}或${requestScope.message}获取该值
               return "helloworld" // 返回逻辑视图名称，Spring会自动通过RequestToViewNameTranslator获取物理的ViewName(如/WEB-INF/views/helloworld.jsp)
           }
       }
       #+END_EXAMPLE
    2) ~@RestController~
       将 ~@Controller~ 和 ~@ResponseBody~ 结合，用于标识RESTful API的控制器
    3) ~@RequestMapping~
       全限定类名org.springframework.web.bind.annotation.RequestMapping，可用于标识类和实例方法，用于设置请求与handler匹配条件
       - 参数
         | 属性     | 类型            | 说明                                                                     | 示例                                                            |
         |----------+-----------------+--------------------------------------------------------------------------+-----------------------------------------------------------------|
         | value    | String[]        | URI                                                                      |                                                                 |
         | name     | String          | 映射地址的别名                                                           |                                                                 |
         | method   | RequestMethod[] | 请求方法类型：RequestMethod.GET/POST/HEAD/OPTIONS/PUT/PATCH/DELETE/TRACE | @RequestMapping(method={RequestMethod.GET, RequestMethod.POST}) |
         | consumes | String[]        | 指定请求头字段Content-Type的必须匹配的值，如application/json,text/xml等  | @RequestMapping(consumes="application/json")                    |
         | produces | String[]        | 指定请求头字段Accept的必须匹配的值                                       | @RequestMapping(produces="application/json")                    |
         | params   | String[]        | 请求参数必须匹配的值                                                     | @RequestMapping(params="myParam=123"                            |
         | headers  | String[]        | 请求头必须匹配的头字段及值                                               | @RequestMapping(headers="Referer=http://test.com")              |
         | Path     | String[]        |                                                                          |                                                                 |
    4) ~@GetMapping, @PostMapping~ 和 ~@PutMapping, @DeleteMapping~
    5) Handler方法入参类型
       - javax.servlet.ServletRequest 或 javax.servlet.http.HttpServletRequest
       - javax.servlet.ServletResponse 或 javax.servlet.http.HttpServletResponse
       - javax.servlet.http.HttpSession
       - java.util.Locale
       - java.util.Map
       - java.io.InputStream 或 java.io.Reader
       - java.io.OutputStream 或 java.io.Writer
       - HttpEntity<?>
       - java.security.Principal
       - org.springframework.ui.Model
       - org.springframework.ui.ModelMap
       - org.springframework.web.servlet.ModelAndView
       - org.springframework.web.servlet.mvc.support.RedirectAttributes
       - org.springframework.validation.Errors
       - org.springframework.validation.BindingResult
       - org.springframework.web.bind.support.SessionStatus
       - org.springframework.web.util.UriComponentsBuilder
       - @PathVariable, @@MatrixVariable
       - @RequestParam, @RequestHeader, @RequestBody, @RequestPart
    6) Handler方法返回值类型
       - org.springframework.web.servlet.ModelAndView
       - org.springframework.ui.Model
       - java.util.Map<K,V>
       - org.springframework.web.servlet.View
       - java.lang.String, 作为视图名称
         - 若匹配 ~redirect:<handle-name>~ 或 ~redirect:/path/to/static/resource~ 则为请求重定向
         - 若匹配 ~forward:<handle-name>~ 或 ~forward:/path/to/static/resource~ 则为请求转发
       - HttpEntity 或 ResponseEntity
       - java.util.concurrent.Callable
       - org.springframework.web.context.request.async.DeferredResult
       - void, @RequestMapping的value值即作为视图名称
    7) Model、ModelMap和ModelAndView
       Spring MVC 在调用处理方法前会创建一个隐含的作为模型数据存储容器的模型实例，若Handler相关方法入参类型为Model或ModelMap时就会将隐含的模型实例引用传递给这些参数。
       #+BEGIN_EXAMPLE java
       @Controller
       public class HelloController {
           // @ModelAttribute 修饰的方法会在实际的handle执行前先执行，并且可以接收请求的参数
           // 可用于将从请求体获取的数据加工存放到Model或ModelMap实例中供后续的Handle使用
           @ModelAttribute
           public void createUserModel(String loginname, String password, Model model, ModelMap mm, ModelAndView mv){
               User user = User.builder()
                               .loginname(loginname)
                               .password(password);
               model.addAttribute("user", user);
               mm.addAttribute("user", user);
               mv.addObject("user", user);
           }
           
           @RequestMapping("/hello")
           public ModelAndView login(Model model, ModelMap mm, ModelAndView mv){
               User user1 = (User) model.asMap().get("user");
               User user2 = (User) mm.get("user");
               User user3 = (User) mv.getModel().get("user");
               mv.setViewName("viewname");

               return mv;
           }

       }
       #+END_EXAMPLE
    8) 参数绑定注解
       1) ~@RequestParam~
          全限定类名org.springframework.web.bind.annotation.RequestParam，用于将指定的请求参数(querystring和request body中的参数)赋值给Handle的型参。
          - 参数
            | 属性         | 类型    | 说明               |
            |--------------+---------+--------------------|
            | name         | String  | 指定请求参数的名称 |
            | value        | String  | 指定请求参数的名称 |
            | requried     | boolean | 是否必须绑定       |
            | defaultValue | String  | 默认值             |
          - 示例
            #+BEGIN_EXAMPLE java
            @RequestMapping("/login")
            public String login(@RequestParam(value="username", required=false, defaultValue="john") String username){
              // TODO
            }

            @RequestMapping(value="/register", method=RequestMethod.POST)
            public String login(@RequestParam(value="username", required=false, defaultValue="john") String username){
              // TODO
            }
            #+END_EXAMPLE
       2) ~@PathVariable~
          全限定类名org.springframework.web.bind.annotation.PathVariable，用于获取请求URL中的动态参数。仅含String类型的value参数，若省略则默认绑定同名参数。
          - 示例
            #+BEGIN_EXAMPLE java
            @RequestMapping(value="/url_include_dynamic_variable/{userId}")
            public void index(@PathVariable String userId){
              // TODO
            }
            #+END_EXAMPLE
       3) ~@RequestHeader~
          全限定类名org.springframework.web.bind.annotation.RequestHeader，用于将指定的请求头字段映射到Handle形参。
          - 参数
            | 属性         | 类型    | 说明                 |
            |--------------+---------+----------------------|
            | name         | String  | 指定请求头字段的名称 |
            | value        | String  | 指定请求头字段的名称 |
            | requried     | boolean | 是否必须绑定         |
            | defaultValue | String  | 默认值               |
          - 示例
            #+BEGIN_EXAMPLE java
            @RequestMapping("/path/to/resource")
            public void index(@RequestHeader("Accept") String[] accepts){
              // TODO
            }
            #+END_EXAMPLE
       4) ~@CookieValue~
          全限定类名org.springframework.web.bind.annotation.CookieValue，用于将指定的请求头字段Cookies或Cookies2中的键值对绑定到Handle形参。
          - 参数
            | 属性         | 类型    | 说明         |
            |--------------+---------+--------------|
            | name         | String  | 指定键       |
            | value        | String  | 指定键       |
            | requried     | boolean | 是否必须绑定 |
            | defaultValue | String  | 默认值       |
          - 示例
            #+BEGIN_EXAMPLE java
            @RequestMapping("/path/to/resource")
            public void index(@CookieValue("JSESSIONID") String sessionId){
              // TODO
            }
            #+END_EXAMPLE
       5) ~@SessionAttributes~
          全限定类名org.springframework.web.bind.annotation.SessionAttributes，只能修饰类。用于指定Model实例中哪些属性将转存到HttpSession对象中。
          - 参数
            | 属性  | 类型       | 说明                                                 |
            |-------+------------+------------------------------------------------------|
            | names | String[]   | Model中属性的名称，即存储到HttpSession中的属性的名称 |
            | value | String[]   | 属性names的别名                                      |
            | types | Class<?>[] | 存入HttpSession中的属性的类型                        |
          - 示例
            #+BEGIN_EXAMPLE java
            @Controller
            @SessionAttributes(value={"user","dept"}, types={User.class, Dept.class})
            public class HelloController{
                @RequestMapping("/hello")
                public String hello(Model model){
                    model.addAttribute("user", User.builder().username("john"));
                    model.addAttribute("dept", Dept.builder().name("IT"));
                    // 在jsp视图中可通过${sessionScope.user}从HttpSession中获取User实例
                    return "hello";
                }
            }
            #+END_EXAMPLE
       6) ~@ModelAttribute~
          全限定类名org.springframework.web.bind.annotation.ModelAttribute，将请求参数绑定到Model实例。被修饰的方法会在每个相同Controller中被@RequestMapping修饰的方法执行前被执行。
          - 参数
            | 属性  | 类型   | 说明                        |
            |-------+--------+-----------------------------|
            | value | String | 指定绑定到Model中的属性名称 |
          - 示例
            #+BEGIN_EXAMPLE java
            @ModelAttribute("name")
            public String getName(@RequestParam("username") String username){
                // 返回值将作为Model实例属性name的值
                return username;
            }
            
            @ModelAttribute
            public User getUser(){
                // 若没有指定属性名称，且返回值为某实例，那么会自动对类名作小写转换作为Model的属性名称
                return User.builder().name("john");
            }

            @ModelAttribute
            public void getUserManually(Model m){
                m.setAttribute("user", User.builder().name("john"));
            }

            @RequestMapping("/index")
            @ModelAttribute("message")
            public String index(){
                 // 当@RequestMapping和@ModelAttribute同时修饰一个方法时，该方法返回值将作为Model实例属性值，而视图名称即保持与RequestMapping的属性value值一致
                 return "helloworld";
            }

            @RequestMapping("/user")
            public void user(@ModelAttribute("name") String name){
                // 从Model实例中将属性name值赋值给形参name。
            }
            #+END_EXAMPLE
       7) ~@RequestBody~
          全限定类名org.springframework.web.bind.annotation.RequestBody，用于读取请求体中部分数据。内部使用HttpMessageConverter实现类对请求体进行解析，然后将结果绑定到Handle的形参上。
          - GET或POST请求方式，以下ContentType的处理情况
            - application/x-www-form-urlencoded，可通过@RequestParam、@ModelAttribute和@RequestBody获取
            - multipart/form-data，@RequestBody则处理不了
            - 其他类型(包含application/json、application/xml)，必须用@RequestBody处理
          - PUT请求方式，以下ContentType的处理情况
            - application/x-www-form-urlencoded，必须用@RequestBody处理
            - multipart/form-data，@RequestBody则处理不了
            - 其他类型(包含application/json、application/xml)，必须用@RequestBody处理
          - 参数
            | 属性     | 类型    | 说明                               |
            |----------+---------+------------------------------------|
            | required | boolean | 是否必须要存在请求体，默认值为true |

    9) ~@ResponseBody~
    10) ~@ResponseStatus~
        - 示例
          #+BEGIN_EXAMPLE java
          @PostMapping("/")
          @ResponseBody
          @ResponseStatus(HttpStatus.CREATED)
          public String[] create(@ResponseBody NewOrderRequest newOrder){
              return new String[] {"a", "b"};
          }
          #+END_EXAMPLE

*** 静态资源

    1) 在注册DispatcherServlet映射前，先注册应用服务器的defaultServlet拦截所有静态资源
       #+BEGIN_EXAMPLE xml
       <!--WEB-INF/web.xml-->
       <!--
         Tomcat, Jetty, JBoss, and GlassFish  默认 Servlet的名字 -- "default"
         Google App Engine 默认 Servlet的名字 -- "_ah_default"
         Resin 默认 Servlet的名字 -- "resin-file"
         WebLogic 默认 Servlet的名字  -- "FileServlet"
         WebSphere  默认 Servlet的名字 -- "SimpleFileServlet"
       -->
       <servlet-mapping>
           <servlet-name>default</servlet-name>
           <url-pattern>*.js</url-pattern>
       </servlet-mapping>
       <servlet-mapping>
           <servlet-name>default</servlet-name>
           <url-pattern>*.css</url-pattern>
       </servlet-mapping>
       
       <!-- DispatcherServelt 配置 -->
       #+END_EXAMPLE
       - *注意: 静态资源不能位于WEB-INF下，必须位于Web Application根目录下。*
    2) 通过 ~<mvc:resources mapping="" location=""/>~ 实现(Spring 3.0.4+支持)
       #+BEGIN_EXAMPLE xml
       <!--WEB-INF/dispatcher-servlet.xml-->
       <mvc:annotation-driven />
       <!-- 静态资源位于Web Application根目录下 -->
       <mvc:resources mapping="/style/**" location="/css/" />
       <!-- 静态资源位于WEB-INF目录下 -->
       <mvc:resources mapping="/script/**" location="/WEB-INF/script/" />
       <!-- 静态资源可以打包压缩到JAR包中 -->
       #+END_EXAMPLE
       - 原理
         将mapping值和ResourceHttpRequestHandler作为键值对加入到SimpleUrlHandlerMapping的urlMap中，那么当请求静态资源时就会使用ResourceHttpRequestHandler处理。
    3) 通过 ~<mvc:default-servlet-handler/>~ 实现
       #+BEGIN_EXAMPLE xml
       <!--WEB-INF/dispatcher-servlet.xml-->
       <mvc:annotation-driven />
       <mvc:default-servlet-handler/>
       #+END_EXAMPLE
       - *注意: 静态资源不能位于WEB-INF下，必须位于Web Application根目录下。*
       - 原理
         可以理解为第一个方法的进化版，将 ~/**~ 和 ~org.springframework.web.servlet.resource.DefaultServletHttpRequestHandler~ 作为键值对加入到SimpleUrlHandlerMapping，DefaultServletHttpRequestHandler会调用应用服务器的defaultServlet。
       - 多个HandlerMapping的执行顺序
         HandlerMapping通过属性order值从小往大执行，若通过当前HandlerMapping找到Handler则中止当前流程。
         1) DefaultAnnotationHandlerMapping 的 order 值为 0;
         2) ~<mvc:resources/>~ 的 order 值为 2147483646;
         3) ~<mvc:default-servlet-handler/>~ 的 order 值为 2147483647;

*** 信息转换
    将请求体转换为对象，将对象转换为响应体。Spring3.0+新增接口HttpMessageConverter<T>，和一堆具体的实现类来处理信息转换。
    DispatcherServlet默认装配了RequestMappingHandlerAdapter作为HandlerAdapter组件的实现类，而RequestMappingHanlderAdapter会调用HttpMessageConverter实例。
    默认装配的实例有：
    - StringHttpMessageConverter
      - 将请求信息转换为String，可以读取所有MIME(*/*)的请求信息，可通过设置supportMediaTypes属性指定MIME。
      - 响应信息的MIME为text/plain
    - ByteArrayHttpMessageConverter
      - 将请求信息转换为byte[]，可以读取所有MIME(*/*)的请求信息，可通过设置supportMediaTypes属性指定MIME。
      - 响应信息的MIME为application/octet-stream
    - SourceHttpMessageConverter
      - 将请求信息转换为javax.xml.transform.[dom.DOMSource|sax.SAXSource|stream.StreamSource]，可以读取的MIME包含text/xml和application/xml的请求信息。
      - 响应信息的MIME为text/xml或application/xml
    - XmlAwareFormHttpMessageConverter
      继承FormHttpMessageConverter，当表单属性是XML数据，则用该转换器
      - FormHttpMessageConverter
        - 将请求信息转换org.springframework.util.MultiValueMap<String, ?>类型，支持读取MIME为application/x-www-form-urlencoded，不支持multipart/form-data。
        - 响应信息的MIME为application/x-www-form-urlencoded或multipart/form-data

    通过Bean组件自定义RequestMappingHandlerAdapter装配的HttpMessageConverter实例
    #+BEGIN_EXAMPLE xml
    <!-- WEB-INF/applicationContext.xml -->
    <bean class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">
        <property name="messageConverters">
            <list>
                <bean class="org.springframework.http.converter.StringHttpMessageConverter"/>
                <bean class="org.springframework.http.converter.xml.XmlAwareFormHttpMessageConverter"/>
                <bean class="org.springframework.http.converter.ByteArrayHttpMessageConverter"/>
                <bean class="org.springframework.http.converter.BufferedImageHttpMessageConverter"/>
            </list>
        </property>
    </bean>
    #+END_EXAMPLE

    
**** 接收JSON数据
     

**** 响应JSON数据

*** 国际化

    基于Java国际化通过提供不同国家/语言环境的消息资源，然后通过ResourceBundle加载指定Locale对应的资源文件，再取得该资源文件中指定key对应的消息。
    Java国际化利用 ~java.util.ResourceBundle~

    Spring MVC 两种方式输出国际化消息：
    1) 通过 Spring MVC 标签库在视图上输出国际化消息
    2) 通过 ~org.springframework.web.servlet.support.RequestContext~ 的 ~getMessage()~ 方法在 Controller 的 Handle中输出国际化消息

    支持3种语言环境存储解析器：
    1) AcceptHeaderLocaleResolver，默认值
    2) SessionLocaleResolver
    3) CookieLocaleResolver

    资源文件路径规则： ~<basename>_<locale>.properties~ ，如 message_zh_CN.properties 和 message_en_US.properties。
    
**** AcceptHeaderLocaleResolver实例
     1) 配置国际化资源文件
        #+BEGIN_EXAMPLE xml
        <!-- /WEB-INF/dispatcher-servlet.xml -->
        <bean id="messageSource"
              class="org.springframework.context.support.ResourceBundleMessageSource">
              <!-- 对于多个资源文件时，property组件的name值设置为basenames，list组件则列出资源文件名称前缀 -->
              <property name="basenames">
                  <list>
                      <value>message</value>
                      <value>fkit</value>
                  </list>
              </property>
              <!--
                  单个资源文件时，property组件的name值设置为basename，value值为资源文件名前缀
                  <property name="basename" value="message">
              -->
        </bean>
        #+END_EXAMPLE
     2) 配置多语言资源文件
        #+BEGIN_EXAMPLE
        # message_en_US.properties
        loginname = Login name:
        submit = Submit
        welcome = Welcome {0} access fkit
        #+END_EXAMPLE
     3) 配置语言环境存储解析器
        #+BEGIN_EXAMPLE xml
        <!-- /WEB-INF/dispatcher-servlet.xml -->
        <mvc:interceptors>
            <bean class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor"/>
        </mvc:interceptors>
        <bean id="localeResolver" class="org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver"/>
        #+END_EXAMPLE
     4) message标签在视图输出国际化消息
        #+BEGIN_EXAMPLE jsp
        <%@taglib prefix="spring" uri="http://www.springframework.org/tags" %>
        <spring:message code="loginname"/>
        #+END_EXAMPLE
        - message标签的属性
          | 属性              | 描述                                            |
          |-------------------+-------------------------------------------------|
          | arguments         | 标签的参数，类型为字符串、数组或对象            |
          | argumentSeparator | 标签参数的分隔符                                |
          | code              | 资源文件的键                                    |
          | htmlEscape        | boolean值，被渲染的值是否应该进行HTML转义       |
          | javaScriptEscape  | boolean值，被渲染的值是否应该进行JavaScript转义 |
          | message           | MessageSourceResolvable参数                     |
          | scope             | 保存var属性中定义的变量的作用范围               |
          | text              | 如果code对应的值不存在，所显示的默认文本        |
          | var               | 用于保存消息的变量                              |
     5) 在Controller的Handle中输出国际化消息
        #+BEGIN_EXAMPLE java
        @RequestMapping("/index")
        public void index(HttpServletRequest request, Model model){
            RequextContext context = new RequestContext(request);
            loginname = context.getMessage("loginname");
            model.addAttribute("loginname", loginname);
        }
        #+END_EXAMPLE

**** SessionLocaleResolver实例
     将Locale实例保存到HttpSession中
     1) 配置语言环境存储解析器
        #+BEGIN_EXAMPLE xml
        <!-- /WEB-INF/dispatcher-servlet.xml -->
        <mvc:interceptors>
            <bean class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor"/>
        </mvc:interceptors>
        <bean id="localeResolver" class="org.springframework.web.servlet.i18n.SessionLocaleResolver"/>
        #+END_EXAMPLE        
     2) 在Controller中设置语言环境信息
        #+BEGIN_EXAMPLE java
        @RequestMapping("/{formName}")
        public String setLocale(
            @PathVariable String formName,
            @RequestParam("request_locale") String request_locale,
            HttpServletRequest request){
            
            if (request_locale != null){
                if (request_locale.equals("zh_CN")){
                    Locale locale = new Locale("zh", "CN");
                    request.getSession().setAttribute(SessionLocaleResolver.LOCALE_SESSION_ATTRIBUTE_NAME, locale);
                }
                else{
                     request.getSession()
                            .setAttribute(SessionLocaleResolver.LOCALE_SESSION_ATTRIBUTE_NAME,
                                          LocaleContextHolder.getLocale());
                }
            }
            
            return formName;
        }
        #+END_EXAMPLE
**** CookieLocaleResolver实例
     1) 配置语言环境存储解析器
        #+BEGIN_EXAMPLE xml
        <!-- /WEB-INF/dispatcher-servlet.xml -->
        <mvc:interceptors>
            <bean class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor"/>
        </mvc:interceptors>
        <bean id="localeResolver" class="org.springframework.web.servlet.i18n.CookieLocaleResolver"/>
        #+END_EXAMPLE
     3) 在Controller中设置语言环境信息
        #+BEGIN_EXAMPLE java
        @RequestMapping("/{formName}")
        public String setLocale(
            @PathVariable String formName,
            @RequestParam("request_locale") String request_locale,
            HttpServletRequest request,
            HttpServletResponse response){
            
            if (request_locale != null){
                if (request_locale.equals("zh_CN")){
                    Locale locale = new Locale("zh", "CN");
                    (new CookieLocaleResolver()).setLocale(request, response, locale);
                }
                else{
                    (new CookieLocaleResolver()).setLocale(request, response, LocaleContextHolder.getLocale());
                }
            }
            
            return formName;
        }
        #+END_EXAMPLE
*** 数据转换、格式化和数据校验
    转换流程：
    1) 通过ServletRequest获取请求消息，并通过反射获取Handle入参对象，将这些信息交给DataBinder
    2) DataBinder调用装配在 Spring Web 上下文中的 ConversionService 组件进行数据类型转换、格式化工作，并将 ServletRequest 中的消息填充的参数对象中
    3) 调用 Validator 组件堆已绑定的参数对象进行数据合法性校验
    4) 最终生成数据绑定结果 BindingResult 对象，其包含 *参数对象* 和 *校验错误对象*

**** 数据转换
     Spring MVC 提供的Converter不单可以实现String到任意Java类型的转换，还可以实现任意Java类型到其他Java类型的转换。

***** 自定义日期转换器
     ~<mvc:annotation-driven/>~ 自动注册 RequestMappingHandlerMapping 和 RequestMappingHandlerAdapter 为 @Controller 分发请求所必须的。此外还注册了一个默认的 ConversionService - FormattingConversionServiceFactoryBean 内置很多类型转换器足以满足大部分类型转换。
     #+BEGIN_EXAMPLE java
     // 实现Converter<S,T>接口的转换器
     public class StringToDateConverter implements Converter<String, Date>{
         private String datePattern;
         public void setDatePattern(String datePattern){
             this.datePattern = datePattern;
         }

         @Override
         public Date convert(String date){
             try{
                 SimpleDateFormat dateFormat = new SimpleDateFormat(this.datePattern);
                 return dateFormat.parse(date);
             }
             catch (Exception e){
                 return null; // 返回null则会继续使用其他转换器
             }
         }
     }
     #+END_EXAMPLE
     修改converters属性注册自定义转换器
     #+BEGIN_EXAMPLE xml
     <!-- dispatcher-servlet.xml -->
     <mvc:annotation-driven conversion-service="conversionService">
     <bean id="conversionService"
           class="org.springframework.context.support.ConversionServiceFactoryBean">
           <property name="converters">
               <list>
                   <bean class="path.to.StringToDateConverter"
                         p:datePattern="yyyy-MM-dd"/>
               </list>
           </property>
     </bean>
     #+END_EXAMPLE
     存在3种类型转换器接口
     1) Converter<S, T>
     2) ConverterFactory<S, R>
     3) GenericConverter

**** 格式化

**** 数据校验

*** RESTful API    

*** WebService

*** 文件上传下载
    
**** 文件上传
     Spring MVC 使用 Apache Commons FileUpload 技术实现一个 MultipartResolver 实现类 CommonMultipartResolver。
     示例：
     #+BEGIN_EXAMPLE xml
     <!-- dispatcher-servlet.xml -->
     <bean id="multipartResovler"
           class="org.springframework.web.multipart.commons.CommonsMultipartResolver">
           <!-- 上传文件大小上限，单位为字节(10MB) -->
           <property name="maxUploadSize">
               <value>10485760</value>
           </property>
           <!-- 请求的编码格式，必须和JSP的pageEncoding属性一致，以便正确读取表单的内容，默认为ISO-8859-1 -->           
           <property name="defaultEncoding">
               <value>UTF-8</value>
           </property>
     </bean>
     #+END_EXAMPLE

     #+BEGIN_EXAMPLE java
     /* MultipartFile实例包含如下方法
        byte[] getBytes() - 返回文件数据
        String getContentType() - 返回MIME类型，如image/jpeg等
        InputStream getInputStream() - 返回文件流
        String getName() - 返回表单中文件组件的属性name值
        String getOriginalFilename() - 返回上传的文件原名
        long getSize() - 返回文件的字节大小
        boolean isEmpty() - 是否有上传文件
        void transferTo(File dest) - 将上传文件保存到一个目标文件中
      */
     @PostMapping("/upload")
     public String upload(HttpServletRequest request, @RequestParam("file") MultipartFile file) throws Exception {
         if (!file.isEmpty()){
             // 上传路径
             String path = request.getServletContext().getRealPath("/images/");
             // 上传文件名
             String filename = file.getOriginalFilename();
             File filepath = new File(path, filename);
             
             // 若父路径不存在则创建
             if (!filepath.getParentFile().exists()) {
                  filepath.getParentFile().mkdirs();
             }
             
             // 将上传文件保存到目标路径中
             file.transferTo(new File(path + File.separator + filename));
             return "success";
         }
         return "error";
     }
     #+END_EXAMPLE
    
**** 文件下载
     #+BEGIN_EXAMPLE java
     @GetMapping("/download")
     public ResponseEntity<byte[]> download(HttpServletRequest request, @ReqeustParam("filename") String filename) {
         String path = request.getServletContext().getRealPath("/images/");
         File file = new File(path + File.separator + filename);
         HttpHeaders headers = new HttpHeaders();
         // 处理中文文件名的乱码问题
         String downloadFilename = new String(filename.getBytes("UTF-8"), "iso-8859-1");
         headers.setContentDispositionFormData("attachment", downloadFilename);
         // 设置MIME为application/octet-stream
         headers.setContentType(MediaType.APPLICATION_OCTET_STREAM);
         // 设置HTTP Status为201
         // 通过Apache Commons FileUpload组件的FileUtils将文件内容读取到byte[]中
         return new ResponseEntity<byte[]>(FileUtils.readFileToByteArray(file), headers, HttpStatus.CREATED);
     }
     #+END_EXAMPLE

*** 拦截器
    通过实现接口HandlerInterceptor或抽象类HandlerInterceptorAdapter的三个方法来完成
    - ~boolean preHandle(HttpServletRequest request, HttpServeltResponse response, Object handle)~
      该方法在请求处理之前依据它声明顺序依次被调用(链式调用)，若前一个方法返回 ~false~ 则后续Interceptor和Controller都不会再执行。
    - ~void postHandle(HttpServeltRequest request, HttpServeltResponse response, Object handle, ModelAndView mv)~
      该方法在请求处理之后渲染之前依据它声明顺序倒序依次被调用(链式调用)，因此可以在这个方法中对Controller处理后返回的ModelAndView实例进行操作。
    - ~void afterCompletion(HttpServeltRequest request, HttpServeltResponse response, Object handle, Exception exception)~
      该方法在DispatcherServlet渲染对应的视图后执行，主要用于资源清理。
    
    示例：
    #+BEGIN_EXAMPLE xml
    <!-- dispatcher-servlet.xml -->
    <mvc:interceptors>
        <mvc:interceptor>
            <!-- 拦截所有请求 -->
            <mvc:mapping path="/*"/>
            <!-- 使用Bean定义一个Interceptor -->
            <bean class="org.john.interceptor.AuthorizationInterceptor"/>
        </mvc:interceptor>
    </mvc:interceptors>
    #+END_EXAMPLE

    #+BEGIN_EXAMPLE java
    public class AuthorizationInterceptor implements HttpInterceptor {
        private static final String[] IGNORE_URI = {"/loginForm", "/login"};

        @Override
        public boolean preHandle(HttpServletRequest request, HttpServeltResponse response, Object handle) {
            boolean flag = false;
            
            String servletPath = request.getServletPath();
            for (String uri : IGNORE_URI){
                flag = IGNORE_URI.contains(uri);
                if (flag){
                    break;
                }
            }

            if (!flag){
                // 获取用户凭证
                Usre user = (User) request.getSession().getAttribute("user");
                if (user == null){
                    request.setAttribute("message", "请先登录");
                    request.getRequestDispatcher("loginForm").forward(request, response);
                }
                else{
                    flag = true;
                }
            }

            return flag;
        }
    }
    #+END_EXAMPLE

*** 货币/金额处理
    依赖:
    #+BEGIN_EXAMPLE xml
    <dependency>
        <groupId>org.joda</groupId>
        <artifactId>joda-money</artifactId>
    </dependency>
    <dependency>
        <groupId>org.jadira.usertype</groupId>
        <artifactId>usertype.core</artifactId>
    </dependency>
    #+END_EXAMPLE

* Spring

** 体系结构
   1) Core Container
      Spring容器会负责控制程序间的关系，而不是由程序直接控制。
      1) Beans
         作为顶层模块提供BeanFactory,由Spring管理的对象称为Bean。
         #+BEGIN_EXAMPLE java
         // 很少直接使用BeanFactory
         // 需要提供Spring所管理容器的详细配置信息
         BeanFactory beanFactory = new XmlBeanFactory(new FileSystemResource("/applicationContext.xml");
         #+END_EXAMPLE
      2) Core
         Spring框架的基本组成部分，包含IOC和DI。
      3) Context
         基于模块Beans和Core之间构建，用于读取定义和配置的任何对象的媒介。
         ApplicationContext为BeanFactory的子接口，作为常用的核心容器，不仅包含BeanFactory的所有功能，还添加国际化、资源访问、事件传播等方面的支持。
         #+BEGIN_EXAMPLE java
         // 创建方法1：通过ClassPathXmlApplicationContext
         // 从环境变量classPath中寻找指定的XML配置文件，并加载实例化ApplicationContext
         ApplicationContext applicationContext = new ClassPathXmlApplicationContext(String configLocation);

         // 创建方法2：通过FileSystemXmlApplicationContext
         // 从文件系统中寻找指定的XML配置文件，并加载实例化ApplicationContext
         ApplicationContext applicationContext = new FileSystemXmlApplicationContext(String configLocation);

         /* 在Web项目中ApplicationContext容器的实例化工作将由应用服务器来完成
            应用服务器会通过org.springframework.web.context.ContextLoaderListener来实例化ApplicationContext容器
            在web.xml中添加
            <context-param>
                <param-name>contextConfigLocation</param-name>
                <param-value>/applicationContext.xml</param-value>
            </context-param>
            <listener>
                <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
            </listener>
         */

         /* 从ApplicationContext容器中获取Bean实例
            @param name - 为Bean组件的id或name
            Object getBean(String name)
            
            @param requiredType - Bean实例所属类型
            <T> getBean(Class<T> requiredType)
         */
         #+END_EXAMPLE
         - 继承关系
           #+BEGIN_EXAMPLE txt
           BeanFactory <- HierarchicalBeanFactory <- ApplicationContext <- ConfigurableApplicationContext <-...<- ClassPathXmlApplicationContext
                       <\ ListableBeanFactory       </          Lifecycle </                                   <\ FileSystemXmlApplicationContext
                          ApplicationEventPublisher </                                                         <\ AnnotationConfigApplicaitonContext
                          MessageSource             </
           ResourceLoader <- ResourcePatternResolver</
           #+END_EXAMPLE
         - 手工实现root/child ApplicationContext
           #+BEGIN_EXAMPLE java
           ApplicationContext rootApplicationContext = new ClassPathXmlApplicationContext(new String[] {"applicationContext.xml"});
           ApplicationContext webApplicationContext = new ClassPathXmlApplicationContext(new String[] {"web.xml"}, rootApplicationContext);
           #+END_EXAMPLE
      4) SpEL
         Spring3.0增加的运行时查询和操作对象图的表达式语言。
   2) Data Access/Integration
      1) JDBC
         对Java的JDBC更高层次的抽象，简化开发工作。org.springframework.jdbc.core.JdbcTemplate
      2) ORM
         对JPA、JDO和Hibernate等提供集成支持。org.springframework.orm.[hibernate3.HibernateTemplate|jap.JpaTemplate]等
      3) OXM
         提供支持对象/XML映射的抽象层实现，如JAXB、Castor、XMLBeans、JiBX和Xstream。
      4) JMS
         对Java消息传递服务使用和产生的支持，位于模块Spring-message。
      5) Transaction
         提供事务管理。
   3) Web
      1) WebSocket
      2) Servlet
      3) Web
      4) Porlet
   4) Other
      1) AOP
      2) Aspects
         AOP框架。
      3) Instrumentation
      4) Messaging
      5) Test

   核心容器: BeanFactory 和 ApplicationContext

** 包分类说明
   - AOP
     - com.springsource.net.sf.cglib-x.x.x.jar
     - com.springsource.org.aopalliance-x.x.x.jar
     - com.springsource.org-aspectj.weaver
     - spring-aop-x.x.x.jar
     - spring-aspects-x.x.x.jar
   - IOC
     - spring-beans-x.x.x.jar
     - spring-context-x.x.x.jar
     - spring-core-x.x.x.jar
     - spring-expression-x.x.x.jar
   - JDBC
     - spring-jdbc-x.x.x.jar
     - spring-orm-x.x.x.jar
     - spring-tx-x.x.x.jar
   - Web
     - spring-web-x.x.x.jar
     - spring-webmvc-x.x.x.jar
** Bean的配置和实例化
   通过配置文件(XML或Properties文件)注册并管理Bean之间的依赖关系。
   
   Bean组件属性/子元素
   | 属性/子元素 | 说明                                                                                                     |
   |-------------+----------------------------------------------------------------------------------------------------------|
   | id          | Bean组件的唯一标识                                                                                       |
   | name        | 一个Bean组件可以拥有多个名称，多个名称间通过逗号分隔                                                     |
   | class       | 指定Bean对应的具体实现类，为全限定类名                                                                   |
   | scope       | 指定Bean实例的作用域，singleton(默认值),prototype,request,session, global Session,application和websocket |

*** Bean的3种实例化方式
    1) 构造方法
       Spring容器直接通过调用实现类的构造方法实例化对象。
       #+BEGIN_EXAMPLE java
       // Bean对应的实现类
       public class UserInfo{}
       
       // 使用Spring容器创建Bean实例
       ApplicationContext context = ClassPathXmlApplicationContext(contextConfigLocation);
       UserInfo userInfo = (UserInfo) context.getBean("useInfo");
       #+END_EXAMPLE
       #+BEGIN_EXAMPLE xml
       <bean id="userInfo" class="UserInfo"/>
       #+END_EXAMPLE
    2) 静态工厂
       Spring容器调用静态工厂的静态方法获取目标实现类的对象。
       #+BEGIN_EXAMPLE java
       // Bean对应的实现类
       public class UserInfo{}
       
       public static class StaticUserInfoFactory{
           public static UserInfo createBean(){
               return new UserInfo();
           }
       }

       // 使用Spring容器创建Bean实例
       ApplicationContext context = ClassPathXmlApplicationContext(contextConfigLocation);
       UserInfo userInfo = (UserInfo) context.getBean("userInfo");
       #+END_EXAMPLE
       #+BEGIN_EXAMPLE xml
       <bean id="userInfo" class="StaticUserInfoFactory" factory-method="createBean"/>
       #+END_EXAMPLE
    3) 实例工厂
       Spring容器先实例化实例工厂，然后再通过实例工厂创建目标实现类的对象。
       #+BEGIN_EXAMPLE java
       // Bean对应的实现类
       public class UserInfo{}
       
       public class UserInfoFactory{
           public UserInfo createBean(){
               return new UserInfo();
           }
       }
       // 使用Spring容器创建Bean实例
       ApplicationContext context = ClassPathXmlApplicationContext(contextConfigLocation);
       UserInfo userInfo = (UserInfo) context.getBean("userInfo");
       #+END_EXAMPLE
       #+BEGIN_EXAMPLE xml
       <bean id="userInfoFactory" class="UserInfoFactory"/>
       <bean id="userInfo" class="UserInfo" factory-bean="userinfofactory" factory-method="createBean"/>
       #+END_EXAMPLE

*** Bean的作用域
    1) singleton, Spring容器中最多只有一个实例，无论有多少个Bean引用它，始终指向同一个实例。
       用于无会话状态的Bean(Dao组件、Service组件)
       注意：默认情况下在Spring容器初始化时就会实例化作用域为singleton的Bean，并将实例存放到内部的Map中，后续从Map中直接获取。
    2) prototype, 每次通过Spring容器获取时，Spring容器都会创建一个全新的实例。
       用于需要保持会话状态的Bean(Struct2的Action类)
    3) request, 同一个HTTP请求中，每次通过Spring容器获取时将返回同一个实例；不在同一个HTTP请求中时则返回全新的实例。即实例仅在当前HTTP Request内有效。
    4) session, 对于同一个HTTP Session，每次通过Spring容器获取时将返回同一个实例。
    5) globalSession, 在一个全局的HTTP Session中，将返回同一个实例。仅对portlet上下文有效。(portlet现在已不怎么使用了)
    6) application, 为每个ServletContext对象创建一个实例，仅Web相关的ApplicationContext有效。
    7) websocket, 为每个websocket对象创建一个势力，仅Web相关的ApplicationContext有效。

*** Bean的生命周期
    Spring容器只能跟踪scope为singleton和prototype的Bean的生命周期。
    | 序号 | 流程操作                                                                                                                             |
    |------+--------------------------------------------------------------------------------------------------------------------------------------|
    |    1 | 通过构造方法实例化Bean                                                                                                               |
    |    2 | 通过依赖注入设置属性值                                                                                                               |
    |    3 | 若实现BeanNameAware接口，则调用setBeanName方法                                                                                       |
    |    4 | 若实现BeanFactoryAware接口，则调用setBeanFactory方法                                                                                 |
    |    5 | 若实现ApplicationContextAware接口，则调用setApplicationContext方法                                                                   |
    |    6 | 调用BeanPostProcessor的预初始化方法                                                                                                  |
    |    7 | 调用InitializingBean的afterProperties方法                                                                                            |
    |    8 | 若设置init-method属性，则调用其值指定的方法                                                                                          |
    |    9 | 调用BeanPostProcesser的初始化方法                                                                                                    |
    |   10 | 对于scope为singleton的Bean，则将准备就绪的Bean实例存放在Spring缓冲池中并返回给调用者。若scope为prototype则将Bean实例直接返回给调用者 |
    |   11 | 对于scope为singleton的Bean，则调用Disposable的destroy方法                                                                            |
    |   12 | 对于scope为singleton的Bean，若设置destroy-method则调用其值指定的方法                                                                 |

** Spring IoC/DI
   Spring IoC通过反射实习。
   IoC和DI只是从不同的角度描述同一个事物。
   - IoC(Inversion of Control, 控制反转)
     - 实例由Spring容器创建，而不是由实例的使用者来创建；
     - 程序间的关系由Spring容器来负责，而不是由调用者来直接控制。
   - DI(Dependency Injection, 依赖注入)
     - 由Spring容器将被依赖对象赋值给调用者的成员变量。

*** 基于XML的DI实现方式
    1) Setter Injection
       - 前提条件
         1) Bean类必须提供一个没有参数的构造方法
         2) Bean类必须为属性提供setter方法(通过 ~<property>~ 元素为每个属性注入值)
       - 示例
         #+BEGIN_EXAMPLE java
         public class UserInfo{}
         public class UserServiceImpl{
           private UserInfo userInfo;
           public void setUserInfo(userInfo){
               this.userInfo = userInfo;
           }
         }
         #+END_EXAMPLE
         通过Spring配置文件设置注入关系
         #+BEGIN_EXAMPLE xml
         <!-- applicationContext.xml -->
         <bean id="userInfoBean" class="UserInfo">
         <bean id="userDao" class="UserServiceImpl">
             <!-- 设置注入方式，name为调用者的成员变量名称，ref为被注入的Bean组件id -->
             <property name="userInfo" ref="userInfoBean"></property>
         </bean>
         #+END_EXAMPLE
    2) Constructor Injection
       - 前提条件
         1) Bean类必须提供有参数的构造方法(通过 ~<constructor-arg>~ 元素为构造方法的每个参数注入值)
       - 示例
         #+BEGIN_EXAMPLE java
         public class UserInfo{}
         public class UserServiceImpl{
           private UserInfo userInfo;
           private String name;
           public UserServiceImpl(UserInfo userInfo, String name){
               this.userInfo = userInfo;
               this.name = name;
           }
         }
         #+END_EXAMPLE
         通过Spring配置文件设置注入关系
         #+BEGIN_EXAMPLE xml
         <!-- applicationContext.xml -->
         <bean id="userInfoBean" class="UserInfo">
         <bean id="userDao" class="UserServiceImpl">
             <!-- 设置注入方式，name为调用者的成员变量名称，ref为被注入的Bean组件id -->
             <constructor-arg index="0" ref="userInfoBean"></constructor-arg>
             <constructor-arg index="1" value="john"></constructor-arg>
         </bean>
         #+END_EXAMPLE
    3) Interface Injection
       作为注入其他服务的接口，如JNDI数据源注入——由Tomcat或其他服务器中提供具体的JNDI数据源。
       - 示例
         #+BEGIN_EXAMPLE xml
         <bean id="dataSource" class="org.springframework.jndi.JndiObjectFactoryBean">
           <property name="jndiName">
             <value>java:comp/env/jdbc/mybatis</value>
           </property>
         </bean>
         #+END_EXAMPLE

*** 基于Annotation的DI实现方式
    | Annotation  | 说明                                                                                                                                    |
    |-------------+-----------------------------------------------------------------------------------------------------------------------------------------|
    | @Component  | 表示该类为一个Bean                                                                                                                      |
    | @Repository | 用于将数据访问层DAO标识为一个Bean                                                                                                       |
    | @Service    | 用于将业务层Service标识为一个Bean                                                                                                       |
    | @Controller | 用于将控制层Controller标识为一个Bean                                                                                                    |
    | @Autowired  | 用于对Bean的属性变量、setter方法和构造方法进行标记，配合对应的注解处理器和Bean的类型完成自动装配                                        |
    | @Resource   | 用于对Bean的属性变量、setter方法和构造方法进行标记，设置属性name时则通过Bean的id或name完成装配，设置属性type时则通过Bean的class完成装配 |
    | @Qualifier  | 和@Autowired配合使用，通过Bean的id或name实现自动装配                                                                                    |

    #+BEGIN_EXAMPLE java
    @Repository("userDao")
    public class UserDaoImpl implements UserDao{}
    @Service("userService")
    public class UserServiceImpl implements UserService{
        @Resource(name="userDao")
        private UserDao userDao;
    }
    @Controller("userController")
    public class UserControllerImpl{
        @Resource(name="userService")
        private UserService userService;
    }
    #+END_EXAMPLE
    1) 通过 ~<context:annotation-config>~ 启用Annotation装配
       Annotation仅标识依赖关系，以便Spring容器在作Bean实例化时实现依赖注入，但要手工注册Bean信息。
       #+BEGIN_EXAMPLE xml
       <!-- applicationContext.xml -->
       <context:annotation-config/>
       <bean id="userDao" class="UserDaoImpl"/>
       <bean id="userService" class="UserServiceImpl"/>
       <bean id="userController" class="UserControllerImpl"/>
       #+END_EXAMPLE
    2) 通过 ~<context:component-scan>~ 启用Annotation装配
       自动扫描注册Bean信息。
       #+BEGIN_EXAMPLE xml
       <!-- applicationContext.xml -->
       <context:component-scan base-package="org.test"/>
       #+END_EXAMPLE
    3) 通过属性 ~autowire=""~ 启用Annotation装配
       - 值
         - default 由 ~<beans>~ 的属性default-autowire的值决定
         - byName 根据Bean的id值装配
         - byType 根据Bean的class值装配
         - constructor 根据构造方法参数的数据类型，进行byType模式的自动装配
         - no 不使用自动装配，必须使用ref元素定义
       - 注意：成员变量必须提供setter方法，否则无法实现。
       - 示例
       #+BEGIN_EXAMPLE java
       @Repository("userDao")
       public class UserDaoImpl implements UserDao{}
       @Service("userService")
       public class UserServiceImpl implements UserService{
           @Autowired
           private UserDao userDao;
           public void setUserDao(UserDao userDao){
               this.userDao = userDao;
           }
       }
       @Controller("userController")
       public class UserControllerImpl{
           @Autowired
           private UserService userService;
           public void setUserService(UserService userService){
               this.userService = userService;
           }
       }
       #+END_EXAMPLE
       #+BEGIN_EXAMPLE xml
       <!-- applicationContext.xml -->
       <bean id="userDao" class="UserDaoImpl" autowire="byType"/>
       <bean id="userService" class="UserServiceImpl" autowire="byType"/>
       <bean id="userController" class="UserControllerImpl" autowire="byType"/>
       #+END_EXAMPLE

** Spring AOP
  
*** 术语
    - Aspect(切面), 封装用于横向插入系统功能(如日志、事任等)的类。
    - Joinpoint(链接点), 程序运行过程中的函数/方法调用。
    - Pointcut(切入点), Aspect与程序运行过程中的交叉点，就是Aspect起作用的Joinpoint。
    - Advice(通知/增强处理), 在Pointcut中执行的具体的Aspect下的方法。
    - Target Object(目标对象), 被通知或被增强的对象，若采用动态AOP实现，那么Target Object即为一个被代理对象。
    - Proxy(代理), 将Advice应用到Target Object后，被动态创建出来的对象。
    - Weaving(织入), 将Advice应用到Target Object时生成Proxy的过程。
    - Introduction(引入), 为现有类型声明额外的方法和属性。
  
*** 动态代理
    1) JDK动态代理
       通过调用 ~java.lang.reflect.Proxy~ 的方法 ~newProxyInstance~ 来创建代理对象实现的。
       - 限制：
         1) Target Object 必须实现业务接口才能使用JDK动态代理。
       - 示例
         #+BEGIN_EXAMPLE java
         // 定义代理类
         import java.lang.reflect.Proxy;
         import java.lang.reflect.Method;
         import java.lang.reflect.InvocationHandler;

         public class JdkProxy implements InvocationHandler{
             // 目标对象
             private UserDao userDao;

             // 创建代理类
             public UserDao createProxy(UserDao userDao){
                 this.userDao = userDao;
                 // 1. 获取类加载器
                 ClassLoader classLoader = JdkProxy.class.getClassLoader();
                 // 2. 获取目标对象实现的所有接口
                 Class<?> interfaces = userDao.getClass().getInterfaces();
                 // 3. 生成代理
                 Object proxy = Proxy.newProxyInstance(classLoader, interfaces, this);

                 return (UserDao) proxy;
             }

             /* 调用代理类的任何方法时实质上都是调用该方法，然后我们在该方法中通过反射调用目标对象的方法
              * @param Object proxy - 代理对象
              * @param Method method - 调用的方法信息
              * @param Object[] args - 入参
              * @returns Object
              */
             @Override
             public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
                 // 前置增强
                 System.out.println("");

                 // 调用目标对象的方法
                 Object ret = method.invoke(this.userDao, args);

                 // 后置增强
                 System.out.println("");

                 return ret;
             }
         }
         #+END_EXAMPLE
    2) CGLIB动态代理
       CGLIB(Code Generation Library)是一个采用底层字节码技术的代码生成包，对指定的目标类生成一个子类，从而对子类实现增强。
       - 示例
         #+BEGIN_EXAMPLE java
         public class CglibProxy implements MethodInterceptor {
             public Object createProxy(UserDao userDao){
                 // 创建动态类对象
                 Enhancer enhancer = new Enhancer();
                 enhancer.setSuperClass(userDao.getClass());
                 enhanser.setCallback(this);
                 return enhanser.create();
             }

             /*
              * @param Object proxy - 动态类对象
              * @param Method method - 所调用的方法信息
              * @param Object[] args - 入参
              * @param MethodProxy methodProxy - 动态类对象的方法对象，用于执行父类的方法
              */
             public Object intercept(Object proxy, Method method, Object[] args, MethodProxy methodProxy) throws Throwable {
                 // 前置增强
                 System.out.println("");

                 // 调用目标对象的方法
                 Object ret = methodProxy.invokeSuper(proxy, args);

                 // 后置增强
                 System.out.println("");

                 return ret;
             }
         }
         #+END_EXAMPLE

*** Advise类型
    1) org.aopalliance.intercept.MethodInterceptor - 环绕通知
       在目标方法执行前后实施增强，如日志、事务等功能
    2) org.aopalliance.intercept.MethodBeforeAdvice - 前置通知
       在目标方法执行前实施增强，如权限管理等
    3) org.aopalliance.intercept.MethodReturningAdvice - 后置通知
       在目标方法执行后实施增强，如关闭流、上传文件、删除临时文件等
    4) org.aopalliance.intercept.ThrowsAdvice - 异常抛出通知
       在方法抛出异常后实施增强，如异常处理日志等
    5) org.aopalliance.intercept.IntroductionInterceptor - 引介通知
       在目标类中添加新的方法和属性，用于修改老版本的程序

*** 通过 ~<bean class="org.springframework.aop.framework.ProxyFactoryBean">~ 构建AOP
    ProxyFactoryBean作为FactoryBean的实现类，负责为其它Bean创建代理实例，作为Spring中床将AOP代理的基本方式。
    - 参数
      | 属性             | 说明                                                                |
      |------------------+---------------------------------------------------------------------|
      | target           | 目标对象                                                            |
      | proxyInterfaces  | 代理实现的接口，若实现多个接口则使用<list><value></value>...</list> |
      | proxyTargetClass | 是对类代理(底层使用GCLIB)，还是对接口代理(底层使用JDK Proxy)        |
      | interceptorNames | 需要织入的目标Advice                                                |
      | singleton        | 代理是否为单例，默认为true                                          |
      | optimize         | true时底层采用GCLIB                                                 |
    - 示例
      #+BEGIN_EXAMPLE xml
      <!-- applicationContext.xml -->
      <context:component-scan base-package="org.proxy.experiment">
      <!-- 然后通过 applicationContext.getBean("userDaoProxy") 即可获取代理实例 -->
      <bean id="userDaoProxy" class="org.springframeowork.aop.framework.ProxyFactoryBean">
          <property name="target" value="userDaoImpl"></property>
          <property name="proxyInterfaces" value="UserDao"></property>
          <property name="proxyTargetClass" value="true"></property>
          <property name="interceptorNames" value="myAspect"></property>
      </bean>
      #+END_EXAMPLE

*** 通过AspectJ构建AOP
    AspectJ是一个基于Java的AOP框架，Spring2.0+引入对AspectJ的支持。
    
**** 基于XML声明式
     #+BEGIN_EXAMPLE
     <aop:config>
        - attributes
        - child-element
          - <aop:pointcut>, 全局切入点
          - <aop:advisor>, 通知器
          - <aop:aspect>
            - attributes
            - child-element
              - <aop:pointcut>, 切入点
              - <aop:before>, 前置通知
              - <aop:returning>, 后置通知
              - <aop:around>, 环绕通知
              - <aop:throwing>, 异常通知
              - <aop:after>, 最终通知
              - <aop:declare-parents>, 引介通知
     #+END_EXAMPLE

     #+BEGIN_EXAMPLE xml
     <!-- applicationContext.xml -->
     <bean id="myAspect" class="org.john.MyAspect">
         <aop:config>
             <!-- 配置通知器 -->
             <aop:aspect id="aspect" ref="myAspect">
                 <!-- 切入点表达式：execution(modifier-pattern? ret-type-pattern declaring-type-pattern? name-pattern(param-pattern) throws-pattern?)
                      * 表示任意
                   -->
                 <aop:pointcut id="myPointCut" expression="execution(* org.john.*.*(..))" />
                 <!-- 通知组件的属性：
                      - pointcut, 设置独立的pointcut expression
                      - pointcut-ref, 引用<aop:pointcut>
                      - method, 设置用于作为Advise的Aspect类的方法名
                      - throwing, 设置用于存储异常对象的形参名称，供Advise访问异常对象
                      - returning, 设置用于存储返回值的形参名称，供Advise访问返回信息
                   -->
                 <aop:before method="myBefore" pointcut-ref="myPointCut"/>
                 <aop:returning method="myAfterReturning" returning="returnVal" pointcut-ref="myPointCut"/>
                 <aop:around method="myAround" pointcut-ref="myPointCut"/>
                 <aop:throwing method="myThrowing" throwing="e" pointcut-ref="myPointCut"/>
                 <aop:after method="myAfter" pointcut-ref="myPointCut"/>
             </aop:aspect>
         </aop:config>
     </bean>
     #+END_EXAMPLE
     #+BEGIN_EXAMPLE java
     public class MyAspect{
         public void myBefore(JoinPoint joinPoint){
             // 目标对象
             Object targetObject = joinPoint.getTarget();
             // 目标方法
             Method method = joinPoint.getSignature();
         }

         public void myAfterRetuning(JoinPoint joinPoint, Object returnVal){
             // 目标对象
             Object targetObject = joinPoint.getTarget();
             // 目标方法
             Method method = joinPoint.getSignature();
         }
         
         public Object myAround(ProceedingJoinPoint proceedingJoinPoint) throws Throwable {
             // 前置
             
             Object ret = proceedingJoinPoint.procee();

             // 后置

             return ret;
         }
         
         public void myThrowing(JoinPoint joinPoint, Throwable e){
         }

         public void myAfter(){
         }
     }
     #+END_EXAMPLE

**** 基于Annotation声明式
     #+BEGIN_EXAMPLE xml
     <!-- applicationContext.xml -->
     <context:component-scan base-package="org.john.test"/>
     <!-- 启动基于注解的AspectJ支持 -->
     <aop:aspectj-autoproxy>
     #+END_EXAMPLE
     #+BEGIN_EXAMPLE java
     @Component
     @Aspect
     public class MyAspect{
         // 通过一个私有方法定义Pointcut表达式
         // 而Pointcut的id为方法函数名加形参列表
         @Pointcut("execution(* org.john.*.*(..))")
         private void myPointCut(){}

         @Before("myPointCut()")
         public void myBefore(JoinPoint joinPoint){
             // 目标对象
             Object targetObject = joinPoint.getTarget();
             // 目标方法
             Method method = joinPoint.getSignature();
         }

         @AfterReturning(value="myPointCut()", returning="returnVal")
         public void myAfterRetuning(JoinPoint joinPoint, Object returnVal){
             // 目标对象
             Object targetObject = joinPoint.getTarget();
             // 目标方法
             Method method = joinPoint.getSignature();
         }

         @Around("myPointCut()")
         public Object myAround(ProceedingJoinPoint proceedingJoinPoint) throws Throwable {
             // 前置
             
             Object ret = proceedingJoinPoint.procee();

             // 后置

             return ret;
         }
         
         @Throwing(value="myPointCut()", throwing="e")
         public void myThrowing(JoinPoint joinPoint, Throwable e){
         }

         @After("myPointCut()")
         public void myAfter(){
         }
     }
     #+END_EXAMPLE
     
* Spring Boot
  通过[[https://start.spring.io/][Spring Initializr]]初始化项目。

* TODO QA
  1) Eclipse 中的 Dynamic Web Module Version 与 Application Server 搭配
     Dynamic Web Module Version 决定Java动态网站依赖的包版本，因此必须和Application Server对应才能成功运行。
     - 映射表
       | Dynamic Web Module Version | Application Server |
       |----------------------------+--------------------|
       |                        2.4 |                5.5 |
       |                        2.5 |                6.0 |
       |                        3.0 |                7.0 |
       |                        3.1 |                8.5 |
       |                        4.0 |                9.0 |
     - 通过 ~项目目录/.setting/org.eclipse.wst.common.project.facet.core.xml~ 修改 Dynamic Web Module Version
       #+BEGIN_EXAMPLE xml
       <?xml version="1.0" encoding="UTF-8"?>
       <faceted-project>
         <fixed facet="wst.jsdt.web"/>
         <installed facet="java" version="1.5"/>
         <installed facet="jst.web" version="3.1"/> <!-- 修改为对应的Dynamic Web Module Version，然后重启Tomcat即可 -->
         <installed facet="wst.jsdt.web" version="1.0"/>
       </faceted-project>
       #+END_EXAMPLE
  2) URI和URL的区别？


